### PR TITLE
Update ruleset.xml

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by frederic34** [comment]
@eldy can this fix stickler?

**Comment by eldy** [comment]
I added this because this rule it generated a warning in travis that seems useless.
I do not experience trouble with sticker. You do ?

**Comment by frederic34** [comment]
@eldy stickler is failing since some days
Sélection_014

**Comment by eldy** [comment]
The error in stickler is not relative to this. PR not required.

**Pull request closed without merging**
