### PR TITLE
FIX: Setting supplier as client when accept a supplier proposal

### PR DESCRIPTION
**Pull request by fmarcet**
If supplier proposal is signed, set supplier as client.

### CODE REVIEW

**Comment by BebZ** [comment]
WHy ? a supplier proposal "request" means the supplier keeps being a supplier, he is requested to make a proposal to his client. It is not the client tht makes the proposal to the supplier...
Did I get it wrong ?

**Comment by aljawaid** [comment]
@BebZ I was thinking the same lol

I thought the order flow would be:
supplier proposal>supplier order>supplier invoice

unless i'm confused on supplier and customer.

**Comment by fmarcet** [comment]
Before the pull request, when a supplier proposal is closed, the supplier was marked as customer. And that didn't make much sense.
Now if you close a supplier proposal, the supplier is still a supplier. Maybe the title of the pull request was not entirely clear...

**Comment by aljawaid** [comment]
@fmarcet thanks for clarifying that, it makes more sense now.

**Comment by BebZ** [comment]
i should have read code first :) sorry for bothering ;) and thx

**Pull request merged**
