### PR TITLE
3.8.3 product image

### PR DESCRIPTION
**Pull request by centoasa**
A product image, near the barcode of product

### CODE REVIEW

**Comment by eldy** [comment]
Merge into develop from backport branch ?
Can't see any change new in develop.

**Comment by centoasa** [comment]
sorry, I write in wrong section. My was only a suggestion.

**Comment by eldy** [comment]
With 3.9, product image is visible near barcode on top banner of card

**Comment by centoasa** [comment]
Can I know the ETA of 3.9?

**Pull request closed without merging**
