### PR TITLE
Add userid on bill line (for tracking feature)

### PR DESCRIPTION
**Pull request by defrance**

### CODE REVIEW

**Comment by eldy** [comment]
Is user that create line ? that modify line ? else ?

**Comment by defrance** [comment]
In my vision it's the user associated to the line, by default the creator of line. The main goal is to associate
a product to an user for tracking feature (sell, job made, ...)

**Comment by eldy** [comment]
I try to normalize name of fields that store users id.
Can you use same convention than he one usd for llx_facture with 4.0 so
  fk_user_author  or  fk_user_modif   or fk_user_valid ...
depending of goal.

**Comment by defrance** [comment]
OK So introduce 3 fk_user key :+1: 
fk_user_author for creating line user
fk_user_modif for editing line user
fk_user_associate for line associate to a specific user for some additionnal tracking feature

**Comment by defrance** [comment]
UP change made since one month...

**Comment by BebZ** [comment]
Good idea. And what will be the data entered in line when you convert an order in an invoice ? 
The fk user that created bill line or the fk user that converted the order in invoice ?
Is it streamlined with the Propal also ?

**Comment by defrance** [comment]
UP Change made since 2 month ...

**Comment by eldy** [comment]
Can you split your PR in 2.
fk_user_author for creating line user
fk_user_modif for editing line user
is ok for me as this fields are generic features we must normalie.

Another PR for fk_user_associate because I still didn't find what is the current feature of dolibarr that ill use it (if goal is a need for an external module, field must be provided by external module too and not be by default into dolibarr)

**Comment by defrance** [comment]
the fk_user_associate is exactly for an external module i planned to create 
in this case, should i do add field on native table or create an additionnal table specificly?

**Comment by eldy** [comment]
For your external module need, there is 2 school:
You can ask your module to create an extrafields when module is activated (for example the external module ecotax works like this) 
Second solution: you can add your own table with same id than in dolibarr table and updated by trigger create and update and make visible into view form using hooks (for example the external module dolimed works like this).
Depending on how many fields you have to add, context, you may prefer one or other solution.

**Comment by defrance** [comment]
Thank's for this precious advice, i think first solution is better for perf with a table who contains many lines as facturedet...

**Pull request merged**
