### PR TITLE
 FIX Dolibarr#29028 Md-theme - Login is on other icons

### PR DESCRIPTION
**Pull request by aspangaro**
Without patch

image

With patch

image

### CODE REVIEW

**Comment by eldy** [comment]
I do not experience trouble with current v19
image

Did your clear CSS cache of your browser ?

**Comment by aspangaro** [comment]
You don't see the problem because you have a photo or you use the gravatar module.

The problem is only when we have no photo (empty($user->photo))

**Comment by eldy** [comment]
With no photo and no gravatar.
image

also i see no diff in code to explain what you got.

I will test with your change to see what happen on my side...

**Comment by aspangaro** [comment]
In the linked issue, several user are the same problem. I'm going to try again with a new clean installation

**Comment by sonikf** [comment]
I can confirm the bug exists also in a clean 20.0.0-alpha installation and occurs when username is visible.
Tested in Ubuntu 22.04
Screen resolution 1920x1080, 1024x768
Latest Google Chrome and Firefox
Cleaning browser cache doesn't fix this
@aspangaro fix works

**Comment by eldy** [comment]
> and occurs when username is visible.

What do you mean with "and occurs when username is visible". Do you use a hidden option to have the user name visible ?

**Comment by eldy** [comment]
Can you try commit 330d20813ebd7c462f48a796293cd0efdde33740 instead.
I think it is a better fix because trouble is in CSS and not in HTML: HTML must be the same for eldy and md theme and difference must be into CSS file.
Also the trouble existed also in eldy theme when user has no photo and username is long.

**Comment by sonikf** [comment]
It works!

**Pull request closed without merging**
