### PR TITLE
Try to improve stock display for all stock increase/decrease options

### PR DESCRIPTION
**Pull request by frederic34**
:warning:  WIP

### CODE REVIEW

**Comment by rdoursenaud** [comment]
@BebZ @eldy Being able to ventilate stock while the order is not at least partially received sounds like a bug to me. No?

**Comment by BebZ** [comment]
Hey Raphael, there is no bug i think. Supplier Order needs to follow workflow : validated>approved> pass order (ordered) to begin dispatch in stocks. So status passesin "waiting reception" ("attente reception") to be able to ventilate to stocks. 
Status "waiting reception" should change in "partially delivered" automatically as soon as some products have been ventilated  and also automatically change in "totally delivered" as soon as all products have been ventilated, maybe this could be an improvement ;)

**Comment by rdoursenaud** [comment]
@BebZ Yup, your way makes even more sense. Opened a Doliforge task: https://doliforge.org/goto?key=task&val=1700&group_id=144
Thanks!

**Comment by BebZ** [comment]
I hope the guy developping it will pay attention to the experimental module batch numbers and expiry dates (DLC / DLUO) and not break it :)

Even more sense would be to put on each line a date Y and qty X of products on backorder 
if the supplier tells on the delivery receipt when the rest of the products can be delivred... 
Then on the stock's tab of product card it would say Xqty of products can be deliverd on date Y.
Okay, okay I stop asking for more... Thanks for the forge :)

**Pull request merged**
