### PR TITLE
Fix shipping is not a delivery_note (is sub module of shipping)

### PR DESCRIPTION
**Pull request by fappels**
Related to #28452, #28512 and #28511

### CODE REVIEW

**Comment by mdeweerd** [comment]
To fix phan, update the list of modules in dev/tools/phan/config_*.php .
To fix phpunit, update the list of modules in test/phpunit/CommonClass.class.php .

**Comment by fappels** [comment]
For info screen dump of a 'delivery note'

2024-03-12 - 11_47_50 - Delivery

**Comment by fappels** [comment]
@mdeweerd not sure why phan still failing

**Comment by mdeweerd** [comment]
The remaining issue was introduced in develop - probably a "use Stripe..." in conf.class.php that is not useful to the code in conf.class.php.  #27998 .

**Pull request merged**
