### PR TITLE
NEW : add constant TICKETS_NO_COMPANY_ON_FORM

### PR DESCRIPTION
**Pull request by altairis-tof**
this constant avoid to select a company when creating a ticket; useful for internal usage.

### CODE REVIEW

**Comment by altairis-tof** [comment]
Travis problem here

**Comment by eldy** [comment]
@altairis-tof Don't know why, i can't update the pr to use last version of branch develop. Can you try to pull and repush it or make a minor change in comment to force such update ?

**Comment by altairis-tof** [comment]
salut @eldy, il reste une erreur bizarre qui ne vient pas de moi.
image

**Comment by eldy** [comment]
> salut @eldy, il reste une erreur bizarre qui ne vient pas de moi

It seems i can't update the PR with last develop branch myself. Can you retry a pull/push ? (should be fixed after that)

**Comment by altairis-tof** [comment]
Yes, PR ready for merge @eldy

**Pull request merged**
