### PR TITLE
Last version of JQuery 1.12 and DataTables Componenent with working

### PR DESCRIPTION
**Pull request by FHenry**
Last version of JQuery 1.12 and DataTables Componenent with working export and column visibility

### CODE REVIEW

**Comment by eldy** [comment]
It seems you not only updated datatables but also introduced new external libraries. We must reduce the number of external libraries because each time a lib is upgraded all other are not compatible and it breaks a lot of thing. Also it brings a lot of legal issue about license (font and pdf for exemple often used non free component or data). And we must not include minified version .min.js file without includind the original version.

It may be better to restrict feature than providing too much external component and exotic dependencies. We can still provide them as addon into external module.

What happened if we don't include this 3 one ?
jszip
pdf_make
vfs_font

 Why aren't they part of datatable ?

**Comment by FHenry** [comment]
PDF, Excel, Print and may be other export will not work. For me this is the main interesting feature of datable.

**Comment by eldy** [comment]
So jszip must be store into its own dir  includes/jszip (and not into dir dedicated to project jstz dedicated to timezone management) and both minified and not minified version must be included.

vsf_font seems to be provided with pdfmake project, so only one dir is required, the one with js files provided by pdfmake project. We trust the all in one package of pdfmake project that contains this: https://cdnjs.com/libraries/pdfmake, so one dir only for 1 dependency).

Can you fix this 2 comments ?

**Comment by FHenry** [comment]
It make sounds to me. I've just update the PR following your recommendation

**Comment by defrance** [comment]
pdf, excel and print associated to datatables is for me not a good way. I have use it for a time with myList (using datatables and flash element), now i prefer use native dolibarr export and pdf generation
Think the good way is to use the sames tools for the same feature (export, print, pdf...)

**Comment by eldy** [comment]
It is clear that if this is using flash, we must just not include this into dolibarr standard code. 
It is also clear that having a standard csv and pdf export will be soon available by default with dolibarr. I am just waiting the the "mass action" feature introduce into invoice list as a demo is generalized to othe code part. In future, we will see into the mass action button something like "Extract selected list into CSV"

**Pull request merged**
