### PR TITLE
token was not refreshing

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by frederic34** [comment]
@fboitel do you have the same problem with smtps ?

**Comment by fboitel** [comment]
What do you mean by "Not refreshing"? Is it about the expiration of the token or you mean the token doesn't update on mail module when you update it?

**Comment by frederic34** [comment]
If you just send mail, token is not updating when expired

image

with changes made here, it auto update (for swiftmailer)

**Comment by fboitel** [comment]
I get it, indeed, with smtp you have to regenerate manually the token once it expires. I will update this shortly, inspiring by you solution. Thanks for the work !

**Pull request merged**
