### PR TITLE
NEW #23232 : Export fec with documents as zip

### PR DESCRIPTION
**Pull request by rycks**
# NEW|New accounting export file

First step for that export file format (zip include FEC + PDF)  (please check and make some tests with your accounters)

### CODE REVIEW

**Comment by aspangaro** [comment]
Thanks @rycks but we (Progiseize / OpenDSI) have a different implementation of this function, we proposed to generate a zip file like an option of a format, not a new accounting export format.

The first format is Quadra with this PR (See pictures) : https://github.com/Dolibarr/dolibarr/pull/23209
The FEC format is already ready on our side but not posted

**Comment by aspangaro** [comment]
The other PR having been accepted for Quadra, I will close your PR Eric and I will push the file for the FEC format next week.

Remaining at your disposal to exchange if you wish ;)

**Comment by rycks** [comment]
ONE year later i was a little bit surprised dolibarr seemd to not make FEC+ exports as ZIP file with all data included i'm wrong ?

I'm sorry @aspangaro but that's an example of a bad intervention against a contribution: you make a PR for quadra ... ok but quadra is not FEC and if last year my PR had been included the problem for all people with dolibarr 18 would have been fixed : we could send FEC files to our accounters experts

"my" PR will not fight againts "your" contribution : nobody make a PR for FEC+ZIP during 2023 no ?

**Comment by rycks** [comment]
note -> https://github.com/Dolibarr/dolibarr/pull/26192

**Pull request closed without merging**
