### PR TITLE
fix wrong buy price update (confusion between entity and npr !)

### PR DESCRIPTION
**Pull request by altairis-tof**
and i hope a lot there is not the same problem elsewhere because entity is kind of important in dolibarr foreign keys... (yes my supplier prices database is very corrupted and i'm as well irritated)

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Pretty big mistake here !
The wrong code has been introduced at b2b0d1616defca62e833381cbcbe95ec15991f6e
As we can see (Thanks to tags), all installs since 3.4.0 are affected.
Unfortunately, these queries aren't logged (timestamped) so I don't think we can cook a database fix.

**Comment by altairis-tof** [comment]
maybe we can update the product_fournisseur_price table to set entity to 1 if module multicompany is not active ?

**Comment by rdoursenaud** [comment]
@altairis-fr Yes, that would fix entity but not info_bits.

Another possibility I just thought of :
- entity should never be 0 in this table
- info_bits is 0 most of the time

So, swap entity and info_bits values for entries where entity is 0.
Better yet, swap entity and info_bits for all entries after the first with entity is 0.
What do you think about that ?

**Comment by altairis-tof** [comment]
your solution would work except for the case of npr is used ; in this case, entity will not be equal to 0 so the line will not be corrected. if legal npr values are 0 or 1, it will not be a problem except if entity should be greater than 1 (multi-company).

**Pull request merged**
