### PR TITLE
Add module accountancy expert in auguria menu

### PR DESCRIPTION
**Pull request by aspangaro**

### CODE REVIEW

**Comment by defrance** [comment]
not the good way, better to add menu description on module files (modAccountancy...)

**Comment by aspangaro** [comment]
Hi Charles,

I know but it's only the simply way to integrate a dynamic menu (journal by
bank account).

We have already talk about this problem & the solution but it's not my
programming level. I'm a newbie !

Le dimanche 4 janvier 2015, BENKE Charles notifications@github.com a
écrit :

> not the good way, better to add menu description on module files
> (modAccountancy...)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/2220#issuecomment-68632817.

## 

Alexandre SPANGARO
Mobile : +33 6 42 26 64 73

**Comment by defrance** [comment]
define menu on description module file is not a complex programming level
propose to explain it for one or two menu.
never good to stay newbie ;-)

**Comment by aspangaro** [comment]
I program the menu in the module but the problem in core, it's dynamic menu needed to show journal by bank account (Doesn't exist in module). After we discuss, I try to program it few months ago but sorry It's under my knowledges.

Maybe in final step, for the moment, the core of accountancy need debug for the 3.7 final.

Thanks for your help ;)

**Pull request merged**
