### PR TITLE
NEW : add hidden conf to display generated bills on fourn bills list

### PR DESCRIPTION
**Pull request by atm-josselin**
Fix : Add a hidden conf to see mass generated files on the list of bills fourn

### CODE REVIEW

**Comment by eldy** [comment]
Can you push this on develop ?

**Comment by atm-josselin** [comment]
Yes, but we also need this in 8.0

**Comment by eldy** [comment]
Only bug fix of existing features are allowed into a v8.
You must manage yourself your own branch if you need to backport features on old versions

**Comment by atm-josselin** [comment]
This hidden conf would have standardize the list of providers' bills list because this area is available in lists of customers' bills

**Pull request closed without merging**
