### PR TITLE
FIX : wrong file path for user documents

### PR DESCRIPTION
**Pull request by atm-gauthier**

### CODE REVIEW

**Comment by hregis** [comment]
@atm-gauthier @eldy 
I do not think we should use "multidir_output" for users because there is only one directory "users" at the root of the directory "documents" for all entities!

**Comment by atm-gauthier** [comment]
Hello @hregis, that's wrong, in my Dolibarr 7.0 i also have "users" folder in other entities than main.

**Comment by hregis** [comment]
@atm-gauthier 
without transverse mode ? you can try with transverse mode ?

**Comment by atm-gauthier** [comment]
@hregis if i revert my modifications it never works in other entites than first, no matter if transverse mode in on or off.
It's impossible to upload or download a file

**Comment by eldy** [comment]
I confirm. Without patch, no way to see/upload a file on user card except if we are on entity 1.
But with the patch, it seems each document is visible in the uploaded entity only. 

The question is what do we want. What are the specification.
1) Do we want to have one dir per user so one document dir. It means a document uploaded on company 1 is also on other companies.
2) Or do we want to have uploaded doc specific to each company ? 

I pushed a fix that make thing coherent. Behaviour is now 1, if we want behaviour 2, we need patch of atm-gauthier

**Pull request closed without merging**
