### PR TITLE
NEW : Add constant to show only the products in stock in TakePos

### PR DESCRIPTION
**Pull request by altairis-melina**
Add constant TAKEPOS_PRODUCT_IN_STOCK

The products in stock

image

### CODE REVIEW

**Comment by altairis-tof** [comment]
@altairis-melina ta PR a été rejetée par Travis à cause de : 
Found non escaped string in building of a sql request (case 3) in takepos/ajax/ajax.php: $sql .= ' AND fk_entrepot ='.$conf-">global->{'CASHDESK_ID_WAREHOUSE'.$_SESSION[ - Bad."
Il faudrait mettre en ligne 136 :  `$sql .= " AND fk_entrepot = '" . $db->escape($conf->global->{'CASHDESK_ID_WAREHOUSE'.$_SESSION['takeposterminal']}) . "'";`

**Comment by altairis-tof** [comment]
@eldy we do not understand Travis problem ;)

**Comment by eldy** [comment]
Fk_entrepot etant un id, il faut mettre
...fk_entrepot = ".((int) $var)
No need to use the ' and the escape that must be used for sql string. Forcing with cast in int is enough.

**Comment by altairis-melina** [comment]
@eldy Cast is done

**Comment by altairis-melina** [comment]
@eldy I put back escape because of Travis

**Comment by altairis-tof** [comment]
@eldy Travis is very annoying : "Failed asserting that false is true."

**Comment by eldy** [comment]
Travis is annoying but travis is right. ;-) 
Do
`$sql .= " AND fk_entrepot = " . ((int) getDolGlobalInt('CASHDESK_ID_WAREHOUSE'.$_SESSION['takeposterminal']));`

sql string must be forged using ", the ' is reserved for sql string, and a comparison with an int field must not use ' and avec the var casted into int.

**Comment by altairis-tof** [comment]
@altairis-melina : please make the requested change so the PR may be merged.
and don't forget to add fix we've done yesterday

**Comment by altairis-tof** [comment]
@eldy Melina did what you said but Travis is still annoying us; how do you think we can definitively fix this ?

> Found non escaped string in building of a sql request (case 3) in takepos/ajax/ajax.php: $sql .= " AND ps.fk_entrepot = ".((int) getDolGlobalInt('CASHDESK_ID_WAREHOUSE'.$_SESSION[ - Bad.
> Failed asserting that false is true.

**Comment by altairis-tof** [comment]
@altairis-melina despite of what @eldy wrote, maybe you can try to use single quotes on the line like everywhere else inside this sql statement forge.

**Comment by altairis-tof** [comment]
unless you'll have to use double quotes everywhere... please try the previous solution before this one.

**Comment by eldy** [comment]
You have to replace in
takepos/ajax/ajax.php:

 $sql .= ' AND ps.fk_entrepot = '
Into
$sql .= " AND ps.fk_entrepot = "

Don't forget, when forging a sql string: " must be used for php string, ' must be used for sql string

**Comment by altairis-tof** [comment]
@eldy this one seems to be ok too

**Comment by altairis-tof** [comment]
Hello @eldy : do we have to modify something for this PR or is is ok ?

**Comment by eldy** [comment]
There is one conflict to solve. 
Also you must replace $conf->global->TAKEPOS_BARCODE_RULE_TO_INSERT_PRODUCE
into
getDolGlobalString('TAKEPOS_BARCODE_RULE_TO_INSERT_PRODUCE')
to avoid errors with PHPv8 that is a target vo dolibarr v16

**Comment by altairis-tof** [comment]
hello @eldy, the constant TAKEPOS_BARCODE_RULE_TO_INSERT_PRODUCE was introduced by a later PR made by @lvessiller-opendsi 
can you ask him to fix it ?
the conflict also come from this PR that was made after ours and we have trouble to understand how to solve the conflict.
can you help us with it please ?

**Comment by lvessiller-opendsi** [comment]
@eldy @altairis-tof @altairis-tof 
See PR #20671 to resolve it

**Comment by altairis-tof** [comment]
thank you @lvessiller-opendsi

**Comment by altairis-tof** [comment]
Ok i've updated the script to resolve the conflict and integrate Lionel's fix.
I'm just waiting for @altairis-melina to update her account to integrate the new ssh key in order to push the commit and update this PR.
Hope it will be integrate soon !

**Comment by altairis-tof** [comment]
@eldy this PR is finally OK ! Travis and Stickler are happy !
Please note that others PRs on TakePos are also waiting to be merged.
Hope they will be soon to avoid more conflicts ;-)

**Comment by altairis-tof** [comment]
:+1: 
thanks

**Comment by Zulgrib** [comment]
I don't see where it could be configured from TakePOS module configuration page, is this setting only available by adding it using const.php ?

**Pull request merged**
