### PR TITLE
FIX #5705 Supplier Order's lines array initalisation  

### LINKED ISSUE #5705: Bug : Array for supplier order's lines not initialized
When using fetch function in CommandeFournisseur class, the array for the lines is not initialized before being filled.
In some case of use, for example
Fetch an Supplier Order and is lines
Delete on lines
Fetch again the Supplier order with the same object, the lines deleted remains.
## Environment
- **Version**: 3.9 / 4.0 / develop

### PR DESCRIPTION
**Pull request by philippe-opendsi**
Initialize array for supplier order's lines before filling it

### CODE REVIEW

**Comment by simnandez** [comment]
@philippe-opendsi can you make this for the maintened branch 3.8?

**Comment by philippe-opendsi** [comment]
yes, no problem

**Comment by philippe-opendsi** [comment]
Add PR #5719 for 3.8 and PR #5720 for 3.9
Not sure my commit or PR are well done.. I'm just beginning using github en git....

**Comment by simnandez** [comment]
Already made into 3.8 by #5719

**Comment by eldy** [comment]
Because fix already done in 3.8, this pr fix is useless so closed. Fix in 3.8 will be propagated to all higher versions by regular patch merges process.

**Pull request merged**
