### PR TITLE
[ task #1204 ] Add ref_ext contract field

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by FHenry** [comment]
I change the field name by ref_ext

**Comment by simnandez** [comment]
Can you change the ChangeLog from ref_int to ref_ext?

**Comment by FHenry** [comment]
Done

**Comment by simnandez** [comment]
I understand the ref_ext as customer reference (like orders, propals..), and therefore I see interesting and necessary.

**Comment by FHenry** [comment]
thank for complaining users

**Pull request merged**
