### PR TITLE
FIX: Accountancy Add informations to show in journal & correct problems to export in bookkee…

### PR DESCRIPTION
**Pull request by aspangaro**

### CODE REVIEW

**Comment by aspangaro** [comment]
Thanks @Darkjeff

**Comment by eldy** [comment]
Some files are UTF8 corrupted making travis report error

**Comment by hregis** [comment]
@eldy @aspangaro ... yes this is the BOM error, it's possible to resolved this... copy the content of the file, remove/delete the file, and recreate this file and paste the original content... save, push and enjoy ! ;-)

**Comment by aspangaro** [comment]
Conflict UTF8 solved @eldy  !  Thanks for the solution @hregis :+1:

**Pull request merged**
