### PR TITLE
NEW : continue hidden extrafield feature

### PR DESCRIPTION
**Pull request by FHenry**
NEW : continue hidden extrafield feature

### CODE REVIEW

**Comment by eldy** [comment]
What is goal of hidden extrafields ?
With new list, every user can decide which field to show or not so it is useless for user to hide field.

**Comment by ghost** [comment]
Hi @eldy i think it's usefull because with that we can manage extrafields by trigger or JS without give view for user on non user friendly value (in our case, we do that a lot and it's sometimes hard to explain it to the customer. And just add fields in base wasn't manage in the object has limit :/)

**Comment by FHenry** [comment]
Hi @eldy My use-case is store the JOSN of an order give by external system I use to create my order. I need to keep this original JSON, and may be use it with native class fetch method, but display it on card is just not possible. 
This type of extrafields will be use to store external key (when ref_ext is not enough) or data that need to be into dolibarr database without to be displayed to final users

**Comment by eldy** [comment]
@FHenry What i undestand is that you need a field specific to your case for your order for a specific module. If i am right, this means the data is only usefull for your module (only your module edit it and use it, never the end user). This just means the field must be stored into a dedicated table of your module (id_order / new field).

@atm-alexis It seems to be another use case. Do you mean you you want to have field output on html table but hidden to user so you can inject js to make actions on it ?

**Comment by ghost** [comment]
@eldy Yes is not our general purpose to update a hidden extrafield with JS. 

But i agree with both of you (@FHenry) because, if he put the field into custom table, he can manage the field from an hook or a trigger. But I think it's good way to have it into page even if it's to be manage by a thirdparty module because it's an object option and it complete the hidden extrafield function. I remember that in some of our module we share some non-hidden input and it's interresting to have the same with hidden field.

**Pull request merged**
