### PR TITLE
New pdf document column system : starting with CRABE AZUR and EINSTEIN

### PR DESCRIPTION
**Pull request by john-botella**
Hi

Add more flexibility on PDF document, allow to easily change or modify column order from module.
My goal is to create an easy to use responsive PDF models  with portrait and landscape support.

To make PDF models as flexible as possible (write less, do more ...), I choose a defined fixed size in mm, but i leave one column (desc by default) as a flexible column.
But, you can also define width by percentage, using the "scale" parameter instead of "width"

**I keep curent documents size and appearance.**

I have extend  this new feature to AZUR and EINSTEIN too

New behavior:
- the columns of the table are **automatically positioned according to the the page width** add a column definition array.
- the desc column is defined as fluid layout by default **so this column width is dynamic** , but you can set a width or define another column as flexible.

New features: now you can
- I add some methods to easily manage columns from modules
- add collumn from module
- move collumn from module
- desable collumn from module

exemple of adding new col to PDF
in module action_{yourmodule}.class.php use:

```

/*
     * Overloading the defineColumnField function
     *
     * @param   array()         $parameters     Hook metadatas (context, etc...)
     * @param   CommonObject    $object         The object to process (an invoice if you are in invoice module, a propale in propale's module, etc...)
     * @param   string          $action         Current action (if set). Generally create or edit or null
     * @param   HookManager     $hookmanager    Hook manager propagated to allow calling another hook
     * @return  int                             < 0 on error, 0 on success, 1 to replace standard code
     */
    public function defineColumnField($parameters, &$object, &$action, $hookmanager)
    {
        global $conf, $user, $langs;
        
        $error = 0; // Error counter
        
        $contexts = explode(':',$parameters['context']);
        
        if (in_array('invoicecard',$contexts)) {
            
            $def = array(
                'rank' => 55,
                'width' => 20, // in mm
                'status' => true,
                'title' => array(
                    'label' => 'test'
                ),
                'border-left' => true, // add left line separator
            );
            
            $object->insertNewColumnDef('newcoltest', $def, 'desc',1);
            
        }
        
    }
```
```

    /*
     * Overloading the printPDFline function
     *
     * @param   array()         $parameters     Hook metadatas (context, etc...)
     * @param   CommonObject    $object         The object to process (an invoice if you are in invoice module, a propale in propale's module, etc...)
     * @param   string          $action         Current action (if set). Generally create or edit or null
     * @param   HookManager     $hookmanager    Hook manager propagated to allow calling another hook
     * @return  int                             < 0 on error, 0 on success, 1 to replace standard code
     */
    public function printPDFline($parameters, &$object, &$action, $hookmanager)
    {
        global $conf, $user, $langs;
        $pdf =& $parameters['pdf'];
        if ($object->getColumnStatus('newcoltest'))
	{
            $object->printStdColumnContent($pdf, $parameters['curY'], 'newcoltest', 'exemple of text');
            $parameters['nexY'] = max($pdf->GetY(),$parameters['nexY']);
            return 1;
        }
    }
```

### CODE REVIEW

**Comment by atm-john** [comment]
exemple of module action_{yourmodule}.class.php use:
`
    /**
     * Overloading the defineColumnField function : replacing the parent's function with the one below
     *
     * @param   array()         $parameters     Hook metadatas (context, etc...)
     * @param   CommonObject    $object         The object to process (an invoice if you are in invoice module, a propale in propale's module, etc...)
     * @param   string          $action         Current action (if set). Generally create or edit or null
     * @param   HookManager     $hookmanager    Hook manager propagated to allow calling another hook
     * @return  int                             < 0 on error, 0 on success, 1 to replace standard code
     */
    public function defineColumnField($parameters, &$object, &$action, $hookmanager)
    {
        global $conf, $user, $langs;
        
        $error = 0; // Error counter
        
        $contexts = explode(':',$parameters['context']);
        
        if (in_array('invoicecard',$contexts)) {
            
            $def = array(
                'rank' => 55,
                'width' => 20, // in mm
                'title' => array(
                    'label' => 'test'
                ),
                'border-left' => true, // add left line separator
            );
            
            $object->insertNewColumnDef('newcoltest', $def, 'desc',1);
            
        }
        
    }
    
    /**
     * Overloading the printPDFline function : replacing the parent's function with the one below
     *
     * @param   array()         $parameters     Hook metadatas (context, etc...)
     * @param   CommonObject    $object         The object to process (an invoice if you are in invoice module, a propale in propale's module, etc...)
     * @param   string          $action         Current action (if set). Generally create or edit or null
     * @param   HookManager     $hookmanager    Hook manager propagated to allow calling another hook
     * @return  int                             < 0 on error, 0 on success, 1 to replace standard code
     */
    public function printPDFline($parameters, &$object, &$action, $hookmanager)
    {
        global $conf, $user, $langs;
        $pdf =& $parameters['pdf'];
        $object->printStdColumnContent($pdf, $parameters['curY'], 'newcoltest', 'exemple of text');
        $parameters['nexY'] = max($pdf->GetY(),$parameters['nexY']);
        return 1;
        
    }
    `

**Comment by eldy** [comment]
related to #8320

**Comment by john-botella** [comment]
For Crab, the long note's weird behavior is fixed.
Remains to apply the change to the other two

**Comment by atm-john** [comment]
OK, this pull request is ready!

**Comment by frederic34** [comment]
Checking Azur
[PR1712-0001(1).pdf](https://github.com/Dolibarr/dolibarr/files/1917496/PR1712-0001.1.pdf)
Where are product photo?
Page 4 where is head and pdf background
Footer is overwrited, did you check with adress options in footer

**Comment by frederic34** [comment]
Checking crabe
[FA1804-0004.pdf](https://github.com/Dolibarr/dolibarr/files/1917531/FA1804-0004.pdf)

**Comment by john-botella** [comment]
Indeed, 
I just fixed head, pdf background and footer size.

But for photos on Azur, It's work's for me, I use MAIN_GENERATE_PROPOSALS_WITH_PICTURE conf and I not using PRODUCT_USE_OLD_PATH_FOR_PHOTO.

**Comment by frederic34** [comment]
For the footer, i did this:

$heightforfooter = $this->marge_basse + (empty($conf->global->MAIN_GENERATE_DOCUMENTS_SHOW_FOOT_DETAILS)?12:22);

because there is an option to enable more details in footer in configuration/pdf

**Comment by john-botella** [comment]
@atm-florian, @atm-maxime, @ATM-Marc , @atm-ph , if you have enough time, Your tests and feedback are expected :-)

**Comment by aconits** [comment]
:+1: 
Work's fine for me
For the PRODUCT_USE_OLD_PATH_FOR_PHOTO conf, now I think we sould execute the script in `scripts/product/migrate_picture_path.php` 
This new system will give us some much possibilities to customize PDF without replace the originals documents

**Comment by ATM-Marc** [comment]
Tested it today, works great ! I hope it is not postponed for too long.

**Pull request closed without merging**
