### PR TITLE
NEW : Product stock and subproduct stock are independent

### PR DESCRIPTION
**Pull request by atm-gauthier**
Allows to avoid subproducts destock when parent product destock

### CODE REVIEW

**Comment by marcosgdf** [comment]
I think you meant `Independent` and not `Independant`

**Comment by ghost** [comment]
he made ​​this mistake because it 's almost the same in French ;) "Indépendant"

**Comment by eldy** [comment]
A more powerful feature development has been started to be developed.
On page to edit the subproduct, we must add a new checkbox to say if subproduct must be decreased or not. The field already exists into table llx_product_association, it is "incdec" (meaning increase/decrease).
It is just missing the checkbox on page to edit subproduct to decrease and we also miss the test in the movement function to decrease or not subproduct according to this checkbox.

I prefer not including your PR because it will be a conflict with this other way of working, that is more powerfull and does not need no option. It would be great if instead you can finish to implement it, you already have found where is code to modify   :-)

**Comment by BebZ** [comment]
I'm sorry Eldy, but where is the new more powerful feature ? 
I guess if he would have seen it in the code he would have made it better, no... or maybe he tried to make it simpler ?
With the more powerful feature we can choose 
which subproduct stock must decrease or not 
when/if parent product stock is decreasing ?

**Comment by eldy** [comment]
As i said, this feature is not yet visible because noy yet implemented into screen. Only database is ready for that. I hope someone will implement it soon as work to finish is low now.
Yes, goal is to choose which subproduct will decrease/increase when a parent product is changed.

**Comment by BebZ** [comment]
:+1:

**Pull request closed without merging**
