### PR TITLE
FIX : product_batch line not delete when qty =0

### PR DESCRIPTION
**Pull request by defrance**
Otherwise we can't made some tracability with it

### CODE REVIEW

**Comment by fappels** [comment]
ref FR #3438

**Comment by eldy** [comment]
The goal of table llx_product_batch is to contains details of product with serial that are currently in stock.
It's name should be "llx_product_stock_batch".
We CAN'T use same table to store list of serial that had existed on day with dates related to serial and to store content of a stock. 
Currently implementation used table "llx_product_batch"  as if it was table "llx_product_stock_batch" (detail of stock). The date in this table should be useless.
So we just need another table called llx_product_lot that is a table taht would be always edited in insert and will store serial nb and dates. We should not used dates into other table.
So currently position is: table llx_product_batch is table for stock, so we must remove line with qty = 0 and we must introduce a new table call llx_product_lot to store the dates related to a serial number. This table will be checked inserted each time we made a stock movement.

**Comment by defrance** [comment]
so why just rename llx_product_batch llx_product_lot ???

**Comment by eldy** [comment]
Because table llx_product_batch is not used currently to store list of lot but is used to store the detail of a stock. It's a vision of how many qty we have for each lot in each stock.

The table llx_product_lot I introduced by a #7b16482cee32b7c9cb8b2f0702bbad34d18db86b today is a table to store association between a lot/Serial number and other properties like date, notes, .... lot number is here unique and never deleted.

**Comment by defrance** [comment]
Yes it is not used to this and it is for this reason that I wish to change its use while maintaining its functionality.
There is a confusion between a lot number and a serial number
over my equipment module already manages very well the management of serial numbers

I have on several occasions said that this batch module / lot had been integrated into the core without having had any long-term thinking, now we must develop it to give it a real value but add tables will not help.

---

Oui elle n'est pas utilisé pour cela et c'est pour cette raison que je souhaite faire évoluer son usage tout en conservant sa fonctionnalité.
Il y a une confusion entre un numéro de lot et un numéro de série dans votre analyse, d'ailleurs mon module Equipement gère déjà très bien les numéros de séries et saura faire usage de la fonctionnalité de lots

J'ai à plusieurs reprises expliqué que ce module de batch/lot avait été intégré au core sans qu'il y ait eu la moindre réflexion à long terme de son usage, à présent il faut le faire évoluer pour lui donner une réelle utilité mais d'ajouter des tables ne servira à rien.

**Comment by eldy** [comment]
There is no confusion between lot and serial number. This is definition

A barcode EAN13 identify in most cases a product (as a template), like do the reference of a product (also called Part number). Identification of the serial or lot can be done with the Serial No also called SSN, S/N, or SN or "Product No". Serial and Product are sometimes an autonomous bar code number, sometimes included into a EAN128 code: http://www.barcodeisland.com/uccean128.phtml. A serial may be a lot or a unique instance of a product (that is a lot of 1).

The SKU is a generic term to say: "The ID enough accurate to manage stock". So SKU depends if you use lot/serial number or not. It can be a Part number or a Serial No. Best thing is to avoid using this term to avoid confusion.

Adding the new table is absolutely necessary. We must manage 2 different tihngs:
- the stock (we already have this table)
- the properties of a lot/serial number (we didn't have it, we have it now called llx_product_lot)

The module batch/lot was seriously analyzed before being introduced. The only default was the missing table as i explained. I was aware of this since the beginning but it was not critical to enable the module because this could be fixed after and we must go forward step by step.

**Comment by defrance** [comment]
OK i anderstand your point of view but use line with qty=0 not empeach the evolution of the functionnality, juste give more time to implement it
another point not solved is case of the same batch/lot come in warehouse, in this case we have 2 lines with same value except qty, we must made an update instead a create
please consider some little change here : https://github.com/Dolibarr/dolibarr/pull/4973

**Comment by eldy** [comment]
I think now the update is correctly done. A unique key has been introduced into llx_product_batch (detail of different lots into one stock). Also table llx_product_lot is loaded when a new couple product/lot is known.

**Pull request closed without merging**
