### PR TITLE
New : Add new status Shipped in expedition

### PR DESCRIPTION
**Pull request by dolibarr95**
Prepare new status (3) shipped.

- 0 - Draft : prepare the shipment
- 1 -Validated : Validate the products, transport etc
- 2 - Done (or Ready) : The package is ready to be send (weight, best deliveray delay...)waiting for shipping
- 3 - Processed: Close (the parcel is gone)

### CODE REVIEW

**Comment by eldy** [comment]
To analyze also with #9660 #10174 #8953

**Comment by dolibarr95** [comment]
Hi
@eldy  tks for the tag.
Do you think we have to make a new PR instead of this 3 PR?

**Comment by wdammak** [comment]
@eldy : what's the problem with this PR?

**Comment by dolibarr95** [comment]
Hi!
Just a reminder about mentioned PR by eldy : 
 
- #9660 : allow get back to draft status (status draft already exists)
-  #10174 : add a new status named "shipped" (this status doesn't exist)
-  #8953: new try to add a new status named "shipped" (this status doesn't exist)

**Comment by fbosman** [comment]
Is there any progress on this issue?
We are in need of this statuses. I think it is wise not to take alle these pr’s in one step.

**Comment by eldy** [comment]
There is several PR to enhance this and it is not clear what will be the behaviour after (except that all of them suggest a different way of working). So to help to choose which one to retain, i updated wiki doc to describe current worklow:
https://wiki.dolibarr.org/index.php/Module_Shipments#Usage

Can you cut and paste this workflow text graph and update it to describe what will be workflow after the change (keeping the X and the number of status in parenthesis)

**Comment by eldy** [comment]
I think we should enhance the process with something like that:
Draft ---X---> Validated ---> Closed (X = stock change, Can edit qty and lot in Draft step)
must become
Draft --X--> Validated ---Y---> Shipped (We choose to have stock change into X or Y step, Can edit qty and lot in status Draft + Validated)

The Y has been implemented in v17 or before.  You can now choose X or Y.

With v18, the default mode is set to Y instead of X.

**Comment by eldy** [comment]
Now we need a PR to be able to edit the qty and lot in status Draft, or Validated when stock change is set to Y...

**Comment by eldy** [comment]
The feature to be able to edit qty and lot into a shipment in draft status is available in v18, so i close this PR.

**Pull request closed without merging**
