### PR TITLE
Qual: societe: fix warning during tests

### PR DESCRIPTION
**Pull request by alexandre-janniaux**
# Qual societe: fix warning during tests

    1) /home/alexandre/workspace/dolibarr/htdocs/societe/class/societe.class.php:1299
    Attempt to read property "country_id" on null

    Triggered by:

    * BookKeepingTest::testBookKeepingCreate (6 times) /home/alexandre/workspace/dolibarr/test/phpunit/BookKeepingTest.php:53

    * SocieteTest::testSocieteCreate (6 times) /home/alexandre/workspace/dolibarr/test/phpunit/SocieteTest.php:87

    * SocieteTest::testSocieteFetch (6 times) /home/alexandre/workspace/dolibarr/test/phpunit/SocieteTest.php:114

    * SocieteTest::testSocieteMerge (12 times) /home/alexandre/workspace/dolibarr/test/phpunit/SocieteTest.php:450

    * SocieteTest::testSocieteUpdate (6 times) /home/alexandre/workspace/dolibarr/test/phpunit/SocieteTest.php:143

### CODE REVIEW

**Comment by alexandre-janniaux** [comment]
Note: the warning might disable code that needs to be executed, but there's no fallback available for this part.

**Comment by mdeweerd** [comment]
In order to have these cases catched by static analysis (phan), 
we should set the global to nullable in dev/tools/phan/config.php (`        'mysoc' => '?\Societe'`).

**Comment by alexandre-janniaux** [comment]
> In order to have these cases catched by static analysis (phan),  we should set the global to nullable in dev/tools/phan/config.php (        'mysoc' => '?\Societe').

Good idea, feel free to submit that! I've never used the tool. ;)

**Comment by mdeweerd** [comment]
> Good idea, feel free to submit that! I've never used the tool. ;)

You're "using it" - it's executed in ci !

**Comment by alexandre-janniaux** [comment]
> > Good idea, feel free to submit that! I've never used the tool. ;)
> 
> You're "using it" - it's executed in ci !

Of course! I mean I don't use the configuration or the tool locally, and I'm absolutely not a PHP developer, so I'm clearly not familiar with it!

**Pull request merged**
