### PR TITLE
FIXED: Remove condition to show accountancy field on user.

### PR DESCRIPTION
**Pull request by aspangaro**
Needed for accountancy.

### CODE REVIEW

**Comment by eldy** [comment]
When does this field is used ?

**Comment by aspangaro** [comment]
Hi Eldy,

This field is used to affect salary in accountancy. The user is considered like a thirdparty. (Same thing with customer & supplier)

**Comment by eldy** [comment]
Can't we add a test to enable field only when module salary is used ?

**Comment by aspangaro** [comment]
If you want, I will remove the test when accountancy module is more completed.

It's done !

**Pull request merged**
