### PR TITLE
Experimental new pdf documents  using new column system

### PR DESCRIPTION
**Pull request by john-botella**
The same as #8570 but instead of modifying existing PDFs, I created three new models.
eratosthene (orders), sponge (invoices) and cyan (quotations)

### CODE REVIEW

**Comment by atm-maxime** [comment]
@eldy could you have a look ? Allows more flexibility on PDF documents

**Comment by john-botella** [comment]
Hi @eldy , 
All this new PDF  are now on 'development' version

**Comment by frederic34** [comment]
👍

**Comment by john-botella** [comment]
YES !!

**Pull request merged**
