### PR TITLE
NEW French new regions

### PR DESCRIPTION
**Pull request by aspangaro**
Migration for old data in progress

### CODE REVIEW

**Comment by eldy** [comment]
The table of state are record linked to the region.
If id of region change, the table llx_departements may also need to be modified (or id will point to a non existing foreign key).

**Comment by aspangaro** [comment]
@eldy You're right, the migration is being prepared.

image 🥇

**Comment by aspangaro** [comment]
@eldy Migration is ok for v12

**Comment by aspangaro** [comment]
Ping @eldy 

PR verified 3 times

**Pull request merged**
