### PR TITLE
Fix : email model was not kept in presend form after choosing one

### PR DESCRIPTION
**Pull request by atm-maxime**

### CODE REVIEW

**Comment by atm-maxime** [comment]
@eldy ?

**Comment by eldy** [comment]
Not sure it is a good behaviour.

When a field is selected in a form, it means we use this data when we click on submit button, but here, once template is applied, we won't use this selection at all, so it is giving a false information to use to have the field selected with something that won't be used.

Goal of choosing a template is to "prefill" content field but once the field is filled, content, subject, etc might be modified and even completed, so having the "initial template used to prefill" the form does not looks good to me. In a future we may even choose several times different template (to concat several content).

**Comment by atm-maxime** [comment]
Ok understood, but we should at least have the information in a hidden input.
I did this because I need to execute some code with the _SENTBYMAIL trigger, but I have no way of knowing which model has been used. How would you achieve that ?

**Comment by atm-maxime** [comment]
Ok @eldy, I changed it as discussed and added a hidden field containing the selected model id.

**Comment by atm-maxime** [comment]
@eldy ?

**Comment by atm-maxime** [comment]
ping @eldy

**Pull request closed without merging**
