### PR TITLE
ADD new function getQtyYetShipped

### PR DESCRIPTION
**Pull request by PeartreeG**
Determination of qty yet shipped of a product from an order

### CODE REVIEW

**Comment by marcosgdf** [comment]
Why adding a new property to the class?

**Comment by PeartreeG** [comment]
the goal is to modify the shipping pdf like this : http://www.dolibarr.fr/forum/526-autres-modules/55411-modele-pdf-des-expeditions-detailles
for the moment the query is directly on the pdf file

**Comment by marcosgdf** [comment]
It doesn't answer my question. That property does not make much sense in the class… Why not returning the qty yet shipped directly in the function?

**Comment by eldy** [comment]
If the origin order has 2 lines with same product, you will get same value of already shipped for each line.
That's why a I prefered to extend function "loadExpeditions" that return array of qty already shipped in array $order->expeditions but with detai for each line.
Using this function is better than the one you suggest to build the suggested PDF because you have detailed value for each line of order without counting twice data when same product is on different lines of order.

**Comment by PeartreeG** [comment]
In fact we have 3 lists of products :
- the list of order where you can have 2 lines with the sames product 
- the list of all the product to send with one line by product who's not realy exist
- the list of product send in the expedition where only line of product with qty > 0 on the sending

the first line generate conflict on the qty send for the line with same product
the last list is used on the shipping pdf but i think it's not a good pratice because the customer don't have enough information

I will show the loadexpeditions to build a good list of array and use it on PDF

**Comment by BebZ** [comment]
the last list is used on the shipping pdf but i think it's not a good pratice because the customer don't have enough information

> TRUE and MISSING !!!
> PDF, with shipment has to tell there was no qty of product shipped but was a qty ordered
> product X : qty ordered 3 sent 2 missing 1
> product Y : qty ordered 2 sent 0 missing 2
> product Z : qty ordered 4 sent 4 missing 0
> or there should be another line added at the end with (or another pdf with missing items) : 
> product missing on this shipment : 
> product X (qty 1) product Y (qty 2)

Is there someone seeing the bug, it has been 3 years i replace 

> 0 
> by >=0 

on 
htdocs/commande/fiche.php
htdocs/expedition/fiche.php

I know it' UGLY !

**Comment by BebZ** [comment]
is the 
var $qty_yet_shipped;

DEAD ?

**Pull request closed without merging**
