### PR TITLE
NEW Add button Cancel on shipping

### PR DESCRIPTION
**Pull request by leninrivas**
Button cancel, confirm cancel, no delete Ref and recovery stock.

### CODE REVIEW

**Comment by altairis-tof** [comment]
Hello, what is the difference between Cancel and Delete here ?

**Comment by altairis-tof** [comment]
i mean in which use case do you want to keep the shipping as cancelled instead of delete it ?

**Comment by leninrivas** [comment]
Hello, extacly, is to keep correlative shipping ref.

**Comment by altairis-tof** [comment]
i understand, thanks. Maybe that we should keep delete for draft shippings only, and cancel for validated shippings ?

**Comment by leninrivas** [comment]
That is better.

**Comment by JonBendtsen** [comment]
@leninrivas  hi. Seems like you introduced deleteObjectLinked in the cancel method, and there is now a bug on why. Do you remember why?

see issue #37381

**Pull request merged**
