### PR TITLE
New: prepare for e-shipment (SQL part)

### PR DESCRIPTION
**Pull request by sonikf**
Related to #31652

Hi @eldy 

My guess is that by 1/4/2025(compulsory date for Greece) v 22.0.0  will not have  been released yet, so i kindly request  for the inclusion to v. 21.0.0 of the minimum changes needed for e-shipment to work meaning this pr + #31701 first + a pr following to show fields in modules card.php

A few remarks
- General rule is that for every item exiting business facilities a shipment must be issued and there are many use cases not supported such as:

|Type|use case examples|Dolibarr|
|-|-|-|
|internal movements of assets(not financial)|move a pc from one building office to another building office |ko|
|internal movements of  stock|from main warehouse to secondary warehouse, warehouse to store etc |ko|
|repair - maintenance|faulty equipment, motherboard fails,equipment service etc|ko|
|Sampling - Exhibition and/or Free distribution|event organization-conference also involves an equipment movement|ko|
|Return|damaged goods from vendor|ko|
|Recycling or Destruction of waste material |manufacturing|ko|

- Right now shipment is  treated as a secondary document by being dependant to sales orders.

- Following comment seems wrong, warehouse is used for stock management and not for per product departure this is not how logistics work.
As per above examples a warehouse can be a starting point or a destination of a shipment
https://github.com/Dolibarr/dolibarr/blob/40aca2803f1b329bb95d8d784d0c87eba2353362/htdocs/install/mysql/tables/llx_expeditiondet.sql#L31

- Shipment address is used through contacts but is not recorded to shipment or invoice as it should. Same would apply to loading address

If you agree i will work for independent shipment creation for v 22.0.0  plus support for above use cases

### CODE REVIEW

**Comment by eldy** [comment]
I validated PR but :
- I remove field datee: seems duplicate of the field date_expedition. Or i miss something ?
- I renamed  is_delivery_note into is_also_delivery_note because if my understanding is good, the invoice will be both a real invoice (that affect the turnover and go into accounting) and is also used as a shipment document to avoid to duplicate documents. This is not invoice XOR shipment but Invoice alone, or invoice + shipment, right ?

**Comment by sonikf** [comment]
Ηι @eldy 
Thanks for  validation 
We also need datee as issue date(shipment has no issue date because it depends on order)  + https://github.com/Dolibarr/dolibarr/pull/31701 because as @altairis-noe explains we need the date shipment actually starts/gone  meaning when loaded to a company truck for example or received from a shipment/delivery service.

workflow example:
today 12/11/2024 i issue Proposal or order with planned date(date_delivery=18/11/2024) 
Friday 15/11/2024 i issue Invoice or shipment with issue date (datef, datee=15/11/2024) and also actual starting date (date_expedition=Tuesday 19/11/2024). 

In future this date(date_expedition) will be filled by e.g. shipment/delivery service driver by scanning QR CODE and transmitted to all related parties (The way this is designed based on EU VIDA proposal is that  info provided to both vendor and mainly client will be in near real time so there will be no need for tracking number in future. Authorities need to fight illegal trade and vat fraud)

**Comment by eldy** [comment]
> Ηι @eldy 
> Thanks for  validation 
> We also need datee as issue date(shipment has no issue date because it depends on order)  + https://github.com/Dolibarr/dolibarr/pull/31701 because as @altairis-noe explains we need the date shipment actually starts/gone  meaning when loaded to a company truck for example or received from a shipment/delivery service.
> 
> workflow example:
> today 12/11/2024 i issue Proposal or order with planned date(date_delivery=18/11/2024) 
> Friday 15/11/2024 i issue Invoice or shipment with issue date (datef, datee=15/11/2024) and also actual starting date (date_expedition=Tuesday 19/11/2024). 
> 
> In future this date(date_expedition) will be filled by e.g. shipment/delivery service driver by scanning QR CODE and transmitted to all related parties (The way this is designed based on EU VIDA proposal is that  info provided to both vendor and mainly client will be in near real time so there will be no need for tracking number in future. Authorities need to fight illegal trade and vat fraud)

So the issue date in your exemple seems to be the date of creation of shipment ?

**Comment by sonikf** [comment]
Yes ok we can use date_creation, thanks

**Pull request merged**
