### PR TITLE
FIX better method to check if pdf is protected/encrypted

### PR DESCRIPTION
**Pull request by hregis**

### CODE REVIEW

**Comment by eldy** [comment]
Dans quel cas tu utilise cette fonction ?
J'ai l'impression que dolibarr ne s'en sert jamais?

**Comment by hregis** [comment]
@eldy je veux m'en servir pour améliorer les tests lors des concaténations et pouvoir utiliser l'encryption lorsqu'on fusionne des pdf dans les listes

**Comment by eldy** [comment]
Because the 2 methods works in different context (old method was using an already loaded pdf object and yours need to reread file on disk, also it use ob_... function that have side effect in some context), i suggest to add a parameter to decide which method we use (the old one or the new one).

**Comment by hregis** [comment]
@eldy 
the first method that uses TCPDI does not work, it must be buggy, you must use the tcpdf parser for it to work! it's possible to remove "od_*"
i send a fix for this PR

**Pull request merged**
