### PR TITLE
FIX #10796 #8927 Accept both CLI argv and CGI modes in /script/cron_run_jobs.php

### PR DESCRIPTION
**Pull request by edupulpillo**
Fix the case when crontab in shared hosting launch the script as PHP cgi mode and do not allow CLI mode. 
To fix it, this version of the script /script/cron_run_jobs.php accept both modes, and use the security key and username passed by argv in the case it was launched in CLI mode, and use key=$conf->global->CRON_KEY and $userlogin = "firstadmin" if it was launched in cgi mode.

### CODE REVIEW

**Review by edupulpillo — COMMENTED** [review]
This PR should be applied also to v13 and v14. Is my first commit here, kindly help me to drive me to perform a PR in several branches. In this case i would like to PR in the versions: v12, v13, v14 and develop.

**Comment by eldy** [comment]
No need to push a PR in several branch. If you push it for v12, it will be merged few days after into v13 , v14... until develop.

**Comment by eldy** [comment]
Because the file is into the dir "scripts", it means it can be executed by CLI only. Only dire htdocs is reachable by web access.
You already have a page to access cron by url into  public/cron/cron_run_jobs_by_url.php

**Comment by edupulpillo** [comment]
Thank you for the info!.
So then we have 4 versions of the script to launch scheduled jobs, with almost the same code, as you warn already inside the comment in sourcecode as "// TODO Duplicate code", except the first part that control the calling parameters:
1. /scripts/cron/cron_run_jobs (The only one supposed to accept to use CLI mode)
2. /public/cron/cron_run_jobs.php
3. /public/cron/cron_run_jobs_by_url.php
4. /public/cron/cron_run_jobs_bycgi.php

So if you agree, i can work to try to merge it in only one version of php script **cron_run_jobs.php** taking care of all the calling cases and applying the values and call controls accordingly the way it was invoked. 
Then we will have an easier code maintenance with only one file, instead using 4 different versions of files for cli, cgi, url. and script, providing more simplicity in the code, as you warn already in one comment inside as "// TODO Duplicate code".

The controls for the parameters could be:
1. If is detected that cron_run_jobs.php was launched from **/scripts/cron/** then
     1.1  if CLI mode detected, take securitykey  and userlogin from the passed arguments of the command line and check that are valid.
     1.2  if CGI mode detected, take securitykey from $conf->global->CRON_KEY and $userlogin = "firstadmin", (this help a lot in shared hostings, because now the security key and loginname can be seen with ps, basically is the PR i did, because **is the only way to make it works in my shared hosting and never php cli mode is detected**) 
2.  If is detected   that cron_run_jobs.php was launched **from any different path than /scripts** then:
     2.1  if CLI mode detected, return an error
     2.2 if CGI mode detected, get the parameters from GETPOST and check that are valid

Doing this way, also the same script can works fine in shared hosting environments with CPANEL that even is specified a CLI mode, is detected as cgi inside the script, and also works fine in external url request mode.

To avoid to have to files duplicated in **/scripts/cron/cron_run_jobs** and **/public/cron/cron_run_jobs.php**, maybe one can be a symbolic link to the another one or just that one file have inside only an include to the another one, to have only one version of the code.

At the moment the solution seems is already working pretty good in my instance of Dolibarr. :-)

**Comment by eldy** [comment]
We only have 2 version of scripts
/scripts/cron/cron_run_jobs (The one used by CLI)
/public/cron/cron_run_jobs_by_url.php  (The one for used from CGI)

We still need to have this 2 different scripts. They are used in different context with different security rules.
We may have similar portion of code inside that may be factorized but not so much.

**Comment by edupulpillo** [comment]
Thanks for the update and clarifications!. Then this pull request in
/scripts/cron/cron_run_jobs (The only one supposed to accept to use CLI mode) allows now to also accept to be calles in CGI mode instead CLI mode only, allowing to be invoked by cron configurations in shared hosting services that do not allow CLI mode, that without his update never works with CPANEL.
This feature do not create any problem in security rules, since is not under public_html, so only add the feature tp add both CLI and CGI modes.

**Comment by eldy** [comment]
When you call a CLI script with CPANEL, are you able to set an environment variable ?
If you add a test  $_ENV['DOL_ACCEPT_CLI_AS_CGI'] to accept to run script as a cgi is a better option.

**Comment by eldy** [comment]
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Pull request closed without merging**
