### PR TITLE
Authorship recognition at ticket API messaging #20582

### PR DESCRIPTION
**Pull request by pratushraj**
# Instructions
*Dolibarr provides simple tickets Creation and messaging via its API. Generally, the API client is connected using an API key. The SuperAdmin key is generally used for API communication. Now here is the lack of features in the ticket API communication*

*You can simply do that to add "authorid": "0" for creating the ticket or sending the new message from the customer side.*

# FIX|Fix #[*20582 Authorship recognition at ticket API messaging*]

### CODE REVIEW

**Comment by eldy** [comment]
This may create security trouble.
Any user can use the api to create a ticket by hidding it was created by himself. What is the goal ?
If goal is to avoid to send an email after ticket creation, a new param into API would be a better choice.

**Comment by pratushraj** [comment]
@eldy  the goal of this is to make the ticket API communication more advanced. We want to integrate ticket API communication with another software having the customers. Now customer will directly reply to the ticket from the software. And the software will send the message to the Dolibarr system using the API. Now as the Dolibarr mistakenly makes author of the reply to the API owner, we can't track the user who actually is the author.

**Comment by eldy** [comment]
There is no need to add a property authorid for that.
There is already the property  "fk_user_create"

Did you try to set   fk_user_create  into api call so when the api call ticket->create, the fk_user_create is set to this id ?

**Comment by pratushraj** [comment]
Yes, I tried. But not working with the property "fk_user_create". Because the property "fk_user_create" always takes the value of the user Id. That's why I add the property "authorid".

**Comment by eldy** [comment]
I checked the code in v16. I see no reason why setting fk_user_create into api call won't work. Did you try with the develop branch ?

**Comment by pratushraj** [comment]
Yes, I Also checked in develop branch, that "fk_user_create" not working because "fk_user_create" took the value of the user related to the API key. That's why I introduced the new property called "authorid".

**Pull request closed without merging**
