### PR TITLE
Qual: keep trigger naming consistent

### PR DESCRIPTION
**Pull request by rdoursenaud**

### CODE REVIEW

**Comment by marcosgdf** [comment]
I think a PRODUCT_ prefix would be nice...

**Comment by rdoursenaud** [comment]
Well, it can either be a product or a service. I think it's explicit enough, don't you?
PURCHASEPRICE would be better but inconsistent with other namings across Dolibarr sourcecode (functions, database fields…).

**Comment by marcosgdf** [comment]
Yep but... the rest of triggers do have a PRODUCT_ prefix... services are just products with different behaviour.

I'm just basing my decisions in http://wiki.dolibarr.org/index.php/Triggers

**Comment by eldy** [comment]
I added "SUPPLIER_PRODUCT_" before trigger name. There was no specific rule at beggining for trigger name.
More and more, i try to have a name that start with module name (in english) then more information (not rule) and finished by action.

**Comment by rdoursenaud** [comment]
@eldy Sounds reasonable to me!

**Pull request merged**
