### PR TITLE
Fix bug [ bug #861 ] Erreur de droit groupe et utilisateur

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by marcosgdf** [comment]
Would you mind adding changelog entries? :smile:

**Comment by FHenry** [comment]
You are damly rights ! I forget this each time. Egalmente para los task de Doliforge olvido de poner le dentro ChangeLog. Ahora esta listo

**Comment by marcosgdf** [comment]
:us: It would be great if you could translate the title of bug #861 to english
:es:    _Sería genial si pudieras traducir el título del bug #861 al inglés_

Thanks!

**Comment by FHenry** [comment]
One more time you'r right. We need quality guy like you.

**Comment by marcosgdf** [comment]
You mean being a pain in the ass haha. But I'm not a quality guy, just a noob trying to make things right... and I'm usually not right... haha

Thanks btw

**Pull request merged**
