### PR TITLE
Update 16.0.0-17.0.0.sql

### PR DESCRIPTION
**Pull request by dolibit-ut**
v17 Sorting

ALTER TABLE llx_emailcollector_emailcollector ADD COLUMN port varchar(10) DEFAULT '993';   was twice

### CODE REVIEW

**Comment by dolibit-ut** [comment]
any reason why  `ADD COLUMN ip`  is  `var(250)`   and not var(255) ?

**Comment by eldy** [comment]
> any reason why  `ADD COLUMN ip`  is  `var(250)`   and not var(255) ?

I don't think so.

**Review by eldy — COMMENTED** [review]
Editing a file used for migration to v16 to v17 is not allowed for version higher than v17. It is only in branch v17.
However, the v17 beta is nearly finished, so no change in this file will not be done except if it fixes a blocking bug.

**Comment by dolibit-ut** [comment]
Okay. I have only sorted the order and so I noticed that this line is duplicated:

ALTER TABLE llx_emailcollector_emailcollector ADD COLUMN port varchar(10) DEFAULT '993';

This should be deleted.

For the future a better order/sorting is recommended.

**Comment by eldy** [comment]
> Okay. I have only sorted the order and so I noticed that this line is duplicated:
> 
> ALTER TABLE llx_emailcollector_emailcollector ADD COLUMN port varchar(10) DEFAULT '993';
> 
> This should be deleted.
> 
> For the future a better order/sorting is recommended.

Don't forget that even a simple sort generates trouble: when doing merge of maintenance releases, changing sort order of lines in files generates troubles and conflict that lead to errors (line forgotten or corrupted) when trying to solve conflict.

**Pull request closed without merging**
