### PR TITLE
Prodpic

### PR DESCRIPTION
**Pull request by tiaris**
Correct get_exdir function for showing pictures when using PRODUCT_USE_OLD_PATH_FOR_PHOTO 
add a filter for search of parent company (based on company type)

### CODE REVIEW

**Comment by fmarcet** [comment]
Your first commit is the same that mine #4072 We will wait for some good Yoda that accept someone :smile:

**Comment by eldy** [comment]
The fix introduce a lot of bugs with standard setup.
If goal is to fix behaviour when option PRODUCT_USE_OLD_PATH_FOR_PHOTO is on, we should see some "if (! empy($conf->global->PRODUCT_USE_OLD_PATH_FOR_PHOTO))" somewhere in the patch.

**Comment by tiaris** [comment]
why doing it in the patch ? 
in function of standard class product is_photo_available test is allready done for PRODUCT_USE_OLD_PATH_FOR_PHOTO  we have get_exdir($this->id,2,0,0,$this,'product')
if you do not add 'product' in the get_exdir function, this could newer work
Problem is that the new system is buggy because on user of an older system can not migrate to dolibarr 3.8.

**Comment by eldy** [comment]
If you introduce code to manage an old behaviour and you dont introduce test if (oldoption) then code will be executed also into new context. So you fix a bug for old users but introduce a bug for new one.
That's why the patch must include a test on "if (! empy($conf->global->PRODUCT_USE_OLD_PATH_FOR_PHOTO)"

**Comment by tiaris** [comment]
test is done in product.class.php standard method is_photo_available. 
if (! empty($conf->global->PRODUCT_USE_OLD_PATH_FOR_PHOTO)) $dir .= '/'. get_exdir($this->id,2,0,0,$this,'product') . $this->id ."/photos/";
        else $dir .= '/'.get_exdir(0,0,0,0,$this,'product').dol_sanitizeFileName($this->ref).'/';

it seems to be the new way for using get_exdir according comments in code

**Comment by eldy** [comment]
I can't reproduce any bug currently. Can you provide a use case to reproduce the bug when patch is not merged. What I need is :
The full path into "documents" diretory where pictures of a product are stored, name of picture file and url of page where image is not visible when it should.

**Comment by eldy** [comment]
Bugs seems to have been fixed by other PR, so i close this one

**Pull request closed without merging**
