### PR TITLE
another set of empty($action) fixes

### PR DESCRIPTION
**Pull request by cfoellmann**
Extends #21469 

some more blockers for card.php without $action

### CODE REVIEW

**Comment by eldy** [comment]
Note: I reverted #21469 because it introduced some regression going on the create form when we should not (for example on navigation).
What do you think of fixing diferently, for example by adding this just after the $action = GETPOST('action', 'aZ09');
`if (empty($action)) $action = 'view'; `

**Comment by cfoellmann** [comment]
setting to `view` would kill the card.php also.
When there is nothing to view why load a view screen?

**Comment by cfoellmann** [comment]
I realize what the problem is. What makes it hard is that all card.php files are somewhat different. We definitely need a class to replace the functionality of card.phps

```
if (empty($action) && empty($id) && empty($ref)) {
    $action = 'create';
}
```

if it defaults to 'create' it might do the trick

**Comment by cfoellmann** [comment]
I will do another PR and collect all fixes until it is complete

**Pull request closed without merging**
