### PR TITLE
Adding Hooks in bookkeeping card

### PR DESCRIPTION
**Pull request by AWeerWolf**
# NEW|New Adding Hooks in bookkeeping card

### CODE REVIEW

**Comment by eldy** [comment]
Can you describe the use case you have that need a hook before actions ?

**Comment by AWeerWolf** [comment]
For my module "Bookkeeping Template" I only use "onConfirmCreate_onAfterCreateEmptyLine" and "onCreate_onAfterShowFields"
I put the other hooks for future use by other programmers.
The Hook "onBeforeActions" is the same as the one generated by the "Module and Application Builder".
So if your "Module builder is creating the hook, I thougth I shoud do the same in the "bookkeeping card".
This hook could be use for exemple if you want to check if the "doc_ref" already exist and warn the user.

If you want me to delete some hooks, juste let me know.

**Comment by AWeerWolf** [comment]
Hello,
What do we do with the missing hooks ?
Seems that in the mean time we have a conflict with another branch.
Regards,
AWeerWolf

**Comment by eldy** [comment]
> onBeforeActions

I can't find any hook onBeforeActions on modulebuilder template.
May be you are thinking of hook "doActions" ? Can you point me the file and line of code with such hook onBeforeActions ?

**Comment by AWeerWolf** [comment]
Yes, this is the doActions.

As there is one hook before action and one after action, i find the name "onBeforeAction" more clear.

You want me to change ?

**Comment by eldy** [comment]
If you need to make code before any action, why don't you use the hook doAction ?

**Comment by AWeerWolf** [comment]
Je ne comprends pas bien le but de cette discussion.
Il n'y avait **aucun** hook dans la page bookkeeping card.php
J'ai donc ajouté les hooks suivants:
- "onBeforeActions" qui s'appelle habituellement "doAction" (Je trouve ce nom mal approprié, donc je l'ai renommé)
- "onAfterActions"
- "onBeforeView"
- "onAfterView"
Je n'utilise aucun de ces hooks donc si vous préférez, on peut les supprimer ou les renommer.

J'ai aussi ajouté les hooks suivants :
- onConfirmCreate_onAfterCreateEmptyLine
- onCreate_onAfterShowFields
J'utilise **uniquement** ces 2 hooks dans mon module "BookKeeping Template" (Modèles d'écritures comptable pour faciliter l'encodage d'OD)

**Comment by eldy** [comment]
PR must be atomic: See CONTRIBUTING.md file (adding several hooks at different places reduce probability to have the PR merged) For exemple here PR is blocked due to bad name of hook: The name of hook to manage actions is "doAction" (executed before any common action), even if name is not fantastic, it is the one used everywhere, so we must reuse the same if we introduce it on a page that does not have it.

**Comment by AWeerWolf** [comment]
Now, it's clear.
I will rename the hook, delete the unnecessary ones  and make a new submit.

**Pull request merged**
