### PR TITLE
Add External Ref for Cheques Deposit

### PR DESCRIPTION
**Pull request by adriennsm**
# Add External Ref for Cheques Deposit

image

https://www.dolibarr.fr/forum/t/reference-externe-remise-de-cheques/20469/2

### CODE REVIEW

**Comment by eldy** [comment]
The definition of "External ref" is : 
"it is in database but never used by dolibarr, never read and never modified by dolibarr".  It is here for need of external app, not for Dolibarr.
If you need a visible field, with possible edition, it means it is not the ref_ext. What would be the purpose of the field you need ?

**Comment by adriennsm** [comment]
Thanks @eldy.
The need is to have a field to indicate the cheque deposit form reference, as provided by the bank.
Does this mean that a new field must be created?

**Comment by eldy** [comment]
> Thanks @eldy. The need is to have a field to indicate the cheque deposit form reference, as provided by the bank. Does this mean that a new field must be created?

Yes, you must first push a PR to change db structure to add a new field. It could have been  "ref_bank", but it may be a better idea to add a field "label" and user is free to enter anything of its choice. So what do you think of just a field "label" (empty by default and free text). So it can also be used for other purpose for people that want to store something else that an ref coming from the bank.

**Comment by eldy** [comment]
@adriennsm I have added the field  "label" into llx_bordereau_cheque so the road is open to implement edition of an input text label at the cheque deposit slip level.

**Comment by adriennsm** [comment]
Thanks @eldy. Sorry for my late reply.
This is perfect with the new field "label".
I try to propose a PR, in a few weeks, to add this field in the cheque deposit UI.

**Pull request closed without merging**
