### PR TITLE
Resource fixes

### PR DESCRIPTION
**Pull request by IonAgorria**
Several fixes for resources module
NOTE: I was not sure how to populate the resource_type in resource add template, so I used $resource_obj if $resource_type is empty.

### CODE REVIEW

**Comment by eldy** [comment]
You should not have to use resource_obj because resource_type should always be set. Hown can you reproduce case when did you experience resource_type empty ?

**Comment by IonAgorria** [comment]
I just tried to link the resource from a thirdparty and the entries in table where created without resource_type

**Comment by eldy** [comment]
Can you describe process you do to "try to link a resource from a thirdparty" ?

**Comment by braito4** [comment]
Just add RESOURCE_ON_THIRDPARTIES = 1
Then you will be able to add resources to thirdparties
Even doing that you always won't be able to see the list of the resources linked to a event or thriparty because if the link resource does't has resource_type the sql fails

**Pull request merged**
