### PR TITLE
dont reopen billed orders

### PR DESCRIPTION
**Pull request by altairis-tof**
when an order is billed, it should not be modified anymore

### CODE REVIEW

**Review by eldy — COMMENTED** [review]
Why not ? 
The status billed or not is independant if the workflow of staus of order. We can bill or not an order at begin of order status, even when not yet delivered, so going back should not depend on billed or not

**Comment by altairis-tof** [comment]
Hello @eldy Maybe we could add a hidden constant for those who dont want their teams to do such things ?

**Comment by eldy** [comment]
> Hello @eldy Maybe we could add a hidden constant for those who dont want their teams to do such things ?

Yes you can. Option to allow "to block" looks better than blocking by default (will match more use cases).

**Comment by altairis-tof** [comment]
> > Hello @eldy Maybe we could add a hidden constant for those who dont want their teams to do such things ?
> 
> Yes you can. Option to allow "to block" looks better than blocking by default (will match more use cases).

Ok @eldy, we have new constant ORDER_DONT_REOPEN_BILLED

**Pull request merged**
