### PR TITLE
FIX: Bug on order and supplier invoice numeraion mask

### PR DESCRIPTION
**Pull request by fmarcet**
Must use supplier code when are generating order or supplier invoice.

### CODE REVIEW

**Comment by rdoursenaud** [comment]
I think this is an ugly hack :-1: 
The fix should go into `get_next_value()` based on its third parameter `*_fournisseur`.

**Comment by fmarcet** [comment]
The truth is that first I thought it on <code>get_next_value()</code>, but the third parameter can be commande_fournisseur and facture_fourn. I think that in the future these tables will be renamed in supplier_order and supplier_invoice or something like that and the rule <code>*_fournisseur</code> will stop being valid. I thought that modify the numbering module was easier to maintain. That's why I opted for this option, but as I told you, I also thought about the other.

**Comment by rdoursenaud** [comment]
I think that an explicit fix using `commande_fournisseur` and `facture_fourn` would be far better and could not be missed upon refactoring as a quick grepping would reveal them quite easily.
Changing an object property is bad because you have no control over the next user of that object and you will just create a mess for him even if the object scope is local in this case.

**Comment by fmarcet** [comment]
I reopen my previous pull request #2759 that modifies <code>get_next_value()</code>

**Pull request closed without merging**
