### PR TITLE
Allow negative quantity in TakePOS

### PR DESCRIPTION
**Pull request by andreubisquerra**
https://github.com/Dolibarr/dolibarr/issues/13037 Feature request

### CODE REVIEW

**Comment by eldy** [comment]
This would generates a lot of problems.
If we add a negative line into POS, we may have also a negative invoice. And negative invoice is not allowed. It must be a "credit note invoice". Does this generate a credit note when you use the - in takepos ?

**Comment by andreubisquerra** [comment]
Yes, my idea is if a customer change a 'shoes' as:

Shoes A    -1      50€
Shoes B     1       70€
Total      20€

I think here we don't generate a problem.
Than I work in the next commit and if is a negative invoice will be a 'credit note invoice'.
What do you think?

**Comment by eldy** [comment]
Even with case
Shoes A -1 50€
Shoes B 1 70€
Total 20€

In the same manner than 
Shoes A -1 70€
Shoes B 1 50€
Total -20€

both will generate troubles because it does not match the accounting rules. The problem will occurs when we will make the double party accounting or turnover or vat to pay or not calculation. when we make a -50, we must know if this is a -50 because of a credit note (return of product) or a -50 because of a commercial gift (no turnover counted in this case). For return of product we MUST have a credit note.

This is how we should proceed: 
We must follow the same logic than into the Dolibarr backoffice usage: Return products and new bought product must be processed in 2 different steps, and 2 different documents. The customer may decide to not purchase other product and want a refund or a mix. If we follow the backoffice rules, we can do it. So:

First, we have a "Make a return button" instead of "Make a new sale". In this case, we accept only the products that are returned. And we create a credit note with all lines (so and invoice with all negative lines). We do not accept returns and new purchases in same sale, we will make two different sales.

So after first step, we have a good credit note in backoffice. This credit note can be "refunded" (we make a payment on it) or converted as "credit marked as available" (we give a paper to customer so customer can come several weeks later to reduce amount of its next purchase with it). 

If customer or seller decide to refund by a refund of money, seller can switch in backoffice to record the payment (so no need to develop something urgently in TakePos, at least not to start). 
Seller record payment, and give money to customer. End of step 1. There is no step 2 in such a case.

But if consumer decide to purchase other products, so we must convert the credit note as "credit available" for another purchase. We can switch to backoffice to do this for the moment.

Then we made the second step. We create a Sale with the new purchase product. And we select the pending credit available to include it in the new sale (this will reduce the amount of new invoice). Exactly like we do from backoffice. The customer pay the 20 euros instead of 70. The new invoice will show that Product B 70 - Credit note for product A 50 = 20 euros.

A third situation can occurs, the new product 50 is lower than old one 70. In such a case, you can go in backoffice to split the credit available of 70 into 20 + 50. Then when making the sale you can choose the credit available of 50, the new invoice will be zero. It is free. And there is still 20 euros in the list of "credit available" that can be consumed later in a next purchase.

This look more complex but in fact it is not. It solve a lof of troubles later and it will work in a similar manner than backoffice. Above all, it will works like the law expect to for all european countries.

It is not necessary to have all the process managed by TakePos. A simple Popup to say "Switch to backoffice for this step" may be enough to start instead of duplicating the logic into TakePOS, and you can implement only the generation of the credit note with the returned product and the selection of credit available when making the new real purchase.

**Comment by andreubisquerra** [comment]
Solved with https://github.com/Dolibarr/dolibarr/pull/15155

**Pull request closed without merging**
