### PR TITLE
FIX #5024 Customer invoices pending payment box should show total amount

### LINKED ISSUE #5024: Feature request: Option to show TTC or HT amounts in Dolibarr dashboard boxes
To create an option to allow the user to select showing TTC or HT amounts in dolibarr dashboard boxes. 

You can read the discussion in #5025.

### PR DESCRIPTION
**Pull request by marcosgdf**
FIX #5024 Customer invoices pending payment box should show total amount

Close #5024

### CODE REVIEW

**Comment by eldy** [comment]
Most companies prefer to see due amount without tax (that is real amount because vat will be retreive).
Also for consistency, currently, it seems that all boxes show amount without tax.
I would prefer to see a hidden option MAIN_BOXES_SHOW_AMOUNT_WITH_TAX

**Comment by marcosgdf** [comment]
I disagree. Companies want to know how much money do customers owe them, taxes included because they have to pay them to the tax administrations.

I would consider doing the opposite. Consider using this as the general function and add a hidden option to those little companies that do not want to see the amount of taxes they have to get from their clients.

It also doesn't need to be a hidden option, we could add it to the Boxes admin page

**Comment by atm-maxime** [comment]
I agree with @marcosgdf, in a company when we talk about a proposal or an order, we speak without taxes. But when it comes to invoices, we always speak including taxes because this is the amount that the customer really owe to us. The outstanding amount for a customer is including taxes and when you want to calculate the average payment period, you use the global outstanding that includes taxes.

Beside, I just noticed that in the invoice list, the column giving the "remain to pay" for each invoice and the total is no longer present. This was a useful column to know exactly your global outstanding.

**Comment by eldy** [comment]
We can't have total that sometimes are with tax and sometines without, without providing information.
We can't ask user to see the code to know what is the reference amount (with or without tax).
Currently there is no problem, because all amount on boxes are without tax, if we change this on at least one boxes, we must provide a way for user to know, this box does not show same information than others.

**Comment by marcosgdf** [comment]
What do you think about adding an option in the boxes config page to allow the user to choose? I know this would convert the bug to a feature request

**Comment by accett** [comment]
IMHO tax included is better.

**Comment by eldy** [comment]
Yes, it means it is a PR.
Introducing a way to provide more option on a box/widget will be necessary for future. This case is not the only one we would face. Currently, there is one field called "note" to save options of a box/widget at the global level.
But they are not used because we can't edit a box line in the admin widget/box page.
We should introduce this feature.

Or, there is also a field "maxline" and "params" (not used) so user can also set/save parameters, but here at each user level. Each user can decide number of lines and other options for a box and we can store this into this field. Not yet used, because no boxes/widget can be set currently from user dashboard (the graphic boxes of products has option but choice is stored into a cookie instead of the "params" field for the moment). But it is another option to store the choice here.

**Pull request closed without merging**
