### PR TITLE
Fix Bad link for salaries payments and display user concerned in thirdparty column 

### PR DESCRIPTION
**Pull request by mapiolca**

### CODE REVIEW

**Comment by eldy** [comment]
I can't reproduce the bug. Currently, for payment salaries, the field "Thirdparty" is empty (there is no thirdparty for payment of a salary). And it is the expected behavior. It is same for expense reports.
May be we can introduce another column "User".

**Comment by mapiolca** [comment]
The bug concerns just the bad link. 

The other commit is just an adding. I don’t think it’s useful to add more column, I think it’s better to use existing column. It will be better for smallest screens.

**Comment by atm-maxime** [comment]
I think we could display the user in the same column as suggested. I agree there's no thirdparty on salary payment (in the object sense) but in this case, the user is the third-party (in the common sense). Same with expense reports.

**Comment by eldy** [comment]
Ok, so i pushed the bug into a separate fix. For a better understanding of issue, it is better to separate issue that fix bugs and issue that introduces new things.

**Comment by mapiolca** [comment]
Ok

**Pull request closed without merging**
