### PR TITLE
FIXED Allowed 0 to be used as an account mask

### PR DESCRIPTION
**Pull request by rdoursenaud**
0 is used by some accounting systems and software.

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Yes, it is always set but is set to NULL when no data exists (installation time) and isset checks if it is set _and_ not NULL.

Since the form always return a value (an empty string if the field is left blank) and it does not make sense to not have an account prefix, I feel we could get rid of the test and just set the value to null if the field is left empty so we have it replaced by the default value.

I've updated the code accordingly. Let me know what you think.

**Comment by rdoursenaud** [comment]
Travis is upset by old rules checking phpdoc comments.
Since we use doxygen, these can safely be ignored.

**Comment by eldy** [comment]
I don't understand fix. Can you provide an example of mask wher bug appears ?

**Comment by rdoursenaud** [comment]
Yes just a 0 (Cegid needs it…)

**Comment by aspangaro** [comment]
I confirm this fix, Cegid by default provide an accountancy supplier number beginning by 0. Example : 0DOLIBARR & Dolibarr don't accept only "0" in this field.

**Comment by eldy** [comment]
I included a patch manully

**Comment by rdoursenaud** [comment]
@eldy I'd love if you could reference the commit number in your comment when you apply your own fixes (which is better BTW).
You just have to paste the commit hash like this 89b22be063b2c1f2b032e3e9a7b416cfa3c11859.

Thanks anyway!

**Pull request merged**
