### PR TITLE
NEW - Add an advanced permission to read price (if const MAIN_USE_ADVANCED_PERMS on)

### PR DESCRIPTION
**Pull request by BB2A-Anthony**
# NEW|New [*Add right for read price if const MAIN_USE_ADVANCED_PERMS*]
[*if we need to give access to the product to users but they do not necessarily need to know the prices but only to find informations*]

### CODE REVIEW

**Comment by shihab0020** [comment]
Dear thanks for new option for hiding selling price , but still there have some area too.
Home screen widget Products/Services: last 5 modified still can see selling price
product/index.php Full List Latest 15 products/services which were modified can see selling price

**Comment by BB2A-Anthony** [comment]
I'm looking at this, is there anything else?

**Comment by BB2A-Anthony** [comment]
> Dear thanks for new option for hiding selling price , but still there have some area too. Home screen widget Products/Services: last 5 modified still can see selling price product/index.php Full List Latest 15 products/services which were modified can see selling price

It's done in https://github.com/Dolibarr/dolibarr/pull/22012

**Comment by shihab0020** [comment]
> > Dear thanks for new option for hiding selling price , but still there have some area too. Home screen widget Products/Services: last 5 modified still can see selling price product/index.php Full List Latest 15 products/services which were modified can see selling price
> 
> It's done in #22012

thanks

**Comment by shihab0020** [comment]
> I'm looking at this, is there anything else?

Dear is it possible /product/stock/product.php also, if it possible good, then Where House people can check product stock without knowing price, 
apricating for grate job.

**Comment by BB2A-Anthony** [comment]
> > I'm looking at this, is there anything else?
> 
> Dear is it possible /product/stock/product.php also, if it possible good, then Where House people can check product stock without knowing price, 
> apricating for grate job.

I'm looking for the stock I'll do another pr

**Comment by josett225** [comment]
Hi @bb2a 
Many thanks for this new perms.

Do you know if it is possible to add perms on the product accounting configuration?
Several times when adding products we need to add or change the product accounting number by a mass action by category. This can be done by the product manager instead of the accounting manager. 

Many thanks 
Jose

**Comment by BB2A-Anthony** [comment]
> Hi @bb2a 
> Many thanks for this new perms.
> 
> Do you know if it is possible to add perms on the product accounting configuration?
> Several times when adding products we need to add or change the product accounting number by a mass action by category. This can be done by the product manager instead of the accounting manager. 
> 
> Many thanks 
> Jose

you may be able to read only for accounting

**Comment by BB2A-Anthony** [comment]
> > I'm looking at this, is there anything else?
> 
> Dear is it possible /product/stock/product.php also, if it possible good, then Where House people can check product stock without knowing price, apricating for grate job.

It's done here [#22600](https://github.com/Dolibarr/dolibarr/pull/22600)

**Pull request merged**
