### PR TITLE
Can choose several fields to display with extrafield list of table

### PR DESCRIPTION
**Pull request by jfefe**

### CODE REVIEW

**Comment by eldy** [comment]
Sorry conflict

**Comment by rdoursenaud** [comment]
@jfefe you can use
`git rebase upstream/develop`
with `git@github.com:Dolibarr/dolibarr.git` as your upstream remote
then push eventually with `--force` or to a separate branch before pull requesting to avoid conflicts

I believe this should be standard procedure documented on the wiki. What do you think @eldy ?

**Comment by eldy** [comment]
Thanks, I know how to deal manually, but to avoid to have a bottlenek at the last step (validation of the 2 project leaders), good pratice is to let the submitter manage its conflict. Submitter is at best place than project validator because he know what he wanted to do and this allow to keep project validators (level jedy) to spend more time to check each submit.

**Comment by rdoursenaud** [comment]
@eldy I think you misunderstood me. What you say was exactly my point ! And I suggested a git feature to help dealing with it on the contributor side.
If the contributor rebases its code upon current develop, there can't be any conflict. This is the standard procedure to contribute to the Linux kernel. I was proposing to document it so we can refer contributors to proper documentation when such problem arises.
Hope this clears thing a bits and @jfefe sorry to highjack your PR.

**Comment by jfefe** [comment]
Ok rebase done. Do I have to create a new pull request?

**Pull request merged**
