### PR TITLE
fix calendar per user

### PR DESCRIPTION
**Pull request by laudeco**
fix the calendar per user by displaying :
* Saterday and sunday (like other calendars)

And fixing the bug when the user changes the displayed hours.

### CODE REVIEW

**Comment by laudeco** [comment]
@eldy I don't understand why I got an error in PHP 5.3

**Comment by eldy** [comment]
When error is "!" instead of "X" in travis, problem is not into application but on travis platform. You can ignore it.

About the fix. The nb of days depend on the filter "Visible days range". It can be modified into setup.

About fix on display hours. I can't reproduce. May be it is a bad understanding on filter hour range.
When it is 9-18, it means event into 9 and 18:00 but if event is at 18:30, it is excluded. Did your fix respect that or change that ?

**Comment by laudeco** [comment]
Hello,

Ok, I have to change hour, my mis understanding.
But this fix is about the display of Saturday and Sunday in calendar per user

**Comment by eldy** [comment]
So your fix introduce visibility on saturday and sunday all the times ?
It does not take in considefration the option days  1-5  (to say day 1 to 5 of week) ?

**Comment by eldy** [comment]
Structure of page for calendar per user was modified in 7.0 enough to have this PR no more compatible, so i close it.

**Pull request closed without merging**
