### PR TITLE
FIX desirestock can now be set to 0

### PR DESCRIPTION
**Pull request by c3do**
Without this fix, it is impossible to set desiredstock to 0.

### CODE REVIEW

**Comment by atm-maxime** [comment]
Shouldn't you fix this in previous versions ? You can  PR this in 9.0 and it will be applied on 10, 11 and develop after.

**Comment by c3do** [comment]
I'm just contributing to my level. You could also fix it by yourself. I detect a bug, I fix it ... You're welcome!

**Comment by atm-maxime** [comment]
Hi ! Sorry, didn't mean to be rude... I just wonder if this issue was also present in previous versions... Thanks for contributing 😊

**Comment by c3do** [comment]
Indeed, the bug is present at least since v10. I await the closure of this PR and I will correct the others afterwards.

**Comment by atm-maxime** [comment]
Ok thanks. As I said, the best way to fix a bug is to fix it in a lower branch, because it will be merged into higher branches afterwards. A fix done in 8.0 will be automatically done by merge in 9.0, 10.0 11.0 and develop. Eldy merged branches like this to propagate bugfixes. If you do it in develop, there's no merge possible in lower branches, so the fix has to be done manually in all other branches.

**Comment by c3do** [comment]
i did not know that. Thank you. I will create another PR.

**Pull request closed without merging**
