### PR TITLE
FIX total rounding avoid unit rounding into price function

### PR DESCRIPTION
**Pull request by ghost**
In case of a 4 decimal on PU and 2 on total, price function just show the minimum of two.
We add the support ( as price2num ) of the rounding parameter MT,MS,MU in order to allow to show PU with 4 dec, and total with 2.

We juste correct it on bill for the moment and we'll push the rest if you agree to this

PS : tracis failed because of your last commit on 3.9 ;-)

### CODE REVIEW

**Comment by eldy** [comment]
You are making some rounding when "showing" data. We should not show another value than what is real value.
If a round is required, this rounding should have been done before (for example when instering data into database, or just after a computation is made). Can you provide a screen shot of visible amount that is wrong ?

**Comment by ghost** [comment]
Hi Eldy, i think i explain it wrong.

The problem is in the showing method price. If i define the rounding precision in this screen with 2 differents values, i'll never see the greater one because the price function return a rounding value of the smallest number (between MAIN_MAX_DECIMALS_UNIT and MAIN_MAX_DECIMALS_TOT) so it's the same result if i have only one parameters.

capture du 2016-02-24 17-07-17

We have some customers who need to show a great precision for the UP but not the total who is larger and the precision become useless. (I agree, the most of customer have a rounding of 2 for the both and is ok obviously in this case)

The fix give this result
capture du 2016-02-24 17-12-24

Before the Fix the unit price had only 2 decimal even though I set 4 decimal in conf

**Comment by eldy** [comment]
No, if you set a unit price accuracy to 5 and and total accuracy of 2, dolibarr will not use the smallest number (between MAIN_MAX_DECIMALS_UNIT and MAIN_MAX_DECIMALS_TOT)
It will use MAIN_MAX_DECIMALS_UNIT for unit pric and MAIN_MAX_DECIMALS_TOT for total.

Most users are not using 2 and 2. Most users are using 2 for total prices and 5 for unit prices (this is the rule for nearly all countries in europe). Everything is working correctl with 2 and 5 so should also work with 2 and 4 (that is a lower accurancy that the default value).

If you have only 2 decimal on screen before the fix, it just because you enter an number with only 2 decimal and dolibarr optimize space on screen by not showing ending 0. It keeps only the minimum number of decimal (min of MAIN_MAX_DECIMALS_UNIT and MAIN_MAX_DECIMALS_TOT) to save space when the is no more decimal but if you try to enter 1.2345678 and you will see that everything is working correctly on unit price, you will get your 4 decimals as you defined into setup.

I think what you want is an option to say:
When number of decimal is lower than the accurancy, then show the 0 until reaching the accurancy.
Am i right ?

**Comment by ghost** [comment]
I agree to your point of view, just a showing method, i'll do a special for my customer,

regards ;)

**Pull request closed without merging**
