### PR TITLE
NEW [ task #851 ] Add a new field: Commercial name

### PR DESCRIPTION
**Pull request by marcosgdf**
Build fail has nothing to do with this PR

### CODE REVIEW

**Comment by eldy** [comment]
When invoice needs another dedicated name, in most cases, it means it is another enteprise. I am not sure using different name is legal. If this is different company name, it probably means this is different professional id too. So may be different the second name is a parent or child company of other. 
Do you have an example of company with 2 different name but with same professional id ?

**Comment by KreizIT** [comment]
In France, you can have multiple name. It's usefull if you have multiple activities. You are able to emit document under different name if you also specify your professionnal ID and your official name (Raison sociale)
Cf : http://vosdroits.service-public.fr/professionnels-entreprises/F23283.xhtml

**Comment by aspangaro** [comment]
I confirm this information, really usefull, It is used a lot when that a company is a part of a network and possesses a sign(brand).

Example: Mc Donald / EURL XXX

On the other hand Kreiz, the trade name has to be on the extract Kbis, you should not invent names like that otherwise we speak about company(society) creates de facto and it is not cool.

**Comment by marcosgdf** [comment]
It is also really used in Spain.

You can call your enterprise "PAPERS 2012, Sàrl" but in you shop you are called "MULTIPAPERS". It is useful because suppliers and clients will call you MULTIPAPERS even if the formal name is "PAPERS 2012, Sárl".

**Comment by eldy** [comment]
I would prefer another name for this fields
so usage of field may vary according to needs.
What are you think of

"alias name"
or 
"alternative name"

Goal is to be clear this field as no legal meaning, is not mandatory, and everybody can use it for usage of its choice.

**Comment by KreizIT** [comment]
@aspangaro : Sure, I never said that trade name is totaly free of use. You must declare it of course ;)

**Comment by marcosgdf** [comment]
Well... I can agree that a commercial name is an "alias" of the company name but commercial names are so common that I don't find the reason to rename it to "alias name"...

**Comment by eldy** [comment]
The only fact I did not understand what is a "commercial name" let me think other users and dev will ask question too.
A "commercial name" let user and dev think this field is here for the official commercial name. "commercial name" just means nothing for me. Some people, like me, may understand it is "official name". "Commercial" can be understood as "business name", so in such case it means "official" name. And here it is just the opposite. Depending on countries and languages, this is very confuse.
"alternative name" is more clear for me it is not the official "key".

**Comment by KreizIT** [comment]
Just have a look on the link http://vosdroits.service-public.fr/professionnels-entreprises/F23283.xhtml
It's explain all 3 kind of legal name for a french company.
Pretty sure that for other country it's nearly same thing.

**Comment by rdoursenaud** [comment]
I also vote up :+1: 
The correct terminology is "[trade name](https://en.wikipedia.org/wiki/Trade_name)" (« Nom commercial » in french).
It is indeed one of the official names. You can even have multiple ones.
It has nothing to do with trademark. You can trademark your trade name but it is not a requirement (at least in France).
I used to have one in my previous activity where the registered legal name was my own name but my trade name was EMA Tech.
@KreizIT link is very straightforward.
INPI has also something similar at http://www.inpi.fr/fr/societes-registre/les-noms-de-votre-societe/qu-est-ce-qu-une-denomination-sociale-un-nom-commercial-une-enseigne.html

**Comment by aspangaro** [comment]
@marcosgdf  Can you resolve the merge conflict ?

**Comment by marcosgdf** [comment]
Done.

**Pull request merged**
