### PR TITLE
Not shippable if quantity in all order are greater than in stock

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by frederic34** [comment]
I can change like this :
2015-11-17 08_36_49-dolibarr - commandes
2015-11-17 08_37_24-dolibarr - commandes
Order is shippable but there isn't enough products for other orders.

**Comment by eldy** [comment]
What mean 15/16 ?
Can you introduce a small text (xxx and yyy in example) to have things clear. For example

15 xxx / 16 yyy

**Comment by frederic34** [comment]
15 in stock, 16 in orders

**Comment by eldy** [comment]
So 15 = real stock

But 16 ?
16 = virtual stock (real stock - opened customer order + opened supplier order) ? 
or 
16 = opened customer order ?

**Comment by frederic34** [comment]
16 = opened customer order
when there are supplier order, a text is added with "zz in supplier order"

**Pull request merged**
