### PR TITLE
fix link error on const page

### LINKED ISSUE #8439: Bug: "Setup other" whole table is a link.
# Bug
"Setup other" whole table is a link.

## Environment
- **Version**: 7.0.0
- **URL(s)**: http://.../admin/const.php?mainmenu=home

## Expected and actual behavior
Actual behavior: If you click inside the table and want to add a new key, the wiki page for "Setup other" is opened. The whole table is a link
Expected: Only "hier überprüfen" (in German, I guess it's "check here" or similar in EN) is a link, not the table

## Steps to reproduce the behavior
Open "Setup Other" page and click somewhere on the table.
On hover all table entries/lines are underlined

## Attached files
Screenshot 2018-03-22 um 19 01 16

### PR DESCRIPTION
**Pull request by lampi87**
# Fix #8439
Table not longer a link and useable

### CODE REVIEW

**Comment by eldy** [comment]
PR on files into langs/xx_XX where xx_XX is not english are useless. Files are erased by transifex translation en en_US. If pb is in another language, fix translation on transifex., can you fix it on transifex ?

**Comment by lampi87** [comment]
Hello Eldy,
thank you for the information.
Unfortunately, on transifex it seems to be correct. But the end tag "</a>" is inserted wrong.
How to fix that?

**Comment by eldy** [comment]
The end tag should also be editable in transifex.
If it's ok in transifex, it will be ok also in next stable version. Nothing to do more, just wait the transifex sync that will overwrite language files into GIT.

**Comment by eldy** [comment]
Close after transifex sync

**Pull request closed without merging**
