### PR TITLE
Vagrant

### PR DESCRIPTION
**Pull request by rdoursenaud**
Adds a nice vagrant box suitable for Dolibarr development along with some fixes and a neat manual.

Note that for this to work great, we need to make the symlink point towards the right initdata*.sql for maintenance branches.

This is the first basic box but I plan to add more for specific development needs.

### CODE REVIEW

**Comment by eldy** [comment]
I would like to avoid to have a symlink into official sources.
Reason is that is creates problems with some package tools or packaging policy rules of some distribution. It also does not work correctly on other os systems.
Well advantage of this is lower for the moment than problems.

I suggest this. You put the file ***latest.sql as an ignore file (so not into official sources). And people who want to use the "varant" feature create the symlinks manually.

**Comment by rdoursenaud** [comment]
OK, I removed the symlink and hardcoded the machine to use the latest 3.5.0 dump.
Just for the record, could you be specific about which distribs have problem with them? They are useful as hell!
Thanks.

**Comment by eldy** [comment]
This is not distribution itself but tools to build or check package for distribution:
unzip, rpm, rpmlint for redhat, lintian for debian, git-buildpackage, ...
Some have controls to report warnings when they found a duplicate file/link, some complies about permission we must manage differently for symlink. A big headach.
Then there is doliwamp (windows) that just save a broken file into package when there is a link

Having uniform process to build so different packages for all distrib is so a headach that we should avoid symlinks when we can (there is no symlink at all currently, keeping this will save us time).

**Comment by rdoursenaud** [comment]
Ok, I perfectly understand the need to keep distribution packages clear of symlinks but I was under the assumption that the dev subdirectory was only for developers and not part of standard packaging.
Anyway since it looks that initdata is only used in travis and vagrant at the moment we can cope with the maintenance overhead.
Thanks.

**Comment by eldy** [comment]
Le 29/11/2013 16:02, Raphaël Doursenaud a écrit :

> Ok, I perfectly understand the need to keep distribution packages
> clear of symlinks but I was under the assumption that the dev
> subdirectory was only for developers and not part of standard packaging.
> Anyway since it looks that initdata is only used in travis and vagrant
> at the moment we can cope with the maintenance overhead.
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/1329#issuecomment-29521180.

You are right... but also wrong.

dev dir is not part of binary packages. but is part of sources packages.
For example, for debian, we must use intermediate sources packages than
are nearest the git sources. So for user, this dir does not appears into
final package, but for the "intermediate" packages, it is.
Example the file  dolibarr-*.tar.gz  as found into
http://www.dolibarr.org/files/lastbuild/package_debian-ubuntu/
Such packages are also part of release process and checked and
manipulated by miscellaneous tools, even if such package never appears
onto sourceforge binary distribution platform.

## 

Eldy (Laurent Destailleur).

EMail: eldy@destailleur.fr
Web: http://www.destailleur.fr

Dolibarr (Project leader): http://www.dolibarr.org
To make a donation for Dolibarr project via Paypal: contact@destailleur.fr
AWStats (Author) : http://awstats.sourceforge.net
To make a donation for AWStats project via Paypal: contact@destailleur.fr
AWBot (Author) : http://awbot.sourceforge.net
CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by rdoursenaud** [comment]
Thanks for taking the time to answer. I now see the hassle symlinks could cause. I'll try to not forget ;)

**Pull request merged**
