### PR TITLE
Qual: Fix phan/phpstan notices 💊 

### PR DESCRIPTION
**Pull request by mdeweerd**
# Qual: Fix phan/phpstan notices

Fix notices by adjusting phpdoc

### CODE REVIEW

**Comment by frederic34** [comment]
this change cause error https://github.com/Dolibarr/dolibarr/commit/5203d99c2f4cd448f9eac684551194775f25f7e8

**Comment by mdeweerd** [comment]
> this change cause error [5203d99](https://github.com/Dolibarr/dolibarr/commit/5203d99c2f4cd448f9eac684551194775f25f7e8)

Thanks, I reverted it to static.

**Comment by mdeweerd** [comment]
I added an exception in phpstan.neon.dist - test_buttons give 'true' to confirm, not an array - this is pre-existing, so ignored for the sake of fixing ci.

**Comment by mdeweerd** [comment]
@eldy 6his fixes CI.

**Pull request merged**
