### PR TITLE
Update commondocgenerator.class.php

### PR DESCRIPTION
**Pull request by defrance**
add : outstanding limit on ODT 
fix  : only public note are display on ODT (private stay private)

### CODE REVIEW

**Comment by FHenry** [comment]
Did you check setMysoc into societe.class.php ? This is $this->note_private affeced with global $conf->global->MAIN_INFO_SOCIETE_NOTE. 
$mysoc into commondocgenerator is for the main company not the thirdparty replacement variable

**Comment by jfefe** [comment]
One question : this information (company note) is public or private?

**Comment by defrance** [comment]
we have 2 note : one public and another private, in my vision we do not permit to have the private note on a document, else it's a public note too ...

**Comment by jfefe** [comment]
@defrance69 with mysoc object, we have only one note, used by $conf->global->MAIN_INFO_SOCIETE_NOTE

**Comment by FHenry** [comment]
yes $mysoc is generally use to fill the header and footer of document with the information of the main company of dolibarr set up in Configuration->Company this is the seller not the customer.
In this one, we have only one field note.

**Comment by defrance** [comment]
All appologies, i'm in the wrong function 
get_substitutionarray_mysoc
instead
get_substitutionarray_thirdparty
'outstanding_limit'=>$mysoc->outstanding_limit,

Made corrections and submit

**Pull request merged**
