### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by FrederikHeinrich**
For using the Fichinter in other classes.

e.g. `public $fields=array(
		'rowid' => array('type'=>'integer', 'label'=>'TechnicalID', 'enabled'=>1, 'position'=>1, 'notnull'=>1, 'visible'=>-1, 'noteditable'=>'1', 'index'=>1, 'comment'=>"Id"),
		'userForm' => array('type'=>'integer:userform:custome/mobileformular/class/userform.class.php', 'label'=>'UserForm', 'enabled'=>1, 'position'=>1, 'notnull'=>1, 'visible'=>3,),
		'serviceLink' => array('type'=>'integer:fichinter:fichinter/class/fichinter.class.php', 'label'=>'ServiceLink', 'enabled'=>1, 'position'=>2, 'notnull'=>0, 'visible'=>3,),
		'prjectLink' => array('type'=>'integer:project:projet/class/project.class.php', 'label'=>'ProjektLink', 'enabled'=>1, 'position'=>2, 'notnull'=>0, 'visible'=>3,),
	);
	public $rowid;
	public $userForm;
	public $serviceLink;
	public $prjectLink;`

### CODE REVIEW

**Comment by Tim-Otte** [comment]
The class declaration of `Fichinter` is duplicate...

**Comment by FrederikHeinrich** [comment]
> The class declaration of `Fichinter` is duplicate...

that was not by me lol

**Comment by Tim-Otte** [comment]
> > The class declaration of `Fichinter` is duplicate...
> 
> that was not by me lol

Ja ja, das sagen alle ;) Wahrscheinlich auf `Strg+D` gekommen

**Comment by FrederikHeinrich** [comment]
> > > The class declaration of `Fichinter` is duplicate...
> > 
> > 
> > that was not by me lol
> 
> Ja ja, das sagen alle ;) Wahrscheinlich auf `Strg+D` gekommen

Denke nicht. 🤔

**Comment by FrederikHeinrich** [comment]
image
"vergessen das mit reinzupacken :o"

**Pull request merged**
