### PR TITLE
FIX You can not set the value to empty

### PR DESCRIPTION
**Pull request by hregis**
@eldy for example when using a multiple choice list, the total deselection of choices is not saved

### CODE REVIEW

**Comment by hregis** [comment]
@eldy same problem in 15, 16 and develop

**Comment by eldy** [comment]
I can't reproduce on v15.
For example with extrafields  chkbxlst   with value  c_typent:libelle:id::active=1  like in example
image
I can unselect all.

Are you using chkbxlst or checkbox type ?

**Comment by hregis** [comment]
@eldy yes with chkbxlst and checkbox, try with extrafield for propal lines by example

**Comment by hregis** [comment]
@eldy  the problem is with extrafields chkbxlst and checkbox for object lines

**Comment by eldy** [comment]
@hregis Is this trouble still present into v18 ?

**Comment by hregis** [comment]
@eldy yes the problem still present in v18 with checkboxes (multichoice) only with extrafields in object lines

**Pull request closed without merging**
