### PR TITLE
New functionality for save 5 oldest versions of pages

### PR DESCRIPTION
**Pull request by lamrani002**
# NEW|New functionality for save 5 oldest web page by updating dolSavePageContent() function to handle it.

### CODE REVIEW

**Comment by rycks** [comment]
Hello all,
could we make a little brainstorm for that sort of things ?

Make a .old.x. ... file ... ok why not, but for example nextcloud has already made a choice for that sort or need, maybe we could do the same choice to be able (one day) to "natively" store dolibarr data into a nextcloud ?

Near than one year before i open a message on french dolibarr forum about that problem:
https://www.dolibarr.fr/forum/t/ged-dolibarr-17-suffixe-des-fichiers-pdf-pseudo-signes-et/

Even if you're working on website part i mean we could use same solution for all needs of "keep archives" of dolibarr documents no ?

**Comment by eldy** [comment]
> ...but for example nextcloud has already made a choice for that sort or need, maybe we could do the same choice...

Sure, why not. 
Because most of us does not know what is the choice of nextcloud, can you describes what is the choice of nextcloud ?
I did not find any doc about this. Asked to chatgpt give me this:

"A previous version of a file named "document.txt" might be stored as something like ".document.txt.v1.timestamp", where "v1" represents the version number and "timestamp" represents the date and time when the version was saved"

Is this good ?
Tihs means archives files are hidden on disk (due to the starting .)  Right ?  Is there any draft of spec about this topic on dolibarr or nextcloud github repositories ?

**Comment by rycks** [comment]
Excuse me dolibarr forum was not the only and the right link, here it is

https://github.com/Dolibarr/dolibarr/issues/24271

**Comment by rycks** [comment]
And the art of my brain last year ... in french

https://inligit.fr/cap-rel/dolibarr/plugin-archivespdf/-/wikis/R%C3%A9flexion%20globale%20GED%20de%20dolibarr

**Comment by eldy** [comment]
@lamrani002 Can you take a look at the summary i added on issue #24271, and try to suggest a rotation of archive files as described into part 1 of the summary to match nexcloud (you can forget part 2 for the moment as Dolibarr is not ready yet).

**Comment by lamrani002** [comment]
i update the code to get like you said
files

**Pull request merged**
