### PR TITLE
targetid and sourceid is not enough

### PR DESCRIPTION
**Pull request by defrance**
if we have the same id in sourceid and targetid we have a selection of some own element

### CODE REVIEW

**Comment by eldy** [comment]
"but the fetchobjectlinked return 2 lines : one for the propal and another for the order"

with which input parameter of fetchobjectlinked do you get this ?

**Comment by eldy** [comment]
OK. I see. Not easy to fix.
Does it works for you now i introduced commit 22979523dbad10ba9843bbaef1b8f3eb7bbb6274 ?

**Comment by defrance** [comment]
my commit correct fine the problem yet without some other fix
the main problem is to find some test case (sourceid and targetid with the same number)
you can use customLink to create your own faulty case

**Comment by eldy** [comment]
You"re commit was ok for the case justsource and justtarget was false. If one was true, it looks to no be enough.
I think my fix is more complete, so I close this bug. Let's open it if it is not enough.

**Pull request closed without merging**
