### PR TITLE
Fix force https

### PR DESCRIPTION
**Pull request by ndrosis**

### CODE REVIEW

**Comment by eldy** [comment]
@ndrosis 
When you do 
$_SERVER["REQUEST_URI"]["L,R=301"], it means  $_SERVER["REQUEST_URI"] is an aray, isn' it ?
And on my php installation, it is a string.
So we should add a test to manage both cases.

**Comment by ndrosis** [comment]
Hi @eldy see here http://httpd.apache.org/docs/2.2/ssl/ssl_faq.html#relative

**Comment by rdoursenaud** [comment]
I agree with @eldy here.
You cannot make any assumption about what's running and certainly not rely on mod_rewrite lightly.
This may perfectly work in some setup and completely break others.
I, for example, use nginx which does not provide such a mechanism, IIS is also behaving differently.
$_SERVER variables are not really reliable and should always be treated carefully.
Forcing HTTPS is always best done at the web server level but relying on the application should not break anything so, please check you're running on the expected environment before doing such dramatic changes.

**Comment by ndrosis** [comment]
@rdoursenaud I agree with you for nginx, IIS but above variable if I am not mistaken is for apache/ mod_ssl

**Comment by eldy** [comment]
Hi nikos.
I am running on apache, and the $_SERVER["REQUEST_URI"] is NOT, on my environment, an array but a string. So the $_SERVER["REQUEST_URI"]["L,R=301"] just returns empty, same for _SERVER["REQUEST_URI"]["L,R"] on my environment, so please just add a test  
if (is_array()) 
to be able to manage correctly all cases: Old behaviour if var is not an array but a string and new behaviour when it is an array, like it seems to be for your environment.
A simple test should make all cases working.

**Pull request closed without merging**
