### PR TITLE
FIX multiple problems when MULTICOMPANY_TRANSVERSE_MODE

### PR DESCRIPTION
**Pull request by hregis**

### CODE REVIEW

**Comment by hregis** [comment]
@mdeweerd  ?? "CI / windows-ci" error ? ;-)

**Comment by mdeweerd** [comment]
@hregis It's having trouble to download the sql installation file. It's not systématic.
However it seems that this is not the case in older windows version. I prepared a PR.

**Comment by hregis** [comment]
@eldy it's ready for me, in transverse mode, a basic user with the permissions of create a user or group can not create users and groups and buttons/menus for to create are grey

**Comment by hregis** [comment]
@eldy in the futur, with the field "enabled" in the llx_rights_def, we will have the possibility to deactivate the possibility of assigning a permission under certain conditions

**Comment by hregis** [comment]
@eldy this is a fault positive phan error :-) (an open wound)

**Comment by mdeweerd** [comment]
~Almost or~ already resolved in #29298 .

**Pull request merged**
