### PR TITLE
New:Constant MAIN_EXTERNAL_USERS_CAN_ALSO_SEE_SUBSIDIARIES_COMPANIES to allow access to any thirdparty for external users

### PR DESCRIPTION
**Pull request by bafbes**
New:Constant MAIN_SHOW_SOCIETE2EXTERN to allow access to any thirdparty for external users

### CODE REVIEW

**Comment by frederic34** [comment]
@bafbes can you use a full english contant name like MAIN_SHOW_THIRDPARTIES_TO_EXTERNAL_USERS (this is une suggestion)

**Comment by eldy** [comment]
What is a goal of this paramater. If an external user need access to any thirdparty, it just means it is an "internal access" user.
The definition "external user" means "access to only its thirdparty". If an external user need to see any thirdparty, it means it is not an external user but an internal user. Why not just changing the profile of the user ?

**Comment by bafbes** [comment]
In our case, an organization needs to make invoices to various of its substructures. This is the reason for wich these substructures are managed as customers. Also,  These substructures need also to see each other. This option is to give them this ability.

**Comment by bafbes** [comment]
I think using a more explicit name like MAIN_SHOW_THIRDPARTIES_TO_EXTERNAL_USERS is a good thing

**Comment by frederic34** [comment]
Do you need that user can see the subsidiaries of the companies ?

**Comment by bafbes** [comment]
This is what is intended by this option.

**Comment by eldy** [comment]
Do you mean the new option name should be
MAIN_EXTERNAL_USERS_CAN_ALSO_SEE_SUBSIDIARIES_COMPANIES ?

**Comment by eldy** [comment]
@bafbes Can you confirm me the name for the constant
MAIN_EXTERNAL_USERS_CAN_ALSO_SEE_SUBSIDIARIES_COMPANIES
is a good name compared to the result you expect with the feature ?

**Comment by bafbes** [comment]
Yes, I think also that functional explicit names are better. Perhaps MAIN_EXTERNAL_USERS_CAN_SEE_SUBSIDIARY_COMPANIES is yet better and shorter

**Comment by eldy** [comment]
Ok for MAIN_EXTERNAL_USERS_CAN_SEE_SUBSIDIARY_COMPANIES. Can rewrite your PR to use this name ?

**Comment by bafbes** [comment]
Done

**Pull request merged**
