### PR TITLE
update accountancy breakdown

### PR DESCRIPTION
**Pull request by elarifr**
- added select all/none 
- column filter & added by date / rowid
- clear search filter link
- updated productaccount to display invoice and account. missing menu in dolibarr
  -review breakdown customer check product account & type / vs facturedet produc_type display both value to let user choose good account
- change filter based on datef + facture + rowid

### CODE REVIEW

**Comment by eldy** [comment]
Can you try to solve conflict ?
Also, don't change any file into lang dir fr_FR. It is a wat of time because such iles are erased frequentlyby transifex synchro. To change fr_FR lan, you must use transifex.com

**Comment by elarifr** [comment]
Hi Eldy,
When i try to make a new pr it is still in conflict
Should i close this pr and try to make a new one ?
i have included a change in product/card.php to have a selet_account combobox when accountancy is enabled. no change are made for code_buy & code_sell iyt store plain account_number not the rowid.

**Comment by rdoursenaud** [comment]
@elarifr To avoid this, you should have made a topic branch (working directly on develop is evil).
This would have allowed to merge or rebase upstream/develop easily.
My 2cents.

**Comment by elarifr** [comment]
@rdoursenaud i'm lost with Git...

**Comment by elarifr** [comment]
the sql is only to define the box
the constant was the easiest way to try it. 
value is stored because
- i don't want to forget offset each time i open session few hours later, 
- only admin can set offset for other users
  it should be defined in login form or in left menu or maybe in the box itself. 

true by default because the meaning is to add virtual time zone as if we really were few days before and it appears to me to be best way to avoid change in any other part of code. but we can use false and the meaning will be by default dol_now() = fake virtual time and true real time if parameter is true. 

after writing this it appears you're right ! it should be false by default 
so i updated code in a branch thanks to your link again !

**Pull request closed without merging**
