### PR TITLE
NEW: #19763 DB change only - Can invoice task time per different services

### PR DESCRIPTION
**Pull request by FHenry**
NEW: #19763 DB change only - Can invoice task time per different services

### CODE REVIEW

**Comment by lmag** [comment]
👍

**Comment by eldy** [comment]
Merge can't be done by github. Can you resubmit the pr after merge by develop ?

**Comment by FHenry** [comment]
@eldy done, but as I can't(don't want) commit wihout local git hook phpCSsnifer is ok, I have to put comment into Wordpress OAuth class also

**Comment by eldy** [comment]
> @eldy done, but as I can't(don't want) commit wihout local git hook phpCSsnifer is ok, I have to put comment into Wordpress OAuth class also

When you have modified files into includes dir, you can make a commit for this file with
git commit --no-verify
so it bypass phpcs for it, then you commit the rest of files as usual.

**Pull request merged**
