### PR TITLE
Update list.php

### PR DESCRIPTION
**Pull request by oscim**
list contrat for thirdparty is not closed

# Instructions
*This is a template to help you make good pull requests. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "FIX", "CLOSE" or "NEW" section* (use uppercase to have the PR appears into the ChangeLog, lowercase will not appears)
- *follow the project [contributing guidelines](/.github/CONTRIBUTING.md)*
- *replace the bracket enclosed texts with meaningful information*

# FIX|Fix #[*issue_number Short description*]
[*Long description*]

# CLOSE|Close #[*issue_number Short description*]
[*Long description*]

# NEW|New [*Short description*]
[*Long description*]

### CODE REVIEW

**Comment by FHenry** [comment]
@oscim is it not the case for other document list (propal, order, invoice, customer/supplier) ? shoud we add a "morefilter" for it ?

**Comment by eldy** [comment]
Every filter used to restrict a list visible to end user must also be a filter "visible" to end-user (user must know why list is not complete and giving user a chance to see everything).
For the moment there is not available filter "Status of thirdparty (open or closed)", so adding this will lead to a blocking situation. User that need to see all contracts (even for closed thirdparties will have no more chance to be able to do it).
A better fix would be to add a filter field "Status of thirdparty". I would not use a $morehtml filter as suggested by @FHenry but a simple new column (we already have alot of information about the Thirdparty as filter, we can add one)
Note also that once we have such filter, it is also easy to define the default value of this filter using the generic filter feature.

**Comment by eldy** [comment]
I have some reason to think this may be fixed or no more applicable into more recent version. Does this bug still occurs with last stable version ?
If yes, please reopen the ticket and mention the recent version you tried with...

**Comment by eldy** [comment]
Even if this PR goal is to fix a bug or add a feature, it seems it introduces more problems than it solves, so request is closed.

**Pull request closed without merging**
