### PR TITLE
Fix #26050 #26225 and fiscal year report

### LINKED ISSUE #26050: In Accounting > Reporting, if I click on a month expenses, the dates are incorrectly loaded
### Bug

I want to go Accounting > reporting and click on a month to see the details of that month.

It goes to this url: /compta/resultat/clientfourn.php?year=2023&month=6&modecompta=CREANCES-DETTES

But the first date of the reporting period is a year in the future and I don't see the data

### Environment Version

18.0.1

### Environment OS

CloudLinux 7.x Linux hl109.lucushost.org 3.10.0-962.3.2.lve1.5.77.el7.x86_64 #1 SMP Mon Dec 12 07:06:14 EST 2022 x86_64

### Environment Web server

LiteSpeed

### Environment PHP

7.4.33

### Environment Database

MySQL or MariaDB 10.6.11-MariaDB-cll-lve

### Environment URL(s)

/compta/resultat/clientfourn.php?year=2023&month=6&modecompta=CREANCES-DETTES

### Expected and actual behavior

To load the detailed expenses for the month 6 of the year 2023

### Steps to reproduce the behavior

- Go to Accounting > Reporting
- Click on a month's detail

### Attached files

image

### PR DESCRIPTION
**Pull request by sonikf**

### CODE REVIEW

**Comment by eldy** [comment]
If fiscal year start on june and we are in april, what is the suggested range after the pr ?
Same question if fiscal yearcstart on june and we are in october ?

**Comment by sonikf** [comment]
Hi @eldy 
If i understood your questions correctly 
When SOCIETE_FISCAL_MONTH_START = 6
Setting $month_current = 4 range is 1/6/2022 to 31/5/2023
and when $month_current = 10 range is 1/6/2023 to 31/5/2024

Something else i noticed is highlighted menu entry, I think it should be renamed to "By fiscal year"
FISCAL

**Comment by eldy** [comment]
> mething else i noticed is highlighted menu entry, I think it should be renamed to "By fiscal year"

The group by is "Predefined group" so the good menu label should be "By predefined group"

**Comment by eldy** [comment]
I have fixed the label for menu. Good label is
"By predefined group"

**Pull request merged**
