### PR TITLE
New: Add tooltips and cache for boxes

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by frederic34** [comment]
tooltip-facture

**Comment by frederic34** [comment]
tooltip-produit

**Comment by eldy** [comment]
Nice.

However, we should keep cache dir into temp dir of module
DOL_DATA_ROOT.'/facture/temp'
and not 
DOL_DATA_ROOT.'/cache/'

Reason 1) is security, having data into module dir related to content make things easier to know what data are related to.
Reason 2) Having "temp" dir allow to use the feature to clean cache files from menu home - system  tools - purge.

**Comment by frederic34** [comment]
I changed to DOL_DATA_ROOT.'/module/temp' when possible and changed to DOL_DATA_ROOT.'/boxes/temp' for the boxes

**Comment by frederic34** [comment]
tooltip-user

**Comment by eldy** [comment]
Please recheck i have some conflicts on box produits*, i am not sure your changes were correctly included into this files.

**Pull request merged**
