### PR TITLE
Start to work on complete hrm module

### PR DESCRIPTION
**Pull request by aspangaro**
Help is welcome !

Warning, many bugs !

### CODE REVIEW

**Comment by eldy** [comment]
Creating a table employee is a good thing.
Table to store employee already exists. It is table llx_user. We call them "internal user", "employee" is just a synonym.
All employee information are already working with table llx_user (like the Hierarchical responsible in the company, job information, but also some modules like the intervention and expenses used by employees).

You should add fields you need into table llx_user.  Extrafield table should be done in the same way onto table llx_user.
If an employee must not have login to dolibarr, its statut must be set to 0. (disabled, so is a user that can"t login).

**Comment by aspangaro** [comment]
Thanks Eldy for your answer.

Like the member module, I thought it's a good thing to separate llx_user and llx_employee to have a better compatibility with others softwares...

Ok, I will work in this direction.

I'm open to all ideas !

**Comment by eldy** [comment]
Can you provide more detail why your think separating will increase better
compatibiliy ?

member and user are different because they are 2 different modules. member
is module membership management but user table is linked to no "named"
module but i confirm main goal is to manage "employee". Permission are
owned by table llx_group and llx_group_user not by llx_user whose main goal
is to store employee using dolibarr or not, so don't be afraid of merging
your work with llx_user.

2014-02-24 20:39 GMT+01:00 aspangaro notifications@github.com:

> Thanks Eldy for your answer.
> 
> Like the member module, I thought it's a good thing to separate llx_user
> and llx_employee to have a better compatibility with others softwares...
> 
> Ok, I will work in this direction.
> 
> I'm open to all ideas !
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Dolibarr/dolibarr/pull/1424#issuecomment-35926315
> .

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/astats_project

**Comment by aspangaro** [comment]
Désolé je la fais en français... malade au fond du lit :(

Bonsoir Eldy,

Je n'ai pas plus d'arguments pour la séparation des tables, je vais donc utiliser la table llx_user pour continuer mais il faudra néanmoins que j'ajoute une case pré-cocher disant "salarié" oui ou non car un utilisateur Dolibarr peut ne pas être salarié de l'entité et dans ce cas il ne sert à rien qu'il apparaisse dans la listes des salariés. 

Exemple : Je m'occupe de l'infogérance de Dolibarr pour plusieurs clients, j'apparais en superadmin, je n'ai rien à voir avec l'entité en question et pourtant j'apparais dans la liste des congés.

Je laisse la pull request ouverte, je vais publier au fur et à mesure les correctifs.

**Comment by marcosgdf** [comment]
If you write in French then other people won't be able to contribute... :cry:

**Comment by eldy** [comment]
Le 25 février 2014 21:13, aspangaro notifications@github.com a écrit :

> Désolé je la fais en français... malade au fond du lit :(
> 
> Bonsoir Eldy,
> 
> Je n'ai pas plus d'arguments pour la séparation des tables, je vais donc
> utiliser la table llx_user pour continuer mais il faudra néanmoins que
> j'ajoute une case pré-cocher disant "salarié" oui ou non car un utilisateur
> Dolibarr peut ne pas être salarié de l'entité et dans ce cas il ne sert à
> rien qu'il apparaisse dans la listes des salariés.
> 
> Exemple : Je m'occupe de l'infogérance de Dolibarr pour plusieurs clients,
> j'apparais en superadmin, je n'ai rien à voir avec l'entité en question et
> pourtant j'apparais dans la liste des congés.
> 
> I understand, but this is another need: A flag to make a difference between
> salaries and not. You will find same thing for the boss. He is not a
> salaries, need a dolibarr account but not beeing into job contract
> management.

This was goal of field fk_societe to make difference for that (we call that
"internal user" when fk_societe=0 and "external user" when fk_societe is >
0). However "external user" is still too restricted since it is limited to
its thirdparty only.
I suggest to increase possible values for fk_societe with:

fk_societe = 0 (currently the default as it is currently) => employee
fk_societe = -1 => other non employee (boss, a trusted provider)
fk_societe > 0 = external user as it is currently

This also means that everywhere we get the test if ($user->societe_id) we
will replace ($user->societe_id > 0).

 Je laisse la pull request ouverte, je vais publier au fur les correctifs.

> I prefer you close it and push small delta by small delta with this need
> direction.
> 
>  --
> Reply to this email directly or view it on GitHubhttps://github.com/Dolibarr/dolibarr/pull/1424#issuecomment-36052518
> .

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/astats_project

**Comment by aspangaro** [comment]
@marcosgdf  Marco, I think my english is so bad... If I've sick, it's worse !

@eldy  Thanks Eldy For your answer.
I've develop the extension in this direction and if necessary, I return to you for advice.

I close this pull request, I'll create a branch on my github and I will publish by touch when a function is ok.

**Comment by eldy** [comment]
Don't worry for english.

Bad (and even very bad english) is better than french.

2014-02-27 15:06 GMT+01:00 aspangaro notifications@github.com:

> Closed #1424 https://github.com/Dolibarr/dolibarr/pull/1424.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Dolibarr/dolibarr/pull/1424
> .

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/astats_project

**Comment by BebZ** [comment]
@aspangaro if you need help with english just put my name in the comment @BebZ and I will translate the part you could not write or express clearly :)
But anyway, writing in english is not that bad for training, but the more you read, the easier it will become !

**Pull request closed without merging**
