### PR TITLE
VAT: Replace "label for" by the function fieldLabel

### PR DESCRIPTION
**Pull request by aspangaro**

### CODE REVIEW

**Comment by aspangaro** [comment]
Sorry @eldy, where the class is lost on the td ?

the function fliedLabel is present for that.

/**
- Show a string with the label tag dedicated to the HTML edit field.
  *
- @param   string  $langkey        Translation key
- @param   string  $fieldkey       Key of the html select field the text refers to
- @param   int     $fieldrequired  1=Field is mandatory
  */

function fieldLabel($langkey, $fieldkey, $fieldrequired=0)

**Comment by aspangaro** [comment]
@eldy See the result. With the function fieldLabel, you can delete the class="required" and set the third param of the function to "1".

2015-11-02 20_49_41-centre de notifications

**Comment by simnandez** [comment]
@eldy: @aspangaro is right

**Comment by eldy** [comment]
I am balanced between the uniformization using the
"fieldLabel" function as you do
and using the 
"editfieldkey" + "editfieldval"
(do a search on editfieldkey to find an example).

I think we should go toward the second. We must just add the parameter "required" to add the span class="required". The main advantage of this second method is that is is designed to have interaction between the label and the field, so we are able to provide an "edit in place" feature. Not yet published.

**Pull request closed without merging**
