### PR TITLE
T944 amount to bill in order list

### PR DESCRIPTION
**Pull request by PaulPoulain**
The amount to bill is added before the status column, one before the order amount
see in /htdocs/commande/liste.php

### CODE REVIEW

**Comment by eldy** [comment]
Bad balance of td.
Also getting the $linkedObject inside a loop of a list create subrequests inside requests. This will seriously slow down and usage of subrequet into select list must be avoid.

**Comment by lrasamoelina** [comment]
But if i create an element remains in bills in the table llx_commande,i think this will solves the problem.
Or what is your idea about this?

**Comment by lrasamoelina** [comment]
It's should be ok now

**Comment by FHenry** [comment]
Still the transaltion "A Factuer" is not ok for Dolibarr. You should add the translation key into FR-fr and EN_us lang files

**Comment by lrasamoelina** [comment]
It's ok,i corrected

**Comment by eldy** [comment]
PR was in "conflict" so no way to merge it. Automatically closed after one year.

**Pull request closed without merging**
