### PR TITLE
FIX add a script for migrating pictures of products

### PR DESCRIPTION
**Pull request by tiaris**
script for migrating pictures path to new system.

### CODE REVIEW

**Comment by rdoursenaud** [comment]
I believe this is related to #2612 and #2743, right?

Do we really need a script? Shouldn't this be done during the upgrade wizard?

**Comment by tiaris** [comment]
Yes related to #2612 and #2743
Sure that an automated process is better, because some user will not be able to lauch a script.
Will update process migrate >30 000 products without timeout problems ? 
In my sense it shoud be an option for migrating large catalogs.

**Comment by simnandez** [comment]
I think the best is (at this point, you already know my reasons):
for 3.7.1 Use old system by default and make script and/or migration with upgrade wizard from new to old system and not from old to new.... 

@tiaris , @rdoursenaud , @eldy  you agree?

**Comment by tiaris** [comment]
ok for me
And we must think about same issue for invoices, orders, shippings ... see my comment on #2743

**Comment by rdoursenaud** [comment]
@simnandez :+1:

**Comment by eldy** [comment]
I don't think it is a good idea to go back to old system for 3.7.1, this will break photo for people who installed the 3.7.0.

Best thing is adding a insert, into migration script of 3.7.*, to insert the option to use old system but only IF the first installation was done with a version < 3.7.0 (we can check constant MAIN_VERSION_LAST_INSTALL to know if install was done on 3.6 or lower).

And for 3.8, we include function done by jean that make migration into upgrade2 script and we erase option to use old system from llx_const table.

**Pull request merged**
