### PR TITLE
NEW selectable const list

### PR DESCRIPTION
**Pull request by ghost**
# NEW
This PR add a list with (all) usable Dolibarr constants on the `Setup Other` page for easier administration.
 
Hope you like it.

### Picture

_Dolibarr major version is set to 5 (only for testing and show case)_

### CODE REVIEW

**Comment by BebZ** [comment]
Wow nice feature :)
Is this dropdown list "searchable" ?

**Comment by ghost** [comment]
> 
> 
> Wow nice feature :)
> Is this dropdown list "searchable" ?

Sorry, currently not , but nice idea, i will take a look

EDIT:
I think we need a separate JavaScript solution for that.
`datalist` on `input` is not supported by Safari. (possible without JQuery dependency)
https://www.w3schools.com/tags/att_input_list.asp

**Comment by eldy** [comment]
Having a combo list here is not a good idea because this page is dedicated to enter unknown constants like some setup variables required by external modules that are not yet documented.
Also it give a visibility on some things that the end user must absolutely not see as they are not stable features or not yet completed, or deprecated, etc).

If it appears that a hidden constant in this list must become "visible" for end-user, it is better to make it appear somewhere in one of the existing setup pages or modules setup page but not here.

**Comment by josett225** [comment]
Hi @eldy and @TobiasSekan,
As being a recent customer and admin, not sure if I can share my small experience here. I totally understand both point of views. Is there any way to get a kind of super admin access to get these admin gui (a specific ACTIVATE_SETUP_ADMIN_GUI 1)?. As an example, I am managing 5 different Dolibarr instance for 4 companies and I had to go several times to this setup section to type "MAIN_AUTO_TIMESTAMP_IN_PRIVATE_NOTES". I did a mistake once and I waste some time to find out that I missed "_IN_". I also use it a lot for PDF resolution issues or features (e.g. MAIN_PDF_ADDALSOTARGETDETAILS). If the GUI could avoid me this type of error or quick access, it will be great. Also having all of them in one place, is really helpful as this is avoiding to go to either to forum of wiki to find them. Of course this cannot be given to everybody as it is a source of mistake. This was my small feedback. Regards.

**Comment by ghost** [comment]
Hi,

We could add a check for each used constant and when a constant is known by Dolibarr, we can highlight it or give the user a short info. like
* This constant is known by Dolibarr
* This constant is deprecated
* This constant need a newer version of Dolibarr (v12.0 or higher)

**Comment by atm-maxime** [comment]
The list of hidden conf is documented on a specific wiki page. https://wiki.dolibarr.org/index.php/Setup_Other
I agree that end-users should not have a direct access to this list.
I'm working on a shell script that extract from Dolibarr all not documented hidden conf, I'll share it soon.

**Comment by BebZ** [comment]
I understand your concerns about security... But a warning message should avoid silly behaviours ?
Oh, no, sorry we are talking to humans ;)
 "a super super admin status" is not necessary
just give SuperAdmin status and a new right /access to users to modify hidden options, no ? 

My 2 cent to say : Hiding hidden options... is not a way to secure dolibarr admins but complicates their tasks. 
Many questions on the forums are often answered by "you can fin a hidden option for that"...

Let the hidden options be free :) 
but put a warning message and a "log" when hidden option is activated / modified ? 

It's like the warning when you presse "ERASE Database" ... somme people will always click believing someone can fix it after the "no way back" messsage...

**Comment by Tim-Otte** [comment]
To add my 2 cents:
I find this feature very practical. It helps to find and set a constant without having to search for a long time and without, as @josett225 has described, making mistakes and wasting time on troubleshooting. I would suggest that the constants are filtered according to the value MAIN_FEATURES_LEVEL, so that you don't see experimental constants when using only the stable version of Dolibarr. Since only administrators are allowed to change the constants, no user with limited dolibarr knowledge can interfere with the running system. And administrators who can change and add constants can also google the name of a hidden constant in 5 minutes.

@TobiasSekan: For a searchable selection field you can use [select2](https://select2.org/getting-started/basic-usage). Some other parts of Dolibarr use it as well.

**Comment by dpriskorn** [comment]
+1 @Tim-Otte

**Comment by josett225** [comment]
Hi @eldy and @TobiasSekan and @atm-maxime 
Sorry to comeback in this old one PR but I believe the need is still there for admins. Any chance to get Tobias work and maybe Maxime script embedded in one unique gui solution? 
The wiki is in general by default difficult to maintain up to date and most of the time to be accurate, we have to parse the code to find out the latest Const. Also the number of const are increasing as Dolibarr core features are growing. 

Best Regards
Jose

**Comment by eldy** [comment]
Some people think that hidden options are reserved to admin users, so should be visible to admin users. This is a bad understanding of what are hidden options. Hidden options are even not for admin users. The admin sys of a company is a powerful user, but even this user must have no access to hidden option : Activating a hidden option make the company that use the Dolibarr in a dangerous non stable situation. Even the admin of Dolibarr for a company should not be able to do that. The Dolibarr admin owns right to make powerfull tasks, but not make changes that make the application unstable or data corrupted as easily as choosing a value into a combo.
Hidden option are really for developers (option is hidden until dev of option is finished when option appears into common setup) or for integrators that are expert in Dolibarr (because the option has dangerous side effect). 
There is a difference between "advanced option" that may appears on some setup screen and that can be enabled by the admin of Dolibarr and hidden options that must be enabled only by the author of the code that did the hidden or by someone that made an impact analysis into the code of the hidden option.
Remind: 100% of hidden options are experimental and not stable for production use. They may be removed, modified, renamed at any time.
Because an admin user is also an end user (mostly the admin sys or the "computer" guy of a company), and not a core developer of Dolibarr, hidden option must not be visible by admin users. 
For this reason, the "hidden options" must be called the "unstable or dev options".
So i close this PR.

**Pull request closed without merging**
