### PR TITLE
fix imports

### PR DESCRIPTION
**Pull request by altairis-tof**
keyfield may content any field defined in import_fieldshidden_array so the present code dont do updates !

### CODE REVIEW

**Comment by rycks** [comment]
@altairis-tof i need more informations too ... 

for information in 20.0 you seems to made a different fix : https://github.com/Dolibarr/dolibarr/pull/29553 no ?

and in case of fix for that bug, i think xls import will be concerned too

@eldy could a backport of 20.0 fix be a better solution in same situation ?

**Comment by eldy** [comment]
> @altairis-tof i need more informations too ...
> 
> for information in 20.0 you seems to made a different fix : #29553 no ?
> 
> and in case of fix for that bug, i think xls import will be concerned too
> 
> @eldy could a backport of 20.0 fix be a better solution in same situation ?

@rycks Yes, if a bug is already fixed in a higher version, a fix for a backport should use the same way to fix than the fix in higher version. It is always a better solution, as long as it is possible. This may not be possible if backport/cherry-pick is not possible because the fix in recent version is based on other changes done by other PR available only into the recent version.

**Comment by rycks** [comment]
@altairis-tof what do you think about that ? different solution with https://github.com/Dolibarr/dolibarr/pull/29553 looks strange and make me trouble ...

**Comment by eldy** [comment]
I close the ticket. It seems a fix was done differently in develop so backport shoud fix the same way.

**Pull request closed without merging**
