### PR TITLE
Fix: Bug in the new photo system

### PR DESCRIPTION
**Pull request by fmarcet**
The new photo system doesn't work properly

### CODE REVIEW

**Comment by kvalnirk** [comment]
it does not work:

Parse error: parse error in D:\CalcherERP\www\dolibarr\htdocs\product\class\product.class.php on line 3179

the syntax is correct?

a greeting

**Comment by simnandez** [comment]
I tested this and this work perfectly. Also the line 3179 is empty (blank line). which is the exact error message?

**Comment by kvalnirk** [comment]
sorry had to remove the modified line. But I still see the products before the upgrade.

thanks

a greeting

**Comment by kvalnirk** [comment]
I have a template in pdf showing me pictures of old products, but in the data sheet no picture.

**Comment by kvalnirk** [comment]
I still can see the images on the card of old products, any solution?

a greeting

**Comment by tiaris** [comment]
I solved this problem in such maner

http://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/52980-disparition-des-images-produits-dans-mon-stock#59841

**Pull request merged**
