### PR TITLE
Unit Management for MO lines

### PR DESCRIPTION
**Pull request by atm-lena**
# NEW|New

- Add Column "Unit" in "mo_production.php" for each line of mo
- Create mo from a bom : transfer unit of bom lines in, unit of mo lines
- Create a line to consume in "mo_production.php" : unit line is unit of product
- Sql request to update new column fk_unit of mo lines and  fk_unit of bom lines

image

### CODE REVIEW

**Comment by eldy** [comment]
@atm-lena Did you enable the precommit git hook ? See this page: https://wiki.dolibarr.org/index.php?title=Environment_and_development_tools#Install_Pre-commit_git_hook
If yes, most error reported by travis will be automaticaly fixed during your commit...

**Comment by atm-lena** [comment]
> @atm-lena Did you enable the precommit git hook ? See this page: https://wiki.dolibarr.org/index.php?title=Environment_and_development_tools#Install_Pre-commit_git_hook If yes, most error reported by travis will be automaticaly fixed during your commit...

@eldy it's done !

**Comment by eldy** [comment]
Can you help me fix the merge conflict. It seems in your new version, you add a new column but a lot of old code also disappears in mo_production.php

**Comment by atm-lena** [comment]
Done @eldy

**Pull request merged**
