### PR TITLE
FIX: duplicate table column

### PR DESCRIPTION
**Pull request by rdoursenaud**
Already declared on line 59

### CODE REVIEW

**Comment by aspangaro** [comment]
Same fix than https://github.com/Dolibarr/dolibarr/pull/1905 but yours is more complete

**Comment by ndrosis** [comment]
I think it should be removed and the ALTER TABLE llx_user ADD COLUMN salary double (24,8); on line 91 in file 3.6.0-3.7.0.sql

**Comment by eldy** [comment]
thm is not same than tjm.
thm would store hourly amount of an employee
tjm would store daily amount of an employee.
Some company use one, other use the other.

**Comment by ndrosis** [comment]
Hi eldy thm in the line 59 and 74.

**Comment by rdoursenaud** [comment]
@eldy please read the comment! This is already declared on line 59 and causes the installer to hang.

**Comment by ndrosis** [comment]
@rdoursenaud I think from version 3.6 to 3.7 will present the problem of 'salary' from the file 3.6.0-3.7.0.sql in line 91

**Comment by rdoursenaud** [comment]
@ndrosis This is a different problem. Please do your own PR and don't ask others to do the work for you.

**Comment by ndrosis** [comment]
Sorry @rdoursenaud  I did not say for this reason a misunderstanding.

**Comment by eldy** [comment]
Fixed

**Pull request closed without merging**
