### PR TITLE
NEW More picto for phone

### PR DESCRIPTION
**Pull request by dolibarr95**
runs with #6617

### CODE REVIEW

**Comment by dolibarr95** [comment]
If some admin can push this file : theme/eldy/img/object_phoning_mobile.png
object_phoning_mobile

**Comment by hregis** [comment]
@dolibarr95 
you work directly in github ?

**Comment by dolibarr95** [comment]
@hregis 
hi 
yes

**Comment by dolibarr95** [comment]
#6616
#7290

**Comment by hregis** [comment]
@dolibarr95 https://github.com/Dolibarr/dolibarr/pull/7607

**Comment by dolibarr95** [comment]
@hregis 
tks !

**Comment by hregis** [comment]
@dolibarr95 don't close your PR, i just add picto

**Comment by dolibarr95** [comment]
sorry

**Pull request merged**
