### PR TITLE
FIX: can use LINEORDER_SUPPLIER_CREATE

### PR DESCRIPTION
**Pull request by olsesacl**
in function addline use LINEORDER_SUPPLIER_CREATE, but no add to object the new line, so that can't use in a module this trigger.

Now add new line to object and can use.

### CODE REVIEW

**Comment by eldy** [comment]
The problem is that the addline should use
$this->line=new CommandeFournisseurLigne($this->db);
and
$this->line->insert
like do the other object.

Then into trigger, you can use the id of inserted line to retreive all information. You can however still do it using the this->rowid currently. For a better isolation, it is better just to have id propagated and let consumer that need information to get/load it, even if it needs one more fetch request on line.

**Comment by marcosgdf** [comment]
That param `new_line` does not really make sense. It is not a property of a `CommandeFournisseur` object

**Comment by olsesacl** [comment]
Add functions insert and update in CommandeFournisseurLigne and SupplierInvoiceLine

**Comment by olsesacl** [comment]
@eldy Add functions insert and update in CommandeFournisseurLigne and SupplierInvoiceLine

**Comment by olsesacl** [comment]
update

**Comment by eldy** [comment]
Something looks wrong with your PR:  8945 files modified !

**Comment by olsesacl** [comment]
Sorry, I update it

**Pull request merged**
