### PR TITLE
FIX: reload $object after updating lines

### PR DESCRIPTION
**Pull request by altairis-noe**
# FIX: reload $object after updating lines
current Propal object should be fetched again when its lines are all updated, in order to reflect differences in the margin table
image

### CODE REVIEW

**Comment by frederic34** [comment]
can you compare with https://github.com/Dolibarr/dolibarr/pull/32081

**Comment by altairis-noe** [comment]
> can you compare with #32081

I kind of like your approach. What does @eldy think about it?

**Comment by altairis-noe** [comment]
Hey there, @eldy
Where are we on this issue ?

**Comment by eldy** [comment]
> Hey there, @eldy
> Where are we on this issue ?

I gave priority to #32081 so fix will benefit to other use cases not yet identified.

**Comment by altairis-noe** [comment]
OK, thanks!

**Pull request closed without merging**
