### PR TITLE
Add project filtering to calendar export && Correct bug on project contacts list printing

### PR DESCRIPTION
**Pull request by groolot**

### CODE REVIEW

**Comment by eldy** [comment]
It's ok for patch for the new feature and translation fix. I don't undestrand Fix 3d2e298.
Can you provide more information on how to reproduce bug on current dev ?

**Comment by groolot** [comment]
seems to be a wrong correction ...
looking forward, because there was a real bugin front of that :/

**Comment by eldy** [comment]
Can you remake this PR after reverting 3d2e298 and solving merge conflicts ?

**Comment by eldy** [comment]
Integrated by another PR.

**Pull request closed without merging**
