### PR TITLE
NEW manual lettering in accounting

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
NEW manual lettering in accounting

1.  Add a mass action Lettering :
image

2. And manage errors
- show errors if it's already done 
image

- or amounts are not balanced
image

3. And the code between accounts and sub accounts was merged
- keep only one file "listbyaccount.php' ("listbysubaccount.php was removed)

### CODE REVIEW

**Comment by eldy** [comment]
On the screenshot on the column for lettering, I see the filter "Non rapproché", surely "NotReconciliated" in english.
Because term Reconciliated is already used for another purpose, can you add another entry called "Letterable" (that apply to the lettering action)

**Comment by aspangaro** [comment]
@eldy No, this is the term "Reconciled". "Letterable" =>This term really exists in English ?

"Reconciliated" is used in bank module.

In the actual version of reconciled function, we need to show alpha code (AAA, AAB, etc), in column "Reconciled", generated when a debit and credit amounts was reconciled.

image

if it wasn't clear, I'll send you a troop of accountants 

Also, this functionnality was present in thirdparty tab. This two tab will disappear because it is no longer useful (accountancy>bookkeeping>thirdparty_lettering_customer.php & accountancy>bookkeeping>thirdparty_lettering_supplier.php)

**Comment by eldy** [comment]
You're right, the term is "Reconciled" not "Reconciliated" (this does not exist).

But, when a credit and debit amount are linked together, this is a difference process than bank reconciliation. Even if in english we use the same term "Reconciled" (and may be in french too), the code must use 2 different keys (in other languages it may be different). So to avoid confusion i renamed the key:
"Reconciled" and "NotReconciled into "BankLineReconciled" and "BankLineNotReconciled" into the lang file banks.lang and on screen related to bank reconciliation  (the key Reconciled was duplicated into file banks.lang + accountancy.lang generating conflict).
So now you can use "Reconciled" (only present into accountancy.lang) for the lettering operation.To summarise:

- BankLineReconciled into bank.lang for bank reconciliation => Translated into Reconciled
- Reconciled into accountancy.lang for the lettering feature => Translated into Reconciled

Are you ok ?
If yes, another question, can we translate in french into

- "Rapproché" for bank reconciliation
- "Lettré" for the lettering feature or do we have to use "Rapproché" too in french ?

**Comment by eldy** [comment]
@aspangaro the last question is for you

...
So now you can use "Reconciled" (only present into accountancy.lang) for the lettering operation.To summarize:

BankLineReconciled into bank.lang for bank reconciliation => Translated into Reconciled
Reconciled into accountancy.lang for the lettering feature => Translated into Reconciled
Are you ok ?
If yes, another question, can we translate in french into

"Rapproché" for bank reconciliation
"Lettré" for the lettering feature or do we have to use "Rapproché" too in french ?

**Comment by eldy** [comment]
@lvessiller-opendsi I like the merge of 2 files in this PR  👍🏻 
However, it seems one line of code containing the print of "WarningRecordWithoutSubledgerAreExcluded" has been lost. Can you check ?

**Comment by lvessiller-opendsi** [comment]
@eldy 
You're right, I forgot this line and I add it.
Could you see to merge this PR ?

**Comment by aspangaro** [comment]
> @aspangaro the last question is for you
> 
> ... So now you can use "Reconciled" (only present into accountancy.lang) for the lettering operation.To summarize:
> 
> BankLineReconciled into bank.lang for bank reconciliation => Translated into Reconciled Reconciled into accountancy.lang for the lettering feature => Translated into Reconciled Are you ok ? If yes, another question, can we translate in french into
> 
> "Rapproché" for bank reconciliation "Lettré" for the lettering feature or do we have to use "Rapproché" too in french ?

I'm ok with this translation. Reconciled is en_US and Rapproché (Banque) & Lettré (Comptabilité).

You can merge this PR, Lionel has added the print of warning in subsidiary ledger

**Pull request closed without merging**
