### PR TITLE
Fix 17986 error on comparing integer and string in strict sql

### PR DESCRIPTION
**Pull request by daraelmin**
@eldy 
I'm not sure that is the best solution, but it may be important to fix it before 14.0.0, so I try the faster way.

### CODE REVIEW

**Comment by daamien** [comment]
This is not the proper solution.

It's best to use `YEAR()` or `EXTRACT( YEAR FROM ...)` instead of `DATE_FORMAT()`

```php
$sql .= " WHERE YEAR(p.dateadh) = ". (int) $year;
```

If you want to do a numeric comparison, just convert both values in `INT`. No need to use strings for that.

**Comment by daraelmin** [comment]
May be this one is better.

**Comment by eldy** [comment]
Usage of date function on SQL side (native but also provided by dolibarr like date_format) must be avoided because it will not manage correctly the timezone of user (that is defined on Dolibarr) and the timezone of server (that is stored in php setup). Also it is slower than using a true comparison on date (such comparison allow to use the index on date when using a test on YEAR will not use it)
Here the good practice is to use the function
$sql .= "WHERE ".dolSqlDateFilter('p.dateadh', 0, 0, $year, 1);

**Comment by daraelmin** [comment]
> Usage of date function on SQL side (native but also provided by dolibarr like date_format) must be avoided because it will not manage correctly the timezone of user (that is defined on Dolibarr) and the timezone of server (that is stored in php setup). Also it is slower than using a true comparison on date (such comparison allow to use the index on date when using a test on YEAR will not use it)
> Here the good practice is to use the function
> $sql .= "WHERE ".dolSqlDateFilter('p.dateadh', 0, 0, $year, 1);

@eldy
Ok. I've done the changes. Thank you for your review.

However, I wonder if we shouldn't change this kind of statement to  :
```php
$sql = "SELECT date_format(p.dateadh,'%m') as dm, count(*)";
````

**Comment by eldy** [comment]
> > Usage of date function on SQL side (native but also provided by dolibarr like date_format) must be avoided because it will not manage correctly the timezone of user (that is defined on Dolibarr) and the timezone of server (that is stored in php setup). Also it is slower than using a true comparison on date (such comparison allow to use the index on date when using a test on YEAR will not use it)
> > Here the good practice is to use the function
> > $sql .= "WHERE ".dolSqlDateFilter('p.dateadh', 0, 0, $year, 1);
> 
> @eldy
> Ok. I've done the changes. Thank you for your review.
> 
> However, I wonder if we shouldn't change this kind of statement to :
> 
> ```
> $sql = "SELECT date_format(p.dateadh,'%m') as dm, count(*)";
> ```

No, here the date_format is used to extract substring to get the Month (it is used as a substr method). We can keep it. The dolSqlDateFilter is designed to be used to forge the WHERE of sql.

**Comment by daamien** [comment]
Thanks

**Pull request merged**
