### PR TITLE
FIX TakePos barcode rule

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
FIX TakePos barcode rule
Issue https://github.com/Dolibarr/dolibarr/issues/30203

### CODE REVIEW

**Comment by rycks** [comment]
Hello,
i'm sorry but i'm in trouble because two years ago we did the opposite commit, please have a look here:

https://github.com/Dolibarr/dolibarr/commit/cad8b1ee7e84f704b3f66f3bda54940ee31e6cec "Fix autoadd in basket after a search (only if search on barcode)"

what do you think about that ?

maybe i need more time to test and set up a dolibarr with that use case

**Comment by lvessiller-opendsi** [comment]
@rycks 
You're right I will see an another solution to do it.

**Comment by rycks** [comment]
note about quality : $term is most of the time used for session terminal number

image

then it could be a quality fix to change term= by something like search= or barcode= .... and a new variable $search or $barcode then $term will be only for terminal number

**Review by rycks — APPROVED** [review]
ok for me (and "quality" note is a "global" remark)

**Pull request merged**
