### PR TITLE
Fix utf8_encoding/decoding (PHP8.2 deprecation)

### PR DESCRIPTION
**Pull request by mdeweerd**
Fix files that were missed in #27018

# Fix deprecation of utf_(en|de)code function ins PHP8.2

### CODE REVIEW

**Comment by eldy** [comment]
Can you solve conflict and repush without any change into extrnal lib (files into includes dir).
such change must be done into separate pr

**Comment by mdeweerd** [comment]
Ok, noted that changes to libraries need to be in separate PR.  However, it seems that now there are no more changes left to these.

This PR has been rebased.

**Comment by eldy** [comment]
Note: Do you know we already have this in functions.lib.php

```
if (!function_exists('utf8_decode')) {
	/**
	 * Implement utf8_decode for PHP that does not support it.
	 *
	 * @param	mixed	$elements		PHP Object to json encode
	 * @return 	string					Json encoded string
	 */
	function utf8_decode($elements)
	{
		return mb_convert_encoding($elements, 'ISO-8859-1', 'UTF-8');
	}
}

```

**Comment by mdeweerd** [comment]
Yes, I know that already is in the functions.lib.php - it will not avoid deprecation messages as the built-in php function takes precedence!

**Pull request merged**
