### PR TITLE
Removed unmaintaned OScommerce module

### PR DESCRIPTION
**Pull request by rdoursenaud**
This module is broken and AFAIK no one takes care of it.
I propose that we remove it for 3.7.
In the "show me the code" tradition, I make the proposal with this PR.

### CODE REVIEW

**Comment by atm-maxime** [comment]
:+1:

**Comment by FHenry** [comment]
:+1:

**Comment by ndrosis** [comment]
:+1:

**Comment by marcosgdf** [comment]
:+1:

**Comment by aspangaro** [comment]
:+1:  :)

**Comment by frederic34** [comment]
RIP

**Comment by eldy** [comment]
I was still hoping someone develop it, so i would like to keep it. But this goes against the large majority, so i validate the PR. 
Snif, ;-(

**Pull request merged**
