### PR TITLE
Files Integrity Checker

### PR DESCRIPTION
**Pull request by frederic34**
Here is the code I use to generate xml:

```
<?php
header('Content-type: text/xml');

print '<?xml version="1.0" encoding="UTF-8" ?>'."\n";
print '<checksum_list>'."\n";
print '<dolibarr_root_dir version="3.6.2">'."\n";

$dir_iterator = new RecursiveDirectoryIterator(dirname(__FILE__));
$iterator = new RecursiveIteratorIterator($dir_iterator);
$dir='';
$needtoclose=0;
foreach ($iterator as $file) {
    $newdir = str_replace('/mnt/data/fred/github/dolibarr/htdocs','',dirname($file)); //Need to adapt
    if ($newdir!=$dir) {
        if ($needtoclose)
            print '</dir>'."\n";
        print '<dir name="'.$newdir.'" >'."\n";
        $dir = $newdir;
        $needtoclose=1;
    }
    if (filetype($file)=="file") {
        print '<md5file name="'.basename($file).'">'.md5_file($file).'</md5file>'."\n";
    }
}
print '</dir>'."\n";
print '</dolibarr_root_dir>'."\n";
print '</checksum_list>'."\n";
```

### CODE REVIEW

**Comment by frederic34** [comment]
2015-02-19 21_53_37-dolibarr

**Comment by frederic34** [comment]
May be useful for detectives on the forum...

**Comment by aspangaro** [comment]
:+1:

**Comment by eldy** [comment]
To have this working in an automatic way, you must put the script that generate md5 into the directory build (with makepack-dolibarr.pl).
Then modify the makepack-dolibarr.pl to add a step "-1" before the step 0 to generate this file.

**Comment by frederic34** [comment]
makepack-dolibarr.pl is now building the file

**Comment by marcosgdf** [comment]
Why not integrating this into Info Dolibarr section?

**Comment by frederic34** [comment]
That's what I did at first but test can take some times to complete and "Infos Dolibarr" is a long page, you have to scroll down

**Comment by frederic34** [comment]
I need to build the xml in the buildoc directory after the cleaning

**Pull request merged**
