### PR TITLE
Add accountancy export option for Sage50 Swiss

### PR DESCRIPTION
**Pull request by a-schild**
# Instructions
# New accountancy Sage50 Swiss export format
Closes Issue #11235

### CODE REVIEW

**Comment by aspangaro** [comment]
Thanks @a-schild !

Can you delete your change on language file other than en_US. Other language files are managed with transifex.

**Comment by a-schild** [comment]
Ok, reverted the DE/FR/IT language changes

**Comment by a-schild** [comment]
BTW: We would need to have the file Ansi encoded.
In plain php we would do this in the code:

```
header('Content-type: application/txt');
header('Content-Transfer-Encoding: binary');
```

Would this be ok to have this in Dolibarr, or do we have to tell the users to convert the csv file from utf8 to ansi once downloaded?

**Comment by aspangaro** [comment]
@eldy Seems ok for me

**Pull request merged**
