### PR TITLE
[Qual] Reviewed commonobject

### PR DESCRIPTION
**Pull request by rdoursenaud**
Added missing fields
Removed unused variables
Documented methods parameters
Checked return points

### CODE REVIEW

**Comment by marcosgdf** [comment]
Are you sure all classes that extend from CommonObject have those fields?

**Comment by eldy** [comment]
I think some "properties" should not appears into common:
barcode, delivery address or incoterm.

**Comment by rdoursenaud** [comment]
Well, they are all declared dynamically in this class' methods so they pertain to this class anyway.
I just made explicit what was implicit.

I agree that most of them should find a better home but until then, having them listed allows for better completion and inspections in the IDE and other automated tools.

**Comment by rdoursenaud** [comment]
Conflicts resolved.

**Pull request merged**
