### PR TITLE
Added Sumup support to TakePoS: triggers the app and get the status b…

### PR DESCRIPTION
**Pull request by Mavyre**
# New Sumup support on TakePoS

It's now possible to configure Sumup application in TakePoS. It permits to trigger the Credit Card Terminal directly from the PoS, and continue the usual workflow if the transaction is successful.

Also enhanced the mobile viewability.

### CODE REVIEW

**Comment by ptibogxiv** [comment]
Can we set amount to pay with terminal from takepos ?

**Comment by ptibogxiv** [comment]
Becareful this PR revert lot of last PR. It seems to be an old dev file.

Can you add an alternative module like stripe for settings  (sumup support online pay too). It will be more clean and we can add sumup support in more module without takepos cc @eldy

But Great idea to add this.

**Comment by Mavyre** [comment]
@ptibogxiv Yes, it's the sole purpose of this PR, you can enter the amount with the Pay button from TakePoS and it triggers the app with the amount you entered. Paying half in cash and half with Sumup Terminal is possible.

I'll refactor it to a new module, but won't be able to add the Online Pay, as it doesn't seem available anymore in France... :(
I didn't pay attention to the last PR, so I'll rollback and merge with a diff correctly.

**Comment by eldy** [comment]
@Mavyre It seems your PR was done on an old version of develop. Can you try to resubmit it on last develop ? (this PR is very interesting and we need it, but due to a lot of change done before, we can't validate it for the moment).

**Comment by Mavyre** [comment]
> @Mavyre It seems your PR was done on an old version of develop. Can you try to resubmit it on last develop ? (this PR is very interesting and we need it, but due to a lot of change done before, we can't validate it for the moment).

I'll redoit on last develop when I'll have some time next week. I'll create a new Sumup module where I'll put all the config options I added on TakePoS. This way, we'll have a proper base for every Sumup development.
Does that seem okay?

**Comment by eldy** [comment]
In such a case, may be it is better to keep Sumup module as an external module and sell it or distribute it for free on dolistore ?
If you prefer having it into dolibarr core so it is maintained after by the community for the following years, because it seems to have a sens only with TakePos, you can include it into TakePos core code but you can/must add a test on an option "TAKEPOS_ENABLE_SUMUP" 
if ($conf->global->TAKEPOS_ENABLE_SUMUP) { ...
So there is no change if sumup is not used, and we can easily find part of code modified or added to manage Sumup.
Using a dedicated module is a good choice only if:
- It is an external module 
- Or it is a standalone feature that will bring a very high quantity of code.
- Or it is a transversal feature that will be used in a lot of other modules.

In the case of sumup, except, if you prefer to stay an external module, I don't think it matches the condition to be an independent module of the core.

**Comment by Mavyre** [comment]
I think it should be included in the core as Paypal and Stripe are because it has the same online payment functionalities – and should be integrated. Sumup can also be used in a PoS with its physical terminal, and we should integrate it in TakePoS as I did, and maybe in SimplePoS too (but I didn't dig into it, yet).

What do you think about it?

**Comment by eldy** [comment]
Ok for the core.
However, can you resubmit PR with last develop version and add
if ($conf->global->TAKEPOS_ENABLE_SUMUP) { 
So it will be easier to find code added to support SUMUP.

**Comment by eldy** [comment]
@Mavyre It would be great to have this PR in v11, so can you resubmit PR with last develop version and add 
 if ($conf->global->TAKEPOS_ENABLE_SUMUP) {   around code added specific to sumup ?

**Comment by Mavyre** [comment]
@eldy I'll finalize the Pull Request this week-end, merging it with the latest dev !

**Comment by Mavyre** [comment]
Hi. Sorry for the delay @eldy. I'm opening a new Pull Request with a new next saturday with a cleaned repository on my side.
Thus, I'm closing this one.

**Pull request closed without merging**
