### PR TITLE
Intégration code charles project V2

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by FHenry** [comment]
OK, I'm checking other wrong things in this pullrequest.

**Comment by FHenry** [comment]
It should be ok now

**Comment by FHenry** [comment]
Forget this pull request for the moment, I have to work on the code to make it standard. For exemple function Task_Transfer_FichInter have to be a method of ficheinter class createFromProject

**Comment by jfefe** [comment]
Some functions in project.lib.php needs to be moved to task.class.php and we will do more enhancement before to be merged in core. 

Work in progress ;)

**Pull request closed without merging**
