### PR TITLE
NEW add Opening Balance column to balance.php

### PR DESCRIPTION
**Pull request by maboelfotoh**
Add Opening Balance column to balance.php where colspans and line break widths are adjusted accordingly.

### CODE REVIEW

**Comment by eldy** [comment]
Here we are losing an important feature making the report grouped by account.
Can you make this an option from a parameter so we can switch between this view and the old behavior ? (lilke it is done for the ledger page with button "Group by account")

**Comment by maboelfotoh** [comment]
Under Ledger (accountancy/bookkeeping/list.php) I do see the button 'Group by finance account', whereas under the Account balance page (accountancy/bookkeeping/balance.php) I only see the 'EXPORT (CSV)' button. Is there supposed to be a 'Group by account' button there too?
balance
(I do acknowledge that removing the line break would break sorting by 'Financial account')
Thanks.

**Comment by eldy** [comment]
The button "group by" is not yet. My suggestion is to add it so we won't loose the existing feature.

**Review by eldy — COMMENTED** [review]
The button "group by" is not yet. My suggestion is to add it so we won't loose the existing feature.

**Comment by maboelfotoh** [comment]
> The button "group by" is not yet. My suggestion is to add it so we won't loose the existing feature.

If you may, kindly provide a screenshot of the "existing feature" that would break by adding an Opening Balance column. So far, I tested balance.php by sorting by 'Financial Account', as well as search filter options and those work without issues.

Alternatively, if you would rather have this new version of balance.php as a separate page, say openingbalance.php, and have a button from balance.php that links to openingbalance.php (passing over search filter parameters), then that's also fine with me.

Thank you.

**Comment by maboelfotoh** [comment]
Re-implemented this as a separate view that can be toggled, similar to how the Ledger page views (list.php and listbyaccount.php) are implemented. Thanks.

**Comment by eldy** [comment]
So, i misunderstood what was the goal of your PR. I though you move the breakdown of accounting account as a simple column, this is why i guide you to this change. I finally revert your PR to take last version - 1.

**Comment by maboelfotoh** [comment]
> So, i misunderstood what was the goal of your PR. I though you move the breakdown of accounting account as a simple column, this is why i guide you to this change. I finally revert your PR to take last version - 1.

The merge didn't take the commit.
I actually reverted my commit before committing the re-implementation as balance.php and openingbalance.php. So there is now one commit (one version), where balance.php has a button that links to openingbalance.php, and vice versa. In addition to your suggestion, I figured this would keep the balance.php view as-is for those who do not want the extra "Opening Balance" column.

balance.php screenshot:
balance php

openingbalance.php screenshot:
openingbalance php

**Pull request merged**
