### PR TITLE
various en_US changes

### PR DESCRIPTION
**Pull request by torvista**
1) Standardization of use of "third party"as a noun : third party
as an modifier: third-party contact
2) use of colons: no space before
3) Use of supplier/vendor was mixed.
Vendor is B2B or B2C, supplier is B2B. Changed all references to supplier.
4) Many minor grammar changes.

### CODE REVIEW

**Comment by eldy** [comment]
We made some changes into v9 to replace all "suppliers" into "vendors".
Dolibarr can be used both B2B or B2C and it seems some other software use "vendor". so we choose to use "vendor" everywhere. 
Do you think it's possible to standardize using the other switch (supplier -> vendor) ?

**Comment by torvista** [comment]
> Do you think it's possible to standardize using the other switch (supplier -> vendor) ?

Ok. Done, although I don't agree with it. especially since most of the constants are named Supplier..

**Comment by aljawaid** [comment]
Supplier made more sense.  Vendor is very American.  'Supplier' is more common in the UK.  Just saying. 

Adding 'vendor' to the lang strings is probably going to confuse most of the end users who are used to 'supplier' for so many versions.

**Comment by torvista** [comment]
Vendor does get used in the UK, but Supplier is better.
...but this is the en_US lang after all!

Personally it irks me that en_US is considered the base language instead of en_GB when
a) english comes from England.
b) france is closer (mentally and physically) to GB than the US.
c) anything that gives more importance to the US, especially coming from a european EU project, is a bad thing, in my opinion. Although the UK is a circus too at the moment.

When one day I consider en_US to be properly translated, I'll start on en_GB for my own use, and yes I'll be using supplier.

**Comment by torvista** [comment]
> We made some changes into v9 to replace all "suppliers" into "vendors".

Was that discussed anywhere public?

**Pull request merged**
