### PR TITLE
Qual - Optimize requests in sells journal for situation invoices

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
Qual - Optimize requests in sells journal for situation invoices
- not reload "Facture" object when already loaded from SQL request
- add a method "getPrevProgressFromInvoiceCycleRefAndType" to determine the progress percent from "cycle ref" and invoice "type"

**Remark**
When you got a lot of invoices and you set "INVOICE_USE_SITUATION" to 1, you can excess the max execution time.

### CODE REVIEW

**Comment by aspangaro** [comment]
Hi @lvessiller-opendsi 

Have you tried your code with the constant INVOICE_USE_SITUATION = 2, which adds "progressive" situation invoices to v20?

**Comment by lvessiller-opendsi** [comment]
> Hi @lvessiller-opendsi
> 
> Have you tried your code with the constant INVOICE_USE_SITUATION = 2, which adds "progressive" situation invoices to v20?

Hi @aspangaro, I haven't tried with INVOICE_USE_SITUATION = 2 yet.
I did'nt know it.
What is the difference with "INVOICE_USE_SITUATION = 1" ?

**Comment by aspangaro** [comment]
Hi @lvessiller-opendsi 

It's a new mode for situation invoice integrated in v20 (hidden for the moment). The mode 2 of the constant must be replaced the mode 1 officialy in v21.

This work comes from the GIFF situation invoice, the difference between the two modes is that situation invoices were on a cumulative mode and now it will be on a progressive mode.

**Comment by lvessiller-opendsi** [comment]
> Hi @lvessiller-opendsi
> 
> It's a new mode for situation invoice integrated in v20 (hidden for the moment). The mode 2 of the constant must be replaced the mode 1 officialy in v21.
> 
> This work comes from the GIFF situation invoice, the difference between the two modes is that situation invoices were on a cumulative mode and now it will be on a progressive mode.

Hello,

This PR not depends on INVOICE_USE_SITUATION const, I only add a method not to fetch and load invoice object (many SQL requests).
I used the value got early in the SQL request to retrieve the previous situation percent.
It's only to optimize and avoid an excessive execution time.

**Comment by lvessiller-opendsi** [comment]
I had some troubles in retrieving the "develop" branch and some unwanted PR was introduced in it.

**Pull request closed without merging**
