### PR TITLE
Presentation rule :: Space before and after "Two points"

### PR DESCRIPTION
**Pull request by aspangaro**

### CODE REVIEW

**Comment by frederic34** [comment]
Hello Alexandre
If you want that, I think you may write .'&amp;nbsp;: '. to avoid the two point to go to new line.
Fred

**Comment by aspangaro** [comment]
Hello Frederic,

I had thought of it, it works like that but we can put .'& nbsp;:& nbsp;'. to be complete seen that we make both the hunting for spaces ;)

What do you think ?

**Comment by eldy** [comment]
Having a space is a french (latin) typographic rule. For other languages (above all english), there is no space before a punctuation mark as i know. It will be difficult to manage both language. 
We could introduce a global var $colon or a language key to manage this, but i think it does not worth pain, so i would prefer to keep english convention.

**Comment by aspangaro** [comment]
Thanks Eldy,

I was afraid of the answer. Maybe introduce a language key called "latin_ponctuation" with nothing in language en_US and a space in fr_FR for example.

**Comment by rdoursenaud** [comment]
Yay, a typonazi :)
The right way to dealing with it is to _not_ have the colon concatenated but part of the translation key. Having alternative keys if need be.

**Comment by marcosgdf** [comment]
Please don't accept this. I've spent so much time removing those spaces.

In Spanish and English is an misspelling.

:sob:

**Comment by eldy** [comment]
Rest of world > France,
so I close request.

**Comment by altairis-tof** [comment]
Dolibarr french users are very disappointed in reading this; especially pdf documents should be with no spelling mistake in every language so we have to improve the way of coding the presentation screens and documents. I am tired of fixing pdf.lib.php and pdf models for each new customer or each dolibarr core upgrade !

**Comment by BebZ** [comment]
@altatof should we put in place a translation file for the punctuation of pdfs ? 
what can be proposed ? implemented ?

**Comment by altairis-tof** [comment]
the right way would be to put punctuation marks in translation strings; ie :
PaymentTerms: 
would be translated by Payment terms: in english and by Conditions de règlement : in french

**Comment by rdoursenaud** [comment]
Yes @altatof. Exactly what I suggested 2 years ago.
Also, to make it clean, use a replacement string instead of concatenation. This conveys intent and meaning and helps the translator shape the result to suit the cultural characteristics of his language.

For example:
```php
{
	if (!$mailmanspip->del_to_spip($object)) {
		setEventMessage($langs->trans('DeleteIntoSpipError', $mailmanspip->error), 'errors');
 	}
}
```
English translation:
```
DeleteIntoSpipError=Remove from SPIP: %s.

```
French translation:
```
DeleteIntoSpipError=Supprimer de spip&nbsp;: %s.
```
Notice that the french typographic convention is to prepend the colon with a non breakable space and follow with a regular space. This is to prevent the colon from slipping on the next line when formatted, essentially gluing it, spaced, to the previous word while allowing the rest of the sentence to break into a new line.
I used the HTML convention to make it explicit. The unicode character is also fine.
I also added the final dot which is typographically correct.

**Comment by altairis-tof** [comment]
@rdoursenaud : it would be perfect !

**Comment by altairis-tof** [comment]
an easier way to solve colonn problem would be to have a $langs->trans(":") translated by ": " or " : ".

**Comment by rdoursenaud** [comment]
No @altatof. You don't want to arbitrarily restrict translators work. There may be situations you haven't evaluated that need different translations. Punctuation is always part of a context and should never be isolated.
Let the translator decide!
One use case I can thing at the top of my head is a duration or time. You wouldn't want `12:00:00` displayed `12 : 00 : 00`!

**Pull request closed without merging**
