### PR TITLE
FIX include oauth.lib.php, not require_once as it defines local varia…

### PR DESCRIPTION
**Pull request by mdeweerd**
# FIX include, not require_once a oath.lib.php which defines locals.

DOL_DOCUMENT_ROOT.'/core/lib/oauth.lib.php' defines locals.
"require_once" would make the code fail on multiple calls or when the file is included in multiple locations in the same execution.

So this must be included every time.

### CODE REVIEW

**Comment by mdeweerd** [comment]
May fix #24940 , ##24163 (not verified).

**Comment by eldy** [comment]
Yes, it includes variable.
However it should be constant variable that should not be modified so no reason to call the file a second time.
Also it contains a function, so doing an include will generate fatal error.

**Comment by mdeweerd** [comment]
Ok, I did not see the function, but this can be protected from relaod.

The value of the variable is overridden (set to empty) in several cases before the require_once.

Also this is used in different scopes, so there is the risk that this is not defined in the right execution scope.

Finally, this was also noticed by phan in a way and by changing this to include, the typing is recognized and some notifications disappear.
I'll protect the function.

**Comment by eldy** [comment]
OAuth.lib is a lib.php
So it should not be used as if it was a .inc.php
So i pushed a better fix.

**Comment by mdeweerd** [comment]
https://github.com/Dolibarr/dolibarr/blob/1d589fd74e29a1f872a120277b11194b59dc9e3c/htdocs/core/class/CMailFile.class.php#L925

https://github.com/Dolibarr/dolibarr/blob/1d589fd74e29a1f872a120277b11194b59dc9e3c/htdocs/core/class/CMailFile.class.php#L1080

https://github.com/Dolibarr/dolibarr/blob/1d589fd74e29a1f872a120277b11194b59dc9e3c/htdocs/emailcollector/class/emailcollector.class.php#L1135

**Pull request closed without merging**
