### PR TITLE
link clients mail/card to ticket messages

### PR DESCRIPTION
**Pull request by MaximilienR-easya**
# New
We can now see a link to the contact card or just the email (if not found) of the contact who send a message via the public interface.
Inside the public interface, we do not have a link to the contact card, just the name or email (if not found).

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide a screenshot ?

**Comment by eldy** [comment]
Can you provide a screenshot ?

**Comment by MaximilienR-easya** [comment]
In this screenshot, TEST Jean and MANIQUANT are clients who have sent messages via the public ticket interface and this is how we see it in the list of messages on the public page
Public interface message side

Here we see the same case as the first screenshot but from the ticket card messages list, here we have a link to the card of the contact present on their name
ticket card interface

At this one, we have a case with a client who is not found (in case the option to permit ticket from people who are not client in the options)
User not found public side
User not found show email

**Comment by MaximilienR-easya** [comment]
@eldy I have provided some screenshot

**Pull request merged**
