### PR TITLE
This module is not enought stable to be native

### PR DESCRIPTION
**Pull request by defrance**
they are problems with stock values

### CODE REVIEW

**Comment by BebZ** [comment]
Can you reproduce on stable demo please ?
http://demo.dolibarr.org/product/stock/product.php?id=2624
I couldn't make a stock mistake or miscalcuation with : 
http://demo.dolibarr.org/product/stock/mouvement.php?idproduct=2624&mainmenu=home

**Comment by eldy** [comment]
Can you mention the bug you have on this module. Like BebZ, i don't experience problems.

**Comment by defrance** [comment]
sample 1
you receive 24 product from fournish
you send to a customer 12 products
the quantity in llx_product_batch stay in 24
the product_stock is ok (12)

sample 2
you receive 10 product from fournish
you send to a customer 10 products 
the quantity line on llx_product_batch is deleted instead to update the value to zero

**Comment by BebZ** [comment]
I don't understand
I have well computated values here : 
Was +49 originally and sent -30 to customer

It is displayed well on fiche entrepot here
But you can also check values in the list of movements 

http://demo.dolibarr.org/product/stock/product.php?id=2624

And also on stock card here with correct values

http://demo.dolibarr.org/product/stock/mouvement.php?id=20

I have no access to DB datas but I think those values emanates from there...

**Comment by defrance** [comment]
I dont understand too, 
I have made test on 3.8.2 with the default setting and a partial sending don't décrease the quantity of serialised product...

**Comment by eldy** [comment]
I close request. Looks more and more stable even if not perfect yet.

**Pull request closed without merging**
