### PR TITLE
Implemented constants for some object types and statuses

### PR DESCRIPTION
**Pull request by marcosgdf**

### CODE REVIEW

**Comment by BebZ** [comment]
what is it made for ?

**Comment by rdoursenaud** [comment]
@BebZ Make code more readable and thus more maintainable.

**Comment by BebZ** [comment]
+1 Good for noobs like me. 
Why constants and not Comments? wouldn't be adequate because it doesn't display everywhere systematically ?
So some modules using statuses like : if blabla > 1 could be affected and should change their code ?

**Comment by rdoursenaud** [comment]
Yes, the idea is to replace occurences of single digits in the code by their meaning (the constant).
ie:

``` php
if ($product_type == 0) {
    // Do something
}
```

by

``` php
if ($product_type == Product::TYPE_PRODUCT) {
    // Do something
}
```

which is more readable and understandable.

**Comment by marcosgdf** [comment]
In fact there is more beyond that... If in the future the digit that represents an status changes, the value of the constant can be changed and the rest of the code won't need to be changed.

**Comment by BebZ** [comment]
All right :) good explanations and ideas, professors :)

Last question :
if code uses digits like :
if ($value >=0) {
                                                                         //
do something
}
;
else if ($value <0) {
           // do another thing
}

What should we do, is it allowed to write if ($value == Value::constant1
"or" Value == constant2 "or".... ?

PS : be indulgent i never wrote a single line of code :( except copy paste
of old oscommerce memories :)

_Hubert ANDRIOLO_
_Gérant F.M. MEDICAL et NORD HYGIENE_
Mobile: +33 (0) 6 23 10 17 31
Fax: +33 (0) 9 56 51 95 71
Site: www.fournisseur-medical.com

_FM MEDICAL - NORD HYGIENE_
280, rue berthie Albrecht
62110 Hénin-Beaumont
SIRET : 532 788 700 00021
N° de TVA : FR15 532 788 700

2015-04-13 12:16 GMT+02:00 Marcos García notifications@github.com:

**Comment by eldy** [comment]
Constant are good when they have a specific hard coded meaning. So for a status. For a comparison of amount to test is result is negative or not, just keep 0.

**Pull request merged**
