### PR TITLE
Add swedish chart of accounts (K1 MINI)

### PR DESCRIPTION
**Pull request by swedebugia**
Are the rowids correct?

### CODE REVIEW

**Comment by swedebugia** [comment]
psql complains like this when I try to insert it: 
ERROR:  value too long for type character varying(20)
ERROR:  value too long for type character varying(20)
ERROR:  value too long for type character varying(20)
ERROR:  value too long for type character varying(20)
ERROR:  value too long for type character varying(20)
ERROR:  value too long for type character varying(20)
ERROR:  value too long for type character varying(20)
ERROR:  value too long for type character varying(20)
ERROR:  value too long for type character varying(20)
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
ERROR:  value too long for type character varying(20)
ERROR:  value too long for type character varying(20)
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1

So I'm guessing some of the swedish account names are longer than expected.

**Comment by swedebugia** [comment]
I issued this command to find the culprit:
dolibarr=> select * from llx_accounting_account \gdesc
         Column         |            Type             
------------------------+-----------------------------
 rowid                  | integer
 entity                 | integer
 datec                  | timestamp without time zone
 tms                    | timestamp without time zone
 fk_pcg_version         | character varying(32)
 pcg_type               | character varying(20)
 pcg_subtype            | character varying(20)
 account_number         | character varying(32)
 account_parent         | integer
 label                  | character varying(100)
 fk_accounting_category | integer
 fk_user_author         | integer
 fk_user_modif          | integer
 active                 | smallint
 import_key             | character varying(14)
 extraparams            | character varying(255)
(16 rows)

 pcg_type               | character varying(20) <-- this is too short for swedish category names it seems.

After changing this with:
dolibarr=> alter table llx_accounting_account
alter column pcg_type type varchar (50);

It imported the rest just fine :)

**Comment by eldy** [comment]
The field pcg_type is dedicated to store a hard coded constant among this list:
CAPIT
IMMO
STOCK
THIRDPARTY
FINAN
EXPENSE
INCOME
OTHER

Currently, some files doe not follow this. This is not important because only "EXPENSE" and "INCOME" are used for some report but to be ready for future, it would be great if you can edit your file to use this codes into your submitted file. Can you try to fix this ?

**Comment by swedebugia** [comment]
Is this okay?
[llx_accounting_account_se.sql.txt](https://github.com/Dolibarr/dolibarr/files/3536221/llx_accounting_account_se.sql.txt)

**Pull request closed without merging**
