### PR TITLE
Fix #28071 - New branch to fix bad merge

### LINKED ISSUE #28071: Merge that went wrong?
### Bug

@eldy  Sorry for tagging directly, but this concerns a merge

https://github.com/Dolibarr/dolibarr/compare/2a28248..854292e

Something went wrong when merging 2a28248d to 854292e .  

I double confirmed that this is a direct transition (7db64c5bcc0 is the commit just before 2a28248d):
```
$ git rev-list --ancestry-path 7db64c5bcc0..854292ea47d
854292ea47ddb87714fae56e2dc4d338a5dd238f
2a28248dd4e9202d7cadfc9e91de35d29ab16173
```

I discovered this when I went looking for the reason some changes that I made in PR's went missing in the develop branch.

### PR DESCRIPTION
**Pull request by mdeweerd**
# Fix #28071 - New branch to fix bad merge

The head of this branch has no difference with 2a28248dd4e9202d7cadfc9e91de35d29ab16173 that was not merged correctly in the develop branch.

There is no difference before and after the merge that should have integrated the above commit hash:
https://github.com/Dolibarr/dolibarr/compare/eb4f53665d2..854292ea47 .

Merging this PR should get back the missing pull requests and commits.

### CODE REVIEW

**Comment by mdeweerd** [comment]
For clarity, 3fe5a24 is the commit that has the same content as 2a28248 .
I updated dev/tools/codespell/codespell-lines-ignore.txt to be exactly the same as the one in develop to avoid conflict - it can be updated after the merge to avoid detection of spelling issues as needed.

**Comment by eldy** [comment]
Too many pr were merged since, so this one is in conflict.
I discovered some pr that disappeared but i don't understand why.
Do you know whichvor has been lost ?

**Comment by mdeweerd** [comment]
There are only a few conflicts and the branch that I constructed here concerns all the commits that were lost - about 70 commits.
See Issue #28071's description for the script and analysis of the merge issue.

I identified the exact merge where all these commits were lost.
It was a "null merge": nothing was effectively merged - on the develop branch nothing changed, but the merge was recorded.  That means that everything on the side branch was lost.

There are not that many conflicts - I suggest that you check out his merge branch locally, merge develop into the branch, fix the conflicts, push, and then merge to develop.
That is IMHO really the best option.

**Comment by W1W1-M** [comment]
Would reviewing changes through GitHub PR review be any help ? or not useful ?

**Comment by mdeweerd** [comment]
All the commits proposed here were already validated before because they would  have been integrated in the develop branch.

I propose the following approach.

I merged develop in this branch in my fork, with the conflicts (branch redo1-fix-conflicts).
From there I branched to redo-1-fix-conflicts-pr where I made a change to the 10 files needing a conflict fix, and created a PR from redo-1-fix-conflicts-pr to redo-1-fix-conflicts:
https://github.com/mdeweerd/dolibarr/pull/1

That PR now shows the 10 files that need a change in the "Files Changed" tab, anyone can propose a fix for those.
Once all 10 are fixed, I can propose that branch as a PR to dolibarr/develop.

**Comment by mdeweerd** [comment]
@eldy I would not have merged develop directly on this PR at this time.  I can still recover the version just before it.

Look at https://github.com/mdeweerd/dolibarr/pull/1 : I fixed several issues, 4 files still need fixing and it's more manageable.

**Pull request merged**
