### PR TITLE
NEW Support barcode on supplier price references

### PR DESCRIPTION
**Pull request by atm-quentin**
# New Supplier Buy price Barcode

Give possibility to manage buy price by barcode.
When you scan your product, you immediately find the good buy price on supplier object
You can go to the product page too by scanning this code

(https://github.com/Dolibarr/dolibarr/pull/10642)

### CODE REVIEW

**Comment by atm-quentin** [comment]
ping @eldy

**Comment by BebZ** [comment]
Duplicate entry '0000000000001-2-1' for key 'uk_product_barcode' sql=UPDATE llx_product_fournisseur_price SET fk_user = 1 , ref_fourn = 'XXXX', desc_fourn = '', price = 19, quantity = 1, remise_percent = 0, remise = 0, unitprice = 19, fk_availability = 2, multicurrency_price = '0', multicurrency_unitprice = null, multicurrency_tx = '1', fk_multicurrency = null, multicurrency_code = '', entity = 1, tva_tx = 0, default_vat_code=null, info_bits = 0, charges = 0, delivery_time_days = null, supplier_reputation = NULL, barcode = '0000000000001', fk_barcode_type = '2' WHERE rowid = 2482

Do I have to open an issue ? 
The same product with the same barcode 
can be bought to 2 different suppliers
it should not check for duplicates if the supplier is not the same.

I tried to add the same barcode to 2 different supplier prices, and it went back wrong.

**Comment by atm-maxime** [comment]
@BebZ in your example you're saying that the barcode is relative to the product, so record it on the product card, not on the purchase price.

**Comment by BebZ** [comment]
Thanks for answering me long time ago and sry i did not notice your anser.
I was trying to record 2 barcodes for 1 product and 1 supplier.
 Because they have a barcode for the unit and a barcode for a carton of x units
and another barcode for a box of y cartons of x units ;)

**Pull request merged**
