### PR TITLE
Option for rewrite sorting button on ref.

### PR DESCRIPTION
**Pull request by andrelec1**
Add column num facture and sorting ...

uigj
3t7h

[edit] 
the column didn't display anymore ... 
but you can change sorting option

### CODE REVIEW

**Comment by eldy** [comment]
There is no correlation between number of credit note and standard invoice. So why sorting on this ?

**Comment by andrelec1** [comment]
We need this modification because our account expert need to classify bills by creation number.
In the case of the bill is backdated, the sorting order is sometime wrong.

PS : Look bill FA1407-0004 and FA1407-0005 in screen-shoot.

**Comment by marcosgdf** [comment]
¿Why would someone want that by default?

I do think this is more appropriate for an external module.

**Comment by gonzalesleo** [comment]
I find it useful too. But we could indeed make it optionnal by adding an "ON/OFF option button" in the settings.

**Comment by aspangaro** [comment]
In accountancy, it´s useful to detect an invoice or credit note who are deleted (it´s forbidden in french accountancy) but a new column without a separation by type is not user friendly and in fact not needded by everyone, maybe an option ?

**Comment by eldy** [comment]
It is strange to sort on "creation date". You probably mean sorted on "validation date" (before validation, it is just a draft with no real existence).
So what you need, is probably a sort on validation date. I prefer to see a hidden option to have this field added into the list.

**Comment by andrelec1** [comment]
I remove the column and i add a option for rewrite sorting button on ref.

**Comment by gonzalesleo** [comment]
Any news from this PullRequest ?

**Comment by marcosgdf** [comment]
PR is targeted to develop branch so it seems it is not going to be for 3.7 version.

**Comment by eldy** [comment]
Last comment was

"It is strange to sort on "creation date". You probably mean sorted on "validation date" (before validation, it is just a draft with no real existence).
So what you need, is probably a sort on validation date. I prefer to see a hidden option to have this field added into the list."

Does this comment was considered ?

**Comment by eldy** [comment]
Closed. Missing answer and conflict for a too long time.

**Pull request closed without merging**
