### PR TITLE
NEW Can update product type through API Rest (2nd possibility)

### PR DESCRIPTION
**Pull request by c3do**
New: UpdateType method in product.class.php
New: Update product type through API Rest using updateType method

### CODE REVIEW

**Comment by eldy** [comment]
Why a second method compared to #12135 ?
The #12135 seems already ok for me.

**Comment by c3do** [comment]
> 
> 
> Why a second method compared to #12135 ?
> The #12135 seems already ok for me.

Just to give you the choice.
Both works.
If the first is more appropriate for you, so let's go for the first.

**Comment by eldy** [comment]
> > Why a second method compared to #12135 ?
> > The #12135 seems already ok for me.
> 
> Just to give you the choice.

:-) It is no more open source, it is luxe source
> Both works.
> If the first is more appropriate for you, so let's go for the first.

**Comment by eldy** [comment]
First method match better CRUD rules (one method for Create, Read, Update, Delete)

**Pull request closed without merging**
