### PR TITLE
NEW|add member civility to the labels

### PR DESCRIPTION
**Pull request by AlainRnet**
# NEW|New add member civility to the labels
as described on https://www.dolibarr.fr/forum/t/modification-carte-ou-licence-adherent/36013/15
But I don't know how to do to add extrafields. If anybody has an idea to get me on the track...

Note that the global variable ADHERENT_ETIQUETTE_TEXT does not work. \n appear in text instead of a return line, only those of this file return a new line, as described on https://www.dolibarr.fr/forum/t/personnaliser-champs-a-imprimer-sur-etiquettes-pdf-des-adherents/47668

### CODE REVIEW

**Comment by hregis** [comment]
@AlainRnet request civility code instead the label and use langs->trans with civility code

**Comment by AlainRnet** [comment]
You’re absolutely right, thank you for the tip!
Do you have a lead for the extrafields, which are "options" based on what I see in the MySQL rendering: options_". $key ??

**Comment by hregis** [comment]
@AlainRnet try the tag `__OPTIONS_XXXX__` XXX is the $key in upper case

**Comment by AlainRnet** [comment]
Thank you @hregis this niew code works for me.

To understand: in the next line, what is the function `complete_substitutions_array($substitutionarray, $langs, $adherentstatic);`? Strangely, if I comment on this line, it does not change the rendering?!?

**Comment by hregis** [comment]
@AlainRnet "complete_substitutions_array" is for external module for completed/personnalized the substitution

**Pull request merged**
