### PR TITLE
New | Add AGENDA_SORT_EVENT_TYPE_BY_POSITION_FIRST hidden conf to change sort method of actions

### PR DESCRIPTION
**Pull request by hansemschnokeloch**
# New | Use position as main sort criterion
Currently the `position` defined in the dictionnary isn't the main sort criterion. This prevents you from ordering the actions as you wish.
This PR changes the sort criterions order, and defines the `position` as main sort criterion

### CODE REVIEW

**Comment by eldy** [comment]
Yes goal of position is to sort record among a given type. Prority is on type because we always want to have actions of the same type together...

**Comment by hansemschnokeloch** [comment]
I see your point.
But sadly this prevents you to put the most used items in top of the select when you create manually an event.

**Comment by eldy** [comment]
> I see your point.
> But sadly this prevents you to put the most used items in top of the select when you create manually an event.
> 

I see. I suggest to introduce a hidden conf (no need for setup, just the test for one order by or thevother) to allow your behaviour for integrators.

**Comment by hansemschnokeloch** [comment]
> I see. I suggest to introduce a hidden conf (no need for setup, just the test for one order by or thevother) to allow your behaviour for integrators.

I added a hidden conf. I didn't find any naming convention in the docs for such variables. I hope the name is fine, it should be self-explanatory enough.

**Comment by hansemschnokeloch** [comment]
@eldy PR ready for review

**Pull request merged**
