### PR TITLE
Update Restler to 3.0.0RC6

### PR DESCRIPTION
**Pull request by nka11**
# Fix REST API dependencies for PHP7+

### CODE REVIEW

**Comment by nka11** [comment]
fix for #4912

**Comment by eldy** [comment]
It's a pain to not have at least on phpunit test on rest api. I am always threatened by upgrading external lib.
Do you have such an api script client in your basket ? If yes, can you add it to this ticket so i can enhance our ci platform to validate more easyly such PR ?

**Comment by nka11** [comment]
I can provide a few phpunit script with httpful dependency, did you uncomment unit tests on travis build file ?

**Comment by eldy** [comment]
PHPUnit test are fully enabled with travis. This is the main goal of travis. All tests are defined into file
test/AllTests.php
This includes tests for web services SOAP, but i don't have any phpunit tests for API REST. I need at least one. "few" is better but if I can have just one example, it would be enough...
For example, adding a file
/home/ldestailleur/git/dolibarr/test/phpunit/RestAPIUserTest.php
that do same thing than 
/home/ldestailleur/git/dolibarr/test/phpunit/WebservicesUserTest.php
(so a simple get of admin user)
but using API REST instead of SOAP would show me the way. So travis would be able to make some regression tests on possible api regressions.

**Comment by nka11** [comment]
Okay for writing unit test for REST services, I have some tests for it already described in another project, I use httpful dependency. Do you have it in dolibarr ? if no, i'll be glad to have an hint for adding it.

I'll be really pleased to trust you about the fact that httpunit tests are fully enabled in travis, but I've never seen any test report on recent builds.
Tell me if I'm wrong, but I interpret the symbol # at the beginning of line 294 in .travis.yml as a comment symbol, and I guess it instruct the build to ignore text after it. 
https://github.com/Dolibarr/dolibarr/blob/develop/.travis.yml#L294

**Comment by nka11** [comment]
PR #5181 opened with a new test class and phpunit enabled

**Comment by nka11** [comment]
I finally spotted a blocker for it in #5196.
Composer is misused and many files should not be in version control, at first, composer.lock, and the whole directory downloaded by composer.

**Pull request merged**
