### PR TITLE
additional fields for margin modules

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by eldy** [comment]
Hi Christophe.
Can you resubmit you push request using normalized field name:

fk_fournprice int(11)   ->  fk_product_fournisseur_price
pa_ht   ->  buy_price_ht
marque_tx   ->   margin_buyprice
marge_tx    ->    margin_sellprice

Rem: Les champs marges contiennent quoi (un pourcent ?) et sont calculées comment ?
Ne faut-il pas mieux stockée une valeur de marge (et non un pourcent) car stocké des pourcent, c'est stocké des valeurs arrondies dont on ne peut retrouver les valeurs de calcul d'origine alors que l'inverse, avoir les valeurs absolues permet toujours de retrouver le pourcent. Ceci est important pour pouvoir faire des statistiques exactes.

**Comment by altairis-tof** [comment]
Hi Laurent,
In fact, the fields pa_ht, marge_tx and marque_tx were already existing in llx_propaldet, that's why i used this name.
OK for the renaming of fk_fourprice.

Les champs marge_tx et marque_tx contiennent les taux de marges et taux de marques qui seront appliqués lors du calcul des marges. Ce sont des taux et non des valeurs arrondies.

Il ne faut surtout pas stocker une valeur, car les prix fournisseurs peuvent varier entre la commande/propale et la validation de la facture et donc les marges également.

**Comment by altairis-tof** [comment]
by the way, the margin module is already used on dolibarr311 by three customers (who paid for the development).
it would be better not to change the tables field names so they can migrate later to new dolibarr versions without problem.

may i add that fk_product_fournisseur_price seems a strange normalized name since it contains french and english words... there are lot of strange things like this in dolibarr (fournisseur is supplier in english) and maybe we should one day really normalize the code using one language or another but not a mix.

**Comment by eldy** [comment]
Having customer or not onto external modules can't be used to define direction of dolibarr code code.

fk_product_fournisseur_price is simply the rule  fk_table_pointed_to. So what is strange is not foreign key name, but table name pointed by foreign key. It will be changed one day probably. As you say "one day". The better day is just after a major release when major change on data structure is ready. Current dev branch is ready for such changes. The rule is simple: Now everything must be english if no other rule apply.

Also marge_tx et marque_tx are rates, so they are result of a division. We should instead store data used for division. 
If we need a calculation that is a snapshot at a t time, it would be better to store value of buying total ht (already done into pa_ht). Calculating the marge or marque can be done with only this value.
marge = prix vente - cout achat / cout achat  (prix vente is already saved, we only need cout achat) and marque = prix vente - cout achat / prix vente (agin we only need cout achat)

And if we need a dynamic value (changes when buying value change), there is no need to store anything, we can recalculate with new link to fk_product_fournisseur_price.

That's why marge_tx and marque_tx are useless field for me and should be removed. 
Only pa_ht and fk_product_fournisseur_price are required.

**Comment by altairis-tof** [comment]
you convinced me about field names. and you're right about the table name too.
it seems you're also right with the inappropriate storage of the rates; i guess i did it because the fields were already present in the llx_propaledet structure. I will check my code on friday to see if there aren't any other reason.
but before we remove marge_tx and marque_tx from the tables structure, i suggest we post a confirmation question on the dev mailing-list, to be sure nobody is using these fields in a way or another, especially the one who put them in the table structure - i guess it's Regis.
I thank you a lot for your implication and explanations about my mistakes; we should find a better way to share like this before and during the coding, and not after; it will improve our efficiency.
I have tried to put a mail about this dev one or two weeks ago on the dev mailing-list, but i had no response except proposal for translations - which was very stimulating, and (to my true surprise) a selling of this module to one follower.
At my sense, doliforge is not an appropriate place for such discussions, besides all its assets, or i didnt find the way to use it correctly; the dev mailing-list is a good start, but i think we should at term move this type of discussion to a more convenient place, like a community website dedicated to the dev of the software.
Well, since it's definitively not the place for such discussion here on github, i say you again thanks and good night !
Oh yes, one latter news, i'm working on the local taxes management for any country (vs hard-coded tests for ES as at the moment !)
Désolé pour ce laïus, mais j'étais lancé - et sûr que tu me lises ;-)

**Comment by eldy** [comment]
May be we can open a draft page into wiki for all new features to discuss before starting dev.

I did it few weeks ago for the multicurrency feature:  http://wiki.dolibarr.org/index.php/Draft:Multi-Currency

**Comment by altairis-tof** [comment]
i close this pull request and will open a new one asap.

**Pull request closed without merging**
