### PR TITLE
Mailing for supplier orders

### PR DESCRIPTION
**Pull request by IonAgorria**
This pull adds mailings for creating diferent supplier order mail templates which are seleccionable when sending mail in supplier order page

You can put order information in mail, per line format etc
__ LINES __ will be filled with all lines of order, the line format is specified in mailing editor

I have cleaned some old code by the way, renamed titre to description and sujet to subject, moved substitution arrays from card.php to separate methods in mailing.class.php, fixed using $this-> in static method libStatutDest

### CODE REVIEW

**Comment by IonAgorria** [comment]
There is something wrong?

**Comment by BebZ** [comment]
I'm sure it's too good... but it's too good to be true...

**Comment by eldy** [comment]
Problem here is that the method to select between template is a method that take data from the mass emailing module. The mass emailing module must not share code with email template. There is a table to store email templates. It is called llx_c_email_templates. We must use this one to suggest templates into form to send email from order or invoice pages.

**Comment by BebZ** [comment]
will someone correct it ? to not let it fall in the hole of great features forgotten ?

**Comment by IonAgorria** [comment]
At this moment I'm working with https://github.com/Dolibarr/dolibarr/issues/2587 which is taking more time than excepted, if someone fixs this would be great, if not i will try to fix myself when I finish the current task.

**Pull request closed without merging**
