### PR TITLE
Introducing amount in the main dashboard

### PR DESCRIPTION
**Pull request by defrance**
Because the total amount is more significant than the number
Need to change all the class to introduce this feature
Maybe add some rights to show or not the amount is a plus

### CODE REVIEW

**Comment by defrance** [comment]
IS somebody interested by this feature, total amount is more interesting than the number ...

**Comment by eldy** [comment]
What about other lines ? A new td is intrduced but what happened with of lines of other objects that does not support yet this ne field ?

**Comment by defrance** [comment]
@eldy: I did not go to the end of the modifications, just explain the concept and  wait for your agreement on the principle of operation before doing laborious work ...
If it is ok, I add them now

**Comment by defrance** [comment]
@eldy : the feature is ok for you? can i start to achieve the function?

**Comment by aljawaid** [comment]
I think the value would be useful but the number is useful too.

Either have a "number (£value)" display with user rights showing number only
Either have a switch to show "number" or "£value"

**Comment by altairis-tof** [comment]
i still do not understand why this type of discussion is not on a forum thread where users may read it and express their needs.

**Comment by aljawaid** [comment]
Because the English forum is not so active :(

**Comment by altairis-tof** [comment]
it will be more active if such debates would have a place on it ;-)

**Comment by defrance** [comment]
So I close it, another PR made for that

**Pull request closed without merging**
