### PR TITLE
NEW : Supplier recursive invoice 

### PR DESCRIPTION
**Pull request by atm-adrien**
# NEW|New Supplier recursive invoice 

We plan to develop the **"Template/Recursive invoices" functionality for the supplier invoices** juste like it is for customers inoices.
For now, we just developed the datamodel : 
- Creation of llx_facture_fourn_rec.sql file 
- Creation of llx_facture_fourn_rec.key.sql file 
- Creation of llx_facture_fourn_rec.extrafields.sql file 
- Creation of llx_facture_fourn_rec.extrafields.key.sql file 
- Creation of llx_facture_fourn_det_rec.sql file 
- Creation of llx_facture_fourn_det_rec.key.sql file 
- Creation of llx_facture_fourn_det_rec.extrafields.sql file 
- Creation of llx_facture_fourn_det_rec.extrafields.key.sql file 

- Update of 14.0.0-15.0.0.sql file to create all recursive supplier invoice tables
- Update of the supplier invoice class to add fk_fac_rec_source field

Can you validate it ?

### CODE REVIEW

**Comment by BebZ** [comment]
You have to rename your company name to Santa-ATM with this potential wonderful gift :)

**Comment by aspangaro** [comment]
Thanks but the future version 15.0 of Dolibarr is now freeze. You need to create a migration file from version 15 to version 16, simply open a new file based on a previous migration file.

**Comment by atm-maxime** [comment]
#9598

**Comment by eldy** [comment]
@atm-adrien It's ok with tables and fields. Can you rename file 14.0.0-15.0.0.sql into 15.0.0-16.0.0.sql

**Pull request closed without merging**
