### PR TITLE
NEW: Dev documentation about setting up pre-commit locally

### PR DESCRIPTION
**Pull request by mdeweerd**
# NEW: Dev documentation about setting up pre-commit locally

A quick start guide about setting up pre-commit.

### CODE REVIEW

**Comment by eldy** [comment]
May be rhe README file should be in a dev/setup/precommit dir ?

**Comment by mdeweerd** [comment]
@eldy 
I noticed afterwards that there is a policy to add documentation in separate subdirectories, but I found that not to be very practicle: a developer needs to look into every subdirectory and every README to determine which tools to setup and which are useful. 

Other than the README there is no other file to add to the subdirectory and IMHO, pre-commit is something that should be recommended to the developer.
I think the README could be extended with a summary of what the other directories are for.

I do not determine the policy, but I do recommend to keep this README at least in the root directory of the setup directory.
OR, put a small README in the setup directory and the more detailed documentation in the subdirectory.

Tell me what you want and I'll comply to it.

**Comment by eldy** [comment]
I prefer to have the README into the directory related to what it is speaking about. So into the subdirectory precommit, because we have tons of use case and tons of tools. The dev must choose according to its time.
To solve the pb you mention: "no directive for dev" (and i agree we should be stricter on this point), we can add a readme also into the dev/setup directory, but it would be better to point into this readme to the wiki developer https://wiki.dolibarr.org/index.php?title=Environment_and_development_tools
and then complete this wiki page with instructions recommended for each developers...

**Comment by mdeweerd** [comment]
Done:
- README.md moved to subdirectory;
- Small README.md at the root for setup referencing the online URL.

CI reported spelling errors are in files not related to this PR.

**Pull request merged**
