### PR TITLE
Fix line_order when we have children with children

### PR DESCRIPTION
**Pull request by MaximilienR-easya**
# Fix

Fix case when we have children with children that are not taken into account and cause a problem with the rank of the lines

### CODE REVIEW

**Comment by eldy** [comment]
What was the trouble ? Can you provide an example ?

**Comment by MaximilienR-easya** [comment]
In a case that we have a product (Test0) who have a child (Test00) who also have child (test01, test02, test03, test04).
Screenshot from 2024-07-22 10-34-19

Without the Fix we obtain that
Screenshot from 2024-07-22 10-33-44
But if we check children recursively, we obtain that

Screenshot from 2024-07-22 10-35-45

If we don't check the children recursively, we can have case like this one where everything is mixed up and not ordered

**Comment by MaximilienR-easya** [comment]
@eldy do you need more exemple ?

**Comment by MaximilienR-easya** [comment]
@eldy is there a problem ?

**Comment by MaximilienR-easya** [comment]
Was finally merged here #31314

**Pull request closed without merging**
