### PR TITLE
FIX bad calculation for stock value

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by simnandez** [comment]
@altatof  3.5 branch is not more maintened.

**Comment by altairis-tof** [comment]
@simnandez i know but eldy write this last time : 
"Not the now 3.8 has been released, version 3.5 is no more maintained. So PR may be accepted, but no new package 3.5.x should be released." (https://github.com/Dolibarr/dolibarr/pull/3701)

and please note that i am talking about wrong stock valorisation that is a very important problem and is not resolved even on develop branch

**Comment by rdoursenaud** [comment]
@altatof Yes but that one was already fixed in other versions. This one is not (your words), so it's better to PR on the lowest supported version to ensure that the fix will be merged in other versions.
Else it may be lost because, AFAIK, 3.5 is not merged into upcoming releases anymore!

**Comment by altairis-tof** [comment]
good point !

**Comment by altairis-tof** [comment]
@rdoursenaud please note that https://github.com/Dolibarr/dolibarr/pull/3701 is not fixed on develop branch (otherwise i have to clean my glasses)

**Comment by altairis-tof** [comment]
PR made to 3.6 here : https://github.com/Dolibarr/dolibarr/pull/3901

**Comment by rdoursenaud** [comment]
@altatof Sorry, I'm the one needing glasses. I red your comment a little bit fast ;)
Hope you can make another PR for that one too then!

**Comment by altairis-tof** [comment]
no problem... i will do it.

**Comment by altairis-tof** [comment]
done https://github.com/Dolibarr/dolibarr/pull/3902

**Pull request merged**
