### PR TITLE
NEW: Added odt support to supplier orders

### PR DESCRIPTION
**Pull request by Tim-Otte**
# NEW functionality to generate odt files for supplier orders
I added the support for generating __odt files__ for *supplier orders*. I basically copied the source from the *commande* module and edited it to match my needs. Then i added a template odt file and the copy logic to the module init.

### CODE REVIEW

**Comment by Tim-Otte** [comment]
Possible implementation of Issue #8111

**Comment by Tim-Otte** [comment]
@eldy Could you review this pull request and merge it if you want? I'd be happy if this feature would be added in the next update...

**Comment by scarcamo-eyg** [comment]
Hi there, waiting for this funcionality, thanks

**Comment by atm-maxime** [comment]
Hi @scaramo-eyg. Since this pull request has been merged 7 months ago, I think this feature is available in stable version 11.

**Pull request merged**
