### PR TITLE
fix entity if interventions are shared between entities

### PR DESCRIPTION
**Pull request by rycks**
Fix a bug : impossible to validate an intervention if there configuration is set to "share interventions between entities"... @hregis please confirm / have a look to that PR
thanks !

### CODE REVIEW

**Comment by rycks** [comment]
@eldy, @hregis explain to me that getEntity should be used only on SELECT requests, not on UPDATE ... then "the good" patch seems to be AND entity = ". ((int) $this->entity); (replace $conf->entity by $this->entity) ... let me check and tests that on my dolibarr dev setup

**Comment by eldy** [comment]
> @eldy, @hregis explain to me that getEntity should be used only on SELECT requests, not on UPDATE ... then "the good" patch seems to be AND entity = ". ((int) $this->entity); (replace $conf->entity by $this->entity) ... let me check and tests that on my dolibarr dev setup

I see. Let me know...

**Comment by rycks** [comment]
hmmm @eldy  as you do the merge i have to make a new PR ?

**Comment by eldy** [comment]
> hmmm @eldy  as you do the merge i have to make a new PR ?

I'm afraid yes. Sorry...

**Pull request merged**
