### PR TITLE
Add region tab for stats in adhrent

### PR DESCRIPTION
**Pull request by squarou**
Hi,

I added a tab to sort members by region.
Need to add some translations but don't know how to do that.

### CODE REVIEW

**Comment by rdoursenaud** [comment]
@squarou Translations for Dolibarr are managed with Transifex: https://www.transifex.com/projects/p/dolibarr/

**Comment by squarou** [comment]
OK. Can you confirm that in order to add new strings I can use Transifex ? I didn't find how neither in transifex or the translation documentation.
Thanks for your answer.
Benjamin

---

 De : Raphaël Doursenaud notifications@github.com
À : Dolibarr/dolibarr dolibarr@noreply.github.com 
Cc : Benjamin benjamin_cantele@yahoo.fr 
Envoyé le : Vendredi 18 avril 2014 11h01
Objet : Re: [dolibarr] Add region tab for stats in adhrent (#1530)

@squarou Translations for Dolibarr are managed with Transifex: https://www.transifex.com/projects/p/dolibarr/

**Comment by rdoursenaud** [comment]
@squarou No, to add new strings, you have to add them in the source code in, at least, the reference language which is en_US.
Please see http://wiki.dolibarr.org/index.php/Translation_system and http://wiki.dolibarr.org/index.php/Translator_documentation
Transifex is then used for translations in other languages.
Feel free to ask for help if this is insufficiently clear.

**Comment by squarou** [comment]
Thanks a lot.

**Pull request merged**
