### PR TITLE
Fix transfer stock

### PR DESCRIPTION
**Pull request by ndrosis**

### CODE REVIEW

**Comment by eldy** [comment]
I can't reprocue any bug with current branch of 3.9.
How can you reproduce the bug of this ?

**Comment by ndrosis** [comment]
Hi eldy,
Go in one Product and try to transfer stock from a warehouse in another.
See below picture.
product card 2016-06-04 12-43-37

**Comment by eldy** [comment]
I try with 3.9.2 and it works even without your fix. I think a fix was already done differently, and i dont and to introduce a PR that may reintroduce a bug if i am right. Can you check on last 3.9 branch (future 3.9.2)  if you still ave problem ?

**Comment by ndrosis** [comment]
Yes I tried it with the 3.9.2 version and not present the problem.
Thanks!

**Pull request closed without merging**
