### PR TITLE
[ task #746 ] add extrafields support on propal object

### PR DESCRIPTION
**Pull request by jfefe**
Now we can add extrafields on propal and use it in ODT document. 
Also the datas of linked propal can be shown in ODT document for invoice.

### CODE REVIEW

**Comment by eldy** [comment]
Sorry, there is conflicts. Merge is not possible from github. Can you solve them ?

**Comment by jfefe** [comment]
I've started on develop branch... Where is conflict?

Maybe could you add my repo as a remote into your local config to be able to merge conflict?

I don't know how to solve conflict,I don't have anyone on my machine :-\ 

Note that extrafields are on invoice too in this pull request (commits added un branch  after pull request)

And for information it's not finished with extrafields, some improvements are coming!

**Comment by eldy** [comment]
Hum, strange.

I think you have no choice to fix on your local branch or you will not
be able to make push anymore. Conflict has not appears because change
was done by another dev after you push. But it is here. So i can't
validate the git push request.

To solve problem:
First, try to make a pull. I think conflicts will appears then.
To solve then, edit files that are "red tagged" by searching the string
"<<<<<"
You will find a part
<<<

## code before

code after


and ask you to edi this part with a version that match the two changes.

Once change is done into file, you must make an "Add to index" onto file
(it means, "i have solved the conflict on file").
Repeat this on each file that is "red tagged".

Then commit and push again.

Le 08/03/2013 01:47, jfefe a écrit :

> I've started on develop branch... Where is conflict?
> 
> Maybe could you add my repo as a remote into your local config to be
> able to merge conflict?
> 
> I don't know how to solve conflict,I don't have anyone on my machine :-\
> 
> Note that extrafields are on invoice too in this pull request (commits
> added un branch after pull request)
> 
> And for information it's not finished with extrafields, some
> improvements are coming!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/715#issuecomment-14596340.

## 

Eldy (Laurent Destailleur).

EMail: eldy@destailleur.fr
Web: http://www.destailleur.fr

Dolibarr (Project leader): http://www.dolibarr.org
To make a donation for Dolibarr project via Paypal: contact@destailleur.fr
AWStats (Author) : http://awstats.sourceforge.net
To make a donation for AWStats project via Paypal: contact@destailleur.fr
AWBot (Author) : http://awbot.sourceforge.net
CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by jfefe** [comment]
Ok conflicts resolved.

**Pull request merged**
