### PR TITLE
Updated codesniffer descriptor

### PR DESCRIPTION
**Pull request by marcosgdf**

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Great!

**Comment by eldy** [comment]
I would prefer to have PR that add one criteria at time. So we can solve it step after step. Reason is to avoid to have Continuous integration saying "error" during a too long period.

**Comment by marcosgdf** [comment]
What about using PSR-1 temporarily instead of PSR-2? It is less strict.

The problem was that PEAR CS is not the same as PSR-2 and I was facing CS errors that were actually incorrect.

**Comment by marcosgdf** [comment]
Hi @eldy, I'd like this conversation to continue

**Pull request closed without merging**
