### PR TITLE
Fix : Product supplier price is related to supplier's currency

### PR DESCRIPTION
**Pull request by atm-maxime**
When adding a new product in a supplier order, the product supplier price was inserted in "Unit Price". But if the currency is different from the company's currency, it should be in "Unit Price Currency", then unit price is recalculated. A supplier mainly use prices in its own currency.

### CODE REVIEW

**Comment by atm-maxime** [comment]
@eldy Not qualified because ?

**Comment by atm-maxime** [comment]
ping @eldy

**Comment by eldy** [comment]
Because you fix a "not implemented feature" by introducing a more serious "bug". It is better to say feature to define another currency when setting a supplier price is not yet available in v5 that trying to solve it in a way it will corrupt data by sharing in same field amount in a currency and amount into another.
It is not possible to fix this in v5 because this need to change the database model, like i did in v6. See my previous explanation. The approach to solve this must be done differently and use the new fields introduced in v6.

**Comment by eldy** [comment]
Closed because need a different approach for a definitive solution

**Pull request closed without merging**
