### PR TITLE
Add translation from pcbelt@hotmail.com(Rodrigo Beltrán) get from

### PR DESCRIPTION
**Pull request by FHenry**
assodolibarr@gmail.com

### CODE REVIEW

**Comment by simnandez** [comment]
There is a grammatical error: Must be Clave, and not Clabe

**Comment by marcosgdf** [comment]
This translation is not right. It is CLABE and not CLAVE.

Also, IBAN and BIC are international acronyms created for a specific purpose. They **should not** be translated.

**Comment by FHenry** [comment]
Ok guys. I'm not spanish fluent. I just get this translation file from a contributor and paste it. I let you check what is the correct translatin.

**Comment by simnandez** [comment]
Marcos is not "KEY" interbancaria?

**Comment by simnandez** [comment]
OK, CLABE... sorry!

**Comment by marcosgdf** [comment]
**CLABE** stands for _Clave Bancaria Estandarizada_ in Mexico, which is like **CCC** in Spain (account number). But Dolibarr is asking for **IBAN** and **BIC** translation, which is not the same. I find this translation incorrect...

**Comment by simnandez** [comment]
Yes, I just found now, I had thought it was the typical confusion B / V

**Pull request merged**
