### PR TITLE
FIX #28533 and #28581 v3 Mo::deleteLine removes the "main" MoLine if consumed line is delete

### LINKED ISSUE #28533: BUG: Mo::deleteLine removes the "main" MoLine if consumed line is delete + GETPOST in class
### Bug

At MoLine with Product type "Services":
Delete consumed line...
image
The result... the parent MoLine is deleted:
image

In the database is the main MoLine deleted, but the linked MoLine is existing!
image

### Environment Version

19

### Environment OS

_No response_

### Environment Web server

_No response_

### Environment PHP

_No response_

### Environment Database

_No response_

### Environment URL(s)

_No response_

### Expected and actual behavior

_No response_

### Steps to reproduce the behavior

_No response_

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by Humml87**
To fix this Issue #28533, some changes are required.
Thru this Bugfix the Issue #28581 also fixed.
To understand it better, i make a few pictures:
image
image
image
image

I hope this work is now successful *pfffff* .
Best regards
Christian

### CODE REVIEW

**Comment by eldy** [comment]
Before analyzing the fix, it is important to be able to reproduce the bug.
On last version (with fix done few days ago), I do not experience the trouble. Deleting the parent delete the parentand child consummed. Deleting the child delete only the child.
Can you describe a process to reproduct the bug ?

**Comment by Humml87** [comment]
@eldy the link to the answer: https://github.com/Dolibarr/dolibarr/issues/28533#issuecomment-1977246528
Also this fix https://github.com/Dolibarr/dolibarr/issues/28581

**Comment by Humml87** [comment]
Hallo @eldy,
should i recreate this PR into"develop" branch as QUAL?
If i do this, i also make the the API function "Delete a line to given MO" of PR #28515 into "develop" branch.
Best regards
Christian

**Comment by eldy** [comment]
The PR is related to 2 points:
- A bug fix in v19. But i am not able to reproduce the bug with the last version in v19 branch.
- A change to avoid GETPOST into class files. But this has already been fixed into develop branch.

So this PR seems deprecated. 
Note: PR mixing (bug fix and refactoring) are always a bad idea as rules to merge into a maintenance branch (that should contains the minimal change to fix the bug) and rule to merge into develop (that allow refactoring and changing more lines than a fix) are not the same. So such PR can't never be merged.

**Pull request closed without merging**
