### PR TITLE
Set mail reply-to field to sender in smtps class

### PR DESCRIPTION
**Pull request by bafbes**
Set mail reply-to field to sender

### CODE REVIEW

**Comment by eldy** [comment]
Why this ?

Reply-To has not the same meaning than the From. Adn the getAddr return the email qualified for the From.

If an email does not have a Reply-To header, then all human (mail client) replies should go back to the FROM address.
http://stackoverflow.com/questions/1235534/what-is-the-behavior-difference-between-return-path-reply-to-and-from

Does this is to solve a bug ?

**Comment by bafbes** [comment]
In the provided link you can see that the From field is the smtps account used mail name : {C}MAIL FROM:<coolstuff-you=yourcompany.com@mymailinglist.com> that is tied to the smtps mail account used. You can only change it if you change the smtps account in mail configuration.
 while the from field {C}From: coolstuff@mymailinglist.com is configurable in the Mail from field used in the message to send.
This is to get the reply to a different address than the one of the SMTPS account.

**Comment by eldy** [comment]
I can' see difference.
If in the Mail from field, you set the from to  coolstuff@mymailinglist.com
Currently, it means that the from will be coolstuff@mymailinglist.com, and the reply to will be empty (so reply to will be to coolstuff@mymailinglist.com)
After the patch, the from will be coolstuff@mymailinglist.com and reply to will be set to coolstuff@mymailinglist.com to. So reply will also go to coolstuff@mymailinglist.com ?

Right ?
If not, can you provide an example with data that does not work like this ? And what is wrong and expected.

**Comment by bafbes** [comment]
I have two mail accounts : 
- a gmail account that is easily configurable by smtps "bafbes@gmail.com "
  and another account : 
- "contact@dolibarrpar.org" that accepts only accepts the STARTTLS encrytion on smtps.

As there is  presently no way to configure STARTTLS on dolibarr, I had to use my gmail account for sending mails. When I left the "reply-to" field empty, the reply is sent back to the gmail account what may be the value I put in the "From" field. The only solution I could have the reply sent to contact@dolibarrpar.org was by configuring the "reply-to" field to contact@dolibarrpar.org.

**Comment by eldy** [comment]
Interesting. Thanks for info. 
So it means google does not provide the rule "if reply-to not provided, use the from" but instead use the rule "if reply-to no provided", use the email account.

**Comment by BebZ** [comment]
:+1: my customers always replied to the "no reply" address of my company... and i never found a way to fix it ;) thanks

**Comment by bafbes** [comment]
I am happy to have discovered a trick that could help somebody to solve
some problem.

2016-02-10 9:28 GMT+01:00 BebZ notifications@github.com:

**Pull request merged**
