### PR TITLE
NEW: place in warehouse for product object

### PR DESCRIPTION
**Pull request by ptibogxiv**
WIP for place in warehouse for more efficient picking

### CODE REVIEW

**Comment by BebZ** [comment]
Why dont you use warehouses for picking ? I have 3000 warehouses which are places in one warehouse

**Comment by ptibogxiv** [comment]
@bebz because for big company, we need to dispatch warehouse which are physical building or rack ex fridge, building 1, and physical place in this warehouse. And juste use warehouse for global stock is more light and easy for picking. 

Ex: ikea, amazon

I introduce later picking with place with logical order in the warehouse for less Walk while picking and more Quick shipping.

**Comment by dolibarr95** [comment]
Hi!
@ptibogxiv  just to let you know:
In my case for some product we have 2 places (actually I use 2 extrafileds on product card).
First place : where to pick to product
Second place : where to stock the product (when the picking place is empty we take some product from stock zone to pick zone, there is no stock movement).
Because sometimes we receive some very big product or a lot of quantity so we can't store everything at the same place.

Hope it's clear.....

Tks for reading

**Comment by ptibogxiv** [comment]
@dolibarr95 indeed, it's the case of most of big company as amlazon, ikea, la redoute, verbaudet...

they have 1 or more warehouse(s) for stock and another one for picking (some time in differents buidings in differents cities so they made stock movement for reporting this and new value in warehouse (for inventory))

While picking, they have a favorite and logic walk in picking warehouse for easy and quick ship

This is want i want to introduce indolibarr for more efficiency.

whats your extrafields exactly ?

**Comment by dolibarr95** [comment]
Tks for reply.
In my case products can be in 2 warehouses.
And each product can be in 2 places.
Eg for product_XXX

warehouse name  | picking place | stock place
--- | --- | ---
warehouse_0 | 0A12 | Z45
warehouse_1 | 1T27 | d41

Eg for product_YYY

warehouse name  | picking place | stock place
--- | --- | ---
warehouse_0 | 0X12 |  
warehouse_1 | 1H27 |  

I use extrafield (product extrafield) for picking place and stock place (in a high rack, big bag, palette....).
When I move product from stock place to picking place there is no stock movement (they stay in the same warehouse).

**Comment by ptibogxiv** [comment]
@dolibarr95 i will think about it for more compliant et usefull for most of dolibarr's users and standard in industry

**Comment by dolibarr95** [comment]
tks !!

**Comment by eldy** [comment]
In dolibarr a "warehouse" is already an "emplacement". The user is free to define some places inside a warehouse (because a warehouse can be inside another one).
Introducing 2 similar fields for same goal may lead to big side effect in a lot of existing feature.
Did you try to use sub-warehouses (a warehouse called "place A" into warehouse "Building B" ?
N-levels of warehouse is designed for this. So you can define on product that its default warehouse is Place A, it means "Buidling B -> Place A" because place A is a sub-emplacement of Building B.

**Comment by ptibogxiv** [comment]
> Did you try to use sub-warehouses (a warehouse called "place A" into warehouse "Building B" ?
> N-levels of warehouse is designed for this. So you can define on product that its default warehouse is Place A, it means "Buidling B -> Place A" because place A is a sub-emplacement of Building B.

The issue with this, it's that the master warehouse don't report stock or value for all product in it and sub warehouse.

With big customer or supplier order, it's make no cense to select many warehouse (1 for each product, how recognise it in select list ?) and not globla same as picking warehouse.

-> is it make cense for you to add new not required value in stock transfert "emplacement" instead of this PR ? 

Purpose of this, more easy for picking and less click (i work with big company , big growth, with very big order) and keep powerfull data with stock quantity and value for management and inssurance

**Comment by eldy** [comment]
"The issue with this, it's that the master warehouse don't report stock or value for all product in it and sub warehouse."

=> We should not. We can recalculate dynamically stock for parent if we need to know stock of parent warehouse based on its sub warehouses. This is a feature enahncement we can do.

"-> is it make sense for you to add new not required value in stock transfert "emplacement" instead of this PR ?"

=> I don't understand what you mean with this alternative solution. Can you provide an example or describe it differently ?

**Comment by cfoellmann** [comment]
@ptibogxiv we need/want the functionality you are proposing here.
Can you come over to the Dolibarr Slack https://test-slackin001.herokuapp.com/ so we can talk about it more informal?

**Comment by StephaneLesage** [comment]
> "The issue with this, it's that the master warehouse don't report stock or value for all product in it and sub warehouse."
> => We should not. We can recalculate stock for parent if we need to know stock of parent warehouse.

@eldy Yes please do this #14496

**Pull request closed without merging**
