### PR TITLE
Use the parent address if in invoice contact

### PR DESCRIPTION
**Pull request by manact**
Same apply to crabe

### CODE REVIEW

**Comment by eldy** [comment]
Why using parent address if company has a mother company ?
This may be a need in some case but should be rare. Also why "only" when there is specific contact defined, whatever are this contact ?

**Comment by manact** [comment]
Because, here, I notice that the mother company I placed for one customer is set as parent in the societe table. So, in the invoice form, if I set the mother company as billing's contact it sounds to me that, on the invoice pdf, it must not only mention the name but also the full address and VAT of the billing's contact I've choosen. Am I totally wrong?

**Comment by manact** [comment]
Sure "Why only for a specific contact". Whatever the contact is choosen, it should apply to receive the complete address and VAT.

**Comment by BebZ** [comment]
You're not wrong, but it modifies deeply the way invoices are created and it may need an agreement from the community... or an option to define BILL_ALWAYS_TO_PARENT

From my point of view, i have customers willing to receive invoices addressed to parent company, and customers wanting to receive it addressed to "child" subsidiaries. 

There are 2 use cases, and the best scenario is to display on PDF, where it was delivered.
More simply : 
As most of softwares do, displays 3 zones : 
1 for our company
1 for the company delivered (suivi commande/order, or suivi livraison/shipment)
1 for the company invoiced (invoice contact)

Does it sound good ?

**Comment by manact** [comment]
You are right. The problem now (with my PR) is that the parent has no invoices when in their "Client/Customer" tab.
The parent doesn't appear in the invoice list and so on...
So, like you submitted, there should be a place to choose the invoice recipient (like you explain).
The invoice should be shown in the parent and in the child lists of invoices.
The invoice list should only show the parent or accordingly with the choice made before.
Non?

**Comment by BebZ** [comment]
image

For some situations, we use the "switch" of third on the invoice, and we invoice to "child companies" 
it's true that the invoice generated with the parent company is not linked in the "child" list of invoices...
but it's anyway a good tweak to generate propal and ordered labelled to parent or child, 
and invoice labelled to child (the only problem having child with no invoice linked...)

Anyway our goal in this scenario is to keep global track of "parent" company orders and invoices, 
and to label it with child companies names. 

Hope you understand...

**Comment by eldy** [comment]
Thanks for screenshot. Now I understood what you mean. But there is a big mistake.
If on the invoice, what appear is the name of parent company, then invoice must be created on parent company.
And if you really want to keep invoice on thirdparty "Centre De" and see name of company of invoice contact, so "SCM O", you can set option 
MAIN_USE_COMPANY_NAME_OF_CONTACT to 1
with no need to patch

**Pull request closed without merging**
