### PR TITLE
Update to TakePOS 8

### PR DESCRIPTION
**Pull request by andreubisquerra**
Update to TakePOS 8 with Odoo theme

### CODE REVIEW

**Comment by eldy** [comment]
Using javascript code coming from Odoo can't be introduced into Dolibarr for 2 reason:

- First, you must know that Odoo is not OpenSource. Of course, the enterpise version is fully "proprietary licence" version. But even the version that is annouced to be "free", so the version available as the "Community version" on public github is not clear on the licence. Odoo has started to make legal suites against some compmanies that make fork of Odoo. Also, when you submit a PR, you have to sign a document to say that the code you submit become the full property of Odoo and that they can "sublicence" the work you submit, so code introduced is not GPLv3 (sublicence is not possible with this licence), even if they say the oposite. I was an Odoo integrator myself, I won a Trophy as the best Odoo integrator, but i have to sign such a document just to publish some bug fixes, even in the community version). This is one of the reason (and because code is just awful and unreadable) that I completely abandonned to work on Odoo. The company has doubtful policies and rules on project, that seems to be not completely compliant with OpenSource rules. So it is too dangerous to reuse just 1 line of code of Odoo project, even if this code is announced to be LGPL v3 and was found in the public community version.

- Then, "semi-minified" javascript code coming from Odoo is just impossible to debug and modify. Code is just unreadable. And unlinke Odoo, Dolibarr has a policy to follow to be easy (for users but also for developers). Code must be well commented and easy to understand and modify.

So we can provide another POS that is inspired (the interface seems good) but we have to provide a complete rewrite of all embedded code and we have to include code that will be possible to maintain easily (to be Dolibarr compliant) ; It means we must remove all the js part to be replaced with php files (with ajax call and self developed js, like it is in current version of TakePos)

**Comment by andreubisquerra** [comment]
Are you sure? This week I contacted with people from FSF and Odoo Community and say me Odoo Community is 100% open source:
https://directory.fsf.org/wiki/Odoo
And any code released under LGPL v3 is open source, and comply this license is not optional. Other thing is the company internal policy for accept PR...

Minified code is not problem, I can replace with original code.

**Comment by andreubisquerra** [comment]
> Using javascript code coming from Odoo can't be introduced into Dolibarr for 2 reason:
> 
> * First, you must know that Odoo is not OpenSource. Of course, the enterpise version is fully "proprietary licence" version. But even the version that is annouced to be "free", so the version available as the "Community version" on public github is not clear on the licence. Odoo has started to make legal suites against some compmanies that make fork of Odoo. Also, when you submit a PR, you have to sign a document to say that the code you submit become the full property of Odoo and that they can "sublicence" the work you submit, so code introduced is not GPLv3 (sublicence is not possible with this licence), even if they say the oposite. I was an Odoo integrator myself, I won a Trophy as the best Odoo integrator, but i have to sign such a document just to publish some bug fixes, even in the community version). This is one of the reason (and because code is just awful and unreadable) that I completely abandonned to work on Odoo. The company has a doubtful policy and rules about its project, that seems to be not completely compliant with OpenSource rules. So it is too dangerous to reuse just 1 line of code of Odoo project, even if this code is announced to be LGPL v3 and was found in the public community version.
> * Then, "semi-minified" javascript code coming from Odoo is just impossible to debug and modify. Code is just unreadable. And unlinke Odoo, Dolibarr has a policy to follow to be easy (for users but also for developers). Code must be well commented and easy to understand and modify.
> 
> So we can provide another POS that is inspired (the interface seems good) but we have to provide a complete rewrite all embedded code and we have to include code that will be possible to maintain easily (to be Dolibarr compliant) ; It means we must remove all the js part to be replaced with php files (with ajax call and self developed js, like it is in current version of TakePos)

Are you sure? This week I contacted with people from FSF and Odoo Community and say me Odoo Community is 100% open source:
https://directory.fsf.org/wiki/Odoo
And any code released under LGPL v3 is open source, and comply this license is not optional. Other thing is the company internal policy for accept PR...

Minified code is not problem, I can replace with original code.

**Comment by eldy** [comment]
On the paper it is.
On the fact, it is not i'm afraid. Yes, i am sure they ask me to sign a paper that say the code i push become the full property of odoo with a mention saying they are allowed to sublicense and use my code as a prorietary code (and this is not compliant with GPL).
The legal suite odoo did against flectra is also a reality (Flectra really did infringement on Odoo licence for 90% of reported problem, for the rest it is doubtful: The most important problem is that "version entreprise" is just some code coded differently than the community version (class with enhancement). Code is so similar that if you take code from community version, Odoo can say it is code similar to the proprietary version, so this is enough to speak about infringement. This is a VERY CLEVER way to say, "we are opensource, but we have legal weapon to warn you if you reuse our code".
So we can't take any risk on the point 1.
Also the point 2 is important too.

**Comment by andreubisquerra** [comment]
> On the paper it is.
> On the fact, it is not i'm afraid. Yes, i am sure they ask me to sign a paper that say the code i push become the full property of odoo with a mention saying they are allowed to sublicense and use my code as a prorietary code (and this is not commliant with GPL).
> The legal suite odoo did against flectra is also a reality (Flectra really did infringement on Odoo licence for 90% of reported problem, for the rest it is doubtful: The most important problem is that "version entreprise" is just some code coded differently (class with enhancement) that the community version. Code is so similar that if you take code from community version, Odoo can say it is code similar to the proprietary version, so this is enough to speak about infringement. This is a VERY CLEVER way to say, "we are opensource, but we have legal weapon to warn you if you reuse our code".
> So we can't take any risk on the point 1.
> Also the point 2 is important too.

I contacted with Flectra and the copyright infringement about Odoo and Flectra is very complex. But the suit is against enterprise code never released as LGPL. Now is settled the matter.
It really is a topic relevant to Dolibarr, not only for Takepos. Dolibarr have a lot of code released as LGPL: fckeditor, PHPExcel, Restler. And if you are in right any company can license this code as propietary and make legal suites against Dolibarr.

I thing is very important to clarify the law on the issue.

**Comment by eldy** [comment]
Yes, as i said, 90% of the trouble with flectra is legitimate. But if you analyse all the cases, you will see that 10% is a very doubtful use of Odoo practice saying that code is similar to proprietary version (Odoo himslef does not hide this in their own analyse, and of course, because proprietary code is coming from community code, this is not strange).
There is no risk with fckeditor, Restler, PHPExcel because they are LGPL and there is no version with a proprietary licences for all this libraries, so there is no risk. Nobody can say you are near a proprietary code, there is no proprietary variant of code of this libraries.
The problem is that a version of code very similar of community just exists (in fact when proprietary code was released with v8, odoo move some gpl code  as proprietary, of course this should not be possible, but they did, this is another example why the policy of the company is very doubtful and why we can't rely on code coming from this company).
Definitely, the risk is too high to solve the point 1
Also, as i said, the point 2 is the most important.

**Comment by andreubisquerra** [comment]
> Yes, as i said, 90% of the trouble with flectra is legitimate. But if you analyse all the cases, you will see that 10% is a very doubtful use of Odoo practice saying that code is similar to proprietary version (Odoo himslef does not hide this in their own analyse, and of course, because proprietary code is coming from community code, this is not strange).
> There is no risk with fckeditor, Restler, PHPExcel because they are LGPL and there is no version with a proprietary licences for all this libraries, so there is no risk. Nobody can say you are near a proprietary code, there is no proprietary variant of code of this libraries.
> The problem is that a version of code very similar of community just exists (in fact when proprietary code was released with v8, odoo move some gpl code as proprietary, of course this should not be possible, but they did, this is another example why the policy of the company is very doubtful and why we can't rely on code coming from this company).
> Definitely, the risk is too high to solve the point 1
> Also, as i said, the point 2 is the most important.

Sorry for my English, may have been unclear.
In the most important point, the 2, we have the no minified code. The unminified code is in Odoo sources. I can upload this original unminified code instead the minified code. This unminified code is readable and debugable.
In point 1 I wanted to say (is only example): If I get LGPL Dolibarr code and I relicense to propietary code and I say my propietary code is similar to some Dolibarr code ( and do other things that Odoo has done), do you remove this code from Dolibarr?
I watch you close this PR. I continue hard working with Takepos as external module with community legal advice. And if in the future takepos have more users, more stability, more improvements and mostly license clear for you I contact you again.

**Pull request closed without merging**
