### PR TITLE
[ bug #1552 ] Foreign Key problems when doing first install

### PR DESCRIPTION
**Pull request by KreizIT**

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide more info on error of first install. Mysql or pgsql ? We currently should not have pb because departements are loaded after regions. What is error ?

**Comment by KreizIT** [comment]
Was on mysql.
Problem is for french department, rowid values in c_department are not same as fk_region values as for other department. Also, if look at dictionary query's, join are done on code_region not rowid.

Second problem, if you don't use the SET option, you can't insert AI of 0. without the "SET" inserting 0 for AI mean automatic value, not the 0 value.

**Comment by eldy** [comment]
I see.
I made a better fix. Tell me if you see something wrong.

**Comment by KreizIT** [comment]
It's ok

**Pull request closed without merging**
