### PR TITLE
NEW: Add triggers on import success

### PR DESCRIPTION
**Pull request by noec764**
Adding a trigger at the end of import process can be useful

### CODE REVIEW

**Comment by hregis** [comment]
@noec764 @eldy triggers or hooks here ?

**Comment by noec764** [comment]
@hregis If a custom process needs to be run after an import (e.g. linking one object to another after it has been created, as could be done with a standard creation trigger), there is currently no way to run it.

**Comment by eldy** [comment]
trigger is reserved for CRUD BUSINESS event.
See https://wiki.dolibarr.org/index.php?title=Triggers
and https://wiki.dolibarr.org/index.php?title=Hooks_system
should use a hook here

**Comment by noec764** [comment]
@eldy @hregis I've replaced my triggers with hooks in the import page, although I'm not sure why inserting items into the database isn't a CRUD event.

**Pull request closed without merging**
