### PR TITLE
FIX: allow user creation in choosen entity

### PR DESCRIPTION
**Pull request by altairis-tof**
it was impossible to create a user with an existing login in other entity from the main entity (multicompany related)

### CODE REVIEW

**Comment by hregis** [comment]
par défaut chaque entité doit être autonome et le fait d'avoir mis la visualisation et la création de tous les  users sur l'entité principale lorsqu'on est un superadmin porte à confusion et crée des problèmes sur certains modules (externe et interne) ! seul le mode transversal doit permettre de faire ça...

**Comment by simnandez** [comment]
@hregis please  write in english your comments

**Comment by eldy** [comment]
If we are logged on entity X, when we want to see user, we want to see user of entity X (because we are login on entity X, even if user is from entity alpha). So I don't understand this change.
Please first write specification of what multientity module must do to have an uniform implementation before submit change.
The following wiki page can be used for that, into section "development":
https://wiki.dolibarr.org/index.php/Module_MultiCompany#Development
What we need are business rule that we want to see when using multicompany feature according to different options/situation.

**Comment by hregis** [comment]
yes, it's in the pipes ;-)

**Comment by altairis-tof** [comment]
the bug i've fixed for one of my customer is simply to be able to manage users and create users with same login on different entities. i thought it was a bug for two reasons : 1) how to do it without the fix ? 2) there is a $this->entity setting just above and i thought it was not useless...

**Comment by eldy** [comment]
how to do it without the fix ?
=> just login on entity with an admin user. So $conf->entity is set to entity you are logged on. Create login.
What was value for $conf->entity for you ?
Did you use an admin of entity X or the superadmin ?

**Comment by eldy** [comment]
Not sure, but i think this request is no more required.
Check should be done with last version of multicompany that was rewrote recently for 6.0

**Pull request closed without merging**
