### PR TITLE
NEW|Add export features and modify the bank transactions pages display

### PR DESCRIPTION
**Pull request by NeilOrley**
- Add an export button to create a CSV file with the complete transaction list to pages compta/bank/account.php and compta/bank/search.php
  - CSV separator can be configured in the bank module configuration menu
-  Change the bank transactions page display (compta/bank/account.php) :
  - replace : put transaction type and and transaction number in the same column
  - add : link to invoices after the transaction description
  - replace : replace the navigation controls for pagination
  - add : translations fr_FR and en_US
- Change the bank transactions page search display (compta/bank/search.php) :
  - add : column invoices

### CODE REVIEW

**Comment by eldy** [comment]
Hi NeilOrley.
It seems you are using a syntax formatter in your IDE making a lot of change in the code that is not required by your PR. Also it seems, other patch are include (like adding vat on report). It is easier for me to have one feature at time, so it is easier to discuss and/or validate. This make me not possible to validate your PR

**Comment by NeilOrley** [comment]
Hi Eldy.
I use a "dolibarr style" syntax formatter provided by @atm-florian . I like the style of it and didn't realize it would bother you (I'm sorry for that).
I thought that adding an export feature + modifying the display of a single module (bank module) could be merged.. 
I'll keep it in mind and split features in small part for the next time.
However, to merge these features would you like me to create : 
 1 PR with "export button" + "CSV separator in admin menu"
 1 PR with "Change the bank transactions page display"
 1 PR with "Change the bank transactions page search display"
Let me know

**Comment by eldy** [comment]
If you are using eclipse, recommandation to setup syntax formatting is here: https://wiki.dolibarr.org/index.php/Environment_and_development_tools#Install_Eclipse

Yes, if you can resubmit your pr in several parts as suggested, i can't promise i will validate but it increase chances and at i least i would be able to analyze it.

**Comment by eldy** [comment]
Close due to too many conflict. The page was seriously modified and enhanced since this first PR and some of the feature were already added by other developers, so i prefer to close this PR.

**Pull request closed without merging**
