### PR TITLE
Close #15307 New Widget : Encours dépassé 

### LINKED ISSUE #15307: New widget : Encours dépassé
# Feature Request

Avoir un widget sur la page d'accueil qui gère les dépassements d'encours de tous les tiers et qui liste les tiers dont l'encours est dépassé
## Use case
Contrôler a l'arrivée d'une nouvelle commande si le tiers a dépassé l'encours afin de lui dire de régulariser son encours afin de valider la nouvelle commande

## Suggested steps
Des emails paramétrables pourraient être envoyé au moment d'un dépassement d'encours
premier mail : gentil
deuxième : moins gentil
troisième mail: mail de dernière relance un peu sec

### PR DESCRIPTION
**Pull request by Hystepik**
New widget Maximum Outstanding reached

### CODE REVIEW

**Comment by eldy** [comment]
There is one problem in algorithm:
You take first 5 companies. Then you check if outstanding limit is reached. But imaging it is for the last one and not for the 5 first one. In your case, the widget will be empty.
It is very difficult to filter company on outstanding limit because this is not stored yet. It is dynamically calculated and it is a complex calculation. This is what i suggest to have a fix:
- In the select of company, add a filter on outstanding_limit > 0 (so only companies with a limit defined will be returned so we won't make the outstanding calculation for all of them. If not limit is defined, we don't mind if customer is over). Also add a condition to check there is at least 1 open invoice in the selection request (so this will also reduced the number of companies returned by first select).  " AND rowid IN (SELECT fk_soc from ".MAIN_DB_PREFIX."facture as f where f.status = 1 and f.fk_soc = s.rowid)"   (you must add an alias on table "llx_societe as s")

Note: It is a good job for a first try. Also in your PR, title must be Close #idofticket (you can add text after or befor but not inside close and idofticket or you will break to automatic closing done by github when a PR is merged)

**Comment by Hystepik** [comment]
I admit that I don't know what to do now. I need to recommit with your changes?

**Comment by eldy** [comment]
I just pushed a minor fix on your PR to solve a syntax error of the Continuous integration. 
Nothing to do on your side. Just wait it is merged.

**Comment by StephaneLesage** [comment]
Hi, interesting, but I didn't see it.
Does it appear only if not empty ?
Is it a widget on homepage ? a box on the company's page ? Both ?
Can send a screen capture ?

**Comment by Hystepik** [comment]
Hello it's a widget on the homepage, to see it in the widget list you need to make a migration.
Capture d’écran du 2020-12-03 09-05-02
Then you can see this in the widgets

**Pull request merged**
