### PR TITLE
if FAC_FORCE_DATE_VALIDATION can't change the billing date

### PR DESCRIPTION
**Pull request by defrance**

### CODE REVIEW

**Comment by marcosgdf** [comment]
:+1:

**Comment by eldy** [comment]
Why removing edit capability when option FAC_FORCE_DATE_VALIDATION is on ?

**Comment by defrance** [comment]
If you want that date validation and the date of bill is the same, you don't want that some people of your team have the possibility to modify it, 
In fact you not really remove the feature, you can temporay disable the option on bill setting module to have the feature again. Like this only, advanced user can change the date of a bill, with maybe somes major impact of accounting...

**Comment by marcosgdf** [comment]
Agree with @defrance. In fact I don't think the date of an invoice should never be edited once a reference is assigned to it since the reference is related to the date

**Comment by eldy** [comment]
I am not sure users using option FAC_FORCE_DATE_VALIDATION use it to lock date of invoice. I think they use it to have a default date but nevet mind,, this option is a stupid option. Date of an invoice should never be the date when user enter it into its system but when it was really decided with customer.
Because this option should never be set in real life, never mind what it does, i validate the pr.

**Comment by defrance** [comment]
@eldy when your alone on your socity i agree that this option is a nonsence, but with a team they become a really need, particulary for some accountng rules...
Thank for the pr

**Pull request merged**
