### PR TITLE
New : Add new status Shipped in expedition

### PR DESCRIPTION
**Pull request by dolibarr95**
Hi !
Add status shipped see #8838 
I will try to do step by step...

### CODE REVIEW

**Comment by wdammak** [comment]
@eldy I think the addition of other delivery status is rewarding for the shipping module.
However, in future versions, maybe I should create a _status table and group the statuses of all the modules in this table and allow the admin to Add/Edit/del these statuses.

Otherwise, in the current state of things, you can also make this change through the dictionary vars?

**Comment by dolibarr95** [comment]
Hi !
The status table is a very good idea!!!!

**Comment by eldy** [comment]
To analyze also with #9660

**Comment by eldy** [comment]
There is several PR to enhance this and it is not clear what will be the behaviour after (except that all of them suggest a different way of working). So to help to choose which one to retain, i updated wiki doc to describe current worklow:
https://wiki.dolibarr.org/index.php/Module_Shipments#Usage

Can you cut and paste this workflow text graph and update it to describe what will be workflow after the change (keeping the X and the number of status in parenthesis)

**Comment by eldy** [comment]
I think we should enhance the process with something like that:
Draft ---X---> Validated ---> Closed (X = stock change, Can edit qty and lot in Draft step)
must become
Draft ----> Validated ---X---> Shipped (X = stock change, Can edit qty and lot in status Draft + Validated)

**Comment by eldy** [comment]
Duplicate of #8953

**Pull request closed without merging**
