### PR TITLE
Update propal.php

### PR DESCRIPTION
**Pull request by defrance**
problems with milestone module (and probably some other modules) who use it's own <form></form> in additionnal template and goes wrong with this setting

### CODE REVIEW

**Comment by defrance** [comment]
they are probably the same problems on order and bills

**Comment by defrance** [comment]
BAD NEWS ; More informations about this problems :
the use of only one form for the addline generate a bug on the extrafields on line because the extrafield option name are the same on the template (maybe some other bug who have not detected)
I think It's a major bug on 3.5.0beta version, we need to think of a 
the good and proper way seems to create 5 tables and 5 forms for the propal, order and bills main page
1 form/table for the printobjectlines
1 form/table for the formAddObjectLine
1 form/table for the formAddFreeProduct
1 form/table for formAddPredefinedProduct
and finaly 1 form/table for the hook (allready done on the milestone)
propose that the form/table was written on template

**Comment by eldy** [comment]
Putting a form into a table element is just not allowed by W3C.
This just means problem is into "milestone" module not compatible with 3.5 but not a problem into dolibarr itself. Version 3.5 seems ok.

Note that form for free preoduct and predefined product wil me merged probably into 3.6 into one area.

**Comment by defrance** [comment]
Le problème n'est pas QUE sur milestone (je l'ai détecté en testant avec mais c'est général), l'utilisation d'un formulaire unique n'est pas compatible avec des champs de saisie ayant un nom identique (cas de saisies d'extrafields sur les lignes d'éléments)

The problem is not ONLY on milestone (I detected by testing with but general), the use of a single form is not compatible with the input fields with the same name (case with extrafields in the element-line)

**Comment by eldy** [comment]
A form is not compatible with fields that has same name -> you're right.
But you should not have 2 fields with same name into this form. If we have this, it just means there is a bug in the module or in dolibarr. And you are right, there is a bug with the feature extrafields on detailed lines. So because this is a new feature not yet released, i disabled it with test ($conf->global->FEATURES_LEVEL >= 2) meanings this is still a dev feature. 
The feature should work when the 2 forms (predefined product and free product) will be merged into 1 (initially planned for 3.5, a first step was done by normalizing/mutualizing all fields and code but the  second step and last step will be for 3.6)

**Comment by defrance** [comment]
I understand you point of view BUT i think it's not a good solution to breaek 2 majors features to preserve one form 
so i push a new solution to correct this problem as descripted on my 3e comment

**Comment by eldy** [comment]
This does not break any features. This feature just never exists yet (not
available in 3.4).
Feature will be validated and included into a stable version only when it
will be stable. I will see your new fix.

2014-01-30 BENKE Charles notifications@github.com:

> I understand you point of view BUT i think it's not a good solution to
> breaek 2 majors features to preserve one form
> so i push a new solution to correct this problem as descripted on my 3e
> comment
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Dolibarr/dolibarr/pull/1395#issuecomment-33651215
> .

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/astats_project

**Comment by BebZ** [comment]
When do you speak about broken Extrafields
On product's lines it is quite embarassing if it can't work as FHenry has worked a lot to implement it on almost all screens and his code changes have been accepted and merged successfully, no ?

What makes it buggy : 
the use of only one form for the addline

> but there are still 2 forms to "addline" in 3.5 (free and predefined product), no ?

Then, it should work when the 2 forms (predefined product and free product) will be merged

when ? 3.6 in some months ? or sooner with an intermediate patch ?

and what if it doesn't work ? As you said it is : 
NOT compatible with the input fields with the same name (case with extrafields in the element-line)

But input fields in 3.6 will keep the same name, no ? 
or will we have (joke) an extrafield name per product ?

**Comment by eldy** [comment]
Having code accepted into experimental version does not mean code is
enabled for stable release.
I can't tell when it will works. Best answer i can do, is "when someone
will submit a bug fix that solve problems in a good manner".

2014-02-07 BebZ notifications@github.com:

> When do you speak about broken Extrafields
> On product's lines it is quite embarassing if it can't work as FHenry has
> worked a lot to implement it on almost all screens and his code changes
> have been accepted and merged successfully, no ?
> 
> What makes it buggy :
> the use of only one form for the addline
> 
> but there are still 2 forms to "addline" in 3.5 (free and predefined
> product), no ?
> 
> Then, it should work when the 2 forms (predefined product and free
> product) will be merged
> 
> when ? 3.6 in some months ? or sooner with an intermediate patch ?
> 
> and what if it doesn't work ? As you said it is :
> NOT compatible with the input fields with the same name (case with
> extrafields in the element-line)
> 
> But input fields in 3.6 will keep the same name, no ?
> or will we have (joke) an extrafield name per product ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/Dolibarr/dolibarr/pull/1395#issuecomment-34473829
> .

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/astats_project

**Pull request closed without merging**
