### PR TITLE
FIX #19760 Uniformize labels

### LINKED ISSUE #19760: 14.0.3 - Exception 'Data too long' - Add an entry in the dictionnary (Note de frais - Types de lignes de notes de frais)
# Bug
When adding a new entry on the dictionnary "Note de frais - Types de lignes de notes de frais" an exception occurs

## Environment
- **Version**: 14.0.3
- **OS**: Ubuntu
- **Web server**: Apache2
- **PHP**: 8.0
- **Database**: MySQL 7
- **URL(s)**: https://XXXX/htdocs/admin/dict.php?id=17

## Expected and actual behavior
The restriction on the lenght should be :
- Predicted by a max size of the input
- Raise a 'normal' error after submitting the form

## Steps to reproduce the behavior

1. Open dictionnary : https://XXX/htdocs/admin/dict.php?mainmenu=home
2. Click on "Note de frais - Types de lignes de notes de frais" normally https://XXXX/htdocs/admin/dict.php?id=17
3. Add a new line with libélé 'Hosting (Domaine et hébergement)' -> exception.

## Exception 
dolibarr a détecté une erreur technique.
Voici les informations qui pourront aider au diagnostic (Vous pouvez fixer l'option $dolibarr_main_prod sur '1' pour supprimer quelques notifications):
Date: 20220107083508
Dolibarr: 14.0.3 - https://www.dolibarr.org
Niveau de fonctionnalités: 0
PHP: 8.0.14
Serveur: Apache
OS: Linux XXX 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0

Url sollicitée: /erp/htdocs/admin/dict.php?id=17
Referer: https://XXXX/erp/htdocs/admin/dict.php?sortfield=code&sortorder=&rowid=8&code=EX_TOL&&id=17&action=activate&token=5cce447e9dafdd422d3528fb6334a24c&page_y=544
Gestionnaire de menu: eldy_menu.php

Modules/Applications: syslog, user, categorie, adherent, export, propal, mylist, contrat, comptabilite, notification, mailing, emailcollector, projet, product, banque, cron, commande, ecm, expensereport, facture, fournisseur, salaries, service, societe, expedition, import
Type gestionnaire de base de données: mysqli
Requête dernier accès en base en erreur: INSERT INTO llx_c_type_fees (id,code,label,accountancy_code,active) VALUES(26,'EX_HOST','Hosting (Domaine et hébergement)',null,1)
Code retour dernier accès en base en erreur: DB_ERROR_1406
Information sur le dernier accès en base en erreur: Data too long for column 'label' at row 1

## Priority
Minor

### PR DESCRIPTION
**Pull request by simnandez**
This is for the future v16

### CODE REVIEW

**Comment by atm-maxime** [comment]
Great! Next step is to rename all "libellé" into "label" 😉

**Comment by simnandez** [comment]
It is not finished yet. We have to control the maxlength from the code (next step), then rename all "libelle" into "label"

**Comment by atm-maxime** [comment]
You could put your PR in draft ?

**Comment by simnandez** [comment]
I think I should cancel this and make a new one as draft ... for now I change the label to this one since it has the postponed tag.

**Comment by eldy** [comment]
@simnandez Is this PR of for merging ?

**Comment by simnandez** [comment]
@eldy Yes, it is ready for merging.

**Pull request merged**
