### PR TITLE
NEW: tables for a new module, supplier contract (same a contrat but for supplier)

### PR DESCRIPTION
**Pull request by kkhelifa-opendsi**
Tables for a new module, supplier contract (same a contrat but for supplier)

I renamed the fields in french to english and remove obsolete fields
I plan to used template for the product line for customer contract et supplier contract same as template for proposal, orders, invoices but specific for contract.

Is it ok ?

### CODE REVIEW

**Comment by eldy** [comment]
Currently, the module contract was designed to work on both side for customer and supplier.
Can we  support this with just a flag 'Customer / Supplier' on existing contract ?

**Comment by kkhelifa-opendsi** [comment]
ok

**Comment by kkhelifa-opendsi** [comment]
In Dolibarr, modules are now split between customer and supplier.
This makes it possible to have different sets of document templates, separate additional fields, separate reference, add lines specific to purchases and sales, etc...
Now this can be done in a single module, but not in the same way as other modules where the customer and supplier parts have been separated.

**Comment by philippe-opendsi** [comment]
we need to start developing. @eldy Are you sure we're starting with a single module ?

**Comment by eldy** [comment]
> we need to start developing. @eldy Are you sure we're starting with a single module ?

No, not sure. There is pro and cons.

So i I procrastinated by notice you the fact that we can already do it in a simple manner. I would just like to be sure that before starting a full module you were aware that we can already manage supplier contract in a simple way. And if this is enough for short time, may be priority for this enhancement is no more a priority and we can merge other PR before...

**Comment by pscoffoni-opendsi** [comment]
@eldy Concerning our customer's request, the module as it stands doesn't meet his requirements. He already uses the module for the customer part, and would like to be able to clearly differentiate between the two types of contract with additional fields specific to customers and suppliers. The same applies to document templates.
Last but not least, the lines need to retrieve purchase prices for products/services, rather than sales prices as at present.
That's why we're moving towards a complete, separate module.
If you think this is premature, we can do it as an external module and push it later into the core.

**Comment by pscoffoni-opendsi** [comment]
This will be an external module.

**Pull request closed without merging**
