### PR TITLE
The .htaccess is already placed in documents folder, this is actually du...

### PR DESCRIPTION
**Pull request by marcosgdf**
...plicating code

### CODE REVIEW

**Comment by eldy** [comment]
Having .htaccess into documents may depends on distribution and packaging. Having information to remind what to do when it is not the case is still usefull.

**Comment by marcosgdf** [comment]
Does Dolibarr distribute packages without .htaccess file?

**Comment by eldy** [comment]
Yes, dolibarr project does not control how are done package for linux distribution or also package for VM solutions. And with such packages the documents directory creation is not done (often) by dolibarr installer but by distribution installer.

**Comment by marcosgdf** [comment]
Weird.

**Comment by rdoursenaud** [comment]
This should be added to the packagers documentation then…

**Pull request closed without merging**
