### PR TITLE
work on accounting

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by eldy** [comment]
Can you push PR on develop ?

**Comment by aspangaro** [comment]
@eldy This PR is already on the develop branch, it's more a bugfix, can you validate for all users who use the accountancy module ?

**Comment by simnandez** [comment]
In 3.8 the accountancy is experimental, but it's nice update it, so users can test it

**Comment by aspangaro** [comment]
Thanks @simnandez . We have more users day after day.

**Pull request merged**
