### PR TITLE
Fix missing accounting lib on product card

### PR DESCRIPTION
**Pull request by atm-maxime**

### CODE REVIEW

**Comment by aspangaro** [comment]
Accounting lib already present in line 54 : 
if (! empty($conf->accounting->enabled)) require_once DOL_DOCUMENT_ROOT.'/core/lib/accounting.lib.php';

refer to this PR : #5041

**Comment by atm-maxime** [comment]
Thanks @aspangaro for the info, but unfortunately, even if accountancy is not enabled, there's a function called on accountacncy code disaply that is part of accountancy module. Here is the current error message on product card :

Fatal error: Call to undefined function length_accountg() in /var/www/dolibarr/htdocs/product/card.php on line 1485

**Comment by aspangaro** [comment]
Thanks @atm-maxime 

Finally, it's a problem when the module accounting is not used. 
Please close your PR, I will propose a PR to rewrite the line 1485.

**Comment by aspangaro** [comment]
I propose this PR instead #5076

**Comment by atm-maxime** [comment]
Fixed by @aspangaro in #5076

**Pull request closed without merging**
