### PR TITLE
NEW - Right for stats orders

### PR DESCRIPTION
**Pull request by BB2A-Anthony**
# NEW|New [*Right for stats orders*]
[*Long description*]

### CODE REVIEW

**Comment by eldy** [comment]
Can you merge conflicts ?

**Comment by BB2A-Anthony** [comment]
> Can you merge conflicts ?

@eldy it's done

**Comment by BB2A-Anthony** [comment]
@eldy Up for 18 please

**Comment by eldy** [comment]
Sorry, still conflict with develop branch

**Comment by BB2A-Anthony** [comment]
> Sorry, still conflict with develop branch 

@eldy it's done

**Pull request merged**
