### PR TITLE
Patch 14 - Invoice situation Margin filter

### PR DESCRIPTION
**Pull request by mapiolca**
Only final situation invoices are considered to calculate margin and only the product with buying price not null.

### CODE REVIEW

**Comment by eldy** [comment]
@atm-john Are you ok with this :  Only final situation should be included to calculate margin ?
When you use situationinvoice for 100 euros do you have
INV 1 = 40, INV2 = 40, INV3final = 20
or
INV1 = 40, INV2 = 40, INV3final = 100  ?

**Comment by mapiolca** [comment]
The problem is the made of calculate the margin. Dolibarr calculate margin like this : 
(%progress * Total HT Sell)/ (Buying Price * Qty) = %margin.
So when you have a situation invoice, your margin is systemically negative...

**Comment by john-botella** [comment]
Hi, I comme back from holidays.

I don't thing include only the final situation to calculate margin is a good solution (credit notes can change situation invoices during cycle)
We need to know margin on all situation invoices but that right, situation invoices are specials.

so we must know both 100% progress margin and current margin
but for current margin it's not easy to answer... 

The current margin depend of progress and cases : 

For services if your progress is 30% so your real margin could be 30% too because it's easy to imagine 30% of a task
But for product it can't be the same ex : take one product with one in quantity,  the product need to be buy at supplier before selling so if progress is less than 100 %  margin is negative.
Now same exemple but taking one product with 10 in quantity. We can imagine a 30% progress like 3 finished products. so margin can be understand like services .



I will brainstorm with my team for view point because I think I something miss

**Comment by mapiolca** [comment]
> But for product it can't be the same ex : take one product with one in quantity, the product need to be buy at supplier before selling so if progress is less than 100 % margin is negative.

Yes, and you can't sell 30% to 1 product.... 

> Now same exemple but taking one product with 10 in quantity. We can imagine a 30% progress like 3 finished products. so margin can be understand like services .

I'm OK.
> I will brainstorm with my team for view point because I think I something miss

So I think we need to change calculation of margin from this :
(%progress * Total HT Sell)/ (Buying Price HT* Qty) = %margin.

to this :
(%progress * Unit Price HT Sell* Qty )/ (%progress * Buying Price HT* Qty) = %margin.
or this :
(%progress * Total HT Sell )/ (%progress * Buying Price HT * Qty) = %margin.

**Comment by mapiolca** [comment]
Hi @eldy , What's new here ?

**Comment by mapiolca** [comment]
I do an other version of the correction, I just integered  the product's `situation_percent` in calculation. See Fix  #12740

**Comment by eldy** [comment]
Replaced by #12740

**Pull request closed without merging**
