### PR TITLE
catch $cancel action executed by submit-button cancel

### PR DESCRIPTION
**Pull request by cfoellmann**
when the "Cancel" button is submitted on a form we need to clear all POST and redirect to the appropriate location.
This catches "all" cancel actions

### CODE REVIEW

**Comment by cfoellmann** [comment]
@eldy this is a very hard requirement to fix all the cancel buttons refreshed by the button function in my other, already merged, PR

**Comment by eldy** [comment]
If you look into the code of modulebuilder, you will find a "generic". This is the way:

If the page card.php has the 
	include DOL_DOCUMENT_ROOT.'/core/actions_addupdatedelete.inc.php'


Then you can add this (in a perfect world):

```
if (empty($reshook)) {

	$backurlforlist = DOL_URL_ROOT.'/societe/list.php';

	if (empty($backtopage) || ($cancel && empty($id))) {
		if (empty($backtopage) || ($cancel && strpos($backtopage, '__ID__'))) {
			if (empty($id) && (($action != 'add' && $action != 'create') || $cancel)) {
				$backtopage = $backurlforlist;
			} else {
				$backtopage = DOL_URL_ROOT.'/societe/card.php?id='.((!empty($id) && $id > 0) ? $id : '__ID__');
			}
		}
	}

...
```

If the page card.php has NOT the 
	include DOL_DOCUMENT_ROOT.'/core/actions_addupdatedelete.inc.php'

then it should be in a perfect world:

```

if (empty($reshook)) {

	$backurlforlist = DOL_URL_ROOT.'/societe/list.php';

	if (empty($backtopage) || ($cancel && empty($id))) {
		if (empty($backtopage) || ($cancel && strpos($backtopage, '__ID__'))) {
			if (empty($id) && (($action != 'add' && $action != 'create') || $cancel)) {
				$backtopage = $backurlforlist;
			} else {
				$backtopage = DOL_URL_ROOT.'/societe/card.php?id='.((!empty($id) && $id > 0) ? $id : '__ID__');
			}
		}
	}

	if ($cancel) {
		if (!empty($backtopageforcancel)) {
			header("Location: ".$backtopageforcancel);
			exit;
		} elseif (!empty($backtopage)) {
			header("Location: ".$backtopage);
			exit;
		}
		$action = '';
	}
```

**Comment by eldy** [comment]
I saw several code lost into this PR. So i suggest to cancel it wan we will fix any case when we found it instead of a global PR.

**Comment by eldy** [comment]
I have processed most case with the sample of code suggested by the modulebuilder sample. So i close this ticket.

**Pull request closed without merging**
