### PR TITLE
FIX #18627 REST API: Allow users with self read / modify rights to get own info

### LINKED ISSUE #18627: REST API: User with "self" read / modify access right cannot read own info
# Bug
User with "self" read / modify access right cannot read own user information

## Environment
- **Version**: 14.0.x
- **OS**: CentOS 8.4
- **Web server**: Apache httpd 2.4.37
- **PHP**: 7.3.20
- **Database**: 10.3.28
- **URL(s)**: api/index.php/users/info api/index.php/users/<id>

## Expected and actual behavior
When requesting api/index.php/users/info with an user with self modify / read permission, we should be able to read it but we get a 403 forbidden error. 

Same with api/index.php/users/<id> when <id> is the current user id.

### PR DESCRIPTION
**Pull request by lainwir3d**
# Fix #18627
Allows user with self user read / modify rights to query its own information using the REST API.

### CODE REVIEW

**Comment by eldy** [comment]
Can you try to merge with last develop branch and retry to submit your PR ?

**Comment by lainwir3d** [comment]
Yeah no problem. Do I have to close this one and resubmit a new one or I can do this on this one? Sorry first time doing this.

**Comment by eldy** [comment]
You choose.
But the easier way is just to make the pull in your branch lainwir3d:fix_rest_api_fix_self_user_info_read
Fix the conflicts and push. When you make your PR request from github, it should automatically replace your old PR with the new one.

**Comment by lainwir3d** [comment]
Apparently pushing to my linked PR branch is enough to update the PR. I just had to change the target branch to "develop" instead of "14.0". Does it look ok on your side?

**Pull request merged**
