### PR TITLE
jump to create if $action empty

### PR DESCRIPTION
**Pull request by cfoellmann**
@eldy maybe this is an option to tackle the empty $action issue!?

### CODE REVIEW

**Comment by eldy** [comment]
What is the trouble with empty $action ?   action is defined 
- when there is an action to do. If not, it is just a read.
- or to ask a page in a different mode than a simple view, for example to show it in mode create or edit.

**Comment by cfoellmann** [comment]
@eldy problem is if there is NO parameter in the url for a card.php it results in a white page.

**Comment by eldy** [comment]
> @eldy problem is if there is NO parameter in the url for a card.php it results in a white page.

Yes.
According to module builder, a card page return the file if an id=X or ref=Y is provided, return a creation page if action=create is provided and return an empty page if page is called without parameter (should not happen in app context, and we do the less possible if the action=create is not provided).

**Comment by cfoellmann** [comment]
I understand you but a user should never see a whitescreen
How does he know what happened?

**Comment by eldy** [comment]
> I understand you but a user should never see a whitescreen How does he know what happened?

He should never see it. The only case where he will see it if an attempt to hack app by removing parameters or a bug inside app. Am i wrong ?

**Pull request closed without merging**
