### PR TITLE
NEW Can hide eatby, sellby dates with option PRODUCT_DISABLE_SELLBY and PRODUCT_DISABLE_EATBY

### LINKED ISSUE #14200: Deactivate eatby + sellby
# Feature Request
Disable the fields `eatby` and `sellby` for products.

## Use case
We do not use any of these fields and it is always better to hide fields via php and not css or even change core files

## Suggested implementation
Add constants `PRODUCT_DISABLE_EATBY` and `PRODUCT_DISABLE_SELLBY`.
If these are `1` selects for these days are skipped in php

I will start a PR for this.
If anyone could help test for missing occurrences it would be most helpful

### PR DESCRIPTION
**Pull request by cfoellmann**
# Fix #14200 

By defining the globals

`PRODUCT_DISABLE_EATBY`
and/or
`PRODUCT_DISABLE_SELLBY`

the fields will be hidden from the UI

### CODE REVIEW

**Comment by StephaneLesage** [comment]
I suppose many users like us use serial/batch numbers but don't use these dates.
@eldy Please review and commit this useful feature.

**Comment by cfoellmann** [comment]
@StephaneLesage this still a draft because I have not done all the edits. There are still screens showing the dates

**Comment by cfoellmann** [comment]
@StephaneLesage can you please test these changes? I am not sure if I have missed any pages where these fields are displayed

**Comment by StephaneLesage** [comment]
> @StephaneLesage can you please test these changes?

My git skills are are limited to knowing that I must "clone" to get a repository.
So I'm not setup yet to do this.

>I am not sure if I have missed any pages where these fields are displayed

I see you changed 4 files. But when I do `grep -rnw . -e 'EatByDate'`, then I get 16 files:
```
./mrp/mo_movements.php:133:     'pl.eatby'=>array('label'=>$langs->trans("EatByDate"), 'checked'=>0, 'position'=>10, 'enabled'=>(!empty($conf->productbatch->enabled))),
./shippableorder/script/interface.php:87:                                       $detail .= ' - '.$langs->trans("EatByDate").': '.dol_print_date($dbatch->eatby, "day");
./fourn/commande/dispatch.php:579:                                      print '<td class="dispatch_dluo_title">'.$langs->trans("EatByDate").'</td>';
./fourn/commande/dispatch.php:964:                              print '<td class="dispatch_dluo_title">'.$langs->trans("EatByDate").'</td>';
./product/stock/productlot_list.php:93: 't.eatby'=>array('label'=>$langs->trans("EatByDate"), 'checked'=>1),
./product/stock/movement_list.php:109:    'pl.eatby'=>array('label'=>$langs->trans("EatByDate"), 'checked'=>0, 'enabled'=>(!empty($conf->productbatch->enabled))),
./product/stock/productlot_card.php:339:    print $form->editfieldkey($langs->trans('EatByDate'), 'eatby', $object->eatby, $object, $user->rights->stock->creer, 'datepicker');
./product/stock/productlot_card.php:341:    print $form->editfieldval($langs->trans('EatByDate'), 'eatby', $object->eatby, $object, $user->rights->stock->creer, 'datepicker');
./product/stock/index.php:165:          print '<th>'.$langs->trans("EatByDate").'</th>';
./product/stock/movement_card.php:102:  'pl.eatby'=>array('label'=>$langs->trans("EatByDate"), 'checked'=>0, 'position'=>10, 'enabled'=>(!empty($conf->productbatch->enabled))),
./product/stock/class/productlot.class.php:547:            $label .= '<br><b>'.$langs->trans('EatByDate').':</b> '.dol_print_date($this->eatby, 'day');
./product/stock/product.php:839:                print '<td class="center" width="10%">'.$langs->trans("EatByDate").'</td>';
./product/stock/tpl/stockcorrection.tpl.php:104:        print '<td>'.$langs->trans("EatByDate").'</td><td>';
./product/stock/tpl/stocktransfer.tpl.php:114:  print '<td>'.$langs->trans("EatByDate").'</td><td>';
./product/reassortlot.php:308:  print_liste_field_titre("EatByDate", $_SERVER["PHP_SELF"], "pb.eatby", $param, "", '', $sortfield, $sortorder, 'center ');
./reception/card.php:991:                                       print '<td class="left">'.$langs->trans("EatByDate").'</td>';
./reception/card.php:1868:                                                      print $langs->trans('EatByDate').' : ';
./reception/card.php:1923:                                                              $detail .= ' - '.$langs->trans("EatByDate").': '.dol_print_date($lines[$i]->eatby, "day");
./expedition/card.php:1366:                                                                     $detail .= ' - '.$langs->trans("EatByDate").': '.dol_print_date($dbatch->eatby, "day");
./expedition/card.php:2419:                                                                     $detail .= ' - '.$langs->trans("EatByDate").': '.dol_print_date($dbatch->eatby, "day");
./core/modules/modStock.class.php:238:                          'p.tms'=>'DateModification', 'pb.rowid'=>'Id', 'pb.batch'=>'Batch', 'pb.qty'=>'Qty', 'pl.eatby'=>'EatByDate', 'pl.sellby'=>'SellByDate'
./core/lib/sendings.lib.php:393:                                                                $detail.= ' - '.$langs->trans("EatByDate").': '.dol_print_date($dbatch->eatby,"day");

```

**Comment by cfoellmann** [comment]
@StephaneLesage good idea. I wiill check the list and try to get this done today

**Comment by cfoellmann** [comment]
- [x] ./mrp/mo_movements.php:133:     'pl.eatby'=>array('label'=>$langs->trans("EatByDate"), 'checked'=>0, 'position'=>10, 'enabled'=>(!empty($conf->productbatch->enabled))),
- [ ] ./shippableorder/script/interface.php:87:                                       $detail .= ' - '.$langs->trans("EatByDate").': '.dol_print_date($dbatch->eatby, "day");
- [x] ./fourn/commande/dispatch.php:579:                                      print '<td class="dispatch_dluo_title">'.$langs->trans("EatByDate").'</td>';
- [x] ./fourn/commande/dispatch.php:964:                              print '<td class="dispatch_dluo_title">'.$langs->trans("EatByDate").'</td>';
- [x] ./product/stock/productlot_list.php:93: 't.eatby'=>array('label'=>$langs->trans("EatByDate"), 'checked'=>1),
- [x] ./product/stock/movement_list.php:109:    'pl.eatby'=>array('label'=>$langs->trans("EatByDate"), 'checked'=>0, 'enabled'=>(!empty($conf->productbatch->enabled))),
- [x] ./product/stock/productlot_card.php:339:    print $form->editfieldkey($langs->trans('EatByDate'), 'eatby', $object->eatby, $object, $user->rights->stock->creer, 'datepicker');
- [x] ./product/stock/productlot_card.php:341:    print $form->editfieldval($langs->trans('EatByDate'), 'eatby', $object->eatby, $object, $user->rights->stock->creer, 'datepicker');
- [x] ./product/stock/index.php:165:          print '<th>'.$langs->trans("EatByDate").'</th>';
- [ ] ./product/stock/movement_card.php:102:  'pl.eatby'=>array('label'=>$langs->trans("EatByDate"), 'checked'=>0, 'position'=>10, 'enabled'=>(!empty($conf->productbatch->enabled))),
- [ ] ./product/stock/class/productlot.class.php:547:            $label .= '<br><b>'.$langs->trans('EatByDate').':</b> '.dol_print_date($this->eatby, 'day');
- [x] ./product/stock/product.php:839:                print '<td class="center" width="10%">'.$langs->trans("EatByDate").'</td>';
- [x] ./product/stock/tpl/stockcorrection.tpl.php:104:        print '<td>'.$langs->trans("EatByDate").'</td><td>';
- [x] ./product/stock/tpl/stocktransfer.tpl.php:114:  print '<td>'.$langs->trans("EatByDate").'</td><td>';
- [x] ./product/reassortlot.php:308:  print_liste_field_titre("EatByDate", $_SERVER["PHP_SELF"], "pb.eatby", $param, "", '', $sortfield, $sortorder, 'center ');
- [x] ./reception/card.php:991:                                       print '<td class="left">'.$langs->trans("EatByDate").'</td>';
- [x] ./reception/card.php:1868:                                                      print $langs->trans('EatByDate').' : ';
- [x] ./reception/card.php:1923:                                                              $detail .= ' - '.$langs->trans("EatByDate").': '.dol_print_date($lines[$i]->eatby, "day");
- [x] ./expedition/card.php:1366:                                                                     $detail .= ' - '.$langs->trans("EatByDate").': '.dol_print_date($dbatch->eatby, "day");
- [x] ./expedition/card.php:2419:                                                                     $detail .= ' - '.$langs->trans("EatByDate").': '.dol_print_date($dbatch->eatby, "day");
- [ ] ./core/modules/modStock.class.php:238:                          'p.tms'=>'DateModification', 'pb.rowid'=>'Id', 'pb.batch'=>'Batch', 'pb.qty'=>'Qty', 'pl.eatby'=>'EatByDate', 'pl.sellby'=>'SellByDate'
- [ ] ./core/lib/sendings.lib.php:393:                                                                $detail.= ' - '.$langs->trans("EatByDate").': '.dol_print_date($dbatch->eatby,"day");

**Comment by cfoellmann** [comment]
This PR is ready.
I have tested it but there should be at least one more looking this over

**Pull request merged**
