### PR TITLE
Optimized and added triggers for add/del rights user functions

### PR DESCRIPTION
**Pull request by all3kcis**
Optimized :

```
addrights()
before : 2+(2*n) requests
after :  4 requests
```

```
delrights()
before : 2+n requests
after :  3 requests
```

and added triggers

```
before processing : USER_ADDRIGHTS / USER_DELRIGHTS
after processing (for get result) : USER_ADDRIGHTS_AFTER / USER_DELRIGHTS_AFTER
```

### CODE REVIEW

**Comment by marcosgdf** [comment]
What are the new triggers for?

**Comment by all3kcis** [comment]
For me it is for an "audittrail" module but like the others there is no limit.
It is unfortunate that the triggers are not always existent. (Example: warehouse)

**Comment by marcosgdf** [comment]
Yeah but I mean… does it answer an user action? It sounds more like a hook …

**Comment by eldy** [comment]
It's ok for optimizing.
1) However syntax for insert generate not portable sql (we save requests for the delete, but for the insert we still have to make one insert per record).

2) Also can you rename trigger into USER_SETRIGHTS and  USER_REMOVERIGHTS

3) Point 1 and 2 are code change to 2. The third point is a question: Why a trigger _AFTER (such behaviour is not compatible with trigger philosophy. Using a hook here will probably be better, but because, there is no code after that, why adding this ?

**Comment by all3kcis** [comment]
1) I don't understand "not portable" ? (line 410 to 416 ?)
2) Ok
3) First trigger use for processing (before sql DELETE),
The second trigger is just to retrieve with certainty the final result
and allows you to make sure everything went well and that the transaction can't be canceled and been validated.

Example :

Trigger USER_SETRIGHTS triggers two modules (module1 first et module2 second with equal priority)

module1 (priority : high) processing :

```
runTrigger(){ 
    /* processing */
    log('User set rights id:'.$id);
}
```

module2 (priority : high) processing :

```
runTrigger(){ 
    /* processing */
    return -1; // probably an error
}
```

The module1 writes a log that isn't right because addrights() function was interrupted by the module2.

Trigger USER_SETRIGHTS_AFTER is used to get the final result of the function

**Comment by eldy** [comment]
Not portable means not standard sql that will not work on some databases. Line 452.

3) The trigger system already provide solution to decide if the transaction can be canceled or not. Just use a return code in your trigger. If one trigger fails, then all transaction will be canceled.

**Comment by all3kcis** [comment]
Rewrite SQL, Ok
Rename triggers Ok

Travis failed fix by #5017 thx, please retry Travis checks

3) All transaction will be canceled but all transactions will be canceled, but some can have realized irreversible actions (write log, sql transaction on another database, etc), **triggers "after" are essential.**

**Comment by eldy** [comment]
Trigger "after" is not required because if one trigger fails, even the last one, all requests are canceled as if nothing were done at all.
What do you mean with irreversible actions ?

**Comment by all3kcis** [comment]
Which can't be canceled by db->rollback() :
- write log
- sql transaction on another database
- and probably other things

**Comment by eldy** [comment]
Because triggers are executed at end of code, it is recommended to make "non reversible event" with a higher priority code so they are executed only when all db action are done and ok.

**Pull request closed without merging**
