### PR TITLE
supplier invoice fix : correct path determination if origin is project

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by altairis-tof** [comment]
c'est penible que github ne permette pas de créer plusieurs pull requests et mette tout dans le même !
ici les deux commits n'ont rien à voir.

**Comment by hregis** [comment]
c'est pour celà qu'il est recommandé de faire une branche temporaire par modification, ainsi tu peux faire ton pull request sur cette branche, puis tu peux la supprimer dès que c'est ok.

**Comment by altairis-tof** [comment]
cant agree totally with that... one must make a backup before migration; so if migration process fails, he can restore its data.
if we keep all old tables, it's becoming a mess... i have a partner who is writing a  module using llx_compta_compte_generaux !

**Comment by eldy** [comment]
Le 18/12/2012 09:54, Christophe Battarel a écrit :

> cant agree totally with that... one must make a backup before
> migration; so if migration process fails, he can restore its data.
> if we keep all old tables, it's becoming a mess... i have a partner
> who is writing a module using llx_compta_compte_generaux !
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/547#issuecomment-11478270.
> 
> The goal is not to restore data and restart from the beginning but to
> have a migration process that is able to restart where it ends.
> We don't keep old tables indefinetly, because rule is to delete them
> during n+2 migration (where we are sure migration n+1 is finished
> succesfully).

Currently, having a migration process able to start from where it fails,
and that is safe (with no need to restore each time there is a small
problem during migration) is an important feature for end users that we
should not loose.

## 

Eldy (Laurent Destailleur).

EMail: eldy@destailleur.fr
Web: http://www.destailleur.fr

Dolibarr (Project leader): http://www.dolibarr.org
To make a donation for Dolibarr project via Paypal: contact@destailleur.fr
AWStats (Author) : http://awstats.sourceforge.net
To make a donation for AWStats project via Paypal: contact@destailleur.fr
AWBot (Author) : http://awbot.sourceforge.net
CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by altairis-tof** [comment]
ok for the explanations; i agree with you.

**Pull request closed without merging**
