### PR TITLE
Error install when insert database

### PR DESCRIPTION
**Pull request by ndrosis**
DB_ERROR_COLUMN_ALREADY_EXISTS Duplicate column name 'thm'

### CODE REVIEW

**Comment by aspangaro** [comment]
It's two different name : thm and tjm

**Comment by ndrosis** [comment]
The name 'thm' exists in line 59

**Comment by aspangaro** [comment]
Ok sorry don't view the complete file.

**Comment by aspangaro** [comment]
More complete fix by @rdoursenaud into commit #1907

**Comment by ndrosis** [comment]
Yes you're right closes this commit and continue the #1907

**Pull request closed without merging**
