### PR TITLE
NEW module Intracomm report

### PR DESCRIPTION
**Pull request by aspangaro**

### CODE REVIEW

**Comment by eldy** [comment]
@aspangaro Did you still work on this PR ?

**Comment by aspangaro** [comment]
@eldy Yes, I have to resume development soon to finish this module

**Comment by eldy** [comment]
@aspangaro Ticket still has title WIP, it is ok to try a merge ? If yes, can your help me to solve conflict ?

**Comment by eldy** [comment]
Travis report this error :
1) CodingPhpTest::testPHP
Found a forbidden string sequence into core/class/html.form.class.php : name="token" value="'.$_SESSION[..., you must use a newToken() instead of $_SESSION['newtoken'].
Failed asserting that false is true.

**Comment by aspangaro** [comment]
Ping @eldy

**Pull request merged**
