### PR TITLE
[NEW] PDF Add options

### PR DESCRIPTION
**Pull request by BB2A-Anthony**

### CODE REVIEW

**Comment by eldy** [comment]
Sorry, to avoid to have to many tabs with too low options, i moved all tabs with specific options for PDF into one tab called "other" (pdf_other.php) with one section for each module. 
Can you move your option addition into this new file ?

**Comment by BB2A-Anthony** [comment]
> Sorry, to avoid to have to many tabs with too low options, i moved all tabs with specific options for PDF into one tab called "other" (pdf_other.php) with one section for each module.
> Can you move your option addition into this new file ?

@eldy It's done

**Comment by BB2A-Anthony** [comment]
@eldy it's ok for me

**Comment by eldy** [comment]
A lot of options added here are currently hidden because they are not yet ready or stable or simply not a good idea to be supplied for end users. Because there is a lot, i suggest to make a different PR for each option so it is easier to discus case by case what we can do to make the option completely available.

**Comment by bb2a** [comment]
@eldy Done it's ok for me

**Comment by bb2a** [comment]
@eldy conflict resolved

**Comment by BB2A-Anthony** [comment]
Done it's ok for me

@eldy conflict resolved

**Comment by eldy** [comment]
Other PR were introduced to add each option one by one and few of them were already merged so i closed this one.

**Pull request closed without merging**
