### PR TITLE
Add the build/list doc to movement (mode dev)

### PR DESCRIPTION
**Pull request by wdammak**
Please validate the 4 lasts pull requests to fix operate the document generator for warehouse moves.
- I added it in development mode until we agreed on the functionality and the need.
- I added a link to the inventory code to print the list of items in a move.

Thx

Note: Well I admit that the use of two terms mouvement (BDD & rights) / movement (in the scripts) complicated me the task! Make the need work and after you clean up with the terms you prefer!

### CODE REVIEW

**Comment by eldy** [comment]
To be consistent with other feature, i plan to add a page dedicated to show an inventory record (that is a list of 1 to n movements (often 2). Generating document and button to generate them should be on this page.
So i postponed this PR until this page is ready, but if you are ready to introduce it yourself, it is welcome...

**Comment by wdammak** [comment]
What do you think of adding a folder movement in the stock folder to have card.php, list.php and index.php?
otherwise make the movements a sub-module of stock module.

**Comment by eldy** [comment]
Because movement of stock is completely correlated to stock module, there is no need for a sub module.
We can use the prefix syntax to have movement php files.
For example:
movement_list.php
movement_card.php

I have already renamed mouvement.php into movement_list.php
We are missing the movement_card.php where the section to generate document should be.

**Comment by wdammak** [comment]
To advance on this topic, attached a first step.
[movement_card.zip](https://github.com/Dolibarr/dolibarr/files/2707487/movement_card.zip)
We must now edit the movement_list.php to link movement_card.php when we click on the link inventory
`// Inventory code
	        print '<td>'.'<a href="'
								.DOL_URL_ROOT.'/product/stock/movement_card.php'
								.'?id='.$objp->entrepot_id
								.'&amp;search_inventorycode='.$objp->inventorycode
							    .'&amp;search_type_mouvement='.$objp->type_mouvement
						.'">'
							.$objp->inventorycode
						.'</a>'
					.'</td>';`

**Comment by wdammak** [comment]
> 
> 
> To advance on this topic, attached a first step.
> [movement_card.zip](https://github.com/Dolibarr/dolibarr/files/2707487/movement_card.zip)
> We must now edit the movement_list.php to link movement_card.php when we click on the link inventory
> `// Inventory code print '<td>'.'<a href="' .DOL_URL_ROOT.'/product/stock/movement_card.php' .'?id='.$objp->entrepot_id .'&amp;search_inventorycode='.$objp->inventorycode .'&amp;search_type_mouvement='.$objp->type_mouvement .'">' .$objp->inventorycode .'</a>' .'</td>';`

[https://github.com/Dolibarr/dolibarr/pull/10437](url)

**Comment by wdammak** [comment]
done

**Comment by BebZ** [comment]
Did you give up the movement module ? Or is it merged with another commit ?
Or why did you close it ? 
Thanks :p

**Pull request closed without merging**
