### PR TITLE
Link Third party old

### PR DESCRIPTION
**Pull request by BB2A-Anthony**
# New [*Link Third party old*]

Adding a link with a previous owner allows you to have a history while keeping the information of the old contact and history.

### CODE REVIEW

**Comment by dpriskorn** [comment]
Could you explain the usecase for this? Is there a feature request you could link to?

**Comment by BB2A-Anthony** [comment]
> Could you explain the usecase for this? Is there a feature request you could link to?

If company sales another company
If company sales warehouse, office another company

**Comment by eldy** [comment]
The name "old" is not really explicit. What is the goal of the field ?

**Comment by BB2A-Anthony** [comment]
> The name "old" is not really explicit. What is the goal of the field ?

the goal a link for look the history and save the informations. contact old owner if a problème or more informations

**Comment by eldy** [comment]
I see. You mean that when a company is renamed, you create a second record and close old one, and need a link to say, this "new record" is the renaming of "old record company" ?

**Comment by BB2A-Anthony** [comment]
Yes in the idea that's it!

**Comment by eldy** [comment]
This feature does not look to be expected by a lot of users. Also adding such a feature is easy by just adding an extrafield of type "link to object company". Increasing number of fields for a feature that is not enough requested does not worth it. Above all when you can address it with a custom field.

**Pull request closed without merging**
