### PR TITLE
natural search in list pages

### PR DESCRIPTION
**Pull request by csalvador**

### CODE REVIEW

**Comment by eldy** [comment]
I found a 
if (! empty(GETPOST('button_removefilter')))
that is not good practice
empty should not be used on a function (only on a vars)
Can you replace with

if (GETPOST('button_removefilter'))

**Comment by csalvador** [comment]
Fixed

**Comment by eldy** [comment]
Sorry, now it's a conflict...

**Comment by csalvador** [comment]
Just rebased, should be ok now

**Pull request merged**
