### PR TITLE
Update commondocgenerator.class.php

### PR DESCRIPTION
**Pull request by syrus34**
add company_iban and company_bic fields

### CODE REVIEW

**Comment by syrus34** [comment]
Useful for generating odt

**Comment by marcosgdf** [comment]
I think a better apropiate tag would be company_bank_iban

**Comment by syrus34** [comment]
in rib.php, the field is called "iban_prefix" , company_bank_iban_prefix  is a little longer and company_bank_bic then, but sure, why not "company_bank_iban" and "company_bank_bic" ?

**Comment by eldy** [comment]
With version 3.5, a company can have several bank account.
So i suggest to use
company_default_bank_iban
and
company_default_bank_bic

Because we can have other iban and bic tags in future. Also can you push this into develop instead of 3.5 ?

**Comment by eldy** [comment]
Patch added into dev branch

**Pull request closed without merging**
