### PR TITLE
Feature Request: NEW Added product attributes feature

### PR DESCRIPTION
**Pull request by marcosgdf**
Based in Prestashop's product combinations feature it allows to create product attributes and then create combinations of products, with product price and weight variations.

captura de pantalla 2016-07-24 a las 11 57 31
captura de pantalla 2016-07-24 a las 11 57 40
captura de pantalla 2016-07-24 a las 11 57 56
captura de pantalla 2016-07-24 a las 11 58 09
captura de pantalla 2016-07-24 a las 11 58 18

I've assigned a random module number, if you want to assign any other number please change it freely.

### CODE REVIEW

**Comment by defrance** [comment]
Hello Marcos, I have already développed this type of feature (declinaison) on factory free version module

**Comment by BebZ** [comment]
Hello Marcos... Woah, this is SERIOUS feature ;) 
Based on prestashop ? But do you think we can make it Magento-compliant too ? 
I have a dev working on ecommerce Magento Synch, and i will tell you if it's compliant or not, and if it has "hooks" (or triggers) to Web-service it ;)

Hello Defrance, never seen this in Core anyway ;) and in your module it is "sub products you integrate together" 
an "attribute" is a property of a product, like shown and well explained on clear screenshots : blue, is an attribute you can add without modifying the product, (if you have already blue color in stock, but you were not differentiating it).

Last question ; what is or waht is not batch/dluo compliant ?

**Comment by simnandez** [comment]
@marcosgdf please resolve conflicts

**Comment by defrance** [comment]
Hello Seem's left many thing (modarttributes.class.php by example)
Many problem with this feature 
-> we are link to much with this to prestashop and i think it's not a good way, dolibarr must work with other platforms
-> we don't manage the stock and the dispatch (hubz???)
-> we change many thing on main part of (bill order invoice) 

Managing by attribute (or with etrafield) is for me not a good way, particulary for stock management feature who will be more and more complex ...

It is time that before adding features that profoundly changes how dolibarr there was minimal discution between developers in order to measure the impact

**Comment by defrance** [comment]
@bebz, i have no problem to integrate factory free on the core of dolibarr, mylist free in the same time if you want ... oups they have suppress the datatables librairies.... they can't...

**Comment by marcosgdf** [comment]
Well, this feature was already approved before I started developing. Think it as a very standard approach –it can be improved a lot– to manage product attributes, which are useful in most companies. This is not for Prestashop, this is based in Prestashop's approach for supporting product attributes.

They are actually individual products but linked to the parent one, so that stock management is not affected as well as other features. It was really developed with other-modules features "minimum conflict" in mind.

Also I don't think that I am changing anything in the Facture object…

**Comment by defrance** [comment]
Approved by who?
As i know, this feature is present on 2 additionnal products present on dolistore (one by atm, one by me who free)
Why spend time to create another one?

when i speak to change on the facture, i speak of the card.php, as i understand, the feacture add some additionnal fields on the creation of line...

**Comment by eldy** [comment]
It seems philosopy of our module is to add a second level of table under the product.
So we still have one product into database of product, even if there is 2 variant, right ?
If yes, this will generate problem on how to manage stock and moreover "lot".

A better approch would be to manage variant with wizard that help to enter variant, but variant must be stored as dedicated products, so every other features (shipments, stock, lot, import/export) would be compatible. Don't you think so ?

**Comment by BebZ** [comment]
EDIT : out of scope remark

@eldy variant must be stored as dedicated products, so every other features (shipments, stock, lot, import/export) would be compatible. Don't you think so ?
I  agree, every variant should be a unique predefined product/service.
and I think Marcos thought the same way, look carefully, there is a unique ref ;) 
screenshot 2016-11-11 at 16 50 28

@marcosgdf it is the same behaviour on magento : 
you create variant (blue) on a second table, and you assign a variant to a product (shirt), which can make a third product (blue shirt). they even added in magento variants "families" : colors, sizes, etc.. to get less lost when assigning to products.

**Comment by defrance** [comment]
Go back to your warehouse and your boxes and let the big people talk to each other ....
Factory free is proposed to integration on core, and the declinaison feature is present on it.
This module is used by more people than used batch/lot bullshit and work fine

**Comment by BebZ** [comment]
Where is your P.R , kid ?

**Comment by defrance** [comment]
Go back to your warehouse and your boxes and let dev people talk to each other ....

**Comment by philippe-opendsi** [comment]
@BebZ Why a PR ? I think that the integration of Factory has to be first debated by the community to decide if it meet the requirements in term of functionality et code. We can easily test this module before integration. There is an issue for this subject #5824 . Maybe first discussion then code ?

**Comment by BebZ** [comment]
IMHO, no pull request = no willing demonstration, no Continuous Integration tests, no merge into core ;) 
If Factory "free" is proposed into core, it means it is widely used by Dolibarr people who manufactures... see the subjects in forum are quite long.
Sure that in terms of functionnality it is useful, as long as it doesn't stuck others / modify existing workflows. But community can't say yes before seing real implications onto Core (still, IMHO !)

**Comment by defrance** [comment]
Factory Free a été proposé à l'intégration, j'aurai l'occasion d'en discuter avec les personnes se posant de vrais question sur l'avenir de dolibarr, pas des trolls sans courage...
Au passage il y a plus de personnes qui utilisent factory free que batch/lot, 
Hubert, j'attend ton coup de fil pour qu'on s'explique une bonne fois pour toute et que tu nous foutes la paix ... je ne te demande pas l'impossible à savoir venir au devcamp à Valence, et j'ai pas de soucis pour comparer ton implication en terme de PR dans le core, ca ce passe ici : https://github.com/Dolibarr/dolibarr/graphs/contributors  
Semble que tu sois pas très présent, si tu veux jouer chez les grands, il faut avoir les moyens de ses prétentions...

**Comment by marcosgdf** [comment]
Please, if you guys want to talk about other things you can email each other, but do not argue in this PR that does not have anything to do with other modules or features. Also, remember that English is the only official language here.

@eldy They are created as individual products so that 3rd party modules do not get affected by it. They are "linked" so that an update in the parent product triggers an update in a child product. But as I said before, this is a "basic" approach which can be improved in the future.

**Comment by BebZ** [comment]
@marcosgdf @eldy 
sorry for pollution, I wrongly answered these **out of scope** remarks... I should not have, subject is clear : 
integration of quality code for upgrading Dolibarr's quality ;). 
i will clean these useless answers. and I ask Defrance to do the same, he can always look at : https://github.com/Dolibarr/dolibarr/graphs/contributors to jerk off on his rank if he wishes.

**Comment by eldy** [comment]
@marcosgdf OK. So the way module works look ok for me. However, another module is doing same in a similar way: https://www.dolistore.com/en/modules/372-Product-Declination-3-4---4-0.html
I must compare yours with this one to choose which is better to be introduced as a new core module.

**Comment by simnandez** [comment]
@eldy we can speak about it with @atm-maxime in Valence. I think, what Marcos has permormed has more advantages compared to Product Declination

**Comment by defrance** [comment]
I'll  be there to discus to
Maybe next time we can discus befor...

**Comment by simnandez** [comment]
@eldy @marcosgdf @defrance I have tested it and works fine! There is no duplicity, easy for use... I think, what Marcos has performed should be included in the core.

**Comment by BebZ** [comment]
A "must have" for 5.0 experimental or 6.0 ?

**Comment by eldy** [comment]
Thanks @simnandez . Your point of view help me to decide to make a try to include this as experimental into core.

**Comment by eldy** [comment]
Note that, to avoid confusion with the extrafields feature, i renamed the module "Product variants" and "attribute" into "variant attribute".

**Comment by marcosgdf** [comment]
🎉

**Comment by simnandez** [comment]
Perfect, now we will have to work on improve it!

**Comment by BebZ** [comment]
and we will work on it
 to sync with magento 
and develop API classes 
to send attributes and variants of products created to other systems :)
for, let's say mid 2018

**Comment by edupulpillo** [comment]
Dear all, nice to be here.
Thinking about how to organize the product attributes, and taking a look to the aproach of the PIM systems like akeneo or pimcore that permits the concept "attribute groups", maybe a good idea to be able to use "tags/categories" in these both kind of attributes: 
1- The “complementary attributes” in “Products and services” module 
2- The "variant attributes” of the module variants

In fact maybe even better to considerate the module “variants” as a “extra product attributes management”, then all the attributes declared in the module can be organized in groups of attributes, using "tags/categories", and enable the feature “variant” only in the attributes that we want to permit the creation of product declinations using that attribute.

When the products has a lot of technical parameters (like smartphones for example), is hard to manage a large number of variant attributes, and having a way to group the attributes with tags/categories will permit more flexibility for example to:
- Be able to generate variant declinations based in all the values of "variant attribute groups" and no selecting one by one all the attributes 
- Be able to display in a product card the “extended product attributes” grouped by "tags/categories" to organize a huge amount of parameters, and also generate the “datasheet” of products that have a lot of parameters
- Be able to select//filter products that match specific values of the attributes that have a specific  tag/category, for example selecting filter using the "smartphones attributes tag" values like  “search all the smartphones cuadcore with 3Mb RAM and 16Gb Storage with red color”

Some example of values for variant attributes tags could be:  Marketing,  ERP, Technical, Design, Product, Manufacturing, Ecommerce,	Color, Size, Media...
 
So it will be great to use tags/categories in both cases "variant attributes" and "product extra attributes", and use it in the selections combined in a “join”
So @marcosgdf kindly could you add the use of "tags/categories"  in the module "variant attributes"? 

What do you think?

**Pull request merged**
