### PR TITLE
NEW Can set type of price without tax) per defaut for new sale price creation

### PR DESCRIPTION
**Pull request by BB2A-Anthony**
# New [*Add option HT TTC créate product*]
[*Long description*]

### CODE REVIEW

**Comment by altairis-tof** [comment]
Hello, good job.
imho you should test if constant exists before using it, otherwise there will be problem after migrations; unless if you update the mirgration script to put a deffault value.

**Comment by BB2A-Anthony** [comment]
Thanks

yes I wanted to add an initialization of the constant but I forgot to do it
I correct it as soon as possible

Le lun. 4 mai 2020 à 14:37

> Hello, good job.
> imho you should test if constant exists before using it, otherwise there
> will be problem after migrations; unless if you update the mirgration
> script to put a deffault value.

**Comment by BB2A-Anthony** [comment]
@eldy i have conflict resolvde

**Comment by eldy** [comment]
Can you also move the insert from file 11.0-12.0 into 12.0-13.0 ?

Because v12 is freezed for new features since April now.

**Comment by BB2A-Anthony** [comment]
> Can you also move the insert from file 11.0-12.0 into 12.0-13.0 ?
> 
> Because v12 is freezed for new features since April now.

Ok I change

**Comment by bb2a** [comment]
Why a file confli I deleted the file in PR

**Comment by bb2a** [comment]
What is problem?
Is not posible to resolv a conflic

> This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.

>

**Comment by BB2A-Anthony** [comment]
I resolved the conflicts

**Pull request merged**
