### PR TITLE
Add a field fk_entrepot in llx_societe

### PR DESCRIPTION
**Pull request by dolibarr95**
Add a field foreign key fk_entrepot in llx_societe ( llx_entrepot.rowid ).

https://github.com/Dolibarr/dolibarr/issues/7852

### CODE REVIEW

**Comment by eldy** [comment]
If you add a field into a table, you must also add the sql request into the migration script 7.0.0-8.0.0.sql to add the field.

**Comment by dolibarr95** [comment]
Hi!
Tks for your help
I would like to add 
```sql
ALTER TABLE llx_societe ADD COLUMN fk_entrepot int DEFAULT 0;
```
But i can't find the file 7.0.0-8.0.0.sql in https://github.com/Dolibarr/dolibarr/tree/develop/htdocs/install/mysql/migration

**Comment by hregis** [comment]
@dolibarr95 @eldy 
branch 7.0 not exists !!!
add to 6.0.0-7.0.0.sql

**Comment by dolibarr95** [comment]
Sorry for misunderstanding. I've update the 6-7.sql and delete 7-8.sql

**Comment by eldy** [comment]
Sorry.
Version 7.0 has been frozen. It means new feature and new fields that does not fix a serious bug and not related to experimental new tables can't be introduced.
So the upgrade instruction was correct into file 7.0 to 8.0. File does nit exist because you are the first to suggest a database change for next 8.0.
Can you restore file 7.0 to 8.0 and remove update in 6.0-7.0 ? (Sorry for misunderstood)

**Comment by dolibarr95** [comment]
Hi
thks for your feedback, i've reopen the first pr #7975

**Comment by eldy** [comment]
Done in another PR

**Pull request closed without merging**
