### PR TITLE
NEW Uniformize search sub-category

### PR DESCRIPTION
**Pull request by atm-greg**
# New Search sub-category behaviour
Allow to search on a category and its sub-category on all lists

### CODE REVIEW

**Comment by eldy** [comment]
Can you explain. If i have category CategGeo -> Europe -> France -> North
And i made a search on "Euro", does this return all record with category "Europe" + "France" + "North" ?

**Comment by atm-greg** [comment]
> Can you explain. If i have category CategGeo -> Europe -> France -> North
> And i made a search on "Euro", does this return all record with category "Europe" + "France" + "North" ?
no it returns results for europe and its level 1 subcategories (France, germany...)

**Comment by atm-greg** [comment]
> Can you explain. If i have category CategGeo -> Europe -> France -> North
> And i made a search on "Euro", does this return all record with category "Europe" + "France" + "North" ?
no it returns results for europe and its level 1 subcategories (France, germany...)

**Comment by atm-greg** [comment]
> Can you explain. If i have category CategGeo -> Europe -> France -> North
> And i made a search on "Euro", does this return all record with category "Europe" + "France" + "North" ?
no it returns results for europe and its level 1 subcategories (France, germany...)

**Comment by atm-greg** [comment]
> Can you explain. If i have category CategGeo -> Europe -> France -> North
> And i made a search on "Euro", does this return all record with category "Europe" + "France" + "North" ?
no it returns results for europe and its level 1 subcategories (France, germany...)

**Comment by eldy** [comment]
I am afraid that this behaviour introduce troubles for users.
Can you add a hidden conf on 

$moreforfilter.='&nbsp;'.$langs->trans("SubCats") . '? <input type="checkbox" name="subcat" value="yes"'.(($subcat) ? ' checked>' : '>');

so we have

if (! empty($conf->global->MAIN_ALLOW_SEARCH_ON_SUBLEVEL1_OF_CATEG))
{
$moreforfilter.='&nbsp;'.$langs->trans("SubCats") . '? <input type="checkbox" name="subcat" value="yes"'.(($subcat) ? ' checked>' : '>');
}

**Comment by eldy** [comment]
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolte, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.

**Pull request closed without merging**
