### PR TITLE
NEW add tax message on takepos menu

### PR DESCRIPTION
**Pull request by ptibogxiv**

### CODE REVIEW

**Comment by ptibogxiv** [comment]
for legal reasons, some country need more informations to display

**Comment by eldy** [comment]
Still travis errors

**Comment by eldy** [comment]
@ptibogxiv can you fix the syntax error reported by travis ?

**Comment by eldy** [comment]
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Pull request closed without merging**
