### PR TITLE
Add category contact into left menu entry

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by simnandez** [comment]
we should be updated also init_menu_auguria.sql?

**Comment by FHenry** [comment]
I didn't find the same entry into Augeria menu. Let me check.

**Comment by FHenry** [comment]
Yes I've just check again. The method use into edldy theme and that is use for all other theme is print_left_eldy_menu, but in method print_left_auguria_menu i can't find any of thirdparty menu information.

**Comment by FHenry** [comment]
Ha ok, I've found it. It's into SQL file

**Comment by FHenry** [comment]
Ok, done

**Pull request merged**
