### PR TITLE
NEW show supplier name in getNomUrl of supplier order

### PR DESCRIPTION
**Pull request by hregis**
@eldy useful in the list of linked objects in a BOM document for example

### CODE REVIEW

**Comment by hregis** [comment]
to replace this PR https://github.com/Dolibarr/dolibarr/pull/23463

**Comment by frederic34** [comment]
@hregis look at this PR https://github.com/Dolibarr/dolibarr/pull/24198

you can avoid fetch thirdparty everywhere

add `'nofetch' => 1,` in getNomUrl and check it in getTooltipContentArray

**Comment by hregis** [comment]
@frederic34 thank you, but if i add "nofetch = 1" in getNomURL i don't see the supplier name !?

**Comment by frederic34** [comment]
yes only on ajax tooltip

MAIN_ENABLE_AJAX_TOOLTIP = 1

**Comment by hregis** [comment]
@frederic34  if i add `MAIN_ENABLE_AJAX_TOOLTIP = 1`  i have the html code in the tooltip window!

**Comment by hregis** [comment]
@frederic34 ok i see the problem !! you missing to send the token for "/core/ajax/ajaxtooltip.php" !

**Comment by frederic34** [comment]
Ak ok I didn't see the problem... love these external modules changing conf 
image

**Comment by frederic34** [comment]
@hregis are you adding it in lib_foot.js.php ?

**Comment by hregis** [comment]
@frederic34 i see to add token in lib_foot

**Comment by hregis** [comment]
@frederic34 @eldy 
ok it's ready ! ;-)

**Pull request merged**
