### PR TITLE
New needs net tab on bom

### PR DESCRIPTION
**Pull request by atm-quentin**
# NEW|New needs net tab on bom

On the standard BOM form, a Net Requirements tab has been added to display all the products / services required for the BOM and its sub-BOMs, with no level limit. The products / services will be grouped by products / services, the table will display :
- The quantity needed for the BOM and its sub-BOMs
- The real stock
- The virtual stock

A button Display in tree structure will allow you to display the complete tree structure of the BOM and its sub-BOMs without level limit.

image
image

### CODE REVIEW

**Comment by eldy** [comment]
Can you replace the button "Display in a tree structure" and "Back to" that is at position for "Actions" button with 2 pictos just over the table that is position for "presentation" (Picto Flat view /  Hierarchic view) like it is for the list of users. So it will match look and feel. See example:
image

**Comment by atm-quentin** [comment]
Yes but we are in a card there, where should i display those pictos ?

**Comment by eldy** [comment]
> Yes but we are in a card there, where should i display those pictos ?

Just above the table, like it is for the task in a project card:
image

**Comment by atm-quentin** [comment]
I did it : 
image

Is it ok for you ?

**Comment by atm-quentin** [comment]
(i can add a hidden conf if necessary)

**Comment by atm-quentin** [comment]
@eldy

**Pull request merged**
