### PR TITLE
NEW personalized week project timesheet

### PR DESCRIPTION
**Pull request by atm-arnaud**
# New timesheet view per week and personalized.
This new view allow you to dynamically add tasks and spent times.

Why ?
I usually work with 10 project per week. To add my times in project's tasks i need more than 15 minutes. For finally check with custom query.

Aim ?
I created this new view to see in 1sec all my times in a week.
If i want to write my week times, i will add with the first row all tasks i worked on. When i finished to personalized my table. I will put my times in.

general_view_1
default view (my tasks)

general_view_2
Add new task in my list thanks to first row

general_view_3
default view with a new task added in my table + time spents to have 7hours / day

This new screen works with
- right : $user->rights->projet->all->create
- project allowed for all or users only
- new hide conf allowed :  PROJECT_TIMESHEET_AUTO_ADD_IN_CONTACT. This configuration overide all others and allow you to add time on not assigned task. This will add you as project and task contact

Default value : 
Only show our assigned tasks and public project
This view add all tasks with spent times (allowed or not allowed) -> you will see all your times entered in dolibarr

#Technical informations
i used SESSION vars to manage added tasks. All tasks added will be saved  in your weeks navigation.

### CODE REVIEW

**Comment by atm-arnaud** [comment]
@eldy what do you think about ?

**Comment by atm-arnaud** [comment]
hi @eldy. As you asked for, I added a new conf : PROJECT_USE_TIMESHEET_PERWEEK_PERSONALIZED

This global conf is hidden.

**Comment by delcroip** [comment]
Relying on the session seems strange, it can generate complains from the users because its behaviour is not obvious. Why didn't you use a table ?  I did it the timesheet module and it's working fine.
https://github.com/delcroip/dolibarr_project_timesheet

br

**Comment by eldy** [comment]
A lot of change was done into page  htdocs/projet/activity/perweek.php that are not in the duplicate code
 htdocs/projet/activity/perweek_personalized.php.
Can you make a compare to realign the 2 pages.
Better, if we can have just one page and the difference managed by the test on $conf->global->PROJECT_USE_TIMESHEET_PERWEEK_PERSONALIZED would be better to avoid the same situation at each new version.

**Comment by eldy** [comment]
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolete, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.

**Pull request closed without merging**
