### PR TITLE
Removed unnecesary dev/codesniffer files

### PR DESCRIPTION
**Pull request by marcosgdf**
- ruleset.dtd is not provided by CodeSniffer and it is not valid either.
- Removed unnecesary php.ini
- Modified README to remove mentions to Eclipse IDE

### CODE REVIEW

**Comment by eldy** [comment]
The ruleset.dtd is required because it is the file that guarante files ruleset.xml has correct format.

**Comment by marcosgdf** [comment]
But it is not provided by CodeSniffer so it cannot guarantee anything...

**Comment by eldy** [comment]
It is a Dolibarr addon tool, like a lot of other doibarr tools into dev or build directory to enhance and guarantee quality controls.

**Comment by marcosgdf** [comment]
Ruleset.xml validation is taken by CodeSniffer. I don't find the benefit of having the file in Dolibarr's case but I'm gonna restore it.

**Comment by eldy** [comment]
In the past, i have already several error that was not visible into this file (for exemple when merge fails), so not having a check file make errors not appears. With it, i immedialty see the error without doing anything, so i prefer keeping this file that help me so many time in past.

**Comment by marcosgdf** [comment]
@eldy Don't understand. What do you mean?

**Pull request closed without merging**
