### PR TITLE
Auto print option

### PR DESCRIPTION
**Pull request by andreubisquerra**
Add option to print automatically when sale validated.
Thanks to David Beniamine @dbeniamine

### CODE REVIEW

**Comment by frederic34** [comment]
@andreubisquerra do not forget to check travis errors:
image

**Comment by eldy** [comment]
Duplicate with PR #10903 just merged

**Comment by BebZ** [comment]
CAN IT ALSO PRINT ON DESK PRINTERS ?
THANKS

**Comment by dbeniamine** [comment]
yes it can, the print command is handled by your computer so you can use any printer available, but It will not print the full invoice. The ticket is designed to look good on narrow paper, I do not know I it will look like on "classic" printer format.

**Pull request closed without merging**
