### PR TITLE
Include locale js select2

### PR DESCRIPTION
**Pull request by frederic34**
I looking for doing that with other language

### CODE REVIEW

**Comment by frederic34** [comment]
2015-10-21 21_45_38-debut
2015-10-21 21_51_47-debut

**Comment by frederic34** [comment]
2015-10-21 22_25_31-debut

**Comment by eldy** [comment]
Hi @frederic34 
Do you work on this ? If not, i will do it.

**Comment by frederic34** [comment]
Hi @eldy 
i'm currently on printers (Google Cloud Print) and also looking at ESC/POS printers for receipt.
I prefer let you do that, I had try something but It's beurk

**Pull request closed without merging**
