### PR TITLE
NEW auto set closing date and user on invoice

### PR DESCRIPTION
**Pull request by ptibogxiv**
rewamp of  #11637

### CODE REVIEW

**Comment by eldy** [comment]
What is the definition of a date of closure ? When we set status to "paid" ?

**Comment by ptibogxiv** [comment]
@eldy indeed when set "paid" totally or not  invoice is "closed"

**Comment by eldy** [comment]
OK for merge, however can you call the field   date_closing  because we should no more introduce new data or var using french name. We spent a lot of energy with old var to rename/migrate them, so we should not introduce them with bad name. Once they are used/deployed, it is very difficult to rename them correctly.

**Comment by ptibogxiv** [comment]
@eldy  changes done ;)

**Pull request merged**
