### PR TITLE
Bug for warehouse affect

### PR DESCRIPTION
**Pull request by BB2A-Anthony**
Fix #[*Bug for warehouse affect*]

In option stock DEFAULT_WAREHOUSE not memory const

Change affect becose bug on affect select warehouse

### CODE REVIEW

**Comment by eldy** [comment]
I do not experience any trouble with last develop. Can you describe how we can reproduce the bug ?

**Comment by BB2A-Anthony** [comment]
> I do not experience any trouble with last develop. Can you describe how we can reproduce the bug ?

If an order was generated from a proposal the warehouse was not assigned correctly. If a warehouse is defined on the user, this was not taken into account.
Because we focus on the select.
This will change all other selects. When creating or modifying a warehouse, add or modify in the "Add in" field by the warehouse present on the user what could lead to errors or unintentional modifications!

**Comment by eldy** [comment]
I was speaking about the change in htdocs/admin/stock.php
I can't reproduce the bug for this change. Saving is done correctly. Can you recheck ?

**Comment by BB2A-Anthony** [comment]
> I was speaking about the change in htdocs/admin/stock.php
> I can't reproduce the bug for this change. Saving is done correctly. Can you recheck ?

If change default warehouse and modify the param is not save.

I test in V13

**Comment by eldy** [comment]
Do you mean you go on "Setup - Modules - Module stock", select a warehouse from combo list. Click on button "Modify" at right of combo list ?
I still do not experience troubles.

**Comment by BB2A-Anthony** [comment]
https://youtu.be/LieUr0UZH5c

behavior video

**Comment by eldy** [comment]
Thanks for video. I confirm i was speaking about same screen and field.
I do not reproduce the problem since it was already fixed before your PR.
Do you make a recent merge (from dolibarr develop branch and not from your forked branch) to have your repository updated with the last develop version before submitting your PR ?

**Comment by bb2a** [comment]
> Thanks for video. I confirm i was speaking about same screen and field.
> I do not reproduce the problem since it was already fixed before your PR.
> Do you make a recent merge (from dolibarr develop branch and not from your forked branch) to have your repository updated with the last develop version before submitting your PR ?

@eldy Ok how to undo the changes in /htdocs/admin/stock.php and not the others?

**Comment by BB2A-Anthony** [comment]
@eldy ok I a create new pull #14850

**Pull request closed without merging**
