### PR TITLE
FIX : get multicurrency infos of propal when create order from propal…

### PR DESCRIPTION
**Pull request by atm-gauthier**
… with "WORKFLOW_PROPAL_AUTOCREATE_ORDER" conf

### CODE REVIEW

**Comment by atm-gauthier** [comment]
Hi @eldy, i don't understand this message in travis error :
image

**Comment by eldy** [comment]
> Hi @eldy, i don't understand this message in travis error :
> image
> 

Don't understand too. May be the use of list(...) = ...
Avoid use of list() =.
Try to storz into a tmp array first $tmparray = ...
Then use tmparray[0], tmparray[1]... if defined.

**Comment by atm-gauthier** [comment]
@eldy i have the same problem after modification :(

**Comment by eldy** [comment]
i found the trouble. It is this fuc... composer. When phpunit is installer with composer 2.5 instead of 2.4, even if phpunit is same version, result differs (composer add stupid autoload code).

**Comment by atm-gauthier** [comment]
@eldy ok, do you know if i can do something about this ? Or are you going to merge anyway ?

**Comment by frederic34** [comment]
@atm-gauthier can you try to comment this line : https://github.com/Dolibarr/dolibarr/blob/fc466b1ce30b526b7feb6df60602bcd34f0db5b2/htdocs/includes/restler/framework/Luracast/Restler/AutoLoader.php#L78
I got similar problem using dolibarr api and other autoloader, this line unregister other autoloaders to keep only restler autoloader (function name is thereCanBeOnlyOne)

**Comment by atm-gauthier** [comment]
@frederic34 thank you for your answer but as i don't know this file, i prefer ask @eldy if this is what i should do ?

**Comment by eldy** [comment]
@atm-gauthier nothing to do on your side, i have fixed this by forcing composer version used to install phpunit in travis setup.

**Pull request merged**
