### PR TITLE
Problem with extrafields if we use SQL reserved word

### PR DESCRIPTION
**Pull request by defrance**
We need to use `  to frame fields when we manipulate extrafields fields

### CODE REVIEW

**Comment by ghost** [comment]
@defrance you shoud use if $db->type!='pgsql' for this notation, in pgsql this will crash.

**Comment by defrance** [comment]
@atm-florian what happens with pgsql if we use reserved sql word as SELECT or FROM as extrafields???

**Comment by eldy** [comment]
Reserved word should be filtered during creation of extrafields and refused if word is inside a list of reserved keyword

**Comment by defrance** [comment]
seems we need a great keyword list ... 
http://sqlpro.developpez.com/cours/motsreserves/

**Comment by philippe-opendsi** [comment]
Maybe forcing a prefix to prevent this problem ?

**Comment by ghost** [comment]
As I read on internet it should be double quote for pgsql, but always put them is not a good option. Better to prevent creation with reserved key word (as they already are in dolibarr tables (type, range, etc...). A prefix seems to be a good option to be sure.

**Comment by defrance** [comment]
maybe use something like this :  
SELECT \* FROM mysql.help_keyword
select \* from pg_get_keywords()

**Comment by defrance** [comment]
please consider other fix of this problem https://github.com/Dolibarr/dolibarr/pull/5996

**Pull request closed without merging**
