### PR TITLE
Fix categories bug

### PR DESCRIPTION
**Pull request by rdoursenaud**
When using the string type,
$typeid == 1 matched all strings making other conditions ineffective.

3.6 and develop also affected

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Casting an int from a string returns 0, it's asking for trouble again.
I updated my fix with an explicit condition.
Thanks for the heads up.

**Comment by rdoursenaud** [comment]
Not sure you got my answer so : ping @eldy

**Comment by simnandez** [comment]
Ummmm...
why replace the $typeid == 0 by $typeid === 0 || $typeid === '0'  ?

using == instead === we checking that the values ​​are equal, regardless of the type since a conversion is performed before comparing...

**Comment by rdoursenaud** [comment]
@simnandez because we don't want to match all the other things that are 0 in php. (Empty strings, null objects…)  We're expecting to receive either the integer 0 or a string with the character 0.
The bug was triggered by that kind of behavior, better be cautious.

**Comment by simnandez** [comment]
when I said ==0 I meant also 1(it can also be troublesome) ,2,3 ... But in the case of 0 you're right (as is usually...;) )

**Comment by simnandez** [comment]
For my is ok this pull request, can you update the ChangeLog?

**Comment by eldy** [comment]
You say
$typeid == 1 
match all other string.
I don't understand.
If you do print 'astring' == 1 you will get false. That what we want.
If you do '1' == 1 you get true, That what we want.

So as it is it should works, with your suggested patch, it won't. So i don't understand your fix

**Comment by rdoursenaud** [comment]
@eldy You're right, my initial message was wrong, I ment 0 instead of 1.
But the problem remains the same if I pass, let's say 'contact', I expect the fifth test to match, not the first !
Of course we could get away by just patching the first test but my patch makes the intentions explicit instead of implicit which is better IMHO.

**Comment by simnandez** [comment]
I agree with Raphael.

**Comment by eldy** [comment]
Ok, i understood.
There was a more simple way to fix. Just replace 
if ( $typeid == 0) 
by 
if ( $typeid == '0') 

So any string will report false with no need to duplicate all tests with and without quotes.

**Comment by rdoursenaud** [comment]
@eldy Yes, but your fix is implicit not explicit.
It's easy to think it was a mistake and revert it without understanding the consequences. (Unless you leave a comment.)
I always prefer explicit code because it's easy to understand what's expected from it.

Anyway, that's your call. If you prefer fixing it your way, I have no problem with that. What's important is that it gets fixed.

Cheers,

**Comment by eldy** [comment]
No, I don't have any preference either. It was to save time or code line ;-)

2014-09-02 15:36 GMT+02:00 Raphaël Doursenaud notifications@github.com:

> @eldy https://github.com/eldy Yes, but your fix is implicit not
> explicit.
> It's easy to think it was a mistake and revert it without understanding
> the consequences. (Unless you leave a comment.)
> I always prefer explicit code because it's easy to understand what's
> expected from it.
> 
> Anyway, that's your call. If you prefer fixing it your way, I have no
> problem with that. What's important is that it gets fixed.
> 
> Cheers,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/1815#issuecomment-54151960.

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/awstats_project

**Pull request merged**
