### PR TITLE
Fix handling of boolean extrafields in list filters

### PR DESCRIPTION
**Pull request by lemathou**
Cherry-pick commits done on earlier versions.

### CODE REVIEW

**Comment by lemathou** [comment]
I reverted a commit who was in my branch cause I started from the wrong branch... (from a fix branch I did juste before)

**Comment by eldy** [comment]
Do you mean there is a trouble in v16 ? And what about v20 for example, is it the same ?

**Comment by lemathou** [comment]
It was fixed in v20, but I (and 3 customers) are still in v19 with the bug. I a using a lot of boolean extrafields, and I cannot sort columns without loosing filters with those fields.

So, I cherry-picked the fixes from v20 in v16, because I think it was here that the bug started.

**Comment by lemathou** [comment]
I wrote "earlier version" but I though "more recent version" ... My English is bad sorry

**Pull request merged**
