### PR TITLE
I added 4 invoice pdf templates

### PR DESCRIPTION
**Pull request by Fred-Zweig**
I added 4 pdf templates for invoices. Apart from some visual improvements, I set the columns in the most commonly used order: Product Description, Quantity, Unit Price, Taxes, Total Excluding Taxes.

invoice1

Two of the templates also include an additional column: taxes amount per line, which is expected in some countries:

invoice2

Two of the templates, the ones ending in 'wt' (which stands for 'without table'), have a more modern look, as they only include the horizontal lines, which are enough to display a clear list of products and prices. This design is also adopted by many other well-known ERP applications:

invoice3

All the templates also contain the following commented lines:
```
// Add background image
//$pdf->Image(DOL_DOCUMENT_ROOT.'/core/modules/facture/doc/background1.png', 26, 90, 160, 110);
//$pdf->Image(DOL_DOCUMENT_ROOT.'/core/modules/facture/doc/background2.png', 56, 100, 100, 100);
```
If you uncomment one of the lines, you can add an image as background for the table of prices, as can be seen in the examples below. This can be useful if someone wants to include a highly transparent version of their logo or of a pattern, as background for the invoice, in order to personalize it. (The two png images are free for commercial use without attribution, as they are taken from pixabay.com)

invoice4
invoice5

The column headers: 'Quantity', 'Unit Price', 'Taxes', 'Taxes Amount', 'Total Excl. Tax' are handwritten in the pdf template, so, if someone needs them in French/German, etc. the easiest way is to replace them  with their French/German translation, directly in the pdf templates.

### CODE REVIEW

**Comment by atm-maxime** [comment]
Hi ! Thanks for contributing !
There's work in progress on PDF to be able to choose column appearance order. I think that having only one PDF model with display options is better than having to maintain several models.
Ping @atm-john

**Comment by Fred-Zweig** [comment]
Hi, atm-maxime. Thank you for reviewing this pull request.

Please consider accepting all the 4 templates as alternatives to the default 'crabe' template, which is far from being sufficient for many users. There is much thought behind the structure of the 4 new models. They are the result of a real need. I understand that you want to use one single pdf template to avoid maintenance efforts, but one single template for invoices, which are so important for every business, is not enough. For example, in some countries, all the invoices have the taxes amount specified on every line. Also, the default 'crabe' has 'U.P. (net)' instead of 'Unit Price', which can be confusing. Also, the taxes column is not large enough if there are three percent amounts mentioned for three different taxes. Please consider making the 4 templates available to everybody, if not in the next official Dolibarr version, at least somewhere in the Dolistore or on the forum.

I came to Dolibarr after using Odoo, and after getting tired of the structural faults of Odoo, such as the use of Python insteaf of PHP, and of PostgreSQL instead of MariaDB which led to very slow performance in spite of all the speed optimizations. I also profoundly disliked the so called 'open core' model, in which many modules providing useful features where not licensed as FOSS but as proprietary software. But, I have to say that even Odoo had about 5 alternative models of pdf invoices. I attach one here for reference:
odoo-invoice
As you can see, there are no vertical lines, because they are in general not needed. Also, after the product description, the most logical thing to have is the quantity, then the unit price, then the taxes and then the amount without taxes. There is also a background image.

**Comment by atm-maxime** [comment]
As I said, a single model with options for the column orders will be soon available. Adding a background image is possible with a hidden conf. As for the vertical lines, it's a cool evolution to consider as an option of the model.
You're welcome to share your models on dolistore or the forums.
Other element, if you have this 4 models on invoice, then we should have the same on orders, proposals, contracts, ... And maintaining 1 model per type is quite enough, multiplying this by 4 would be very time consuming.

**Comment by Fred-Zweig** [comment]
I shared the templates on the Dolibarr forum (https://www.dolibarr.org/forum/t/4-alternative-invoice-pdf-templates/18886).

I understand that the maintenance effort would be much greater for one default template plus 4 alternative ones instead of for a single default template. In this case, the optimal thing to do, in my opinion, would be to create one default template that would be easily customizable by the user (maybe in Home > Setup > Modules/Applications > Invoices > Setup) in the following areas:
1. Order of columns.
2. Header of columns.
3. The option to include or not to include the tax amount per line.
4. The option to enlarge the width of a column.
5. The option to display the product list with or without vertical lines.
6. The option to display or hide the square background or frame around the sender or the receiver's name and address.
7. The option to include an adjustable size image as background for the product list and not for the area below the product list.

I must confess, I was surprised that such a powerful and flexible ERP/CRM platform like Dolibarr, has such limited options when it comes to customized invoices. Indeed orders, proposals, shipments, etc., have their importance, but for many businesses, the only document that the customers see is the invoice for the products that they order on an e-commerce platform like WooCommerce, so from a design point of view, the invoice is far more important than orders, shipments, etc. The invoice is like a business card. If it looks professional, then the company behind it looks professional. And indeed, the default pdf template can be customized, but it took me many hours to study and understand what to change and how to change it, in order to get the visual structure that I needed. It would have been much better if I had the option to choose between about 5 templates, or to be able to customize through a graphical interface, the one single default template.

**Comment by altairis-tof** [comment]
@Fred-Zweig : Many thanks for sharing this here and on the forums. It should be useful to lot of users.
@atm-maxime : good news to know that column order setup will soon be available; i am also working on this and in fact all pdf content setup since some months. It would be nice if we succeed to share our planned r&d work to avoid working on the same subjects in the same time without cooperation ;-) not speaking of the forbidden "roadmap" word but something approaching that might lead to more efficient communautary work. I tried to start it some years ago with the dolipro project but it did not work mainly i think because it was not lead by an "official" dolibarr team. I know that it is not the goal of the dolibarr fundation, but we should find a way to achieve this, either by evolving the fundation status or (bad idea i guess) by creating another structure to manage it. In all cases, i remain at your disposal to talk about it and/or take part into this project, as well as the communication of the fundation if needed ;-) Best regards

**Comment by atm-maxime** [comment]
Hi !
For all core contributions, GitHub is for me the right place to share. Issues can be used to share work in progress, i.e the work on the theme (#9429) is subject to many discussion on the related issue. So when starting work on a subject, I think we must first search the issues to see if the subject is already in discussion and join, or create the issue to start it. Maybe @atm-john should create the issue about PDF enhancement and share what he's working on. I know extrafields will be easily added to PDF in v12.

Besides, @eldy manages the "top priority" issues that are the main subjects we want the community to go to, but the roadmap is made by the contributions.

So for now, GitHub is our place to share. So what we need is more people checking on issues to answer, link to other issues, labelling issues, ...

As for the foundation communication, can you send an email to the foundation and tell how you can help us on this subject? Next board meeting is on 5th of May.

Have a nice day !

**Comment by altairis-tof** [comment]
i thought "Issues" were meant to report bugs or evolution demands; github has a "Projects" tab to manage the project that is much more optimized for work (see below)
Capture du 2020-04-18 09-25-12

**Comment by altairis-tof** [comment]
@atm-maxime for the communication part, my proposal would be tocommunicate about the activity of the fundation to users via the forums and to partners by email. 
Maybe also communicate about the work in progress on github to the users on forums and report their comments to the projet maintener and developers. 
It will be useful especially for the big french community where everybody has not all the skills to follow discussions in english, and for all the users that are not on gitthub.
I will email these proposals to the fundation if you think this post is not sufficient. Tell me ;-)

**Comment by altairis-tof** [comment]
thanks to ksar that just made posts on the forums with links to the fundation board reports !

**Comment by Fred-Zweig** [comment]
Here are the pdf templates and the two backgrounds for anyone who wants to upload them to their server and test them:
[pdf_templates.zip](https://github.com/Dolibarr/dolibarr/files/4496823/pdf_templates.zip)
Unfortunately, the forum won't let me post any type of archive.

**Comment by eldy** [comment]
.zip files should be uploadable on forums.
Do you get an error message ?

**Comment by Fred-Zweig** [comment]
Yes, when I tried to upload any type of archive I got: "Sorry, new users can not upload attachments.".
Anyway, ksar told me on the forum that new users with less than 10 messages can't upload archives and lifted this limitation for me, so now I can upload zip archives on the forum. The archive is now on the forum. Thanks !

**Comment by cfoellmann** [comment]
Shouldnt this be in a module?
Keeping the core templates simple and in the same style as they are now should be the way to go.

**Comment by alsoft10** [comment]
@atm-maxime I would like to say that @Fred-Zweig did an excellent contribution to the Dolibarr project. I think we should not discourage his contribution. On the other hand it is not necessary to add 4 templates at a single time. I think follwoing things we can do.

1. First we can take his changes and make it available at our default theme, **crabe**, if possible.
2. If it is not possible to include his changes in our default theme then we should create a new single template and add necessary features from his PDF templates.

I agree with @Fred-Zweig that for a powerful ERP?CRM like Dolibarr should have more customizable invoice template. Because a single template cannot fulfill all users requirements all over the world.

**Comment by BebZ** [comment]
Hello, 

I am not sure if orders of columns is available in Dolibarr 12 or 13 ? (announced by @atm-maxime )

As you see, a little modification can take a lot of time, to have no major structural problems :) and respect the way we develop it, on github with pull / comments / & push requests, on the develop core branch ;).

Maybe you can cross check the modifications you asked if available in develop ? 

Home > Setup > Modules/Applications > Invoices > Setup) in the following areas:

Order of columns.
Header of columns.
The option to include or not to include the tax amount per line.
The option to enlarge the width of a column.
The option to display the product list with or without vertical lines.
The option to display or hide the square background or frame around the sender or the receiver's name and address.
The option to include an adjustable size image as background for the product list and not for the area below the product list.

**Comment by BB2A-Anthony** [comment]
It is true that we do not always know current topics and current or future developments.
Even following the git or the forum it is not always explicit even for the meeting minutes of the thank you @ksar-ksar

**Comment by BB2A-Anthony** [comment]
@Fred-Zweig @atm-maxime @altairis-tof I created configuration pages for PDF documents PR #17404

**Comment by eldy** [comment]
@Fred-Zweig To avoid to have too many templates to maintain, I try to keep now only 1 template for each type of document. But we can add options of the reference template to customize the template.
Can you instead push your enhancement into the existing template pdf_sponge for invoices (pdf_crabe will be removed and replaced with pdf_sponge in a future that is the "reference" template now) ?

A setup tab page has also been introduced into v14 in section setup - pdf - other to give an area where we will be able to add options to customize more PDF (for example choosing columns to show, order, and more...).

**Comment by cfoellmann** [comment]
Maybe we should correct this wiki entry: https://wiki.dolibarr.org/index.php?title=Create_a_PDF_document_template#For_an_existing_module

There is the easy way we use internally. We have a custom module containing PDF templates for all different elements of Dolibarr.
For example we extend pdf_sponge and overload all functions we want to modify.
As long as the module is active the template is available to dolibarr without any database modifications.

Just follow the folder structure like : `/custom/mymodulename/core/modules/facture/doc/pdf_facture_extended.modules.php` here you start with `class pdf_facture_extended extends pdf_sponge{}`

**Comment by cfoellmann** [comment]
another solution might be to add a folder structure to place custom templates in.
Possibilities:

`/custom/templates/<module>/doc/<template-name>.template.php` OR
`/templates/<module>/doc/<template-name>.template.php`

**Comment by DATUC** [comment]
> Hi ! Thanks for contributing ! There's work in progress on PDF to be able to choose column appearance order. I think that having only one PDF model with display options is better than having to maintain several models. Ping @atm-john

Nice idear this wil be realy helpfull

**Comment by john-botella** [comment]
@DATUC from 12.0 of Dolibarr version some new Models were introduced, they have possibility to allow custom column organisation from hooks, for exemple, find defineColumnField in pdf_sponge.
The first step was here
For the second step we introduced extrafields in columns and description of PDF
Now the next step is to create an user interface to manage cols for all compatible PDF models 
I currently searching for a good structure of code and datadase data storage, but the balance between time to spend for creating this feature than use hook to set cols as we want on a custom module is clearly ins't in avantage of the new feature... so I wait to found a good idea in addition of this feature to be sure to not add maintenance charge in Dolibarr for a not realy used feature

**Comment by DATUC** [comment]
> 
Hi @atm-john 
Can this be tested allready if yes how please this wil be verry usfull

**Comment by eldy** [comment]
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolete, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.
Having one generic template is preferred than maintaining n specific templates.

**Pull request closed without merging**
