### PR TITLE
fix: catch error extrafields delete

### PR DESCRIPTION
**Pull request by FHenry**
method extrafields->delete() do not handle error correctly

### CODE REVIEW

**Review by lvessiller-opendsi — APPROVED** [review]

**Comment by lvessiller-opendsi** [comment]
@rycks 
It's ok for me

**Comment by FHenry** [comment]
@eldy 
Is it in contribution guidelines to allow this kind of changes in 18.0 branch or should I change the PR base branch to develop ?

I've suggested this PR in 18.0 branch because I've encounter "not displayed error messages at all and failed action" when I try to delete extra-fields with foreign key constraint added by external module in 18.0 branch, but that's obviously an edged use case. 

Would it be a better way to change base merge branch (or create a new PR on develop branch) ?

**Comment by eldy** [comment]
> @eldy 
> Is it in contribution guidelines to allow this kind of changes in 18.0 branch or should I change the PR base branch to develop ?
> 
> I've suggested this PR in 18.0 branch because I've encounter "not displayed error messages at all and failed action" when I try to delete extra-fields with foreign key constraint added by external module in 18.0 branch, but that's obviously an edged use case. 
> 
> Would it be a better way to change base merge branch (or create a new PR on develop branch) ?

No guideline available for the moment. I must write it. Yes it is at the edge of the limit. It may changes behaviour so should be in develop, but it also avoids an error visibility so may be small bug. If t's 50/50.

**Comment by FHenry** [comment]
@eldy 
I've change to develop branch

**Pull request merged**
