### PR TITLE
Add Extrafields management bom line

### PR DESCRIPTION
**Pull request by atm-lena**
# FIX|Fix #
Add extrafield management for bom line

### CODE REVIEW

**Comment by eldy** [comment]
Can you push on develop branch ?

**Comment by atm-lena** [comment]
> Can you push on develop branch ?

Possible to merge in 16.0 ? We need extrafields on bom line in 16.0. 
Create bomline class without extrafields was an error

**Comment by eldy** [comment]
Sorry, it is not possible to add this into v16.
The v16 is already finished and was already published and we can't have 2 v16.
But this is welcome into develop.

**Comment by eldy** [comment]
The structure of database is already ok into v16, so i can include this into v16. However we had some changes into develop on how the database is updated, where method updateLine and addLine were introduced into BOM.
If i merge this into v16, the change will be lost into develop (merging this into develop is not compatible). For this reason i can't merge this into v16.

**Pull request closed without merging**
