### PR TITLE
NEW: no more default rights defined by default

### PR DESCRIPTION
**Pull request by atm-maxime**
That's a suggestion I'd like to make. From my point of view, having default permission given when a module is activated is a bad practice. It happended many times that a new user is created and has by default rights to read "everything" (bank accounts, invoices, ...).
Rights should be managed by administrator on user or groups cards.

Open to suggestions or opposite points of view :)

### CODE REVIEW

**Comment by BebZ** [comment]
Same for me, access to "everything" leads to "a mess" in the the head of new users.
When a user is new, we should grant him access when we trust him and when we know he can use it.
At the beginning I only allow reading and writing : 
 Thirds and Products for a secretary for example...
then to "customer orders"
At last, I allow  deleting (if needed), 
when the person has understood its error and will not reproduce and delete something important.

So rights should be granted little by little, except for admin accounts

**Comment by accett** [comment]
I agree. By default could be without permissions, but maybe a legend or
message to the admin for remember give the permissions would be good.
Overall for the beginners users.

**Comment by simnandez** [comment]
I agree, the default permissions must be set into security admin setup, on module activation maybe a message for remember give the default permission for this new useable module.

**Comment by rdoursenaud** [comment]
Agreed. :+1: 
As @BebZ said, a popup notice warning the admin to set permissions would be a neat addition.

**Comment by eldy** [comment]
Dolibarr must be easy to install. That's why we introduced default permission once module is enabled. 

It is VERY VERY important that user see/find feature after enabling module without loosing time and without asking him to make useless setup. If an admin enable a module, it means he want to use it.
But may be the "default permission" is not the correct answer.

If we remove it (this means removing the page to setup default permissions), we must be sure that:
- for admin users, all permissions are still set just after enabling the module (this is the most important point)
- for other users, a warning visible on user card (in the new card banner) when no permission at all are set must be visible.
- a warning when a module is enabled must also warn that permission were added for admin users but not for all other users.

Does the 3 points are dealed with the PR ? If not, can you complete ?

**Comment by atm-maxime** [comment]
Ok work done. Now :
- Module activation gives a message to remind that permissions were added only for admin users
- User card shows a warning if user has no permission (and number added in permission tab)
- Core module won't give default permissions on activation

**Comment by eldy** [comment]
Hi @atm-maxime 
Branch develop is opened for major changes now. Can you solve conflict on this PR ?

**Comment by eldy** [comment]
Ping @atm-maxime

**Pull request merged**
