### PR TITLE
Fix: use array_merge_recursive instead array_merge

### PR DESCRIPTION
**Pull request by hregis**
@eldy 

array_merge_recursive is better for avoid overwriting existing values,
you can show examples here:

for array_merge_recursive : http://php.net/manual/fr/function.array-merge-recursive.php
for array_merge : http://php.net/manual/fr/function.array-merge.php

### CODE REVIEW

**Comment by hregis** [comment]
@eldy  ping
it's very blocking if 2 externals modules use the same hook with array return !

**Comment by eldy** [comment]
This fix will solve problem when 2 external modules return array with same key.
But it will also introduce a lot of problems.
If module 1 return array with key toto and val "v1" and module 2 return also key toto and val "v2", then the merge_recursive will transform the return so the key will not be v1 neither v2 but an array.
However, the dolibarr core code expect to get a string and not an array of string.
For wich hook do you have this need ? Can you provide an exemple of return array for module 1 and 2 that create a problem ?

**Comment by hregis** [comment]
@eldy 
désolé je le fait en français !
par exemple ça se produit avec le hook "getLoginPageOptions" qui permet de personnaliser la page de login, mais ça peut se produire avec n'importe quel hook qui utilise "resArray" !

Multicompany l'utilise et renvoi "array('options' => array('table' => '...', 'div' => '...'))"
et j'ai un autre module qui se sert de "array('options' => array('js' => '...'))"

ci-dessous un exemple simple du fonctionnement actuel : 

```
$results1=array("options" => array("table" => "code html", "div" => "div code"));
$results2=array("options" => array("js" => "code js"));

$resArray=array();
$resArray = array_merge($resArray, $results1);
$resArray = array_merge($resArray, $results2);

print_r($resArray); //Array ( [options] => Array ( [js] => code js ) )
```
le second écrase le premier, alors que avec array_merge_recursive : 

```
$resArray=array();
$resArray = array_merge_recursive($resArray, $results1);
$resArray = array_merge_recursive($resArray, $results2);

print_r($resArray); // Array ( [options] => Array ( [js] => code js ) ) Array ( [options] => Array ( [table] => code html [div] => div code [js] => code js ) )
```

**Comment by hregis** [comment]
@eldy 
à mon avis il faudrait mettre le nom du module sur les "resArray" afin de ne pas écraser les valeurs !
et faire en sorte de modifier les foreach ou autres en conséquence... Ainsi on garde array_merge !

array('nomdumodule' => array('options' => .... ))

```
$results1=array("multicompany" => array("options" => array("table" => "code html", "div" => "div code")));
$results2=array("nomdumodule" => array("options" => array("js" => "code js")));

$resArray=array();
$resArray = array_merge($resArray, $results1);
$resArray = array_merge($resArray, $results2);

var_dump($resArray);

array (size=2)
  'multicompany' => 
    array (size=1)
      'options' => 
        array (size=2)
          'table' => string 'code html' (length=9)
          'div' => string 'div code' (length=8)
  'nomdumodule' => 
    array (size=1)
      'options' => 
        array (size=1)
          'js' => string 'code js' (length=7)

```

si on ne modifie pas à partir de la version 4 il faudrait au moins modifier la version 6 !

**Comment by hregis** [comment]
@eldy ping !

**Comment by eldy** [comment]
The problem is how the hook getLoginPageOptions was implemented. It does not match the hook specification.

We have
$morelogincontent = $hookmanager->resArray['options'];		// TODO Use here a resprints
And we should have
$morelogincontent = $hookmanager->resPrint;

If we make this change and you make the return of output into  ->resprint, then, having multiple hooks with different returns is supported correctly. You should not have any problem, don't you ?

**Comment by hregis** [comment]
@eldy 
In this case it would be necessary to add a hook for the part "js" to avoid that it is in the middle of the table ? 
Otherwise, globally, it would be good to be able to define a priority order of display of the resprints!

**Comment by hregis** [comment]
@eldy 
it's ok with resprint https://github.com/Dolibarr/dolibarr/pull/7297

**Pull request closed without merging**
