### PR TITLE
FIX: typo

### PR DESCRIPTION
**Pull request by rdoursenaud**

### CODE REVIEW

**Comment by eldy** [comment]
Currently field into database is ref_supplier, so we should keep code for this.
May be we must introduct a new field ref_customer ?

**Comment by eldy** [comment]
Still don't understand why we change ref_supplier into customer ? Is it a bug ?
If we need customer ref, should we not add ref_customer without removing ref_supplier ?

**Comment by rdoursenaud** [comment]
Sorry for the late reply.
This is weird indeed, but the UI says CustomerRef while the code/database is ref_supplier! How confusing!
I don't know what's going on here…

**Comment by rdoursenaud** [comment]
Sorry, I didn't get my head around what it was meant for.
Looks like I was not the only one:
The code token has been renamed at commit 14ca936cfc6ad09ba11348d295d4fa03d6eb1913 for unknown reasons.
Looking further down into this file's history, it seems going back and forth between ref_ext, ref_supplier and ref_customer. See d02814192f16ecc70b0486b63f01905e3825eba5, cf63f1a40da02e93360913d3580aea60f1fe8e53.

**Pull request closed without merging**
