### PR TITLE
NEW : Add constant to hide categories in TakePos

### PR DESCRIPTION
**Pull request by altairis-melina**
Add constant TAKEPOS_NO_CATEGORY

image

### CODE REVIEW

**Comment by eldy** [comment]
This replace #19525 ?

**Comment by altairis-tof** [comment]
no they are two different options

**Comment by eldy** [comment]
Ok. Can you rename option into  
TAKEPOS_HIDE_CATEGORIES

**Comment by altairis-tof** [comment]
ok thanks: @altairis-melina will do it next week (she's part time at school)

**Comment by altairis-melina** [comment]
@eldy It's ok. The constant was renamed into TAKEPOS_HIDE_CATEGORIES

**Comment by altairis-tof** [comment]
@eldy please note that @andreubisquerra has "approved" Melina PRs : https://github.com/Dolibarr/dolibarr/issues/13863#issuecomment-987176715

**Pull request merged**
