### PR TITLE
 NEW Accountancy - Add options to disable accounting on sales, purchases & expense reports

### PR DESCRIPTION
**Pull request by aspangaro**
image

### CODE REVIEW

**Comment by eldy** [comment]
Do you mean, you use expensereport module and accounting but you don't want to export expensereport in accounting, only invoices for example ?

**Comment by aspangaro** [comment]
@eldy you're right.

Some customers want to use only module without export in accountancy. We frequently see it on expense reports.

**Comment by eldy** [comment]
So it is not only the binding that is disabled but all the transfer in accountancy too. If there is no binding, it means there is no transfer in accountancy ? If right, we may rename "Disable binding on expense report" into "Disable accountancy on expense report", all the process is disabled, right ?

**Comment by aspangaro** [comment]
Hi @eldy 

I changed the wording of the feature to make it clearer. Yes, if you disable on sales, binding & transfer in accountancy for sales journal is totally disabled. Will remain the creation of handwriting directly in the ledger

image

**Comment by aspangaro** [comment]
Ping @eldy

**Pull request merged**
