### PR TITLE
Fix: [ bug #1754 ] Error while installing 3.7

### PR DESCRIPTION
**Pull request by marcosgdf**
Fix: [ bug #1754 ] Error while installing 3.7

### CODE REVIEW

**Comment by eldy** [comment]
To have the install and upgrade process working correctly, we should never have constraint coded into the creation of table. All constraints must have an explicit name.
That why the creation of index must be done into the .key.sql file.

And creation of unique index is done by the
ALTER TABLE llx_c_regions ADD UNIQUE INDEX uk_code_region (code_region);

Why removing it in the patch ?

**Comment by marcosgdf** [comment]
Because llx_c_country keys are created before llx_c_regions.

So, llx_c_country tries to create a foreign key but llx_c_regions doesn't have any key defined and it fails.

It would be nice to only put in .key.sql files the foreign keys because of that

**Comment by eldy** [comment]
Sorry i still don't understand.

First we create table with no constraints.
Then, we create key for llx_c_country. There is no foreign key on this table, so no erreur, only unique keys.
Then we create the keys for llx_c_regions that include creation of a foreign key from llc_r_region to the unique key of country. So we have thing in correct sequence.

I think you are speaking of a pb with llx_c_departements.
I pushed a better fixed.

**Comment by marcosgdf** [comment]
You should have let me explain instead of closing the PR.

What I was telling you is that Dolibarr is configured in a way that `llx_*.sql` files are executed first and then `llx_*.sql.key`. But the order is normally alphabetic (depends on the OS)

This is OK until foreign key is being created BEFORE an index is created on the destiny table.

For example:

llx_c_departments (FIRST): Tries to create a foreign key to llx_c_regions.column. FAILS because llx_c_regions indexes were not yet created. (Unable to create foreign key because destiny table doesn't have an index on that row)
llx_c_regions (SECOND): Creates indexes.
Result: KO because llx_c_departments foreign keys couldn't be created.

**Comment by marcosgdf** [comment]
ping @eldy

**Comment by eldy** [comment]
Pb is only between foreign key for llx_c_departement toward llx_c_region.

Because indexes are created into order of files , to solve pb i introduced
creation of missing index just before the creation of foreign key into file
llx_c_departements.key.sql
This is the only case so it is better to add this exception than splitting
all index files in 2 to have fors all indexes and then all foreign keys
created.

2015-01-13 19:41 GMT+01:00 Marcos García notifications@github.com:

**Comment by marcosgdf** [comment]
Thanks for your explanation :)

**Pull request closed without merging**
