### PR TITLE
Update es_ES from transifex

### PR DESCRIPTION
**Pull request by simnandez**

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Isn't that supposed to be done regularly for all languages by @eldy?
It's just a matter of using `tx pull` and committing the changes.
Maybe it's time for us to invest in a nightly build server that'll do cumbersome maintenance tasks like this automatically!

**Comment by simnandez** [comment]
@rdoursenaud: OPS!! You're right (as usual, but not always ...), @eldy make this for all languages...

Is a godd idea invest in a nightly build server....

**Comment by rdoursenaud** [comment]
Of course I'm not always right! I'm still human after all, or am I? :ghost:

**Comment by simnandez** [comment]
I thinks... I'm yoda... @eldy: if you are full i can do it every friday (or any other day that we stipulate)

**Comment by rdoursenaud** [comment]
Upon further inspection, there seem to be quite a bunch of languages that are out of sync.
Using the simple `tx pull` don't sync es_ES amongst others.
The transifex script don't seem to work very well there. Don't know why though.
Using `tx pull -f` I get a huge diff with all the languages updated correctly.
Strange…

**Comment by rdoursenaud** [comment]
After RTFM, it looks like we also need to use `tx pull -a` to get new translations.
Of course since these are new files a `git add htdocs/langs` is also needed to get them on board ;)
Hope it helps defining a more streamlined workflow for translations management.

**Comment by simnandez** [comment]
Normmaly, I use for sync from transifex to my local only a language(Eg Spanish): tx -d pull -f -l es_ES , and for sync all languages: tx -d pull -a without problems

**Pull request closed without merging**
