### PR TITLE
links color for table title line is equal to Text color for table title line

### PR DESCRIPTION
**Pull request by BB2A-Anthony**
# Fix #[*links color for table title line is equal to Text color for table title line*]
[*Long description*]

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide a screenshot of what it changes ?

**Comment by BB2A-Anthony** [comment]
> Can you provide a screenshot of what it changes ?

@eldy Change color title

Befor:
image

After:
image

**Comment by BB2A-Anthony** [comment]
@eldy its not good?

**Comment by eldy** [comment]
This break one of the user interface behavior that say that "clicable links" uses the same color. It means here it is no more possible to know the link is a lickable link ?
So with default theme, we got
image
instead of
image

In your case, it is better, but with the default setup of colors, it is the opposite.

**Comment by BB2A-Anthony** [comment]
> This break one of the user interface behavior that say that "clicable links" uses the same color. It means here it is no more possible to know the link is a lickable link ?
> So with default theme, we got
> image
> instead of
> image
> 
> In your case, it is better, but with the default setup of colors, it is the opposite.

An other param for color link title its a solution no?

**Review by BB2A-Anthony — COMMENTED** [review]
@eldy i change code

**Pull request merged**
