### PR TITLE
Update expedition.class.php

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by frederic34** [comment]
Without this PR, you need to refresh the page to see effect of set_billed function.By example, try to close a sending ('cloturer').

**Comment by eldy** [comment]
Thanks, i pushed a better fix.

**Comment by BebZ** [comment]
Where is it pushed, i tried to see history of file, but there is no fix, maybe on another file ?

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/commit/9c69ab966fbd6cb2272b6a194e55c5444fc2aa63

**Pull request closed without merging**
