### PR TITLE
T975-develop: Don't print the mail of the contact who is gone

### PR DESCRIPTION
**Pull request by lrasamoelina**
I Add an element (statut) in the table llx_socpeople.
It's used to mark if the contact is gone or no(we can activate or desactivate the contact with this)
And if the contact is gone,we don't print her mail in the mail list,where we can send a mail

### CODE REVIEW

**Comment by atm-maxime** [comment]
This is a great function. However, I think that status functions that were already existing should be overwritten. The contact status didn't exist before you adding it, so status 0, 1, 4, 5 should not exist.
I suggest you to delete status related function and only keep the 0 and 1 status.
If I were you, status 1 = active, status 0 = inactive. So in database we should update this column and set all to 1.
Another thing I noticed, you user the trigger USER_ENABLEDISABLE, it should be CONTACT_ENABLEDISABLE.

Thanks !

**Comment by lrasamoelina** [comment]
Ok,thanks for your suggestion.

**Comment by eldy** [comment]
Patch could be valid for validation but there is a conflict when merging. If pull request is resend with merge fixed, i can validate it.

**Comment by lrasamoelina** [comment]
it's should be ok now

**Pull request merged**
