### PR TITLE
Added SOAP client for creating a client order in remote webservice

### PR DESCRIPTION
**Pull request by IonAgorria**
Added SOAP client for creating a client order in remote webservice that thirdparty might have.

This commit adds these language keys:
-SOAPError - SOAP Error occurred
-RemoteOrderRef - Successfully created remote order with ref: 
-CreateRemoteOrder - Create remote order
-RemoteUserMissingAssociatedSoc - Remote user doesn't have a associated thirdparty
-SupplierMissingRef - Supplier doesn't have ref
-ResponseNonOK - Incorrect response from remote server
-RemotePriceMismatch - Supplier price doesn't match local price
-RemoteUserNotPermission - Remote user doesn't have permission
-ErrorOccurredReviseAndRetry - A single or various errors ocurred, please revise and retry again

### CODE REVIEW

**Comment by IonAgorria** [comment]
I would like to store the remote dolibarr host address and webservice key, having to introduce it each time can be time consuming, for example in thirdparty card. But I'm not really sure how to proceed, should change the existing table and add 2 cols? create a separate table?

**Comment by eldy** [comment]
This might be an interesting feature. However, this is what you should do to have it validated into core.
- Create a new module called "Sync supplier order with external web services".
- Add an option on code you add (button visibility) if module is on.

For your queston, you ae speaking about "dolibarr remote host". You mean the external supplier web service remote host ?
I right, you can add fields into thirdparty table and have the field visibles only when module ""Sync supplier order with external web services" is on.

**Comment by IonAgorria** [comment]
The fields is still pending, for adding new fields in table I have to modify the https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/migration/3.6.0-3.7.0.sql file right?

**Comment by IonAgorria** [comment]
modSyncSupplierWebServices has the ID 2650, translation is need for name/description

These new language keys are added
ErrorWebServicesFieldsRequired - Web Service URL and Key are not filled in thirdparty page
WebServiceURL - Web Service URL
WebServiceKey - Web Service Key
RemoteUserBadCredentials - Remote user login problem, check credentials

**Comment by eldy** [comment]
Yes, fields must be added both into:
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/migration/3.6.0-3.7.0.sql
and into
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/install/mysql/tables/

**Pull request merged**
