### PR TITLE
FIX #2820 : rename reserved keyword "Resource" into "DolResource"

### LINKED ISSUE #2820: Class name of the resource module's CRUD is reserved
The classname `Resource` is reserved in PHP for [resources](https://php.net/manual/fr/resource.php) (file handlers, database handlers, sockets…).
Using it messes with type hinting in IDEs.
I think it should be renamed to something like `DolResource`.
ping @jfefe

### PR DESCRIPTION
**Pull request by jfefe**
Rebase made from 3.9 branch, I don't know why those several commits attached :\

### CODE REVIEW

**Comment by braito4** [comment]
@jfefe check this repository https://github.com/IonAgorria/dolibarr/tree/resources

**Comment by eldy** [comment]
Because this is an architectrue and refactoring change, can you push it into develop ? 3.9 is already frozen.

**Comment by jfefe** [comment]
@eldy : ok!

@braito4 : could you tell more about features included in this repository? @IonAgorria is welcome to push its changes into Dolibarr core :)

**Comment by braito4** [comment]
@jfefe The main idea is the possibility of using services to made resources busy on time.
you still have the simple resource and we add the scheduled resource. This one is related to a schedule that you can create to fit your time: open hours, days (hotels for example), etc
You can add a resource to a service (you can create a tree of preferences to be used by) with a duration (it can be equal to the duration of the schedule resource or proportional) in order that when you sell that service the resource become busy.
Also you can add directly a client to a resource and then chose the service that fit your criteria.

Also we improve resource add to a event, a webservice to ask the status of a resource and more.

**Comment by eldy** [comment]
@jferry Because some PR come to enhance the resource module, we must clean it quickly to avoid pb with other PR. Can you make PR of this on develop branch ?

**Comment by defrance** [comment]
think dolResource is not the better name...
why not use instead 'Unit' or 'Device' by opposite of Human Resource

**Comment by eldy** [comment]
Merged manually to solve conflict

**Pull request closed without merging**
