### PR TITLE
NEW: Project contact tab

### PR DESCRIPTION
**Pull request by atm-quentin**
# NEW|New Project contact tab

### CODE REVIEW

**Comment by atm-maxime** [comment]
Can you describe what this does or maybe add a screenshot ?

**Comment by atm-quentin** [comment]
image

**Comment by atm-quentin** [comment]
image

**Comment by atm-maxime** [comment]
Thanks ! So this is a contact project tab.
Why not add this in in the "related objects" tab ? I think it would be better and also display the contact role

**Comment by atm-quentin** [comment]
Because on thirdparty it's a tab so we did the same on contact

**Comment by atm-maxime** [comment]
Ok understood, please just add the contact role on the list

**Comment by atm-quentin** [comment]
done

**Pull request merged**
