### PR TITLE
[WIP] de_DE translation for 10.x

### PR DESCRIPTION
**Pull request by cfoellmann**
This PR will bring the German translation to 95%+

### CODE REVIEW

**Comment by frederic34** [comment]
translation are done in transifex, your change here will be overwritten by next update
https://www.transifex.com/dolibarr-association/teams/

**Comment by cfoellmann** [comment]
@frederic34 transifex is not up-to-date.
There are strings from the source missing can you fix that?
When are the the translations updated? On release?

**Comment by eldy** [comment]
Yes, translation are sync just before a release.
Transifex should be up to date, except for very new strings. New strings may need 1 month to appear.

**Comment by eldy** [comment]
PR on files into langs/xx_XX where xx_XX is not en_US is useless because files are erased by Transifex translation of en_US. Change on translation files must be done with PR for en_US only. For other languages (en_NZ, es_ES, ...), fix of translation must be done directly on https://www.transifex.com/dolibarr-association/dolibarr/

**Comment by cfoellmann** [comment]
So I need to manually add strings from the UI to en_US?
That is a very error prone and tedious way of doing it. There must be some kind of update process scanning the codebase for all strings.
is there some package for it? Like for gnu gettext?

**Pull request closed without merging**
