### PR TITLE
ODT fix + new feature (full control over ODF object)

### PR DESCRIPTION
**Pull request by lrq3000**
Hello,

Here is a new commit which fix a problem with ODT segments temporary folders (which prevent odt with dynamic images to be generated), and adds an optional $odfHandler parameter for users' substitution functions, which extends ODT substitution functions to pretty much do anything because users now have full control over the ODF object.

For example, this allows to generate dynamic images for every products lines on-the-fly, which is not possible otherwise (except by modifying either the ODF class or Dolibarr generation classes...).

This patch is clean, small, and retrocompatible (if you didn't specify $odfHandler, the substitution function still works from my own tests).

### CODE REVIEW

**Comment by lrq3000** [comment]
odfHandler is already added at the end, just before funcname (which is not relayed to the substitution function), and I checked, there's no compatibility problems, because anyway there's no function in the whole Dolibarr code that uses funcname except the lines I modified.

But indeed, I agree that odfHandler depends on the context, but I thought this can probably be adapted to other contexts (there's always a parent object that can be relayed if needed), and anyway it's an optional parameter.

BUT a cleaner alternative would be to change in doc_generic_odt.modules.php what $parameters contains: instead of just containing the current product's $line, it could contain $parameters['line'] = $line; $parameters['odfHandler'] = $odfHandler. But this would break the compatibility with existing substitution functions that use complete_substitutionarray_lines (although I'm certain that there are really anyone yet using this substitution function except CustomFields since this change was introduced in v3.3, not yet in any stable version).

If this change appeals more to you, I can make a new patch implementing this alternative.

But I think it is really necessary: indeed there is no other way to achieve this kind of functionality in a flexible manner. For example, here we would have to create another array to contain images and pass them to $odfHandler in doc_generic_odt.modules.php to process them, and there's no way around because the substitutionarray is special characters-filtered, so that we can't output XML code directly to the ODT from the substitution function.

**Comment by eldy** [comment]
Yes, i prefer the alternative of using  $parameters['odfHandler'] = $odfHandler into  doc_generic_odt.modules.php
Usage of $parameters array was designed for this.

**Comment by lrq3000** [comment]
Okay new commit released. This pull request is updated, please take a look and tell me if everything's alright now.

**Comment by lrq3000** [comment]
Hello,

Sorry for the delay. I checked the change, but unluckily, it is not sufficient: the problem is that the ODF segments (products lines) need to be processed all at once. Once a segment is generated, it cannot be modified with this library as far as I know, thus, there either needs to be a hook per products line processing, or either add $odfHandler in the $parameters array in the complete_substitution_array_lines() as I did.

Both are equally valid, so what would you prefer?

**Comment by eldy** [comment]
Hum. What i can say is having odfhandler into sub function is burk. So i
prefer hooks. I suppose you plan to add hook just after the call of sub
function ? If yes it looks to be the good solution.

**Comment by lrq3000** [comment]
Whether the hook is placed after or before the completearray function call
does not matter, as long as it is placed inside the ODT segment loop.

I will do a new patch with your specifications as soon as possible.

2013/2/8 Laurent Destailleur notifications@github.com

> Hum. What i can say is having odfhandler into sub function is burk. So i
> prefer hooks. I suppose you plan to add hook just after the call of sub
> function ? If yes it looks to be the good solution.

**Comment by eldy** [comment]
Hum. What i can say is having odfhandler into sub function is burk. So i
prefer hooks. I suppose you plan to add hook just after the call of sub
function ? If yes it looks to be the good solution.

**Comment by lrq3000** [comment]
Closing this pull request, a new one has been done:
https://github.com/Dolibarr/dolibarr/pull/798

**Pull request closed without merging**
