### PR TITLE
FIX ADHERENT_LOGIN_NOT_REQUIRED

### PR DESCRIPTION
**Pull request by ptibogxiv**
false fields need and bad (inverse) view of login/password field

### CODE REVIEW

**Comment by hregis** [comment]
@ptibogxiv 
your tests is wrong !

**Comment by hregis** [comment]
@ptibogxiv 
example : 

```
if (!empty($conf->global->ADHERENT_LOGIN_NOT_REQUIRED))
{
   print '<tr><td><span class="fieldrequired">'.$langs->trans("Login").' / '.$langs->trans("Id").'</span></td><td>...........
}
```
if (!empty($conf->global->ADHERENT_LOGIN_NOT_REQUIRED)) == login not required
but there you display the required fields while you say that it is not required!

**Comment by ptibogxiv** [comment]
i don't fix too but you may fix the admin member panel which don't set, save and keep correctly this settings too ;) and when a member is link to a user, a blank required field error occur...

with a fix - a correct yes /no form in admin panel, yes create a constant and no delete it; so the name of this constant is not correct (should be ADHERENT_LOGIN_REQUIRED) and is non uniform in his behaviour in these files

**Comment by hregis** [comment]
@ptibogxiv 
it seems to me that this has been fixed in the develop branch

**Comment by ptibogxiv** [comment]
@hregis i will see it and get some feedback with develop branch

**Comment by ptibogxiv** [comment]
@hregis i upgrade and test with my demo install. bug is always present.

**Comment by ptibogxiv** [comment]
in ligne 165 (develop branch) in admin.php replace by to correct the form
print $form->selectyesno('ADHERENT_LOGIN_NOT_REQUIRED',(! empty($conf->global->ADHERENT_LOGIN_NOT_REQUIRED)?$conf->global->ADHERENT_LOGIN_NOT_REQUIRED:0),1);

after the behaviour of login field is the opposite that it shoud be (required and present when disabled and disabled when required is set...) 
so this function must be inverse oor traduction in french change ;)

**Comment by eldy** [comment]
The problem may be the name of the constant.
ADHERENT_LOGIN_NOT_REQUIRED means we need a login when it is set to 1 (see setup of member module).

Can you describe a way to produce the bug ?

**Comment by ptibogxiv** [comment]
@eldy You can produce the bug, in mode login/MP not required and not display, when updating a member who is link to a user and society (member without blank  login and MP ) you will have in last v7 and V6 an error with - "" required fields -

**Pull request closed without merging**
