### PR TITLE
FIX #30670 late invoice search option (v19)

### LINKED ISSUE #30670: Too late invoice filter is not working in version 19.0.02
### Bug

The filtering for too late invoices is not working anymore.

Example
The start page, shows that there are 20 too late invoices.
But when I click onto the 20, all invoices are showed, that have been ever entered to the system.

### Dolibarr Version

19.0.2

### Environment PHP

_No response_

### Environment Database

mysql

### Steps to reproduce the behavior and expected behavior

_No response_

### Attached files

invoiceProblem

### PR DESCRIPTION
**Pull request by W1W1-M**
# FIX #30670 late invoice search option (v19)
Fixes broken search option for late invoices

### CODE REVIEW

**Comment by hregis** [comment]
@W1W1-M you change just the name of variable ! Where is the broken feature?

**Comment by W1W1-M** [comment]
> @W1W1-M you change just the name of variable ! Where is the broken feature? 

I also changed the key used in GETPOST. I changed the variable name in order to comply with clean code principles, the rest of the code base and also the fix that already exists in v21.

**Comment by hregis** [comment]
@W1W1-M sorry but, how will the name change correct a broken feature here?

**Comment by W1W1-M** [comment]
> @W1W1-M sorry but, how will the name change correct a broken feature here?

Ah, unless I'm mistaken the menu link from home page is using search_option and not search_late for the post variable. Hope this clears things up 😃

**Pull request merged**
