### PR TITLE
NEW Add hidden option INVOICE_CREDIT_NOTE_STANDALONE to allow to create credit note without invoice

### PR DESCRIPTION
**Pull request by atm-maxime**
and option to allow credit note without relation to an old invoice.

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Good luck justifying that to the tax authorities!
Any comments @aspangaro?

**Comment by aspangaro** [comment]
@rdoursenaud You're right, it's problematic with the tax authorities. I see only one possibility with this option : create a credit note when the invoice are in another system (Changing ERP)

**Comment by aspangaro** [comment]
It's maybe dangerous but if it's only an option, it must be interessant for integrator I think.

**Comment by simnandez** [comment]
For this case (create a credit note when the invoice are in another system (Changing ERP)), I thinks the best is add a input text for introducing the related invoice number

**Comment by aspangaro** [comment]
@simnandez Yes good idea :+1:

**Comment by eldy** [comment]
I agree with warning. Such feature should be visible only for very experienced and integrator because it introduce way of using that is not compliant with accountancy rules. So i prefer to have this as a hidden feature. Also an input field if option is set is required to enter ref of related invoice.

**Comment by atm-maxime** [comment]
Hey. Thanks for your reactions. I agree there's the case of credit note on an old invoice from another software. But I have also another use case.
A customer of mine told me that at the end of the year, for their customers, they create a credit note which represent X % of the customer's turnover on the whole year. Say a customer bought for 100K in the year, he will have 5K of credit note if they agree for a 5% discount.
Is he misleading me ?

**Comment by eldy** [comment]
Are you sure for such case, it is a credit note ? I think it is just a commercial discount ?
So it must be just a fixed discount with no need to be tracked into accounting on both sides (it does not cancel anything).

**Comment by aspangaro** [comment]
@atm-maxime has right, I didn't think of that.

In the case of BFA or RFA in France, we can have a credit note for a period with a % defined by the customer's turnover on the whole year.

Ok for me but with an hidden option maybe. The cases are rare.

**Comment by atm-maxime** [comment]
I just had a chat with my customer and he confirms that every quarter they create a credit note that is 11% of the customer turnover for the last quarter. Seems to be usual in the GMS industry.

I'll add a hidden option allowing that so others are not bothered by this :)

**Comment by rdoursenaud** [comment]
@atm-maxime If I was to be picky (And you know I always am) I'd say that the credit note is not unrelated to other invoices but related to all the invoices of the quarter at once ;) Don't know if implementing this relationship is worthwhile though…

**Comment by eldy** [comment]
So waiting the hidden option to validate.

**Comment by eldy** [comment]
@atm-maxime Don't forget to resubmit with hidden option.

**Comment by atm-maxime** [comment]
Should be ok now ?

**Pull request merged**
