### PR TITLE
fix actionbuttons on editline or presend

### PR DESCRIPTION
**Pull request by cfoellmann**
fix behavior of action buttons and linked documents table when presend or editline

### CODE REVIEW

**Comment by eldy** [comment]
I don't understand the diff. Can you provide a screenshot of what it fixes ?

**Comment by cfoellmann** [comment]
I streamlined the display of elements when you are in `presend` or `editline`.
The main action buttons should be removed when you are in the "send email" or "edit line" screen. This way a user does not jump to another action and realizing afterwards that the change (that was not saved or sent) is gone or was not executed.


Example contrat/card.php:

# Before:
image


# After:
image

**Comment by cfoellmann** [comment]
more significant issue on `fourn/commande/card.php`

# Before:
image


# After:
image

**Comment by cfoellmann** [comment]
@eldy I redid the change and force pushed to catch up with the current develop branch

**Comment by cfoellmann** [comment]
@eldy it is very hard to keep this up to date.
Merging this is a bi***.

What is the blocker? If this will be merged I will make a refresh for the changes

**Comment by cfoellmann** [comment]
@eldy redone for current develop. It is just 2 minor corrections

**Pull request merged**
