### PR TITLE
Added link to multi-origin invoicing on thirdparty page

### PR DESCRIPTION
**Pull request by atm-maxime**

### CODE REVIEW

**Comment by simnandez** [comment]
I think it's better to show or activate the button only when multiple customer orders are billable

**Comment by eldy** [comment]
I agree with simnandez. We should have link clicable only if there is orders to invoice. 
If not, tooltip must be "No orders to invoices" and link not clicable.
Can you add this ?

**Comment by atm-maxime** [comment]
I'm working on it :)

**Comment by atm-maxime** [comment]
I think it's better I close this pull request, the first commit was included in the pull request #431.
I'll make a new one on develop for the cosmetic correction.

**Pull request closed without merging**
