### PR TITLE
Fix: User id correction on holiday request

### PR DESCRIPTION
**Pull request by fmarcet**
Fix: The user who manages the request and the user requesting the vacation was not done correctly. When comparing if a user had already requested vacation in a period, it checks the vacation of the user who was doing the management instead of the user who asked for the vacation.

### CODE REVIEW

**Comment by eldy** [comment]
I think if we keep name userid for both (even if we mix uppercase and not), we may still experience errors in future.
Other pages use this convention:  current user is $user so userid
For user we edit/request, can you use   fuserid  ?

**Comment by fmarcet** [comment]
Changes made @eldy !

**Comment by matll42** [comment]
Hi, about the ticket referenced just above #7358, we noticed a problem that this PR may be the cause. `fuserid` on line 684 is no longer initialized (only on line 59 by a GET or POST data Inside a conditional), and a user that don't have full rights (only CRUD for himself not for all) on Holiday module can't create a request anymore (no pb fur a full rights user).
If we initialized it like it was before, it works (just replaced `userid` by `fuserid`)
```
$fuserid = GETPOST('fuserid')?GETPOST('fuserid'):$user->id;
```

But this PR was made to avoid another problem, so I don't know why it was deleted. Can we let the initialization just before the test without risk ? or can a side-effect occured ?

## Environment
- **Version**: 5.05
- **OS**: Ubuntu 16.04.3
- **Web server**: Apache 2.4.18
- **PHP**: 7.0.22
- **Database**: MySQL 5.7.19
- **URL(s)**: /holiday/card.php?action=request&leftmenu=

**Comment by fmarcet** [comment]
You were right @matll42 . Thanks for the note! Corrected on #7459

**Pull request merged**
