### PR TITLE
Missing trad

### PR DESCRIPTION
**Pull request by grandoc**

### CODE REVIEW

**Comment by marcosgdf** [comment]
That translation does not convince me... Wouldn't be better "for sale" instead of "on sale" and "on purchase" instead of "on buy"?

**Comment by rdoursenaud** [comment]
I made a better suggestion in my older PR : https://github.com/Dolibarr/dolibarr/pull/1607/files#diff-96c15cb69c13e0e9e25f447f0fe12dfeR31

**Comment by eldy** [comment]
Does this means this PR can be closed (because already addressed by PR https://github.com/Dolibarr/dolibarr/pull/1607/files#diff-96c15cb69c13e0e9e25f447f0fe12dfeR31 ?)

**Comment by rdoursenaud** [comment]
I think so.
You may want to cherry pick the typo fix  though https://github.com/grandoc/dolibarr/commit/2ce36aafc6c072706d042f06e5c03536203bec7f

**Pull request closed without merging**
