### PR TITLE
Can choose several fields to display with extrafield list of table

### PR DESCRIPTION
**Pull request by jfefe**
Fields now accept to display several fields in label for extrafields table list.
For example with value table:code|libelle:rowid it's display code[:space:]libelle in select list (better only one field...)

### CODE REVIEW

**Comment by simnandez** [comment]
3.4 is freeze and are only applied bug fixes and translations

**Comment by eldy** [comment]
Good answer juanjo :-)

**Comment by jfefe** [comment]
Nothing ventured, nothing gained :)

I thought it would happen as it is a continuation of implementation of extrafields and it's very useful for user when he use long list (NAICS codelist for example)

**Comment by eldy** [comment]
Usefull is not an argument to include a change into a freezed version.
I don't think it is a continuation in the definition of a freeze version ("continuation for a freeze" means something included fails because work was not finished).
A lot of tests were already done and we can't accept to ask all testers to restart ther work to test non regression because we added a new feature.
So, please, can you push into dev branch (or if you need for a customer, you can cherry-pick it into 3.4_backported) ?

**Pull request closed without merging**
