### PR TITLE
NEW add State/Province origin for products

### PR DESCRIPTION
**Pull request by ptibogxiv**
usefull for food, fruits or vegetables  or regional product

soon in other PR i will push filter by state or country in product list

### CODE REVIEW

**Comment by dolibit-ut** [comment]
Hello,

i am unsure, what you mean with **state** 
because you speak about foods ... and regional products.

Do you mean the state = condition (of perishable goods)
(so i think)

or the state => county = region?


with best regards
Udo

**Comment by ptibogxiv** [comment]
state in dolibarr .... sub location of a country ie oregon, ile de france... 
Departement or canton in french

we use the llx_c_departements table in dictionnary

**Comment by dolibit-ut** [comment]
but we have also a **table  llx_c_regions**   

and _state_ is not usual used for region - but for federal state/country
or even used for condition / status 
and this ambiguity leads to misunderstandings, that should be avoided

regions is a clearer but broader concept than state 

state is in some countries a political defined area - but if we think about organic regional agriculture
the attribute should be more a (smaller) geographical value

**Comment by ptibogxiv** [comment]
This pr introduce no New value, it's the strictly the same as thridparties code with country and optionnel state value

**Pull request merged**
