### PR TITLE
Remove full descriptions from the product list in the contract card

### PR DESCRIPTION
**Pull request by daamien**
Hi guys !

We've been using the "contract" feature since a few weeks now. It's usefull but the card/fiche pages are too long  because:

a/ we have a lot of product in our contracts 
b/ our product have very long descriptions 

Display the entire description of each prpduct is not usefull at all and it take a lot of rooms on the page.

I'd like to remove it so that the contract card would be more consistent with propal and invoice pages....

Regards,

### CODE REVIEW

**Comment by atm-maxime** [comment]
Hey !
The idea is excellent, but I think you should have a test to display or not the full description.

In the Product / Service module configuration, you can define if the full description is displayed or available as a tooltip (see the PRODUIT_DESC_IN_FORM constant). I think you should try to reproduce the same behaviour on the contract card line display.

Cheers

**Comment by daamien** [comment]
ok why not... Here's the new patch

I'm a bit confused by the number of hidden constants such as PRODUIT_DESC_IN_FORM 

Afaik there's no documentation about them and I don't see the point if the average dolibarr admin doesn't even know about them. 

Any way thanks for your help. Is there any chance that this patch will be pushed to the 3.7 branch ?

**Comment by atm-maxime** [comment]
Hey.
This is not a hidden option, this is a configuration in the product module.
To know the list of hidden option, you can have a look here : http://wiki.dolibarr.org/index.php/Setup_Other#List_of_known_hidden_options.
I don't know if this could go into 3.7, on of the 2 yodas will decide ( @eldy @simnandez )
Bye

**Comment by daamien** [comment]
ok ! 

Thanks for your help and for the link :)

**Pull request merged**
