### PR TITLE
NEW Sending email can also use the STARTTLS protocol.

### PR DESCRIPTION
**Pull request by jtisseau**
# New [Add a STARTTLS authentication mode]

This pull request goal is to add a STARTLS authentication mode for sending emails.

The STARTLS authentication mode is used by Microsoft Hotmail and Exchange (with or without Office 365). It may also be used by other servers.

What is STARTTLS ? It start like an unprotected connection and then ask the server to protect it by sending the `STARTTLS` command. It doesn't use the `ssl://` prefix.

A new const is added `MAIN_MAIL_EMAIL_STARTTLS` which behave like the `MAIN_MAIL_EMAIL_TLS` const. It can be modified through `admin/mails.php` and the core functionality is made in `core/class/smtps.class.php, _server_authenticate` function. Nothing else is changed regarding SSL or unprotected connection.

### CODE REVIEW

**Comment by jtisseau** [comment]
The Travis CI build failed with PHP 5.4 on database init but not on 5.3, 5.5 nor 5.6. Why ?

**Comment by eldy** [comment]
Travis error is just a server that hangs. Nothing to worry.

You don't have to change all language files. Only the en_US. Other language files will be translated magically by transifex translators if en_US is updated.

Just a question. Can you tell me example of SMTP services you can say "it works with" ? so i can update the wiki here:  https://wiki.dolibarr.org/index.php/Setup_EMails#Usage_of_TLS_.28SSL.29

What happens if we set TLS and STARTTLS both to yes ?

**Comment by jtisseau** [comment]
I tested it with smtp.office365.com (Microsoft Office 365, Exchange Server).and smtp-mail.outlook.com for Microsoft Hotmail/Outlook.com

**Comment by jtisseau** [comment]
I didn't know for translations, I will for future pull.

I just discovered Dolibarr and really love it. I'd like to help, where can I find features needing development ?

**Comment by jtisseau** [comment]
Thanks to jQuery, TLS and STARTTLS can't be both set to yes : I added two functions to unselect TLS if STARTTLS is selected and to unselect STARTTLS if TLS is selected. But manually unselecting one option won't select the other, this to allow unprotected connection.

If someone set both values directly in DB : 
- if it's a STARTTLS server, it won't connect because of the `ssl://` prefix added by the TLS option.
- if it's a TLS server, I haven't tested but I think it will connect but could fail on authentication due to the `STARTTLS` command send, or due to the `stream_socket_enable_crypto` function called after. If both pass then authentication will pass as usual.

**Comment by eldy** [comment]
To respond your question where can I find features needing development ?

What me miss the most is bug fixers to fix bugs declared and visible here:

https://github.com/Dolibarr/dolibarr/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+bug

**Pull request merged**
