### PR TITLE
Update fiche.php

### PR DESCRIPTION
**Pull request by defrance**
wrong value : 
1 = customer
2 = customer/prospect
3 = prospect

### CODE REVIEW

**Comment by defrance** [comment]
Ok for the currect rule, but it's for the prospect tab navigation
so the right filter must be 2,3
for the customer tab they must be 1,2

**Comment by eldy** [comment]
Yes, this rule
"so the right filter must be 2,3
for the customer tab they must be 1,2"
is ok.

But i think there is no more prospect tab and customer tab. They were merged. Did i miss something ?

**Comment by defrance** [comment]
No you have 3 tabs : customer only / prospect/customer / prospect only
This filter is very usefull when you list all the prospect for made a phone-calling operation :
you call the all prospect not the customers and made "next" to go to the next prospect

**Comment by eldy** [comment]
Fix added manually

**Pull request closed without merging**
