### PR TITLE
NEW : add tables in database for product return management

### PR DESCRIPTION
**Pull request by altairis-tof**
this is first commit to add product return management to dolibarr core.
other PRs to come...

### CODE REVIEW

**Comment by altairis-tof** [comment]
Hello, si quelqu'un qui parle le Travis passe par ici ? @frederic34 ? @eldy ?

**Comment by hregis** [comment]
@altairis-tof

date_valid timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

**Comment by altairis-tof** [comment]
> @altairis-tof
> 
> date_valid timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

Merci @hregis ; il faut rajouter ça partout sur mes tms c'est ça ?

**Comment by hregis** [comment]
@altairis-tof oui c'est pour être compatible avec les versions récentes de mysql qui contient une option pour activer ou pas ces paramètres lors de la création d'un champ timestamp

**Comment by altairis-tof** [comment]
merci @hregis c'est fait; Travis est en train de vérifier tout ça... si seulement il ne pouvait afficher que les erreurs dans sa log...

**Comment by altairis-tof** [comment]
everything is ok :)

**Comment by eldy** [comment]
What is a product return ?
A reception of product that increase the stock ? It can also be a negative shipment.

I don't think we need a new object for this business case as we already have a process for shipment and reception. 
Also a "return" is probably in relation with an order ?

**Comment by lmag** [comment]
Return vouchers are linked to customer orders and not to supplier orders. Managing return vouchers opens up many possibilities

- Short and long term rental
- Equipment loan
- Return for after-sales service
- Management of the return flow (Broken, defective, after-sales service, etc.)

**Comment by altairis-tof** [comment]
Hello @eldy , the return module allows merchandise return from customer.
It increases stocks, allow to comment and add documents, and even make credit notes if needed.
in the future it will also manage RMA (return merchandise authorisations).
You might look at this issue : https://github.com/Dolibarr/dolibarr/issues/20504
or at this thread on the forum : https://www.dolibarr.fr/forum/t/gestion-de-retour-des-produits/20922

**Comment by altairis-tof** [comment]
The module is already in Dolibarr production of several companies and is about to be sold on Dolistore to finance cost of integration in Dolibarr core as expected by @lmag and other people (see issue or forum)

**Comment by eldy** [comment]
The module add new tables to manage a process that already exists: Managing shipment and reception.
This is a good choice for an externa module but for the core, this generates duplication of data, and duplication of code for a process very similar.
In such a situation, extending existing tables of reception is a better direction to add the feature of return management.

**Comment by altairis-tof** [comment]
@eldy i am not very found of storing customer related data into supplier related database tables.

**Comment by lmag** [comment]
You mean : @eldy @altairis-tof 
Use table commande_fournisseur_dispath

- [ ] Change the name of this table ?
- [ ] Add Element_Type
- [ ] Add fk_element
- [ ] Add fk_element_det
- [ ] Transfert fk_commande to fk_element
- [ ] Transfert fk_commandefourndet to fk_element_det

In Table reception

- [ ] Add type from element_type (name of the objet "commandefourn,expedition")

**Comment by altairis-tof** [comment]
I am not very found of having database tables that store elements of different natures.
if we go in this way, we will store proposal, order, invoice, shipping, reception, return data in only 2 tables (llx_element and llx_elementdet) like wordpress (wp-post and wp-meta) with consequences in term of performance, support ability, and so on.

**Comment by eldy** [comment]
> You mean : @eldy @altairis-tof 
> Use table commande_fournisseur_dispath
> 
> - [ ] Change the name of this table ?
> - [x] Add Element_Type
> - [ ] Add fk_element
> - [ ] Add fk_element_det
> - [ ] Transfert fk_commande to fk_element
> - [ ] Transfert fk_commandefourndet to fk_element_det
> 
> In Table reception
> 
> - [x] Add type from element_type (name of the objet "commandefourn,expedition")

There is no need to add fk_element and fk_elementdet. We already have column fk_commande and fk_commandedet. However, this 2 fields should be renamed in future into fk_element and fk_elementdet to make name of fields  easier to understand.
Field element_type has been added for v19.

Renaming table commande_fournisseur_dispath into llx_receptiondet_batch would be also a good renaming step to make code easier to understand.

There is no need for column addition into llx_reception. Like what we have for shipment, the link between reception or shipment with a purchase order or a sale order is done using llx_element_element. It can be used to be linked to a propals, or any object.

**Comment by FHenry** [comment]
@eldy let's imagine we rename the table  commande_fournisseur_dispath into llx_receptiondet_batch, should we put in the same PR the rename of the class CommandeFournisseurDispatch everywhere or do you suggest to just change the table_element property of CommandeFournisseurDispatch

**Comment by eldy** [comment]
> @eldy let's imagine we rename the table  commande_fournisseur_dispath into llx_receptiondet_batch, should we put in the same PR the rename of the class CommandeFournisseurDispatch everywhere or do you suggest to just change the table_element property of CommandeFournisseurDispatch

The smaller are PR, the better they are. So we can 2 steps: 1 PR to rename table. 1 to rename class (i suggest to keep a class with name CommandeFournisseurDispatch that herits the one with the new name to keep compatibility of code).

**Comment by altairis-tof** [comment]
@eldy i am about to start the rename of commande_fournisseur_dispatch into llx_receptiondet_batch but this will either be a small PR (with only the rename BUT nothing will work until we modify scripts that use the table) or a big PR with all the scripts update... **what do you prefer ?**
i also note that we will also have to rename the table commande_fournisseur_dispatch_extrafields (and the scripts that use it)...

**Comment by altairis-tof** [comment]
other point, i feel uneasy with llx_reception and llx_receptiondet_batch without any llx_receptiondet

**Comment by altairis-tof** [comment]
i close this PR and start another one for renaming of commande_fournisseur_dispatch (and extrafields).

**Comment by altairis-tof** [comment]
first PR here : https://github.com/Dolibarr/dolibarr/pull/27528

**Pull request closed without merging**
