### PR TITLE
add an option to instantiate the new line on the intervention card with the current time

### PR DESCRIPTION
**Pull request by SylvainLegrand**

### CODE REVIEW

**Comment by thomas-Ngr** [comment]
More info:

Current behavior:
When creating a fichinter line, the date is pre-filled on current date but time is set on 00:00.

This PR introduces an option to pre-fill the time on current time when creating a fichinter line.

**Comment by SylvainLegrand** [comment]
This option increase the user experience of intervention card.
May you have a look on it ?

Thank's.

**Comment by SylvainLegrand** [comment]
Intervention standard

After the PR the current time is set
Intervention improved

**Comment by SylvainLegrand** [comment]
@eldy 

Would you be so king with me to check this PR ?
Thanks.

Best regards.
Sylvain.

**Pull request closed without merging**
