### PR TITLE
Fix bug 1298 : category nav on member

### PR DESCRIPTION
**Pull request by atm-maxime**
```
modified:   htdocs/categories/categorie.php
```

### CODE REVIEW

**Comment by atm-maxime** [comment]
Bug 1293 was about numbering. When mask contains fixed data the same as var daa (eg FA000{000}) the numbering failed

**Comment by marcosgdf** [comment]
Changelog, changelog! :laughing: 

Also, bug of numbering shouldn't be pr'd to 3.5 branch?

**Comment by atm-maxime** [comment]
Hey Marcos !
Watching the work we are doing ? :D

I guess we will add everything that wil be done during devcamp into
Changelog at the end because it makes conflicts if everybody modifies the
changelog...

See you :)

Bien cordialement,

## 

_Maxime KohlhaasConsultant associé *_ATM Consulting*
_+33 6 33 42 92 43_

2014-03-14 23:58 GMT+01:00 Marcos García notifications@github.com:

**Comment by marcosgdf** [comment]
Haha I received the bug 1293 fix notification and just wanted to have a look...  didn't remember you were in DevCamp! But... (i edited the comment) what about pushing the bugs to 3.5 branch instead of develop? At least the 1293 bug :P

**Comment by atm-maxime** [comment]
Yeah you're right, I'll see to have it done on 3.5

**Pull request merged**
