### PR TITLE
FIX: Saving wrong localtax on order addline

### PR DESCRIPTION
**Pull request by fmarcet**
Saves the localtax rate regardless of whether or not it should be applied on the line.

### CODE REVIEW

**Comment by eldy** [comment]
Hi @fmarcet 
I need your help to understand this as some things looks strange to me in this fix.
First, do you know if problem exists with 6.0 ?
If yes, can you provide an example on how to reproduce the bug with example of data obtained versus expected.

**Comment by fmarcet** [comment]
Hi @eldy 

We found this error when using one of our external modules. In a Dolibarr without external modules, apparently there is no error, but we notice that an erroneous value is stored in the database.

To reproduce:
Dolibarr company: Spanish using VAT but no other localtax
deepinscreenshot_seleccionar area_20180102095350

Customer company: Spanish

When we add a line, all seems ok:
deepinscreenshot_seleccionar area_20180102095541

But if we look at the line in the database, we see that it has added a value in the localtax1_tx column (5.2)
deepinscreenshot_seleccionar area_20180102095734

We do this commit by looking at the addline function of the invoice class (facture.class.php) that doesn't save any wrong value in the database.

Although the user doesn't see any wrong value on the screen, we think that the correct thing is to store it well in the database since an external module could make use of this information obtaining erroneous results. It occurs in both Dolibarr 5 and Dolibarr 6

**Comment by eldy** [comment]
The parameter $txlocaltax1 and $txlocatax2 is deprecated, so we must find a fix that does not depends on this parameters so the fix will be ready for future.
I suggest the fix in this commit 0fb95fa15f4afdc86f9afbf87d97ede6780c7092
Can you test and confirm it works for you as expected ?

**Comment by fmarcet** [comment]
@eldy I test it and works as expected :+1:

**Pull request closed without merging**
