### PR TITLE
Fix supplier deposit can not be used to pay supplier invoice

### PR DESCRIPTION
**Pull request by SylvainLegrand**

### CODE REVIEW

**Comment by SylvainLegrand** [comment]
When a supplier requests a deposit, it is paid and transformed into an exceptional discount.
When you use this discount to pay all or part of the supplier's invoice, it is not deducted from the amount remaining due on the invoice.

**Comment by eldy** [comment]
A deposit of 10 euros must not be deducted from the remain to pay of an invoice of 100 euros but must be deducted from the total on the remaining invoice (so second invoice must be 90 euros with a remain to pay of 90 euros, not 100 euros with already paid 10 euros).
Because a deposit is an invoice and is already counted into the turnover and must not be counted twice, you must have 1 invoice of 10 for the deposit and 1 invoice of 90 euros for the second invoice. So a deposit must be included as a item of -10 in the second invoice so invoice is 90 euros and not as a payment of 10 euros on an invoice of 100.

**Comment by josett225** [comment]
Hi @eldy and @SylvainLegrand 

There is already 2 opened issues (if I am not wrong), could you please review the following content :
https://github.com/Dolibarr/dolibarr/issues/19724
https://github.com/Dolibarr/dolibarr/issues/20226

I already discussed with accounting expert and it seems both solutions could work. 
Main issue in Edly's behavior is the fact that the displayed margins are wrong as the deposit is used as a product line. See issue #19724. All invoices are either in 707 or 607 account classes.
In the meantime Sylvain's behavior works well as the Deposit is used like a payment after correcting the code in v14  (in V15 the setup has also to changed with FACTURE_DEPOSITS_ARE_JUST_PAYMENTS set to 1). Deposit invoices are in 409 or 419 accounting classes and final invoice is 707 or 607. 

As I am not expert as you are,  I let you comeback  with your thoughts/directions.

Best Regards

Jose

**Comment by eldy** [comment]
currently, there is no known problem of margin shown when using the default solution (so when FACTURE_DEPOSITS_ARE_JUST_PAYMENTS is 1) :  Don't forget that the deposit is an invoice, so you have a part of the margin in this invoice too, and another part of the margin in the final invoice. You must take into account the 2 invoice to get a good idea of the complete margin. 
If you think you experience problem in margin in default mode, thanks to paste a view of invoice (lines and margin section) for both the deposit and the finale invoice.

When using the other mode (when FACTURE_DEPOSITS_ARE_JUST_PAYMENTS is set to 1), may be there is margin trouble, this mode is deprecated. A lot of accounting feature can't work correctly in this mode. Note that to get a similar behaviour on purchase/supplier side, the option will be FACTURE_SUPPLIER_DEPOSITS_ARE_JUST_PAYMENTS but this option is introduced in v16 only (also a hidden feature because not the recommended way to work).

For the way to make accounting on deposit, having the deposit moved first into 409 or 419 for the deposit of 10 euros instead of 401 and 411 and then transferred later into 401 or 411 does not depends on the fact you use FACTURE_DEPOSITS_ARE_JUST_PAYMENTS to on or not. 
Currently, with a minimal setup, Dolibarr transfers the first 10 euros of deposit invoices directly in 401 or 411 and the remain of final invoice of 90 into 401 or 411 too, for a total of 100. The feature to transfer "firstly" in 409 and 419 and then moving this into 401 or 411 at the same moment we add the final 90, is implemented only if you set a "Default deposit account" to 419 into menu Home - Accounting - Setup - Default accounts). So, the use of 419 instead of 411 for deposit depends on this setup and not on deprecated option FACTURE_DEPOSITS_ARE_JUST_PAYMENTS. It is available for sale invoice only. Also note that you have to manually move amount from 419 to 411 (i think but i am not sure, i never use this setup).

**Pull request merged**
