### PR TITLE
add missing trigger ORDER_SUPPLIER_DISPATCH 

### PR DESCRIPTION
**Pull request by cfoellmann**
add missing trigger ORDER_SUPPLIER_DISPATCH to fire when a supplier order is received.

### CODE REVIEW

**Comment by fappels** [comment]
Did you try trigger 'ORDER_SUPPLIER_SUBMIT'?

**Comment by cfoellmann** [comment]
> Did you try trigger 'ORDER_SUPPLIER_SUBMIT'?

My description above was false (changed now). My trigger is NOT for when the order is sent to the supplier BUT for when the products arrive,
We send a notification to the creator of the supplier_order to tell that the items have arrived.

Should be merge because there really is no trigger firing at that point

**Comment by fappels** [comment]
$object->Livraison also calls trigger ORDER_SUPPLIER_RECEIVE
ORDER_SUPPLIER_DISPATCH trigger is called in dispatch.php but do not understand why. Just before $object->calcAndSetStatusDispatch also is called. This one also calls ORDER_SUPPLIER_RECEIVE. So think ORDER_SUPPLIER_DISPATCH is obsolete.

**Comment by cfoellmann** [comment]
Thanks. You are totally right.

I don't know why I didn't see this.

**Pull request closed without merging**
