### PR TITLE
Extrafieldsedit

### PR DESCRIPTION
**Pull request by rdoursenaud**
Fixes https://doliforge.org/tracker/?group_id=144&func=detail&atid=246&aid=1594

### CODE REVIEW

**Comment by eldy** [comment]
We currently have form inside a /tr and another tr for fourn/commande/card.
This makes some javascript function crazy, break standard and compatibility with jquery mobile.

It seems to be already the case before. Things seems to be correct into customer commande/card.

Does you PR keep this correct into proposal, customer orders ?

**Comment by rdoursenaud** [comment]
@eldy Don't understand what you're talking about. You can inspect my changes on GitHub in the "Files changed" tab to see if they fit your requirements or not.

**Comment by eldy** [comment]
I pushed a fix on what i was speaking about. So you don't have to worry about my comment anymore. However, solving conflict is now required.

**Comment by eldy** [comment]
A patch was submited by atm, and included into dev branch, that seems to make same thing than patch https://github.com/Dolibarr/dolibarr/pull/1918

If i am right, can we close the ticket ?

**Comment by atm-maxime** [comment]
I have checked and it seems to be ok to me. Just made a new PR because I wasn't dealing with rights.

**Comment by rdoursenaud** [comment]
Much better fix from @atm-maxime. Thanks!
Just missed a small fix I PR'd in #1999.

**Pull request closed without merging**
