### PR TITLE
New #23449 Limited duration (deliverytarget) for services and also for products too

### PR DESCRIPTION
**Pull request by Humml87**
See Feature Request: #23449

Impression:
image
image

### CODE REVIEW

**Comment by eldy** [comment]
This looks strange. The differencebetween a product and a service is that when there is a limit duration, the oroduct is in fact a service. So why having limit duration on product ?

**Comment by Humml87** [comment]
Hi @eldy, 
as example, you have a customer order with different products. The customer need the products on different dates.
Or:
You order some products, but you like the products on different dates.

It's better to rename 'Limited duration' to 'Delivery time' if it's a product? 
I hope you understand my mind. 
Best regards!

**Comment by hregis** [comment]
@Humml87 you can add extrafields !

**Comment by Humml87** [comment]
> @Humml87 you can add extrafields !

Hi, I think it is not a good idea. As example we create a report for expected sales volume, then you need the values in the same column.

Please let me know, wath the foreseeable problem of this PR is.

**Comment by hregis** [comment]
@Humml87 you can create a module with custom "/core/tpl/objectline.*.tpl.php" templates

**Comment by Humml87** [comment]
Hi eldy, hi hregis,
now i understand your problem with this PR. Joachim from the german community helping me to understood this.
@hregis thanks for the tips.
Best regard!

**Pull request closed without merging**
