### PR TITLE
migrate font awesome to 5.4.1

### PR DESCRIPTION
**Pull request by laudeco**
migrate the font awesome to the latest library in the idea to use the last one (more complete) to use font awesome icons instead of images.

Font awesome 5.4.1 is lighter than the previous loaded version.

To migrate I followed those steps: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4. And since I'm also importing the shims file all previous icons must still work. I tested most of them and it works.

Can also enter in the ticket #9429 .

### CODE REVIEW

**Comment by laudeco** [comment]
The next step would be migrate to a package manager for the front end, what do you think @eldy  ?

Cheer
L.

**Comment by eldy** [comment]
Because we have started the beta 9, I note this PR to be merged later as no architecture change is allowed during a beta period.

**Comment by laudeco** [comment]
> Because we have started the beta 9, I not this PR to be merged later as no architecture change is allowed during a beta period.

Ok I understand but 2 questions for you then:
1. Is it for you an architecture changes ? Since it's backward compatible for me it doesn't break anything. Anyway I respect your choice.

2. Is it ok for if I based the change of top menu icons on this PR or you prefer not, in that case the other PR must wait ...

Kind regards
L.

**Comment by john-botella** [comment]
Hello, 
@laudeco Good Idea ! I need this for menu because some picto I need doesn't exist in version 1.4.7 

For your first question, I maked the experience 3 weeks ago and some icons dont use the same "font content" (for ::before).
In facts, it's backward compatible if you use a dom element like `<i class="fas fa-arrow-up"></i>` (I use a random class for the exemple) but if you use your own class using font awesome you can experiment some glitch.

**Comment by eldy** [comment]
Any change of an external library is an architecture change.
Even if it is "compatible". It is always compatible in the text, in real life, it is not. So merge will be done after 9.0

**Comment by laudeco** [comment]
Ok @eldy ;-)

**Comment by wdammak** [comment]
> 
> 
> Ok @eldy ;-)

pending its publication, can you update to 5.5.0?

**Comment by eldy** [comment]
@wdammak i'm ready to merge. Something wrong with version 5.4 ?

**Comment by wdammak** [comment]
> @wdammak i'm ready to merge. Something wrong with version 5.4 ?


Any wrong with version 5.4.
Yes you can! :)
In the second step we go directly to version 5.6 which has just released.

**Pull request merged**
