### PR TITLE
remove Old files on upgrade

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by Arre8** [comment]
nice (thx !) , but...

why do not keep wright files instead of delete potential "old" files ?

**Comment by hregis** [comment]
@frederic34 
you are sure that all the files you delete are not used by Dolibarr or external modules !!!
example: "/langs/en_CH/propal.lang", propal.lang is used by Dolibarr !!
and many others !!

**Comment by Arre8** [comment]
ok but then ... an xml (or other file) of 'official files" should work.
not depending of a "maintened file list" in the updating-process of old files to erase... (as Frederic has done by re-updating to check)
no ?

**Comment by frederic34** [comment]
> 
> 
> @frederic34
> you are sure that all the files you delete are not used by Dolibarr or external modules !!!
> example: "/langs/en_CH/propal.lang", propal.lang is used by Dolibarr !!
> and many others !!

I remove all files that are not in 9.0, where did you find /langs/en_CH/propal.lang

**Comment by Arre8** [comment]
no... not sure ...
if you think it's the better way for all  at this moment: it's ok. 
(but i'll still think that ALL other file/développement should be in /custom and not impacting orginals files... if possible...)

**Comment by eldy** [comment]
I understand the need to clean old installation but imagine there is a file x in your list (so not in v9)
file x appears in v10 (this will surely happen with language file when translation is available for exemple).
If you make a migration from 7.0 to 10.0, after unzip files of v10 over a v7, the migration process will delete files required by the v10 during migration of v8 to v9.
For this reason, we must limit files to the one that create conflict/problems.
A full cleaning like the one suggested is however welcome inside the htdocs/install/repair.php  !

**Pull request merged**
