### PR TITLE
NEW: API can create, get and update extrafields #29249

### PR DESCRIPTION
**Pull request by JonBendtsen**
NEW setup API can get & update existing as well as create new extrafield
Second, third and fourth step in fixing #29249 though this pull request can create, get and update

### CODE REVIEW

**Comment by JonBendtsen** [comment]
@eldy I don't know how to fix the failed `CI / phan` check. I don't see any difference compared to many other post( functions in other api_*.class.php files.

**Comment by frederic34** [comment]
@JonBendtsen look here https://github.com/Dolibarr/dolibarr/blob/bc8e4c19cc6719584e46b11652fd8173928962e1/htdocs/societe/class/api_contacts.class.php#L272-L281

**Comment by JonBendtsen** [comment]
> @JonBendtsen look here
> 
> https://github.com/Dolibarr/dolibarr/blob/bc8e4c19cc6719584e46b11652fd8173928962e1/htdocs/societe/class/api_contacts.class.php#L272-L281

should that be in all post functions with request_data?

**Comment by JonBendtsen** [comment]
> @JonBendtsen look here
> 
> https://github.com/Dolibarr/dolibarr/blob/bc8e4c19cc6719584e46b11652fd8173928962e1/htdocs/societe/class/api_contacts.class.php#L272-L281

@frederic34  thanks, that worked :-)

Should that line be before all API post functions? and what about update functions?

**Comment by frederic34** [comment]
only needed to suppress phan error

**Comment by JonBendtsen** [comment]
Notice how the attrname and element name in the json are ignored and only those from the 2x single line boxes aka the URL are used.


API_setup_post_v3

**Comment by JonBendtsen** [comment]
here's the view from inside where you can see that the attrname and elementtype in the request_data are ignored.

API_setup_post_v3_dolibarr_view

**Comment by JonBendtsen** [comment]
Will fix conflicts

**Comment by JonBendtsen** [comment]
Conflicts fixed

**Comment by JonBendtsen** [comment]
get_extrafield_from_attrname_elementtype

here's the json result

```
{
  "commande": {
    "fourcode": {
      "id": "38",
      "type": "varchar",
      "label": "Fourlabel",
      "size": "255",
      "elementtype": "commande",
      "default": null,
      "computed": null,
      "unique": "0",
      "required": "0",
      "param": {
        "options": {
          "": null
        }
      },
      "pos": "104",
      "alwayseditable": "1",
      "perms": null,
      "list": "1",
      "printable": "0",
      "totalizable": "0",
      "langs": null,
      "help": null,
      "css": null,
      "cssview": null,
      "csslist": null,
      "fk_user_author": "1",
      "fk_user_modif": "1",
      "datec": "2024-04-06 15:24:23",
      "tms": "2024-04-06 15:24:23"
    }
  }
}
```

**Comment by JonBendtsen** [comment]
The existing GET that fetches all extrafields still works

image

**Comment by JonBendtsen** [comment]
@eldy in case you haven't seen, this pull request is ready again, "All checks have passed", no longer any conflict.

**Pull request merged**
