### PR TITLE
NEW modimport update option

### PR DESCRIPTION
**Pull request by atm-maxime**
Adds an option in the import module (CSV for now) that allows to select one or several fields that will be used as keys to perform an update. If UPDATE does not affect any row, then regular INSERT is done.

For now, option is available on thirdparties import, for some fields.

### CODE REVIEW

**Comment by eldy** [comment]
Did you test with pgsql ?
With pgsql, transaction management differs and if an error occured (may be an update that fails) it may reject all transactions. I think it should works too but a test is welcome

**Comment by atm-maxime** [comment]
I did not actually test with pgsql, but if the UPDATE fails, the error is logged and the module will try the INSERT.
I'll try to test it and give you feedback

**Comment by eldy** [comment]
I have reason to think the code product will not work correctly with pgsql. But this need a test to be sure.

**Comment by atm-maxime** [comment]
ok we made some tests and fixes. It wasn't working with extrafields tables.
We will finish testing, especially on pgsql during devcamp.

**Comment by atm-maxime** [comment]
Hi @eldy, merged and solved conflicts.
As discussed, the SELECT before trying to update should be compatible with PGSQL.

Currently, only thirdparties, products and product supplier prices have the update option, which will give us some feedbacks before adding this to other objects.

My only concern is that we should add a warning, saying that update is not undoable, that user should have his data saved or exported first to be able to reimport if necessary. With INSERT you can easily delete with the import_key, with an update, it's different...

**Pull request merged**
