### PR TITLE
Phone is a number only

### PR DESCRIPTION
**Pull request by BB2A-Anthony**
# New [*Phone is a number only*]
Delete other character is not number

### CODE REVIEW

**Comment by atm-maxime** [comment]
Hi. You're right, phones should be better formatted. But I think we must have the + symbol to store international format. Here was a feature request about this #4361

Don't forget phones on other objects (users, members, extrafields of type phone, ...)

**Comment by BB2A-Anthony** [comment]
> Hi. You're right, phones should be better formatted. But I think we must have the + symbol to store international format. Here was a feature request about this #4361
> 
> Don't forget phones on other objects (users, members, extrafields of type phone, ...)

Thank you @atm-maxime 

I think that the + should rather be in the display of the phone number according to the pay in function.lib.php

I look others phone number

In function.lib.php i offers next for international phone number

```
elseif (strtoupper($countrycode) == "PT")
	{//Portugal
		if ($conf->global->MAIN_PHONE_PREFIX_ADD) $newphone = "+351" . $newphone;
		if (dol_strlen($newphone) == 13)
		{//ex: +351_ABC_DEF_GHI
			$newphone = substr($newphone, 0, 4).$separ.substr($newphone, 4, 3).$separ.substr($newphone, 7, 3).$separ.substr($newphone, 10, 3);
		}
	}``
```

if ok offers modify for the others cuntry and solution for calltodial

**Comment by BB2A-Anthony** [comment]
@eldy your opignon for intenational number?

**Comment by eldy** [comment]
There is a lot of other need to store a phone number. Some usage needs to store a prefix, a suffix, sometimes we need to store an internal phone number like "A-123" or "B-456". Sometimes we need the "()", sometimes the +, the space. Sometime we need to also save a code used for password to be able to make the phone call like  '123456 (Code 5#9)", sometimes a complementary information for a CTI system,.... There is a lot of use case. For this reason, sanitizing data during insert into database is not recommended and we must keep a char value (for information, it was an integer in the past on some phone number in database and we had to change this to varchar). So if phone number match a simple rule of a fixed length number (the most common case), the sanitizing of data must be done during the output of value.
This is the reason why the dol_print_phone() function exists. We must keep that.

An interesting feature may be to have a generic feature "control format rules" feature, like we have for "default value", or "mandatory values" so we would be able to define a mask for some fields for the case you want to have the cleaner value as possible during input instead of a sanitizing of data during output. But this is a completely different feature (and we must have it for future) and it is a generic approach, not only for phone number.

**Comment by BB2A-Anthony** [comment]
thank you
Create a function in commonobject, function or funtion2?

Or one const for number is integer MAIN_PHONE_INTEGER !

**Comment by eldy** [comment]
For formatting data during output, there is already a function called "dol_print_phone"

For the feature to be able to define control rule, it must be another tab into home - setup - default values

**Pull request closed without merging**
