### PR TITLE
clean code on the common object

### PR DESCRIPTION
**Pull request by laudeco**
Hello @eldy ;

The only objective of this PR is to optimize the code base of Dolibarr by cleaning the code of the common class.

* I simplified a lot of if ... else. When there is a return in the 'if' condition you don't need the else (cf the code)
* I tried to remove unused variables
* I tried to check why this class is red (and still red) on PHPStorm 
image

If you have any concerns about this refactoring please share it. But, I think important to improve our codebase. I can explain each change I made.

### Why PHPStorm is red ?
For those who don't develop with PHPStorm. There is a flag which informs the developer about the stability of his class. If it's red it means the class has (probably) a running error. 

In our case, it's because there is some JS on the page so the PHP interpreter cannot interpret that code (that's a non issue). But it was also red because the usage of some variables that don't exist! 

So I cleaned that also.

Cheers
L.

### CODE REVIEW

**Comment by eldy** [comment]
The PR creates a regression reported by Travis that is in error.

**Comment by laudeco** [comment]
> The PR creates a regression reported by Travis that is in error.

Good catch I'll address it.

**Comment by laudeco** [comment]
@eldy I think I addressed the comment isn't it

**Comment by laudeco** [comment]
@eldy I didn't change the visibility of the variable $fields why is it failing?

**Comment by eldy** [comment]
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolete, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.

**Pull request closed without merging**
