### PR TITLE
This commit adds a way to filter projects by checking if selected year is in creation/ending range.

### PR DESCRIPTION
**Pull request by IonAgorria**
The year input is shown after the list, outside the table.

It's hidden by default and must be enabled with PROJECT_LIMIT_YEAR_RANGE

### CODE REVIEW

**Comment by IonAgorria** [comment]
Well... The "Closed projects are greyed out in project selector" commmit wasn't supposed to be here, sorry.

PD: The travis build seems to fail in a file that I didn't changed.

**Comment by eldy** [comment]
The test

$sql.= " AND (YEAR(p.datec) <= ".$project_year_filter." AND YEAR(p.datee) >= "...

must be replaced with something like

$sql.= " AND p.datec between '".$db->idate(dol_get_first_day($year,1,false))."' AND '".$db->idate(dol_get_last_day($year,12,false))."'";

2 reasons: 
- sql YEAR is not portable,
- the second way can use index on field date, not when using YEAR.

**Comment by rdoursenaud** [comment]
@Cubexed you can revert (or even better, rebase without) 6899482 if it's not supposed to be there.
Looks good to me either way.

**Comment by IonAgorria** [comment]
Thanks both for helping, I will make another pull request for 6899482

**Comment by eldy** [comment]
So PR closed. Waiting for PR with commit 6899482

**Pull request merged**
