### PR TITLE
FIX: Restore lost functionality of making a single payment for a withdrawal

### PR DESCRIPTION
**Pull request by simnandez**
Made by new option in withdrawal setup module

### CODE REVIEW

**Comment by eldy** [comment]
When you pay customer 1 for AMOUNT1 and customer 2 for AMOUNT2 in one bank transfer, you make 2 payments. So you MUST keep 2 payments in the table of payment, one for each customer.
There is a difference between the payment and the record into bank.
Yes, we should have 2 payment record and 1 into bank. and currently we have 2 payments and 2 record into bank. So i think you introduce this feature because you want only one record into the bank.

But we must keep 2 payments.

Also, having 1 bank record has a problem: If you record only 1 payment in bank, it has only one record.
Then when you will use the accounting feature "Journalize bank transaction into bank journal", what happen ? The current code currently loop on each transaction and record
one line debit for bank and one line credit for thirdparty
If there is 1 bank record for x thirdparties, the journalization will be broken.

Problem is same than when recording a check deposit of several customers.

Solution is: 
1) You record 1 payment in llx_paiement  (+detail for each invoice into llx_paiement_facture) because we must know when we pay 100, that customer X has paid 80 and Y has paid 20), we can't loose this information.
2) You record 1 bank record instead of n and you record n entry into bank_url with link for each customer
3) We enhance the feature to journalize bank record so it is able to process record in bank done for several customers (instead of making 1 debit and  credit, it should do 1 debit in bank and n credit per customer).

**Comment by simnandez** [comment]
@eldy Ok, your solution may be valid.

What is clear is, as it is now, it can not be. For example, in Spain, most banks only create one account record by withdrawal (even if there are 5000 receivable invoices) with total amount. If we in Dolibarr create the 5000 bank records, the user can go crazy to reconcile it....

**Comment by atm-maxime** [comment]
1. Not sure why you want to keep N payments. Before, we had only 1 payment for N invoices and we still knew how much each customer paid because of the link "facture_paiements"
2. Agreed, one bank line linked to N customers
3. Agreed, impovrement of accountancy jounalization

This is the same @atm-greg did for checks, this time with N payments, but only one bank line.
I suggest we harmonize all this during devcamp so we can definitely say how to deal with withdrawals and check deposits.

**Comment by eldy** [comment]
@atm-maxime I was not clear for point 1, i fix the text. I means "1 payment line into llx_payment + n lines into llx_payment_facture (for each invoice) so we can know which payment is done for each invoice, so we can know, recalculate part paid for each customer, this is what i want to keep". But this is already what we do, so that is no more the point.
So enhancement must be done on point 2 and 3.
2 - one bank line linked to N customers
3 - Improvement of accounting dispatching.

**Comment by simnandez** [comment]
I close this, I will perform another PR related to this later

**Pull request closed without merging**
