### PR TITLE
Fix default products list limit

### PR DESCRIPTION
**Pull request by azzi907**
# Fix #[_Fix for default limit for products list_]

[_Passing "" will make it to return all products list which is big issue. so i am passing 20 as default limit_]

### CODE REVIEW

**Comment by simnandez** [comment]
It is better to make the change (limit control) in the select_produits_list function,

**Comment by azzi907** [comment]
@simnandez yes that's even better.
we could check if param is empty set limit to default

**Comment by eldy** [comment]
The goal of ajax autocompletion is to not have same problem with standard combo box (where we must enter a limit to avoid too long list).
But with ajax, we can decide the number of chars before triggering the search. This is this number of chars that can be used to restrict list. And no data are lost. Introducing a limit on ajax make ajax autocompletion useless and user lost by not finding data that should be returned.

**Comment by azzi907** [comment]
@eldy 
I think you are getting it wrong way..
in Reality it would be like.
select something from products_table where label='$ourpostedtitle' order by something limit $ourpostedlimit;

so it would first find matching records and then apply limit on them and return records.

In our case query will first find out match records with limit to 20,

**Comment by eldy** [comment]
Sorry, i didn't understand.
Can you describe a way to reproduce the bug so i would be able to understand ?

**Comment by eldy** [comment]
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Pull request closed without merging**
