### PR TITLE
Typo "Copytight"

### PR DESCRIPTION
**Pull request by aspangaro**

### CODE REVIEW

**Comment by marcosgdf** [comment]
:laughing:

**Comment by frederic34** [comment]
Also in 
compta/bank/card.php
compta/bank/class/account.class.php
Jood Gob :laughing:

**Comment by aspangaro** [comment]
I know Frederic, it's correct with an another PR : https://github.com/Dolibarr/dolibarr/pull/2420/files

**Comment by rdoursenaud** [comment]
Now that was a funny one!

**Pull request merged**
