### PR TITLE
NEW : manage output languages for free text

### PR DESCRIPTION
**Pull request by altairis-tof**
allow input of free text by language
also factorized and harmonized related code
Please note that default text is not associated with any language for compatibility with present and logical UX.
image

### CODE REVIEW

**Comment by altairis-tof** [comment]
thanks to merge ;-)

**Comment by eldy** [comment]
I did the merge but i had to make a revert.
The PR add problem because it add a "form" and "/form" inside html "table" html tags. And this is forbidden by html5, even if this appears to work on some browser.
This create troubles also with some javascript library and when using strict HTML browser like on an Android WebView.
We must have only 1 <form> and the table with tr of each param must be inside the form and not the opposite.

**Comment by altairis-tof** [comment]
do i have something to do ?

**Comment by eldy** [comment]
Yes, can you remake your PR but with any tag "form" inside object "table".
You must have

> < form>
>   < table>...</ table>
> </ form>

You can use this plugin to check page is correct:
https://chrome.google.com/webstore/detail/html-validator/mpbelhhnfhfjnaehkcnnaknldmnocglk

The problem with this tool, is that there is a lot of alert that are harmful and others that are. You must ignore all errors of type "deprecated", "Bad value for", "Attribute target not allowed on element"

**Comment by altairis-tof** [comment]
@eldy the problem is that every dolibarr core admin script is made with a table with forms inside (ie one form for freetext, one for watermark...) so i cannot do anything by myself except rewriting all architecture in those admin scripts.

**Comment by eldy** [comment]
> @eldy the problem is that every dolibarr core admin script is made with a table with forms inside (ie one form for freetext, one for watermark...) so i cannot do anything by myself except rewriting all architecture in those admin scripts.

Note that the form can be inside the table if it is inside the < td > because you can put any content inside a cell, even a form, but is not allowed before a < tr >

A lot of work were done in v7 and v8 to remove all of them (most form tags were moved before and after the table tags, but there was so many cases that we may have forgot some. What is harmfull is the <form between < table > and < tr >
It seems into admin page, work was not complete for freetext and watermark on some admin pages.

Take a look at the admin page of contract. 
admin/contract.php
Html is correct here. Only one "Save" button for the two field "Free text" and "watermark" and table are inside the form, compared to setup or order where it is not valid HTML5.

**Pull request merged**
