### PR TITLE
Move poll menu into tools menu.

### PR DESCRIPTION
**Pull request by aspangaro**

### CODE REVIEW

**Comment by marcosgdf** [comment]
Are you sure that is the best place? I would say polls should have their own area or be in commercial area

Better ask dev list

**Comment by aspangaro** [comment]
Report a conversation in french forum to reduce icon number in menu.

http://www.dolibarr.fr/forum/11-suggestionsnouvelles-fonctionnalites/48608-suggestions-devolution-du-classement-du-menu

Like emailing, polls can serve in many domains.

**Comment by marcosgdf** [comment]
I think this kind of conversations should be discussed in the mailing list instead of the french community forum...

Polls can be used for different topics, but in a company it is more oriented to commercial or HRM purposes

**Comment by rdoursenaud** [comment]
I concur, design decisions should be discussed on the international mailing list.

As for this particular change, my only griefs are:
- why are you removing the "Last trips and expenses" box in a pull request related to a menu move?
- please don't leave comments behind, update the module descriptor accordingly!

**Comment by aspangaro** [comment]
Good evening,

I transfert this discussion into international mailing list

@rdoursenaud Removing the box trips & expenses is a bug on this pull request, it's an "old" pull request waiting for validation
I will come back on module descriptor, sorry

**Comment by eldy** [comment]
The number of entries into top menu  become dangerously high. That' s why survey menu was moved into tools at same level than emailing. There is so many cases when poll can be used than moving it into a non generic entries does not look a good choice.

**Pull request closed without merging**
