### PR TITLE
Hook printObjectLine and printObjectSubLine work for all external modules

### PR DESCRIPTION
**Pull request by olsesacl**
Hook printObjectLine and printObjectSubLine work for all external modules

### CODE REVIEW

**Comment by eldy** [comment]
Waiting tests when using modules like deee or subtotal of milestome to know if module can deal with this change.

**Comment by hregis** [comment]
@olsesacl What will manage your external module?

**Comment by simnandez** [comment]
From what I see, this change will standardize the behavior of hooks in dolibarr.  It must be the external modules who check the conditions necessary for proper operation, not Dolibarr.

**Comment by olsesacl** [comment]
The fail check is because i edit reference and label a invoice line, and the check see differences.

**Comment by hregis** [comment]
@simnandez @eldy @olsesacl 

Yes I agree ! I'll make sure to do otherwise. keep in a corner the "product type 9" is a separate line and the special code is the number of external module ! ;-)

**Comment by eldy** [comment]
@hregis What do you mean with I agree. You agree to include the patch or you agree when to not include it ?
I think this patch is a good thing. As said by juanjo, it is goal to external module to manage product type 0 or special code.
But my question is:
- Does external module still have a solution to solve their need after the patch. If yes, we should accept the patch, even if this needs to change the external module code. If external module has no more solution to work even by changing its code, we should not.
- Also, does the feature of dolibarr for "option" still works (option are special_code = 3). However, i just don't know how to test it because i can't remember how we can create line with special_code = 3 with standar ddolibar :-(

@olsesacl If you submit a patch as it is but keeping the line 2957, does this is enough for your need (it will be easier to know if we can accept patch or not)

**Comment by hregis** [comment]
@eldy @olsesacl @simnandez 
The special_code is set to 3 when the qty is 0.
Can be should be done differently, and add a check box to set whether when a qty to 0, this is an option or just a quantity to 0?
For the patch I agree that this is the module that is responsible for testing the special_code. by cons must define rules: the product_type must be greater or equal to 9 and special_code must match the module number.

**Comment by olsesacl** [comment]
Line 2957: I need edit line for show other information in documents.

Line 1045: I need for edit information in pdf.

The remaining lines are because I think it's better that way, but for my part is optional.

**Comment by olsesacl** [comment]
In my module i need change this value, but i can change de pull request for more standard and i make in my module a function for this

**Comment by eldy** [comment]
Your PR just point the fact the way the hook were implemented for all pdf_... function into dolibarr core was not correctly done (with test on status_code sometimes, sometimes not, sometimes test on type = 9, sometimes not, and sometimes this change the return and sometimes not.
It becomes difficult for me to know if I can validate or no your PR (not because of your PR but because of current bad code into the pdf_ functions).
So I pushed a PR 9f21ea58a374571e31f226f10430d609172960b4 to try to make things easier. This means you will probably have to suggest another PR based on new code now. Sorry for making you to make redo what you've done, but it was really not possible for me to undestrand with old code, so i just implemented all pdf as "replace" hook, so things should be easier for future.

**Pull request closed without merging**
