### PR TITLE
add 'fusion pdf' in mass action of expense report

### PR DESCRIPTION
**Pull request by laudeco**
Add a mass action 'fusion pdf (build doc)' in expense report list

### CODE REVIEW

**Comment by eldy** [comment]
Can you push into develop branch ?

**Comment by laudeco** [comment]
I'd prefer on 5.0 first if possible for you, in that case I can deploy it on my production :)

Kind regards
L.

**Comment by eldy** [comment]
5.0 versions has been released so no new feature can be accepted. 
To deploy on your own server you can still create a fork of the 5.0 branch and make a cherry-pick of the PR.

**Comment by laudeco** [comment]
@eldy isn't ok ?

**Pull request merged**
