### PR TITLE
Add customer code in customer orders documents

### PR DESCRIPTION
**Pull request by openthink-laurent**

### CODE REVIEW

**Comment by openthink-laurent** [comment]
Can anyone review this? Thank you.

**Comment by openthink-laurent** [comment]
Could anyone review this? Thank you.

**Comment by saxa** [comment]
This just add the customer code on one of the documents, probably would be better if you would add it to all standard documents, and you would describe what this PR does next time. Although I do not have 
permissions to push it up I am just suggesting you to fix it that way. Maybe I am wrong but where is this setting done ? Is there some configuration needed ?

Rgds
Saxa

**Comment by atm-maxime** [comment]
@eldy, now you have to add your option in all other documents models, code_client is already on proposals, invoices, ...

**Comment by openthink-laurent** [comment]
The main documents for customers (invoices, commercial proposals and even interventions...) already mention the customer code, so it makes sense to add it the same way on customer orders. I do not agree with the addition of the option "DOC_SHOW_CUSTOMER_CODE" for customer orders, or at least the same thing should be done for all documents.

**Pull request merged**
