### PR TITLE
Migrated old message notifications to the """new""" system

### PR DESCRIPTION
**Pull request by marcosgdf**
Migrated old message notifications to the """new""" system

### CODE REVIEW

**Comment by marcosgdf** [comment]
Error not related to this change:

```
1) LangTest::testLang
Error for code fa_IR
Failed asserting that an array contains '،'.
```

**Comment by marcosgdf** [comment]
Ewww! You did not give me time to fix the CS errors! :smile:

**Comment by eldy** [comment]
Removing the "public" in declaration of run_trigger method is the fast way.
Renaming run_trigger( into runTrigger( is a better solution, but it will break all modules providing triggers. Not sure we must do this.

**Comment by eldy** [comment]
I fixes the ces pb

**Pull request merged**
