### PR TITLE
NEW enable free emails input with select2

### PR DESCRIPTION
**Pull request by frederic34**
email

### CODE REVIEW

**Comment by eldy** [comment]
What if user enter 
`abc@def.com  instead  of   abc <abc@def.com>`

**Comment by frederic34** [comment]
@eldy it happen nothing, but i can check for `abc<abc@abc.fr>` and `abc@abc.fr` and return match for the first case found

**Comment by frederic34** [comment]
@eldy so now you can enter `abc <abc@def.fr>` or `abc@def.fr`

**Comment by frederic34** [comment]
Sélection_080


Sélection_081

**Comment by frederic34** [comment]
@eldy do you need more information?

**Pull request merged**
