### PR TITLE
NEW Add engine and libs for pdf generation using wkhtmltopdf

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by frederic34** [comment]
To test you need to install wkhtmltopdf...

**Comment by frederic34** [comment]
wkhtml

**Comment by eldy** [comment]
I try to fight against not absolutly usefull external libraries.
Can you check if you can remove phpshellcommand and use instead the internal dolibarr method
executeCLI()  from class  Utils ?

**Comment by frederic34** [comment]
I know this is very experimental, I share to make possible a new way for pdf. whhtmltopdf can generate pdf from html css javascrit (webkit)

**Comment by dolibarr95** [comment]
Hi
This new library  could be very very very help/useful for dev or user.
@frederic34 do you have screenshot of your pdf ?

Tks

**Comment by frederic34** [comment]
@dolibarr95 yes on the french forum

**Comment by dolibarr95** [comment]
tks :)

**Pull request closed without merging**
