### PR TITLE
NEW Extend option PDF_HIDE_PRODUCT_REF_IN_SUPPLIER_LINES to change supplier ref display mode in PDF

### PR DESCRIPTION
**Pull request by defrance**
we have like this 3 mode of display supplier ref

### CODE REVIEW

**Comment by aljawaid** [comment]
Would this be able to show the following 3 modes?

our reference + supplier reference / supplier reference / our reference

**Comment by defrance** [comment]
0 = internal ref ( supplier ref)    ===> default
1 = only supplier ref
2 = supplier ref (internal ref)

Think 2 is the most pertinent for supplier who receive the document, but like this we keep the previous setting

**Comment by aljawaid** [comment]
This would be excellent to add!  **2** would be very important so we can send supplier orders which let's them identify their own products.

Will this work on 4.0.2 or only compatible with the next version?

**Comment by aljawaid** [comment]
Tried this, but it doesn't seem to show the reference or the language though.

**Option 2**
_language issue? but which language file should I add the 'InternalRef' string to?_
snip_20161218234337

**Option 0**
_supplier reference should be YY123456_
snip_20161218235252

**Option 1**
_supplier reference should be YY123456_
snip_20161218235600

**Comment by aljawaid** [comment]
Also, for the sake of customer pdfs and supplier pdfs, where customer pdfs don't have the reference number, can we amend the below?
`if (empty($hideref))` 

If I change it to `if (!empty($hideref))` would it hide references from customer pdfs but not supplier pdfs?

**Comment by aljawaid** [comment]
I'm wondering whether the generated PDF is not showing supplier reference because of $prodser vs $prodserv

**Review by aljawaid — COMMENTED** [review]
I've tried this on both 4.0.2 and 4.0.3 and it does not work

**Comment by aljawaid** [comment]
@defrance Could you kindly provide any insight on why this may not work for the supplier reference? seems to pull up the customer reference fine - just a language issue...but the supplier reference is just blank on both minor versions.

**Pull request merged**
