### PR TITLE
NEW Level multiprice generator based on per cent variations over base price

### PR DESCRIPTION
**Pull request by marcosgdf**
Users will be able to generate automatically, prices for products of levels > 1 based on percent variations rules defined in the admin page

captura de pantalla 2015-10-19 a las 15 15 31
captura de pantalla 2015-10-19 a las 15 15 50

### CODE REVIEW

**Comment by simnandez** [comment]
This is a good and necessary feature!!! :heart_eyes:

But into script migration you must also create the constraint unique_level...

**Comment by BebZ** [comment]
Is it possible to base the price generation over the average (PMP) buying price in the price level rules ?
or on the pfp (product fournisseur price ?)

**Comment by altairis-tof** [comment]
and is it possible to do it per product directly in the customer prices tab of the product tab ?

**Comment by marcosgdf** [comment]
You guys are free to open up a feature request :)

**Comment by torvista** [comment]
This appears to have been included...but how do I enable it to produce prices based on a percentage discount?
https://www.dolibarr.org/forum/12-howto-help/28285-product-multiprice-price-levels-by-percentage#34670

**Pull request merged**
