### PR TITLE
NEW: new const MAIN_ORDERLIST_CREATEBILLS_ONEBYTHIRD

### PR DESCRIPTION
**Pull request by altairis-noe**
NEW: new const to allow preselecting yes in the bill orders massaction from order list

### CODE REVIEW

**Comment by altairis-noe** [comment]
For some reason, my email address seems to trigger an error in CI/pre-commit. I had to change it. @eldy, would you happen to know what could be wrong in noe.cendrier@altairis.fr in the copyright section ?

**Comment by eldy** [comment]
> For some reason, my email address seems to trigger an error in CI/pre-commit. I had to change it. @eldy, would you happen to know what could be wrong in [noe.cendrier@altairis.fr](mailto:noe.cendrier@altairis.fr) in the copyright section ?

No idea. Do you remember if it was in precommit or on phan tool ?
My be @mdeweerd knows ?

**Comment by altairis-noe** [comment]
It was on pre-commit. it asked to replace noe with no, none or some other values

**Comment by mdeweerd** [comment]
My preferred method is to add this case to the codespell ignorelist using dev/tools/codespell/addCodespellIgnores.sh .  Done in #29394.

**Pull request merged**
