### PR TITLE
#NEW : Add Balance report with order in Project

### PR DESCRIPTION
**Pull request by mapiolca**
# New Add Balance report with order in Project

Add a new balance report to follow project before invoices

### CODE REVIEW

**Comment by mapiolca** [comment]
@eldy, @hregis, What's the problem ?

**Comment by eldy** [comment]
Can you describe the goal of this PR ? A screenshot commented may be enough.

**Comment by mapiolca** [comment]
This function is useful for forecasting future supplier invoicing, highlighting hidden invoicing costs when the project is finished, etc.

**Comment by eldy** [comment]
Can you provide a screenshot ?

**Comment by eldy** [comment]
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolete, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.

**Pull request closed without merging**
