### PR TITLE
Code separation in tree layer, Discussion on pattern, Best practices …

### PR DESCRIPTION
**Pull request by gnovaro**
Moving html to a new template view

### CODE REVIEW

**Comment by altairis-tof** [comment]
:+1:

**Comment by gnovaro** [comment]
@eldy can check this? please, thank you.

**Comment by eldy** [comment]
Introducing a file product.tpl.php is what i call a "good practice" on paper. What we earn a school.

In real life, this introduce headache when we want to make maintenance, code analysis, bug impact analysis, by creating a file using var that are not initialized/defined in file. It becomes difficult to know how a var into .tpl file is filled, and even if it is, because 2 part of codes that depends each other are splitted in 2 different places.
For this reason, I recommend the usage of .tpl.php files only if the "presentation code" must be used at least into 2 different places (when code is mutualized, the gain of removing duplicate code is higher that the pain introduced by the "treasure hunts" we must make when we read code by switching of files, so it worse the split).
I know that "on the paper", it is better. I developped like that in the past by creating ton of files for just one output. But experience tells me it is not so good. So i prefer we keep the philosophy: Split "intricated code" only if one part of the extracted intricated code need to be used at 2 different places at least.

**Comment by gnovaro** [comment]
HTML inside php is and old bad practice, we need to separate the business logic to the presentation and  only FOCUS in the really matters (Business). This file have a lots of lines, in the same file see other block for editing is basic the same html with only small changes. I have more than 16 years making software I' not newbie. Dolibarr code is spaghetti code, anti pattern, Structured programming mixed with pseudo objects. SQL, JS PHP, CSS, HTML all in the same file and mixed code inside strings is difficult to anyone to understand. Is more clear have a few files more. We need to use inheritance, namespaces, Reuse more code, this is a first try to move forward to something modern... more clear to read...

For example if you know java, they have a practice in OOP, never have a method with more than 20 lines (Recommendation in eclipse and other IDE), this minds you have made something wrong. 

The SQL and DB access only we only made in Model Objects.. but in this project we have a class made all...

**Comment by gnovaro** [comment]
@rdoursenaud What do you think about this?

**Comment by rdoursenaud** [comment]
@gnovaro 
Ugh, welcome to the community? I guess…
Joke aside, I'd love to see Dolibarr's technical debt reduced and introduce better separation of concerns to allow people with various skills to contribute but, as you can see, @eldy is deeply stuck within its ways. I won't go through that rabbit hole again. Sorry!
That being said, he's got a point about uninitialized variables and this whole "tpl" approach. It's too naive to be useful. This is one of the reasons for using a proper templating engine. But hey, he's against that too…
I won't let myself fight a loosing battle again. Been there, done that, not worth it.

**Comment by eldy** [comment]
"we need to separate the business logic to the presentation and only FOCUS in the really matters"
Sure. But this separation does not force us to split intricated code into a lot of separate files. This is scholar  practice not a good practice. Having html into php is not a bad practice. Don't forget than PHP IS an HTML template engine. It is also a framework engine more powerful than a simple template engine, that's why we forgot this. But we can make the separation as it is done currently :
* Model = object.class.php files (with the design pattern of "Active Record", see https://wiki.dolibarr.org/index.php/Language_and_development_rules#Design_patterns_and_Object_programming)
* Controller = Part after the /* Action */ comment and before the /* View */
* View = Part in page after the /* View */ comment. Common portion of code that are shared with other can be placed into library, external methods or files but if they are common to several places.


The argument to allow different people with knowledge in design and developer work each other in their side is true but that is just useless in real life. I saw several hundred of project and the ratio of project using people that work on the HTML formatting and different people that works on the controller code is near 0%, even on project with hundred of developers. 
I know perfectly Java, I managed and sponsored several thousands of big project in Java, like in PHP, and that a good argument to says we must not do like it is in Java. Java is probably the worst language that exists for productivity and maintainability and bug fighting. The same project with an experienced user in java need twice more time than same project with a rookie developer in PHP, and result has a  lower quality. The reason: The idea to make separation everywhere, to add more and more layers, coming from Java frameworks philosophy and Java abstraction layers, in tons of files of 20 lines, is a good example of what we must NOT do. So the example of Java to justify the reason to include layers is surely the best argument to not do it. This is very beautiful when you like technology. I think it's beautiful, but it's awful to maintain, to debug, to learn, to have a good productivity. And Dolibarr project won't be where it is today if we took this approach. I surely think it will be funnier, but my goal is not to choose what i think it's fun, but what will bring the higher productivity to have the project the more stable, enhance quickly, having a learning curve low, etc... There is pro and cons in both way of working. I  already experienced the different ways of working in various languages and project. And result is without appeal: A good productivity, a good maintainability is not always obtained with what we think or we earn to think.

So using of .tpl.php must be done for code mutualization and fight against code duplicate, not to follow "good" practice that are "good" only on paper and worst in real life.

**Comment by gnovaro** [comment]
I do not agree much with "real life" ... and html within php, java has good and bad things ... But it is a language with many years in the market ... PHP adopted many practices taken from JAVA. ..
The use of design patterns involves code reuse. Let's start with simple things that we can use:

For example:
- Do not use styles inline, always class for CSS
- No JS inside the html within a string inside the php, better JS files separately.
- Move SQL queries to current objects (Models)
- Convert the loose php files into controllers as object class and separate each action in methods

They are small changes but they would make the work easier.

**Comment by ParisLiakos** [comment]
@gnovaro Dont bother, just move on to something else. If you see older issues and discussions, there is no point. 
You are trying to change something that doesnt even have a consistent way to apply identation yet. Not to mention that everything is a mix of French with English, method names and docs make no sense etc.

And this will not change anytime soon, trust me, eldy thinks that stuff like autoloaders are bad and makes people coding like cows.

@eldy dont get me wrong, dolibarr is great, but being stuck to a certain way and ignoring best practices and standards is a huge turnoff and turning contributors away. Issues like those are criticism and they will not stop coming unless you start considering that "hey it cant be that all those people are wrong and i am right"

**Comment by eldy** [comment]
@ParisLiakos As you say Dolibarr is great.
And it is great because i keep in consideration things that differs than only technical and geek purposes. Maintainability, Compatibility, learning curve, non abstract coding is sometimes more important that making the art of coding. I don't think i am right and other are wrong. As I said, i myself love making code with the state of the art, but I can't do only what i want, and priority is not how me and you and other geeks wants to code, but what is the best choice to provide the better architecture to have a high productivity and very low time to fix a bug with a very low learning curve and non abstract but explicit code.
I can't validate a choice just because it's something geeks, like me, want. That is a main difference between Dolibarr and a lot of other projects (started in year 2000 like Dolibarr) but that has disappeared.

Note that there is a fork of Dolibarr that was created and dedicated to follow the state of the art several years ago, dedicated to geeks (I myself encourage this), because few developers would like to work among perfect coders and not with cow coders. This fork was called:  speadealing. Goal of this project is to accept coding rupture, but, well, it seems "cow coders" are more productive than "perfect coders" when i compare the road of the 2 projects.

My experience, based on managing several hundred of small and very large projects show me that the perfect choice is not always the choice that win the battle, so I prefer to trust my experience than my desire. This is called "pragmatism" and my pragmastic is probably stronger than my desire to make funny and very pure developing practices.

**Comment by ParisLiakos** [comment]
If you really think that dolibarr is maintenable or that people are productive with it, in its current state, well, i guess i have nothing constructive to add here.

**Comment by dunhamjared** [comment]
In most of my projects I've developed that are kind of like Dolibarr, I just use PHP for logic, querying data, session management and creating JSON for Handlebars with a bunch of AJAX calls. I do cheat time to time if a page requires very little work by using PHP as the templating engine instead of handlebars. ;)

**Comment by BebZ** [comment]
Dolibarr makes more for users and dev beginners than it makes for the pride and satisfaction of the geeks. Others projects like Speedealing may need your autocoding help ;) 
But it's not impossible to fork and make Dolibarr with new rules, less technical debt and certainly a much lower speed of evolution ;)

**Comment by hregis** [comment]
@BebZ @eldy @gnovaro @rdoursenaud @ParisLiakos 
Just for information, at the time it could be considered that Speedealing was a fork because we used Dolibarr php code, but since all the code has been rewritten in Javascript / Ajax and uses Node.js, Total.js, Angular and MongoDB for the database (NoSQL). So the project is no longer really a fork, just the spirit of Dolibarr was kept. The project was renamed to ToManage.

https://www.tomanage.fr/
https://github.com/ToManage/TM-CRM_ERP

**Comment by absnc** [comment]
Variables that are being initialized from outside a tpl file, thus obfuscating their behaviour inside a
given tpl file, isn't a concern related to MVC(2) pattern at all.

Graphically reusable components, would logically be called and initialized with clearly defined
parameters in any case; as opposed to apply simple code ellipsing in the current situation, right ?

As far as I understand, tpl files were introduced so to give to external developers, a way to override
the default behaviour of some key system components/widgets (product lines, dialog boxes, etc), on the
same principle as hooks, that give developers a way to add custom functionalities.

The problem, is that anyone could write tpl, in a 'unconventional' manner (interlacing display and logics, in a way that also gave PHP the bad reputation we all know).
That could potentially lead to problems, when some developments/enhancements deeply rely on one each other. (let say, my customer already uses a module that override an existing tpl with its own. What happens in case I also need to customize in my own same tpl ? wouldn't an overloadable OOP graphical object be handy in that case ? ).

One way to address those concern, would consist of defining consensually, how shared graphical components need be instanciated (framework?).
As well as defining a common/central real-time (shared..) datastructure, globally defining the way these objects mutate under certain conditions.
There are few templating engines (could also be it a custom one), that address those questions;
picking an existing ones would also allow the avoidance of redefining in detail all possible scenarios...

**Pull request closed without merging**
