### PR TITLE
FIX: restore supplier price charges input

### PR DESCRIPTION
**Pull request by altairis-tof**
that have disappeared here : https://github.com/Dolibarr/dolibarr/commit/c3b74e66ffc7f04f214884e271f11bbfd2c46e80

### CODE REVIEW

**Comment by eldy** [comment]
This option seems to be removed with 3.7 when code for margin calculation was debugged to have it working correctly.
I think you want to introduce a more complete method to calculate margin (currently we have in 3.8:  on best supplier price, and on pmp price). I think you would like to calculate taking in consideration the cost of production and distribution.

I think you want 2 more complete method to calculate margin using that will be
comparing sell price with (best supplier price + the offset field you introduce and called Charges)
or
comparing sell price with (pmp price + the offset field you introduce and called Charges)

If i am right, we first need a field to store this value into database. I suggest to introduce the field called "prod_distrib_cost" (for "Production or Distribution Cost") into table llx_product.
Such change must be done into develop branch.

**Comment by altairis-tof** [comment]
the db field already exists (charges and unitcharges in llx_product_fournisseur_price since it depends on the supplier). And it is not a new feature since it exists since 3.3.
i also disagree about your second method (pmp + charges) because it's not a good calculation. If you want to do something like that, you need to add an option to integrate charges in the pmp, but this would be a new feature.

**Comment by BebZ** [comment]
Sry I put my 2 cents again but PMP is an average of buying prices dispatched in stock no ? Nothing to do with the charges or no reason to introduce charges in this calculation. except if you want to calculate average of your charges... but I don't see the point because charges can vary a lot.
BTW when you get products discounted at 100% it's not taken in the PMP . SO PMP may be false.

**Comment by altairis-tof** [comment]
Ok, imagine you are a company that sells computers and you are located in French Guyana (real use-case).
You have 10 big servers in your stock; the unit supplier price is 9000€ but you have shipping costs and custom taxes that cost 2000€.
As a manager, do you want to evaluate your stock to 90000€ or 110000€ ? 
Same use-case, you sell your server 15000€; do you consider your margin as 4000€ or 6000€ ?

**Comment by BebZ** [comment]
hum... yes that's right for this particular case if you know in adavnce (before sending the supplier order) the price of those extra charges.
I thought those extra charges would be also on the supplier invoice and customer invoice . 
I am not against the field charges, it is convenient for those use cases.
PMP is in my mind the EX WORKS average of buying prices, 
but PMP+charges is also right to know the cost of DDP or FOB buying prices...
It was a good discussion ;) Thanks for your remarks, and I hope this "charges" field will be re-implemented.

**Comment by eldy** [comment]
Well, i started to introduce "cost_price" into table llx_product (price + production and distribution cost).

There is also a cost for charges that is available at each supplier price if hidden option PRODUCT_CHARGES is set.

Now, we can introduce 2 new choices for option "rule to calculate margin". Currently value 
"1" = Best supplier price
"pmp" = PMP price

We can add:
"costprice" = Cost price introduced into 3.9
"suppliercostprice" = Cost price calculated with supplier price + charges already available when option PRODUCT_CHARGES is set.

**Pull request closed without merging**
