### PR TITLE
Introduce class and helper for Incoterms

### PR DESCRIPTION
**Pull request by ghost**
Hello,

this PR (draft) introduce a new class and helper for Incoterms.

The final goal of this change is to move all Incoterms related values, functions, etc. to a separate Module.

When it is okay, I will do more work on it.

### CODE REVIEW

**Comment by eldy** [comment]
The PR has status Draft. But if it is stable and application is still working the same way than before PR, i can validate it at this step if you confirm it's ok...

**Comment by ghost** [comment]
@eldy I will take a look at conflicts on this weekend and update this PR

**Comment by ghost** [comment]
I will make a new fresh PR for this, for a better commit history

**Comment by atm-maxime** [comment]
Hi @TobiasSekan !
I always thought that having incoterms as a module was wrong. I think it should be removed and replaced by a dictionary system just like "payment modes" or "payment terms", and add an option to activate this dictionary. Helpers can be added in the dictionary I think.
And have incoterms properly managed in the PDF documents, at the bottom left of the table.
What do you think ? Is there something special about incoterms that makes them not manageable by a dictionary ?

**Comment by ghost** [comment]
Hello,

Did you mean a Directory with files (json, xml, php, ..) and helpers ?

Like:
```
Incoterms
 |-DAP.json
 |-FOB.json
 |- IncotermHelper.php
```
or mean you a dictionary inside the database with triggers used as helpers?

IMHO:
The biggest problem with Incoterms (or multi currency) is, 
that the most pages in each module need a hand of code-lines to support it.
(And theses code lines are useless when a user don't use Incoterms.)
For this we need a better way to include it in pages, like massactions or similar.

Why not as module?
I think one of the base ideas of Dolibarr is to handle (the most) features as modules. 

1. When Incoterms and other multi-modules are translate into real modules it would make the future development and maintaining eaiser.
2. We can combine these two things ( the idea with the dictionary/directory and the module)

**Comment by atm-maxime** [comment]
Hi @TobiasSekan ,

Sorry I didn't get your answer.
I really mean a dictionary. For me incoterms must be dealt with the same way as payment modes or payment terms. A simple drop down list based on a dictionary.

**Comment by ghost** [comment]
Okay, 

Hm but i think when it possible we should expand the dictionary entries a little bit with more attributes.

The incoterms get a change typical all 10 years, so it would be nice when we a a `fromDate` and `toDate`
So that a user can see that an Incoterm is not longer valid or it will be unvalid in the next time.

When I have time i will make another PR with a little improvements for the Incoterms.

**Comment by atm-maxime** [comment]
I think that if it only changes every 10 years, we don't need from date an to date. Simply some entries will be inactivated and new ones will be added...

**Pull request closed without merging**
