### PR TITLE
First Version of Batch number, eat-by date and sell-by date management

### PR DESCRIPTION
**Pull request by KreizIT**
Add a specific module for this management.
Should not disturb normal operation if not activated.
Require : decreasing stock on expedition validation.
TODO : 
- Adapt IHM for stock transfer (Disabled for instance)
- define what to do when decreasing stock on customer order validation.
- more test

### CODE REVIEW

**Comment by BebZ** [comment]
Major improvement, "chapeau bas" et je suis là pour le "required : more test"... si tant est qu'il puisse y avoir un "merged" je download le zip ASAP.

Merci :)

**Comment by BebZ** [comment]
Some errors I can't really understand as I'm not a dev, i can barely read php ;)

On page : 
/htdocs/product/stock/product.php?id=1
error : 
Warning: get_class() expects parameter 1 to be object, null given in 
\htdocs\product\class\productdluo.class.php on line 512

and on page : 
/htdocs/fourn/commande/dispatch.php?id=8

it is unfortunately not possible to give to the products its DLUO/BATCH, would it be on this screen ?

also not possible on : 
/htdocs/expedition/fiche.php?action=create&id=5&origin=commande&origin_id=5&entrepot_id=1
 another error after validating an expedition : 
Warning: get_class() expects parameter 1 to be object, null given in C:\dolibarr\www\dolibarr35\htdocs\expedition\class\expeditiondluo.class.php on line 154

And what i did not understand as a "user" is where to put those Dates and Batch numbers and modifiy in the case we did a mistake ? 
If it's not allowed to change or decide what numbers it has to be, what defines it, the date and time we dispatch the products in stock  ?

**Comment by KreizIT** [comment]
For the moment, for 1 given product, you can add batch number  in  'stock' tab when you add or delete quantity. And then you can select which specific batch number you send to your customer when creating a delivery note.

**Comment by BebZ** [comment]
it seems it is not possible to edit the dluo and batch on the stock tab of a product. I can add manually products to the stock with batch dlc dluo, but the info coming from suppliers deliveries are not : possible to define and possible to write on the dispatch.php page... but maybe the module doens't interfere with dispatch.php and is only working with automatic filling of the stock when supplier's order is validated ? Thanks for you answer ;)

**Comment by BebZ** [comment]
stock dluo

**Comment by BebZ** [comment]
@eldy  : Did you review the improvement of the Core and is there a chance to see it implemented in a near version, like 3.6 ? (I'm already using it in a production environement... and I was really missing this feature, you may have seen it on many, many, many topics...).

I have a full PDF of the "how to" with screenshots, etc to explain the function, do you need it ? 

Thanks for your answer.

**Comment by BebZ** [comment]
@eldy 
http://wiki.dolibarr.org/index.php/Module_Stock_(developer)

 De même, une livraison d'un produit composé de plusieurs sous-produits devrait pouvoir être intégrée au stock sous forme des différents constituants plutôt que du tout.

**Comment by FHenry** [comment]
You rocks !

**Comment by BebZ** [comment]
Update of the core may be rocking but is it of NO interest in the devs community? Please advise

**Comment by FHenry** [comment]
Do you come to the DevCamp ? It should be great to discuss with Eldy why this pull request is not yet merged. I think it's huge and 28 files modified make it hard to analyse, may be Edly have some recommendation to made this functionnality into Dolibarr in other way, I don't know either. I didn't analyse the code yet, but I know the functionnality is something usefull for lot of person. Let plan a presentation of your code during the dev camp ?

**Comment by BebZ** [comment]
I's Kreiz-IT's code, not mine :) 
I'm not a coder, just a alpha-beta...zeta-user of Dolibarr, I made a nice file on how to set-up a demo of this new functions... since it's not mergerd, i wrote e-mail to Eldy, he was answering it is a BIG piece of code, and he doesn't have time (or he doesn't want) to study it (better studying barcodes, and other things, like wiki and developping rules...).
I really wouuld like to "stay" on Dolibarr as long as my company develops (and you can't imagine how fast it grows :) 
but Dolibarr has to keep the pace and adapt (not only to my company, but to ALL the companies leaving the "beta-ERP"/"beta-CRM"-Dolibarr, because it CAN offer advanced functions, but it DOES NEVER (hierarchy is critically blocking in most of cases, and no DIRECTIONS are given.)

I don't know if Kreiz-IT goes. I'm not a member of the Dolibarr foundation, so I don't think I can come, and as I'm not a coder, i will just lose my time opening my mouth to say (or shout) the same as above, and the same messages as I leave on the forums (where I don't want to answer anymore, except stupid questions, like where do... where can I... "touchy" - "sensitive" questions are not debated by the dev's team but by "debators" (people who like to debate?) BUT AND nothing ever comes out from it, and I guesse it is never read at all by any person important in Dolibarr  ;) )...
If you want for DevCamp I can create a powerpoint on the reason's my company being a re-seller of brands (not a shop, not a factory, not a service... just a B2B re-seller and also small web-based activity) COULD LEAVE DOLIBARR (as an example of why companies beginning to have a bit of benefits and having a bit of budget for development would leave because of NOT BEING HEARD...)

**Comment by eldy** [comment]
Sorry to not have study this yet. But i am really busy with 3.5 release (that was planned this month and still need tests), so i will study this later.

**Comment by BebZ** [comment]
@eldy @FHenry 
Still no time to review the code ? 
Even if things changed in stock management (see last commit of Eldy) the pull request could be already useless because of this one...
Nice new useful function already broken ?

**Comment by BebZ** [comment]
2 months ago... I understand dealing with products in Dolibarr is like asking to an ERP to be an Enterprise -Resource- Program
  !

**Comment by marcosgdf** [comment]
@BebZ you don't need to poke @eldy everyday to remind him that this PR is waiting for a decission.

**Comment by BebZ** [comment]
Ok sorry to lose patience and for my aggressiveness (but silence is worst than negative answers)... but I see new functions except this one implemented which is not that huge and suggested like that on the wiki's roadmap(or suggestions) moreover http://wiki.dolibarr.org/index.php/Module_Stock_(developer) 
a delivery should be integrated to the stock with its different components instead of the whole.

Many users complain about lack of infos on products, this is a real good start towards, "stocking" more infos on products (next could be when a delivery arrives to complete infos about packing (nr of products in a box and when sending to a customer to complete infos about number of cartons and number of the carton where the product is...)

This P.R. opens a wide variety of new evolutions, which I have asked to quote me and to integrate to Core for free (like subventions to Dolibarr). 
My company is succeeding and has a budget to invest wisely and I don't want to have mega-modules appart of the core which will cost later, mega-money to adapt 
and will leave Dolibarr mega-empty of useful functions !

This said, if the developping team can not believe an evolution is necessary in this domain of trackabability's product's stock's packing's management... i could just wish good luck for finding customers dealing with consumables/perishing products...

**Pull request closed without merging**
