### PR TITLE
[Tests-Only] Added end-to-end tests

### PR DESCRIPTION
**Pull request by SwikritiT**
## Description
Added end-to-end tests for create user, add user, user login, list users and logout.

Cucumber.js has been used which allows the tests to be written in simple English language.The format in which the tests have been written is referred to as Gherkin language.The tests have been performed using Night-watch.js testing framework.Selenium has been used for automating the browser.Travis CI has been used to automatically run tests.

## How Has This Been Tested?
- locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by SwikritiT** [comment]
Hello, @eldy we have added some end-to-end tests. We would be grateful if you kindly reviewed our PR and gave some feedback. We also need some assistance in Travis setup.

**Comment by eldy** [comment]
It seems tests with travis is no more executed after this PR.
I recommend two step : 
- First keep the travis setup unchanged
- Add a readme file to explain how we can make the test locally.
Once this will work locally, we will try to add it to travis.

**Comment by frederic34** [comment]
@eldy travis is not displayed since some days
travis for his pr is here https://travis-ci.org/github/Dolibarr/dolibarr/builds/733570281

**Comment by SwikritiT** [comment]
@eldy I took your suggestion and I have also added README filereadme file that includes steps to run the tests locally, in my latest commit. It would be really helpful if you could review it.

**Pull request merged**
