### PR TITLE
test github token

### PR DESCRIPTION
**Pull request by frederic34**
@eldy I reactivate action on pull request
this action calculate how many errors are ignored, if the number decrease it update the baseline

### CODE REVIEW

**Comment by frederic34** [comment]
image

**Comment by frederic34** [comment]
if it works, you can also run the workflow manually to clean the phpstan baseline

**Comment by frederic34** [comment]
action to clean caches is also in error
image

image

**Comment by eldy** [comment]
> image
> 

Why having the pho baseline run at each pr ? Why not doing it only once a week or day to avoid overload of github action on our repo ?

**Comment by eldy** [comment]
> image
> 

Why having the pho baseline run at each pr ? Why not doing it only once a week or day to avoid overload of github action on our repo ?

**Comment by frederic34** [comment]
@eldy this task is also sheduled, here you can see it don't work https://github.com/Dolibarr/dolibarr/actions/runs/11831647690/job/32967144876
ok to not run on pull_request, i have no other way to test

**Pull request merged**
