### PR TITLE
NEW check if a resource is in use in an event

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
NEW check if a resource is in use in an event
- add a constant "RESOURCE_USED_IN_EVENT_CHECK" in resource admin
- check if a resource is already in use when we create or update a resource from an event
- check if resources of an event are already in use in others events when we update an event
- add error messages to determine which resource is in use

### CODE REVIEW

**Comment by hregis** [comment]
@lvessiller-opendsi @eldy 
ce serait bien de renommer l'element avant !

https://github.com/Dolibarr/dolibarr/pull/11822/files

vois tu une autre table qui stockerait le mot "dolresource" ?

```
UPDATE llx_c_type_contact set element = 'resource' WHERE element = 'dolresource';
UPDATE llx_element_resources resource_type = 'resource' WHERE resource_type = 'dolresource';
```

**Comment by lvessiller-opendsi** [comment]
@hregis
Attention tu as mis une requete SQL UPDATE sans le SET :+1: 
- UPDATE llx_element_resources resource_type = 'resource' WHERE resource_type = 'dolresource'; 
Au lieu de : 
- UPDATE llx_element_resources SET resource_type = 'resource' WHERE resource_type = 'dolresource'; 

Je vais remplacer dans ma PR 11820 le mot "dolresource" par "resource"

**Comment by hregis** [comment]
@lvessiller-opendsi @eldy 

merci j'ai corrigé ! ;-)

**Comment by lvessiller-opendsi** [comment]
"dolresource" renamed by "resource"

**Comment by hregis** [comment]
@lvessiller-opendsi @eldy 
on va attendre que laurent accepte les deux PR,
ensuite il faudra filtrer par entité sur les tables llx_actioncomm et llx_resource dans tes requêtes

**Comment by hregis** [comment]
@lvessiller-opendsi 
désolé en fait il faut laisser "dolresource" ... désolé ! ;-)

"resource" was a reserved word and generated error of conflict with php and ci. That's why the class and key "resource" were renamed into "dolresrouce" everywhere.

**Pull request merged**
