### PR TITLE
NEW #2739 Permissions setup pages redesign.

### PR DESCRIPTION
**Pull request by rdoursenaud**

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Before:
capture d ecran de 2015-07-10 21-11-29
After:
capture d ecran de 2015-07-10 21-10-51

**Comment by eldy** [comment]
How can we see when the permission is set because admin want it to be set for new user and when permission is set necause inherited ?

**Comment by eldy** [comment]
Also, why introducing more click (must click on save) to do the same than before ?

**Comment by rdoursenaud** [comment]
The permissions override representation is conveyed by the disabled boxes title.
A simple mouse hover gives you the reason.
This is 1 more click but 10 less page refreshes.
This was particularly inaccessible with the page always jumping around and the hard to pinpoint links.
Imagine having to do that with a screenreader.
Here, all the modified settings are save at once letting you tune all the permissions in one go and hit save. The save button is repeated merely not to have to scroll the page.
The fact that it's an accessible form also helps efficiency letting you click not only on the checkbox but also on it's label text. No more laser precision pinpointing.
The plan is to add an AJAX layer that will take care of "update-on-click" and hide the save buttons. One less click and best-of-both worlds.

**Comment by BebZ** [comment]
+1 !!! "Here, all the modified settings are save at once letting you tune all the permissions in on go and hit save. The save button is repeated merely not to have to scroll the page."
+1 !!! "The fact that it's an accessible form also helps efficiency letting you click not only on the checkbox but also on it's label text. No more laser precision pinpointing"
=2 thousands thank you for making this page less "jumping" up and down

**Comment by eldy** [comment]
Needing to put the mouse on each click to know if permission is inherited or not is a pain.
It is important to keep information visible to admin.

I would prefer to keep the current page presentation but when clicking on a button, using an ajax call to update the option (like we do for setup pages to set/unset some options).

Like this, we still have clear information, we save click and we solve pb of the "jumping" up and down.

**Comment by rdoursenaud** [comment]
Argreed but adding an inheritance icon or text info is not too much of a deal and what I intend to do on the AJAX part (see #2739) to not clutter the HTML.

But you completely missed the point.
What I did is use a standard compliant form for accessibility reasons. This is mandatory to convey the meaning of the page in an efficient way.

Please take a minute to take a look at the results with a text browser (lynx):
Before:

```
  Ref.
   1
   Name ggg
   Note ggg
   Only permissions related to activated modules are shown here. You can activate other modules in the Home->Setup->Modules page.
   Module                                    Permissions
   Members                        All/None
   Members                                   Read members
   Members                                   Create/modify members
   Members                                   Delete members
   Members                                   Setup types of membership
   Members                                   Export datas
   Members                                   Read subscriptions
   Members                                   Create/modify subscriptions
   Agenda                         All/None
   Agenda                                    Read actions (events or tasks) linked to his account
   Agenda                                    Create/modify actions (events or tasks) linked to his account
   Agenda                                    Delete actions (events or tasks) linked to his account
   Agenda                                    Read actions (events or tasks) of others
   Agenda                                    Create/modify actions (events or tasks) of others
   Agenda                                    Delete actions (events or tasks) of others
   Agenda                                    Export actions/tasks of others
   Banks and cash                 All/None
   Banks and cash                            Read financial accounts
   Banks and cash                            Create/modify/delete and compare transactions
   Banks and cash                            Setup financial accounts (create, manage categories)
   Banks and cash                            Reconciliate transactions
   Banks and cash                            Export transactions and account statements
   Banks and cash                            Transfers between accounts
   Banks and cash                            Manage cheques dispatching
```

After:

```
Ref.
   1
   Name ggg
   Note ggg
   Only permissions related to activated modules are shown here. You can activate other modules in the Home->Setup->Modules page.
   Module                                  Permissions
   Members                        All/None
   Members                          [X]    Read members
   Members                          [X]    Create/modify members
   Members                          [X]    Delete members
   Members                          [X]    Setup types of membership
   Members                          [X]    Export datas
   Members                          [X]    Read subscriptions
   Members                          [X]    Create/modify subscriptions
                                                                                                                                                               (adherent) Save
   Agenda                         All/None
   Agenda                           [X]    Read actions (events or tasks) linked to his account
   Agenda                           [X]    Create/modify actions (events or tasks) linked to his account
   Agenda                           [X]    Delete actions (events or tasks) linked to his account
   Agenda                           [X]    Read actions (events or tasks) of others
   Agenda                           [X]    Create/modify actions (events or tasks) of others
   Agenda                           [X]    Delete actions (events or tasks) of others
   Agenda                           [X]    Export actions/tasks of others
                                                                                                                                                                 (agenda) Save
   Banks and cash                 All/None
   Banks and cash                   [X]    Read financial accounts
   Banks and cash                   [ ]    Create/modify/delete and compare transactions
   Banks and cash                   [ ]    Setup financial accounts (create, manage categories)
   Banks and cash                   [ ]    Reconciliate transactions
   Banks and cash                   [ ]    Export transactions and account statements
   Banks and cash                   [X]    Manage cheques dispatching
                                                                                                                                                                 (banque) Save
```

Can you spot the differences?

Going back to links with AJAX completely kills the accessibility and looses the semantics benefits.

I also made this pull request now because we're supposed to prefer small changes and AJAX is a nice refinement but not a requirement.

I'd much prefer having this merged and polished during the 3.9 release cycle (since you freezed 3.8 in the meantime anyway) rather than having it sitting around rotting.

I'd like to also point that it is very annoying to report an issue, have zero comments, build the thing and get trashed at the last minute. This is not worth my time!

**Comment by eldy** [comment]
I agree it looks better. But it looks only.
When a permission is inherited, what is the permission of user ?  We must see permission is "on" but we must also still be able to set the permission to user (as a permission specific for user, no inherited) and remove it. Only inherited status could not be modified..
If you use only one checkbox, how can you manage this ? If checkbox is checked because permission is on because inherited, how can we set permission to this user only (box is already checked) ?

**Comment by rdoursenaud** [comment]
I don't understand the issue here.
My code's behavior is the same as the current:
If permission is inherited, it's active (ticked) and can't be changed (disabled).

**Comment by eldy** [comment]
You say 
If permission is inherited, it's active (ticked) and can't be changed (disabled).
With old code, you can still set the permission specificaly to user.
With new one, there is only on boolean. With old one, there was two: first is to say if permission is inherited or not, second was to say if permission was set specificaly tp user or not.

You have 3 states:
1) permission inherited and permission for user not set (We must see the user has permission because inherited. We must also still be able to set and unset permission of user. New code does not allow this. A permission "specific to user" is a permission user won't loose if permission is removed from group so no more inherited)
2) permission inherited and permission for user set (We must see user has permission because it was set specifically to user. We must still be able to set and unset this specific permission of user. New code does not allow this)
3) permission not inherited and permission for user set or not set

So new code differs for state 1 and 2. Is it more clear ?

**Comment by rdoursenaud** [comment]
I don't see any tri-state in the current GUI.
If the permission is inherited, the links are replaced with the text "inherited" with no way to change it!
I understand that the underlying code can lead to have a sorta tri-state (by combining local and inherited permissions) but it's currently not shown.
Adding this feature would be nice but has nothing to do with my PR since there's no regression.
Or maybe I'm just dumb or something…
capture d ecran de 2015-10-15 14-27-29

**Comment by tomours** [comment]
With the current UI, we can do 2) but not 1).

With the new one, you can't do any, so you lose the ability to unset user permission to a user that has inherited permission. But as you can't set it, it seems more logical.

The best solution would be to allow doing both 1) and 2), but it requires to show at least 2 columns.

**Comment by rdoursenaud** [comment]
@eldy I understand that closing old PR is a necessity to keep yourself focused but I would have liked to get a reply… I re-red the thread and still don't grasp what's missing. I can't improve the design without a crystal clear understanding.

**Pull request closed without merging**
