### PR TITLE
NEW Enable all types of fees in expense reports

### PR DESCRIPTION
**Pull request by ymollard**
# NEW Enable all types of fees in expense reports
Some fee types were not enabled by default and no UI setting allowed to enable them

### CODE REVIEW

**Comment by atm-maxime** [comment]
Hi. I think there are doubles. Fuel, hotel, péage already exists (ex_fue, ex_hot, ex_toll...)

**Comment by ymollard** [comment]
Yes, however they start with a different prefix `EX_` and are separated by a blank line from the other `TF_`. Does it mean anything?
Also most `EX_` are not active by default and can't be activated from the UI. Should be active more of them by default?

**Comment by atm-maxime** [comment]
What do you mean "can't be activated from the UI" ? Differences between prefixes is not a problem.

**Comment by ymollard** [comment]
> What do you mean "can't be activated from the UI" ?

There is no button so that a regular user activate them (e.g. in the module settings).

**Comment by atm-maxime** [comment]
All data such as expense report types (of payment methods, currencies, ...) are managed in the dictionaries section, not in a module setup. From there you can activate/add/edit whatever value you want

**Comment by ymollard** [comment]
Hum, ok.
In that case this PR has no reason to be, and i guess that I should instead edit the user doc of the HRM module to tell them how to enable the other types of expenses that are deactivated by default.

**Pull request closed without merging**
