### PR TITLE
T921 I have put the date in the same line of draft orders and draft prop...

### PR DESCRIPTION
**Pull request by PaulPoulain**
...osals

### CODE REVIEW

**Comment by eldy** [comment]
Conflict, can your merge and push again ?

**Comment by PaulPoulain** [comment]
Hi eldy, against which branch do you try to merge ? (we're doing our work against 3.3.2 branch, maybe that's where we don't do the same thing. In this case, we will resubmit the patch against master)

**Comment by eldy** [comment]
Le 08/07/2013 18:07, Paul Poulain a écrit :

> Hi eldy, against which branch do you try to merge ? (we're doing our
> work against 3.3.2 branch, maybe that's where we don't do the same
> thing. In this case, we will resubmit the patch against master)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/1051#issuecomment-20616333.

The correct branch is not "master" (just forget it), but "develop".
Howvere, there is a conflit that make me not possible to validate merge.
Can you try a merge from develop branch, solve conflict and push again ?

## 

Eldy (Laurent Destailleur).

EMail: eldy@destailleur.fr
Web: http://www.destailleur.fr

Dolibarr (Project leader): http://www.dolibarr.org
To make a donation for Dolibarr project via Paypal: contact@destailleur.fr
AWStats (Author) : http://awstats.sourceforge.net
To make a donation for AWStats project via Paypal: contact@destailleur.fr
AWBot (Author) : http://awbot.sourceforge.net
CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by PaulPoulain** [comment]
eldy = could you try again please, patch has been rewritten

**Comment by PaulPoulain** [comment]
pull request 921 based on 921-develop sent a few minuts ago

**Pull request closed without merging**
