### PR TITLE
New: Develop new add dorade model

### PR DESCRIPTION
**Pull request by atm-gauthier**

### CODE REVIEW

**Comment by eldy** [comment]
What is difference with rouget ?
If it is only one more column, adding an option (may be hidden) just to show/hide the column into rouget model is better. We should not maintains several model just because of one minor change.

**Comment by atm-gauthier** [comment]
Hello Laurent,
I understand, i just did it on rouget model.
Hope it will be good now !

**Comment by atm-maxime** [comment]
Hi @eldy ,

The point is that I need to choose my model because some customers want amounts in their delivery receipt, some don't. That's why we need 2 models.

But you gave me an idea that we could allow the user to choose amongst all PDF options just before generation.

Cheers.

**Comment by simnandez** [comment]
@atm-maxime then we can close the PR?

**Comment by atm-gauthier** [comment]
@simnandez this feature could be useful for many people, so we just have to know if @eldy agrees to keep 2 different models or only 1.
I think we should not close this PR before that.

**Comment by eldy** [comment]
There is so many variant on templates that having several templates each time we need a variant is not possible. I prefer to see variant management supported by external modules or companies.
A good way to build an external module that do nearly the same than the one provided with Dolibarr is to create a template that inherit of dolibarr embedded template. Take a look the way we did with the "proformat" template htdocs/core/modules/commande/doc/pdf_proforma.modules.php.
It inherit the "pdf_eistein" template so a change in core template will work into your alternative template.

And you overwrite only the function you need with the variant if you can, or you set on the fly a hidden option in constructor of you variant so it will be used into the core template.

**Pull request merged**
