### PR TITLE
PSR-2 coding standards compliant sniffer

### PR DESCRIPTION
**Pull request by rdoursenaud**

### CODE REVIEW

**Comment by rdoursenaud** [comment]
@eldy The Travis CI error is obviously the result of the more stringent sniffer.
Do you want me to also PR the fixes to the coding style ? In this same PR or separately ?

**Comment by eldy** [comment]
The rule "PSR2" is not implemented in all tools. For example on my dev. Making checkstyle completely not working on my ubuntu. So i prefer to have each rule of PSR explicitely defined into php checkstyle file. I would prefer to have generic rule with a comment  instead of only 1 rule that is PSRx for 2 reason: First: it will works on all env (including my ubuntu). Second, it is more clear which rule is a rule added by dolibarr or coming from the PSR standard.

**Comment by rdoursenaud** [comment]
PSR2 is part of PHP_CodeSniffer since v1.4.0 we are at 1.5.4. You obviously have a very outdated version on your system. It's usually installed through pear, so you're responsible for it's upgrade.
Your argument here is invalid.

Please try `sudo pear upgrade PHP_CodeSniffer`

For your second argument, I don't understand how copying the entire standard will make it more clear than importing it from a known, well maintained source. The maintenance cost is too high for us to afford. Importing the standard and adding our own exceptions is the way to go. No doubt about it and that's exactly what I've done here.

**Comment by eldy** [comment]
Saying into a file we must match PSR2 just means nothing.

However saying we must not have windows carriage return, and not using
lower case for xxx has more a sense for me. It is in that way i think it is
more "clear". Also we will probably don't want full PSR2 but we would like
probably some exceptions. It is also another way why i would prefer to have
details of rules into setup files instead of just one rule.

2014-09-08 11:59 GMT+02:00 Raphaël Doursenaud notifications@github.com:

> PSR2 is part of PHP_CodeSniffer since v1.4.0 we are at 1.5.4. You
> obviously have a very outdated version on your system. It's usually
> installed through pear, so you're responsible for it's upgrade.
> Your argument here is invalid.
> 
> Please try sudo pear upgrade PHP_CodeSniffer
> 
> For your second argument, I don't understand how copying the entire
> standard will make it more clear than importing it from a known, well
> maintained source. The maintenance cost is too high for us to afford.
> Importing the standard and adding our own exceptions is the way to go. No
> doubt about it and that's exactly what I've done here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/1842#issuecomment-54797827.

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/awstats_project

**Comment by rdoursenaud** [comment]
The whole purpose of adhering to a _standard_ is to **not** have to manage it ouselves. You just sound like you contracted the NIH syndrome.

**Comment by marcosgdf** [comment]
Hi @rdoursenaud, I think this PR is more or less the same as this one https://github.com/Dolibarr/dolibarr/pull/1740

**Comment by rdoursenaud** [comment]
@marcosgdf True, great minds think alike ;)

**Comment by eldy** [comment]
To make things easier to discuss, I prefer to have rule enabled/disabled once at time, once per PR.

**Comment by rdoursenaud** [comment]
Well I found that the commits were self-explenatory and nicely splitted but your call anyway.

**Pull request closed without merging**
