### PR TITLE
Projects enhancements

### PR DESCRIPTION
**Pull request by rdoursenaud**

### CODE REVIEW

**Comment by simnandez** [comment]
Can you resolve conflicts?

**Comment by rdoursenaud** [comment]
Oh crap, I rebased it during devcamp to avoid such hassle…
Will try and do that tomorrow!

**Comment by rdoursenaud** [comment]
Code diverged too much…
I'm a bit mad loosing all this good work from @marcosgdf but I can't spend any more time trying to reconcile.
:disappointed:

**Comment by braito4** [comment]
It's a pity...

**Pull request closed without merging**
