### PR TITLE
FIX transverse display

### PR DESCRIPTION
**Pull request by ptibogxiv**
only display entity in transverse mode

### CODE REVIEW

**Comment by hregis** [comment]
@ptibogxiv 
can you explain your problem ?

**Comment by hregis** [comment]
@ptibogxiv 
in transverse mode all groups and users are created in master entity, no need to list the entities!
if you have a group that was created in a child entity before activating the transversal mode, edit/save the group so that it is assigned to the main entity and converted to a global group.

**Comment by ptibogxiv** [comment]
@hregis Hello, the problem is the opposite. I have list of all group in no transverse mode in master entity with forbidden error when I try to edit page. So with this fix, in no transverse mode, we have corect display in transverse active or not. 

List of user is OK.

**Comment by hregis** [comment]
@ptibogxiv @eldy 
you see all groups in NO transverse mode only if you are a "superadmin" and only in master entity!

**Comment by ptibogxiv** [comment]
@hregis Yes but we can't edit them... 😅 So no utility... It's better have the same behavior that the user list. In no transverse mode, we dont' need list all groups if we can't see all user too... 

No transverse mode: list of users and groups only in their own entity and can create / edit them in each entity

In transverse mode: list all users and groups in the master entity create /edit only in master entity

 It's more efficient

**Comment by hregis** [comment]
@ptibogxiv @eldy 
it's already the case ! Are you connected with the "superadmin"?

**Comment by ptibogxiv** [comment]
@hregis @eldy yes I 'm connected with superadmin and no it's not already case with dolibarr v9 😅  display isn' t correct for groups list. 

Users list is OK in each mode. I have just take code in user list page to have the same

**Comment by hregis** [comment]
@ptibogxiv @eldy 
and if you change this line in /group/card.php
`
$result = restrictedArea($user, 'user', $id, 'usergroup&usergroup', 'user');`
by
`$result = restrictedArea($user, 'user', $id, 'user&usergroup', 'user');`

the fourth parameter `usergroup&usergroup` is wrong !
first `usergroup@` is for the rights (eg $user->rights->user->***)
`$user->rights->usergroup->***` not exists !

**Comment by hregis** [comment]
@ptibogxiv @eldy

sorry !! my previous comment is wrong !!!
this is a bug in Multicompany module !

**Comment by ptibogxiv** [comment]
@hregis @eldy Indeed I have this since my last update of your module (last update in dolistore).

**Comment by hregis** [comment]
@ptibogxiv @eldy 
part of fix https://github.com/Dolibarr/dolibarr/pull/10686
fix is completed in branch 9.0 of multicompany

**Pull request closed without merging**
