### PR TITLE
clone of propal improvements

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by altairis-tof** [comment]
replacement for pull request #1340

**Comment by eldy** [comment]
OK for the feature.
However the Travis-CI report there is some error into your push. Probably because of this line
if (empty(MAIN_KEEP_REF_CUSTOMER_ON_CLONING)) $this->ref_client  = '';
you should use
if (empty($conf->global->MAIN_KEEP_REF_CUSTOMER_ON_CLONING)) $this->ref_client  = '';

Note your should link your git account with a travis account so you will automatically receive information when there is a bug into your push:
http://www.dolibarr.org/component/content/article/1-announces/152-a-new-continuous-integration-platform

**Comment by altairis-tof** [comment]
fixed

**Comment by eldy** [comment]
There is still error into integration continuous platform due to bad comment.

I validate commit and i fix the error manually, but you really must follow the guideline here http://www.dolibarr.org/component/content/article/1-announces/152-a-new-continuous-integration-platform to link your git account to travis to avoid submiting PR with control quality errors. If yuo have problem in setting this, just send email to dev mailing list.

**Comment by altairis-tof** [comment]
linking between travis and github done !
i hope it will improve my  work.
thanks

Le 24/01/2014 10:33, Laurent Destailleur a écrit :

> There is still error into integration continuous platform due to bad 
> comment.
> 
> I validate commit and i fix the error manually, but you really must 
> follow the guideline here 
> http://www.dolibarr.org/component/content/article/1-announces/152-a-new-continuous-integration-platform 
> to link your git account to travis to avoid submiting PR with control 
> quality errors. If yuo have problem in setting this, just send email 
> to dev mailing list.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Dolibarr/dolibarr/pull/1381#issuecomment-33208808.

## 

Christophe Battarel
Responsable technique
sarl altairis
Informatique et Web en Grésivaudan
33 Grande Rue
38570 Goncelin
09 52 71 70 96 (appel local)
contact@altairis.fr
http://www.altairis.fr

**Pull request merged**
