### PR TITLE
Add header and footer to TakePOS receipt

### PR DESCRIPTION
**Pull request by andreubisquerra**
Possibility of add header and footer to avoid edit source code to customize the receipt.

### CODE REVIEW

**Comment by aspangaro** [comment]
Hello @andreubisquerra ,

Please add only new language key in en_US. Another language is managed in Transifex.

Thanks

**Comment by andreubisquerra** [comment]
> Hello @andreubisquerra ,
> 
> Please add only new language key in en_US. Another language is managed in Transifex.
> 
> Thanks

Ok, sorry!
I'll do it next time.
Thank you!

**Comment by AurelGDN** [comment]
Whithin my config, custom header and footer texts are not saved in the wysiwyg doleditor instances when hitting "save" button... Other genuine settings are correctly stored.
is somoene can reproduce this unexpected behaviour ?

**Comment by andreubisquerra** [comment]
Yes, you are in right.
Other user commited changes and now save button don't work.
We will fix this issue.
Thank you!

**Pull request merged**
