### PR TITLE
Set and edit fk_currency for customer and supplier

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by ghost** [comment]
I could missed something, but I have not seen the payment management in your PR ?

**Comment by frederic34** [comment]
For the moment, things which are working:
Proposal in any currency, adding a product will convert its price in proposal's currency
Orders create from proposals, Order in any currency, adding a product will convert its price in order's currency
Invoice is in progress
Payment of invoice from bank account in same currency
or from a "caisse" account in the same currency.
Ex : invoice in dollar, you want to pay with euro account: you make "currency transfert" from euro bank account to virtual dollar bank account and then pay with virtual dollar account.

I want to make changes without breaking anything until you activate multicurrency module (I hope...)

**Comment by frederic34** [comment]
In fact I just wanted to make a supplier order in dollars....

**Comment by BebZ** [comment]
Waw, Perfect! but then how you record the invoice and the payment ? With a future PR ?
Maybe you will find time to push such a quality-ful PR for invoices and payments ?

**Comment by eldy** [comment]
Can you explain more the sentence:
"Proposal in any currency, adding a product will convert its price in proposal's currency" ?

If i make a proposal of 100 euros
Then i make a proposal of 50 dollars.
What is content of field total_ttc ? Is it 150 or is it 130 (when 50 dollars is around 30 euros).

**Comment by frederic34** [comment]
Example : Main currency is euro, I make a proposal in dollars US, adding a product which cost 100€ ttc it's make a proposal of 136$ ttc
Field total is 136 and field fk_currency is USD

**Comment by eldy** [comment]
Sorry, my question was not clear :
If you make a proposal of 100 euros
Then you make a proposal of 50 dollars.
What is sum of all fields total_ttc into table llx_propal ? Is it 150 or is it 130 (when 50 dollars is around 30 euros).

**Comment by frederic34** [comment]
It's why I want to add a new field (currency_rate) to calculate sum of all fields, Sum will be (100/1)+(50/1.666667) = 130

**Comment by eldy** [comment]
Yes we need a new field. But we cant add a new field to store the 130. This must be done into current field because all field total_ttc must be store with same currency. 
If we add a new field, we must use it to store original amount into the original currency (so the 50 dollars), but we can share into same field (total_ttc) values that sometimes are euro and sometimes are dollar. This will make all features making total into dolibarr wrong (so all reports, all tests on payments done/todo, ....)
So i don't think this PR is on the good way.
Mutlicurrency is a very complex feature. To have a multicurrency included into core, we must first share the way of working. A first try was done on this page:
http://wiki.dolibarr.org/index.php/Draft:Multi-Currency
But currently, specifications on this page are not yet finished and still have problems with no solution.

So i can't include this PR. All tries to enter multicurrency into dolibarr core code was refused for same reason, specifications must be clear before on wiki so i am sure what we are doing won't break anything.

**Comment by frederic34** [comment]
J'avais bien lu le wiki "multi currency light", et il n'était pas question d'ajouter un champ pour stocker le "130" mais pour stocker le taux de change du document, le total_ttc étant stocké dans la monnaie du document.

**Comment by BebZ** [comment]
i think I understood Eldy because he means if we have documents with different currencies everywhere inDolibarr statistics will be false everywhere... 
For example if you want to see how many customer's invoices you made last month you in 1, 2 or 5 currencies you will see a number... which one is it ... or 2 numbers or 5 numbers each one in its own currency ?

This way is source of errors, if you stock the value of the currency inside a proposal, document or else, it will false your stats. If you define the document to use default crrency + 1 (fk_) or others foreign currencies, then it can work, but at any moment you can change the "per-default" totals which for the moment are in €uros.

But this is a good sense to think in this way. Maybe we could allow to set a field named does this document use "foreign currencies" and if yes define new vales inside... the defaultone : EUR, and when we want to activate another one we can check this oneand have sub-totals, in EUR, USD , etc...

**Comment by frederic34** [comment]
I think stats is not the problem, you can have a look at propalestats.class.php :
$sql = "SELECT date_format(p.datep,'%m') as dm, SUM(p.".$this->field.")";
will become :
$sql = "SELECT date_format(p.datep,'%m') as dm, SUM(p.".$this->field."/p.".$this->currency_rate.")";
and in this way you have correct stats in main currency
If you don't use multicurrency, currency_rate is by default 1 and it change nothing
Everywhere you have SUM(total_ttc) you can transform with SUM(total_ttc/currency_rate) to display correct stats.
To pay an invoice in USD, you use a bank account in USD, in this way no change in payment processing. If you want to pay invoice in USD with bank account in EUR you have to create a currency transfer (TODO) in a bank account in USD, and then pay with the USD account

**Comment by eldy** [comment]
Having  SUM($this->field."/p.".$this->currency_rate)  is surely not enough.
You will have ton of errors in calculation because of rounding. Also, any
other tools using fields of table will report wrong information.
Import/Export will also be wrong and a lot of other things like check of
amount paid compared to dure to pay.

The field "total_xxx" must always contains data of the "main currency" of
company. If we want to store a second currency amount, we must store this
into another field.

2014-07-06 10:45 GMT+02:00 frederic34 notifications@github.com:

> I think stats is not the problem, you can have a look at
> propalestats.class.php :
> $sql = "SELECT date_format(p.datep,'%m') as dm, SUM(p.".$this->field.")";
> will become :
> $sql = "SELECT date_format(p.datep,'%m') as dm,
> SUM(p.".$this->field."/p.".$this->currency_rate.")";
> and in this way you have correct stats in main currency
> If you don't use multicurrency, currency_rate is by default 1 and it
> change nothing
> Everywhere you have SUM(total_ttc) you can transform with
> SUM(total_ttc/currency_rate) to display correct stats.
> To pay an invoice in USD, you use a bank account in USD, in this way no
> change in payment processing. If you want to pay invoice in USD with bank
> account in EUR you have to create a currency transfer (TODO) in a bank
> account in USD, and then pay with the USD account
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/1671#issuecomment-48106286.

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/awstats_project

**Comment by yehanny** [comment]
Hi Eldy and company, I'm really interested in this feature of Multi-currency for proposal/orders/invoices my suggestion it's to use the Product/Service Price registration in different fields for currencies just like the option **"Several segment of prices per product/service"** But we can have another option like **"Several currency of prices per product/service"** so if we have a Product for example the first price field is in Dollar (100) and second field in Euro (130) and then if the Client's country is United States for example, we select it's currency matching the country (in this case will be US Dollar) and then if the product if available in this price we select from the product matching field US Dollar (100) if not, then we get and error message saying _"This product is not available in your currency"_, the final proposal/order/invoice will be always in same currency because we take the value from it's main Location and also if the Several segment option doesn't change anything in the core I believe this extra option will work as well, any comments? Thanks!

**Pull request closed without merging**
