### PR TITLE
DO NOT SUPPRESS DATATABLES !!!!

### PR DESCRIPTION
**Pull request by defrance**

### CODE REVIEW

**Comment by eldy** [comment]
Sorry, this library is not used by Dolibarr (it was a not supported, non official experiment that fails), so there is no reason to have it embedded into Dolibarr.
Also don't forget you MUST never rely on hidden and experimental features for your production developments.

**Comment by defrance** [comment]
OK I will take time to suppress ALL Library not used by Dolibarr, especially on pdf, jquery mobile, multicompany...
Think Cleaning time will be a long time...

**Comment by BebZ** [comment]
Childish behaviour...

**Comment by defrance** [comment]
Ta mère ne ta pas appris à ne pas te mêler des conversations des grandes personnes, tu aimes les fessées?

**Pull request closed without merging**
