### PR TITLE
allow ajax product search on description

### PR DESCRIPTION
**Pull request by altairis-tof**
allow search on product description when adding lines in documents if new constant PRODUCT_AJAX_SEARCH_ON_DESCRIPTION is set on.

### CODE REVIEW

**Comment by altairis-tof** [comment]
dont understand conflict. seems that the source of the file fetched in eclipse is different that what i see on github ???

**Comment by frederic34** [comment]
Is it because your fork is not very uptodate?
2018-10-16 15_06_42-altatof_dolibarr_ dolibarr erp crm is a modern software to manage your company o

**Comment by altairis-tof** [comment]
i've made a "fetch from upstream..." and choose dolibarr/Dolibarr.git but it seems to be useless... how do you update the fork ?

**Comment by frederic34** [comment]
did you merge upstream/develop into your branch PRODUCT_AJAX_SEARCH_ON_DESCRIPTION

**Comment by eldy** [comment]
@altatof Fetch does nothing (it just update the remote mirror on your local mirror). This is a network first step. To update your code to get all new change on your branch, you must make "merge" (=fetch + pull) or just pull if you already did a fetch.

**Comment by altairis-tof** [comment]
thanks i will look at it ... (did i mention i use git plugin for eclipse ?)
anyway, i have deleted my repo and made a new fork yesterday !

**Comment by altairis-tof** [comment]
i close this one replaced by #10227 (also in conflict i don't understand since i have just forked develop branch !)

**Pull request closed without merging**
