### PR TITLE
NEW disabled duplicate API shipping methods

### PR DESCRIPTION
**Pull request by ptibogxiv**
now we have shipment methods API

### CODE REVIEW

**Comment by eldy** [comment]
Because the API scan a table identified as a dictionary, i would keep this API and remove the other (so organiszation of API match organization of interface with all dictionary in same area). Do you have any reason to do the oposite ?

**Comment by ptibogxiv** [comment]
> Because the API scan a table identified as a dictionary, i would keep this API and remove the other (so organiszation of API match organization of interface with all dictionary in same area). Do you have any reason to do the oposite ?

because this dictionnary is call in 2 API with old and new traduction of terms

image

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/pull/16210

**Comment by eldy** [comment]
I ask different people and it seems the name 
shipping_methods is better than shipment_method.
So i suggest to keep this one.

**Pull request closed without merging**
