### PR TITLE
Add default values to extrafields

### LINKED ISSUE #10387: BUG: Default value for Extrafield of type SELECT is not working
# Bug
If you create an ExtraField of type select, it won't take the default value.
Please note that the default value must be the index of the option.

## Suggested implementation
There is a small typo on **htdocs\core\class\extrafields.class.php** on line 1086.
The $key value is checked against $value instead of $default.

Just replace the line with:
**$out.= (((string) $default == (string) $key)?' selected':'');**

Already tested and working properly.

### PR DESCRIPTION
**Pull request by mattsidnell**
# Fix #10387 Default value for Extrafield of type SELECT is not working
Extrafields for an object now shows the default value (if there is one) on creation for html, text and standard select fields.

### CODE REVIEW

**Comment by PsyCrow-code** [comment]
This BUG is come back on V18 (2024/01/11)

**Comment by hregis** [comment]
@PsyCrow-code i check and it's not possible... can you describe your problem !

**Comment by hregis** [comment]
@PsyCrow-code have you externals moduls ?

**Comment by hregis** [comment]
@PsyCrow-code @mattsidnell @eldy 

I'm going to vent but often those who develop additional modules are amateurs who make a crappy module without thinking about the consequences on the functioning of other modules or developments of dolibarr and that can create disruptions... we call that Shitty modules from incompetent, shitty developers! assholes!

**Comment by PsyCrow-code** [comment]
The default values for a line extrafield of an object like invoice is not
working.

I create 3 line extrafields for invoices, and set default values.

For a new invoice the default values doesnot work

**Comment by PsyCrow-code** [comment]
Is this, I think
https://github.com/Dolibarr/dolibarr/issues/26504

**Pull request merged**
