### PR TITLE
Completed missing keys + corrections

### PR DESCRIPTION
**Pull request by fappels**
Added missing keys and language corrections

### CODE REVIEW

**Comment by eldy** [comment]
Happy to meet you during Solution Linux congress...

**Comment by fappels** [comment]
Nice to meet you too...

I’m busy on some other language files, should I focus only on nl_BE files or also on nl_NL files.

There are some major differences like nl_BE has ’Klant’ for customer while nl_NL uses ‘Afnemer’, to my opinion ’Klant’ does sound beter for both country’s, but I don’t like to doubt the choise of nl_NL translator. 

Van: Laurent Destailleur
Verzonden: ‎donderdag‎ ‎30‎ ‎mei‎ ‎2013 ‎23‎:‎40
Aan: Dolibarr/dolibarr
CC: Francis Appels

Happy to meet you during Solution Linux congress...

**Comment by eldy** [comment]
Just do what you think is the best.
If you think a string is bas for both language, you can fix into both files.
If error is only for nl_BE, just edit nl_BE.
Do not push changes into transifex (except in "read mode") because
priority is still git push for the moment that may overwrite changes
done into transifex.

Le 31/05/2013 00:34, Francis Appels a écrit :

> Nice to meet you too...
> 
> I’m busy on some other language files, should I focus only on nl_BE
> files or also on nl_NL files.
> 
> There are some major differences like nl_BE has ’Klant’ for customer
> while nl_NL uses ‘Afnemer’, to my opinion ’Klant’ does sound beter for
> both country’s, but I don’t like to doubt the choise of nl_NL translator.
> 
> Van: Laurent Destailleur
> Verzonden: ‎donderdag‎ ‎30‎ ‎mei‎ ‎2013 ‎23‎:‎40
> Aan: Dolibarr/dolibarr
> CC: Francis Appels
> 
> Happy to meet you during Solution Linux congress...
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/1007#issuecomment-18712854.

## 

Eldy (Laurent Destailleur).

EMail: eldy@destailleur.fr
Web: http://www.destailleur.fr

Dolibarr (Project leader): http://www.dolibarr.org
To make a donation for Dolibarr project via Paypal: contact@destailleur.fr
AWStats (Author) : http://awstats.sourceforge.net
To make a donation for AWStats project via Paypal: contact@destailleur.fr
AWBot (Author) : http://awbot.sourceforge.net
CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by fappels** [comment]
I will fix the important translation errors (especialy in the Pdf's) in both nl_BE and nl_NL. Won’t bother about the better sounding items at the moment, not to confuse dutch speaking users after an update. 

How can I know when transifex gets priority, shoud I join the Savannah mailing list?

**Comment by eldy** [comment]
Yes, post should be sent onto mailing list dolibarr-dev when transifex
should be used as priority. But this may never happen because we must first
a way to solve conflicts between git and transifex and i don't find
solution for the moment...

2013/6/1 Francis Appels notifications@github.com

**Comment by fappels** [comment]
Hi Laurent,

A while ago I did some translation correction pull requests on de 
developer branch. I noticed that some of them are replaced by transiflex 
syncs, did you switch to transifex? (example: History for dolibarr / 
htdocs / langs / nl_NL / deliveries.lang)

Another question: While developing a new dolibarr module, I encountered 
a few minor bugs in some dolibarr classes, can I notify them by pull 
requests on the developer branche?

Kind regards,
Francis

**Comment by eldy** [comment]
2013/10/13 Francis Appels notifications@github.com

> Hi Laurent,
> 
> A while ago I did some translation correction pull requests on de
> developer branch. I noticed that some of them are replaced by transiflex
> syncs, did you switch to transifex? (example: History for dolibarr /
> htdocs / langs / nl_NL / deliveries.lang)

You should not have lost translation you submit. I take care about this but
may be i made an error. Sorry if i lost part of your work.
I did not sent post officially yet, but i will do it soon with this news:
"Yes, you can now use transifex, that is now the reference for all
languages except en_US that is source, fr_FR, and es_ES". So for nl_NL, yes
you can now made changes using transifex.
Wiki translation doc has been update for that:
http://wiki.dolibarr.org/index.php/Translator_documentation

> Another question: While developing a new dolibarr module, I encountered
> a few minor bugs in some dolibarr classes, can I notify them by pull
> requests on the developer branche?

Yes, of course.

**Pull request merged**
