### PR TITLE
FIX_forgeSQLFromUniversalSearchCriteria was unusable

### PR DESCRIPTION
**Pull request by atm-saamiperdrix**
forgeSQLFromUniversalSearchCriteria was unusable

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide an example of a case that was not working.
Add it as a phpunit test in method testDolForgeCriteriaCallback() and check that after the change, phpunit is ok ?

**Comment by carmelchas** [comment]
I am using version 18.x and found issues when trying to use "Form::select_thirdparty_list" with ajax select2.

    print img_picto('', '').$form->select_company('', 'socid', '((s.client = 1 OR s.client = 2 OR s.client = 3) AND s.status=1)',            'SelectThirdParty', 0, 0, null, 0, 'minwidth175 maxwidth500 widthcentpercentminusxx');
    
    
    Search produces the following error:
       "Bad syntax of the search string"
    
   I tried updating the filter to "( s.client IN (1,2,3) )" and get the same error.
   
   I see two(2) issues here:
   A.  The function does not allow for more than one condition.
   B.  The function is rejecting perfectly functional filters.

**Comment by carmelchas** [comment]
Additional example from v18

$object->fields['fk_project'] = array('type'=>'integer:Project:projet/class/project.class.php:1:fk_soc='.$thirdparty_soc_id, 'label'=>'Project', 'picto'=>'project', 'enabled'=>'$conf-  >project->enabled', 'position'=>52, 'notnull'=>-1, 'visible'=>-1, 'index'=>1, 'css'=>'maxwidth500 widthcentpercentminusxx', 'validate'=>'1',);

Here it is rejecting the filter "fk_soc=123" with the error  "Bad syntax of the search string"

**Comment by eldy** [comment]
The string syntax for filter looks wrong.
`((s.client = 1 OR s.client = 2 OR s.client = 3) AND s.status=1)`
You should have use the Universal Search Filter syntax (A structured filter string with parenthesis, AND OR and a criteria 
(operand1:operator:operand2). So
`(((s.client:=:1) OR (s.client:=:2) OR (s.client:=:3)) AND (s.status:=:1))`

**Comment by hregis** [comment]
@eldy maybe add IN in this function ? ;-)

((s.client:IN:1,2,3) AND (s.status:=:1))

**Comment by hregis** [comment]
@eldy c'est pas déjà pris en charge d'ailleurs ?

`((s.client:in:1,2,3) AND (s.status:=:1))`

**Comment by eldy** [comment]
> @eldy c'est pas déjà pris en charge d'ailleurs ?
> 
> `((s.client:in:1,2,3) AND (s.status:=:1))`

Je crois que si...
I think so ...

**Comment by hregis** [comment]
@eldy arrête de parler français on va se faire engueuler ! ;-)

**Comment by carmelchas** [comment]
Thank you! We will try this.

**Comment by carmelchas** [comment]
Je m'excuse de ne pas avoir tenté de poser ma question en français. :-(
Merci. Nous allons essayer cette approche.

**Comment by hregis** [comment]
@carmelchas tu as bien fait de ne pas parler français ! ;-) c'était un joke ! il est préférable de parler anglais... voir américain ! ;-)

**Comment by carmelchas** [comment]
Lol.

**Pull request closed without merging**
