### PR TITLE
Corrected Timezone detection by using jstz external library

### PR DESCRIPTION
**Pull request by marcosgdf**
Corrected Timezone detection by using jstz external library

Bundled timezone detection generated incorrect timezone names, so Dolibarr wasn't able to generate dates properly

### CODE REVIEW

**Comment by rdoursenaud** [comment]
:+1: Tested and approved!

The Travis errors are just PHPCS finally working correctly :p

**Comment by eldy** [comment]
Even if this is a bug, introducing new library is an architecture change that should be included into develop (http://wiki.dolibarr.org/index.php/Category:RoadMap)
Can you make the PR for develop ?

**Comment by rdoursenaud** [comment]
@eldy FWIW you can merge to develop manually:

```
git checkout -b marcosgdf-bug-timezone 3.5
git pull https://github.com/marcosgdf/dolibarr.git bug-timezone
git checkout develop
git merge --no-ff marcosgdf-bug-timezone
git push origin develop
```

Another approach if you don't want to merge 3.5 changes is to use rebase:

```
git checkout -b marcosgdf-bug-timezone 3.5
git pull https://github.com/marcosgdf/dolibarr.git bug-timezone
git rebase develop
git checkout develop
git merge --no-ff marcosgdf-bug-timezone
git push origin develop
```

**Comment by marcosgdf** [comment]
So I should push the PR to develop instead of 3.5?

**Comment by eldy** [comment]
Yes

**Comment by marcosgdf** [comment]
#3061

**Pull request closed without merging**
