### PR TITLE
FIX in_numeric not exists

### PR DESCRIPTION
**Pull request by hregis**

### CODE REVIEW

**Comment by mdeweerd** [comment]
This is also part of #26264 .

**Comment by hregis** [comment]
@mdeweerd yes but my fixe is for v18

**Comment by hregis** [comment]
@mdeweerd ok I close my PR thanks

**Comment by mdeweerd** [comment]
@hregis I am not familiar with your flow, but you are correct to mention that this applies to several versions that are under maintenance.

**Pull request closed without merging**
