### PR TITLE
NEW Add more company informations (ProfId7 to 10)

### PR DESCRIPTION
**Pull request by dolibarr95**
# NEW [Add more company informations]

Related to the issue Feature Request #25214 

Add 4 more company information (as EORI number for ex).
User can now register his "EA - exportateur agréé" number or other Id number (EE - exportateur enregistré...) 
These  numbers will be used in the pdf footer.

### CODE REVIEW

**Comment by eldy** [comment]
EORI is already saved into ProfID5

**Comment by dolibarr95** [comment]
Hello @eldy 
_Tks for the answer, Sorry for misunderstanding_

Yes ProfID5 is EORI, I wanted to give an example of number already registerd in Dolibarr.

What we have now : 

- SIREN
- SIRET
- NAF-APE
- RCS/RM
- EORI
- ProfID6 ( could be EE "Exportateur Enregistré" number if we define it in langs\xx_XX\companies.langs file)
- TVA

What we could have : 
- SIREN
- SIRET
- NAF-APE
- RCS/RM
- EORI
- ProfID6
- ProfID7  ( could be EA "Exportateur Agréé" number if we define it in langs\xx_XX\companies.langs file)
- ProfID8
- ProfID9
- ProfID10
- TVA

Tks for reading

**Comment by dolibarr95** [comment]
Hello
@eldy what do you think of this #25296 instead of #25266

Tks for reading

**Comment by eldy** [comment]
I am still trying to understand the use case of the "EA" number to see how it is generic or not. 
My understanding is that :
- A company has a EA number if it has already an EORI number
- It seems it is a number for the company managed by Dolibarr, no need for thirdparties (customers or prospects).
- this field must be added on bottom of PDF generated with the other profid info (like SIRET, VAT number, ...)

Am i right ? Do you have more info ?

**Comment by dolibarr95** [comment]
Hi @eldy 
Yes EA number is mandatory in our documents (invoices...) it's the "bureau de douane ( -> customs office ?)".

**Comment by eldy** [comment]
Because EA nulber is used only for the managed company 
, i suggest to add it into setup page if company with a llx_const variable
MYSOC_EA_NUMERO
and set it into $mysoc->idprof_ea (property to add into mysoc class)

**Comment by scopcop** [comment]
> # NEW [Add more company informations]
> Related to the issue Feature Request #25214
> 
> Add 4 more company information (as EORI number for ex). User can now register his "EA - exportateur agréé" number or other Id number (EE - exportateur enregistré...) These numbers will be used in the pdf footer.

please i added that to the codes to show that information i add to insert like Rib in the Pdf near the other information like R.C.: - Patente: and I.F in the bottom

**Pull request merged**
