### PR TITLE
NEW Moved some account and account transactions logic to Account and AccountLine

### PR DESCRIPTION
**Pull request by marcosgdf**
NEW Moved some account and account transactions logic to Account and AccountLine classes

Functions:
- Account::getUnconciledTransactions
- Account::getConciledTransactions
- AccountLine::getLabel
- AccountLine::getPaymentType
- AccountLine::increaseValueDate
- AccountLine::decreaseValueDate
- AccountLine::addUrl

Deprecated the following functions:
- AccountLine::datev_next
- AccountLine::datev_previous
- Account::add_url_line

Improved documentation of Account class and created `TYPE` and `STATUS` constants. Also refactored the way the account number is shown to the user by creating some auxiliar functions called:
- Account::__toString
- Account::getFieldsToShow
- Account::getAccountNumberOrder

Please ask any doubts about the changes.

### CODE REVIEW

**Comment by marcosgdf** [comment]
Travis CI build failure has nothing to do with this PR

**Comment by eldy** [comment]
Sorry, The PF affect so many files, that there is a lof of conflict. Is it possible to submit this refactoring code by several pieces of PR, instead of one larger. This will be easier for me to validate it ?

**Comment by marcosgdf** [comment]
I've resolved the conflicts. And there are not that much changes, the thing is that some of them depends on the other and because PR acceptance is very slow, all the changes could take around ~3 months being merged…

I've moved some logic to the classes and therefore pages are starting to treat objects instead of SQL results. With that advantage I was able to refactor some things, like the label of the transaction and so on… If you really want me to split them, I'll do it but I think with 15-20 minutes you'll understand all the changes.

**Comment by eldy** [comment]
Delay of accepting pr does not change anything on number of conflict. Currently delay are very short compared to any other projet, they will probably be increased to let more time for people to discuss about pr. It is the order of merging pr and the number that create conflicts or not and small pr are always processed in priority.
Also 15-20 mn is too much to validate a pr. If pr can t be understand in 30s, it just mean pr should not be validated.

Because number of pr submitted each week increase, conflict will become more frequent (more developers are submitting code that make the opposite of other developers). Having small pr can reduce the risk.

**Pull request closed without merging**
