### PR TITLE
FIX only keep pmp price if set in margin setup

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
FIX only keep pmp price if set in margin setup
- pmp price was selected by default even if it was'nt set in margin setup

### CODE REVIEW

**Comment by eldy** [comment]
Don't understand the fix. What do you mean with "keep pmp price" ?

**Comment by lvessiller-opendsi** [comment]
@eldy 
If "costprice" is set in margin setup, we have "pmp" price selected by default in prices select list when you add a product.
For example in order card, when you want to add a product and "pmp" and "cost" prices are not null, you have "pmp" price selected by default instead of having "cost" price.

**Comment by eldy** [comment]
If "costprice" is set in margin setup, it means: "Autoselect the costprice if defined, else pmp else best vendor price else 0". To summarize, it measn "costprice first, but not only costprice". The goal is to have always something set the most accurate as possible so margin error is lower as possible.

Are you sure a costprice was set on the product ? if not, having the PMP set as a fallback is the expected behaviour.

**Comment by lvessiller-opendsi** [comment]
@eldy 
Example : 
- you set "costprice" in margin setup
- you have a product with "costprice" and "pmp" defined
- you add a product line and "pmp" price was selected by default instead of "costprice"

**Comment by lvessiller-opendsi** [comment]
@eldy 
You're right, it was fixed in "FIX #12875" and costprice is seleced by default even if pmp price is defined.

**Pull request closed without merging**
