### PR TITLE
New making product from virtual products

### PR DESCRIPTION
**Pull request by atm-quentin**
# New making product from virtual products
Add a button to create a kit on virtual products to create kits and increase stock (decrease components). This button open a window allowing you to enter the quantity of kits to be composed and let you choose warehouses. This action will create the corresponding stock movements.

### CODE REVIEW

**Comment by BebZ** [comment]
Wow, this includes management of batch/serials on the products consumed/stocked ?

**Comment by BebZ** [comment]
FeatureDoesntHandleLotBatch=Cette fonctionnalité ne prend pas en compte les numéros de lots et séries

**Comment by atm-quentin** [comment]
No actually i don't have time to handle batch/serials for this feature, that's why i specified it in conf, sorry :S

**Comment by eldy** [comment]
The goal of virtual product is not to make production.
By definition a virtual product is something that does not exists and so has no stock.

If you need that, it means your virtual product is in fact a BOM and your fabrication is in fact a Manufacturing Order.

**Comment by atm-quentin** [comment]
Ok, i know some companies using virtual product to do that, we'll probably need to give possibility to convert virtual product to bom

**Pull request closed without merging**
