### PR TITLE
NEW Show permission text in admin module overview

### PR DESCRIPTION
**Pull request by ghost**
# New
This PR adds the requested function to show the original untranslated permission text of a module (#14665 @Tim-Otte)
To reduce user and admin confusion the column with the permission text is only shown when it selected in the column menu.

Hope you like it.

## Picture (without permission text)
2020-09-24 13_37_19-Dolibarr

## Picture (with permission text)
2020-09-24 13_37_33-Dolibarr

## Picture (with search of a permission text)
2020-09-24 13_39_00-Dolibarr

### CODE REVIEW

**Comment by Tim-Otte** [comment]
Nice. Is there any way to select the language of the permission text? This would be helpful because most of the permission labels are in french.

**Comment by ghost** [comment]
> 
> 
> Nice. Is there any way to select the language of the permission text? This would be helpful because most of the permission labels are in french.

I take the permission labels direct from the module without any translation, so it is the original text of the translation inside the module before the translation do anything. IMHO think that help most for the developer to find the permission inside the module.

I know the most things are in French in the modules. We should translate the permission into English (in the modules) in the next time.

**Comment by Tim-Otte** [comment]
You're right. Nicely done. 👍

**Comment by eldy** [comment]
Goal of this page is to show the list of modules. Adding the details of label of each permission provided by the module generated a duplication of each record with as many line that there is permission. Also what about the modules that does not provide any permission ?
A better way to present the permissions for each module (each line) would be to show labels (into language of user) as a popup of each id or as full text with id into parenthesis separated by a comma.

**Comment by eldy** [comment]
A popup with information has been introduced into v14

**Pull request closed without merging**
