### PR TITLE
Activate HTML5

### PR DESCRIPTION
**Pull request by aspangaro**
First work on HTML5 - Login page - Only available in Eldy template (No test with the others templates).

Test realized on Apple Iphone 4 & Ipad mini.

Any help is welcome!

Need feature_level 2 & need enable option in admin->GUISetup  :
html5button

### CODE REVIEW

**Comment by jfefe** [comment]
Good option but why is it an option?

Also into login page... why use a table for a simple image? HTML5 is cool, but semantic usage is better :)

**Comment by jfefe** [comment]
Sorry table is not for logo but for username / pass
Anyway, table are useless into login page :\

**Comment by aspangaro** [comment]
Hi jfefe !

Why an option ? I think rewriting lot of code need time. At the end, the goal is to remove the option. For the login , I work  on a page without table. I publish this PR to find people who help me.

**Comment by frederic34** [comment]
Hello Alexandre
I think it will be better to make separate PR with typo or langage correction.

**Comment by eldy** [comment]
In main, the modified line 
print '<!DOCTYPE html>';
should have a condition on option MAIN_ACTIVATE_HTML5, shouldn't it ?

**Pull request merged**
