### PR TITLE
[NEW] PDF width picture option

### PR DESCRIPTION
**Pull request by BB2A-Anthony**

### CODE REVIEW

**Comment by BB2A-Anthony** [comment]
@eldy It's ok for you?

**Comment by eldy** [comment]
Because this option is used only if option on the second page pdf_other is set, can you move it at bottom of pdf_other.php page ?

**Comment by BB2A-Anthony** [comment]
@eldy it's done.

**Comment by eldy** [comment]
PR merge are very frequent noways. Still got a conflict with another dev. Can you help me to fix.

**Comment by BB2A-Anthony** [comment]
> PR merge are very frequent noways. Still got a conflict with another dev. Can you help me to fix.

@eldy it's done.

**Comment by BB2A-Anthony** [comment]
@eldy it's not good fix suggest ?

**Pull request merged**
