### PR TITLE
fix #11764 Virtual Product: allow negativ number of sub products

### LINKED ISSUE #11764: Virtual Product: allow negativ number of sub products
# Bug
Currently only positive number of sub products is allowed, we also need the possibility for negative numbers as long as the new BOM-module is not mature. In earlier releases this was possible but has been changed for unknown reasons.

## Environment
- **Version**: [9-10-]

## Expected and actual behavior
Currently only positive number of sub products is allowed, we also need the possibility for negative numbers as long as the new BOM-module is not mature. In earlier releases this was possible but has been changed for unknown reasons.

### PR DESCRIPTION
**Pull request by fbosman**
# Instructions
*This is a template to help you make good pull requests. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Fix", "Close" or "New" section*
- *follow the project [contributing guidelines](/.github/CONTRIBUTING.md)*
- *replace the bracket enclosed textswith meaningful informations*

# Fix #[*issue_number Short description*]
[*Long description*]

# Close #[*issue_number Short description*]
[*Long description*]

# New [*Short description*]
[*Long description*]

### CODE REVIEW

**Comment by eldy** [comment]
This feature will allows users to use the "virtual products" to make "manufacturing". This seems great but this is not the goal of the feature and we are working on a "manufacturing" module that will suits better such need so it appears dangerous to introduce such a feature that will be in conflict with another one currently in development.

Can you describe your use case why you need negative value for virtual product ?

**Comment by atm-maxime** [comment]
related to #11764

**Comment by fbosman** [comment]
Laurant,
Yes you are right, this way this setup can be used in manufacturing. This is exact the reason we need it. 
The current BOM-module is not mature and cannot be used for our purpose and the Factory module is too heavy for our case.
We just want to manage the stock of components for our product (cans of Ghee, consists of glass pots, covers and Ghee-content).
At the moment the BOM module is good enough for our purpose we will start using that module as this is intended for this kind of business.
Do you know who is working on this module? maybe we can set up some requirements and perhaps some funding.

As fat as I know in the past it was possible to have a negativ amount of subproducts in a virtual product, but in time this had been removed.

regards,
Frans

**Comment by fbosman** [comment]
Do you agree @eldy?

**Comment by fbosman** [comment]
ping @eldy

**Comment by eldy** [comment]
@fbosman I want to avoid to have the feature "virtual stock" used for Manufacturing because it was not designed for and may have very vicious side effect that we won't be able to control.

The module BOM seems mature in the develop branch. It will be ready/stable for v11
However, the module BOM without the module Manufacturing Order is useless. For the moment i am the only one to work on the module Manufacturing Order. I hope to have it ready for v11 too...
Feedback of what currently exists into the MO module are however welcome...

**Comment by eldy** [comment]
Update: The Manufacturing Order module is now ready into the develop branch.

**Comment by eldy** [comment]
BOM + Manufacturing Orders module are nos stable in v12, so i close this PR

**Pull request closed without merging**
