### PR TITLE
Add possibility to change package dimension after shipping creation

### PR DESCRIPTION
**Pull request by ghost**
Allow user to change package dimension units on card after creation (otherelse, you need to delete expedition in case of error)

### CODE REVIEW

**Comment by BebZ** [comment]
Thanks for this useful function ;) 
...I bet your next ATM module will be on packaging levels of products, details on shipment about which product is in which carton, no ?

**Comment by ghost** [comment]
thanks,

details on shipment already exist under our module "dispatch" ;) 

It's not on store for now, but it could be in few weeks (don't know when we'll package it)

**Comment by BebZ** [comment]
And do you a a demo previw or explanations screenshots of the processes ?

**Comment by ghost** [comment]
You can see our demo (in French) here : http://dolibarr.atm-consulting.fr/

Go in a expedition, you'll see a details tab allow you to sépcify the product and lot number (and when our asset module is installed - not on demo -, the specific asset)

**Comment by BebZ** [comment]
I see, we have to go to another tab to check wich product is in which carton, and it is not managed by stock (for the moment i use the same method, but with a pen, and the delivery receipt).

Module is functionnal, but very time-consuming compared to Batch-Dluo which is integrated yet and linked with stock. 

Maybe will you plan to make your module compliant to the one in the core (batch/dluo)
and also able to manage product's different levels of packaging ?

Thanks anyway for all the nice works you are doing on Dolibarr :)

**Comment by eldy** [comment]
Because this is a "locking" case, i think this is relevant to bug, so i validate i for 3.6  beta

**Pull request merged**
