### PR TITLE
Hide hourmins

### PR DESCRIPTION
**Pull request by IonAgorria**
This hides hours and/or minutes if service duration is big enough to make it irrelevant

### CODE REVIEW

**Comment by eldy** [comment]
Can you explain more what you mean with first commit "form change to add duration"
When you sell service, the service has a duration, then, when creating a proposal or invoice, you enter the qty that define how many time you take the service (duration can be 1month and quantity 12 for one year)
So why adding duration into form ?

**Comment by IonAgorria** [comment]
The duration is used so we can hide the hour/min boxes in "Hide hours/minutes if duration unit is big" commit.

Also in the next pull the date checking needs duration unit/value for ensuring that date range is big enough. But I can't without accepting this because I need to change some common files between this and next one.

**Comment by braito4** [comment]
We try to improved time management services based in the duration. This made dolibarr more proactive showing hours, mins fileds based in the duration of the service.
Example, if you have a service which has a duration based in days; you need (apart from the day) the hour when you start the service; the mins are irrelevant.
But if you have a service with the duration is based on hours; the mins became relevant (00, 30, 45, etc)... and so on

**Comment by braito4** [comment]
Also the duration isn't the quantity of the service. for example, if you are a Hotel; and someone spend 3 days in a room:
the quantity is , the room you are occupying.
If the service you are using has a cost per night; then the cost of the service is the time you are there \* number of days.
That's why the duration could be used to calculate the cost of the service.

**Comment by IonAgorria** [comment]
I should wait for this pull to create the "date check" pull? there are some code that are shared betwen this and the other

**Comment by eldy** [comment]
If you sell days room, with a cost per night, for 3 night, qty will be 3.
To go forward with this PR, is it possible to submit it in 2 PR.
One for dc54840 and for de5d1cd
The other one for 445c224

**Comment by braito4** [comment]
@eldy The way you're telling is "fine" right now, but at some point in dolibarr roadmap you`re going to split the information between the time that the service is taken and how many unique services you're selling.
For example, we are working in resources module. In this module you can create a resource(room, car, etc).
This resource can be used in a service, for example, a car. the service it will be renting a car; the duration of the service is for hours (10€). if someone rent a car for a week, i just put the range of the time that the car was rent (and dolibarr just calculates the cost of that) and in quantity put 1, the car they are renting.
(The quantity means the number or resources that they're renting). This way i can track the resources that my clients are using. if i put 164 in quantity just means that i've rent 168 cars....
Anyway, this is just a glimpse.
This pull only allow us to track the duration. This one does not change the price.

**Comment by eldy** [comment]
You try to use the contract module in a way that it was not designed for.
A service is something that is defined by a product you hire (a card that is a product or a resource if you try to use this instead, why not), but also a cost  (10 euros per hour). So duration unit for qty is the hour.
If you have 2 cars, you rent it for one week and the other for 2 hours, you should have:
- One service, Car, qty 168.
- One other service, Car 2, qty 2.
  You should have 2 lines in the contract, because it is 2 different services (different resource, different duration, and may be different price, even price per duration can be changed)
  You can still track everything, natively.

If you use it the way you try to use it, statistics on product consumption will be wrong, compatiblity with the future "invoicing subscription" feature will just be broken, also you need to add code to have price calculation working when this is already working currently.

**Comment by braito4** [comment]
My example was simple...
The module we are working works this way:
You create a resource: car, room, etc. This one could be simple (just track busy states) or schedule (you create a schedule for this resource, for example, a room that you use it for 1 day (all days) for a year.
then you create a service with a desire duration. you going have a tab resources in witch one you add all the resources that can be use by this service (maching duration). So, if you have a hotel with 10 rooms, you add it to the service; also you can create dependences between different resources (room+extra bed).
So when you sell the service, dolibarr finds the available resource to the service and this one became busy.
Again, this only works with resources. I'm fine witch your way; but i think that for this case i would work better this way; we can sort the things out.
This is the repository https://github.com/IonAgorria/dolibarr/tree/resources 
An it's far advance right now.

**Pull request closed without merging**
