### PR TITLE
FIX filter supplier invoice list by societe name.

### PR DESCRIPTION
**Pull request by tarrsalah**

### CODE REVIEW

**Comment by hregis** [comment]
@tarrsalah 
english language is prefered

**Comment by tarrsalah** [comment]
@hregis  in the PR title or in the code?

**Comment by hregis** [comment]
@tarrsalah 
in the code, "company" is prefered instead "societe"

**Comment by tarrsalah** [comment]
Hello @hregis, I fixed the naming issue and squashed the two commits, is it ready for merge now?

**Pull request merged**
