### PR TITLE
New branch 29 06 2019

### PR DESCRIPTION
**Pull request by grandoc**

### CODE REVIEW

**Comment by jtraulle** [comment]
@grandoc Can you merge current develop branch into your PR branch (this will fix the code style issue by using the new SticklerCI integration that was deployed earlier).

**Comment by grandoc** [comment]
Hello Jean
Was it what you're asking me to do ?

**Comment by ksar-ksar** [comment]
https://youtu.be/eHqhf7qXEjQ

Sorry grandoc I'm out

**Comment by jtraulle** [comment]
> Hello Jean
> Was it what you're asking me to do ?

Exactly what you've done :) Thanks !

**Pull request merged**
