### PR TITLE
Restler

### PR DESCRIPTION
**Pull request by rdoursenaud**
This PR brings back the composer autoloader. Removing it has done more harm than good and it's required to use modern PHP libraries properly.

We have a whole release cycle ahead of us to see if there are any adverse side effects, but I expect us to have zero issue.

@jfefe's work on Restler is awesome and sorely needed to bring Dolibarr forward and won't work properly without the autoloader.

### CODE REVIEW

**Comment by jfefe** [comment]
@rdoursenaud is right : without autoloader, API pages produces a lot of PHP warnings. 

@eldy please bring back Composer :+1:

**Comment by rdoursenaud** [comment]
@jfefe Just for clarification, it's not composer but it's autoloader that's needed ;)

**Comment by jfefe** [comment]
About API, see #3548 for patch. Merged into develop branch : https://github.com/Dolibarr/dolibarr/pull/3549

**Comment by rdoursenaud** [comment]
Yes except your fix isn't working properly. It spits out a ton of errors (Warnings about not being able to include required classes are errors to me.) making it totally unusable. The only proper fix I know about is the one suggested here.

**Comment by jfefe** [comment]
@rdoursenaud is right : when logging activate, PHP produces a loooooot of warning and API doesn't work at all.

@eldy please accept autoloader from composer . Not because it's a nice tool but we need this if we don't want Dolibarr to finish as an OsCommerce-like

**Comment by eldy** [comment]
I don't see relation between a bad feature like autoloader that allows developers to code like cows and oscommerce. 
If we have warning appears just because autoload is not activated, this demonstrate how the api is bad quality coded. It just mean: if system choose the api randomly it works, and if the system choose the api defined explicitely by developer, it does not. We can't accept such things. I prefer to have bad code fixed where things are wrong than saying, it is easier like that because it seems to works like that. I will try to fix myself, but i need to understand how this api works and it is not yet clear. Can you provide an example on how we can test a call of an api on develop branch ? Better, can you add such a test into phpunit, we could not introduce api if we don't have at least one test to guarantee/test the architecture.

**Comment by rdoursenaud** [comment]
Autoloader is now a f*cking PHP standard. The libraries simply comply with it.
Modern libraries require you to use autoloading in your project and simply does not provide any other means of importing them because they use it internally to resolve their own friggin' dependencies !!!
And you still refuse to understand what the composer autoloader is doing.
It's not loading classes at random, it's loading classes from libraries explicitly installed based on their name and namespace explicitly declared in your code. It's not that magic!
It also helps performance by only loading actually used classes.
It's just the very same concept as shared libraries in every OS: you explicitly link to them (composer) but they are resolved at runtime (autoloader).
Yes the PHP autoloading mechanism sucks ass compared to other languages and shit may happen but that's all we got for now. Let's move forward and hope for the best. Staying stuck in the past won't help anything except code rotting and community demotivation.

**Comment by eldy** [comment]
I would like to make some test to make a final decision on how to solve this. Does someone can explain me how we can make a test of one service that use restler ? An example of url to use to get a thirdparty for example (even if it fails currently because of the autoload problem, I would like to understand better and make some test on my side, but i have no way to understand how this API should work) ?

**Comment by eldy** [comment]
up
someone to provide me a 2 lines doc on how we should make a call of apis of the rest api module, with an example ?

**Comment by jfefe** [comment]
Since you have remove it, we can't make API to work without composer :)

**Comment by rdoursenaud** [comment]
The beauty of restler is that it's auto documenting.
Once you set an API key to your user (on its card), you can access the documentation at /public/api/explorer/index.html
For there on, everything should be self-explanatory since REST APIs are very easy to use but feel free to ping me if needed.
Of course, this will only work with the bug fixed or checkout somewhere around the 1ffb28a revision ;)
For more informations, here's the project site http://www.luracast.com/products/restler

**Comment by ParisLiakos** [comment]
Yes please..Working the last week with dolibarr is a pain without an autoloader..have to always remember to iclude my class files first and with correct order..
Even without restler this should be in already..Like already mentioned its a standard and pretty much every PHP project/library uses it. Ignoring it only harms adoption imho

**Comment by eldy** [comment]
My request is still open, can someone provide me an example on how to make an API test call ?
For example, a small code sample to create a thirdparty ?
I can't progress without that...

**Comment by eldy** [comment]
I did a maxi debug on this feature, rewrote a lot of part.
I also moved the explorator. Also the explorator was not working and too difficult to debug and is not a user feature. I replaced it with the dolibarr admin page into setup of module webservice REST that provide list of exposed services with no need of extra tool.

REST should works correctly now. Waiting for tests.

**Pull request closed without merging**
