### PR TITLE
FIX virtual stock for virtual product

### PR DESCRIPTION
**Pull request by ghost**
[Review on Reviewable](https://reviewable.io/reviews/dolibarr/dolibarr/3316)

### CODE REVIEW

**Comment by eldy** [comment]
I don't think we should increase nb of products into stats when the parent of a product is included into an order. If we do so, we should also do it for all other reports to have behaviour working the same way everywhere.
I suggest a first step to introduce a hidden feature to enable to count recursive records and start to change reports at different place and keep standard behaviour "stats is for direct product".

**Comment by eldy** [comment]
Duplicate with #5188

**Comment by altairis-tof** [comment]
PR #5188 is much more complete and should be reviewed because it was closed with bad reasons

**Comment by eldy** [comment]
@atm-alexis Can you push this PR on develop ?

**Comment by eldy** [comment]
@atm-alexis Can you push this PR on develop ?

**Pull request closed without merging**
