### PR TITLE
FIXED : display prices with 2 digits after comma

### PR DESCRIPTION
**Pull request by aconits**
Change price2num() function by price() to display price with better format in ODT files.

### CODE REVIEW

**Comment by jfefe** [comment]
Be careful : it seems Libreoffice/OpenOffice use comma (,) in numbers. Using a dot (.) will surely break ODS files calculations. 
Please make a test before merging changes.

**Comment by ndrosis** [comment]
Hi @atm-ph try without changes by placing the tag in _locale example {object_total_ttc_locale}

**Comment by eldy** [comment]
The goal of function
get_substitutionarray_object
is to replace a substitution key with "universal" number (with no formatting). Formatting is no goal of this function, at least not goal of tag [object_total_ttc}.
So we must keep the substitution array as it is.
If there is format to do for odt, code should included into the module that generate odt but not into this generic function.

**Comment by atm-maxime** [comment]
Hello,

Ok understood, but in this case  this means we should do the opposite fix, meaning to replace every call to "price" function by price2num. Some values are using price, other price2num...

Currently, this is the same module used for odt or ods, so we don't have anywhere else to deal with it.

We propose to keep current tags for the formatted version of values (with price function) and duplicate these tags with an extension (_num for example) to have the non formatted value (with price2num function). We would do it this way because we think that most people is using this is with ODT rather than ODS.

**Comment by atm-maxime** [comment]
Hi @ndrosis !
I just saw your comment and you're right.
Non formatted value should be {total_ht} for example, when formatted should be {total_ht_locale}. That's what I intended with adding "_num" vars, didn't saw that "_locale" already existed...

I'll tal to @atm-ph about it to complete the function and have all values available.

Thanks

**Pull request closed without merging**
