### PR TITLE
quickadd menu like bookmarks

### LINKED ISSUE #17922: Improve "Quickadd dropdown" style
# Feature Request
I would like to change the current "style" of the quickadd dropdown
image

to show up like the bookmarks dropdown
Like so:
image

I would love to get some input on this. I would get on this very soon.

### PR DESCRIPTION
**Pull request by cfoellmann**
This gives the quickadd dropdown a style like the bookmarks dropdown.
SEE 
Closes #17922

### CODE REVIEW

**Comment by eldy** [comment]
Can't be merged yet. Still in draft.

**Comment by cfoellmann** [comment]
it is working but I am not really happy with the display. especially on mobile.
Is there any plans to enhance the display of these dropdown menus on mobile in general?

**Comment by cfoellmann** [comment]
Can be merged. The display on mobile is the same as the other dropdown menus. Not good but ok.

**Comment by cfoellmann** [comment]
sorry for the branch changes. I just realized that 14.0 is already released so adding it to 14.0 would be bad practice

**Comment by cfoellmann** [comment]
DO NOT MERGE yet-
I can not go back to draft but I want to change this some more!!

**Comment by cfoellmann** [comment]
ready for merge!

usage of the hook:

```php
public function arrayDropdownQuickaddItems( $parameters, &$object, &$action, $hookmanager ) {

	    global $user, $dolibarr_main_url_root;

	    // add menu item
	    $object['items'][] = array(
		    "url" => $dolibarr_main_url_root . "/custom/module/module.php?action=create&mainmenu=project",
		    "title" => "NewItem@module",
		    "name" => "Item@module",
		    "picto" => "object_service",
		    "activation" => $user->rights->module->item_create->write,
		    "position" => 35,
	    );


	    // remove "Services" item by position value
	    $key1 = array_search(110, array_column($object['items'], 'position'));
	    unset($object['items'][$key1]);

        return 1;

    } // END arrayDropdownQuickaddItems()
```

This adds a menu item at position 35 and removes the services menu item by identifying the position value of this item

**Comment by cfoellmann** [comment]
@eldy rebased onto current develop branch.
now with proper hook name

**Comment by cfoellmann** [comment]
I squashed the commits to not pollute the history too much

**Comment by cfoellmann** [comment]
all maintainers: anything "wrong" or to change on this feature?

@eldy: how about a chat session to close as many PRs and issues as possible in a big team affort?

**Comment by cfoellmann** [comment]
@Eldy maybe rename the hook.

**Comment by cfoellmann** [comment]
image

Working state

**Comment by cfoellmann** [comment]
@eldy This is still viable and without merge conflicts

**Comment by cfoellmann** [comment]
please let me know if there is anything to change for this to be merged into dev for 15.x

**Pull request merged**
