### PR TITLE
FIX : Link in knowledge records

### PR DESCRIPTION
**Pull request by atm-adrien**
## FIX : Link in knowledge records

The field "answer" was displayed by the dolEditor object.
But this must be used only for edit and create view otherwise the links can not work.

Before : 
image

After : 
image

### CODE REVIEW

**Comment by eldy** [comment]
Because the solution of a km article is the main article. It was designed on purpose to have the message on all the width of the page. Thus allow the show the article that can be a full web page content.

**Comment by atm-adrien** [comment]
Ok, but, with this solution, no link entered in the article will be functional.
Do you have a solution that I could implement to solve this problem?

**Comment by atm-maxime** [comment]
Maybe just display the answer on the full width of the screen not only half left.
Another inconvenient of the ckeditor is that the height is limited and displays a scrollbar

**Comment by atm-adrien** [comment]
I created a new PR that refers to this one: https://github.com/Dolibarr/dolibarr/pull/25173

**Comment by atm-adrien** [comment]
I created a new PR that refers to this one: https://github.com/Dolibarr/dolibarr/pull/25173

**Comment by atm-maxime** [comment]
@eldy what is the point of having this textearea displayed in readonly with ckeditor ?

**Pull request closed without merging**
