### PR TITLE
Updating invoice notes 32134

### LINKED ISSUE #32134: Issue Detected in Dolibarr API 20.0.2: Updating Invoice Notes
### Bug

Context
In Dolibarr version 20.0.2, we have encountered an issue when attempting to update the public and private notes of an invoice using the API endpoint PUT /invoice/{id}. This behavior differs from the previous version, where this functionality worked correctly.

### Dolibarr Version

20.0.1 ; 20.0.2

### Environment PHP

7.3.33

### Environment Database

MySQL or MariaDB 8.0.37

### Steps to reproduce the behavior and expected behavior

Problem Description

Use Case:

We attempt to update the public and private notes of an invoice by sending an HTTP PUT request to the API endpoint PUT /invoice/{id}.
The payload sent includes the fields for the notes. For example:

{ { "fk_user_author": "10", "fk_user_valid": "10", "fk_user_modif": "1", "datem": 1732790063, "delivery_date": null, "ref_client": null, "ref_customer": null, "total_ht": "112.00000000", "total_tva": "23.52000000", "total_localtax1": "0.00000000", "total_localtax2": "0.00000000", "total_ttc": "135.52000000", "revenuestamp": "0.00000000", "resteapayer": null, "paye": "0", "module_source": null, "pos_source": null, "fk_fac_rec_source": null, "fk_facture_source": null, "lines": [ { "fk_facture": "965", "fk_parent_line": null, "desc": "", "ref_ext": "", "localtax1_type": "3", "localtax2_type": "1", "fk_remise_except": null, "rang": "0", "fk_fournprice": null, "pa_ht": "0.00000000", "marge_tx": "", "marque_tx": 100, "tva_npr": null, "remise_percent": "20", "batch": "", "fk_warehouse": "0", "origin_id": null, "fk_code_ventilation": 0, "date_start": "", "date_end": "", "situation_percent": "100", "fk_prev_id": null, "label": null, "ref": "P-3", "libelle": "Producto P3", "product_type": "0", "product_ref": "P-3", "product_label": "Producto P3", "product_desc": "", "qty": "1", "subprice": "110.00000000", "price": null, "fk_product": "16", "vat_src_code": "", "tva_tx": "21.000", "localtax1_tx": "0.000", "localtax2_tx": "0.000", "remise": null, "total_ht": "88.00000000", "total_tva": "18.48000000", "total_localtax1": "0.00000000", "total_localtax2": "0.00000000", "total_ttc": "106.48000000", "date_start_fill": null, "date_end_fill": null, "buy_price_ht": null, "buyprice": null, "info_bits": "0", "special_code": "0", "fk_user_author": null, "fk_user_modif": null, "fk_accounting_account": "0", "parent_element": "", "fk_parent_attribute": "", "id": "1581", "rowid": "1581", "fk_unit": null, "date_debut_prevue": null, "date_debut_reel": null, "date_fin_prevue": null, "date_fin_reel": null, "weight": null, "weight_units": null, "width": null, "width_units": null, "height": null, "height_units": null, "length": null, "length_units": null, "surface": null, "surface_units": null, "volume": null, "volume_units": null, "multilangs": null, "description": "", "product": null, "product_barcode": null, "fk_product_type": "0", "duree": null, "multicurrency_subprice": "110.00000000", "multicurrency_total_ht": "88.00000000", "multicurrency_total_tva": "18.48000000", "multicurrency_total_ttc": "106.48000000", "module": null, "entity": null, "import_key": null, "array_options": [], "array_languages": null, "contacts_ids": null, "linkedObjectsIds": null, "origin_type": null, "statut": null, "status": null, "state_id": null, "region_id": null, "demand_reason_id": null, "transport_mode_id": null, "shipping_method": null, "multicurrency_tx": null, "multicurrency_total_localtax1": null, "multicurrency_total_localtax2": null, "last_main_doc": null, "fk_account": null, "lines": null, "actiontypecode": null, "date_creation": null, "date_validation": null, "date_modification": null, "tms": null, "date_cloture": null, "user_author": null, "user_creation": null, "user_creation_id": null, "user_valid": null, "user_validation": null, "user_validation_id": null, "user_closing_id": null, "user_modification": null, "user_modification_id": null, "fk_user_creat": null, "specimen": 0, "extraparams": [], "cond_reglement_supplier_id": null, "deposit_percent": null, "retained_warranty_fk_cond_reglement": null, "warehouse_id": null }, { "fk_facture": "965", "fk_parent_line": null, "desc": "", "ref_ext": "", "localtax1_type": "3", "localtax2_type": "1", "fk_remise_except": null, "rang": "0", "fk_fournprice": null, "pa_ht": "0.00000000", "marge_tx": "", "marque_tx": 100, "tva_npr": null, "remise_percent": "20", "batch": "", "fk_warehouse": "0", "origin_id": null, "fk_code_ventilation": 0, "date_start": 1730329200, "date_end": 1761865200, "situation_percent": "100", "fk_prev_id": null, "label": null, "ref": "S-3P1", "libelle": "Suscripción 3P1", "product_type": "1", "product_ref": "S-3P1", "product_label": "Suscripción 3P1", "product_desc": "", "qty": "1", "subprice": "30.00000000", "price": null, "fk_product": "90", "vat_src_code": "", "tva_tx": "21.000", "localtax1_tx": "0.000", "localtax2_tx": "0.000", "remise": null, "total_ht": "24.00000000", "total_tva": "5.04000000", "total_localtax1": "0.00000000", "total_localtax2": "0.00000000", "total_ttc": "29.04000000", "date_start_fill": null, "date_end_fill": null, "buy_price_ht": null, "buyprice": null, "info_bits": "0", "special_code": "0", "fk_user_author": null, "fk_user_modif": null, "fk_accounting_account": "0", "parent_element": "", "fk_parent_attribute": "", "id": "1582", "rowid": "1582", "fk_unit": null, "date_debut_prevue": null, "date_debut_reel": null, "date_fin_prevue": null, "date_fin_reel": null, "weight": null, "weight_units": null, "width": null, "width_units": null, "height": null, "height_units": null, "length": null, "length_units": null, "surface": null, "surface_units": null, "volume": null, "volume_units": null, "multilangs": null, "description": "", "product": null, "product_barcode": null, "fk_product_type": "1", "duree": null, "multicurrency_subprice": "30.00000000", "multicurrency_total_ht": "24.00000000", "multicurrency_total_tva": "5.04000000", "multicurrency_total_ttc": "29.04000000", "module": null, "entity": null, "import_key": null, "array_options": [], "array_languages": null, "contacts_ids": null, "linkedObjectsIds": null, "origin_type": null, "statut": null, "status": null, "state_id": null, "region_id": null, "demand_reason_id": null, "transport_mode_id": null, "shipping_method": null, "multicurrency_tx": null, "multicurrency_total_localtax1": null, "multicurrency_total_localtax2": null, "last_main_doc": null, "fk_account": null, "lines": null, "actiontypecode": null, "date_creation": null, "date_validation": null, "date_modification": null, "tms": null, "date_cloture": null, "user_author": null, "user_creation": null, "user_creation_id": null, "user_valid": null, "user_validation": null, "user_validation_id": null, "user_closing_id": null, "user_modification": null, "user_modification_id": null, "fk_user_creat": null, "specimen": 0, "extraparams": [], "cond_reglement_supplier_id": null, "deposit_percent": null, "retained_warranty_fk_cond_reglement": null, "warehouse_id": null } ], "line": null, "extraparams": [], "fac_rec": null, "date_pointoftax": "", "situation_cycle_ref": null, "situation_counter": null, "situation_final": "0", "tab_previous_situation_invoice": [], "tab_next_situation_invoice": [], "retained_warranty": "0", "retained_warranty_date_limit": "", "retained_warranty_fk_cond_reglement": "0", "availability_id": null, "date_closing": null, "source": null, "remise_percent": null, "online_payment_url": "https://xxxxx.com/xxxxx/public/payment/newpayment.php?source=invoice&ref=FA2410-0023", "title": null, "type": "0", "subtype": null, "fk_soc": null, "socid": "22", "date": 1730329200, "date_lim_reglement": 1730329200, "cond_reglement_id": "1", "cond_reglement_code": "RECEP", "cond_reglement_label": null, "cond_reglement_doc": "Réception de facture", "mode_reglement_id": "3", "mode_reglement_code": "PRE", "totaldeposits": null, "totalcreditnotes": null, "sumpayed": null, "sumpayed_multicurrency": null, "sumdeposit": null, "sumdeposit_multicurrency": null, "sumcreditnote": null, "sumcreditnote_multicurrency": null, "remaintopay": "135.52", "stripechargedone": null, "stripechargeerror": null, "description": null, "close_code": null, "close_note": null, "postactionmessages": null, "module": null, "id": "965", "entity": "1", "import_key": null, "array_options": [], "array_languages": null, "contacts_ids": [], "linkedObjectsIds": { "commande": { "1397": "768" } }, "fk_project": null, "contact_id": null, "user": null, "origin_type": null, "origin_id": null, "ref": "FA2410-0023", "ref_ext": null, "statut": "1", "status": "1", "country_id": null, "country_code": null, "state_id": null, "region_id": null, "demand_reason_id": null, "transport_mode_id": null, "shipping_method_id": null, "shipping_method": null, "fk_multicurrency": "0", "multicurrency_code": "EUR", "multicurrency_tx": "1.00000000", "multicurrency_total_ht": "112.00000000", "multicurrency_total_tva": "23.52000000", "multicurrency_total_ttc": "135.52000000", "multicurrency_total_localtax1": null, "multicurrency_total_localtax2": null, "last_main_doc": "facture/FA2410-0023/FA2410-0023.pdf", "fk_account": null, "note_public": "NEW tooo PUBLIC", "note_private": "NEW tooo PRIVATE", "actiontypecode": null, "name": null, "lastname": null, "firstname": null, "civility_id": null, "date_creation": 1730371423, "date_validation": 1730371423, "date_modification": 1732790063, "tms": null, "date_cloture": null, "user_author": null, "user_creation": null, "user_creation_id": "10", "user_valid": null, "user_validation": null, "user_validation_id": "10", "user_closing_id": null, "user_modification": null, "user_modification_id": "1", "fk_user_creat": null, "specimen": 0, "product": null, "cond_reglement_supplier_id": null, "deposit_percent": null, "warehouse_id": null, "fk_incoterms": "0", "label_incoterms": null, "location_incoterms": "" } }

Observed Behavior:

The request is accepted (HTTP 200), but the notes are not updated in the database when the full invoice payload is sent.
This issue occurs only through the API.
Expected Behavior:

The notes should update correctly, as they did in the previous version.
Additional Details:

If we send only the notes in a simplified payload, they update correctly:

{ "note_public": "Updated public note", "note_private": "Updated private note" }

From the web interface, the functionality works as expected. Notes are updated without any issues.

Conclusion:
This issue appears to be related to how the API processes the PUT /invoice/{id} request when a full payload is sent.

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by JonBendtsen**
FIX #32134 Updating Invoice Notes
throw RestException(500) if update of invoice fails

### CODE REVIEW

**Comment by JonBendtsen** [comment]
replaced with #32190

**Comment by natalieboucher** [comment]
In the new version 20.0.3 it still does not work.

If you extract an invoice with GET /invoices/{id} and the resulting JSON is returned with a PUT /invoices/{id} the system returns a 500 error.

{
  "error": {
    "code": 500,
    "message": "Internal Server Error: Error Cannot add or update a child row: a foreign key constraint fails (XXXXXX.llxpn_facture, CONSTRAINT fk_facture_fk_facture_source FOREIGN KEY (fk_facture_source) REFERENCES llxpn_facture (rowid))"
  },
  "debug": {
    "source": "api_invoices.class.php:699 at call stage",
    "stages": {
      "success": [
        "get",
        "route",
        "negotiate",
        "authenticate",
        "validate"
      ],
      "failure": [
        "call",
        "message"
      ]
    }
  }
}
If we remove “”fk_project": null, from the JSON everything works correctly including the private and public notes.
It would be appreciated if you could fix these corrections.

Thank you

**Comment by hregis** [comment]
@natalieboucher try with "fk_projet" (real name of field in database) instead "fk_project"
@eldy maybe adding a "synonym" parameter in "$fields" array in order to be able to determine the name of the field used if it is different from the name in the database ? (eg id/rowid, fk_soc/socid, etc...)

**Comment by natalieboucher** [comment]
perfect, it's ok version 20.0.4 . Thank you

**Pull request closed without merging**
