### PR TITLE
NEW: all current columns in llx_extrafields can now be seen in the json

### PR DESCRIPTION
**Pull request by JonBendtsen**
NEW: API GET /setup/extrafields now include all llx_extrafield columns in JSON.
This pull request will export all the columns from the table llx_extrafields when generating the JSON as an answer to the GET /setup/extrafields API call.

### CODE REVIEW

**Comment by JonBendtsen** [comment]
New output

```
{
  "commande": {
    "one": {
      "id": "5",
      "type": "varchar",
      "label": "one",
      "size": "255",
      "elementtype": "commande",
      "default": null,
      "computed": null,
      "unique": "0",
      "required": "0",
      "param": {
        "options": {
          "": null
        }
      },
      "pos": "101",
      "alwayseditable": "1",
      "perms": null,
      "list": "1",
      "printable": "0",
      "totalizable": "0",
      "langs": null,
      "help": null,
      "css": null,
      "cssview": null,
      "csslist": null,
      "fk_user_author": "1",
      "fk_user_modif": "1",
      "datec": "2024-04-01 09:44:09",
      "tms": "2024-04-01 09:44:09"
    }
  }
}
```

**Comment by JonBendtsen** [comment]
old output
```
{
  "commande": {
    "one": {
      "type": "varchar",
      "label": "one",
      "size": "255",
      "elementtype": "commande",
      "default": null,
      "computed": null,
      "unique": "0",
      "required": "0",
      "param": {
        "options": {
          "": null
        }
      },
      "pos": "101",
      "alwayseditable": "1",
      "perms": null,
      "list": "1"
    }
  }
}
```

**Comment by JonBendtsen** [comment]
```
JonSweet16:class jonbendtsen$ diff -y /tmp/old_order_extrafields.json /tmp/new_order_extrafields.json  -W70
{					{
  "commande": {				  "commande": {
    "one": {				    "one": {
				  >           "id": "5",
      "type": "varchar",		      "type": "varchar",
      "label": "one",			      "label": "one",
      "size": "255",			      "size": "255",
      "elementtype": "command		      "elementtype": "command
      "default": null,			      "default": null,
      "computed": null,			      "computed": null,
      "unique": "0",			      "unique": "0",
      "required": "0",			      "required": "0",
      "param": {			      "param": {
        "options": {			        "options": {
          "": null			          "": null
        }				        }
      },				      },
      "pos": "101",			      "pos": "101",
      "alwayseditable": "1",		      "alwayseditable": "1",
      "perms": null,			      "perms": null,
      "list": "1"		  |           "list": "1",
				  >           "printable": "0",
				  >           "totalizable": "0",
				  >           "langs": null,
				  >           "help": null,
				  >           "css": null,
				  >           "cssview": null,
				  >           "csslist": null,
				  >           "fk_user_author": "1",
				  >           "fk_user_modif": "1",
				  >           "datec": "2024-04-01 09
				  >           "tms": "2024-04-01 09:4
    }					    }
  }					  }
}                                        }
```

**Review by eldy — APPROVED** [review]

**Comment by hregis** [comment]
@JonBendtsen i don't understand ! what is the differecence with the result in the client of API ?

**Comment by JonBendtsen** [comment]
> ```
> JonSweet16:class jonbendtsen$ diff -y /tmp/old_order_extrafields.json /tmp/new_order_extrafields.json  -W70
> {					{
>   "commande": {				  "commande": {
>     "one": {				    "one": {
> 				  >           "id": "5",
>       "type": "varchar",		      "type": "varchar",
>       "label": "one",			      "label": "one",
>       "size": "255",			      "size": "255",
>       "elementtype": "command		      "elementtype": "command
>       "default": null,			      "default": null,
>       "computed": null,			      "computed": null,
>       "unique": "0",			      "unique": "0",
>       "required": "0",			      "required": "0",
>       "param": {			      "param": {
>         "options": {			        "options": {
>           "": null			          "": null
>         }				        }
>       },				      },
>       "pos": "101",			      "pos": "101",
>       "alwayseditable": "1",		      "alwayseditable": "1",
>       "perms": null,			      "perms": null,
>       "list": "1"		  |           "list": "1",
> 				  >           "printable": "0",
> 				  >           "totalizable": "0",
> 				  >           "langs": null,
> 				  >           "help": null,
> 				  >           "css": null,
> 				  >           "cssview": null,
> 				  >           "csslist": null,
> 				  >           "fk_user_author": "1",
> 				  >           "fk_user_modif": "1",
> 				  >           "datec": "2024-04-01 09
> 				  >           "tms": "2024-04-01 09:4
>     }					    }
>   }					  }
> }                                        }
> ```

@hregis  here is the difference before and after

**Pull request merged**
