### PR TITLE
Posible Bug Multicompany

### PR DESCRIPTION
**Pull request by josemariagomezroncero**
It doesn't allow to shared price fourniseur. Its correct? @hregis

# Instructions
*This is a template to help you make good pull requests. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Fix", "Close" or "New" section*
- *follow the project [contributing guidelines](/.github/CONTRIBUTING.md)*
- *replace the bracket enclosed textswith meaningful informations*

# Fix #[*issue_number Short description*]
[*Long description*]

# Close #[*issue_number Short description*]
[*Long description*]

# New [*Short description*]
[*Long description*]

### CODE REVIEW

**Comment by eldy** [comment]
If the company 1 has a buying price of 100 and company 2 has a buying price of 50 (because it is a VIP client), when making a purchase order on company 1, the price suggested will be 50 instead of 100. I don't think this is what we expect. Do yo have a different use case ?

**Comment by josemariagomezroncero** [comment]
The multicompany module allow to share product, customer price and supplier price separately. 
The user can select to share or not shared the  supplier price, should it be shared in all its effects?

**Comment by eldy** [comment]
"sharing a price" between companies is a feature that is not clear and need more specification :
If there is a buying price of 100 in company 1 and a buying price or 50 in company 2, when we create a supplier order on company 1, what is the expected price ? I think we expect 100 (it is defined like this for company 1). Or do we want 50. As my user point of view i expect 100, even if sharing is one. But @hregis what is definition of "sharing price" given by the multicompany module ?

**Comment by hregis** [comment]
@eldy @josemariagomezroncero 

Regarding customer prices, by default the price field is in the llx_product table, suddenly the price is necessarily already shared between the entities if we share the products. If you modify the price in entity 1, it will be modified in entity 2. You must activate multiple prices so that each entity can have different sales prices. So sharing the prices doesn't make sense. This must be reviewed.

For supplier prices it's different, we already use a different table by default (llx_product_fournisseur_price), so sharing allows you to centralize supplier prices on one entity, and see these prices on another entity. Unless entity 2 creates its own supplier prices! It may indeed have different prices!
Maybe we should just give the possibility to customize this supplier price and see only that one, or not to give the right to modify this supplier price?

**Comment by hregis** [comment]
@eldy @josemariagomezroncero 

There is something else to review, sharing supplier prices requires sharing suppliers. For the moment we are obliged to share all third parties globally (customers and suppliers). It should be possible to define a separate sharing because an entity could have the right to see the suppliers but not the customers of the other entity! (and the opposite too). It's a big change!

**Comment by hregis** [comment]
@eldy @josemariagomezroncero 

The best solution in my opinion is that the Multicompany module adds dynamic "view" tables. This would make it possible to define price grids that could be shared between the entities. This would also allow a customer price of one entity to become a supplier price in another entity. (in the case where an entity 1 is the supplier of an entity 2 and vice versa)

**Comment by eldy** [comment]
So to summarize: For customer prices
If we have a setup to have 1 price per product, when sharing products, we already share prices.
If we use multiprices, it seems multicompany is already managed.
Good.
But here PR is about supplier prices and how to get the minimum best prices of a product among several suppliers. 
What if there is a buying price of 100 in company 1 and a buying price or 50 in company 2, when we create a supplier order on company 1, what is the expected price ? I think we expect 100 (it is defined like this for company 1). Or do we want 50 ? This is not a question about how we can technical implement this, but about the functional rule we want to have in such situation.

**Comment by hregis** [comment]
@eldy 
in my opinion, the supplier order will have the supplier prices of the entity on which we create a quote, order or invoice. If the supplier price is shared it will be this one, if the supplier price is personalized, it will take precedence over the shared price. does that seem correct to you?

I still think that integrating an operation in price grids would be more flexible.

**Comment by eldy** [comment]
I'm afraid rule does not take into account all cases.
What if there is a price P1 for company 1 for qty 1, price P2 for company 2 for qty 2, another price P3 for company 1 for qty 3 and no price for qty3 for company 2, and a price P4 for company 2 for qty 4 but no price for company 1 for qty 4.
And P3 < P1,  and P4 < P2
Company was created into company EC.
And we are working on entity EW.

Rules become complex. 
We must defined a rule for every possible combination (EC, EW, when P1 < P2, when P1 > P2, when P3 > P1, when P3 < P1, etc...). What will be each value for minimum prices foreach combination of EW / EC ?
What is the algorithm to find the best price ? How can we explain to the user what the machine decides to take as best price in an easy to understand rule ? 

Currently, it is easy, best price, is lower price defined into entity. And it is what seems to be expected in most cases. But if we share supplier prices, what will be the algorithm ?

What will be the algorithm defined using EW, EC, P1, P2, P3, P4 ?

**Comment by eldy** [comment]
Even if this PR goal is to fix a bug, it seems it introduces more problems than it solves, so request is closed.

**Pull request closed without merging**
