### PR TITLE
NEW Accountancy - transaction creation and movement on one screen

### PR DESCRIPTION
**Pull request by daraelmin**
Combination of 2 Previous PR
https://github.com/Dolibarr/dolibarr/pull/21208 - New Accountancy - 2 transactions by mvmt in creation mode
https://github.com/Dolibarr/dolibarr/pull/21016 - New Accountancy - transaction creation and movement in one single screen

These are steps 1 and 2 of #20272

Actually, we need to go through 3 screens to register one movement : 

1) When clicking on the "+" button on general ledger, you go to this screen ;

2) Then you click save, and you go to this screen ;

3) Then you click add to go to the third screen to add the second line to balance account ;

So, if you have many movements, it can be long. 

With this PR, you click "+" button, and you can register your movement and first transaction on the only screen display below:
image

### CODE REVIEW

**Comment by eldy** [comment]
Thanks. It's clear now. Will be merged in develop when branch v16 has been created

**Comment by daraelmin** [comment]
There's a issue that is a regression that must ne fixes before merge. I'm working on it.

**Comment by daraelmin** [comment]
I've fixed the PR

**Comment by eldy** [comment]
Can you help me to solve the conflict into develop branch ?

**Comment by eldy** [comment]
@daraelmin I need your help to fix conflict because i can't merge it automatically.

**Comment by daraelmin** [comment]
Hi @eldy,

I'm on hollyday, but I'll woek on it next week.

Cheers.

**Comment by daraelmin** [comment]
Hi @eldy,
The PR is now ready to merge.
Cheers

**Comment by daraelmin** [comment]
Hi @eldy,

It seems good to me now. 
I have an other PR on this file to submit to manage rows with JS, but I'm waiting on thé merging of this one.

Cheers

**Comment by daraelmin** [comment]
Hi @eldy,

This PR is ready to merge. 

Thx

**Comment by daraelmin** [comment]
Hi @eldy,

I've fixed all the conflict with this PR.

Is it ok for you now ?

Cheers

**Comment by daraelmin** [comment]
Hi @eldy,

This one is (again) ready to merge

Cheers

**Comment by daraelmin** [comment]
Seems to be ok for merge, but I'm doing more test

**Comment by daraelmin** [comment]
Hi @eldy,

Conflict are resolved in this PR

Cheers

**Comment by daraelmin** [comment]
Hi @eldy,
Could I have a feedback on this one please ? 
Will it be merged ? Or shoild I change something?
Chers and happy new year

**Pull request closed without merging**
