### PR TITLE
NEW: Move Expense report menu from module to menu files

### PR DESCRIPTION
**Pull request by aspangaro**

### CODE REVIEW

**Comment by simnandez** [comment]
This PR has conflicts that must be resolved

**Comment by aspangaro** [comment]
Conflict solved. Thanks Juanjo.

**Comment by simnandez** [comment]
Travis CI build failure has nothing to do with this commit

**Comment by simnandez** [comment]
@aspangaro It should create a sql migration from 3.9 to 4.0, to remove the menu that has been created by the activation of module in 3.9

**Comment by aspangaro** [comment]
You right Juanjo.You can integrate PR #4873.

Have a nice day !

**Pull request merged**
