### PR TITLE
FIX : According to french law, if seller is in France and buyer isn't…

### PR DESCRIPTION
**Pull request by atm-gauthier**
Law (first paragraph) :
https://www.impots.gouv.fr/portail/professionnel/prestations-aux-non-assujettis

### CODE REVIEW

**Comment by torvista** [comment]
Without going into the code, I would be surprised if rules vary across the EU...ie, is a code chunk exception necessary just for France?
eg. for Spain:
a sale from Spain to Spain: have to charge VAT.
a sale from Spain to other EU country: have to charge VAT unless the customer has a registered intra-Community VAT code.
a sale from Spain to anywhere outside the EU: it is an export and vat is not charged, But there must be an associated export document (DUA/SAD) to justify (to the local tax authority) the issuing of the invoice without vat. I know most people do not bother with the SAD, but if they get a tax inspection they are in trouble...evidence of the product being sent outside the EU is not good enough.

Is this different to anywhere else in the EU?

**Comment by atm-maxime** [comment]
Apparently french law force to charge VAT for physical customers, wherever they're located. The rule you're explaining is also true, when making business with companies.

**Comment by torvista** [comment]
Both physical customers and companies can have a registered EU vat number (at least in Spain). 
I was trading for many years as self-employed (autonomo) based on my spanish personal tax id which was a registered EU vat number, and so not paying VAT on stock purchased from other EU countries.

VAT is not charged on export, as confirmed here:
https://www.service-public.fr/professionnels-entreprises/vosdroits/F31118

> Verified April 20, 2018 - Directorate of Legal and Administrative Information (Prime Minister), Ministry of Finance
> Merchandise exports to countries outside the European Union (EU) are exempt from VAT (customs clearance) subject to certain formalities, including a declaration to the customs office.

VAT should not be charged on an export, as Customs handling in the destination country charges local VAT on import.

**Comment by eldy** [comment]
@aspangaro 
Are you able to clarify the rule when sending to "NON business" people outside of Europe (there is no problem with B2B but for B2C outside europe, it is not clear ?

A) This text say we should not apply VAT:
"https://www.service-public.fr/professionnels-entreprises/vosdroits/F31118"

B) This text say we should:
https://www.impots.gouv.fr/portail/professionnel/prestations-aux-non-assujettis

Currently dolibarr apply rule A)

**Comment by ksar-ksar** [comment]
Hi,

According to this : https://www.impots.gouv.fr/portail/professionnel/achatvente-de-biens

The only case where the vendor should apply VAT is B2C inside europe for "small amounts" because this is considered as Distance selling.

B2C outside europe is without VAT

**Comment by atm-gauthier** [comment]
I talked with @eldy , i'm going to put a hidden conf to choose what we want to do.
By default, we'll use what Dolibarr applied until now, and hidden conf will allow to use product VAT.

**Pull request merged**
