### PR TITLE
Cleaning the print page

### PR DESCRIPTION
**Pull request by mapiolca**
Before : Displays menus and navigation buttons when in print mode

Now : Content only.

### CODE REVIEW

**Comment by mapiolca** [comment]
@eldy This is the only way I know to re-push a PR...

**Comment by john-botella** [comment]
why dont use a simple ccs media query instead of managing display in php ? (ie 6 doesn't exist anymore ;-) )
add/or add "print-view-mode" to body class...

For exemple:
```
body.print-view-mode .side-nav-vert,
body.print-view-mode .side-nav,
body.print-view-mode .hidden-print
{
      display: none !important;
}

@media print { 
 /* All your print styles go here */
 .side-nav-vert,.side-nav, .hidden-print { display: none !important; } 
}
```
just add .hidden-print on element to hide...

And for more compatibility between theme it could be included in a common print.css stylesheet.

what do you think ?

**Comment by mapiolca** [comment]
As you want, but it’s simple to control php, the print display is common to all themes so if one theme doesn’t include this query, the user experience will be degraded, no ?

**Comment by john-botella** [comment]
what's why i talk about a common print.css stylesheet.

**Comment by mapiolca** [comment]
I see, yes it’s a good idea. So we need to see with @eldy if it’s possible to integer this file in each PHP page, or directly main.inc ?

**Comment by eldy** [comment]
I prefer a PR that would work like @atm-john suggests. It will work everywhere the same way on client with no need to update server code.
Can you suggest a PR like this by adding a 
@media print { 
   // instruction here of css you want to hide in print mode.
}

Closing and submitting a new PR may be better...

**Comment by atm-maxime** [comment]
@mapiolca any news ?

**Comment by mapiolca** [comment]
Sorry but I didn’t have the time to do that..

**Comment by atm-maxime** [comment]
No worries, I just wanted to know if this PR is still pending.

**Comment by mapiolca** [comment]
Ok, if you want, you can make the change Asked by @eldy.

**Comment by eldy** [comment]
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolete, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.

**Pull request closed without merging**
