### PR TITLE
prevent draft interventions deletion for users without delete permission

### PR DESCRIPTION
**Pull request by bafbes**
prevent draft interventions deletion for users without delete permission

### CODE REVIEW

**Comment by eldy** [comment]
By definition, in dolibarr, right to delete is right to delete an existing card, son once validated.
A draft is something that does not exists so can always be deleted by people with permission to create it. So permission to delete a draft should be test on create permission (you can create card = you can play with draft)

**Comment by bafbes** [comment]
In  cases of invoices, orders and propals, users need delete permission for deletion. So, one can consider that as just the standardization of this behaviour. Furthermore, draft elements do exist in the extent that they may contain element lines. How to prevent deletion of these elements by non authorized users otherwise ?

**Comment by bafbes** [comment]
Can't this pull request be merged ? 
What is PR not qualified ?

**Comment by eldy** [comment]
PR won't be merged like it is.
Because a draft object is an object that does not exists yet.
A draft is an object you are in a process to create it. Delete of it must be done on create permission because dratf is just a status that mean, "i start to create, but i did not finish to enter all information to create it". So permission must be on create to delete a draft.

Deletion of other status are done on a delete permission but to delete a draft, permission to use is create.
You must split the button in 2 cases of test (if draft or not)

**Comment by bafbes** [comment]
You may test and take a look into the code of invoices. When MAIN_USE_ADVANCED_PERMS is on and that a user does not have the permission to delete invoices, he cannot delete his own invoices whatever they are in draft state. I used this functionality in the past and found it very useful. Once created the employee can no longer delete the created draft invoices that are the proof of a **selling attempt**.  I need just to extend this functionality to interventions. We also can call draft interventions **intervention attempts** that should not be removed from history while they are useful.

**Pull request closed without merging**
