### PR TITLE
NEW setup automatic email

### PR DESCRIPTION
**Pull request by ptibogxiv**
This PR push settings pages for  automatic email (from template model) from proposal / order / invoice / shipment (as member module used it actually)

### CODE REVIEW

**Comment by atm-maxime** [comment]
Hi @ptibogxiv, what is it you want to achieve ? Is it something similar to the notification module ?

**Comment by ptibogxiv** [comment]
@atm-maxime not really notification module not use emails template with PDF joined and need to set notification one by one for all customer. 

When you have lot of invoices or orders, some beautiful email with PDF joined (as all ecommerce in fact) is a really needed feature (without manual send).

when an email template will be set for an action of an object, an email will be send,  if not, no changes with current behavior.

**Comment by atm-maxime** [comment]
Understood. How will be defined the recipients ? Email on thridparty ? Contacts ?

**Comment by ptibogxiv** [comment]
> Understood. How will be defined the recipients ? Email on thridparty ? Contacts ?

if no contact on object, it will be the thirdparty. i there are some default contact for object, they will be used (ie: default order contact on order...) Maybe will need on option for always mail the thirdparty

**Comment by ptibogxiv** [comment]
@atm-maxime i see the code. Actually, notification is only on demand and send email only to thirdparty (not to contact)
@eldy 
so in first time, i just replace predefined message by an templated one if set. but we need an option for notify all thirdparty and defined contact it's better (too hard to manually send for big company and business).

**Comment by eldy** [comment]
I don't understand.
There is already a page to setup email templates. What is difference with this new family of templates ? Is it just another entry on setup menus that point to same existing templates (so when you use existing template edition, it also edit into other setup tabs) ?

**Comment by ptibogxiv** [comment]
@eldy this is no template just set it to action/status for replace automatic email with notification module (manual or Api action). Actual thirdparty's notifications are very bad and need use template (just keep actual email when no template).

When you order on Amazon, Thomann, Fnac... you receive  html email with pdf on order, invoice, shipping, member... Manual is good (no change to do) but automatic good too.

We just enhance notification module with the use of email templates.

**Comment by eldy** [comment]
So if this a new setup for notification module to decide which email template to use (good), it would be easier to have the setup of which email template to use into the setup of notification module, so on page:
htdocs/admin/notification.php
(For each code event, we decide which template email to use)

**Comment by ptibogxiv** [comment]
new PR https://github.com/Dolibarr/dolibarr/pull/13597

**Pull request closed without merging**
