### PR TITLE
add trigger CREATE_BUYPRICE

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by marcosgdf** [comment]
I'm afraid that trigger name does not comply with Dolibarr naming standards. Check http://wiki.dolibarr.org/index.php/Triggers#List_of_known_triggers_actions

Also, please... Changelog!

**Comment by altairis-tof** [comment]
there was already a trigger named "UPDATE_BUYPRICE" in this script, so i have followed the same naming rule...

**Comment by marcosgdf** [comment]
Created task 1325 for renaming that trigger then :tongue:

**Comment by marcosgdf** [comment]
@eldy I don't understand this PR approval.

**Comment by rdoursenaud** [comment]
Me neither. Please try to keep the trigger naming consistent.

**Comment by rdoursenaud** [comment]
PR #1522
Wasn't that hard, was it ?

**Pull request merged**
