### PR TITLE
NEW : Added a configuration in workflows

### PR DESCRIPTION
**Pull request by samifilali**
# NEW
Added a configuration that allows an customer order to be placed in invoiced status if its total excluding tax is equal to the sum of the totals excluding tax of the linked invoices

### CODE REVIEW

**Comment by samifilali** [comment]
@eldy

**Comment by eldy** [comment]
What is difference with the existing option WORKFLOW_INVOICE_AMOUNT_CLASSIFY_BILLED_ORDER ?

**Comment by samifilali** [comment]
The difference is that this configuration takes into account orders linked to several invoices (deposit invoice for example)

**Comment by samifilali** [comment]
@eldy

**Pull request merged**
