### PR TITLE
NEW not show default message if not predefined and not apply

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
NEW not show default message if not predefined and not apply

### CODE REVIEW

**Comment by eldy** [comment]
Do you mean you start with empty message. This may be better for message/mail from public interface, but i think this is also used when using from the backoffice. In such a case, we must use the predefined first template when we do create message (like we do for other object). Did you take this into consideration ?

**Comment by lvessiller-opendsi** [comment]
@eldy 
I understand your remark and a default predefined (generic) message was introduced in the "develop" branch.

However, it remains a problem to load the default message for Dolibarr v10. If no predefined messages defined, when we want to add a new message in ticket, we have "PredefinedMailContentTicket_send" in the text of message  : 
ticket-predefined-message-default

How can I resolve it ?
Is it a FIX for v10 only ?

**Comment by eldy** [comment]
The trouble exists in v10 for any object without a hard coded message (not only ticket). So i backport a fix done into develop into v10 ffb3d810def9e2988a941f43bd58aabf9fc477a1
If no predefined template exists, we fallback on the generic message.

**Comment by lvessiller-opendsi** [comment]
Ok, thanks.

**Pull request closed without merging**
