### PR TITLE
FIXES Webservice : fk_delivery_address not saved

### PR DESCRIPTION
**Pull request by aaujon**

### CODE REVIEW

**Comment by BebZ** [comment]
are you working on a module for deliveries, or on something related to delivery ? 
If yes, i am very interested :)

**Comment by aaujon** [comment]
@BebZ Not for the moment, I'm working on a module to synchronize clients, products and orders from Prestashop to Dolibarr. Once done, I will have a look to see if it's possible to make deliveries easier in France (like connecting to the french postal services)

**Comment by BebZ** [comment]
Thanks for your answer Arnaud, are you working with ZenDSI or JeffInfo for prestashop ? 
I know he's looking for such a module, and maybe he can help with tests or develop ? @Darkjeff.

...to interconnect to postal services it wont be easy i guess (La Poste, Chronopost, Exapaq...)
But if you plan it, i'll be glad to help (i can't dev but help express needs and tests :)

**Comment by aaujon** [comment]
Well, Colissimo services looks quite easy as La Poste provide a webservice to directly print address form. For Chronopost and the others, I dont know yet.
@BebZ Thanks for the tip, once it's stable I will see if he's interesting in giving it a try.

**Pull request merged**
