### PR TITLE
 NEW possibility to force entity when module activation (used for entity template or upgrade process)

### PR DESCRIPTION
**Pull request by hregis**

### CODE REVIEW

**Comment by eldy** [comment]
What happen for external module that still has a signature for method init() in the descriptor file with php 7 ?
Don't you have warning ?

**Comment by hregis** [comment]
@eldy this PR is ready...
this addition is important because during an update we deactivate/reactivate modules in order to take into account the new rights or others and it is only done on entity 1 and suddenly it forces us to deactivate/reactivate the modules in the other entities manually. So yes it creates php warnings if the module does not have the "$force_entity" parameter in the module's "init" function, but that's the game my poor Lucette ! ;-)

`public function init($options = '', $force_entity = null)`

**Comment by hregis** [comment]
@eldy ping

**Comment by hregis** [comment]
@eldy ping again ! ;-)

**Comment by eldy** [comment]
Still don't understand why we need to force entity on such method.
The entity is a data of context and this methods alreay use the entity in context. Why not changing the context if you need to have them executed into a different context ?

**Comment by hregis** [comment]
@eldy 
When launching the update, in "upgrade2.php", the "migrate_reload_modules" and "migrate_reload_menu" functions only manage entity 1
therefore the child entities do not benefit from this update and can create side effects if the modules are not manually deactivated/reactivated.

How do you see the thing in order to solve this concern?

**Comment by eldy** [comment]
> @eldy When launching the update, in "upgrade2.php", the "migrate_reload_modules" and "migrate_reload_menu" functions only manage entity 1 therefore the child entities do not benefit from this update and can create side effects if the modules are not manually deactivated/reactivated.
> 
> How do you see the thing in order to solve this concern?

In v16, i introduced a loop into upgrade2.php for every migrate_... functions
`foreach ($listofentities as $entity) {`

Dos this fix your need ?

**Pull request closed without merging**
