### PR TITLE
FIX count elements in invoice list (Issue #21444)

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
FIX count elements in invoice list (Issue #21444)

### CODE REVIEW

**Comment by lvessiller-opendsi** [comment]
@eldy 
Why PR #21459 was revert ?
Did you see any problem ?

**Comment by eldy** [comment]
> @eldy Why PR #21459 was revert ? Did you see any problem ?

Yes I got SQL error when using a defaut Dolibarr setup. So we still have a problem when we used external module, but i prefered to revert because common use without external module was broken (SQL syntax errors with some strict mysql setup, and bad counting with others).

To help me understand the issue #21444 can you provide the full SQL request you have when using your external module. String before and after.

**Comment by lvessiller-opendsi** [comment]
@eldy 
The SQL request remains the same at final.
Could you send me your SQL request to understand where I forgot to concatenate the SQL request  ?

**Comment by lvessiller-opendsi** [comment]
@eldy 
I checked with a default Dolibar 14.0 but I did'nt get any error.
Could you send me your SQL error to understand my mistake ?

**Comment by lvessiller-opendsi** [comment]
Fixed in Devcamp

**Pull request closed without merging**
