### PR TITLE
Add JetBrains IDEs hidden directory to .gitignore

### PR DESCRIPTION
**Pull request by jyhere**

### CODE REVIEW

**Comment by eldy** [comment]
Currently we need this directory to have Qodana service working https://qodana.cloud/organizations/zqXNA

**Comment by OdyX** [comment]
These things should really reside in each user's [global .gitignore configuration](https://git-scm.com/docs/gitignore#_description), and surely not in each project.

> Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. (…)

**Comment by eldy** [comment]
> These things should really reside in each user's [global .gitignore configuration](https://git-scm.com/docs/gitignore#_description), and surely not in each project.
> 
> > Patterns which a user wants Git to ignore in all situations (e.g., backup or temporary files generated by the user’s editor of choice) generally go into a file specified by core.excludesFile in the user’s ~/.gitconfig. (…)

Sure. It should. But for the moment we can't or we loose one of our CTI tool. We are waiting a Qodana enhancement (planned by Qodana team) to allow us to remove the dir and file...

**Comment by jyhere** [comment]
Ok sorry for this PR !

**Pull request closed without merging**
