### PR TITLE
Increase length of bank code

### PR DESCRIPTION
**Pull request by openthink-laurent**
USA has a 9-digit routing transit number.

### CODE REVIEW

**Comment by rdoursenaud** [comment]
AFAIK this field is deprecated and should not be used anymore. It was used to store the now defunct french RIB (Replaced by SEPA).
The account number is stored into the `llx_bank_account.number` column which is a `VARCHAR(255)` that should give plenty of room for your use case.

**Comment by openthink-laurent** [comment]
SEPA applies only to payments in euro in SEPA zone, other countries outside the SEPA zone (or even the Eurozone when they use a local currency), like Switzerland or USA, still use bank codes. Check https://en.wikipedia.org/wiki/Single_Euro_Payments_Area and https://en.wikipedia.org/wiki/Bank_code for more details.

**Comment by rdoursenaud** [comment]
But now that you gave more informations (Thanks for that!), I better understand the issue.
I'm very well aware that SEPA is only for the euro zone, it's in the name ;)
This does not change the fact that the current `code_banque` field was not designed for that purpose, it was designed to hold the french RIB infos.
Now that we work with a larger international community, I believe it should be transitioned to a `VARCHAR(255)` to remove any arbitrary limit and renamed to a more appropriate `bank_code`.
Raising it only to 9 makes no sense in the long term.
We also need to provide the migration path in `htdocs/install/mysql/migration/3.8.0-3.9.0.sql`.

**Comment by eldy** [comment]
@open-minds Can you modify the PR to increase bank code to 255 instead of 9 and also introduce the line into file htdocs/install/mysql/migration/3.8.0-3.9.0.sql to have upgrade done ?

**Comment by eldy** [comment]
Patch was included manually.

**Pull request closed without merging**
