### PR TITLE
NEW Extend option ORDER_ADD_ORDERS_WITH_PARENT_PROD_IF_INCDEC for all virtual product stats (renamed into PRODUCT_STATS_WITH_PARENT_PROD_IF_INCDEC)

### PR DESCRIPTION
**Pull request by altairis-tof**
also replace constant ORDER_ADD_ORDERS_WITH_PARENT_PROD_IF_INCDEC by new constant PRODUCT_STATS_WITH_PARENT_PROD_IF_INCDEC

### CODE REVIEW

**Comment by altairis-tof** [comment]
@eldy @atm-maxime i did not understand why Travis build failed

**Comment by jtraulle** [comment]
```bash
There was 1 failure:

1) UserTest::testUserCreate
Failed asserting that 0 is less than -3.

/home/travis/build/Dolibarr/dolibarr/test/phpunit/UserTest.php:140
```

**Comment by jtraulle** [comment]
@altatof Can you merge current develop branch into your PR branch to see if this issue was not caused by something else that has now been fixed ?

**Comment by altairis-tof** [comment]
@jtraulle done and ready for merge ;-)

**Pull request merged**
