### PR TITLE
Adding Default version for the BOM

### PR DESCRIPTION
**Pull request by defrance**
It is necessary to have a default BOM for the automation of replenishment or the creation of a default OF

### CODE REVIEW

**Comment by eldy** [comment]
If you add a column, it means you have several default BOM ?
On which screen does this property will be used ?

**Comment by defrance** [comment]
> If you add a column, it means you have several default BOM ?
> On which screen does this property will be used ?

the goal is to have a default bom by product not sure that you can define the key like this
when we launch an OF or an replenishment to select it by default.

**Comment by eldy** [comment]
So the field should be fk_bom on the product table llx_product (and can be null), not into table llx_bom_bom.

**Comment by defrance** [comment]
> So the field should be fk_bom on the product table llx_product (and can be null), not into table llx_bom_bom. 

I ok with your point of you so close and make change in the good place

**Pull request closed without merging**
