### PR TITLE
New : replenish function adds new lines into already existing draft supplier order instead of creating a new supplier order

### PR DESCRIPTION
**Pull request by atm-maxime**

### CODE REVIEW

**Comment by eldy** [comment]
Still a strange thing into code.
'and source = 42'
may be an old pb. What is this hard coded value ?

**Comment by atm-maxime** [comment]
The 42 value into source field has been used to be able to make a difference between orders generated by the replenish function and order created manually.

I can remove the filter "and source = 42" in the SQL request if the expected behaviour is to continue to fill any draft supplier order with the replenish function. Otherwise we can keep it. I don't have any use case telling me which way is the best.

**Comment by atm-maxime** [comment]
Travis failed on sqlite3 file, which has nothing to do with this PR

**Comment by eldy** [comment]
Oops, this is a very old bug. The field "source" seems to not be used, except for setting it to 42. ?!? Why 42 and not a string 'replenishment', i don't know.
Well, let's keep it like this.

**Comment by rdoursenaud** [comment]
Well, certainly because my intern at the time loved The Hitchhiker's Guide to the Galaxy ;)
I didn't catch this ugly hack in my review. Shame's on me…

**Comment by braito4** [comment]
XD

**Pull request merged**
