### PR TITLE
fix: unconfortable use of ajax_combobox

### PR DESCRIPTION
**Pull request by bafbes**
fix: unconfortable use of ajax_combobox

### CODE REVIEW

**Comment by eldy** [comment]
Can you describe what is hurting you with the autocomplete version of combo box ?

**Comment by bafbes** [comment]
The ajax combo_box implements a select2 jquery widget. This widget is adapted to the selection of an element in a list of a minimum 10 element as we can filter this list by introducing some letters of the name. It is not adapted to the selection of a document model as this number is rarely above 3. Furthermore, the field width is reduced to less than 8 chars and the model name is continued with dots. The simple list is much more convenient in this case.

**Comment by dpriskorn** [comment]
On which url is this?

**Comment by bafbes** [comment]
Hi,
htdocs/compta/facture/card.php for example

**Comment by eldy** [comment]
Yes the autocompletion may be useless for most common installation. But it is just an option. Combo box should also works exactly like it does for a common list (one click to drop, one click to select). Truncation is more a problem. However, i do not experience this trouble. Do you have it with v12 ? Can you provide a screenshot ?

**Comment by bafbes** [comment]
In the following we see how the select2 widget is awful and unuseful :

Why not to restrict the use of the select2 widget to only the places where it is useful ?

**Pull request closed without merging**
