### PR TITLE
NEW Add trigger "SUPPLIER_PRODUCT_BUYPRICE_DELETE"

### PR DESCRIPTION
**Pull request by all3kcis**
Add trigger "SUPPLIER_PRODUCT_BUYPRICE_DELETE" for fournisseur.product remove_product_fournisseur_price()

### CODE REVIEW

**Comment by simnandez** [comment]
Travis CI failure has nothing to do with this PR

**Comment by eldy** [comment]
For a delete (and only delete), triggers must be called before the delete of record. Can you change this ?

**Comment by all3kcis** [comment]
it's done

**Comment by eldy** [comment]
The trigger must still be inside the transaction, so after the $this->db->begin();

**Comment by all3kcis** [comment]
It's ok ?
can you tell me more about this ?

**Comment by eldy** [comment]
No.
Now you have a "begin" transaction with no end (no commit nor rollback).

When a begin is done you must be sure a commit or rollback is also done later (this is not the case if there is an error in your trigger.
Code of trigger must be inside same transation than delete of object. So if one of them fails, everything is rollback and nothing is done:  EVERYTHING or NOTHING.

**Comment by all3kcis** [comment]
I'm really sorry..

```
    $this->db->begin();

    // Trigger

    if (empty($error))
    {
        // sql query
        // commit or rollback if error
    }
    else
    {
        $this->db->rollback(); // Just add rollback here ?
        return -1;
    }
```

**Comment by eldy** [comment]
yes this should work.
Another solution is to store if there is an error into a $error var for each step and do the commit/rollback completely at the end at same level than begin

**Pull request merged**
