### PR TITLE
NEW: Add php-iban lib 1.4.6 to check iban information.

### PR DESCRIPTION
**Pull request by frederic34**
Original idea of Alexandre Spangaro
www.dolibarr.fr/forum/11-suggestionsnouvelles-fonctionnalites/52518-aide-ajout-d-un-validateur-iban

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Looks really nice :+1:

**Comment by frederic34** [comment]
Perhaps it's possible (better?) to integrate in account.class.php

**Comment by rdoursenaud** [comment]
The account.class.php is the CRUD class. I don't think this kind of validation goes there.
It should go at the GUI level and that's what you've done, so I'm happy with it ;)

**Comment by aspangaro** [comment]
Hi Frederic,

Thanks for your work.

I add this PR for copyright : https://github.com/Dolibarr/dolibarr/pull/2371

**Comment by rdoursenaud** [comment]
@aspangaro It would be better if @frederic34 added the php-iban copyright info to it's PR.
Having 2 related PRs with such dependencies can be really confusing for maintainers (aka @eldy) and will make the history convoluted for no reason.

**Pull request merged**
