### PR TITLE
New project in decimal day

### PR DESCRIPTION
**Pull request by aconits**
# New 

Add new configurations to declare the number of working hours by day and the number of working days per weeks to show the planned/spent time on project tasks
Another conf (PROJECT_USE_DECIMAL_DAY) allow the user to save the planned time in decimal

### CODE REVIEW

**Comment by nicolassandy** [comment]
new_project_in_decimal_day

**Comment by aconits** [comment]
Last step I need to do, is to update behaviour of "Input per day" tab

**Comment by aconits** [comment]
@eldy is fixed

**Comment by eldy** [comment]
PR had some Continuous Integration errors not solved and making not possible to merge it.
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolete, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.

**Pull request closed without merging**
