### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by FHenry** [comment]
Sorry forget this request. I just try to understand how github work, so sometimes, I click on button.
 The dev is actually as a Module.

 I will ask to merge my dev to master when I will integrate this module as a core part of dolibarr.

**Comment by hregis** [comment]
j'ai regardé vite fait et il y a pas mal de choses qui ne sont pas conforme,
on fera le point un de ces 4

**Comment by eldy** [comment]
Can you explain goal of module.
For example, to decide if a product is visible or not into list when building invoice or proposal, there is already the status "on sell" (visible when build proposal or customer invoices) and "on purchase" (visible when building supplier invoice). 
So can you describe more precisely what this module provide more ?

**Comment by FHenry** [comment]
Pas de problème, au contraire, je suis preneur. 
Je te contacte dés que j'ai un peu de temps. 
Je suis actuellement a l'étranger mais je rentre lundi 26 Septembre, a partir de la j'aurais plus de temps a consacré. Je voulais implémenter l'eco taxe dans dolibarr (en module pour la 3.0.1 et pour la 3.1, et natif sur 3.2) mais plus largement un système de taxe ajustable : Création de nouvelle taxe, avec un code compta propre, fixe ou % du prix, possibilité de séparation sur la facture, a comptabilisé ou non en fonction du client. Bref, quelque chose de complet. Je pense dans un premier temps me consacré a l'eco taxe car tu as deja crée la table, et puis je verrais pas la suite pour élargir le modèle.

Cordialement

**Comment by FHenry** [comment]
Hello Edly. 

Of course : for exemple, you create two category of customers : Retailer(small shop) and food market industrie(big supermarket), may be you want limit the product selection to sell to one and not to the other. Or may be you will create two product (virtual, for the same real product) with different price (including different taxe according to type of compagny you sell) for both of them, and deal with assortment to limit the product or service to sell to them. 

For exemple in France we have the eco Taxe (fix rate or % of price), If you sell to final customer you have to invoice it, if you sell to retailer you have to print it on the bill but not include it in the total amount of the bill.

I work for 10 years for a big compagny and this feature was included in the ERP/CRM (Oracle Siebel), So I say that it would be usefull for Dolibarr too.
After that, we also used this feature to manage and perform the retail audit by the sales forces people (may be another feature to develop in "point of sales" module).

**Pull request closed without merging**
