### PR TITLE
[WIP][NEW]Create parcel.php page [help needed]

### PR DESCRIPTION
**Pull request by dolibarr95**
Hi all!
This is my first full page creation, please feel free comment.

Please read #11636 

- [x] Create page
- [ ] Add table html line
- [ ] Create new table in DB
- [ ] Create CRUD functions in class.php

### CODE REVIEW

**Comment by eldy** [comment]
What is the goal of this feature ?
Can you describe the database change/need ?

**Comment by dolibarr95** [comment]
Hi @eldy 

_Tks for labeling and answer._

As I try to explain here #11636 the goal is:
Manage the parcels sended via an expedition. Because an expedition can contains several parcels (actually in the expedition card the fields are only for one parcel).

If we ad a new page named "parcel" we could manage this kind of case : 

| #        | Width| Height | Depth | Weight |
| ------------- |:-------------:| -----:|-----:|-----:|
| 1      | 10 | 30 | 10 | 0.5 |
| 2      | 150 | 7 | 7 | 3 |
| 3      | 100 | 8 | 5 | 3 |

_3 parcels for an expedition_

```sql
--List of parcels details related to an expedition
create table llx_expeditionparcel
(
  rowid             integer AUTO_INCREMENT PRIMARY KEY,
  fk_expedition     integer NOT NULL,
  description       varchar(255),    --Description of goods in the parcel (required by the custom)
  value             double(24,8)     DEFAULT 0,--Value (Price of the content, for insurance & custom)
  fk_parcel_type    integer,           -- Type or parcel, linked to llx_c_shipment_parcel_type (eg: 1=enveloppe, 2=parcel, 3=palette, 4=other)
  height            float,	       -- height
  width             float,	       -- width
  size              float,	       -- depth
  size_units        integer,	       -- unit of all sizes (height, width, depth)
  weight            float,	       -- weight
  weight_units      integer,	       -- unit of weight
  dangerous_goods   smallint          DEFAULT 0, -- 0 = no dangerous goods or 1 = Explosives, 2 = Flammable Gases, 3 = Flammable Liquids, 4 = Flammable solids, 5 = Oxidizing, 6 = Toxic & Infectious, 7 = Radioactive, 8 = Corrosives, 9 = Miscellaneous (see https://en.wikipedia.org/wiki/Dangerous_goods). I'm not sure if just register 0 (no) or 1 (yes) is enough.
  tail_lift         smallint          DEFAULT 0, -- 0 = no tail lift required to load/unload parcel(s), 1 = a tail lift is required to load/unload parcel(s). Sometime tail lift load can be different than tail lift delivery so maybe adding a new table line.
  rang              integer  DEFAULT 0
)ENGINE=innodb;
```


We could also define all information mandatory or not according to the services (custom, carrier...)

1. Dangerous good
2. Tail lift required or not
3. Type of parcel
4. etc


```sql
--Dictionary of parcel type
create table llx_c_shipment_parcel_type
(
    rowid        integer  AUTO_INCREMENT PRIMARY KEY,
    label        varchar(50) NOT NULL,  -- Short name
    description	 varchar(255), -- Description
    active       integer DEFAULT 1 NOT NULL, -- Active or not	
    entity       integer DEFAULT 1 NOT NULL -- Multi company id 
)ENGINE=innodb;
```

I think we need 
1. a new table to manage the parcels of an expedition : llx_expeditionparcel
2. a new table to manage the dictionnary : llx_c_shipment_parcel_type
3. edit the actual table  llx_expedition : cut and paste datas (height width...) form llx_expedition  to llx_expeditionparcel
4. a new page parcel.php
5. edit expedition.class.php or create expeditionparcel.class.php for new manage function

Tks for reading.

**Comment by BebZ** [comment]
:) Woha, we could wok together to make a wonderful parcels module !
So you plan, after a shipment is Validated or Draft ?
to "explode" the shipment in One or More "parcels"
and these parcels would take one or more attributes
isn't it ?
(BTW : i'm the one with the question for API on the FR forum) :+1:

**Comment by dolibarr95** [comment]
Hi ! 
Yes 🙂
My plan is :

1. The purchase manager create the shipping as **DRAFT**.
2. Then he **VALID** ( everythin is ok, stock, adresses... the order as to be done)
3. The store keeper pick products, and save the parcels informations once everything is ready, he marks as **PROCESSED**
4. The purchase manager make a request to ups or else.
5. Once the carrier takes the parcel the store keeper marks the shipping as **SHIPPED**

Please read also : https://github.com/Dolibarr/dolibarr/pull/8953

**Comment by dolibarr95** [comment]
Hi!
@eldy do you please give opinions / comments ?
Tks

**Comment by fappels** [comment]
Hello @dolibarr95, thanks for the request. Some general feedback.
1) Better to use module builder.
2) Missing products and its qty in parcel (If parcel lost, which products to resend?)
3) Also virtual product child products should be in parcel, if pack too big for one parcel, should be able to split pack items into different parcels.

**Comment by dolibarr95** [comment]
Hi !
Tks @fappels 
+1 for :
> products and its qty

About :

> Better to use module builder

Do you mean I should create an external module ?

Tks for your feedback

**Comment by fappels** [comment]
Hi @dolibarr95,
Because parcel is new object, you can use modulebuilder to have your object classes and pages created with dolibarr standardized code. (make use of the commonobject crud methods).
Also other new recently added new features were made with modulebuilder compliant code (Bom,  Emailcollector, ..)

**Comment by dolibarr95** [comment]
Tks !

**Comment by saxa** [comment]
Hi, nice work, but I think this goes further than what the packing list is. 
A packing list should be created from the confirmed order or better from the invoice.
Now, it is ok if you add all that tracking stuff and possibilities, but in some way would be good to have the possibility to define in some place the exact contents of each packing made from a single order and link it to the invoice.

**Comment by dolibarr95** [comment]
;-) tks for reply

> define in some place the exact contents of each packing

I think it's a good idea. But it should be easy for this kind of case :

2 boxes contain (the same references in 2 different boxes) : 

- Box 1 : 50  unit of reference A, 20 unit of reference B 
- Box 2 : 10  unit of reference B

In my case this is the store keeper who define the packaging (when he picks the product in the warehouse he selects the best box size).

**Comment by saxa** [comment]
ok, my initial idea on the packing list was to have an separate tab in the shipping details of the order and then elaborate some kind of list with quantity on each part number so you could define in which box it is located that single item.

**Comment by BebZ** [comment]
Why do you speak of PURCHASE MANAGER ?
**To clarify :**
Do you need to track parcels coming from your SUPPLIERS to your WAREHOUSE
or from your WAREHOUSE to your CUSTOMERS ?
Because in this case the person who create the draft is (not in the puchase/buying department) 
- the person in charge of picking in the warehouse 
- and the person who VALID draft with clear infos and parcels characterisitcs (in a second screen or on a screen linked to the "customer order", doesn't matter) is in charge of "packing" and "sending". isn't it ?

I thought you wanted to track PARCELS to CUSTOMERS with characteristics, please confirm

**Comment by dolibarr95** [comment]
Hi
The tracking comes later.
**Draft** : create the shiping
**Validate** : the store keeper put the products in the boxes
_He registers the parcels (dimension, weight...) in regards of the order_
**Done** : the manager select the shipping mode and informations (dangerous goods, palette, express...) 
_so the store keeper can stick on the boxes the shipping label_
**Validated**: the shipping company take the parcels (scan...)

Then we could add tracking...

**Comment by saxa** [comment]
I think the status Validate should end up with all necessary information, packing labels, numbering of boxes, defining which items are in which box. Etc..

Also a dictionary with all kind of configurations for boxes, palets, containers, lashes, etc. should exist.

**Comment by eldy** [comment]
Let's go step by step.
First, it's ok for a new table. However, i would use the translation llx_expedition_package instead of llx_expeditionparcel
"parcel" is more british and "package" more american.
But reference language is en_US so we should set priority to american forms.
And undescore makes name more readable.

It's also ok to edit / define the shipment package on another tab of the shipment card. This tab must not be mandatory (User can fill it only if he wants / needs to)

**Comment by najot36** [comment]
Hi, from my perspective, it would be good indeed to have a field for the tracking number of each parcel.
For the rest the features look promising 
How could we help or try this feature? Is there any time frame ?
Thx
Damien

**Comment by prietojc** [comment]
Usually products come in packages (tens, dozens, etc) but card define just individual item.  

I miss a **package quantity** field in product card. It would be very usefull for this new feature, to auto-calculate the number of boxes, like is made with weight and volume. So, if customer ask for 36 items and product come in dozens,  we just send 3 packs and not need re-boxing.

I use an extrafield for that, but I think is good moment for adding in core.

**Comment by najot36** [comment]
Hi again,
Is there any demo available?
Would someone be willing to help or quote for integration of this function?
Thks!
Dj

Le lun. 21 oct. 2019 à 12:35 PM, JC Prieto <notifications@github.com> a
écrit :

**Comment by eldy** [comment]
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Comment by dolibarr95** [comment]
Hi @eldy 
I would like to contribute more.
But I have no guideline about how to create new page etc and not sure that my way to do is the right way.

**Comment by fappels** [comment]
@eldy & @dolibarr95 I have the idea to make a (maybe free) dolistore module with option 'include in core after' activated. Will put on github, contributers will be welcome.

**Comment by saxa** [comment]
I am here to help so feel free to post the source and I am ready to put my fingers on it :)

**Comment by fappels** [comment]
I started development: https://github.com/fappels/dolibarr-expedition-package
Still much to do (link to shipment, status flow, ...), but database (used and extended existing llx_expedition_package), classes and pages are made. 
Menu for package is on product left menu.
Any feedback welcome.

**Comment by dolibarr95** [comment]
Hello
@fappels thank you for this job !!!!!
@eldy what about adding this new (wonderfull) work in the core?

**Pull request closed without merging**
