### PR TITLE
common view on start instead kaban

### PR DESCRIPTION
**Pull request by defrance**
kaban view look good but is not really usefull
please made and keep dolibarr simply, not sexy

# Instructions
*This is a template to help you make good pull requests. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Fix", "Close" or "New" section*
- *follow the project [contributing guidelines](/.github/CONTRIBUTING.md)*
- *replace the bracket enclosed textswith meaningful informations*

# Fix #[*issue_number Short description*]
[*Long description*]

# Close #[*issue_number Short description*]
[*Long description*]

# New [*Short description*]
[*Long description*]

### CODE REVIEW

**Comment by eldy** [comment]
Feedbacks from other users are welcome...

**Comment by philippe-opendsi** [comment]
Hi, like @defrance I prefer the list view. I don't understand what are the advantage of the Kanban view ?

**Comment by eldy** [comment]
There is 2 reasons:

1) This page is the first one that a user see when he discovers Dolibarr. It is important to show new users something more pretty than the old style lists.

2) More important, the kanban view show more information on less space on a common desktop screen (With resolution of 1600 or more and Dolibarr v12.0.2 that fix a css bug, that is majority of screen of users testing Dolibarr today). And scrolling is a pain.

Example with Kanban:

image

Without:

image

We've got 4 more modules visible on same screen without scrolling.

**Comment by RomainDeschamps** [comment]
same as @defrance  and @philippe-opendsi

**Comment by fappels** [comment]
Upgrade gets list, new install gets Kanban ?

**Comment by defrance** [comment]
on kaban view, we don't have the version of the add-on module
Think they where more interesting to use ajax on activate/desactivates modules than the kaban view, scrolling not a pain like this 
An other way is to use checkbox and mass update on list than click one by one the module.

Kaban is like a "string" : sexy but really not comfortable and ergonomic in everyday life

**Comment by dpriskorn** [comment]
I don't have strong views on this. I think the compromise suggested by fappels is good because that keep the learning curve down for existing users.

**Comment by aspangaro** [comment]
Constant : MAIN_MODULE_SETUP_ON_LIST_BY_DEFAULT to cancel kanban view

**Pull request closed without merging**
