### PR TITLE
NEW : payment on several expense report (code integration)

### PR DESCRIPTION
**Pull request by atm-adrien**
This is the following PR on this one : https://github.com/Dolibarr/dolibarr/pull/23703

### CODE REVIEW

**Comment by atm-adrien** [comment]
@eldy

**Comment by eldy** [comment]
Depends on #24884

**Comment by atm-adrien** [comment]
@eldy

**Comment by eldy** [comment]
I merged the structure change but i made some changes to match similar naming with payment of invoices.
So i suggest to publish another PR matching the new name.

**Comment by eldy** [comment]
I merged the structure change but i made some changes to match similar naming with payment of invoices. Also a lot of changed were done in tis PR on modified pages making the re-use of this PR not possible.  So I close this one and i suggest to publish another PR matching the new table name and based on develop branch.

**Pull request closed without merging**
