### PR TITLE
Update main.lang

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by ndrosis** [comment]
Hi @frederic34 I think we have the transifex for translations.
https://www.transifex.com/projects/p/dolibarr/

**Comment by frederic34** [comment]
I just have registered in transifex but I can't help in turkish just for a '.'

**Comment by ndrosis** [comment]
:+1:

**Comment by eldy** [comment]
Any commit into language files are overwrite by transifex synchro (automatic).
So it is useless to submit PR on language files.

**Pull request closed without merging**
