### PR TITLE
Escaped product label using htmlentities() PHP function

### PR DESCRIPTION
**Pull request by aponzio**
Escaped product label (libelle) using htmlentities() PHP function (both edit and view)

### CODE REVIEW

**Comment by marcosgdf** [comment]
Have you configured Linux carriage returns? There are so much changes in that diff

**Comment by simnandez** [comment]
Files must be saved with Unix format (LF) and not Windows (CR/LF). Unix format is compatible on all OS like Unix like, Windows, Mac, but the Windows text file format is no working on some PHP under Unix.

**Comment by aponzio** [comment]
Sorry, I use the web interface at github.com and I have no control of file format (as far I know): I made changes to 3 rows adding a simple "htmlentities(...,ENT_QUOTES)". What is the better way to edit files and push changes?

**Comment by eldy** [comment]
Hum, github interface seems to suffer a serious bug that make us not possible to see what changed. 

Better method to work is defined here
http://wiki.dolibarr.org/index.php/Developer_FAQ#Submit_a_patch.2C_work_and_help_on_Dolibarr_development

We prefer method "with GIT account" but if you fails with command line or eclipse, you can use method "With no GIT account"

**Comment by rdoursenaud** [comment]
I just checked and it seems the source file already had an encoding problem. It has a lone CR.
This might be worth reading : https://help.github.com/articles/dealing-with-line-endings.

**Comment by eldy** [comment]
I close reques because it can't be used by tools due to CRLF problem

**Pull request closed without merging**
