### PR TITLE
New possibility to define batch in draft shipment

### PR DESCRIPTION
**Pull request by atm-quentin**
# New possibility to define batch in draft shipment to use it as a preparation voucher

Give possibility to define later (on draft shipment) batch in a new tab.

1st : new line "Every warehouse" when converting order to shipment to define which product will be defined later.
2nd : Validation is blocked while every batch isnt define
3rd : you can define it in the new tab

image

### CODE REVIEW

**Comment by eldy** [comment]
What is the url of the screenhsot ?

**Comment by atm-quentin** [comment]
expedition/detail_batch.php

**Comment by eldy** [comment]
Still did not found how you can reach this page. Can you point me the path to follow to reach this page ?

**Comment by atm-quentin** [comment]
yes it's a new tab on expedition card which appear if product batch is enabled. 
htdocs/expedition/detail_batch.php?id=object_id

**Comment by atm-quentin** [comment]
@eldy

**Comment by atm-quentin** [comment]
Thanks, I resolved conflicts

**Comment by atm-quentin** [comment]
Confilcts resolved

**Comment by atm-quentin** [comment]
@eldy

**Comment by BebZ** [comment]
I am trying to fin it too 
https://demo.dolibarr.org/expedition/shipment.php?id=1578
https://demo.dolibarr.org/expedition/detail_batch.php?id=1578

https://demo.dolibarr.org/expedition/card.php?id=438
https://demo.dolibarr.org/expedition/detail_batch.php?id=438

doesnt give results on a 13.0.3


hm...my bad, as a noob i did not notice it was a "new" page, so I cannot test it as long as not merged ahah

image

**Comment by atm-quentin** [comment]
@eldy

**Comment by atm-quentin** [comment]
@eldy

**Comment by atm-quentin** [comment]
@eldy

**Comment by BebZ** [comment]
I think Eldy has problems to understand how it works when you see your screenshot it looks like 2 products have already a batch defined, and 2 others have no batch defined : 
image

could you explain the steps ? 
What is underlined on the screenshot in red is 
qty 1 / qty "to define" : 4 / stock qty of batch 222222 is 9... ?
so qty to be shipped is 5 ?
So it is not possible to ship as long as all batches "to define" are not chosen ?

**Comment by atm-quentin** [comment]
- When you create a shipment from an order you have a new input for each line which is "batch to define" it means you will define it later
- You can't validate shipment until every line has batch linked (same qty)
- You have a new tab which show the detail of batch for each line (for the screenshot P1 has 10 of lot 11111 already linked to it and P2 one of 22222)
- You can link each lot/serial number to each line (if enough stock + right product)
- For P2 it means you have 4 left to define batch, there is a lot 22222 which 9 are still available, 1 in 1212 etc ... and for P1 you have 1 left to define, and 2 are available in batch 000000

Is it clearer ?

**Comment by BebZ** [comment]
Ok, 
The goal of this is to make it possible to create a DRAFT shipment WITHOUT any batches defined

You bypass this step : 
https://demo.dolibarr.org/expedition/card.php?action=create&shipping_method_id=&origin=commande&origin_id=3157&projectid=&entrepot_id=-1

and not being able to validate DRAFT before completing all available batches :)

it is like you edit the full shipment and make it possible to replace one batch with another
 https://demo.dolibarr.org/expedition/card.php?id=469&action=editline&lineid=643

It is a special use case, but CAN be useful ! 
To prepare picking lists why not
To generate 4 drafts of similar orders and prepare the orders together (picking by waves)
To control stocks of other batches when you are picking an order

It will be defined as an "option" in hidden conf ?

**Comment by altairis-tof** [comment]
> The goal of this is to make it possible to create a DRAFT shipment WITHOUT any batches defined

Hello, there is also another pending PR which allow to fully modify a draft shipment : https://github.com/Dolibarr/dolibarr/pull/17978

**Comment by atm-quentin** [comment]
Hello
> Hello, there is also another pending PR which allow to fully modify a draft shipment : #17978

This is different here you can define batch after shipment creation and you have a detailed tab view for shipment batch


> Ok,
> The goal of this is to make it possible to create a DRAFT shipment WITHOUT any batches defined
> 
> You bypass this step :
> https://demo.dolibarr.org/expedition/card.php?action=create&shipping_method_id=&origin=commande&origin_id=3157&projectid=&entrepot_id=-1
> 
> and not being able to validate DRAFT before completing all available batches :)
> 
> it is like you edit the full shipment and make it possible to replace one batch with another
> https://demo.dolibarr.org/expedition/card.php?id=469&action=editline&lineid=643
> 
> It is a special use case, but CAN be useful !
> To prepare picking lists why not
> To generate 4 drafts of similar orders and prepare the orders together (picking by waves)
> To control stocks of other batches when you are picking an order
> 
> It will be defined as an "option" in hidden conf ?

Actually i didn't manage this as an hidden conf as it doesn t change standard working

**Comment by atm-maxime** [comment]
@eldy This PR is useful because many companies are creating the shipment but don't know which lot/serial will be used at this time. Currently, Dolibarr forces to select lot/serial while creating the shipment. This PR allows to create a shipment with no lot/serial selected and to go back on the shipment later and then select the lot/serial that was really packed in the warehouse.

**Comment by BebZ** [comment]
Wow, ok, this modifies standard behaviour for users that makes the picking with batch immediately.
For example, we pick the reference in the warehouse and we control directly which batch is picked, and then it is re controlled in the packing / shipment process.

I understand the other way of working, and we could need it also to "reserve" some quantities (independently of the batch picked) before going inside the stock. 

But the 2 systems can not work one next to the other.

For exemple, with your method if you have product A qty 10 in stock with batch X =5  + batch Y = 5
I can make a pre-shipment of 8 (your method)
but another colleague making a picking with batch (our method)
 will not be able to pick batch X or Y as long as the previous shipment isn't confirmed with your method ? 

Thanks for the answers and sorry to look for crazy use cases :)

**Comment by atm-quentin** [comment]
For me, the 2 systems can work together,
If I understand  your question right :
Shipment 1 with 8 product A with 8 "to define" batch (you can  also choose 2X, 1Y, 5 to define during shipment creation)
Shipment 2 with 2 product A with Batch X or Y what you chose
Then you come back on shipment 1 and choose batch available left

It's during shipment creation that you'll choose for each line a qty "to define" or any batch available
And then if you chose "to define", you'll be able to define it when you want with batch that'll be available

Here's what you have during shipment creation and the 1st screenshot at the top of the pull request is a new tab to see the detail of the shipment and where you're able to manage it
image

Does this answer your question ?

**Comment by BebZ** [comment]
Clearly, yes !
So I can choose tu put a qty in the "to define later" input box next to the warehouse name (circled red)
image


then on your new shipment tab "batch to define" we have to input the data before being able to validate the shipment :)

Indeed, That's a way to simplify things for users defining batches after the picking ;)

Thanks a lot

image

**Comment by altairis-tof** [comment]
Hello, am i the only on to be afraid of the huge number of lines on the screen if the product is managed by serial numbers ?

**Comment by atm-quentin** [comment]
@eldy

**Comment by BebZ** [comment]
You're right Christophe :) 
I did not expect that ;) 
If you have 300 serials in stock... you will suffer to find the right ones you want to ship ! 
barcode help ? select2 search box help ?

Good luck

**Comment by atm-quentin** [comment]
which is suggested fix ?

**Comment by altairis-tof** [comment]
> which is suggested fix ?

i would suggest to show serials in multiple select list; i've done it as an equipment module improvement with sumoselect and users are happy since they can select equipments with checking cases or scanning barcodes : https://hemantnegi.github.io/jquery.sumoselect/
image

**Comment by atm-quentin** [comment]
what do you think about it @eldy ?

**Comment by eldy** [comment]
My understanding is that goal of this PR is to add another TAB. So why do you have code change on current tabs ?
To increase readability of PR and make future analysis of code change, can't you make a PR with only the new feature (the new tab + the tab array definition and trans) ?

**Comment by atm-quentin** [comment]
Hello, it's a bit more complicated because this development allow creating a shipment with product which need a batch number but will define it later, card changes are needed because it blocks validation if some batch number are missing, and it allows you to create a shipment with "batch number to define later" as you can see on screenshot there are lines with "Entrepôt / Numéro de lot à définir"(https://github.com/Dolibarr/dolibarr/pull/17265#issuecomment-910032417). Card code also change tooltip to show there's X left to define.
In detail : https://github.com/Dolibarr/dolibarr/pull/17265#issuecomment-891683232

**Comment by BebZ** [comment]
What will be future behaviour for " batch/serial number required" ?
You can skip batch/serial definition on first tab, but you can't validate shipment as long as there are not defined, true ?
Because if you can skip and validate shipment, it makes the stock movements, and it creates a big mess, isn't it ?

**Comment by atm-maxime** [comment]
@atm-quentin can you refresh your PR please ? I showed it to @eldy.
Could you show me a demo ?

**Comment by eldy** [comment]
@atm-quentin Can you solve conflict on this PR. We have several PR for shipment enhancement, not compatible each other, but if this one is ok for merging, i will merge this one.

**Comment by altairis-tof** [comment]
> 



> Hello, am i the only on to be afraid of the huge number of lines on the screen if the product is managed by serial numbers ?

(september 2021)

**Comment by eldy** [comment]
One step by step.
Currently we can't change/enter lot/serial on a draft shipment.
First step is to introduce a page to edit this. Even if page is not the best one, a good step is to add a new tab to edit lot / serial / warehouse when in draft mode.
This will allow to validate the workflow change.
In a next step, we can work on having an edit page (but at least, workflow and database is validated) and only edition interface will need enhancement.
@atm-quentin can you solve conflict on this PR ?

**Comment by atm-quentin** [comment]
i did it

**Comment by eldy** [comment]
A lot of pending PR related to shipment edition were submited with different philosophy and different feature. But all of them was doing a different implementation so were in conflict.
So a PR that try to merge all the idea of all of them was pushed to add a new tab on shipment to add the expected feature of this PR. So i close this one.

**Pull request closed without merging**
