### PR TITLE
Fix: [ bug #1765 ] Unable to create a contract

### PR DESCRIPTION
**Pull request by marcosgdf**
Fix: [ bug #1765 ] Unable to create a contract

### CODE REVIEW

**Comment by eldy** [comment]
To have a similar way of working for all objects, we should have a ref_ext field (field to store an external ref) into all business elements. 
Also into migration script you have an alter to create field.
Did this create failed for you ?

**Comment by marcosgdf** [comment]
I'm going to have a look a it.

**Comment by marcosgdf** [comment]
ref_ext got removed in cf63f1a40da02e93360913d3580aea60f1fe8e53 and renamed to ref_supplier.

**Comment by eldy** [comment]
This was an error, in fact, we should have 3 fields:
ref, ref_supplier (on supplier side) and ref_ext  (on an external tool/module side).

**Comment by marcosgdf** [comment]
Restored `ref_ext` in table definition.

**Pull request merged**
