### PR TITLE
Small improvements to facture.class.php

### PR DESCRIPTION
**Pull request by ywarnier**

### CODE REVIEW

**Comment by eldy** [comment]
Don't change space into tabs and vis versa, just keep "as it is".
Rule is, we don't mind for the moment, so keep unchanged. So we will avoid conflicts and pb when merging patch from previous branch to develop branch.

I included patch of checking files manually.

**Comment by ywarnier** [comment]
OK, thanks. I was going for the complete clean-up. Just following the conventions :-)
I'll leave it as it is (for me, it is a mess at the moment, when tabs and spaces are mixed, that's why I thought it was a _good_ thing to do)

**Comment by eldy** [comment]
I understand. However, it is also a mess when making mass change, in files to manage several version as we do. We maintain, (3.5, 3.6, 3.7, dev and soon 3.8) x 2 for backported branch, so we must have merge feature very efficient.
I did not get return of people borried by mixed style currently, wich IDE do you use, which version ?

**Comment by ywarnier** [comment]
I use a default PHPStorm IDE with PSR-2 validation configured. By default, PHPStorm displays tabs as arrows and spaces as grey dots, which kind of puts tabs in evidence like this:
dolibarr-phpstorm

However, using VIM on a server is a whole different story. By default, it shows tabs as 8 spaces, so the same file would look like this:

dolibarr-vim

So you have unequal indenting in two different editors, which makes it more complicated to read (and the whole point of coding conventions being to make it easier to read for everyone, it is a bit sad...).
I'm not interested in having you change everything now, but if you _do_ set a coding convention, it would be nice to let people slowly change these (even if you have to maintain several branches).
`git diff -w` ignores whitespaces, and I just saw that Github diffs let you ignore them with ?w=1 (here: https://github.com/blog/967-github-secrets)

**Comment by ywarnier** [comment]
After careful consideration, I wonder why the $dirsociete=... line above is not idented a little more, considering it has the same spaces and tabs as the $module=... line. A mystery to be solved!

**Comment by rdoursenaud** [comment]
Current Dolibarr coding style is a huge mess.

I don't complain anymore because I've given up convincing @eldy that we need a big-bang change.
I used to be very vocal about adopting and sticking to a standard when I joined the community. (Looks familiar?).
This is what led to the current situation of PSR-2 being the "official" standard (with the silly exception of tabs indents, but I can live with that) while most of the existing source code is not following any standard.
If I remember correctly, @marcosgdf, @jfefe and @FHenry also supported the use of a coherent coding style across the board. Maybe @atm-maxime and @simnandez too?

IMHO The only way to make it happen is to target a date and get _all_ branches coding style fixed at the same time. Then ask developers to rebase their current changes on the cleaned-up branch and absolutely refuse any PR that's not up to the standard.

This would make any operation with a merge really easier, especially rebases that I use daily to maintain my customers.

Wow, it's been a long time not ranting on the subject.  Feels good :smile:

**Comment by a-schild** [comment]
Just started writing a dolibarr module, I noticed the very same inconsistency.
Would be good to define somewhere what coding rules should be used when touching code, or creating new code.
A good place would be in the dolibarr wiki, along the "Module development" page

**Comment by marcosgdf** [comment]
@a-schild http://wiki.dolibarr.org/index.php/Language_and_development_rules :smile:

**Comment by a-schild** [comment]
Yep, just not telling us what php coding formatting should be used. (1 Tab equals XX white spaces, placement of {} in if / loops etc.)

**Comment by ywarnier** [comment]
I'm not sure I'm convinced changing tabs and spaces is an issue. What we do in Chamilo is ask all developers to _separate_ commits of code styling and commits of code logic. So even if they send one single PR, the PR is composed of several commits, and each commit affecting only style is prefixed by the simple word "Minor". See https://github.com/chamilo/chamilo-lms/commit/fbe0eb6d51cfda44977795f2c54563eea759524e for example.

This way, when doing rebases, merges and cherry-picks, the work is made easier because we know which commits to _really check_ and which are almost guaranteed not to affect the behaviour (obviously, you're bound to have some issues at the beginning while people get used to it).

You can also decide not to cherry-pick code-styling changes and _only_ leave them in HEAD/master, so that you _only_ focus on cleaning the latest release.
Finally, you can use the "?w=1" suffix in Github comparison screens to ignore whitespaces, and you can do pretty much the same in all IDEs. So in the tabs vs whitespaces, there is no real logic in preventing old code to be changed from tabs to spaces, for example, to match PSR-2.

In a sense, Chamilo is very similar to Dolibarr. It has a multi-lingual community, several branches maintained at the same time, patches cherry-picked from one branch to another, a loose/flexible organisation, etc.
Definitely, reviewing code styling adds some work. I'd like to say "for a short time at the beginning", but this has been going on for more than a year now in Chamilo. The effect, after one year of work, is that the code is _really_ much easier to read. Your eyes become used to the syntax and you can catch any flaw in the convention at a glimpse.

For all 4 regular developers involved, it means greater pleasure at contributing and less hesitation when starting to write a patch. But it does require everyone to read PSR rules _several times_ before getting clear on how to do it.

There are also things that we _added_ to PSR-2, like the fact that all variables need to be $camelCaseType to decide on something (there was a big discussion between $this_type_of_variable and $thisTypeOfVariable, but we decided for the second type because that what matched more closely the rules for classes naming).

To me, postponing the application of PSR-2 (which I was against at first) is just postponing some big work that _has_ to be done to a future date, while you _know_ you will have to do it at some point, and you also _know_ you will always have less time available (until you retire :-)). So it's not a particularly good idea. Now is the best time to start.

**Comment by ywarnier** [comment]
@a-schild I agree with you. PSR-2 clearly defines 4 spaces indenting (as a strict directive), but the development rules set this as an exception (but the code is almost 50% 4-spaces, 50% tabs). Brackets {} spacing rules are also defined strictly in PSR-2, so this is not an issue (no exception in Dolibarr rules)

**Comment by marcosgdf** [comment]
@ywarnier @a-schild I agree with both of you. But we have discussed this topic MANY, MANY times in the mailing list in the past years and I don't feel like it is going to happen anytime soon...

Even if Dolibarr is meant to follow PSR-2, rules are not enforced for Pull Requests, so even new code does not follow PSR-2... I even asked people to change things in their Pull requests and the PR got merged after all :disappointed:

**Comment by ywarnier** [comment]
For PRs merged without enforcing, sometimes it may happen. What we do at Chamilo is review them afterwards (or merge manually applying the changes). Of course, it would be better to just refuse the PR, but that doesn't have to be limiting.

The first thing to do now is to finish defining the rules (what remains to be defined) and agree on these. Then we talk about how to apply them. Many times, people sending PRs will not have time to learn PSR-2 if they don't know it in the first place, so more seasoned developers (not necessarily Dolibarr developer, but developers who know PSR-2) should help them understand the rules.

Usually, if one developer comments on the code of someone new, the comment might not be considered with the right level of importance, but summing one or two other people with short comments might help.

My issue at the moment is I'm confused. I want to contribute but the confusion is slowing me down. I want clear directions. If PSR-2 is fully adopted, that gives me clear indications. I can contribute to Symfony, Chamilo and Dolibarr using the same rules and this is great.

If I have to apply exceptions, then I have to reconfigure my IDE. This is slowing me down and is putting in question my contribution (why not making a local branch and maintaining my changes locally instead of contributing?).

The naming of functions and files is in French for many things, but that doesn't really matter for now.

I've also analysed your PR queue, and it is _huge_. This is great because it means you have a lot of contributors, but it shows that you are not spending enough time to talk to the contributors (not pointing fingers, it's not anyone's responsibility).

Priority _now_ is:
- finetuning coding conventions (adopting PSR-2 fully makes it simple)
- agreeing to change the code progressively (my suggestions of splitting code conventions commits from code logic commits above might be useful)

If we can just agree on that, as I understand, this would be a major milestone for the visual attractiveness and general organization of Dolibarr code.

And as far as I understand, @eldy is not even really oposed to it, he just wants to avoid additional headaches.

**Pull request closed without merging**
