### PR TITLE
NEW : modify a shipping draft

### PR DESCRIPTION
**Pull request by altairis-tof**
Add a button "Modify" on shipping draft and manage it.

### CODE REVIEW

**Review by daraelmin — COMMENTED** [review]
Isn't $db->begin() needed to create the $objectsrc object on line 228?

**Comment by altairis-tof** [comment]
@eldy did you view this PR ?

**Comment by altairis-tof** [comment]
some sreen samples : 
- add an Update button on draft shipment : 
Expédition_-_2021-08-03_13 50 06
- then the draft editable shipment : 
Expédition_-_2021-08-03_13 49 35

**Comment by BebZ** [comment]
Wow, so there are 2 PR in "conflict", maybe that's why Eldy did not merge both of them yet ? 
PR of Quentin is making a **draft** shipment possible without batch +1
and PR of Tof is to be "fully" edit-able (but the PR of Quentin makes it also possible) +0 +0
PR of Tof is not a new "tab" it seems completely integrated in the existing screens +1

... I did not try/test both PRs...

**Comment by altairis-tof** [comment]
hello @eldy it would be nice to make a decision about this PR with the label "pending analysis" since september 2021 ;-)
i think it is useful to allow to edit a shipping.

**Comment by eldy** [comment]
I did not received a lot of feedback, except @Bebz with point of views about the different PRs for draft shipment edition.
PR of Quentin #17265 will probably be merged before because having another tab will open the road to other feature, like allowing edition of barcode at any step.

**Comment by altairis-tof** [comment]
i have made lot of improvements that are not yet included in this PR... i still do not understand why you dont agree with an edit form for shipments...

**Comment by eldy** [comment]
> i have made lot of improvements that are not yet included in this PR... i still do not understand why you dont agree with an edit form for shipments...

Never say i disagree. The point is how, using which solution of which PR. It appears that for future we need a dedicated page to edit draft shipment lot/serial/warehouses. Must be a dedicated new TAB on the shipment. Main tab will remain the summary of the shipment (current view). The new Tab is the editor of shipments lot/ serial /warehouse.
This is what is suggested by https://github.com/Dolibarr/dolibarr/pull/17265 but PR is nor mergeable for the moment.
If you have another PR that add such a tab to edit lot/serial/warehouse of a draft shipment, can you paste the number here as a comment ?
Note: A good page to make such a tab we can use as example is the page /fourn/commande/dispatch.php?id=xxx

**Comment by eldy** [comment]
The feature to allow edit of shipment is available in v18, so i close this PR.

**Pull request closed without merging**
