### PR TITLE
Simplify the accounting management.

### PR DESCRIPTION
**Pull request by aspangaro**
I began to delete columns (type, subtype and account_parent) in the table accountingaccount because they are not use and will never be of use to anything. May I continue or I waste my time?

If ok, I publish the three step.

Thanks

### CODE REVIEW

**Comment by BebZ** [comment]
I don't really know if it will be accepted maybe @eldy will understand, or maybe explain the purpose of these 3 columns, or show us future relations.
From my point of view those types of columns and level of details should be reserved to a real accounting software.
But anyway when numbering accounts numbers we should keep in mind (or maybe put a kind of reminder as a popup or smthg... to remember the "normal structure").

**Comment by aspangaro** [comment]
As accountant, I can assure that it's useless. Exemple : EBP uses the principle of the accounts root ( parent Account) and to part to block some account, I do not see the interest. Furthermore, it is not ID of the similar account which is defined but the account directly, what raises problems if several charts of accounts are managed (-> Module Accounting Expert) 

The same goes for the types / sub type, we can possibly leave one, not two and one can identify a type of account with the first number of the account, at least in France. Exemple : Class 7 produces, 1 capital, etc....

I shall want to simplify things rather than to complicate it the life.

**Comment by eldy** [comment]
The goal of the "type" is to store the class. In some countries the class (accoun number for product) is not necessarly defined by the fact it start with 7 or 1. So we need information for them.

The goal of the "subtype" column was to have a predefined link of account number to some triggered action.
For example, if account number has type "xxx" this means, into the trigger that validate an invoice, by default, dispatching will be done on this account number.
Now we have the link stored at different place (on customer, on product, on vat table)

So event, if they are not used yet, i prefer to keep them as it bring developer that is not an book keeper some interesting "information".

**Comment by aspangaro** [comment]
Thanks for the answer.

No problem for type and subtype but we have a problem (not really a problem in fact) for account_parent because it contains account_number and not the id of the account number. How let us can cure this to present a hierarchical view of chart of accounts ?

**Comment by eldy** [comment]
You are right.
The field account_parent should be an int to the primary key, this will
allow to have a database foreign key. Not possible currently.
Can you fix this and the data file   llx_accounting.sql ?

2014-05-14 11:23 GMT+02:00 aspangaro notifications@github.com:

> Thanks for the answer.
> 
> No problem for type and subtype but we have a problem (not really a
> problem in fact) for account_parent because it contains account_number and
> not the id of the account number. How let us can cure this to present a
> hierarchical view of chart of accounts ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Dolibarr/dolibarr/pull/1593#issuecomment-43059466
> .

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/awstats_project

**Comment by aspangaro** [comment]
Yes, I can fix this and the data file llx_accounting.sql but it takes a few hours, the time to make the correction I would say next Monday.

The version 3.6 coming to be frozen since one hour, this correction can nevertheless it be taken? In fact, it will serve us for the module Accounting Expert in branch 3.6.

Thank you for return,

**Comment by eldy** [comment]
This is relevant to bug, so yes i can include it into 3.6

2014-05-14 13:22 GMT+02:00 aspangaro notifications@github.com:

> Yes, I can fix this and the data file llx_accounting.sql but it takes a
> few hours, the time to make the correction I would say next Monday.
> 
> The version 3.6 coming to be frozen since one hour, this correction can
> nevertheless it be taken? In fact, it will serve us for the module
> Accounting Expert in branch 3.6.
> 
> Thank you for return,
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Dolibarr/dolibarr/pull/1593#issuecomment-43068831
> .

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/awstats_project

**Comment by aspangaro** [comment]
ok let's go ! I close this PR

**Pull request closed without merging**
