### PR TITLE
NEW Allow to change the ref of a task

### PR DESCRIPTION
**Pull request by defrance**
Allow to change the ref of a task (like the ref of project)

### CODE REVIEW

**Comment by eldy** [comment]
Can you replace the
$ref=$_GET["ref"];
by
$ref=GETPOST("ref");

**Comment by defrance** [comment]
No
The $_get is for the native url access of the page
The $_post is for the change value
With getpost the function goes wrong

**Comment by eldy** [comment]
Do you mean that into $_get in store a value x and into $_post you store a value y that differs from x ?
If this is the case, you must use 2 different parameter names.
If this is not, you can replace $_get with GETPOST.
We started to remove completely all $_get and all $_post into dolibarr code replaced by getpost.

**Comment by defrance** [comment]
it's generaly the same value stored but if we change the value may be differ but we speak of the same thing...
if the goal is to replace $_get and $_post by getpost, i will use it with  with 3e parameter to specify it

**Pull request merged**
