### PR TITLE
NEW: Add prospect status managment for the contact with managment of custom icon

### PR DESCRIPTION
**Pull request by kkhelifa-opendsi**
# New [*Short description*]
Add prospect status managment for the contact with the managment of custom icons

### CODE REVIEW

**Comment by eldy** [comment]
@kkhelifa-opendsi Can you help me to solv conflict on this PR ?

**Comment by philippe-opendsi** [comment]
ping @eldy conflict solved

**Comment by eldy** [comment]
What is goal of this ?
Because a contact/adress in Dolibarr is just an "alternative address" (when a thirdparty can have several address), a prospect should be a thirdparty.
What is use case to make "prospection" on just alternative addresses ?

**Comment by philippe-opendsi** [comment]
Hi

> a contact/adress in Dolibarr is just an "alternative address"

When you are working in B2C with Dolibarr, I ever found very confusing to have two "entities" for only one physical person. It would be better to have a "customisable" Thirdparty depending of the nature (people or legal entitie).
When you are working in B2B, mostly commercial are working on list of contact to reach in a company. So the need to have prospect status on contact has been mainly ask by our customer.

**Pull request merged**
