### PR TITLE
Fix: Product Thumbnail Popup

### PR DESCRIPTION
**Pull request by aljawaid**
Product did not scale to popup when clicked on through product card

### CODE REVIEW

**Comment by eldy** [comment]
@aljawaid What do you mean with not scale.
Can you provide a screenshot of your screen with popup open and "not scaled" and then "scaled" ?

**Comment by aljawaid** [comment]
#6918 

Not scaled

**Comment by aljawaid** [comment]
image

@eldy scaled (no scroll bars, picture fits into popup fully), see #6918 for not-scaled

**Comment by eldy** [comment]
Hum. I see. This may be a fix but may not. It depends on what we expect to the popup.
1) Do we want to show the image with maximum resolution (for exemple to be able to read a small text in image), in such a case, we must keep code like it is
2) Or do we want to see image in maximum size of our browser with no trunc. In such case, your patch looks good, but on small screen like smartphone it does not provide any interesting feature.

In my opinion, i think goal 1 is more usefull. It provide a interesting feature. 2 is more natural.
I search if can mix both mode...

**Comment by eldy** [comment]
Fixed by 5cf684f5a23f5c02bb791c56e4626073e88a567c

**Comment by aljawaid** [comment]
Thank you for allowing both options.  For me, I show the popup image to my customers onscreen (laptop) so I need it to fit browser. Allowing both options will be welcomed.

**Comment by aljawaid** [comment]
@eldy Your fix was perfect but I have one request:

When we click on the 'show original image' can the button change so we can show it scaled again?  At the moment it scales to the box and then when we click on 'original image' it zooms the image.  There is no way to go back to the scaled image unless we close the box and reopen the image.

**Pull request closed without merging**
