### PR TITLE
Sqlite3 dev

### PR DESCRIPTION
**Pull request by guedel**
Adding functions for sqlite3 databases
- installation with foreign keys creation
- database informations (variables and table).
- add date functions for mysql compatibility: FORMAT_DATE, WEEK, CURRENT_DATE, CURRENT_TIME, MONTH. It use the method SQLite3::createFunction().

FR:
Ajout de fonctionnalités pour la prise en compte de base de données SQLITE 3.
- installation avec création de clefs étrangères
- informations sur la base de données (variables + tables)
- fonctions de date pour la compatibilité avec mysql: FORMAT_DATE, WEEK, CURRENT_DATE, CURRENT_TIME, MONTH. Utilise la méthode SQLite3::createFunction().

### CODE REVIEW

**Comment by marcosgdf** [comment]
Why are you dropping PDO? Also, can you translate it to english?

**Comment by eldy** [comment]
Instead of changing the current "sqlite" that was nerally completed, can you submit a PR that use sqlite3 as another new driver, for example by naming it sqlite3 ?

**Comment by guedel** [comment]
I've changed from PDO to Sqlite3 because some functions doesn't work fine.
I'll prepare a revert and I'll add a new class with 'sqlite3' type.

Sorry, but I don't know how to edit the message of older commits.

**Comment by marcosgdf** [comment]
But if PDO doesn't work fine, why not removing it and implementing a better driver @eldy ?

Please move SQlite3 to the includes path and make a new DoliDB class that extends from it implementing the required methods for Dolibarr to work properly

**Comment by guedel** [comment]
I 've pushed my last modifications. I should test again the installation step.

**Comment by rdoursenaud** [comment]
@guedel Editing previous commits is called rebasing in git. It's a very usefull and powerful feature that can save your ass a lot of times if used properly. It also helps keeping your history clean ;)
See http://git-scm.com/book/fr/v1/Les-branches-avec-Git-Rebaser

**Pull request merged**
