### PR TITLE
 fix 600 first lines of arabic language admin file

### PR DESCRIPTION
**Pull request by bafbes**
fix 600 first lines of arabic language admin file

### CODE REVIEW

**Comment by eldy** [comment]
All files into directory htdocs/langs/ar_SA are generated files. So I validated PR but it is a wase of time because change will be overwritten by the automatic generation. To fix languages files that are not en_US, you must use the transifex interface:
https://www.transifex.com/projects/p/dolibarr/language/ar_SA/

**Comment by bafbes** [comment]
I looked in transifex by the link provided. It seems that transifex is not suitable to Dolibarr language management. While Dolibarr relies on keys to produce translations for all languages (English included), Transifex relies on Gettext and po files, where english expressions are used as keys for translation. Two Dolibarr language keys may lead to one single English expression depending on the context of use. In this aspect the Dolibarr translation system is superior to Gettext as it relies on context. So, I do not see how to use the Transifex translation system more than once, as regeneration of translation files will break all improvements made to correct the correspondance to keys. Transifex do not provide an interface to translate the language keys of Dolibarr.

I also referred before this work to an antecedent commit that concerns only language Portuguese files : https://github.com/ricardosequeira/dolibarr/commit/ec8f664085862c4af02333d67f255d93e04fc609

**Comment by bafbes** [comment]
I completed my knowledge concerning context in gettext translation (see this article) : https://www.gnu.org/software/gettext/manual/html_node/Contexts.html. So, it seems that the keys in dolibarr lang files provide the context information in transifex. I will complete soon the translated phrases in transifex.

**Comment by rdoursenaud** [comment]
@eldy You can push translated files to transifex!
Just use the CLI: `tx push -l ar_SA -t`

@bafbes We use transifex in "Mozilla properties" mode, _not_ gettext.
Please have a look at (and improve, if you feel so) our [translators documentation](http://wiki.dolibarr.org/index.php/Translator_documentation).

**Comment by bafbes** [comment]
I used : tx push -l ar_SA -t, then : tx status. That gives no output. The file admin.lang changed in my repository is not changed on transifex. 

What this means ???

**Pull request merged**
