### PR TITLE
New egg to integrate PM

### PR DESCRIPTION
**Pull request by aconits**

### CODE REVIEW

**Comment by eldy** [comment]
What is PM ?

**Comment by atm-maxime** [comment]
PacMan I guess ☺️☺️

**Comment by aconits** [comment]
@atm-maxime maybe...maybe :smile:

**Comment by eldy** [comment]
Sorry, but i prefer not accepting easter egg when this need to introduce dependencies on and embedding of new external libraries. The less we have external libraries, the less we have dependencies on project external libraries, better we are ready for futures and the less we have security holes.

**Pull request closed without merging**
