### PR TITLE
[Admin] Enhanced module setup ergonomy

### PR DESCRIPTION
**Pull request by rdoursenaud**
I replaced the hard to use setup icon by a nice link on the module name.
This is far easier to use and fits better in the overall look and feel
while cluttering the interface less.

Before:
before

After:
after

### CODE REVIEW

**Comment by eldy** [comment]
Not sure this is more easier. Looks to me more difficult to find where is link for setup page.
Also I planned a complete rewrite of this by removing tabs. I may show you during devcamp. I added the feature request for this.

**Comment by rdoursenaud** [comment]
I agree this can make discoverability a little bit harder but when you spend a lot of time into module's setup pages usability is undeniably better. Not to mention the accessibility benefits (link is right where the name is, no need to fiddle through the columns to get to the button).

Rewriting may be a good idea but this is available now ;)

**Comment by rdoursenaud** [comment]
@eldy
Icon added as requested…

**Comment by rdoursenaud** [comment]
@eldy I think this is in a mergeable state now that the icon has been added. Don't you?

**Pull request closed without merging**
