### PR TITLE
NEW A link to the bugtracker can be enabled in the GUI

### PR DESCRIPTION
**Pull request by rdoursenaud**

### CODE REVIEW

**Comment by eldy** [comment]
We experienced very bad result when having this feature enabled by default. It was available 8 years ago
We received tons of feedbacks and post by end users to ask question and 95% of reported bugs were not (i should say 99%). It was 8 years ago, but cause was just because we provide a link to all end users, so I think we should have. I prefer to have this feature reserved to dev people for the moment and wait to find a solution (we must discuss this in foundation board team) to have more dolibarr bug fixer before having this to end users.

**Comment by jfefe** [comment]
This explain #2821 :)

But there is a bug because constant must be set otherwise we don't see "on" button into setup, even if MAIN_FEATURES_LEVEL > 0 
We could keep test of MAIN_FEATURE_LEVEL but always show the line, to activate option without searching its name into the wiki ;)

**Comment by simnandez** [comment]
Idea: Instead of having a permanent link, we can add a button "send to dolibarr team" (or similar) into dol_print_error (when the error occurs): we can send error with better error info provided (code error, sql query, callstack....) only if dolibarr_main_prod is disabled....

**Comment by rdoursenaud** [comment]
@eldy I understand and share your concerns about the quality of the reports we could get if we enable the feature by default.
However, that's **not what this pull request is about**. This pull request just allows the option to _be visible in the GUI_ and thus _discoverable_ by those interested. I believe this is a good middle ground that allows people to discover and use the feature if they're interested while still leaving it disabled by default so we don't get overwhelmed by crappy reports.
Therefore I'd like to see it merged.
We'll still be able to tweak it if we're not satisfied by the results.

**Comment by BebZ** [comment]
I like the discussion, so I add my 2cents : 
Beeter if it is discoverable in Dolibarr's GUI , because some users would like to provide more details on the error, but don't have the possibility/time to reproduce it (happened once) and/or don't know how to give detailled "details". 
Many of the people that don't know what is a bug, don't search in GUI to activate the reports, and are mainly "testers" that forget to read wiki, or just need a 
http://lmgtfy.com/?q=i+am+a+real+noob+and+i+use+bing

I think it's right to activate it, and if it's not qualified bugs, we can ask to the reporter to desactivate the option, or simply mark as spam his reports.

**Comment by eldy** [comment]
So, if default value for setup is off, it's ok to merge. Can you solve conflict ?

**Comment by rdoursenaud** [comment]
@eldy Done, no more conflicts!
Thanks.

**Pull request merged**
