### PR TITLE
Fix SQL join on select_company

### PR DESCRIPTION
**Pull request by atm-maxime**
SQL error was present when user can't see all thirdparties and address are displayed in the list. There was a LEFT JOIN after a coma join. Following https://mariadb.com/kb/en/comma-vs-join/ information, I transformed the coma join to a LEFT JOIN. Is that the good way to do it ?

### CODE REVIEW

**Comment by eldy** [comment]
When if (!$user->rights->societe->client->voir && !$user->socid)  is true, we want to exclude completely the result from societe, so we should use an exact link and not a left join that will return the record if no link is found. Changing a coma into a left join has not the same effect.
Can you paste the full sql request you have so i can diagnose what's wrong.

**Comment by atm-maxime** [comment]
SELECT s.rowid, s.nom as name, s.name_alias, s.client, s.fournisseur, s.code_client, s.code_fournisseur, s.address, s.zip, s.town, dictp.code as country_code FROM llx_societe as s, llx_societe_commerciaux as sc LEFT OUTER JOIN llx_c_country as dictp ON dictp.rowid=s.fk_pays WHERE s.entity IN (1) AND s.rowid = sc.fk_soc AND sc.fk_user = 1 ORDER BY nom ASC

Unknown column 's.fk_pays' in 'on clause'

**Comment by eldy** [comment]
The left join was at the wrong place.
A left join must always be JUST after the table that it links to. Please validate the fix I pushed.

**Comment by eldy** [comment]
Already fixed with 84105e9

**Pull request closed without merging**
