### PR TITLE
NEW multicurrency total in takepos

### PR DESCRIPTION
**Pull request by ptibogxiv**
@andreubisquerra 
this fix and add can prepare to do an external customer display from takepos/invoice.php

### CODE REVIEW

**Comment by andreubisquerra** [comment]
Thank you @ptibogxiv for your work!
I am working on a new connector concept developed in php and java. This connector is compatible with a **customer display**, scales, printers and other hardware. I will have an early version at the next Devcamp in Valence. Will you be there?

**Comment by ptibogxiv** [comment]
> Thank you @ptibogxiv for your work!
> I am working on a new connector concept developed in php and java. This connector is compatible with a **customer display**, scales, printers and other hardware. I will have an early version at the next Devcamp in Valence. Will you be there?

So cool, i have lot of ask about it (shops, foundations)

What king of customer display ? basic with 2 lines or a second small full screen ? 

I live in north of France, so with covid-19 restrictions, i maybe can't go; but i can test if you need ;) (some friends of my mine opens shops soon)

**Comment by andreubisquerra** [comment]
> What king of customer display ? basic with 2 lines or a second small full screen ?

Compatible with all. The new connector is developed with PHP and Java, so the compatibility is full with any hardware. It is a new concept of connector that is already used by other erps such as Odoo (posboxless idea).

**Comment by ptibogxiv** [comment]
> > What king of customer display ? basic with 2 lines or a second small full screen ?
> 
> Compatible with all. The new connector is developed with PHP and Java, so the compatibility is full with any hardware. It is a new concept of connector that is already used by other erps such as Odoo (posboxless idea).

less expensive that odoo i hope... very expensive for a revamp raspberry but it's great ;)

**Comment by andreubisquerra** [comment]
Posboxless can also be installed without raspberry, but its configuration is very difficult. The new TakePOS connector idea does not use raspberry, it only installs on a webserver (eg xampp) without even a database. Much much easier than in Odoo and of course completely opensource and free

**Comment by ptibogxiv** [comment]
> Posboxless can also be installed without raspberry, but its configuration is very difficult. The new TakePOS connector idea does not use raspberry, it only installs on a webserver (eg xampp) without even a database. Much much easier than in Odoo and of course completely opensource and free

so i can continue my work foundation button with my adherentsplus plugin  (subscription and consumptions (time, machine or more) and a switch entity for invoice in takepos (in marketplace or coworking and invoicing in name of coworker at desk reception)

**Pull request merged**
