### PR TITLE
Fix Cron module date et [ task #710 ] Envoi de mail 

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by eldy** [comment]
Oops, i made some fixes into module before seeing there was a pending push about same topic. Sorry. Can you try to merge ?

**Comment by FHenry** [comment]
Ok, I'll do that.
What do you think about it ?

**Comment by FHenry** [comment]
We will discuss in devcamp, but I think we just have to add Dolibarr task type, this task type were automaticly added regarding modCRONXXX.php file.

**Comment by FHenry** [comment]
I pushed the merge version.

**Pull request merged**
