### PR TITLE
NEW add hidden config 'ORDER_ENABLE_NEGATIVE_QUANTITY' to allow negative quantities to be added to orders

### PR DESCRIPTION
**Pull request by flwe**

### CODE REVIEW

**Comment by eldy** [comment]
What is the need for a negative quantity on an order ? Can't you use a negative amount if this is a discount ?

**Comment by flwe** [comment]
At the moment, you can only enter negative amounts in combination with positive quantities in an order. If you convert this order into an invoice, these items will be converted into a discount. (If the amount is positive and the quantity is negative the position will not be converted to a discount.)
But I need the negative positions to stay as a product on the order/invoice to work with the German bottle deposit system (Pfand). This way, the deposits would keep their position and I could create stats for the whole “deposit” product. Bottle deposit is not a discount. It is a product, that a shop must take back.

**Comment by eldy** [comment]
> At the moment, you can only enter negative amounts in combination with positive quantities in an order
Yes, this is what we want. When we give a discount, it is 1 discount, not -1 discount

> But I need the negative positions to stay as a product on the order/invoice to work with the German bottle deposit system (Pfand).

So your need is a solution to manage the pfand system: https://allaboutberlin.com/guides/pfand-bottles
My understanding here is that you need to create a second invoice with bottle, qty -1, so number of qty when making a total will give the real number of quantities. My question is on the first invoice, you have the bottle with a qty 1 and a price 100 ? Right.
Invoice A:
Product A             Qty 1       Price 100 euros
Product Bottle      Qty 1       Price 1 euros

And you need to enter this
Invoice B (return of bottle):
Product Bottle      Qty -1      Price 1 euros

So total of qty of product bottle is 0.
Am i right or my example is wrong ?

**Comment by Tim-Otte** [comment]
The example is almost correct. Normally, _pfand_ for returnable bottles settled as follows:

```
Bill A:
Random article, 1 piece, price: 5 €
Sixpack of mineral water, 1x 6 bottles, total: 3 €
pfand for six-pack, 6x 0,25€, total: 1,50 €.

total: 9,50 €
```

```
Bill B:
Another random article, 2 pieces, total: 2 €
pfand for 20 returnable bottles, -20x 0,25€, total: -5€
pfand for 10 returnable glass bottles, -10x 0,08€, total: -0,80€

total: -3,80 €
```

The pfand is a separate item that is calculated independently of the product. It is also possible to return returnable bottles that were not purchased in this shop. For example, a customer can return 20 returnable bottles, even if they have only ever bought 6 returnable bottles in this shop.

**Comment by eldy** [comment]
Thanks for example. It's clear

The idea to allow negative number is to put a unit price for returnable bottle that will positive too so you will be able to use the same product for both the sell and the return. Why not. This will make the total good when you will make a total on the product but will make a wrong value for total on amount. It will also generates a lot of trouble with a lot of existing features. for example, it will break validity of a lot of accounting features. For example, the accounting code for selling a pfand may not be the same than when you retrieve the pfand. A lot of controls of sign to avoid errors when making credit notes may also be broken.

It appears that a "returnable bottle" is a product that is different than a product "bottle". The price of a returnable bottle will be -0.25 and quantity will be 20. This works already correctly. So another solution for such need to avoid your PR, is to create a product for pfand sales and another product for pfand returnable. With a price of 0.25 for the pfand sell and a price of -0.25 for pfand returnable. The cons is that you won't be able to get the balance by making a total of 1 product, but you will have to do it by making a diff between 1 product and another one.

Did you make some test with the module stock enabled ? After your PR, if option to decrease stock automatically has been set on "Invoice validation", what happen if you validate the invoice with a pfand and a negative quantity ?

**Pull request closed without merging**
