### PR TITLE
Created foreign key relations for llx_product and llx_product_price table

### PR DESCRIPTION
**Pull request by marcosgdf**

### CODE REVIEW

**Comment by marcosgdf** [comment]
Done!

**Comment by eldy** [comment]
PR included. Note I had to change syntax of request because all index and foreign key must have a "name" so we can delete/change/manipulate in future migration script.

**Comment by BebZ** [comment]
Error on upgrade from 3.6 to 3.7...

Request 46 sql='ALTER TABLE llx_product_price ADD CONSTRAINT fk_product_price_product FOREIGN KEY (fk_product) REFERENCES llx_product (rowid);'

Erreur DB_ERROR_1452: ALTER TABLE llx_product_price ADD CONSTRAINT fk_product_price_product FOREIGN KEY (fk_product) REFERENCES llx_product (rowid);
Cannot add or update a child row: a foreign key constraint fails (`dolibarr/#sql-468_1a`, CONSTRAINT `fk_product_price_product` FOREIGN KEY (`fk_product`) REFERENCES `llx_product` (`rowid`))

Request 47 sql='ALTER TABLE llx_commande_fournisseur ADD COLUMN fk_account integer AFTER date_livraison;'
Request 48 sql='ALTER TABLE llx_facture_fourn ADD COLUMN fk_account integer AFTER fk_projet;'
Request 49 sql='create table llx_accounting_fiscalyear(rowid     integer AUTO_INCREMENT PRIMARY KEY,label    varchar(128) NOT NULL,date_start    date,date_end   date,statut     tinyint DEFAULT 0 NOT NULL,entity   integer DEFAULT 1 NOT NULL,datec    datetime NOT NULL,tms   timestamp,fk_user_author   integer NULL,fk_user_modif  integer NULL)ENGINE=innodb;'
Request 50 sql='ALTER TABLE llx_contrat ADD COLUMN ref_ext varchar(30) after ref;'
Exécution du script    KO

**Comment by marcosgdf** [comment]
It works OK for me.

**Comment by eldy** [comment]
Can you try to run this before the upgrade:

DELETE from llx_product_price where fk_product NOT IN (SELECT rowid from
llx_product);

2014-07-17 21:57 GMT+02:00 Marcos García notifications@github.com:

> It works OK for me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/1700#issuecomment-49356482.

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/awstats_project

**Pull request merged**
