### PR TITLE
patch on the dictionnary setup of local taxes table to be able to set localtax type

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by eldy** [comment]
I made some enhancements. It should look better now. Tell me if something is wrong with my changes.

**Comment by altairis-tof** [comment]
i have tested this morning; it seems good but i realize i didnt push lang file yet. should i push it now ?

**Comment by eldy** [comment]
Le 17/09/2012 19:54, Christophe Battarel a écrit :

> i have tested this morning; it seems good but i realize i didnt push 
> lang file yet. should i push it now ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Dolibarr/dolibarr/pull/399#issuecomment-8624378.

Go.
Note i also added some entries to works with my changes.

## 

Eldy (Laurent Destailleur).

EMail: eldy@destailleur.fr
Web: http://www.destailleur.fr

Dolibarr (Project leader): http://www.dolibarr.org
To make a donation for Dolibarr project via Paypal: contact@destailleur.fr
AWStats (Author) : http://awstats.sourceforge.net
To make a donation for AWStats project via Paypal: contact@destailleur.fr
AWBot (Author) : http://awbot.sourceforge.net
CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by altairis-tof** [comment]
i see you put generic "Type 1".."Type 7" string constants instead of "%ageOnAllWithoutVAT".."AmountOnOrder".
the only reason i see is to be able to have different type lists by country (not yet implemented in my code).

Anyway, if i follow your point, i should put "Type 1=My translation" in the admin or main lang file; wouldnt it be better to have generic string constants a little more significant like "LocalTaxType 1" ?

**Comment by altairis-tof** [comment]
i dont edit the previous despite my mistake. in fact you just put a "Type" string constant followed by a number, so it it's impossible to have specific translations now... not sure it will be user-friendly to have Type 1.. Type 7

**Comment by eldy** [comment]
Yes, i did.
The reason is that it is not possible to understand the meaning of each
type with just a small text in a combo box. And this makes combo box very
large and not usefull because even with a long text, this can't be
understood.
So i choosed to use a numeric value and I added a help tooltip to explain
meaning of each value. Like that we will be able to add a more longer
description, and to add examples for each type.

So we don't need translation into the combo box but only into the tooltip
(however we can replace
"Type 1" by "Type 1 -(see tooltip for definition)" into combo box but i
think the tooltip is enough visible like that.

2012/9/18 Christophe Battarel notifications@github.com

**Pull request merged**
