### PR TITLE
Fix: avoid a non numeric value !!

### PR DESCRIPTION
**Pull request by hregis**
@eldy 
this bug is very blocking in php 7.x

### CODE REVIEW

**Comment by eldy** [comment]
This may hide a more serious bug. If you need this, it means, the caller does not call the function correctly and it is better to have error to show the bug and fix the bad call.
When do you have this needed ?
Do you have error with 8.0 (some test were added to validate and refuse bad input parameters)

**Comment by hregis** [comment]
@eldy 
en fait le problème vient des fonctions "insert()" des lignes
si "subprice" est à 0 il met NULL !

`$sql.= " ".($this->subprice?price2num($this->subprice):"null").",";`

**Comment by hregis** [comment]
@eldy 
ok, I corrected the origin of the problem

**Comment by hregis** [comment]
@eldy 
ping

**Pull request merged**
