### PR TITLE
zh_cn/admin.lang reworkred

### PR DESCRIPTION
**Pull request by zcattacz**
a complete rework, the machine translation is a brain killer ...

### CODE REVIEW

**Comment by zcattacz** [comment]
Hello folks,

Please kindly keep this request open. I am about to commit translation for the following files too.

admin.lang   categories.lang  compta.lang     margins.lang  products.lang  suppliers.lang
agenda.lang  commercial.lang  contracts.lang  orders.lang   propal.lang    todo/
boxes.lang   companies.lang   main.lang       other.lang    stocks.lang    users.lang

I am wondering if there is anyone else working on this translation. 
I hope by opening this pull request, I can draw attention from ppl 
who watches this project, who speaks Chinese and willing to contribute.

Also certain parts of the English translation is confusing.
I hope I can get help from you in this request.

Regards,
Benton

/--------------------------/
here are some of the items in question:

"offset" in Setup > Dictionary > Payment Terms
--- what is this 'offset' refer to, how does it work?

"Hide VAT Intra num with addresses on documents"
1 what is "intra number" ? 

"Time of VAT exigibility by default according to choosed option:"
what is VAT exigibility ?

Display order of /bank accounts for countries/ using "detailed bank number"
what is bank accounts for countries ?

Order in admin.lang
Is it referring to order of display or order of goods ?

**Comment by eldy** [comment]
Nobody is working on chinese translation.
"intra number" is just "vat number"

order in admin.lang seems to refer to order of goods

offset is a delay before when we ask payment.

**Comment by zcattacz** [comment]
thanks for the notes eldy.

What about  exigibility and "bank accounts for countries" ?
I have have difficulty to understand them.

I have translated the major components of dolibarr for internal use.
A internal evaluation has been scheduled. I may have to recheck/revise my language files 
several times in the next week.

I used English translation as source file. If possible, I'd like to suggest some changes in it too.
eg: 'Allocate a commercial' in company.lang -> 'assigned to business representative'
//normally people refer to tv ads as commercials [noun].
'Hour Company' -> Company Time
I may mix them in in this pull request during the Chinese translation revision.
I wonder if these discussions/fixes on EN lang file are welcomed. 
In my humble opinion, If dolibarr wants more user of different language, the EN interface must look professional and easy to understand, since more coders/users understand EN better than FR （maybe EU and FR's historical colonies are exceptions :-).

**Comment by eldy** [comment]
I validated push.

Yes, you can suggest changes into en_US language too, but prefer doing different push requests.

**Pull request merged**
