### PR TITLE
Fix develop deprecated param

### PR DESCRIPTION
**Pull request by aconits**
Fixed type of parameter int to string for categories

### CODE REVIEW

**Comment by marcosgdf** [comment]
You know it is easier to just change the value of the constant, right? That would give developers some time to adapt their code to the new one

**Comment by aconits** [comment]
I'm thinking the const would be remove in futur because the private var $MAP_ID of "Categorie" class will become a constant and sould replace the old constants var

**Comment by eldy** [comment]
I confirm goal is to remove the $MAP_ID array.
But i would prefer to remove deprecated call by changing value of constant 
const TYPE_XXX = Y
into
const TYPE_XXX = 'yyy'

**Comment by rdoursenaud** [comment]
I agree with @eldy and @marcosgdf.
IMHO constants are better since they are easy to read and write, give the class context and are easy to refactor (Core devs keep control over them).
Strings or ints are fragile and would (already) prevent us from doing (much needed) refactoring work especially since these would be (are) used in external modules out of our reach.

**Pull request closed without merging**
