### PR TITLE
New: Add ref_client field on template invoice

### PR DESCRIPTION
**Pull request by fmarcet**
Add ref_client field on template invoice

### CODE REVIEW

**Comment by eldy** [comment]
Do you have an exemple of what can be a ref_customer on a template invoice ?
If we generate 2 invoices from the template invoice, it means the ref_customer will have both the same value. But the ref_customer is dedicated to store the unique reference of an invoice in to customer information system. 
So this means the field won't be recopied into invoice.
So this is to store which kind of information ? Do you have exemple of value in a real use case ?

**Comment by atm-maxime** [comment]
I think that's because nobody uses this customer ref field on invoice to store the value of the document in the customer information system. Usually it's a title that is used here to display on the PDF the context of the invoice.

**Comment by fmarcet** [comment]
Yes, it's like Maxime says. I think that people use it as something internal reference to the company, not the client's information system. For example, "Hosting monthly dolibarr.org". And every month, the hosting invoice has that reference and is easier to find in the lists

**Comment by eldy** [comment]
This means we ara missing a field "Label of invoice" like we have on supplier invoices.
So i would prefer to introduce this new field "label" for customer invoices (field should have same name and be at same place than the label for supplier invoice).

**Pull request closed without merging**
