### PR TITLE
FIX price calculation on edit line in propal or invoice

### PR DESCRIPTION
**Pull request by aconits**
When we edited line and save without modification on unit price, the input price was fill with 0 value and save the line with this price.

### CODE REVIEW

**Comment by aconits** [comment]
So, I have fix the add line in propal after edited one. 

But js function "checkEditLine" make me trouble, I have compare with 3.6 version and it was same code. The difference is in 3.6 the function seems stopped after test with isNumeric but in 3.7 the function is execute entirely.

Someone can fix me about this function ?

**Comment by eldy** [comment]
Does this pb is also present i to 3.8 ?

**Comment by aconits** [comment]
Present in 3.8 too.

**Comment by eldy** [comment]
I don't understand this bug and fix. 
Also i can't reproduce it on 3.8. Can you describe how you reproduce it more precisely ?

**Comment by aconits** [comment]
My last test : 
-  Margin module activate
- Option "Display margin rates" or "Display mark rates" enabled
- Create product with price 50€ for exemple and add a supplier price 10€ for qty 1
- Create customer order
- Add line with this product
- Edit the line and don't modify ths informations
- When i click on "Save", i can see the unit price input changing to 0 and the line is wrong

**Comment by eldy** [comment]
OK. Bug appears when option Option "Display margin rates" or "Display mark rates" is set. If not, no bug.

It seems there is a lot of occurence of 'nb_MarginRate' and no of 'marginRate', so i think we shoul fix by renaming marginRate into np_marginRate and not this opposite.
So i pushed a PR a little bit different than yours (into develop only for the moment). 26e3fcc63688bc7068da7a8d1afe3a0f4eea4786
Can you tell me it tests are ok on your side after my commit ?
If ok, i will cherry pick it into 3.7 branch.

**Comment by aconits** [comment]
It's work.

**Comment by eldy** [comment]
PR added manually so closed.

**Pull request closed without merging**
