### PR TITLE
Fix mistake: Add back conditional substitution IF/ELSEIF/ENDIF for ODT

### PR DESCRIPTION
**Pull request by lrq3000**
Sorry, my attempt to clean the hooks and triggers patch reverted completely the conditional substitution for ODT patch.

Here the patch will be placed back in the right Git timeline (sorry for the mistake).

Signed-off-by: Stephen L. lrq3000@gmail.com

### CODE REVIEW

**Comment by eldy** [comment]
Don t forget to update file changelog sometimes to reflect new features you add.

**Comment by lrq3000** [comment]
Ah sorry, I didn't know I had the right to do so, I'll think about it next time.

**Comment by marcosgdf** [comment]
@lrq3000 you can do it now by making a new pull request. it's important that people notice the new changes!

**Comment by lrq3000** [comment]
Ok done, also updated the wiki to guide users.

Also, updating the ODT templates to show an example of condition can be a good idea, but I dare not adventure to edit the ODT by myself because I may be not using the same software that produced these templates.

**Comment by marcosgdf** [comment]
@lrq3000 Also I see you didn't add yourself to the copyright block in the top of each file you've changed. This is important for you because it does recognize your effort in Dolibarr.

**Pull request merged**
