### PR TITLE
[ bug #1125 ] Remove senseless validation rules for new lines in customer invoices

### PR DESCRIPTION
**Pull request by openthink-laurent**

### CODE REVIEW

**Comment by eldy** [comment]
You must use the dedicated features for that. They are:
- thirdparty discount.
  or
- credit note invoices
  depending on the need.

**Comment by openthink-laurent** [comment]
OK for commercial reductions, but here are other cases:
- Sometimes a customer ask me to split an invoice containing contract services in 2 invoices, so I have to deduce the half in the first invoice and create a second one with the other half.
- Sometimes I need to add a free product to an invoice and those rules don't accept price at 0.

**Comment by eldy** [comment]
Le 21/11/2013 01:54, Laurent Léonard a écrit :

> OK for commercial reductions, but here are other cases:
> - Sometimes a customer ask me to split an invoice containing
>   contract services in 2 invoices, so I have to deduce the half in
>   the first invoice and create a second one with the other half.
> 
> If a first invoice of 100 was already sent and you have to generate 2
> invoices of 50, you don't have choice. Accountancy rule says that you must:
> solution 1: Create a replacement invoice to replace the invoice 100 with
> an invoice 50 (making replacement invoice, so there is a track to show
> that this invoice is a replacement of the 100 one), then create a second
> for 50.
> solution 2: create a second invoice credit note of 50 (to reduce first
> invoice of 100) + create a third one of 50.
> solution 3: If you did not create the invoice 100 already, better
> solution is when you convert your service into invoice, to edit invoice
> when it is in draft status, to set it to 50 instead of 100, before
> validating it. Later you can also convert your service into invoice for
> 50 again.
> - Sometimes I need to add a free product to an invoice and those
>   rules don't accept price at 0.
> 
> I did a test on develop version. I successfully enter a line with price = 0.
> Are you sure there is a problem here ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Dolibarr/dolibarr/pull/1312#issuecomment-28948751.

## 

Eldy (Laurent Destailleur).

EMail: eldy@destailleur.fr
Web: http://www.destailleur.fr

Dolibarr (Project leader): http://www.dolibarr.org
To make a donation for Dolibarr project via Paypal: contact@destailleur.fr
AWStats (Author) : http://awstats.sourceforge.net
To make a donation for AWStats project via Paypal: contact@destailleur.fr
AWBot (Author) : http://awbot.sourceforge.net
CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by simnandez** [comment]
if you  need to add a free product to an invoice you can put te price and a 100% discount

**Pull request closed without merging**
