### PR TITLE
NEW Remove spaces when copying and pasting into idprof fields

### PR DESCRIPTION
**Pull request by zahwyrix**
# NEW
#29241

### CODE REVIEW

**Comment by zahwyrix** [comment]
@eldy to remember this

**Comment by eldy** [comment]
Some users may need spaces.
Also removing spaces may be expected on other fields 
So i suggest to address this like we addressed the "mandatory field", the "default value", the "default filter", the "focus field".
We can add a tab "copy/paste field cleaner" to allow to define a regex. We can then have js that clean char of field according to this regex.

**Comment by zahwyrix** [comment]
This pull request is a response to the max length attribute, which is very frustrating when copying from a site that presents the SIREN with spaces, for example.

`<input type="text" class="maxwidth200" name="idprof1" id="idprof1" maxlength="9" value="">`

The user may indeed want spaces. Personally, I find it easier to read with spaces, but this is not currently possible with maxlength.

But in fact, your solution is more viable in the long term, plus we could adapt the maxlength with regexes, so I'll keep this pull request aside and try to look into it.

**Comment by eldy** [comment]
> This pull request is a response to the max length attribute, which is very frustrating when copying from a site that presents the SIREN with spaces, for example.
> 
> `<input type="text" class="maxwidth200" name="idprof1" id="idprof1" maxlength="9" value="">`
> 
> The user may indeed want spaces. Personally, I find it easier to read with spaces, but this is not currently possible with maxlength.
> 
> But in fact, your solution is more viable in the long term, plus we could adapt the maxlength with regexes, so I'll keep this pull request aside and try to look into it.

I see.
So i can suggest an intermediate solution before a generic one is available.
When we paste, if the size of content that we try to paste is higher than the maxsize, then we remove spaces, otherwsie we keep value unchanged. We should get the best of the 2 worlds like this.

**Pull request closed without merging**
