### PR TITLE
New Accountancy - transcation creation and mouvement in one single screen

### PR DESCRIPTION
**Pull request by daraelmin**
# NEW Accountancy - transaction creation and movement in one single screen

First step of #20272 - Consolidate all transaction registration screens into a single screen
When pressing on "+" in bookkeeping/list.php 
We can register the whole transaction.
By default, the piece name is the next rowid and the Journal by default is Other.
Hope I'm on the right way

### CODE REVIEW

**Comment by daraelmin** [comment]
Hi @aspangaro,
Could you give a try and tell me what you think about this PR ?
Cheers

**Comment by eldy** [comment]
What do you mean in creation of transaction in one single screen. For me the page to create/edit a transaction is already on 1 page ?

**Comment by daraelmin** [comment]
Hi @eldy,

Actually, when clicking on the "+" button on general ledger you go to this screen 



Then you click save and you go to this screen :



Then you click add to add the second line to balance account (this is treated in my second PR).


So, if you have many mouvement it can be long. 

With this PR, you click "+" button and you can register your mouvement and first transaction on one screen.




The next step is to have both credit and debit transaction ready to be stored (witch is treated in my next PR)

**Comment by daraelmin** [comment]
But, we changed the bookkeeping/card.php since I submitted my PR. So it may be better if I close this one, update it and combine it with the second.

I'll try to tomorrow

**Comment by daraelmin** [comment]
These changes are integrated here : #21217

**Pull request closed without merging**
