### PR TITLE
DRAFT : NEW :New predicted cost and real cost

### PR DESCRIPTION
**Pull request by atm-jpb**
# NEW | Feature  add predicted_cost and real_cost on mrp_mo object

Add predicted cost and actual cost functionality. 
Add a caculateCostLines function in the mrp_mo object 
Add  a function that returns the unit price of a product 

Capture d’écran de 2022-08-16 17-45-05

we can see a  service condition in  calculatecostLines not implemented. i think this part can be handle after some other pr  in pipe that handle this particular point.

### CODE REVIEW

**Comment by atm-jpb** [comment]
backport comment

@[eldy](https://github.com/eldy) eldy [8 days ago](https://github.com/Dolibarr/dolibarr/pull/21765#discussion_r947109417) • 
I suppose that
real cost is the "observed price" once production is finished ?
Is it a value defined by end user or a calculation done by the computer ?

Same for predicted_cost ? Is it an estimation done by end user or a calculation ?

Member
Author
@[atm-jpb](https://github.com/atm-jpb) atm-jpb [8 days ago](https://github.com/Dolibarr/dolibarr/pull/21765#discussion_r947115018) • 
it's the qty with the flag toconsume in mrp_production

Member
Author
@[atm-jpb](https://github.com/atm-jpb) atm-jpb [8 days ago](https://github.com/Dolibarr/dolibarr/pull/21765#discussion_r947115911) • 
and it's a calculation (product unitcost * qty)

**Comment by atm-jpb** [comment]
@eldy hi, i don't understand the travis CI error : 
1) EmailCollectorTest::testEmailCollectorCreate
openssl_encrypt(): Using an empty Initialization Vector (iv) is potentially insecure and not recommended

it seen to be outside my dev ...

**Comment by atm-jpb** [comment]
@eldy   
travis 
1) SecurityTest::testGetURLContent
Should GET url 301 with following -> 200 but we get 503
Failed asserting that 503 matches expected 200

the dev is not concerned by this one i presume.

**Comment by atm-jpb** [comment]
@eldy  travis error  it does not come from this PR
Found a tag <br /> that is for xml in file install/doctemplates/websites/website_template-stellar/containers/page23.tpl.ph

**Comment by atm-jpb** [comment]
@eldy

**Comment by eldy** [comment]
predictedcost = Expected cost to consume
realcost = Cost already consumed

**Comment by atm-maxime** [comment]
@atm-jpb After discussions with @eldy, I made 2 commits I want to review with you (ff6880787b6c9417ebebd62b606494f5649a39f8)
Furthermore I think this PR can't be merge like this, we need to discuss the storage of the costs.

**Pull request closed without merging**
