### PR TITLE
Printing System which may accept modules

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by frederic34** [comment]
drivers
google_print

**Comment by marcosgdf** [comment]
Is this related to bug 1762?

**Comment by frederic34** [comment]
Hi Marcosgdf, it's not related to bug 1762, but it may remain present. With the old module printipp, you had only one choice for printing, but with this PR you can choose printipp or google cloud print or any other future module. It's works but code have to be cleaned that's why I share it.

**Comment by marcosgdf** [comment]
Ok. The thing is that the class might be the problem, it is from 2008 and not maintained, we don't even know the author. It would be nice if you have a look at alternative classes like https://github.com/mfly/php-ipp or whatever and tell us if they perform better or not.

**Comment by BebZ** [comment]
Is it merged or closed ?
When it is set as closed after a merge does it mean it's reverted ?

Frederic don't you have planned to make a sort of "scanIPP" ? (does it exist at all ?)
I know Eldy did a scan module, but my server is at OVH, not at my office, and I'm not sure OVH will let me in their datacenter ;)
It would be nice to record supplier's invoices then click on a button and scan the invoice to store it safely in our wonderful Dolibarr :)

**Comment by marcosgdf** [comment]
The status is merged, not closed.

**Pull request merged**
