### PR TITLE
Develop deplacement

### PR DESCRIPTION
**Pull request by aspangaro**
Renamed field km into amount to prepare payment for this module

### CODE REVIEW

**Comment by aspangaro** [comment]
I copy/paste the conversation began in other pul request

@Eldy :: This module should be changed to work like others (by adding details of lines on a trip card).
So changing this into parent table is not the good way. We must instead add field "total_ht", total_vat" and total_ttc and localtax fields like for other elements.

Adding payment before rewriting the module to work this may be a waste of time because we will have to replace the module with this new way of working.

**Comment by aspangaro** [comment]
Ok Eldy.

It's the better way but you see a new complete module or an evolution who keep the old field (km/amount) ?

**Comment by eldy** [comment]
Thebold field km must be forgotten and replace wih llx_deplacement_det. Migration script will move this value into a line of new table to keep compatibility.

**Comment by aspangaro** [comment]
Thanks. I have some work I believe

**Pull request closed without merging**
