### PR TITLE
Translate hebrew3

### PR DESCRIPTION
**Pull request by agarama**
# Instructions
*This is a template to help you make good pull requests. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "FIX", "CLOSE", "NEW", "PERF" or "QUAL" section* (use uppercase to have the PR appears into the ChangeLog, lowercase will not appears)
- *follow the project [contributing guidelines](/.github/CONTRIBUTING.md)*
- *replace the bracket enclosed texts with meaningful information*

# FIX|Fix #[*issue_number Short description*]
[*Long description*]

# CLOSE|Close #[*issue_number Short description*]
[*Long description*]

# NEW|New [*Short description*]
[*Long description*]

# PERF|Perf #[*issue_number Short description*]
[*Long description*]

# QUAL|Qual #[*issue_number Short description*]
[*Long description*]

### CODE REVIEW

**Comment by eldy** [comment]
Thanks for your contribution.
However PR on files into langs/xx_XX where xx_XX is not en_US is useless because files are erased by Transifex translation of en_US. Change on translation files must be done with PR for en_US only. For other languages (en_NZ, es_ES, ...), fix of translation must be done directly on https://www.transifex.com/dolibarr-association/dolibarr/

**Comment by mdeweerd** [comment]
Note: you can probably import the lang files on transifex.

**Comment by agarama** [comment]
> Note: you can probably import the lang files on transifex.

there is no hebrew in transifex. someone can please add it? i can mange/translate it.
but i cannot find any "Project languages " for dolibarr.

**Comment by mdeweerd** [comment]
"Reminder:" there is `dev/translation/txpush.sh` to push the translations to transifex..

**Comment by mdeweerd** [comment]
https://app.transifex.com/dolibarr-association/dolibarr/language/he_IL/

**Pull request closed without merging**
