### PR TITLE
task #768  &  task #769

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by FHenry** [comment]
ok, Iwill lokk how to do it better

**Comment by FHenry** [comment]
Ok it's done. I let you check.

**Comment by FHenry** [comment]
Why not but it mean that people put HTML even if WYSIWG is disabled.
I've done the changes.

**Comment by eldy** [comment]
Option WYSIWIG means "user has an editor to enter data". User should be able to enter html event without editor.
Also image you change option WYSIWIG after data was entered. If you entered HTML before changing option, process must works ith HTML, because process must depends on what there is into database, not on current option to enter future data into database. Not sure my explanation is clear :-(

**Pull request merged**
