### PR TITLE
NEW add geometrics extrafield

### PR DESCRIPTION
**Pull request by frederic34**
image
image

### CODE REVIEW

**Comment by frederic34** [comment]
as json : 

image

**Comment by rycks** [comment]
Hello @frederic34 
please have a look at https://www.dolibarr.fr/forum/t/idee-lancee-sur-le-github-de-dolibarr-ajouter-la-geolocalisation-des-objets-dolibarr/44366

json is - i think - a bad idea : with json i think we could'nt get the power of GIS SQL requests to make thinks like distances searchs

Éric

**Comment by frederic34** [comment]
it use Point to store in db (json was just to try to display it)

image

**Comment by rycks** [comment]
> it use Point to store in db (json was just to try to display it)

Ho sorry,
shame on me i don't take the time to look at the code you made (that's a special weekend here)

**Comment by frederic34** [comment]
image

**Comment by frederic34** [comment]
image

**Comment by frederic34** [comment]
image

**Comment by rycks** [comment]
waouuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu !!!!!!


splendid !!!!! THANKS A LOT @frederic34 !!!!!!!!!

**Comment by frederic34** [comment]
@rycks everybody can now fix the javascript editor 🙄 for the fields

**Comment by lmag** [comment]
Well Done !!!!!! Wahooo!

**Comment by BebZ** [comment]
Wonderfullll :) As a user, i really appreciate the screenshots, else I would only be stare at my screen like Neo, some minutes after taking the red pill :)

**Comment by Thatoo** [comment]
@frederic34 It looks awesome and seems to answer [this issue](https://github.com/Dolibarr/dolibarr/issues/26111#issuecomment-3340518422). Could you tell me how to benefit from your work?
When I go to the "Tiers" module configuration panel and go to extrafield, in the type list, I can't find the "point" type. Is there something I should do to activate that option?

**Comment by frederic34** [comment]
you need to add MAIN_USE_GEOPHP

**Comment by Thatoo** [comment]
Sorry but add MAIN_USE_GEOPHP to what? where in Dolibarr?

**Comment by frederic34** [comment]
In french Accueil/Configuration/Divers

**Comment by Thatoo** [comment]
And in Value (valeur), I write "POINT"?

**Comment by frederic34** [comment]
just '1' or anything else, it just had to exist

**Comment by frederic34** [comment]
image

image

**Pull request merged**
