### PR TITLE
Dictionnary for label sticker and card format

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by frederic34** [comment]
2016-02-06 14_01_52-dolibarr
2016-02-06 14_00_58-imprimer code-barres

**Comment by BebZ** [comment]
Salut Fred, 

Are those labels also available for product's barcodes ? 
Is it planned to print stickers when ventilating a supplier order to stocks ? 
Especially when you have recorded the products received with barcode, batch and dluo , and the stock location (warehouse)
if possible to generate a sticker sith all these infos to stick on the product...

Maybe I open a feat.req ?

**Comment by frederic34** [comment]
http://www.dolibarr.fr/forum/12-howto--aide/54832-imprimer-code-barre-sur-etiquette

**Comment by aljawaid** [comment]
this would be nice to be able to print price stickers and barcode/text for products.

**Pull request merged**
