### PR TITLE
NEW payments by check process

### PR DESCRIPTION
**Pull request by atm-greg**
# New payment by check process
Change behaviour of the module "CheckDeposit" to match with reality.

When we receive a payment by check, the check is not in bank until we bring it and then the bank.
The bank create an entry for the global bordereau and not for each check.

So in dolibarr, we must not create bankentry on payment by check but we create a global entry on check deposit.

### CODE REVIEW

**Comment by eldy** [comment]
So imagine a customer C1 give one cheque of 100 euros and customer C2 give one cheque of 50 euros.
Do you mean, you create when you make deposit of cheque an entry of 150 euro into llx_bank ?
With current behaviour, there is 2 line,
The line 1 is linked to thirdparty C1 and payment of C1 (link is in llx_bank_url)
The line 2 is linked to thirdparty C2 and payment of C2 (link is in llx_bank_url)

After you patch, there is 1 line in llx_bank but what are the link to customers (2 links become none) and what are the links on payments ?

**Comment by atm-greg** [comment]
I totally missed this part.
So I didn't create links.
After some test, I've got a problem : there's a uniqueness constraint on fk_bank-type that prevent's me to create the several links (for payments and customers) to the same fk_bank...
Is this constraint still useful today ?

**Comment by atm-greg** [comment]
otherwise, I cant link the bankentry just to the bordereau where we can ge the payments and customer infos.
This could be better, don't you think ?

**Comment by eldy** [comment]
Yes, we are limited to 1 link of 1 type into llx_bank_url. A lot of current code rely on this, above all the accounting module making the dispatching into the ledger of bank records.

Solution is to include field url_id into the unique key of llx_bank_url
Then we must fix interface at the different places where the bank_url is used to be compatible with several lines.

**Comment by atm-maxime** [comment]
We'll review this at devcamp, but I think the bank url must only link the bank entry to the bordereau. This was the case with the prelevement module, but now this module creates one bank entry per invoice, which is wrong imho.

**Comment by eldy** [comment]
See discussion on #9984 for the road to fix this.

**Pull request closed without merging**
