### PR TITLE
select_duration are limited to 24h on input text

### PR DESCRIPTION
**Pull request by defrance**
and minute to 60
as it made on combo-box?
think it's nedded because the function 	 convertTime2Seconds fails if the value wasn't on this range..

### CODE REVIEW

**Comment by eldy** [comment]
On which screen do you experience. Currently i can enter duration of 30 hours without trouble (it is done on purpose) ?

**Comment by defrance** [comment]
on my personnal development (management) when i enter time passed on a day
you have the function htdocs/projet/tasks.php for time need on task but in this case we can't limit on 24h the time entered.
maybe we need another parameter (ex : "text24") on the function to limit (or not) entered duration

**Comment by eldy** [comment]
Yes, introducing  a type 'text2359' to add a limit to 23h and 59 min seems or 'text2460' (if you need to allow 24 too) is the good solution to keep backward compatibility

**Comment by eldy** [comment]
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolete, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.

**Pull request closed without merging**
