### PR TITLE
Add possibility to add lines in the dashboard without changing index.php

### PR DESCRIPTION
**Pull request by Pfontaine**
This addition to the code allows external modules to easily add lines in the dashboard without changing the file htdocs/index.php

To use this feature simply add a few lines in the module declaration file.

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Looks like a neat feature :+1: 
I would have preferred an object rather than an array for declaration though (Makes autocompletion in IDEs and overall manipulations easier). But I'm nitpicking ;)

**Comment by Pfontaine** [comment]
Actually I hesitated between an object and an array (I prefer objects too, mainly because I am lazy and autocompletion is cool) and my choice fell on array to maintain consistency with the rest of the module declaration file.

**Comment by eldy** [comment]
Where does the new lines appears ? Into statistics ?
Why introducing a sql table ? A hook into index.php page should be enough to allow an external module to add content. Enhancing the hook "addStatisticLine" to use the value return by hooks into 
hookmanager->resArray to complete the current array of dashboard lines would be a better choice.

**Comment by rdoursenaud** [comment]
I agree with @eldy a hook is better suited but the main idea is great nonetheless!

**Comment by eldy** [comment]
Sure, idea is really welcome, but I need an implementation that use hook instead of sql table to validate it.

**Comment by rdoursenaud** [comment]
@Pfontaine Are you still willing to take care of it or should we open a feature request?

**Comment by eldy** [comment]
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Pull request closed without merging**
