### PR TITLE
target the right anchor on POST to addline form

### PR DESCRIPTION
**Pull request by cfoellmann**
On submission of the addline form the resulting URL should target the `#addline` anchor (css id) added to the tpl

That way after adding a new line the form gets focused again

### CODE REVIEW

**Comment by eldy** [comment]
Is it to have the page at the same position after submitting a form ? If yes, we have abandonned the use of anchor. Instead we use the css "reposition" on a link and input button so page remain at same position.

**Comment by cfoellmann** [comment]
Then it is not working what you have tried to implement.
The anchor #line_* is present so it is just using the same technique.

Something working needs to be implemented. My users are going crazy on items with a lot of lines

**Comment by cfoellmann** [comment]
I think a class for pages is overdue.
Fixes or changing stuff All over the place is soo hard to get right completely if not impossible.

An extendable class for pages is the way to got. Still old school but a step into the right direction

**Comment by eldy** [comment]
Can you describe the process to reproduce the trouble ?
I tested on invoice on develop version, i have no trouble, after submit a new line to add on invoice, screen and form remains at same position

**Comment by cfoellmann** [comment]
I am sorry for the trouble I am causing from time to time.
It is a problem with a module I should not have tested on my dev test environment

**Pull request closed without merging**
