### PR TITLE
NEW Import chart of accounts for accounting

### PR DESCRIPTION
**Pull request by kkhelifa-opendsi**
Add import chart of accounts for accounting

### CODE REVIEW

**Comment by aspangaro** [comment]
Hi Kamel, thanks for the export.

Just a question, Why create a new file caccoutingcategory.class.php while a file already exist into htdocs/accountancy/class/accountancycategory.class.php ? Maybe merge the 2 files ?

**Comment by kkhelifa-opendsi** [comment]
hi,

htdocs/accountancy/class/accountancycategory.class.php had only requests on the table llx_c_accounting_category in 2 / 9 functions (getCatsCpts and getCats).

It's manage the categories of the tables llx_accounting_account and llx_accounting_bookkeeping.
Not the dictionary table llx_c_accounting_category as htdocs/core/class/ccountry.class.php for exemple.

It's used in import of user for exemple (htdocs/core/modules/modUser.class.php):
$this->import_convertvalue_array[$r]=array(
	'u.fk_state'=>array('rule'=>'fetchidfromcodeid','classfile'=>'/core/class/cstate.class.php','class'=>'Cstate','method'=>'fetch','dict'=>'DictionaryState'),
	'u.fk_country'=>array('rule'=>'fetchidfromcodeid','classfile'=>'/core/class/ccountry.class.php','class'=>'Ccountry','method'=>'fetch','dict'=>'DictionaryCountry'),
	'u.salary'=>array('rule'=>'numeric')
);

**Comment by RomainDeschamps** [comment]
Hello,
Would be a nice feature. what is the topic to be discussed ?

**Comment by eldy** [comment]
@kkhelifa-opendsi We should not have 2 DAO class for 1 table.
Why not moving all properties and method of your new class into the already existing one ? It seems it should still works as expected.

**Pull request closed without merging**
