### PR TITLE
3.7 feature workflow

### PR DESCRIPTION
**Pull request by tiaris**
It should not be possible to create an invoice from shipping when linked order or propal is allready billed or has an invoice.

### CODE REVIEW

**Comment by braito4** [comment]
You should correct this pull; just download again the last version of the development branch and add again the changes.
Your version is too old, too many changes; and this will create a lot of problems.

**Comment by rdoursenaud** [comment]
Well yes or just learn how to use git rebase.
[FR] http://git-scm.com/book/fr/v1/Les-branches-avec-Git-Rebaser

**Comment by eldy** [comment]
Sometimes a shipment is billed in several times. If we lock invoice process when there is one invoice, we lock user when he need to make second invoice. For example when first invoice was canceled or when invoice is done inseveral steps. A warning saying "This shipment is already linked to an invoice, are you sure you want to create another invoice" would be better.

**Comment by eldy** [comment]
PR #2347 seems to be same but cleaner, so i close this one.

**Pull request closed without merging**
