### PR TITLE
NEW : integration HRM sql and migration files

### PR DESCRIPTION
**Pull request by atm-gauthier**

### CODE REVIEW

**Comment by atm-gauthier** [comment]
Hi @eldy, you will find here my sql integration for hrm module.
PHP code will come in a second PR

**Comment by aspangaro** [comment]
Thanks @atm-gauthier ! Maybe close the other PR #18817 ?

**Comment by atm-gauthier** [comment]
@aspangaro yes good idea ;)

**Comment by eldy** [comment]
Can you make a summary of each table with an explanation of goal for each one (an example of record may be enough to understand) ?

**Comment by atm-gauthier** [comment]
llx_hrm_skill : skill label and description
llx_hrm_skill_extrafields
llx_hrm_skilldet : available rank descriptions
llx_hrm_skilldet_extrafields

image

llx_hrm_job : job label and description
llx_hrm_job_extrafields (not used for the moment)

image

llx_hrm_position : user working at this position with start date and end date if necessary
llx_hrm_position_extrafields (not used for the moment)

image

llx_hrm_evaluation : allow to create evaluation of an employee for a job
llx_hrm_evaluation_extrafields
llx_hrm_evaluationdet : rank of user for each skill at the moment of the evaluation
llx_hrm_evaluationdet_extrafields (not used for the moment)

image

llx_hrm_skillrank : we'll find here all skill with recquired rank for a job, and current rank of all skill an employee has been already evaluated

image

image

**Comment by atm-gauthier** [comment]
After having evaluate some employees, we can compare their skill by usergroup

image

or compare a usergroup with skill level required for a job

image

**Comment by lmag** [comment]
I love this !

**Comment by atm-gauthier** [comment]
To finish you can see how many skills you will lost if an employee resigned from his job.

Before :

image

After :

image

**Comment by eldy** [comment]
My understanding is that llx_hrm_position  table is a link (with properties) between a user and a job.
To make things easier to understand can you rename   llx_hrm_position into   llx_hrm_job_user ?

**Comment by atm-gauthier** [comment]
@eldy you're right, i'm going to do this as soon as possible

**Comment by atm-gauthier** [comment]
Hi @eldy, now hrm_position's name is hrm_job_user everywhere

**Comment by dumitrugrl** [comment]
From what module are the screenshots above? I am using 17.0.0-alpha and I cannot see those views in the HRM module.
Thank you!

**Comment by atm-gauthier** [comment]
Hi @dumitrugrl, these screens come from hrm module, but it is still experimental, then if you want to work with it, you have to set hidden conf "MAIN_FEATURES_LEVEL" with value "2" to make it visible in modules list. But be careful, with this conf set to "2", you will be able to use potentially instable features which could cause unexpected bugs on your environnement.

**Comment by dumitrugrl** [comment]
thank you @atm-gauthier.
I am new to this project and was not aware of that setting. 
I really appreciate your help!

**Comment by dumitrugrl** [comment]
Awesome! Exactly the features I was looking for.

Is there any other configuration I need to do to get around this error when trying to access the Employees List?

image

**Comment by dumitrugrl** [comment]
Another issue that I am facing (even with MAIN_FEATURES_LEVEL = 0) is missing the Tools > Resources module UI.

image

I am not sure if the sidebar not being rendered full height is also and issue here:
image

**Comment by dumitrugrl** [comment]
I defined Jobs and required skills.
I created an Evaluation for the Employee having a position for that Job.
The problem is that I am missing the Skills from the Evaluation in the User card -> Skills Tab

Does any other config parameter need to be enabled for the evaluated skills to show in the employee card?

image

image

image

**Comment by dumitrugrl** [comment]
Is anoyone else experiencing the same issue as above: evaluated skills not showing in the User Card -> tab Skills?

**Pull request merged**
