### PR TITLE
FIX: #22581

### LINKED ISSUE #22581: Shipping multiple products that have unique serial numbers
### Bug

When shipping product with serial number We can ship a quantity greater than 1

### Expected and actual behavior

- [ ] Step 1 : Solve #22582 
- [ ] Step 2 : add the link between shipment lines and stock movements

### Steps to reproduce the behavior

_No response_

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by FHenry**
FIX: #22581

### CODE REVIEW

**Comment by lmag** [comment]
Missing number lot/serial in message ?

**Comment by eldy** [comment]
@FHenry Can you help me to merge this into develop ?

**Comment by lmag** [comment]
@altairis-noe

**Comment by FHenry** [comment]
@eldy  Why did you change merge branch to develop, it's a bug into from 14.0 not a feature ?

**Comment by eldy** [comment]
> @eldy  Why did you change merge branch to develop, it's a bug into from 14.0 not a feature ?

Nearlly.
It is a control that is not implemented. So it can be viewed as a bug but it is also something not yet coded. Also it will introduce a restriction making some action no more possible when it was before. Yes this is in hope to fix a bug but it also change the behaviour of what app accept. This is not a blocking bug and it has also a high risk of introducing regression (because it introduce new restrictions that didn't exists before). So such changes can be qualified as bug or as feature not completely implemented. Don't forget, in a stable, we try to fix "blocking or very annoying" bugs in priority and avoid others, other enhancements must be in develop. Before it has a high risk of regression. The fact that there is a lot of conflict with current code and merging looks difficult is a good proof of this level of risk, make me think it is better to qualify this a feature not yet completely implemented and trying to merge it in develop so we can benefit of the long beta phase if this has side bad effect.

**Comment by lmag** [comment]
In this case are you ok to validate this feature in development? If we adapt it?
@altairis-noe

**Comment by altairis-arre** [comment]
it's seems to be a real problem to be able to send several times a unique SN no ?
it's a bug, not a new feature.

**Comment by FHenry** [comment]
@eldy There a PR on develop branch

**Comment by eldy** [comment]
Merged in develop.

**Pull request closed without merging**
