### PR TITLE
New : HRM integration

### PR DESCRIPTION
**Pull request by atm-gauthier**
# Instructions
*This is a template to help you make good pull requests. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *only keep the "Fix", "Close" or "New" section*
- *follow the project [contributing guidelines](/.github/CONTRIBUTING.md)*
- *replace the bracket enclosed texts with meaningful information*

# Fix #[*issue_number Short description*]
[*Long description*]

# Close #[*issue_number Short description*]
[*Long description*]

# New [*Short description*]
[*Long description*]

### CODE REVIEW

**Comment by atm-maxime** [comment]
Some description and screenshots would help understand the goal of this PR. And it's linked to #17947

**Comment by atm-gauthier** [comment]
@atm-maxime I know, I will do that on Monday, I didn't have enough time today

**Comment by eldy** [comment]
Before submiting the code, as it is a large PR, can you first submit only the changes into database (.sql) so the structure can be validate.

**Comment by atm-gauthier** [comment]
Hello @eldy, no problem I will do that as soon as possible.

**Pull request closed without merging**
