### PR TITLE
NEW Support some HTML contents into ODT documents

### PR DESCRIPTION
**Pull request by Tim-Otte**
# New: Converting html to odt format
With this change it is possible to format texts and to apply this formatting to ODT files. Currently, the tags b, strong, i, em, u, s, sub, sup and span are supported, although span can contain additional formatting in the form of the style attribute. This can contain the font, font size and font color of the text within the tag.

### CODE REVIEW

**Comment by Tim-Otte** [comment]
@eldy This PR is ready to test and merge.

**Comment by eldy** [comment]
Can you move content of class HtmlToODT into the class includes/odtphp/odf.php
This library is no more an external project so we will move it as Dolibarr class. Having another class will generate 2 class to manage odf when we already have one (so no more need to add another class and keep use the existing one that will become soon a Dolibarr class).

**Comment by Tim-Otte** [comment]
- [x] Commit tested
- [x] No change in functionality detected
- [x] PR ready to merge

**Comment by Tim-Otte** [comment]
@eldy Why did the tests fail? My change should not affect the _AdminLibTest_...?

**Comment by Tim-Otte** [comment]
I fixed some bugs. PR now ready to merge.

**Pull request merged**
