### PR TITLE
Feature request: Extrafields - store computed value #11435

### LINKED ISSUE #11435: Feature request: Extrafields - store computed value
# Feature Request
 Extrafields - store computed value
Now computed values are (conceptually just!!!) computed when needed in forms or lists. 
However, they are also used in analytics and bi, and these read the table. In the table the values is null.

## Use case 
Direct access to table <object>extrafields needs also computed values

## Suggested implementation
alter commonobject.class.php, function insertExtraFields so that computed fields are stored in stead of null

## Suggested steps
change commonobject.class.php

### PR DESCRIPTION
**Pull request by fbosman**
# Fix #11435 
extrafields: store computed value

### CODE REVIEW

**Comment by atm-maxime** [comment]
What happens if the computed value uses some data from another object or a setup value ? If this data is changed, the computed value changes but not the stored data since there would have been no insertExtrafields called. So you will see a value on the screen which is not the one in the database ?

**Comment by fbosman** [comment]
You do have a valid point in this issue.
That’s why I stated that it is conceptually right not to store calculated values in the database.
However, as often is the case, this is a trade-off between risk and functionality.
Maybe I can limit the storage to the cases where there is no other object in the formula, but still this is a risk.
I can also set a parameter to let the user make a choice.

Frans Bosman

**Comment by atm-maxime** [comment]
I think this should be an option (hidden at first), something like MAIN_STORE_COMPUTED_EXTRAFIELDS. And add a big fat warning next to the formula input saying that the stored value will only be updated after the object itself is updated.

**Comment by fbosman** [comment]
I made the adjustments arm-maxime proposed.
But I do think that he is right with his warning!
Persistence of derived values is wrong by design, however this is a trade-off.
I think Dolibarr would clearly benefit from a logical data/object layer. The database-code is to much scattered in the code

**Pull request merged**
