### PR TITLE
fix the bill replacement with discounts #8028

### LINKED ISSUE #8028: Replace a customer invoice with discounts
# Instructions
* Create an invoice for a customer. (eg : _OUT15-980756_)
* Add some fix discounts on it.
* Create a replacement invoice for the invoice _OUT15-980756_
image

# Bug
The systems doesn't create the replacement invoice because some discounts are already used.

## Environment
- **Version**: 6.0.4, (maybe the other too)

## Solution
Actually I don't know which solution is the best one. Here some solutions:

1. We create the replacement invoice without discounts, up to the user to create new discounts and apply them.
2. We duplicate discounts and apply them on the replacement invoice.

@eldy do you have a better idea ? To which solution do you prefer to go ?
FYI : I can fix it myself

### PR DESCRIPTION
**Pull request by laudeco**
# Tests
* Create an invoice for a customer. (eg : OUT15-980756)
* Add some fix discounts on it.
* Create a replacement invoice for the invoice OUT15-980756

# Fix #8028 
Replace a customer invoice with discounts

### CODE REVIEW

**Comment by eldy** [comment]
Adding the discount twice (in another invoice) may be dangerous.
Imagine discount is a deposit. You will get the deposit twice in an invoice and a cloned invoice.

We must add a test around your solution that add the same discount to include the discount a second time only if the created invoice is a replacement invoice (if $this->type == Facture::TYPE_REPLACEMENT)
Also we must check the side effect when we go on the view of discounts. When it says it is consumed, what is the invoice shown (first one or second one ? we should show the 2 invoice).

Because, it is a critical change that , it is more welcome in develop branch.

**Comment by laudeco** [comment]
As soon as I create a new discount, it doesn't change anything on this view.

But good catch for the check on the type !

I would like to integrate this fix in the 6.x.x as I need this fix ASAP and I never deploy a forked version on my production...

**Comment by laudeco** [comment]
@eldy any news about this PR ?

**Comment by laudeco** [comment]
@eldy  could you validate / revoke this PR please ?  Or at least let me know if I need to change something

**Comment by laudeco** [comment]
@eldy  why didn't you merge it on 7.0 ?

**Pull request merged**
