### PR TITLE
add serials separator configuration

### PR DESCRIPTION
**Pull request by altairis-tof**
add a config option to define separator that will be used later in multple serials input options (cf old PR https://github.com/Dolibarr/dolibarr/pull/16975)
Configuration_du_module_lot_série_+_multicompany_-_2021-04-08_10 33 24

### CODE REVIEW

**Comment by eldy** [comment]
I don't think there is a , or ; or space as part of a serial number.
So i don't think we need a setup here.
Why not just consider any char  [,;\s] as separator for list of serial ?

**Comment by altairis-tof** [comment]
how do you explode a string without specifying a specific separator ?

**Comment by eldy** [comment]
`$myarray  =   preg_split('/[,;\s]+/',  $thestringtoexplode);`

**Comment by altairis-tof** [comment]
ok for me ! thanks for the tips. 
i close the PR.

**Comment by BebZ** [comment]
how do you explode or "consume" quantities on each batch ? 
if you enter in dispatch 3 batch numbers :  
AAA;BBB;CCC and a qty of 30 
it will add 10AAA 10BBB and 10CCC  
or 30 of each in stock ?
 or do you plan a verification if there is a batch separator, so there must be as many batch numbers as qties ?
so for qty 30 you will have (mandatory) to input 30 batch numbers ? : 
AAA;BBB;CCC...AAE ?

Thanks

**Comment by lmag** [comment]
With this ultime solution it will work

LOT1;QTY1;WAREHOUSEID1
LOT2;QTY2;WAREHOUSEID2
LOT3;QTY3;WAREHOUSEIDX

**Pull request closed without merging**
