### PR TITLE
NEW: Adding template 02

### PR DESCRIPTION
**Pull request by Quatadah**
#NEW [Template 02 adapted and added]

### CODE REVIEW

**Comment by Quatadah** [comment]
all #21568 fixes are pushed.

**Comment by eldy** [comment]
Pas d'amélioration avec ce zip.
Peut tu regarder dedans :  As tu bien l'arbo  medias/image/websitekey/    et dans ce rep tu dois avoir les images que tu as sur ton env de travail à condition qu'elles aient bien été stockées dans   images/xxx/    ou xxx = nom du site web.

**Comment by eldy** [comment]
I have an error when loading the file. There is a sql error into the generated file website_pages.sql
Did you build the zip using the very last version of Dolibarr ?
The file website/class/website.class.php must contains the line
`$line .= (int) $objectpageold->allowed_in_frames;`
into method exportWebSite()
This fix has been introduced with commit 89f7e5ad30ed1685fe5181e4868bca12ad06b220
You must also hve the fix c804469082ae9748094f5ed24368fc6b652d96df

If not, can you regenerate the zip with the very last version of develop branch and resubmit PR.
Also i test to convert your .png images and the size is 4 times smaller with format .webp instead of .png. Can you use this format for the static images (PS: You have a button into the media manager of Dolibarr to convert all images into .webp)

Note that the template03 has not this trouble and was generated with the correct version.

**Comment by Quatadah** [comment]
All done, PR is here  #21656

**Comment by eldy** [comment]
Fixed by https://github.com/Dolibarr/dolibarr/pull/21656

**Pull request closed without merging**
