### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by marcosgdf**
Check commit messages for more info.

Redundant code commit is because `dolibarr_set_const` already sets the value in `$conf->global`

### CODE REVIEW

**Comment by eldy** [comment]
I don't think we should remove the dol_htmlentites. Reason is that default value of htmlentites are set to provide unpredicable results (double encode or encoding depending on env). dol_htmlentities use default value that match dolibarr rules (UTF8 and no other change than html entities)

**Comment by marcosgdf** [comment]
I'm removing the deprecated mark because until PHP 5.4 default encoding param is  ISO-8859-1 and not UTF-8

**Comment by marcosgdf** [comment]
Travis CI build fail has nothing to do with this PR

**Comment by marcosgdf** [comment]
Joined PR with #2456

**Pull request closed without merging**
