### PR TITLE
Fix add field fk_accounting_category (code) into the export of chart of accounts

### PR DESCRIPTION
**Pull request by kkhelifa-opendsi**
Add field fk_accounting_category (code) into the export of chart of accounts of accounts (accounting)

### CODE REVIEW

**Comment by eldy** [comment]
What is goal of table c_accounting_category compared to accounting_category ?

**Comment by kkhelifa-opendsi** [comment]
Because fk_accounting_category is linked with llx_c_accounting_category and the table llx_accounting_category does not exist.
And the "Personalised group" in the configure menu of accounting (htdocs/accountancy/admin/categories_list.php) manage c_accounting_category.

**Comment by aspangaro** [comment]
@kkhelifa-opendsi Kamel, tu peux clore ce PR stp, merci ;)

**Comment by eldy** [comment]
Adding fk_accounting_category into export of table generates duplicates records when exporting the chart of account. Because this field is dedicated to another feature (not yet really stable and useable), it would be better to add another export profile for that, for example called "Export content of groups of accounts".

**Comment by eldy** [comment]
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolete, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.

**Pull request closed without merging**
