### PR TITLE
NEW : TakePOS - alternative payment screen

### PR DESCRIPTION
**Pull request by altairis-tof**
add constant TAKEPOS_USE_NEW_PAYMENT_SCREEN to use alternative payment screen 

image

### CODE REVIEW

**Comment by eldy** [comment]
Can you describe the main difference with current pay.php page ?

**Comment by altairis-tof** [comment]
> Can you describe the main difference with current pay.php page ?

. add a validate button
. group validate, clear and cancel button on the right (A)
. group payment modes after (A)
. add payment list if customer pays with several payment modes for the same invoice
. add remain to pay when doing several payment modes
. add colors
there is a screenshot in the PR description

**Comment by eldy** [comment]
It seems a lot of feature introduced into the pay.php has been lost. 
The tag NOCSRFCHECK must not be set.

I recommend instead of replacing a page with a new one with some feature added and other removed to make 1 PR by feature (PR must be atomic) with small enhancement 1 by 1.

**Comment by altairis-tof** [comment]
i will try to do it; not simple to go back into this javascript mess after all this time

**Comment by altairis-tof** [comment]
replaced by https://github.com/Dolibarr/dolibarr/pull/27268 and https://github.com/Dolibarr/dolibarr/pull/27269

**Comment by josett225** [comment]
Hi @altairis-tof 
Are you doing a new PR for pay2.php?
Regards
Jose

**Comment by altairis-tof** [comment]
> Hi @altairis-tof Are you doing a new PR for pay2.php? Regards Jose

Hello @josett225 it was too complicated to do a PR for pay2.php, i prefer allow to use an alternative payment url (https://github.com/Dolibarr/dolibarr/pull/27269) so anyone can make its own payment screen.
it would be too difficult to manage two different payment screens in the core.

**Pull request closed without merging**
