### PR TITLE
NEW Add type of category from a dictionnary

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
NEW Add type of category from a dictionnary :
- add a dictionnary for all types of category

This feature is useful to add a new type of category in a module.

### CODE REVIEW

**Comment by lvessiller-opendsi** [comment]
How can I resolve this conflict in migration "10.0.0-11.0.0.sql" file ?

**Comment by lvessiller-opendsi** [comment]
@eldy 
How can I resolve this conflict in migration "10.0.0-11.0.0.sql" file ?

**Comment by lvessiller-opendsi** [comment]
@eldy 
Resolved conflicts

**Comment by lvessiller-opendsi** [comment]
@eldy 
New conflicts resolved

**Comment by aspangaro** [comment]
Ping @eldy -> PR verified

**Comment by lvessiller-opendsi** [comment]
@eldy 
all conflicts resolved

**Comment by philippe-opendsi** [comment]
Hi @eldy will this PR merged ? We have other potential PR to propose but depending of the merge of this one.

**Comment by eldy** [comment]
I don't think using a table to store the definition of an array that contains constant is a good idea. The array of categories was introduced to solve problem of portability and migration but we should be able to have it as simple as a list of n constant per n categories.
And using a table just to be able to extend this list means we will make database access on each page call just to get a list of 8 constants (because categories will be used everywhere in a future). I would prefer extending this constant by a hook in the constructor like you did with _loadAllType but by doing memory access only and avoid database access.
Making database access in a object instantiation just hurt me. We should never have database nor external call into a constructor.
Can you try to see if it is possible to extend arrays with a simple hook that return a ->resArray into the _loadAllType()

**Comment by lvessiller-opendsi** [comment]
@eldy 
I undesrstand your request.
I replaced this old PR by a new one : PR 13388.
I used "hook" instead of "databse" to add a new category type.

**Pull request closed without merging**
