### PR TITLE
NEW Experiment supplier packaging with option PRODUCT_USE_SUPPLIER_PACKAGING: Using price according to the minimum quantity

### PR DESCRIPTION
**Pull request by atm-greg**
# New Packaging on supplier prices
give the ability to calculate the quantity of the supplier order line (added of updated) according to the packaging value defined on the supplier price used.

Ex: you have to buy 7 pens but your supplier sells it by 10.
the system recalculate line_qty to match with packaging of 10. 11 => 20. 26 => 30 ....

It's a rebuild of an old PR for this feature.

### CODE REVIEW

**Comment by eldy** [comment]
@atm-greg Can you help me to solve conflict so we can merge the features provided by option PRODUCT_USE_SUPPLIER_PACKAGING ?

**Comment by atm-greg** [comment]
@eldy conflicts resolved

**Comment by cfoellmann** [comment]
there are fields missing in the table so this errors out on `product/fournisseurs.php?id=xx`,

`Unknown column 'pfp.packaging' in 'field list'`

The sql update is missing!?

**Comment by cfoellmann** [comment]
@atm-greg there is still nothing adding the column `packaging` to the DB table!

**Comment by cfoellmann** [comment]
I just realized that there is an option in the settings for the module BUT...

it does not run the SQL command for me.
it does not add the constant.

Also missing is the field to set the packaging "size/number" for the supplier price. The input is not added to the form.

**Pull request merged**
