### PR TITLE
NEW: Change PDF Creator Name

### PR DESCRIPTION
**Pull request by aljawaid**
- Changes the PDF creator name (in the pdf file properties) from "Dolibarr 7.0.4" to whatever the name is set as e.g. "MyCompany 7.0.4")
- This maintains a professional business approach when sharing dolibarr-generated pdf documents to external parties
- Applies to all core pdf document models

### CODE REVIEW

**Comment by atm-maxime** [comment]
I think you mixed up your branches. All of your changes are in the same pull request instead of being separated

**Comment by aljawaid** [comment]
@atm-maxime Thanks for that, I think it's just the way it's displayed/grouped by github.  I've checked each pull request and they show as from different branches and they were definitely from separate pull requests.

Should I close each request and try again?

**Comment by atm-maxime** [comment]
When you do a modification, be sure to create your branch from the Dolibarr branch. E.g. if you have 3 fix to do on branch 8.0, you create 3 branches from 8.0. Here it seems that after commiting and submitting your PR, you created a new branch from your previous one. So every new branch contains everything you modified before...

**Comment by aljawaid** [comment]
@atm-maxime oh thanks for that, so should i close them all and do them again the way you suggested?

**Comment by atm-maxime** [comment]
You can let them open, just rework each one of your branches to only have specific commits concerned

**Comment by eldy** [comment]
It seems this PR contains other PR. Can you resubmit it with only the change on PDF Creator Name ?

**Comment by aljawaid** [comment]
@eldy cool, I will re-create my repo and resubmit these PRs.  I think my problem was that I was submitting PR to my own repo as well as this one and seem to have got messed up in the branches.  I will do them again.  Will close this.

**Pull request closed without merging**
