### PR TITLE
Task [ task #752 ] Allow model from external models Branch 3.2

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by FHenry** [comment]
Pull request send into for Dolibarr 3.2; I'm not sure it's a bug, so....
https://doliforge.org/tracker/?func=detail&aid=752&group_id=144

**Comment by FHenry** [comment]
It's already corrected in 3.3

**Comment by eldy** [comment]
I think this change should not be into 3.2 branch (that is a frozen branch). To know if it's a bug or not, we should answer the question: "Does all visible features, used by user, make something crazy" ?
If no, we should not include it into maintenance branch (but you can into backported branch, see later).

So, if feature does not exists into dev branch, push it into dev instead.

If you really need this feature into an old maintenance branch, push it into x.x_backported (3.2_backported of 3.3_backported) instead of branch x.x. It is the branch of version x.x that can includes features change that are not "maintenance changes". But note that backported version will not be released officially (because only version with a very large beta phase and time are released officially).

**Comment by FHenry** [comment]
Ok. I will pull it into backported branch. Thats ok for me.

**Comment by FHenry** [comment]
I ask the pull request into 3.2_backported bracnh So I close this one.

**Pull request closed without merging**
