### PR TITLE
[Qual] Replaced deprecated dol_clone calls

### PR DESCRIPTION
**Pull request by rdoursenaud**
With proper clone() calls.

### CODE REVIEW

**Comment by eldy** [comment]
Can you submit PR on dev branch ?

**Comment by rdoursenaud** [comment]
@eldy Why ? 3.8 is affected and still supported. It will be merged into 3.9 and develop anyway…

**Comment by eldy** [comment]
3.8 is a stable version, we have no reason to include such change in 3.8: 
This change does not solve any bugs, even on new php version, so why adding this in 3.8 ?
Can you point me the bug and the way and prerequisites to reproduce it ?

**Comment by rdoursenaud** [comment]
OK, didn't know that we weren't supposed to solve code quality issues in supported code.
One more thing that won't make my life as a developer easier with Dolibar :(
PR incoming !

**Comment by rdoursenaud** [comment]
Nevermind, my code was shit anyway (clone is a language construct, not a function…) and I already fixed that issue in develop.
My apologies and thanks for preventing this fuckup.
Small PR incoming though since there's still a very small occurrence ;)

**Pull request closed without merging**
