### PR TITLE
[ task #793 ] Add extrafield feature into Orders module

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by eldy** [comment]
Can you solve conflict ?

**Comment by FHenry** [comment]
Done

**Comment by eldy** [comment]
Oops, sorry still another conflict (probably another push request done after you solve first one).

**Comment by FHenry** [comment]
Should be ok now. Could you try again ?

**Comment by eldy** [comment]
I'm afraid no.
It seems that juanjo and you are working on same files. His push has unvalidate yours. But it should be last time, because now your push is at the top of stack. So one merge again and it should be ok. Reallly sorry.

**Comment by FHenry** [comment]
Ok done also. Not a problem for me to merge to avoid conflict.

**Pull request merged**
