### PR TITLE
3.5

### PR DESCRIPTION
**Pull request by grandoc**

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Don't be dumb. The path should be moved out of translations !

**Comment by grandoc** [comment]
Le 28/11/2013 14:30, Raphaël Doursenaud a écrit :

> Don't be dumb. The path should be moved out of translations !
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Dolibarr/dolibarr/pull/1326#issuecomment-29463561.
> 
> It's already in it, and it gives a wrong example

## 

Philippe GRAND
ATOO.NET
265 rue de la vallée
45160. Olivet
0238639020

**Comment by rdoursenaud** [comment]
Eek, I said _out_ : it should _not be in_ the translation string.
This generates unnecessary translators overhead.

I suggest we move the path into a constant and concatenate it to the translation call in the PHP code. This will allow the update to be made in one single place.

**Comment by eldy** [comment]
Value provided in old example was good one. Don't know where you found new one.
Can you push onyl the fix "fix management of all errors messages"

**Pull request merged**
