### PR TITLE
Update fichinter.class.php

### PR DESCRIPTION
**Pull request by defrance**
add order in fetch_line for display the line in the same order on screen and in the pdf

### CODE REVIEW

**Comment by BebZ** [comment]
Hello Defrance, do you think it could be possible to do the same but with customer's order's line from the order screen and the "reception vers stock screen" ?

**Comment by defrance** [comment]
probably have you the url of the file?

**Comment by BebZ** [comment]
Maybe
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/expedition/class/expedition.class.php
Or
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/expedition/class/expeditionbatch.class.php

**Comment by defrance** [comment]
ok, you use, the expeditiondet table who have a 'rang' fields so it's possible
but the "order by " is not enough, we need to fill the rang fields who is actually empty

**Comment by defrance** [comment]
finaly it's more simple as i thinked : https://github.com/Dolibarr/dolibarr/pull/1785

**Comment by eldy** [comment]
Replaced by #1785

**Comment by rdoursenaud** [comment]
@eldy I don't think #1785 is the same fix.
It does not apply to the same file ;)

**Pull request closed without merging**
