### PR TITLE
NEW : Feature extrafields hidden

### PR DESCRIPTION
**Pull request by aconits**
Allow to hide some extrafields

### CODE REVIEW

**Comment by simnandez** [comment]
What reason could there be to have a hidden extrafield?

**Comment by FHenry** [comment]
Sometimes you need an extrafield to store data like denormalized key or treatment data that you don't need to display. I wasn't aware about Atm work on it that but I meet this feature need. For example on one of my project some, orders in dolibarr are created by custom API with JSON order special structure. I use a orders extrafield to store the original JSON. The fact is this json is displayed on order card. User don't need to see this technical information, but I need to keep it in db and acces to this attribute without create another table/class to store it. in my opinion, it's module developer's need, and for end users useless. But to work correctly, if this option is available, I'll be happy.

**Comment by eldy** [comment]
PS, it would be great if you can edit the page
http://wiki.dolibarr.org/index.php/Table_llx_extra_fields
to have a doc that explain new fields. (note: doc for this table is not upt to date)

**Comment by aconits** [comment]
This feature can be useful for us as developer, and not for end user. With other modules we will can use extrafields hidden to save some data on a trigger.
But take care about the function "showOptionals" because if we use an extrafield with required option this one will be not required yet. And "showOptionals" isn't use everywhere as customer order extrafields but used on line order.

**Comment by rdoursenaud** [comment]
:+1:

**Comment by eldy** [comment]
The change to add the new field must be added into the file 
3.8.0-3.9.0.sql not 3.7.0-3.8.0.

**Comment by eldy** [comment]
I need to have conflict for this PR solved to have it merged and also the datastructure changed moved into file 3.8.0-3.9.0.sql instead of 3.7.0-3.8.0.sql...

**Pull request closed without merging**
