### PR TITLE
Fix: Use special_code=4 for Takepos

### PR DESCRIPTION
**Pull request by prietojc**
The special_code = 3 is used for other cases. See https://github.com/Dolibarr/dolibarr/pull/8128#discussion_r165817513

Using 3, the lines show a weird behavior that I don't understand what means:
imagen

- Quantity is blank and Import shows _"Option"_

### CODE REVIEW

**Comment by hregis** [comment]
@prietojc @eldy

if you change an ID for a field you must also modify the existing records in the mysql migration file (9.0.0-10.0.0.sql)

**Comment by prietojc** [comment]
@hregis  I think is not necessary. The special_code in Takepos is used briefly to tag lines which are ordered, after invoice is validated it is not used. 

Other solution could be clear special_code after validation. But special_code==3 is in core and I think is good idea avoid this number.

By the way, what does mean "option line" in [Wiki](https://wiki.dolibarr.org/index.php/Table_llx_facturedet)?

**Comment by prietojc** [comment]
Ooh! sorry @hregis , you are right, we need update old records (special_code is used briefly, but remain in database).

**Comment by eldy** [comment]
What is the goal of having special code set to 3 or 4 ?

**Comment by prietojc** [comment]
@eldy  If we use Takepos in a restaurant, we need to tag invoice lines with menus or food, that are sent to prepare in kitchen. The use of special_code is short, doesn't matter if is 3, 4 or whatever, but if we leave 3 the lines with menus not show quantity neither total price.

As I said, other solution could be clear special_code after validation of invoice. By now, I don't know if that data will be useful in future.  What do you think?

**Comment by eldy** [comment]
What would be good is to replace the value '4' with a constant
$line::STATUS_LINE_POS_SENT_FOR_COOKING = 4;

**Pull request merged**
