### PR TITLE
Add 13.0 total margin in facture/list.php

### PR DESCRIPTION
**Pull request by 1ocate**
Add version 13.0 total margin in facture/list.php from develop.

This is Already done request "#15821" by @lvessiller-opendsi.

My pr is only for version 13.0 coz still support this version.  

Screen Shot 2021-12-14 at 5 23 01 PM

### CODE REVIEW

**Comment by lvessiller-opendsi** [comment]
@dpriskorn 
It has been done in this request "https://github.com/Dolibarr/dolibarr/pull/15821"

**Comment by 1ocate** [comment]
@lvessiller-opendsi Hi, thank you for review. but I dont know why version 13.0 not apply
I know this already have develop (newer version)

**Comment by lvessiller-opendsi** [comment]
@1ocate 
I was a NEW but not a FIX, maybe it's in 14.0 version

**Comment by 1ocate** [comment]
@lvessiller-opendsi 
Thank you for reply.

Actually I'm remain using 13.0 and I was found 14.0 have (thank you for working this.)
And I just want into version 13.0 .. maybe this wrong..?

And sorry I didn't mention about you, I just know you fisrt add this..

**Pull request closed without merging**
