### PR TITLE
FIX: product price in future

### PR DESCRIPTION
**Pull request by Tim-Otte**

### CODE REVIEW

**Review by fappels — COMMENTED** [review]
date_price iso product_price ??
Can you explain? Is it for already set future price but not charge price yet?

**Comment by Tim-Otte** [comment]
This pull request enables the user to add product prices that are in the future. Currently Dolibarr uses the newest product price without checking if it is in the future. With this change the product prices are valid if the date of the product price is lower or equal the current date.

**Comment by fappels** [comment]
Thanks for clarification. 
I think your PR is not complete for this, sell price query is also in html.form.class, product/ajax, ....
Also no date field when setting price, etc .....

**Comment by Tim-Otte** [comment]
Okay. I currently have no capacaties to fix this whole feature so I'll close this PR for now.

**Pull request closed without merging**
