### PR TITLE
HRM : Work in progress

### PR DESCRIPTION
**Pull request by aspangaro**
(public accountant for exemple)

### CODE REVIEW

**Comment by aspangaro** [comment]
@eldy It is going to be very complex to set up. 
I wanted to make two different pages user and employee.

**Comment by eldy** [comment]
I think the opposite. For me it's easier.
Just call user_prepare_head instead of employee_prepare_head
And move all entries into employee_prepare_head into user_prepare_head
Employee information will be on different tabs so it is not a problem for me. An employee is just a particular case of user.
Odoo did 2 differents card for user and employee and it's just a headach for developer and user, so i would prefer we don't make the same error. Tabs on user are dedicated to present information dedicated to different modules.

**Comment by aspangaro** [comment]
@eldy Ok, I continue to work in this direction. I remove the bad code

**Comment by aspangaro** [comment]
Ping @eldy ;)

**Pull request merged**
