### PR TITLE
Print instead of echo

### PR DESCRIPTION
**Pull request by aspangaro**

### CODE REVIEW

**Comment by rdoursenaud** [comment]
I view this as a regression.

French reading for those interrested: http://www.zpmag.com/articles/echo.html

**Comment by aspangaro** [comment]
I agree with you. I know (The link is very interessant) that echo is more faster than print but it's for the coherence of the code. Why do not to replace all the print in this case ?

**Comment by eldy** [comment]
echo versus print is just a troll, not a regression.
Difference of performance is completely a non sense when difference is on
microsecond and when your sql request takes several thousands of
milliseconds.
In fact, the time take by all prints into dolibarr is lower than 0.0000010
seconds whatever is the page (result taken from xdebug profiler), so just
ignore such articles written by "Neuneu qui se la pete".

2014-05-12 20:15 GMT+02:00 aspangaro notifications@github.com:

> I agree with you. I know (The link is very interessant) that echo is more
> faster than print but it's for the coherence of the code. Why do not to
> replace all the print in this case ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Dolibarr/dolibarr/pull/1588#issuecomment-42867765
> .

## 

## Laurent Destailleur (alias Eldy)

Social networks of my OpenSource projects:
Dolibarr Google+: https://plus.google.com/+DolibarrOrg/
Dolibarr Facebook: https://www.facebook.com/dolibarr
Dolibarr Twitter: http://www.twitter.com/dolibarr
AWStats Google+: https://plus.google.com/+AWStatsOrgPoject/
AWStats Facebook: https://www.facebook.com/awstats.org
AWStats Twitter: http://www.twitter.com/awstats_project

**Comment by aspangaro** [comment]
I like the answer :+1:  :D

**Comment by rdoursenaud** [comment]
Of course this is sort of a troll.
I just find it sane to discuss this openly, even if _you_ may have rehashed this already.
Note that I didn't bring the performance issue to the debate. I also think it makes really no difference in the context of Dolibarr but I found this article informative and provocative enough to get a reaction ;).

What's really interresting is that it's not the same thing and does not have the same features.
The fact that print _acts_ like a function and returns something we never use always bother me.

I believe echo is best suited for most of our string outputing needs.
It helps having free concatenation and reducing the number of calls. It also helps streamlining long concatenations to keep readability at it's best by splitting these over multiple lines.
print is also great when using automatic variable replacement but we don't use that, we concatenate everywhere.
I don't support the idea that we should drop one over the other, just use the best one for the task at hand. For most of _our_ needs, it's echo, not print. Thus, there is no reason to replace any echo by print in our codebase. Nor is there to replace any print by echo. We could use them better when producing new code though…

I find this:

``` php
echo '<p>',
    '<a href="', $mylink, '">',
    $mytext,
    '<a>'
    '</p>';
```

Way more readable / understandable / maintainable than:

``` php
print "<p>";
print "<a href=\"".$mylink."\">";
print $mytext;
print "</a>";
print "</p>";
```

And this is the best case scenario. There are a lot of places where the Dolibarr source code is way uglier.

And don't get me started on the single quotes/double quotes subject.

Ok, I'll stop here, we are not trolldi.

**Pull request merged**
