### PR TITLE
Fix Rest API route for NGINX

### LINKED ISSUE #10571: Rest API explorer results in an error
Hi,

Rest API Explorer shows the error in xml that the stylesheet is missing

I initially installed Dolibarr 8.0.4 and then upgraded to Dolibarr 9.0.0 removed all the depreciated files as shown in this issue [https://github.com/Dolibarr/dolibarr/issues/7623](url)

This did not resolve the issue.

So I uninstalled Dolibarr completely and did a complete fresh install assuming that there would be some issues since I did the upgrade.

This did not work either I still get an error. Given below is the error

**For the first link [Url to get token to use API] on the Rest API page I get the error**

This XML file does not appear to have any style information associated with it. The document tree is shown below.

**For the Rest API explorer page I get the error**

{"messages":["attribute paths is not of type `object`"],"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"type","message":"instance type (array) does not match any allowed primitive type (allowed: [\"object\"])","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/paths"},"instance":{"pointer":"/paths"}}]}

### PR DESCRIPTION
**Pull request by eoxia-jimmy**
# FIX #10571 

Fix: https://www.dolibarr.fr/forum/api/65100-probleme-api

Before I start, I know that some scripts can be fix the problem but does not fully solved it.

Rest API route is not working with nginx default configuration.

The problem appears from the regex make on $_SERVER['PHP_SELF'], because the initial value of PHP_SELF is different between apache and nginx.

Example with Apache

$_SERVER["PHP_SELF"]: /dolibarr/api/index.php/explorer/

preg_match('/index\.php\/([^\/]+)(.*)$/', $_SERVER["PHP_SELF"], $reg);

reg result:
Array
(
    [0] => index.php/explorer/
    [1] => explorer
    [2] => /
)

Example with Nginx

$_SERVER["PHP_SELF"]: /api/index.php

preg_match('/index\.php\/([^\/]+)(.*)$/', $_SERVER["PHP_SELF"], $reg);

reg result:
Array
(
)

However to fix the problem, the superglobal $_SERVER["SCRIPT_URI"] of nginx contains the same value as the $_SERVER["PHP_SELF"] of apache, including the value $_SERVER["SCRIPT_URI"] is equal NULL with apache.

To conclude, here is the line added in this PR:

$url = $_SERVER["SCRIPT_URI"] !== null ? $_SERVER["SCRIPT_URI"] : $_SERVER['PHP_SELF'];

This allows you to get the same value for apache or nginx.

### CODE REVIEW

**Comment by eldy** [comment]
It means $_SERVER["PHP_SELF"] and $_SERVER["SCRIPT_URI"] does not return the same value with nginx ? This is strange and surely means there is a problem in setup of nginx.
$_SERVER["SCRIPT_URI"] can be empty but if defined, it should be same than $_SERVER["PHP_SELF"]
What do you have in $_SERVER["REQUEST_URI"] ?

**Comment by eoxia-jimmy** [comment]
Apache PHP_SELF vs REQUEST_URI

GET on /api/index.php/explorer

string(41) "PHP_SELF:/dolibarr/api/index.php/explorer"
Array
(
    [0] => index.php/explorer
    [1] => explorer
    [2] => 
)

string(45) "REQUEST_URI: /dolibarr/api/index.php/explorer"
Array
(
    [0] => index.php/explorer
    [1] => explorer
    [2] => 
)


Nginx PHP_SELF vs REQUEST_URI

string(23) "PHP_SELF:/api/index.php"
Array
(
)
string(36) "REQUEST_URI: /api/index.php/explorer"
Array
(
    [0] => index.php/explorer
    [1] => explorer
    [2] => 
)



GET on /api/index.php/products?sortfield=t.ref&sortorder=ASC&limit=100

Apache PHP_SELF vs REQUEST_URI

string(41) "PHP_SELF:/dolibarr/api/index.php/products"
<pre>Array
(
    [0] => index.php/products
    [1] => products
    [2] => 
)
</pre>string(85) "REQUEST_URI: /dolibarr/api/index.php/products?sortfield=t.ref&sortorder=ASC&limit=100"
<pre>Array
(
    [0] => index.php/products?sortfield=t.ref&sortorder=ASC&limit=100
    [1] => products?sortfield=t.ref&sortorder=ASC&limit=100
    [2] => 
)
</pre>

Nginx PHP_SELF vs REQUEST_URI

string(23) "PHP_SELF:/api/index.php"
<pre>Array
(
)
</pre>string(76) "REQUEST_URI: /api/index.php/products?sortfield=t.ref&sortorder=ASC&limit=100"
<pre>Array
(
    [0] => index.php/products?sortfield=t.ref&sortorder=ASC&limit=100
    [1] => products?sortfield=t.ref&sortorder=ASC&limit=100
    [2] => 
)
</pre>

**Comment by eoxia-jimmy** [comment]
Hi,

i reopen this PR, my fix doesn't work for some people.

I found new fix for this issue.

REQUEST_URI value is created by the mod_rewrite: https://httpd.apache.org/docs/current/fr/mod/mod_rewrite.html

Sometimes (and I don't know why) the entry REQUEST_URI in $_SERVER isn't declared, i can compare that with two domains, one is primary and another is sub domain like that:

https://domain.com => $_SERVER['REQUEST_URI'] exists with the good value
https://subdomain.domain.com $_SERVER['REQUEST_URI'] doesn't exist.

In my last PR, I use PHP_SELF, in my server, it contains the same value of REQUEST_URI but not for all people.

For now, i'm trying to use this one at line 42 of index.php file in "api" folder and it's working for me.

Change
`$url = $_SERVER["SCRIPT_URI"] !== null ? $_SERVER["SCRIPT_URI"] : $_SERVER['PHP_SELF'];`

to

`$url = $_SERVER["SCRIPT_URI"] !== null ? $_SERVER["SCRIPT_URI"] : $_SERVER['HTTP_HOST'] . preg_replace( '/(\?.+)/', '', $_SERVER['REQUEST_URI'] );`

Tell me if it's worked.

**Comment by MooDaCow** [comment]
For an obscure reason that eoxia-jimmy has analyzed and understood (related to the management of subdomains by NGINX and its display in the PHP variable, nope ?), my API page remains empty without this patch.

I had to get rid of the "if" condition to get it work properly :
```
/*$url = $_SERVER['PHP_SELF'];
// Fix for some NGINX setups (this should not be required even with NGINX, however setup of NGINX are often mysterious and this may help is such cases)
if (! empty($conf->global->MAIN_NGINX_FIX))
{
	$url = (isset($_SERVER['SCRIPT_URI']) && $_SERVER["SCRIPT_URI"] !== null) ? $_SERVER["SCRIPT_URI"] : $_SERVER['PHP_SELF'];
}*/

$url = $_SERVER["SCRIPT_URI"] !== null ? $_SERVER["SCRIPT_URI"] : $_SERVER['HTTP_HOST'] . preg_replace( '/(\?.+)/', '', $_SERVER['REQUEST_URI'] );
```

I hope that his fix will be published soon, to avoid manual edition of php file at each update.

Many thanks to eoxia-jimmy and everyone involved in solving this bug.

**Comment by eoxia-jimmy** [comment]
Hi, maybe we should do an another PR for make it merged in the develop branch ?

@eldy

**Comment by eldy** [comment]
After check on the v14, it seems code
```
if (!empty($conf->global->MAIN_NGINX_FIX)) {
	$url = (isset($_SERVER['SCRIPT_URI']) && $_SERVER["SCRIPT_URI"] !== null) ? $_SERVER["SCRIPT_URI"] : $_SERVER['PHP_SELF'];
}

is no more commented. So my understanding is that adding the MAIN_NGINX_FIX option to 1 fix the problem with nginx, right ?
```

**Comment by Productivix** [comment]
Bonjour Eldy, 
j'ai une v 14.0.2 en Dolibarr sous NGINX  - j'ai bien ce dernier code dans l'index.php de api, mais la page /api/index.php/explorer/# sort seulement 
3 lignes : 
Dolibarr REST API Explorer
un champ de formulaire
Explore

et avec la clé API , rien ne se passe de plus.
Par contre quelle est la config de votre site sous NGINX (V1.14.2) SVP? (j'ai gardé la config de la V10 qui fonctionnait et là plus rien ne fonctionne.
Merci

**Pull request merged**
