### PR TITLE
NEW: add duration extrafield

### PR DESCRIPTION
**Pull request by benoitpascal**
# NEW|New Add duration extrafield

Add a extrafield with type duration that react has task duration type.

### CODE REVIEW

**Comment by frederic34** [comment]
you need to add new features only in develop branch

**Comment by benoitpascal** [comment]
> you need to add new features only in develop branch

Sorry, I will fix my commit then :wink:

**Comment by eldy** [comment]
> > you need to add new features only in develop branch
> 
> Sorry, I will fix my commit then :wink: 

I recommand you install git precommit hook. See https://wiki.dolibarr.org/index.php?title=Environment_and_development_tools

So your code syntax will be automatically fixed and this will avoid ct/ci errors.

If not possible, think to setup your ide to use tabs instead of space for tabs.

**Comment by benoitpascal** [comment]
The other PR is the cleaned one. 

I close this PR to avoid merging the wrong one.

**Pull request closed without merging**
