### PR TITLE
NEW : add titles for wysiwig editor in eldy theme

### PR DESCRIPTION
**Pull request by samifilali**
# FIX
- add titles for wysiwig editor in eldy theme

### CODE REVIEW

**Comment by eldy** [comment]
Looks more as a not yet provided feature than a bug. 
As this add a new feature for end user, this must be pushed into develop. Also this option may generates troubles with rest of features (like pdf generator, or function to calculate size of note content), so i recommand to add this only if a hidden constant if set.

**Comment by samifilali** [comment]
I can do it if necessary but this functionality was present until version 12 of dolibarr which is why I considered it as a fix

**Comment by eldy** [comment]
Yes. It was removed because this options generates a lot of problem with no solution to fix them (like pdf generation that has bad pagination, function to calculate size of note content that is wrong). Using it inside notes and description of lines must be avoid. This is why i recommand to add this only if a hidden constant if set.

**Comment by samifilali** [comment]
how can I do this? It's in a js file, there is no js context?

**Comment by eldy** [comment]
> how can I do this? It's in a js file, there is no js context?

Right. Did not found solution to set ckeditor menu toolbar on the fly so it was reintroduced into v21.

**Pull request closed without merging**
