### PR TITLE
Update llx_c_shipment_mode.sql

### PR DESCRIPTION
**Pull request by frederic34**
Update GLS and Colissimo tracking url

### CODE REVIEW

**Comment by BebZ** [comment]
Hello Frederic, 
Are you working on making an admin to tack and update status of boxes sent via carriers ?
I just ask, maybe it's something possible in Dolibarr...
My carrier is Exapaq (and it's really cheap)... do you want code to input tracking ?

**Comment by frederic34** [comment]
Hello BebZ
I'm just doing update of french examples. I'm working on something in relation with carriers but it's not ready (like selectbank but for shipment method)

**Comment by atm-maxime** [comment]
If I may, I think carriers should be considered as suppliers. Having an option "carrier" yes/no on the supplier card will allow to define the carrier list to display.

**Comment by BebZ** [comment]
Oh, for such good ideas, you may ! off course Maxime :)
if the Third "carrier" is considered as a "supplier" as well 
- if we select it on the propal (as Frederic did today), order and invoice (soon maybe)... 
  We should be able to request it via phpmyadmin 
  and get a list of sub-contracted services to carriers, 
  and then control this list with the detailled invoice of the supplier...
  ... then finally get exact cost of transports...
  ... or we must keep transport costs in the shipments module ?

**Comment by atm-maxime** [comment]
My guess is that we must keep transportation costs as a service line in the documents.

Allowing to define the carrier on proposal, order and invoice seems to be a good thing to me. But should we keep it as a simple combo box on the document ? If we go on the solution to have carriers as suppliers card, I think we should use the "contact/address" tab to define the carrier. It's a contact with the specific role "Carrier". And this role can easily be added to the list of roles on proposal, order, ...

What do you think @frederic34, @eldy ?

**Comment by eldy** [comment]
My think. We must keep difference between "shipment mode" and "supplier" providing transport.
shipment mode is a way to ship (it may be UPS or FedEx but also "by email" or "take it yourself").
So we must keep dictionnary of shipment mode. What we can do is adding a field into thirdparty (for supplier that are "transporteur" to link/store the shipment mode they provide).

**Pull request merged**
