### PR TITLE
Add detailed menus in HRM module

### PR DESCRIPTION
**Pull request by atm-maxime**
In HRM module, menus for holidays and expense reports are now working like in other modules (list by status)

### CODE REVIEW

**Comment by atm-maxime** [comment]
I think I understand what travis is saying, but I don't know how to fix it.

**Comment by mudassar791** [comment]
Salary payment work shoud be also done,
As Pyament of salary cannot be recorded more than defined salary in employee profile.
Advance salary payment recording.
Overtime and othrt benifets can be recorded.

**Comment by atm-maxime** [comment]
@eldy Something wrong with this PR ?

**Comment by atm-maxime** [comment]
@eldy too bad this PR is not in 7.0, it's only a menu modification to match how other menu works...

**Comment by atm-maxime** [comment]
@eldy go go go !

**Pull request merged**
