### PR TITLE
NEW dropdown top menu

### PR DESCRIPTION
**Pull request by dreggy**
# NEW dropdown top menu
I added the dropdown menu from top menu, I find it a faster way to navigate without have to load a page and then to click another one or two buttons on the left menu to reach the desired page. I hope you find it useful otherwise I ask to implement an hook at line 480 in eldy.lib.php to allow customization.

### CODE REVIEW

**Comment by ksar-ksar** [comment]
Good!

Do you have a screen shot?

**Comment by dreggy** [comment]
Of course. 
dropdown-screenshot

the time you have to over the mouse over a main menu button to open the submenu is set to 0.2s through css but can be tuned to avoid opening submenu while moving mouse around the screen

**Comment by eldy** [comment]
What happen if you are on a smartphone ?

**Comment by dreggy** [comment]
At the moment the submens are shown using css :hover selector so they don't popup on mobile and they are hidden via CSS for screen width lower than 565px, it can be disabled also by php code (to save also data traffic) but i didn't find an already implemented way to detect mobile devices, if you can advice me I'll add it.
Also I noticed that the "Reduction 1" in stylesheet break the visibility of submenus so I just find out the css code to fix it but it changes the way menu labels are truncated. At the moment the label are truncated beacuse the container div.tmenucenter have the overflow setted to hidden, I moved this setting to the label container (a.tmenu). I tried this a bit and it seems to work the same way but I have to test it better to be sure
These are the css rules to make it work:

`  

          @media only screen and
            (max-width: ".(empty($conf->global->THEME_ELDY_WITDHOFFSET_FOR_REDUC1) ? round($nbtopmenuentries * 90, 0) + 240 : $conf->global->THEME_ELDY_WITDHOFFSET_FOR_REDUC1)."px)	
            and
            (min-width: ".(empty($conf->global->THEME_ELDY_WITDHOFFSET_FOR_REDUC2) ? round($nbtopmenuentries * 69, 0) + 40 : $conf->global->THEME_ELDY_WITDHOFFSET_FOR_REDUC2)."px)
            {
              div.tmenucenter {
                overflow: visible !important;
              }
              .submenu>.tmenucenter{
                width: auto;
              }
              a.tmenu, a.tmenusel, a.tmenudisabled {
                width: 100%;
                overflow: hidden;
                text-overflow: ellipsis;
                display: inline-block;
              }
              #tmenu_tooltip>div.tmenudiv>ul.tmenu>li.tmenu>div.tmenucenter>div.tmenudiv>ul.tmenu{
                margin-top: -5px;
              }
            }

`

**Comment by dreggy** [comment]
Ok i found $conf->browser->layout OR $conf->dol_no_mouse_hover .
I now check $conf->dol_no_mouse_hover before calling the print_submenu function

**Comment by john-botella** [comment]
Great initiative! :+1:     I put a link in "better look and feed issue"

I was asking myself, it's it more user friendly to use a mega menu interface instead ?
I explain my reasoning :
Actually the current menu user experience is composed by two show levels:
Top menu and left menu.
Using a simple drop-down menu require additional levels (your screen shot is a good exemple). This may complicate the mental path of the user to retrieve the location of a page. 
By using a "Mega menu" it's possible to keep this two show levels.

An arbitrary exemple find on internet :
image

**Comment by john-botella** [comment]
I have tested your menu, I found a bug on url for module installed in custom folder:
exemple :
htdocs/webhost/webpassword_list.php?idmenu=586&mainmenu=webhost
intead of : 
htdocs/custom/webhost/webpassword_list.php?idmenu=586&mainmenu=webhost&leftmenu=

**Comment by dreggy** [comment]
Hi and thank you for your feedback.
I did this type of menu for simplicity on reusing the existing code, in fact to create the submenues I used the existing functions in the menu manager and I added "ad-hoc" css rules.
About the "mega menu interface" I think that it is useful for website where there are many "one time" visitors and it is easier for them to find the right page they need showing all of them. I suppose that a dolibarr user know where is the page he need. Also some submenues have a lot of items, in this case the visibility of the items should be limited to only 1 or 2 subleves.

By the way I think that modifing only the css it can appear like the "mega menu". I can try it but this week I'm a little busy, I hope to make it for the next one.

**Comment by dreggy** [comment]
> By the way I think that modifing only the css it can appear like the "mega menu". I can try it but this week I'm a little busy, I hope to make it for the next one.

No, it isn't only matter of css so to make it appear like a mega menu it should be modified also the code.

**Comment by eldy** [comment]
Yes @atm-john
We need a "mega menu" popup for each top menu instead of a menu that toggle different levels one by one as seen in the screenshot. Someting similare to the menu of the website template "corporate" of dolibarr v11.

**Comment by dreggy** [comment]
I'm working on it

**Comment by dreggy** [comment]
Hi,
i attach a couple screenshots of the megamenu, realized mainly editing the css rules of the first multilevel menu that I proposed. Actually the width of the megamenu correspond to the width of all of the top menu elements, i also tested a full width version but I find it not so beatiful/usable in larger screens.
Inside the megamenu the elements are displayed center aligned.
What it looks like to you?

Firefox_Screenshot_2020-04-08T19-35-40 538Z
Firefox_Screenshot_2020-04-08T19-36-45 084Z

I tested the css rules only for screen width major than "reduction1", if you like this style I will check and fix also other resolutions.
I have to fix just a few things in the code and hope to upload it tomorrow

**Comment by john-botella** [comment]
Great job !

for the last screen-shot, you can add this rule : if there is only one sublevel so plit it 

it could be done with a little bit of css pseudo element like :only-child 

exemple : 
```
**Events**
   menu x
   menu x
       submenu x
       submenu x
       submenu x
   menu x
       submenu x
   menu x
       submenu x
       submenu x
       submenu x
   menu x
```

Like (I use table but it's for exemple ;-) ): 

**Events**

| menu x  | menu x  | menu x  | menu x  | menu x  |
| ------------- | ------------- | ------------- | ------------- | ------------- |
|     | submenu x  | submenu x | submenu x |     |
|     | submenu x  |     | submenu x  |     |
|     | submenu x  |     | submenu x  |     |

**Comment by john-botella** [comment]
PS: including a mega menu will change us navigation habit so menu organisation will probably evolve after including mega menu. Due to user experiences feedback.
in a next step, it could be useful to include hooks to allow add somme html elements on submenu like quick access or quick infos...

**Comment by dreggy** [comment]
I messed up things with github, i don't know how to use it :|

Instead I fixed some things and all is working good also with "reduction 2", I followed the advice of @atm-john and modified the look of the menu when there is only one child of "first level".
About the hooks, actually the menu use the pre-existing code to generate the submenues. For "quick access" do you mean "bookmarks"? A problem using this type of elements in the megamenu it is that if the select2 element is opened the megamenu will lose focus and the menu will close.

**Comment by dreggy** [comment]
> I messed up things with github, i don't know how to use it :|

I wanted to start with a "clean" copy,  so I deleted the fork and restarted one new, now I don't know how to post commits here :|
Should i close this pull request and start a new one? Sorry for that

**Comment by john-botella** [comment]
@dreggy you can close this pull request and start a new one. When it done put a link into the new pull request to this one. It will automatically make a link in both pull request.

@dreggy for the question you asked me about "quick access" I wanted to use your repository to make a screenshot with some manipulations (gimp) but I was not able to retrieve your branch... I know why now :-)
Let me know when the branch is finished ;-)

**Comment by dreggy** [comment]
Starting a new pull

**Pull request closed without merging**
