### PR TITLE
New Periodic product attribute

### PR DESCRIPTION
**Pull request by wdammak**
Add the option of having periodic price variants

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide an example of use case of periodic product attribute ?

**Comment by wdammak** [comment]
Ex.:
From 1st January to 15th-March => price 150€
15-March to 30-May => price 180€
1-June to 31-August => price 250€
1-Sept to 30-Nov => price 170€
1-oct to 31-Dec => price 200€

The final rendering...

image
In dolibarr... :)
image

**Comment by eldy** [comment]
In your example, it seems that what is periodic, is not the attribute (red, blue, or L, XL) but the price.
So the date should not be stored into table llx_product_attribute_value
If you add date into table llx_product_attribute_value, it means the product you sell the first month is Red or L only and the product you sell the second month is blue or XL only.
With the variant module, each combination of attributes (1st option, 2nd option, ...) is a different product. So here what you need a date on the prices definition no on product definition.
Table for price is llx_product_price. There is already a date_price that define the start date but no field date_end_price

**Comment by wdammak** [comment]
Yes maybe We must change the periodic notion by another term ...
In my proposal, the variant remains available during all periods but its price is variable according to time intervals. So to recover the price of a variant simply find the period of the current date and apply the discount or the price increase (negative or positive).
I also opted for variants because it allows me to group in the same product for easy monitoring, updating and management especially when we have hundreds of products with n options.
With n period; (here in the example is 9 but can be more or less) and n options (sub product in ex. 6 + the capital product) so I will have to create 7 products and for each product create 9 prices. If I must to change the prices will have to look for the right product and the good period with going back and forth everywhere in all directions ...

If we can do otherwise by having this table (which facilitates the task of management) I would be leaving.

**Comment by braito4** [comment]
In our company we use the function of dinamic price + a calendar prices:
screenshot 2019-02-28 at 16 40 31

so, when you introduce a range of dates, dolibar calculate the price for this range

**Comment by wdammak** [comment]
> 
> 

> With the variant module, each combination of attributes (1st option, 2nd option, ...) is a different product. So here what you need a date on the prices definition no on product definition.

@eldy 
yes it's a sub-new product that complements the main product. So it's a product dependent on the main product.

@braito4 
Thank you for your solution.
but I say why not propose a simple solution for the case of 80% of the company services!
Calendar has a specific role
The dynamic price module is very complicated for an employee without thorough knowledge.

**Comment by eldy** [comment]
@wdammak As you said the "the variant remains available during all periods", so it means the period date must not be stored into the table of variant but into the table of prices.
Each variant is a product so each variant can have its own price. For a price validity on date, the date must be introduced into the price table (note that there is already the date of begin of validity in the price table).

**Comment by wdammak** [comment]
@eldy if we wanted to use this method we have to work on having the full periodic list for purchase prices.
the subject is already discussed here: https://github.com/Dolibarr/dolibarr/issues/10782

**Comment by wdammak** [comment]
@eldy : new approch
https://github.com/Dolibarr/dolibarr/pull/10975

**Comment by eldy** [comment]
Replaced by #10975, so i close this one

**Pull request closed without merging**
