### PR TITLE
Update api_supplier_invoices.class.php

### PR DESCRIPTION
**Pull request by dpriskorn**
Unified names.
Renamed variable to an english name $paiementid => $payment_mode_id
Added hints where to look up the IDs needed.

### CODE REVIEW

**Comment by dpriskorn** [comment]
I don't understand why the review failed. It looks good to me.

**Comment by fappels** [comment]
You renamed in doc but not in code.

**Comment by fappels** [comment]
You also need to add your rename to changelog for developers so they can modify there model schema on dolibarr upgrade.

**Comment by dpriskorn** [comment]
Oh, thanks for pointing that out. What/Where is the model schema?

**Comment by fappels** [comment]
REST API Explorer 5-8-2020 15-35-00

**Comment by dpriskorn** [comment]
I don't think your statement is correct. That model is generated on the fly by phpdoc from the section I edited on every page load.

**Pull request merged**
