### PR TITLE
NEW: look and feel appli

### PR DESCRIPTION
**Pull request by john-botella**
new manifest file:
The web app manifest is a simple JSON file that tells the browser about your web application and how it should behave when 'installed' on the user's mobile device or desktop. Having a manifest is required by Chrome to show the Add to Home Screen prompt.

Mobile color :
Starting with version 39 of Chrome for Android on Lollipop, developers are now able to use the theme-color meta tag to set the toolbar color—this means no more gray toolbars!

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide a screenshot to let me understand what this is ?

**Comment by john-botella** [comment]
**First -> browser color according to top menu color**


**Click on "Ajouter à l'écran d'accueil**




**An icon is create**


**A Application like loading screen**

**Comment by john-botella** [comment]
@eldy : screen shot added

**Comment by aspangaro** [comment]
ping @eldy

it's work 👍

**Comment by john-botella** [comment]
@eldy your recommendations have been applied

**Comment by john-botella** [comment]
@eldy can U merge it please :-)
most of websites use it, it's good for customer appeal, it's like candy :-)

**Pull request merged**
