### PR TITLE
Test pgsql installation

### PR DESCRIPTION
**Pull request by atm-greg**
#add travis tests
remove the postgresql test exclusion.
add test on installation process.

### CODE REVIEW

**Comment by daamien** [comment]
Hi !

This PR is important for us. 

We need a more robust support for  PostgreSQL in dolibarr.

**Comment by eldy** [comment]
Can you push PR on develop branch ?

**Comment by eldy** [comment]
@atm-greg Can you push PR on develop branch ?

**Comment by atm-greg** [comment]
@eldy sorry for taking so much time to merge conflicts

**Pull request merged**
