### PR TITLE
NEW: Accountancy - Introduce "Level3" - Define account directly in thirdparty

### PR DESCRIPTION
**Pull request by aspangaro**
Very usefull when company use free line product and the accounting account on this thirdparty is always the same  ;)

Example : 
image

### CODE REVIEW

**Comment by eldy** [comment]
Are you ok to rename "Ce tiers" into "Produits de ce tiers" ?
If my understanding is good, we suggest here accounting code of product when product depends from this thirdparty ?
what happen if no accounting code of product is defined on thirdparty level on this screen ?

**Comment by aspangaro** [comment]
@eldy Done

Yes, we have a level more powerfull depends from the thirdparty. If level 3 is empty, go the level 2 and it's also empty, go to level 1. It is a top-down system. Begin level 3 to 1

**Comment by aspangaro** [comment]
@eldy PR fixed

**Comment by eldy** [comment]
Previously, 2 value was suggested and priority was   2 -> 1.
Now we have 3, what is priority (when some values are not defined). My understanding is that implementation you suggest is 3 -> 2 -> 1 (according to screenshot and your comment)

But I think it should be   2 -> 3 -> 1    (the accounting account of product is an accurate value so should be used in priority on the generic value of product of user, right or wrong ?). If i am right, it should be better to set 3 at position 2

**Comment by aspangaro** [comment]
No, for specific needs, in particular to identify certain expenses on the balance sheet, some accountants require certain expenses or income from a third party to be isolated in a specific account. Therefore, it is necessary that level 3 is above level 2. Level 3 is designed to be even more precise beyond its usefulness for the management of free lines.

I recommend the client to fill in at least level 2 (products/services) and if using free lines or isolation in a specific account for the identification of an expense on the balance sheet, fill in level 3 (third party).

It is already in use at several clients, it corresponds perfectly to what the firm requires, so I recommend to keep it in order of importance 3 -> 2 -> 1.

**Pull request merged**
