### PR TITLE
[DRAFT] Add sub total and title

### PR DESCRIPTION
**Pull request by BB2A-Anthony**
[EN]
I would like to add in the corp the possibility of adding titles and subtotals in the documents. Do you think the best option is to add free line types or buttons at the bottom?

[FR]
J'aimerais ajouter dans le corp la possibilité d'ajouter des titres et sous-total dans les documents. Penssez vous que la meilleur option est de rejouter des types de ligne libre ou des bouttons dans le bas?

128700072-9c276e98-453d-4936-9a17-5f3d5a9ca6ab

### CODE REVIEW

**Comment by cfoellmann** [comment]
I am currently testing https://github.com/ATM-Consulting/dolibarr_module_subtotal but we use `rank` column and the lines between the products/services also get numbers and should be excluded from the `rank`

**Comment by atm-maxime** [comment]
If you want to discuss a feature request, start by opening an issue before coding.
I'd say that a line type is a good choice but there's a lot of work to check that everywhere lines are manipulated we check for type 0 or 1 (to avoid adding a subtotal to the main total for example)

**Comment by cfoellmann** [comment]
I am with @atm-maxime 
You should open an issue an discuss what you want to achieve. Your idea is not a simple task.
Look at the atm module it is not just a few lines of code

**Comment by BB2A-Anthony** [comment]
At first it is not to go as far as the atm module

Issues #18380

**Comment by erikvanberkum** [comment]
Just my personal opinion:
add free line types

**Comment by eldy** [comment]
Also related to #18369 or #21675?

**Comment by BB2A-Anthony** [comment]
@atm-maxime can you watch this #18380 ?

**Pull request closed without merging**
