### PR TITLE
Removed duplicated translation

### PR DESCRIPTION
**Pull request by marcosgdf**
Removed duplicated translation.

BIC is a code issued by the SWIFT organization. Its naming is the same all over the world.

### CODE REVIEW

**Comment by marcosgdf** [comment]
Travis CI build fail has nothing to do with this PR

**Comment by eldy** [comment]
The value and field is the same, but common usage differs for countries.
For example in france we call it "BIC". But in india, they call it the "SWIFT" number. The problme here is that translation does not depends on user language but on bank account country. So old code looks better to me.

**Comment by marcosgdf** [comment]
But that is a translation and  not a code issue. They can translate in
transifex BIC as SWIFT. Or they can translate it as BIC/SWIFT like we do in
Spanish translation.

**Comment by eldy** [comment]
Transifex provide a translation according to user language.
What we need here is a translation according to bank account country.  For other thing in same case, we use the country into the key like  ProfIdEN, ProfIdFR. Here, because only 2 cases were identified, we used BIC and SWIFT but we should use BICIN and BICRESTOFWORLD for translation key.
Fact is that we need 2 different keys: An idian people mus see SWIFT for an indian bank account (because bank india use this and see BIC for a european bank account country, keeping the same user language en_IN).

**Comment by marcosgdf** [comment]
I insist BIC is a code issued by the SWIFT organization and this sounds
like a user language issue. I don't see the need of having two translation
keys for the exact same thing… ProfId is a different thing…

**Comment by eldy** [comment]
I know BIC is the code issued by SWIFT organization but Indian bank and not indian people just all it "SWIFT" and not "BIC".
This is not a problem of translation because translation does not depend on user language but on the country of the bank. Than'ts why we need a code BICFORBANKNOTINDIA and a code BICFORBANKININDIA
It's like tje professional ID. ProfID1 does not depends on user language but on company countrie, that's why we have several code ProfID1FR, ProfID1ES, ...

**Pull request closed without merging**
