### PR TITLE
Problem exporting Quadra files

### PR DESCRIPTION
**Pull request by ghost**
Google Translate from french :D 

Accent problem encountered when exporting the large list to Quatratus format in V11.0.0

Accents can appear in the last column of the Quadra file which is a field which can contain refs other than numeric.

So I changed accountancyexport.class.php on line 531 from:

`$Tab['num_piece3'] = substr(self::trunc($data->doc_ref, 20), -10);`

to

`$Tab['num_piece3'] = str_pad(self::trunc(dol_string_unaccent(substr(self::trunc($data->doc_ref, 20), -10)), 30), 30);`

### CODE REVIEW

**Comment by eldy** [comment]
Something is wong in your PR. It was done on develop branch but suggested for inclusion in v11.
You must develop or v11 to push in v11 or develop on develop to push on develop.

**Comment by hregis** [comment]
Can you close this PR please?

**Comment by eldy** [comment]
Something looks wrong in this PR: 520 files modified.
It seems you worked on 11.0 branch and submit in develop branch.
Can you make your change in develop branch and then push to develop OR
Make change in v11 and push in v11

**Comment by atm-maxime** [comment]
@ghost did you see @eldy comment?

**Comment by atm-maxime** [comment]
Please @ghost, close this PR

**Pull request closed without merging**
