### PR TITLE
Fix: command not found with escapeshellarg !

### PR DESCRIPTION
**Pull request by hregis**
i have this error with "escapeshellarg" 

 `KO with antivirus: result= errors=sh: 1:  /usr/bin/clamscan: not found`

it's ok with "escapeshellcmd" !

### CODE REVIEW

**Comment by eldy** [comment]
PHP team recommand to not use escapeshellcmd but escapeshellarg instead. It should works with escapeshellarg
Can you paste the command you set that fails ?

**Comment by hregis** [comment]
@eldy 
with escapeshellarg dolibarr try to run the command with single quotation marks and so inevitably there is an error! 

`'/usr/bin/clamscan' '/path/to/file'`

**Comment by eldy** [comment]
The setup is splitted in 2 fields, one for the command and one for the parameters.
So command   '/usr/bin/clamscan' '/path/to/file'   should not exists.
Can you provide a screenshot of your page  /admin/security_file.php

**Comment by hregis** [comment]
@eldy  
aaahhhh sorry ! I had not seen, I had a space at the beginning of "/usr/bin/clamscan", it would be necessary to add a "trim" when recording the path. I send the correction right away

**Comment by hregis** [comment]
@eldy 
ready

**Pull request merged**
