### PR TITLE
Add field "skype" in soc and socpeople with link callto

### PR DESCRIPTION
**Pull request by aspangaro**
Need Skype to work

### CODE REVIEW

**Comment by hregis** [comment]
should not we put some fields as an option, because it is too specific to certain applications? (skype, IM, etc ...)

**Comment by eldy** [comment]
We may have a lot of field like that (skype, google talk, irc, ....)

To store data:
I suggest to use the already existing field "jabberid" (we can rename it 
to "IM") and put here all list of IM ids like this
jabber:idjabber, skype:idskype, ...

To edit and view data:
When showing the value, we can show several lines for each entry.
However, for input, we will need a more complex system, with a button to 
add en entry and a free text zone to input id. We also need a "remove" 
picto to remove an entry.

Le 14/09/2012 07:13, Regis Houssin a écrit :

> should not we put some fields as an option, because it is too specific 
> to certain applications? (skype, IM, etc ...)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Dolibarr/dolibarr/pull/397#issuecomment-8551976.

## 

Eldy (Laurent Destailleur).

EMail: eldy@destailleur.fr
Web: http://www.destailleur.fr

Dolibarr (Project leader): http://www.dolibarr.org
To make a donation for Dolibarr project via Paypal: contact@destailleur.fr
AWStats (Author) : http://awstats.sourceforge.net
To make a donation for AWStats project via Paypal: contact@destailleur.fr
AWBot (Author) : http://awbot.sourceforge.net
CVSChangeLogBuilder (Author) : http://cvschangelogb.sourceforge.net

**Comment by simnandez** [comment]
We can also add Complementary attributes for contacts like in Third parties, can serve for IM or for example for an optical to indicate the eye color...

**Comment by aspangaro** [comment]
Ok !

I add some improvements and I commit later

**Pull request closed without merging**
