### PR TITLE
FIX: PHPDoc wrong return value

### PR DESCRIPTION
**Pull request by altairis-noe**
# FIX: PHPDoc wrong return value
Sorry, my IDE kept underlining in red if I tried to `foreach` the result 😂

### CODE REVIEW

**Comment by mdeweerd** [comment]
That's nice, but `Categorie[]`is better ;-).  It helps static analysis.

**Comment by altairis-noe** [comment]
I beg to differ, @mdeweerd : the result is an array of category *ids*, so an int[]
I corrected the `@return` description accordingly.

**Comment by eldy** [comment]
The doc in $c->containing says it return Categorie[]|int so doc in "containing" is wrong ?

**Comment by altairis-noe** [comment]
@eldy : the Categorie::containing() has 'id' as third argument, which means we’ll get an array of Categorie ids, not full Categorie objects (see line 1573 of the same file)

**Comment by eldy** [comment]
> @eldy : the Categorie::containing() has 'id' as third argument, which means we’ll get an array of Categorie ids, not full Categorie objects (see line 1573 of the same file)

So doc was not complete. result can be both Categorie[] and int[] (it depends on mode). I pushed a fix for this.

**Comment by altairis-noe** [comment]
> The doc in $c->containing says it return Categorie[]|int so doc in "containing" is wrong ?

I think it is indeed incomplete, I’ll correct!

**Comment by mdeweerd** [comment]
Yes, this happens during the process of typing php items, and in the end the documentation and checks improve and future development is faster with less errors.

**Comment by mdeweerd** [comment]
Looking at the code, it can also be a list of strings.

**Comment by altairis-noe** [comment]
> > @eldy : the Categorie::containing() has 'id' as third argument, which means we’ll get an array of Categorie ids, not full Categorie objects (see line 1573 of the same file)
> 
> So doc was not complete. result can be both Categorie[] and int[] (it depends on mode). I pushed a fix for this.

I added string[] in case mode is label ;)

**Pull request merged**
