### PR TITLE
Update translate.class.php

### PR DESCRIPTION
**Pull request by defrance**
problem with translation of select list

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Well, you could at least syslog a warning. Best of both worlds ;)

**Comment by defrance** [comment]
UP!

**Comment by hregis** [comment]
use
if (isset($key) && $key == '')
instead
if (! $key)

**Comment by defrance** [comment]
thank's regis, changes made

**Comment by defrance** [comment]
UP

**Comment by defrance** [comment]
Error is present on standard dolibarr need a fix urgently !

error on last dolibarr standard

**Comment by marcosgdf** [comment]
I agree with returning an empty value. If anything entered cannot be translated, return the given string to not break the view. A different thing would be giving it something different than string

**Comment by FHenry** [comment]
I agree with charles, trans '' should not return ErrorBadValueForParamNotString but ''.

**Comment by defrance** [comment]
hope fix for Xmas ;-)

**Comment by defrance** [comment]
Hello
Sorry but i Still waiting for this correction
version 3.7 should soon go out and still have to wait six months to address this issue is not acceptable

**Comment by eldy** [comment]
Calling this function with a '' means there is a bug BEFORE the call. The string ErrorBadValueForParamNotString is required to report there is a bug to fix.
I seriously can't accept a PR to "hide" a bug, even if bug is inside dolibarr core code. I prefer accept the PR that will fix the bug.

**Pull request closed without merging**
