### PR TITLE
NEW zapier for dolibarr

### PR DESCRIPTION
**Pull request by frederic34**
:construction_worker_man:  IT A WORK IN PROGRESS DO NOT MERGE BEFORE V11

- [ ] js client
- [ ] dolibarr code

### CODE REVIEW

**Comment by cfoellmann** [comment]
have a look at https://github.com/marketplace/wip to integrate the [WIP] feature (like on GitLab) ;-)

**Comment by eldy** [comment]
@frederic34 Is it ok for merge ?

**Comment by frederic34** [comment]
no i'm on holidays...

**Comment by eldy** [comment]
@frederic34 Can you make a README into dev/zappier to explain quickly how to use the module zapier. For example:
1-Create a zapier account
2-Enable module
3-...

**Pull request merged**
