### PR TITLE
Work on accounting cost

### PR DESCRIPTION
**Pull request by aspangaro**
First piece

image

### CODE REVIEW

**Comment by aspangaro** [comment]
MAIN_FEATURES_LEVEL : 2

**Comment by eldy** [comment]
Before starting any dev, can you describe how this will work ?

**Comment by aspangaro** [comment]
@eldy 

How to work ? It's simple. You have axes and repartition keys like categories & sub categories.

In accountancy, you have an expense for IT department & marketing department with a 40%/60% repartition. If you have 100 €, you need to have two balance. One for the IT department & another for marketing department. It's like element page in project module but you have a repartition by amount.

For the moment, I would like to work only on accountancy module & before, we integrate the notion of repartition key in others modules by line in invoice module for example.

**Comment by aspangaro** [comment]
Precision : 
Sum of the key repartition must be 100%. 
You must have many keys by axes.
Keys can be assign to accounting account to have default repartition on balance

I think we need 2 or 3 tables, I work on the model integration for the moment.

**Comment by eldy** [comment]
This seems to be analytics analysis.
I understand the need. A lot of ERP like Odoo proposed the same feature, but had a lot of problem with that : People make a confusion between analytics reporting and accountancy reporting, axis differs and they doesn't understand this. There was so many problem, that Odoo finally removed completely the feature in v8, even in the proprietary version (they keep only the feature, 1 line = 1 analytics code).
So this might be a sensitive feature. I think such a feature, that we can call "Analytics distribution on multiple lines" should be a dedicated module with its own table.
But relation with accounting or not must be clear : Does the user will make the analytic distribution on:
A) each line of the ledger table (in such a case this is a sub module of accounting module and module accounting will be a prerequisite) or 
B) just on business events (so on line of invoice, lines of expense report, etc..., with no need of accounting, and in such a case, we don't need accounting at all to use it) ? 

It should be one case or the other one, so what is the case you plan to do ?

Suggest the tables/fields you want to add before starting any dev, because this is a sensitive feature that may lead to tons of user issues and a lot of bad feedback. Such feature may also stay an external module (at least the visible part for end user) to protect Dolibarr of having too many bad feedback due to the use of such a feature by users that don't understand what means splitting lines to make analysis on different axis). It is the king of feature the seems to be easy to understand for us but, with experience, show that it is not used correctly by non experienced users and generate a lot of frustration for most users that does not understand what are cardinality on data and don't understand that having report on different axis may lead to different results because it depends on how you define your axis and how you analyze them.
So first, can you confirm we are in case A or B, and then suggest the format of data (table and fields) before starting any dev.

**Pull request closed without merging**
