### PR TITLE
FIX Lines are not inserted correctly if VAT have code

### PR DESCRIPTION
**Pull request by fmarcet**
Lines are not inserted correctly if VAT have code. We must clean VAT before use function price2num

### CODE REVIEW

**Comment by eldy** [comment]
The problem is that if you make getLocalTaxesFromRate before cleaning with price2num, if param was is a text price for example '1,20' for countries that use , as decimal, the vat is not a cleaned decimal when passed to getLocalTaxesFromRate and this function become crazy.
Also it means you call the function and sql request event if status is not draft and you don't need.

I suggest another way.
Test if txtva contains (). If yes, it means, it is already a cleaned vat rate (with dot and no other decimal separator) + a code, so in such a case, we just discard the price2num.
So we keep a better compatibility with old code calling function with a direct input user and we save sql request in such a case. Can you test this ?

**Comment by fmarcet** [comment]
Hello @eldy 
I had coded it in the same way as it is done in invoices (facture.class.php).

Do you suggest that I also modify the way it is done on invoices?

**Comment by eldy** [comment]
It would be great yes :-;

**Comment by fmarcet** [comment]
Hi @eldy 
The first thing I do is check if the status is draft.
Then I check if the VAT has code '()'. If it has code, I don't do anything. If it has no code, I call price2num()

**Pull request merged**
