### PR TITLE
Add version maintained into README.md

### PR DESCRIPTION
**Pull request by dpriskorn**
Add information about supported versions. 
Related to #14416

### CODE REVIEW

**Comment by eldy** [comment]
Note that the same README.md file must works for all versions because the file is not updated when a new released is done by the automatic release process.

**Comment by dpriskorn** [comment]
@eldy I just updated the branch. Is it better now?

**Comment by eldy** [comment]
It's better, however, saying we maintain only the last 3 stables branch is not really true.
Truth is that we maintain all branches opened (for example, i merged PR on v6 4 month ago). Where is the number of "3" coming from ?

**Comment by atm-maxime** [comment]
Maybe because there's 2 release manager positions for n-1 and n-2 version (https://wiki.dolibarr.org/index.php/Projet_Dolibarr) so people in the community conclude that only n, n-1 and n-2 are maintained versions.
Did you release a new v6 package after merging a PR in it 4 months ago ?

**Comment by dpriskorn** [comment]
@eldy I found the number here https://wiki.dolibarr.org/index.php/Versions

Dernières versions des branches maintenues :

- 12.0.1 

- 11.0.5 

- 10.0.7

**Comment by eldy** [comment]
> Maybe because there's 2 release manager positions for n-1 and n-2 version (https://wiki.dolibarr.org/index.php/Projet_Dolibarr) so people in the community conclude that only n, n-1 and n-2 are maintained versions.
> Did you release a new v6 package after merging a PR in it 4 months ago ?

I did not released a new package for v6. I do not do it, except in rarely situation, for version -2 and -1 (active release managers are wanted for that). But we must make a difference between saying that "a branch will not merge maintenance PRs anymore" and "a version has no more packages generated". It is 2 different things. Packages are above all for auto installer for non technical user, and branch maintenance for people that maintain Dolibarr for their customers.
For exemples some fixes were done few month ago in version 3.4, 3.5, 3.6 to have a better compatibility with PHP 7.x. No package was regenerated, but the branch and the version is still maintained so it is possible to update its branch with last version of branch 3.* to work correctly on a very recent infrastructure.
We should fix the wiki to avoid confusion.

**Comment by eldy** [comment]
Wiki was updated

**Pull request closed without merging**
