### PR TITLE
TCPDF: Replaced missing courier monotype font by provided freemono

### PR DESCRIPTION
**Pull request by rdoursenaud**
The courier font is missing from TCPDF's directory.
This leads to "TCPDF ERROR: Could not include font definition file: courier" being outputed by PHP
when the library attempts to render an element with a monotyped font.
Use freemono instead since it's a better alternative (e.g. supports more glyphs) and is already
shipped with Dolibarr.

### CODE REVIEW

**Comment by eldy** [comment]
Dolibarr code should never need to use this parameter because font is forced by the language file (we must use the font that depend on pdf output language). Do you have an example when error occurs ? (having this error mean we have a bug somewhere else i think).

**Comment by rdoursenaud** [comment]
Well, this is used by TCPDF internally and automatically on some occasions with writeHTML() on the `<pre>` tag for example. Not setting it or not restoring the courier font bundle simply breaks the library.
TCPDF is a very useful library and I want to leverage all of its potential.

**Comment by rdoursenaud** [comment]
Woop, wrong button, sorry.

**Comment by eldy** [comment]
OK. Never tested using pre tag.
Can you just complete the push by editing file dev/dolibarr_changes.txt
We track into this file all change we do compared to official distribution of external libraries. This help us to reproduce when we make external lib upgrades.

**Comment by rdoursenaud** [comment]
@eldy Done, thanks.

**Pull request merged**
