### PR TITLE
New: Update ckeditor from 4.3.3 to 4.5.3 (Compatibility Edge)

### PR DESCRIPTION
**Pull request by aspangaro**
Remove _source directory from the repository

### CODE REVIEW

**Comment by eldy** [comment]
What's wrong ith edge if we do not update to 4.5.3 ?
Completely broken or main features can be used ?

**Comment by aspangaro** [comment]
Hi @eldy,

https://github.com/ckeditor/ckeditor-dev/blob/master/CHANGES.md

No, generally it's work but with ckeditor 4.3.3 in Edge, some functions are broken and the "source" button crash the browser.

This version fix also a lot of xss vulnerabilities. 

if you want, I can lower the PR up to the branch 3.5 ?

**Comment by eldy** [comment]
No. Change of lib is done into freeze branch and older only if ---absolutely--- necessary. I think it is not.

**Comment by aspangaro** [comment]
ok, you can merge it into develop branch.

**Comment by rdoursenaud** [comment]
@aspangaro Now that my composer PR has been merged (#3352), this PR should be scrapped in favor of a new one.
The only thing you have to do from develop is update composer.json with `"ckeditor/ckeditor": "4.5.3"`, run `composer update`, `git add htdocs/includes composer.json composer.lock` and `git commit`.

**Comment by rdoursenaud** [comment]
Oh and also since ckeditor now uses semantic versioning (semver), we could use `composer require ckeditor/ckeditor ^4.5` which ensures latest 4.5.x version is installed.

**Comment by aspangaro** [comment]
Sorry @rdoursenaud I'm on Windows10 and my composer is broken for the moment. I propose to close this PR and what you make a new one. Thanks for your explanation.

**Comment by rdoursenaud** [comment]
@aspangaro You shouldn't use such a bad OS :p
I'll see what I can do.

**Pull request closed without merging**
