### PR TITLE
NEW Link to input facture source on payment when there is a lot of invoice

### PR DESCRIPTION
**Pull request by leninrivas**
# NEW|New [*Link to input facture source*]
[*Link to input facture source, useful when there are many invoices*]

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide a screenshot showing the addition ?

**Comment by leninrivas** [comment]
> Can you provide a screenshot showing the addition ?

Good day.
this screenshoot
screenshoot_when_manyinvoices

**Comment by eldy** [comment]
OK, so my understanding is that this link is when there is a high number of lines ? May be to avoid user to ask what is goal of the link (as i did), we can show it only if there is more than 10 links for example ?

**Comment by leninrivas** [comment]
> OK, so my understanding is that this link is when there is a high number of lines ? May be to avoid user to ask what is goal of the link (as i did), we can show it only if there is more than 10 links for example ?

Yes, then with a constant for example FACTURE_PAYMENTS_SHOW_LINK_TO_INPUT_ORIGIN_IS_MORE_THAN, and this for default 10.
let's proceed then.

**Comment by leninrivas** [comment]
> OK, so my understanding is that this link is when there is a high number of lines ? May be to avoid user to ask what is goal of the link (as i did), we can show it only if there is more than 10 links for example ?

That is it

**Pull request merged**
