### PR TITLE
Print IPP

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by marcosgdf** [comment]
Isn't `includes/printipp/CupsPrintIPP.php` missing?

**Comment by frederic34** [comment]
includes/printipp/CupsPrintIPP.php is already merged but some parts aren't finished. It works but need some work in config part. help is welcome
I have done this to be able to print file without opening acrobat if dolibarr can communicate with Cups (automated task can print, you just have to fill printer with paper)

**Comment by eldy** [comment]
There is currently a conflit into this push request. Can you try to solve it and push it again ?

**Comment by eldy** [comment]
Oops sorry, i missed your merge to solve conflict and i forgot to validate your push.
And now of course, there is another conflict. Can i ask you to solve it again ? I really would like to add your work. I will work on other comment/change myself, but i need you to make another push on dev branch that solve conflict.

**Pull request merged**
