### PR TITLE
Parameters harmonization of hook call

### PR DESCRIPTION
**Pull request by defrance**
odfhandler and substitutionarray are allways present

### CODE REVIEW

**Comment by defrance** [comment]
Additionnal fix : duplicate hookname ('ODTSubstitution' used 2 times, introducting 'ODTSubstitutionInit' for the first of all)

**Comment by eldy** [comment]
We should not use 2 different hook name ODTSubstitutionInit and ODTSubstitution
The hook means, we make substitution of reserved keywords with value decided by hook.
It is called twice because there is 2 different var to transform, but we must call the same function.

**Comment by defrance** [comment]
I do not agree: there are two hook must be able to differentiate the call of one or the other.
if one wishes to have the same processing function for both calls, call one of the functions from the other

---

je ne suis pas d'accord : il y a deux hook on doit pouvoir différencier l'appel de l'un ou de l'autre.
si on souhaite avoir la meme fonction de traitement pour les deux appels, il faut appeler l'une des fonctions à partir de l'autre

**Comment by eldy** [comment]
You probably did not understood the meaning of the substitution feature. The substitition engine must replace a string x into y whatever is the context. The "substitution engine" does not take care of the context because goal is to provide engine to substitue. Also if a context in to a hook must be set, it is not by duplicating hook name but by setting the parameter array.

**Comment by defrance** [comment]
actually with this hook ODT we can do in the order 
- change odt tags value in ODTsubstitution
- change odthandler in ODTBeforeSave
- change document file created in afterODTCreation

at the beginning of the patch i have harmonized the parameter of the hook, particulary 'odfHandler' and substitutionarray who's not passed in all hook

then i have notice that att the first call of ODTsubtition hook, the odfHandler is not already created
that why i prefered use 2 different function otherwhise i need to test the precence of this object in my function. I will be agree with you point of view if the first odtsubstitution hook was placed After the creation of odfhandler

The main goal of this change, is to display on a specific odt tags the list of all odt tags usable in the document. I can use the odtbeforesave because the substitutionarray passed is the langarray ...
My additionnal goal is to create some additionnal specific odt tags with simple hook placed in ODTSubtition call (the right one)

SO the question is "one same name and a conditionnal test on my unique hook function" or 2 differents name and two function in my hook

I can do se same thing in too case, just i think it's more clear in the call with two different names

**Comment by defrance** [comment]
@eldy seems this PR have diseapear

**Pull request merged**
