### PR TITLE
Fixed fatal issue with ISO charset for csv export.

### PR DESCRIPTION
**Pull request by bgenere**
# New [CSV export failing on Unix Ubuntu]
I find out that CSV export is failing while TSV export was working perfectly on the same export.

CSV code was forcing ISO character set and was causing a blank screen and an empty CSV file (no title, no records).
I have moved the HARD CODED ISO-8859-1 value to the $conf->file->character_set_client and that solved the issue for me as I am working using UTF-8.
I suspect the transnoentities function to cause the issue in code as documentation says it returns utf-8.
So I suggest to apply the character set  for output at the latest point when title or record is written.
Let me know, if I am correct and you want me to proceed with this fix.
Regards

#FIX display issue for custom modules dictionary list.
latest dictionaries where not displayed due to holes in table number and wrong allocation of order based on a count and not latest order given.

#FIX display issue for custom module import on entity name.
when array import_entities was empty entity name was initialized with icon and not name.

### CODE REVIEW

**Comment by eldy** [comment]
character_set_client is an old var used to saved pagecode of database. So it should not be used for csv export as it can contains values specific to database.
Choice was done to force to ISO because common usage is to say a CSV file is an ISO encoded file. 
Can you describe how you reproduce the bug ?

**Comment by bgenere** [comment]
I am developing a custom module using the develop branch.

I am currently working on having the export and import working for this custom module.
My test is to export data then import the result (having modified ref).

I find out that CSV export of my object was crashing (blank screen when I run the export), but the file was created empty.
When I was selecting TSV export, the file was properly created and the screen was refreshing properly.

I then test a TSV export on product using fields : ref and label and it was OK
Same export on products but using CSV driver was crashing (same as for my object), blank page and file created empty.
So the issue is not with the custom module.
It may be with my development environment, but I do not know why.

**Comment by bgenere** [comment]
I made more tests on my PC.

I put back the initial code and test again -> same issue the file is generated empty and the page is blank (php crash).

the value for _$outputlangs->charset_output_ on my conf is UTF-8.

If I comment this bloc (which does not exist in TSV driver) :

```
// 		else
// 		{
// 			$outputlangs->charset_output = 'ISO-8859-1';
// 		}
```

It's all fine and I get my CSV populated and no blank screen. So I think this piece of code is useless. If user want to force ISO they could use the constant above i.e.  EXPORT_CSV_FORCE_CHARSET.

Actually the current seems to work fine on my hosted platform using Dolibarr 4.9 but the issue is in this case the French specific characters are not displayed properly by default as my client is utf-8.

If you think this code is absolutely necessary it means I should define the EXPORT_CSV_FORCE_CHARSET on my PC server.

**Comment by bgenere** [comment]
I am going back to the original version and forcing UTF-8 using EXPORT_CSV_FORCE_CHARSET on my dev environment.
However I suspect a side effect issue with Translate::transnoentities method used in the code and which return an UTF-8 string following the documentation. As this is not a key blocker for me, I am happy with the EXPORT_CSV_FORCE_CHARSET workaround.

Regards

**Comment by bgenere** [comment]
I do not really know what to do with this pull request now as it contains also 2 other changes. 
I do not see how I could split my changes in other pull request and close this one using github.
It seems all commits made since I first summit this request are added automatically.
It's look like a mess and I do not know how to clean up this.

**Comment by bgenere** [comment]
I am closing this to try to go back to previous situation and see if I could get my fork even with Dolibarr

**Pull request closed without merging**
