### PR TITLE
fix #5455 Set MAIN_USE_JQUERY_DATATABLES give 404 on pdfmake.js

### LINKED ISSUE #5455: Set MAIN_USE_JQUERY_DATATABLES give 404 on pdfmake.js
# Bug

Set MAIN_USE_JQUERY_DATATABLES give 404 on pdfmake.js
## Environment
- **Version**:develop

### PR DESCRIPTION
**Pull request by ghost**
fix #5456 5455

### CODE REVIEW

**Comment by ghost** [comment]
link to #5443 and #5444

**Comment by eldy** [comment]
The more Dolibarr framework for managing table is enhanced, more I think datatable is not a good solution for future. It is too much limited (managing the "mass action" feature introduce with 4.0, management of extrafields, adding column by external module with hooks, filter on amount like this ">10 < 20", filter on string with start with or end with, saving columns per user profile, saving list of columns to show per page context, export restricted to few format when the mass action feature of dolibarr will allow to export list using all export engines of dolibarr, and a lot of other thing coming..).

I recommend if you want to use database to embed the library and all dependencies in your own module because datatable will probably be removed soon as embedded libray (currently not yet used by official feature of dolibarr and will probably never be used, all datatables feature can now be implemented by default framework with more features).

**Comment by ghost** [comment]
@eldy I'm ok to remove datatable from dolibarr but at least in 4.0 it is still there and if we activated DATABALE we have a 404 all the time on PDF "transformer" js lib, may be nice to remove inclusion to file that are not anymore present

**Comment by eldy** [comment]
Regis has pushed the PR to remove the inclusion of files not present #5846

**Pull request closed without merging**
