### PR TITLE
NEW : Extend retained warranty to be  available for all invoices

### PR DESCRIPTION
**Pull request by john-botella**
Extend retained warranty to be  available for all invoices

- replace const INVOICE_USE_SITUATION_RETAINED_WARRANTY by INVOICE_USE_RETAINED_WARRANTY

- Add const USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION  : Make "retained warranty" available only for situation invoices

- Add const USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL : On situation invoices the global "retained warranty" deduction is applied only on the final situation

TODO : add on invoice a new flag in database to give possibility to user to select if retained warranty is applied on a invoice situation final for a situation cycle.

### CODE REVIEW

**Comment by eldy** [comment]
Becasue USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION and USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL seems exclusive, why using 2 parameters: 
Why not USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION = 'all' for all situation invoice
'finalonly' for situation invoice at end only ?

**Comment by john-botella** [comment]
@eldy 
not really, maybe conf USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL is misnamed... 

**first case :**
INVOICE_USE_RETAINED_WARRANTY = 0
**_no retained warranty_**

**Second case**
INVOICE_USE_RETAINED_WARRANTY = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION = 0
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 0
_retained warranty **allowed** on standard invoices and all situation invoices steps_

**third case**
INVOICE_USE_RETAINED_WARRANTY = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 0
_retained warranty **not allowed**  on standard invoices but **allowed** all situation invoices steps_

**fourth case**
INVOICE_USE_RETAINED_WARRANTY = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 1
_retained warranty **not allowed**  on standard invoices and uncompleted situation invoices  but **allowed**  the final situation invoices_


**fifth case**
INVOICE_USE_RETAINED_WARRANTY = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION = 0
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 1
_retained warranty **allowed** on standard invoices and final situation invoice but **not allowed** for uncompleted situation invoices_

**Comment by eldy** [comment]
So the duplicate is between INVOICE_USE_RETAINED_WARRANTY and USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION.
What do you think of summarize with a clearer setup like this one suggested:


**first case :**
INVOICE_USE_RETAINED_WARRANTY = 0
**_no retained warranty_**
=> I suggest INVOICE_USE_RETAINED_WARRANTY = 0 or 'never'


**Second case**
INVOICE_USE_RETAINED_WARRANTY = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION = 0
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 0
_retained warranty **allowed** on standard invoices and all situation invoices steps_
=> I suggest INVOICE_USE_RETAINED_WARRANTY = 'standard+situation'
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 0

**third case**
INVOICE_USE_RETAINED_WARRANTY = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 0
_retained warranty **not allowed**  on standard invoices but **allowed** all situation invoices steps_
=> I suggest INVOICE_USE_RETAINED_WARRANTY = 'situation' and
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 0

**fourth case**
INVOICE_USE_RETAINED_WARRANTY = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 1
_retained warranty **not allowed**  on standard invoices and uncompleted situation invoices  but **allowed**  the final situation invoices_
=> I suggest INVOICE_USE_RETAINED_WARRANTY = 'situation' and
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 1

**fifth case**
INVOICE_USE_RETAINED_WARRANTY = 1
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION = 0
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 1
_retained warranty **allowed** on standard invoices and final situation invoice but **not allowed** for uncompleted situation invoices_
=> I suggest INVOICE_USE_RETAINED_WARRANTY = 'standard+situation' and
USE_RETAINED_WARRANTY_ONLY_FOR_SITUATION_FINAL = 1

Things seems really better to understand like this.

**Comment by john-botella** [comment]
I will try to show impact in code legibility

**Comment by john-botella** [comment]
I applied conf modifications
Remains to perform some tests before
I make sign when it's ready

**Comment by eldy** [comment]
Hi @atm-john Is your last commit the "sign" ?

**Comment by john-botella** [comment]
No, I perform test this morning :-)

**Comment by john-botella** [comment]
OK for me

**Pull request merged**
