### PR TITLE
FIX for #8379 display full product name

### LINKED ISSUE #8379: Feature Request - Full product name on the products list
# Feature Request
I think the full product name on the products list would be very helpful for many users not only me. At the moment product name is restricted and longer names are shorten by "..." even if there is enough space to fit full product name.

screen shot 2018-03-13 at 21 33 02

## Use case
That would speed up product search if we don't remember the full name or code of the product.

## Suggested implementation
responsive product names?

### PR DESCRIPTION
**Pull request by futurehousestore**
# Fix #8379 
Fix for old issue with unsuccessful previous attempt

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide a screenshot of result when all default fields are enabled in list and you have very long product name ?

**Comment by futurehousestore** [comment]
Screenshot attached in PDF version [mozilla.pdf](https://github.com/Dolibarr/dolibarr/files/4243042/mozilla.pdf)

**Comment by eldy** [comment]
I don't think having very long text on several lines into an array is a good idea. In most cases having only the first 30 chars is enough and if not, you can put the mouse over the ref to get full text.
Showing full notes into a table generate tables where you can see only one or 2 record when you want to see a list of 25.

**Comment by eldy** [comment]
This PR is now too old, so i close it. A lot of code may have been validated since the PR and the PR may be obsolete, or too difficult to merge due to other changes. Best choice is too cancel it to avoid to keep PR with too low chances to be validated.

**Pull request closed without merging**
