### PR TITLE
FIX multitentity code customer

### PR DESCRIPTION
**Pull request by atm-quentin**
# Fix # Check if actual entity is shared with others
Incrementing problem of customer code on thirdparty creation

### CODE REVIEW

**Comment by hregis** [comment]
@atm-quentin 
$mc object already exists !

**Review by hregis — CHANGES_REQUESTED** [review]
add a "global $mc" and test if $mc is an object

**Comment by hregis** [comment]
@atm-quentin 
But I do not understand the problem! 
Normally this is handled by "getEntity('company', 1)" !!

**Comment by atm-quentin** [comment]
The problem is that when you're on a shared entity, the customer code isnt the next of the max of all entities who have the data of your entity. For example :
Main entity have access to "test entity" thirdparty data.
When you're on test entity and you want to create a thirdparty your customer code stay at CU-0001 even if the customer code of main entity is at CU-0002, so you can't create it cause this code already exist on main entity.

**Comment by hregis** [comment]
@atm-quentin 
I do not have this problem!
You did not already have customer codes in the entity before adding it to the share?

**Comment by atm-quentin** [comment]
I just tested it again and you're right, i don't have the problem anymore, i probably did something wrong. Thanks for answers and sorry for bothering you.

**Pull request closed without merging**
