### PR TITLE
FIX : Bookmarks with entire url doesn't keep url parameters

### PR DESCRIPTION
**Pull request by ATM-Nicolas**
# Fix bookmarks
Bookmarks with entire url doesn't keep url parameters

### CODE REVIEW

**Comment by eldy** [comment]
Can't reproduce the bug on v6.
Can you describe on to reproduce ?

**Comment by ATM-Nicolas** [comment]
You can reproduce it when you use bookmarks with http protocol for internal links
For exemple, when the url of your bookmark is : http://localhost/Nicolas/dolibarr/htdocs/comm/propal/list.php?viewstatut=0 to show draft proposals
if you click on this bookmark in the bookmark main menu, it will redirect you on the following url :
http://localhost/Nicolas/dolibarr/htdocs/comm/propal/list.php?bookmark=137 
(note that localhost is just an exemple, it doesn't works with any DNS)

**Comment by eldy** [comment]
I tested with 6.0.7 and it seems to work correclty so this seems already fixed in branch 6.
Can you reproduce on 6.0.7 ?

**Comment by ATM-Nicolas** [comment]
I've done my tests with 6.0.8, and i can reproduce this bug

**Comment by eldy** [comment]
I have some reason to think this may be fixed into more recent version. Does this bug still occurs with last stable version ? (can't reproduce with v10)
If not, can you close ticket ?
If yes, can you confirm the last stable version you reproduced the bug with ?

**Pull request closed without merging**
