### PR TITLE
unify categories

### PR DESCRIPTION
**Pull request by frederic34**
- [X] sql
- [X] migration can be run several times, old tables will be deleted in v20
- [X] use new table in category class
- [X] sql changes

### CODE REVIEW

**Comment by frederic34** [comment]
@eldy can i have some feedback ?

**Comment by frederic34** [comment]
@eldy can you review ?

**Comment by frederic34** [comment]
no review so closing

**Comment by atm-maxime** [comment]
@eldy ?
@frederic34 you give up on this subject ?

**Comment by frederic34** [comment]
no review for about five months so bye bye PR

**Comment by atm-maxime** [comment]
@eldy how come you didn't review this PR ?
This would have allowed to use tags on any object in Dolibarr and simplify everything with tag management. Starting by replacing 15 tables by 1...

**Pull request closed without merging**
