### PR TITLE
# NEW|New [Adding new bank account doesn't work]

### PR DESCRIPTION
**Pull request by turkluka89**
# NEW|New [Adding new bank account doesn't work]
When you want to add first bank account, you can't, because app returns you are not allowed. The problem is when checking authorization on a table that doesn't have any rows count always returns 0. I edited sql select to add if there is any rows in table. I hope it helps. This is my first request.

### CODE REVIEW

**Comment by hregis** [comment]
@turkluka89 you can't merge develop to 16 branch

**Comment by turkluka89** [comment]
> @turkluka89 you can't merge develop to 16 branch

how can I commit then. I wanted to commit to develop but i couldn't.

**Comment by hregis** [comment]
@turkluka89 maybe a conflict, try to update your develop branch (git pull)

**Comment by turkluka89** [comment]
> 



> When you want to add first bank account, you can't, because app returns you are not allowed. The problem is when checking authorization on a table that doesn't have any rows count always returns 0. I edited sql select to add if there is any rows in table. I hope it helps. This is my first request.

image
I get this error on online editor.

**Pull request closed without merging**
