### PR TITLE
Use the __METHOD__ magic constant

### PR DESCRIPTION
**Pull request by rdoursenaud**

### CODE REVIEW

**Comment by eldy** [comment]
I was changing code to this but finnaly i discovered that it was better to use
get_class($this)."::".**FUNCTION**

I can't remind reason. I think it is when a class A herit class CommonObject, we want to see name of class A into log and not "CommonObject".
Are you aware of difference ?

**Comment by rdoursenaud** [comment]
**METHOD** returns something in the form Class::methodName.

For class, it always returns the class from where the method was executed.
That is if the method is inherited, the parent class but the local class if it is overriden. I think this is exactly the behavior we want into a syslog.
It's also nice that it's almost free since it's not a function.
If we really want to know the class of the calling object, we could do something like

``` php
__METHOD__ . " called from " . get_class($this)
```

in classes that are designed to be inherited (like CommonObject for that matter).

**Comment by eldy** [comment]
Using **METHOD** always return class name the function belong to. But in some cases (like to make log output), if class B1, B2, B3 inherit class A and call a method of class A, you may would like to see into log which class among B1, B2, B3 is calling.

For example you would like to see:

B1::commond_method_inside_framework
and not
A::commond_method_inside_framework

because you know that common_method_inside_framework is inside common inherited class A.

To solve this, replace **METHOD** with get_class($this).'::'.**FUNCTION**

```
class A
    {
        function commond_method_inside_framework()
        {
            echo "This is class " . get_class($this).'::'.__FUNCTION__.' '. __METHOD__.' '."\n";
        }
    }

class B1 extends A
    {
        function commond_method_inside_caller()
        {
            echo "This is class " . get_class($this).'::'.__FUNCTION__.' '. __METHOD__.' '."\n";
        }
    }

    $a = new A();
    $a->commond_method_inside_framework();   

    $b = new B1();
    $b->commond_method_inside_framework(); 

    $b->commond_method_inside_caller(); 
?>
```

Result will be

This is class A::commond_method_inside_framework A::commond_method_inside_framework 
This is class B1::commond_method_inside_framework A::commond_method_inside_framework 
This is class B1::commond_method_inside_caller B1::commond_method_inside_caller 

Did you see difference between line 1 and 2. I would prefer line 2, so i would prefer using

```
get_class($this).'::'.__FUNCTION__
```

**Comment by rdoursenaud** [comment]
Sorry, I don't like the `B1::common_method_inside_framework` display output if the method is declared in A.
In a syslog I don't want to know _who_ called (This should be provided by the context) but _what_ has been called. This way, if something misbehaves, I can get right to the source file without wandering around.
It may be just a matter of preferences but `get_class()` has a higher cost  for very little benefit IMHO.
Your call…

**Pull request closed without merging**
