### PR TITLE
New: TakePOS head bar

### PR DESCRIPTION
**Pull request by prietojc**
# Head bar
This bar shows and manages the start of Takepos:
- Date
- Terminal Number
- User
- Buttons on/off, fullscreen and more

### CODE REVIEW

**Comment by javierybar** [comment]
Good idea, but:
When click on POS no load correctly the app, you need change url to index.php
Terminal number is not showed
When I select other terminal than 1 crash

**Comment by prietojc** [comment]
Thanks **javierybar**, try now.

**Comment by andreubisquerra** [comment]
Better,
Good idea, but:
Now I can't change user,
And in small screens the head bar showed under other objects,
I thing is better if you can use Dolibarr user tab:
userchange

**Comment by prietojc** [comment]
Thanks @andreubisquerra,
- Small screens: right, should be resolve with CSS, but I think phones are not the way to use POS, maybe a tablet. 
- Dolibarr user tab: I tried this way before, but we need fast switching between waiters (users). The main handicap is the speed. In a shop we can type password in the change of shift, but in a restaurant/bar things go faster. Another idea is adding a new option in setup when there is just one user: _Show fast switching (yes/no)_

Please try the new commit, I hope feedbacks.

**Comment by prietojc** [comment]
The fast switching just use a default group of users. This group would be waiters, and list of permissions limited (they must not go to back office, so we need add this permiss).
I load commit for this option.

**Comment by javierybar** [comment]
In my tablet before this commit:
IMG-9884

And after this commit:
IMG-9883

If I create a group with users I can't switch.
The fast switching is very good idea, but I thing the waiters no are users. I thing is better create a new waiters table diferent users table.

And I thing too is better 1 pull request for 1 function

**Comment by prietojc** [comment]
Thanks @javierybar, I did a mistake with terminal id in user group. (By the way, in Terminal 1, some constants use  ID=1 and other blank, why?, is a headache)

About waiters, in my opinion I think isn't necessary create a new table, Dolibarr has got nice user groups which you can fill with a lot of permissions. Of course, we need to add some new permis to Takepos.

The main feature of head bar is manege user, sorry if I push other functions like fullscreen, but I'm splitting my module and it is hard and long do it.

And  the end, are you using a custom theme? Could you send me a screen in full size?

**Comment by javierybar** [comment]
I use default Dolibarr theme without changes.
I do not see how to create waiters without a password with Dolibarr users and without compromising security.

**Comment by prietojc** [comment]
Well, we have to think about that. I know that is a lack of security, but I think always it will be...  I mean, even if we make a new table for waiters, fast switching would not be enough strong. Any person could use the login of other user. BUT, we have to create new permission and not leave to use backoffice.

I understand can be an serious issue, it depends if we want fast switching or not.

About theme, are those rounded buttons from 10 version, I have not them?

**Comment by javierybar** [comment]
My idea is separate dolibarr users / takepos waiters. By default no waiters, and if the customer want waiters you can create waiter with or without pin.
Theme is default. In some tablets/phone rounded buttons displayed, but I don't know why.

**Comment by prietojc** [comment]
If waiters are not Dolibarr users, Have you think who user will be logged using waiters table?

**Comment by hregis** [comment]
@prietojc @javierybar @andreubisquerra 
lock the POS when a user is logged is a solution ?

**Comment by prietojc** [comment]
Resuming:

- Lack of security comes because _fast-switching_ doesn't ask for password. 
- The Dolibarr variable "dol_login" is in SESSION and user can goes to new pages directly from URL
- Are waiters users? (I think they must be, if not who log in Dolibarr?)
- If ALL **waiters stay into same group**, and this group can not go to backoffice, then the problem will become very small. Even going through a new URL the can't do anything because permission lock actions.

This is the question: want or not want fast-switiching. ;-)

@hregis what do you mean by locking POS?. Is there any way to block rest of Dolibarr when using a module?

**Comment by davidNDU** [comment]
Please also consider placing the Customer on top of the item list.
Currently the customer is only visible as long as the list is empty. Once the first item is added, the customer name is not seen anymore.

**Comment by eldy** [comment]
@andreubisquerra Did you test last version of PR ? Can i merge it ?

**Comment by andreubisquerra** [comment]
I have the same problem as @javierybar 
I like this PR but I thing need fix layout problems

**Comment by eldy** [comment]
Duplicate of #12662

**Pull request closed without merging**
