### PR TITLE
Fix: mysqlnobin export method now works better + more options...

### PR DESCRIPTION
**Pull request by lrq3000**
...(avoid duplicates values errors when a number is in fact a string and foreign keys checks are always disabled when restoring).

I also updated the wiki about saving and restoring Dolibarr's backups, particularly the database part (both in english and french).

Another thing: I wanted to add a mysqlnobin method to restore a backup, but I couldn't understand how dolibarr_import.php works (there's not even a <form> html element, does it really work?), but if you're interested this function would be based on this one:

http://dan.cx/blog/2006/12/restore-mysql-dump-using-php

Pretty simple but supports multi-line SQL statements, so in my books that should be ok.

/EDIT: added options for the mysqlnobin method (I tried to add as many options I could, for the rest, the user can just use phpMyAdmin or mysqldump).

### CODE REVIEW

**Comment by eldy** [comment]
The drop table was commented. If You can add option during export (Same option than the one found for mysqldump export ) it Will be great.

**Comment by lrq3000** [comment]
Yes I commented the drop table because I don't want the sql dump to forcefully remove any prior table, this should be done consciously by the user prior to import the dump (and anyway that's how a standard dump works).

What do you mean by adding options? Do you mean you'd like to have all the options that are available for mysqldump or you want me to add "drop table" as an option?

**Comment by eldy** [comment]
To add option on export page like we have after selecting the method
mysqldump.

**Comment by lrq3000** [comment]
If you mean:
1- adding only the drop table option, yes I can quite easily do that
2- adding all the options that are available for mysqldump: a lot more complicated and probably impossible to reproduce all the options since we manage everything manually in php, and there's no easy switch to do that like with mysqldump. In this case I'd rather not dive into implementing such a thing since it would be really time consuming, and also redundant because the export works and if the user wants a more complex backup facility, he can just use phpMyAdmin which has an exhaustive list of options.

**Comment by eldy** [comment]
Only the drop table is enough to have everybody happy because i think a
simple can be restored with only one command line mysql. With this option
you and i have the backup working in the way we want.

**Comment by lrq3000** [comment]
Ok no problem then, I'll implement it.

**Comment by lrq3000** [comment]
Ok done, I added as many options as I could, the "drop table" option is amongst them.

**Comment by eldy** [comment]
You sent a new push request ?

**Comment by lrq3000** [comment]
No need to, the new commit was directly added to this pull request by Github since it was linked to the head of my branch.

**Pull request merged**
