### PR TITLE
NEW: payment conditions enabling semi-automatic deposit creation (Issue #18439)

### PR DESCRIPTION
**Pull request by marc-dll**
I began implementing issue #18439, considering input from the following forum discussion : https://www.dolibarr.fr/forum/t/demande-davis-sur-fonctionnalite-acompte-automatique/37824

@eldy I will update regularly until it is ready to be fully reviewed and merged. Feel free to comment if you see anything disturbing ;)

### CODE REVIEW

**Comment by marc-dll** [comment]
@eldy All good for me, you can review ;)

**Comment by marc-dll** [comment]
@eldy: conflicts solved ;)

**Comment by marc-dll** [comment]
@eldy : All done : conflicts solved, fields and checks changed to strings, getDictvalue() renamed to getDictionaryValue() and a couple of other bugs fixed ;)

**Comment by marc-dll** [comment]
@eldy : Can you please make a feedback on this PR if still needed ?

**Comment by isamuse2** [comment]
Great feature, long awaited!

**Comment by eldy** [comment]
@marc-dll can you fix confllicts and repush pr ?

**Comment by marc-dll** [comment]
@eldy It should be ok now

**Comment by marc-dll** [comment]
@eldy : conflicts solved again, it would be really nice for this to be done once and for all ;)

**Pull request merged**
