### PR TITLE
Fix can't edit buying price if fk_product_fournisseur_price is set

### PR DESCRIPTION
**Pull request by aconits**
if we set fk_product_fournisseur_price value in propaldet the buying price is hidden and the user can't edit this value

### CODE REVIEW

**Comment by eldy** [comment]
I can't reproduce on 3.8. Can you provide steps to reproduce bug ?

**Comment by aconits** [comment]
Dolibarr way :
- Create product with price and buy price
- Create propal and select the buying price and add the product

First notice : dolibarr will save the row in propaldet with fk_product and buy_price_ht but the fk_product_fournisseur_price will not set (maybe it's an error)

For my way I use third module will automatically get the buying price what I want and update the row (set new buy_price_ht and fk_product_fournisseur_price)

If you force fk_product_fournisseur_price in database you'll not able to edit the buying price

**Comment by eldy** [comment]
The fk_product_fournisseur_price is just a bad field that should not be into database (it was introduce by error and replaced quickly by the buy_price_ht field).
That's why field is not set when creating a line and will never be.

How do you have this field filled ? Do you edit it manually into database ?

**Comment by aconits** [comment]
So if I understand it's an error to set this value from a external module ?

**Comment by eldy** [comment]
@atm-ph Yes. The error is even to use it (set or read). Field may disappear during a clean work.

**Comment by BebZ** [comment]
Is it an error to track a fk product fournisseur price from a Propal or Order and Invoice ?! 
I don't see why it is a mistake.  
One can want to choose a fournisseur price which is higher with less margin but more quickly ship-able. No ?
Buy price is only a price value field... With a fk prod fourn price field it is easier to add data on wished supplier chosen for the price it is sold.
Don't you think ?

**Comment by BebZ** [comment]
For my way I use third module will automatically get the buying price what I want and update the row (set new buy_price_ht and fk_product_fournisseur_price)

I think it is right behaviour to track what you sell with fk prod fourn ;)

**Comment by aconits** [comment]
From 4.0 you can use "MAIN_CAN_HIDE_EXTRAFIELDS" to use hidden extrafields

**Pull request closed without merging**
