### PR TITLE
Mutualise code, introduce MAIN_ALL_TOWN_TO_UPPER

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by hregis** [comment]
@frederic34 great but for the composed first name and last name? Eg Jean-Pierre

**Comment by frederic34** [comment]
ex JEAN-PIERRE => Jean-Pierre

**Comment by hregis** [comment]
The "-" and ' are manage?

**Comment by frederic34** [comment]
yes I just made the test for the "-"

**Pull request merged**
