### PR TITLE
NEW supplier buyprice barcode

### PR DESCRIPTION
**Pull request by atm-quentin**
# New Supplier Buy price Barcode

Give possibility to manage buy price by barcode.
When you scan your product, you immediately find the good buy price on supplier object
You can go to the product page too by scanning this code

### CODE REVIEW

**Comment by BebZ** [comment]
is it possible to give you a +1000 ?

**Comment by wdammak** [comment]
it's possible to give you +10000000 ?
it's the most successful feature since version 5-6
it's a necessary and mandatory feature for retail sale.
I can not wait to test it!!!

**Comment by atm-geoffrey** [comment]
@wdammak 
To go further, we are also studying the possibility of receiving supplier orders by scanning supplier barcodes. See you next stape :)

**Comment by BebZ** [comment]
I think also @fappels will be interested in the current and next development to simplify supplier receptions if needed ;) Because sometimes one supplier has 2 different barcodes for packaging : 
1 barcode for unit and one barcode for overcarton of 12 units
and sometimes in Dolibarr we have one product ref with 2 different suppliers : 
For example you can buy product X from country A supplier ref XXX and product X from country B supplier ref XXX0...
in this case it can be more easily handled ?

**Comment by fappels** [comment]
@atm-quentin you made commit in wrong branch.

**Comment by eldy** [comment]
Can you push on develop ?

**Comment by atm-quentin** [comment]
https://github.com/Dolibarr/dolibarr/pull/10703

**Pull request closed without merging**
