### PR TITLE
fix: cannot update password if dolibarr_main_authentication="mc" (multicompany)

### PR DESCRIPTION
**Pull request by FHenry**
If $dolibarr_main_authentication=mc impossible to udate password because filed readonly is displayed

### CODE REVIEW

**Comment by eldy** [comment]
@hregis is it ok for you ?

**Comment by hregis** [comment]
@FHenry @eldy
 it's a Multicompany bug since v19, I didn't see that the `$caneditpassword` variable was changed to `$caneditpasswordandsee`
I made a correction on v19: https://github.com/Dolibarr/dolibarr/pull/32246
and I will correct Multicompany.
after if we can add a test on the "mc" authentication it will save me some hooks! :-)

**Comment by hregis** [comment]
@FHenry @eldy maye add this in develop branch to avoid conflict

**Comment by FHenry** [comment]
We can close this PR, because use hook  in multicompany is the real fix, as $dolibarr_main_authentication can be provided by external module, all related test on this in Dolibarr Core have to be overridable by a hook.
I've just check in 20.0 the occurence of $dolibarr_main_authentication and I didn't find any other test like the one in user/card.php

@hregis I've just check our fix, it works, thank's

**Pull request closed without merging**
