### PR TITLE
Close #15917 : Improvement to ticket module

### LINKED ISSUE #15917: NEW Improvements to Ticket module 'Ticket Area' Screen
# Feature Request
Add more data/graphs to 'Ticket Area' screen.  Currently there are only 2 tables, - Statistics (year) and Last 10 newest tickets.
More options would be nice such as:
Chart for Ticket Type
Chart of Ticket Severity
Graph of daily tickets for last X days
New tickets vs Completed tickets for the day.

## Use case
Seeing these data points at a glance helps determine how your support department is doing for the day/week and what sort of ticket severity needs to be addressed.

## Suggested implementation
Add these data sets/charts as fixed option to the 'Ticket Area' screen or allow the end user to create widgets based on these data points and add them to the 'Ticket Area' screen.

### PR DESCRIPTION
**Pull request by Hystepik**
4 new graphes for ticket page
image

### CODE REVIEW

**Comment by eldy** [comment]
Number of tickets by severity. Is it Number of tickets (all time) or number of open tickets ?
Same for Number of tickets by types
Number of new tickets by day the last 7 days. Is it based on "date of creation" ?

Also, i suggest to move all those graphs into widgets (1 graph = 1 widget) and the modify the page to setup widget+the index ticket page to allow to add widget on the ticket index page. 
Can you enhance this in this direction ?

**Comment by Hystepik** [comment]
Number of tickets by severity is on open tickets
Number of tickets by types is also on open tickets
Number of new tickets by days the last 7 days. Is based on "date of creation" yes

**Comment by Hystepik** [comment]
Not finished

**Comment by eldy** [comment]
I made some fixes to make thing cleaner. i have still 2 bugs. When you remove a widget from the page ticket, you have a message saying "widget added" => to fix.
Same pb on home page of top menu Thirdparty and Member and User

On the Membership home page, when we add a ticket with a graph (like one for tickets), the colors of first graph become gray.

The drag and drop to move a widget from one column to the other seems also broken.

Can you have a look @Hystepik

**Pull request merged**
