### PR TITLE
QUAL fix hooks on contact.php files - fixes contexts

### PR DESCRIPTION
**Pull request by cfoellmann**
# QUAL
Some */contact.php pages are missing proper hooks and thereby context for externally defined actions.
Also doAction is missing in some.

### CODE REVIEW

**Comment by hregis** [comment]
@cfoellmann can you use english for the context ? "invoicecontactcard", "ordercontactcard", etc... thank you

**Comment by cfoellmann** [comment]
@hregis will do.
what about 'globalcard'? where should that be added? Only to the main card.php or to all cards like contact, note, agenda etc?

**Comment by eldy** [comment]
'globalcard' is for all tabs.
Not sure it is used yet, but well, was introduced like that.

**Comment by cfoellmann** [comment]
I think this PR is ready now.
I will go over the other cards files and clean those up over the holidays.

**Pull request merged**
