### PR TITLE
FIX #1460, #1461

### PR DESCRIPTION
**Pull request by KreizIT**
Adding also ORDER_SUPLIER_\* triggers not found in interface_90_all_Demo.class.php-NORUN

### CODE REVIEW

**Comment by marcosgdf** [comment]
I think adding triggers to htdocs/core/triggers/interface_90_all_Demo.class.php-NORUN is useless as it  only gives an explanation on how to catch them. (Also with one or two examples is fair enough). The list of triggers is managed in the wiki

**Comment by hregis** [comment]
yes it is ! ;-)

**Comment by marcosgdf** [comment]
Do you think is useful? why? I'd like to read your opinion.

**Comment by hregis** [comment]
the trigger demo is just a dictionary of all available triggers with skeleton of the code

**Comment by marcosgdf** [comment]
Then what is http://wiki.dolibarr.org/index.php/Template:TemplateListOfTriggers for?

**Comment by hregis** [comment]
yes there are fans of the wiki and more! ;-)
but the demo file also serves as a skeleton to build a trigger, you know?

**Comment by marcosgdf** [comment]
I know... but the 90 % of the code in that file is duplicated. I think two examples are enough to show a developer how to catch triggers if the list is completed by the wiki. Don't you think so?

**Comment by hregis** [comment]
yes I agree, the file is historic, it was used as an example before the wiki. Perhaps this file should be placed in the "dev" with the minimum and put a reference to the wiki in this file?

**Comment by KreizIT** [comment]
At my beginning of dolibarr, I read this file and not the wiki. Code is useless for sure but as said Regis it's dictionnay (or should be).
If you really think this file is totaly useless, delete it from project. 
Better no file than outdated file.

**Comment by rdoursenaud** [comment]
The other fixes are worthy.

I believe the NORUN/demo files should go into /dev.
Useless code in production environments is always asking for trouble.
I remember such a file leaking user passwords in the webservices.

My 2 cents…

**Pull request merged**
