### PR TITLE
Show HT amounts for compta reports

### PR DESCRIPTION
**Pull request by dbeniamine**
# New Show HT amounts on compta reports

The compta report page `compta/resultat/index.php` computes HT amounts but does not show them, this PR shows the amounts TTC and HT side by side when `$modecompta` is not `BOOKKEEPING`.

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide a screenshot of page without and with you changes ?

**Comment by dbeniamine** [comment]
Before :

image


After :  

image


Sorry the tables are empty as I do not have a test database with enough fake date.

On the last total line, the HT amount appears if not 0

**Comment by eldy** [comment]
Tha table show now 5 years. doubling the amounts (without + with tax) maks table more difficult to read/compare. So i suggest instead to introduce a link "Show amount without tax". When click on it, we reload the page and show content without tax. Link is then name "Show amount with tax".
The link can be similare to this one 
image
Except it is "Show amount without tax" and "Show amount including tax".

**Comment by dbeniamine** [comment]
I have not updated this branch since a while, but I consider it obsolete and not required anymore, as the report by invoice now shows both HT and TTC amounts:

image

So I am closing this PR

**Pull request closed without merging**
