### PR TITLE
NEW Add admin parameter BANK_ASK_PAYMENT_BANK_DURING_SUPPLIER_ORDE for supplier order

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by eldy** [comment]
The requested bank is the bank you plan to use by default for the payment ?

**Comment by frederic34** [comment]
It is used here:
https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/fourn/commande/card.php#L1460-L1467

**Comment by eldy** [comment]
But what is the goal to define the bank account during a proposal request ?

**Comment by frederic34** [comment]
It's not during proposal request but in order supplier

**Pull request merged**
