### PR TITLE
WIP #15383 : New widget: Tunnel of prospection

### LINKED ISSUE #15383: New widget: Tunnel of prospection
Add a widget with a graphic per status of prospection (similar to graphic into home page of project).

### PR DESCRIPTION
**Pull request by Hystepik**
New widget Funnel of prospection which permit to have the graph in project index as a widget

### CODE REVIEW

**Comment by eldy** [comment]
Because this feature add a new things for screen, to help everybody understand what it is, can you add a screenshot of the home page with the widget visible ? (Adding an image is as simple as copy paste image with github)

**Comment by Hystepik** [comment]
image
image
There it is

**Comment by eldy** [comment]
Since this widget goal is to show the funnel of "opportunities to work on", you can exclude here status lost (such opportunities are outside the funnel).
Also the number of each status can be added between () into the legend and removed from the bottom of graphic.

**Comment by eldy** [comment]
This is a good excercice : There is a conflict on a file due to another PR already validated that has updated a common file.
Try to solve the conflict by re-submited the PR after merging last version and solving conflict.

**Comment by eldy** [comment]
I validated the PR but there is still some work to close the #15383. This is the 2 things to do:
* Change the type of graph from donut to horizontalbars. 
* The status must be on y and value must be on x. So graph will looks like
Prospection  ------------------
Qualification ------
...                 -----------

**Pull request merged**
