### PR TITLE
Enable Imports with third-party references using customer/supplier code in addition to rowid and name in v13

### PR DESCRIPTION
**Pull request by StephaneLesage**
# New
Modify all imports related to third parties to be able to reference them by customer/supplier code in addition of name which may not be unique:
- third party: mother company
- third party contacts, bank accounts and sale representatives
- categories
- customer propal/orders
- supplier orders/invoices
- product/service supplier prices

### CODE REVIEW

**Comment by StephaneLesage** [comment]
fix #15490

**Comment by StephaneLesage** [comment]
This should be applied to version 12 also after merging previous PR which were not merged in v12:
- my #14512 and #14532
- @rabib-metroworks #14880 #14920 #14929 #14960
- and @dvdwalker #15139

**Comment by StephaneLesage** [comment]
version applicable to branch 12.0 without new features is PR #15603.

Should modify this one for new features only ?

**Comment by eldy** [comment]
develop branch is now open for merge.
Can you help me to solve the conflicts ?

**Comment by eldy** [comment]
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Pull request closed without merging**
