### PR TITLE
NEW trigger in CommonObject::update_price() + DB transaction wrapping

### PR DESCRIPTION
**Pull request by atm-florianm**
# New trigger 'AFTER_UPDATE_PRICE' in CommonObject::update_price()
As it stands, when a module needs to do something when the total amount of an invoice/order/proposal changes, it has to use the triggers for every action that ends up calling `update_price()`, including (but not restricted to) every possible combination of `LINE(PROPAL|ORDER|BILL)_(INSERT|UPDATE|DELETE)`, with some of them having specificities that need to be taken care of.

This trigger might help with this issue by providing a more unified and straightforward way of intercepting amount changes on standard documents.

### CODE REVIEW

**Comment by eldy** [comment]
The update of price is not a CRUD (Create / Read / Update / Delete) event on a business object.
So we can't use a trigger at this place (triggers are limited to CRUD action on business event, so on class extending CommonObject) . However, if you need to intercept code here to have a generic way to act when price changes, you can introduce a hook instead.

**Comment by atm-florianm** [comment]
Thanks for your quick reply.
It seems to me that updating the price of a business object amounts to an update, even if it doesn’t call `$this->update()` (it still does update the object in the database). Maybe `update_price()` should simply call `$this->update()` and not have a trigger of its own? I am not sure what this would imply.

If you find it impractical or objectionable, I will simply make a hook as you suggested.

**Comment by eldy** [comment]
update_price is called to update a invoice when you make a change on a line.
So it is a feature to enhance performance (by "de-normalization" of the total). The business object that is updated here is not the invoice but the line and only the line. The total price of an invoice is not an information of the invoice but the total of all lines. Here we duplicate information.
So it is not a CRUD event on a business object. With a normalized database (a database folloing completely the "Normal Form", see https://fr.wikipedia.org/wiki/Forme_normale_(bases_de_donn%C3%A9es_relationnelles), this function would just not exists. It is the proof that it is not a CRUD on a business event. Imagine a synchronized system that does use only the lines to know the total of lines. Trigger that update the line is enough to synchronize the external system. If the external system decide to also duplicate information, there is no need to trigger a second event. It is another proof.

So yes, introduce a hook instead.

**Comment by atm-florianm** [comment]
Thanks @simicar29!

**Pull request closed without merging**
