### PR TITLE
FIX bad entity for login user on multicompany

### PR DESCRIPTION
**Pull request by atm-robin**
The check for password is right but the fetched user is the first with right login, not login and entity

### CODE REVIEW

**Comment by hregis** [comment]
you ca not force the entity !!!

**Comment by ghost** [comment]
Hi Laurent, Because the checkLoginPassEntity don't contain the $user var and this function work fine. It's into main.inc.php that the calling of the function is good but the init of the $user object was wrong.

But i just see the FIX won't working as we except because of that in user class : 

if ((empty($conf->multicompany->enabled) || empty($conf->multicompany->transverse_mode)) && (! empty($user->entity)))
{
        $sql.= " WHERE u.entity IN (0,".$conf->entity.")";
}

I'll check that with my team to propose a better fix (by get the entity into $user object instead of conf if exist i think)

**Comment by eldy** [comment]
So the problem is that multicompany allow several user with same login.
And dolibarr do
- check login/pass/entity. If ok, we return login
- dolibarr load user from login.

I pushed a try to fix this.

**Comment by frederic34** [comment]
Fix Typo:
https://github.com/Dolibarr/dolibarr/pull/3790

**Comment by hregis** [comment]
je suis au bord de l'énervement ! ;-)
j'aimerais être consulté avant de faire des modifs qui concerne multicompany !
ce commit casse l'authentification en mode transverse

https://github.com/Dolibarr/dolibarr/commit/77c43ebb26f279a1ad49e1b85269b57e940de215

**Pull request closed without merging**
