### PR TITLE
fix : only generated files displayed on document board card

### PR DESCRIPTION
**Pull request by defrance**
Actually display all the files present in joined document tabs

### CODE REVIEW

**Comment by eldy** [comment]
Goal of function is to show all linked documents linked to an object. Why adding this filter ?

**Comment by defrance** [comment]
We have 2 ways to show documents linked to an object : 
-> from the main tabs : we need to show generated document based on the object
-> from the documents tabs : we show all documents linked to the object (pictures / docs / pdf, ...)

if we do not applied the filter like as proposed, we have ALL the documents linked on the main tabs, who is noit really ergnomic...

**Comment by eldy** [comment]
It's a point of view. But having different content for "linked files" at 2 different place is probably worse.
I would prefer an enhancement into the list on the main tabs where all "other" linked fileds are hidden with a css style and a click on "show all linked files" will make this lines appears.

**Comment by defrance** [comment]
"linked files" is not at the good place on the card tabs, For some elements we can have many associated document but the main problem is to make confusion beetween files create with dolibarr and files added (ex an fournish order receive in pdf added in customer order for information...)

Propose to have "Generated Files" on Card tabs and "Linked files" on the Document tabs and create a specific filter (better than i have made) for separate generated document from other

**Comment by eldy** [comment]
Before deciding where to show which file, we must be able to detect the property "generated or uploaded" for each file.
For this a dedicated table exists called llx_ecm_files exists for this. Each time, we upload or generate a file on a documents, we should add an entry here.

Goal of this table is:
- being able to store information like "generated" or "uploaded"
- being able to decide which image must be used as cover image for card for images uploaded on products
- being able to store index information for indexing search
- define an order between files in same directory
- in a future, use permission per files
- ...

A PR that will make this must be firstly done:
- Creating an entry in this table should be done in function used when we upload a file (dol_move_uploaded_file...
- Deleting entry in function used when we delete a file (the key is field "fullpath").

**Comment by eldy** [comment]
With v7, files "generated" are tracked into the ecm table.
Also the last "main doc" generated is saved into table of object.
This PR should be reconsidered using this new properties if you want to add an option to restrict list of documents on main tab (for example by filtering to show only "generated" documents and not uploaded and adding a link "see other uploaded doc on the document tab..." so user know the list is restricted.

**Pull request closed without merging**
