### PR TITLE
FIX wrong class name "CUnits instead CMeasuringUnits"

### PR DESCRIPTION
**Pull request by hregis**

### CODE REVIEW

**Comment by ghost** [comment]
@regis, I've image two dictionnaries, they are différent actully (one was hard coded "cMeasuringUnit" before the PR, the other is already exists Cunits), to goal is to keep two dictionnaries to avoid regressions

**Comment by hregis** [comment]
@atm-florian @eldy 
Laurent deleted "CMeasuringUnits" and changed "CUnits" !

**Comment by mwelters** [comment]
related Issue: 
#10620

**Comment by ghost** [comment]
Ok, I didn't see it. I was thinking cUnit will be use to define sell and buying unit (and in the future a convertion between them), and measuring unit for orther purpose.

**Pull request merged**
