### PR TITLE
Fix Public Ticket footer

### LINKED ISSUE #11470: BUG: Public ticket page display PayPal footer
# Bug
 Public ticket page display PayPal footer

## Environment
- **Version**: 10
- **OS**: [*Server OS type and version*]
- **Web server**: [*Webserver type and version*]
- **PHP**: [*PHP version*]
- **Database**: [*Database type and version*]
- **URL(s)**: [*Affected URL(s)*]

### PR DESCRIPTION
**Pull request by futurehousestore**
# Fix #11470

### CODE REVIEW

**Comment by ptibogxiv** [comment]
We introduce sale footer for standard footer public page for gdpr et safe infos for customers.

For moments, footer come from payment page but we need more option for footer for all public pages

**Comment by futurehousestore** [comment]
Thanks, @ptibogxiv for letting me know. It would be nice to /comment the code in this case, also this kind of "unfinished features" shouldn't be included in STABLE versions. Anyway, by mistake, I've uploaded the wrong file so @eldy please don't merge.

**Comment by ptibogxiv** [comment]
same thing for  #11474

**Comment by sam-anam1** [comment]
the issue is still with Version: 10.0.1 in **create ticket page**
example 

**Paypal settings** 
Paypal

**create ticket page**
create_ticket

**Pull request closed without merging**
