### PR TITLE
 [ bug #806 ] Tasks are ordered alphabetically instead of chronological order

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by marcosgdf** [comment]
Missing changelog entry!

**Comment by altairis-tof** [comment]
i know, i'm doing it ;-)

**Comment by simnandez** [comment]
I think the order showing of a item really is not a bug...

**Comment by altairis-tof** [comment]
i was thinking like you, so i first did the job on develop branch (see https://github.com/Dolibarr/dolibarr/pull/976 ) but then Marcos told me it's a bug as also said on doliforge (see https://doliforge.org/tracker/?func=detail&aid=806&atid=246&group_id=144 ) so i did it here as a bugfix.

**Comment by eldy** [comment]
I also think it's more a feature than a bug.
Also sorting with date creation is not really better than alphabetic order.
I prefer discard this and convert the bug into a task to add a field "pos" (position) to choose order of tasks

**Comment by marcosgdf** [comment]
Date of creation? Bug #806 from Doliforge asked of "start date" sorting. I find like a "bug" because it does not make sense to have tasks ordered by alphabetic or creation date order, as many times, tasks are created by the project manager and the assigned to each developer, who should have first the tasks that need to do first.

I really didn't know if it was a bug or a task, but I think it is a problem because of the usability of the module...

**Comment by altairis-tof** [comment]
i now sort by start date.
i also think this features is unusable with the alphabetical sort order so we should fix it on this branch (very minor fix indeed)

**Comment by eldy** [comment]
OK. It is a small change so i validate.
However, i think it is no more usable like this. Good solution is to enter a way to order tasks as the user want (using pos into a field).
marcos, it would be great if you can switch bug to fix and open a task instead for this ?

**Pull request merged**
