### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by dolibit-ut**

### CODE REVIEW

**Comment by eldy** [comment]
Not sure it is a good idea to add index.html everywhere into.
Why not remove them everywhere ?
Why keeping them ? It is not a problem to see the content of a dir. This information is already public on github !

**Comment by daraelmin** [comment]
It could be more efficient to use htaccess 'deny from all' command

**Comment by dolibit-ut** [comment]
> Not sure it is a good idea to add index.html everywhere into.
> Why not remove them everywhere ?
> Why keeping them ? It is not a problem to see the content of a dir. This information is already public on github !


I think it makes a difference to read the Dolibarr dirs/files from Github
or to scan the files on a real productive webserver.

Not all hosts use a /dolibarr/ path - 
so you dont know what you are scanning until you see the files.

And maybe not everyone has an up-to-date repository 
so it can be useful to hide this.

A htaccess is possibly a good alternative.

**Comment by eldy** [comment]
A htaccess is surely a better alternative.

**Pull request closed without merging**
