### PR TITLE
fix issue #3579 : bad filtering caused by statut filter

### PR DESCRIPTION
**Pull request by defrance**

### CODE REVIEW

**Comment by defrance** [comment]
i agree it's done

**Comment by rdoursenaud** [comment]
Looking at the related #3571, -1 is also a valid status.
So we may need its fix plus yours adapted to

``` php
>= -1
```

**Comment by rdoursenaud** [comment]
Better yet, you could use the class constants to make the code explicit:

``` php
if ($search_status >= Commande::STATUS_CANCELED)
```

**Comment by defrance** [comment]
not agree with that, what append if constant class value varry and draft statut move to 0 to 1?

**Comment by rdoursenaud** [comment]
s/append/happens/
I expect the developer to be cautious and search for "Commande::" constants and make the required refactoring.
Without it, he has no clue what the single digit value means making the code more fragile.

**Comment by defrance** [comment]
particullary if the constant is for bill, not for commande ;-)

**Comment by rdoursenaud** [comment]
@defrance woops, you're right, I mixed the two issues since they are very related… but yours is for invoices whereas the other is for orders. Way to get confused ;)

**Pull request merged**
