### PR TITLE
Add feature to inform error is deprecated

### PR DESCRIPTION
**Pull request by KreizIT**
Could be usefull for chasing down usage of error or other property.
You could use this to test undeclared property also by changing else part of __set to : 
if (property_exists($this, $name)) {
            $this->$name = $value;
            return;
} else {
            trigger_error("Undefined property in __set(): {$name}");
}

and else part of __get to :
if (property_exists($this, $name)) {
            return $this->$name;
        }
        else {
            trigger_error("Undefined property in __get(): $name");
            return NULL;
}

### CODE REVIEW

**Comment by KreizIT** [comment]
Travis failed because error is marked deprecated :)

**Comment by frederic34** [comment]
Travis failed because phpcs didn't output log for 10 minutes ;-)

**Comment by eldy** [comment]
The phpcs timeout problem shoub be now fixed.

**Comment by KreizIT** [comment]
Seems not ;)

**Comment by marcosgdf** [comment]
Projects usually have a param in their configuration to ensure it is a dev environment or a prod one.

**Comment by eldy** [comment]
Before having report on user usage (so into log), i would prefer to have a period with error reported to developer, so by having the property set to deprecated to have this reported to dev.
So i added tag @deprecated onto param.

**Comment by eldy** [comment]
Deprecation of error (error and errors finally coexist well together so i close this PR.

**Pull request closed without merging**
