### PR TITLE
Allow sales representatives to search themselves in the prospects and client lists

### PR DESCRIPTION
**Pull request by rdoursenaud**
Don't know if this is the best implementation but at least this prevents the empty select when the user is not allowed to see other users.

### CODE REVIEW

**Comment by eldy** [comment]
// Allow at least to search themselves
       $sql_usr .= " UNION ";
       $sql_usr.= "SELECT u3.rowid, u3.name as name, u3.firstname, u3.login";
       $sql_usr.= " FROM ".MAIN_DB_PREFIX."user as u3, ".MAIN_DB_PREFIX."societe_commerciaux as sc";
       $sql_usr.= " WHERE u3.rowid = sc.fk_user AND sc.fk_user=".$user->id;

is same than 

```
   $sql_usr .= " UNION ";
   $sql_usr.= "SELECT u3.rowid, u3.name as name, u3.firstname, u3.login";
   $sql_usr.= " FROM ".MAIN_DB_PREFIX."user as u3";
   $sql_usr.= " WHERE u3.rowid = ".$user->id;
```

and if we do this, why not just adding a OR u3.rowid = ".$user->id; into the first SELECT of the union ?

**Comment by rdoursenaud** [comment]
Wow, this is embarrassing. Seems my hack was ugly as hell.

In fact, I didn't grasp the surrounding logic and still can't figure it out.
What's expected to be shown in this select ?

My rationale would be :
- If I'm an internal user, show at least me (displaying en empty select is distracting/annoying for the user)
- Plus if I'm allowed to see my colleagues, show all internal users
- If I'm an external user, show my sales rep(s) but don't show me as I'm not a sales rep.

What do you think of it?

**Comment by hregis** [comment]
This pull request cannot be automatically merged

**Comment by eldy** [comment]
- If I'm an internal user, show at least me (displaying en empty select is distracting/annoying for the user) -> yes (so we can add OR u.rowid = ".$user->id in first select should be enough.
- Plus if I'm allowed to see my colleagues, show all internal users -> yes
- If I'm an external user, show my sales rep(s) but don't show me as I'm not a sales rep. -> yes (so the OR u.rowid is not enough, we should add OR u.rowid = ".$user->id only if we are internal user.
  Right ?

**Pull request closed without merging**
