### PR TITLE
#FIX tempalte 03 css

### PR DESCRIPTION
**Pull request by Quatadah**
Template 03 Contact page is now centred, additionally all the css is under the .bodywebsite class.

### CODE REVIEW

**Comment by hregis** [comment]
@Quatadah where is the repository of templates? Thanks

**Comment by Quatadah** [comment]
@hregis htdocs/install/doctemplates/websites/*
is that the repository you are asking for ?

**Comment by hregis** [comment]
@Quatadah no the source of zip

**Comment by Quatadah** [comment]
@hregis Only the zip is exported to the github repository, but if you create a new website and you import the zip of the template you want, you can see its source code.

**Comment by hregis** [comment]
If I need to fix or add features in the template?

**Comment by Quatadah** [comment]
@hregis you can create a website on the websites module, import the zip of the template you want to edit, and then you can make the modifications, export the new zip and replace it in htdocs/install/doctemplates/websites/

**Comment by hregis** [comment]
@Quatadah it's not user friendly ! you can't manage the history of changes

**Comment by eldy** [comment]
> @Quatadah it's not user friendly ! you can't manage the history of changes

@hregis currently, we have no better solution for website templates because a website template is "inside" database (files are just cache). We should enhance the "Import website" process to be able to make an import from a "directory" instead of a "zip" (the directory would be the template unzipped). In such a case, we would be able to store the website template inside a subdir of htdocs/install/doctemplates/websites/ . At least we will have txt file.
and we will generate the zip (to save spaces and being able to distribute easily templates) only for the release.

**Pull request merged**
