### PR TITLE
Fix user can always change project owners

### PR DESCRIPTION
**Pull request by ghost**
# Fix - Draft
When a user have the rights to read all projects,
but the user can not change all projects
and the visibility of a project is `Project contacts`
and he is not a project owner
and he is not the project creator
-> the user can change the `Contacts of project`

Opera Momentaufnahme_2019-11-22_085001_dolibarr

Opera Momentaufnahme_2019-11-22_111127_dolibarr

This is a not complete fix for this problem,
but I have no idea how can I find out which user is a project leader

### CODE REVIEW

**Comment by eldy** [comment]
On the case you mention, the user has "permission to create/modifiy project i am contact for".
And he is a contact of the project, so he can modify the contact of the project. This is expected behaviour.
If a user has permission on a project, he can also change contacts.
There is no permissions that depends on the role of project. Dolibarr permission is quite simple.
You can read only or you can edit. And edit means you change change anything, so you can change also the contact.

**Comment by ghost** [comment]
Hello,

and when we add a additional permission for projects that can only enabled/disabled, when the extend user roles are activated?

Like: ```User can link/unlink project contacts```

**Comment by eldy** [comment]
Why not adding such a permission "User can link/unlink project contacts"  but it means you have a use case where:
- a project leader can add tasks on project (so need permission modify project),
- but has no permission to decide who works on the project (so will won't have permission to link contacts)
?

**Comment by ghost** [comment]
closed - I will make a new PR when I have time and found a better solution for this problem.

**Pull request closed without merging**
