### PR TITLE
NEW: Option create pdf if no exist when merge pdf

### PR DESCRIPTION
**Pull request by olsesacl**
NEW: Option create pdf if no exist when merge pdf

### CODE REVIEW

**Comment by simnandez** [comment]
@olsesacl only source language (en_US) must be modified in git into develop branch, all others are translated into transifex

**Comment by olsesacl** [comment]
@simnandez delete translation es_ES

**Comment by eldy** [comment]
I am still thinking on this PR. May be we may add generation of non existing pdf done by default...

**Comment by olsesacl** [comment]
Do I change it by default to create the PDF if it does not exist?

**Pull request closed without merging**
