### PR TITLE
FIX : #19648 Change name order when creating a third party from a member

### PR DESCRIPTION
**Pull request by jocker132**
FIX : #19648 Change name order when creating a third party from a member

The update was conducted on the file adherents/card.php in order to send the last name then the first name to third party creation and avoid to have duplicates as requested in the issue

### CODE REVIEW

**Comment by daraelmin** [comment]
I think this should be an option (setup - other) not the default way.

**Comment by jocker132** [comment]
You are right i'll work on it

**Comment by jocker132** [comment]
Please @eldy how can i provide DML database script. IS there any migration scripts under dolibarr htdocs folder to use?
I want to add a parameter under llx_const table.

**Review by eldy — COMMENTED** [review]
There is already an option to decide the common order of firstname/lastname (into home - setup - display).
You can get the string using the getFullName() of object adherent (member) that should take this option into account.

**Comment by jocker132** [comment]
> There is already an option to decide the common order of firstname/lastname (into home - setup - display). You can get the string using the getFullName() of object adherent (member) that should takebthisboption into account.

So in this case we should close the issue and advise the user to change the settings from Home>>Setup>>Display since the actual code on 12.0 aleady calls getFullName.

image

**Comment by eldy** [comment]
Closed as requested

**Pull request closed without merging**
