### PR TITLE
FIX #4608 [Debian] Don't hard depend on mysql-server

### LINKED ISSUE #4608: Debian package wrong dependencies
The Debian/Ubuntu package depends of mysql-server AND mysql-client
mysql-server should not be required as the mysql server can be hosted on another system.
mysql-client is sufficient to access the database wherever it is.

Regards,
Nicolas.

### PR DESCRIPTION
**Pull request by rdoursenaud**
Allows using a separate MySQL server and switching to MariaDB.

### CODE REVIEW

**Comment by eldy** [comment]
What happened if and end user install the package on a new created debian with no package if mysql-server is moved from depends ?
In the past, for official debian package, this was also moved into Suggests, but this create feedbacks of users that fails to install the package among low level users.
What difference with Recommands, is it still install by default when on Recommands directive ?

**Comment by rdoursenaud** [comment]
Unlike suggested, recommended packages are automatically installed by apt-get and most front-ends. This should maintain the support requests low while allowing more advanced users to configure the package as they see fit without fiddling with a manual install.

Also, MariaDB will be the pulled database since it's now the default MySQL server provider.

Here's an extract from the [Debian Maintainer's guide](https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#control):

**Recommends**

_Use this for packages that are not strictly necessary but are typically used with your program. When a user installs your program, all front-ends will probably prompt them to install the recommended packages. aptitude and apt-get install recommended packages along with your package by default (but the user can disable this behavior). dpkg will ignore this field._

**Comment by eldy** [comment]
We are too nearest 4.0 final release for such change (seems to have a lot of side effect according to my test), i delay this PR for next release and make more test for next release.

**Comment by rdoursenaud** [comment]
Made PR against develop.

**Pull request closed without merging**
