### PR TITLE
Add table thead and tbody for object lines

### PR DESCRIPTION
**Pull request by john-botella**
Add table thead and tbody for object lines

### CODE REVIEW

**Comment by eldy** [comment]
What is goal of explicit thead tbody ?

**Comment by dolibarr95** [comment]
Hi !
it's useful when we use plugin or js to sort html table.
Instead of reload the full page with a new sql querie with get asc/desc argument, we could only use javascript.

example : https://datatables.net/examples/basic_init/table_sorting.html

**Comment by john-botella** [comment]
It's help some js plugins to limit action and weird behavior and it will be useful in future for some ergonomic behaviors integration in community.

it will be interesting to add explicit thead and tbody to standard lists too.

**Comment by dolibarr95** [comment]
:p 
https://github.com/Dolibarr/dolibarr/issues/6634

**Comment by john-botella** [comment]
For information, some browsers such as chrome, automatically add the tbody part if it does not exist.

**Pull request merged**
