### PR TITLE
New Use ajax switch into setup of TakePos

### PR DESCRIPTION
**Pull request by ptibogxiv**

### CODE REVIEW

**Comment by andreubisquerra** [comment]
Thank you ptibogxiv for changes.
But you deleted this lines:

print '<form action="'.$_SERVER["PHP_SELF"].'" method="post">';
print '<input type="hidden" name="token" value="'.$_SESSION['newtoken'].'">';
print '<input type="hidden" name="action" value="set">';

And now save button don't work. Can I add again this lines?

**Comment by ptibogxiv** [comment]
@andreubisquerra of course!

**Comment by andreubisquerra** [comment]
@ptibogxiv 
I'm reviewing the ajax code and I think it does not work correctly, because when you change a parameter you need to reload the page with more or less parameters. So I think the ajax on the TakePOS setup page is not suitable. What do you think?

**Comment by ptibogxiv** [comment]
@andreubisquerra with my fix i just harmonize code within all dolibarr's plugins. We can hide show additionnal parameter with a javascript hide/show code for this addtionnals ?

**Comment by andreubisquerra** [comment]
@ptibogxiv I think is easier without ajax, for example as invoice setup page. The problem now it simply does not work. When we have an ajax that works, we can commit.

**Comment by ptibogxiv** [comment]
i will work on this fix for javascript....

**Pull request merged**
