### PR TITLE
FIX: Update swiftmailer librairies

### PR DESCRIPTION
**Pull request by kkhelifa-opendsi**
FIX: Update swiftmailer librairies

### CODE REVIEW

**Comment by frederic34** [comment]
@kkhelifa-opendsi this is breaking support for php 5...
https://github.com/Dolibarr/dolibarr/blob/20f4b5389b00dec1807f32ca050651cc38b860e1/.travis.yml#L47

**Comment by philippe-opendsi** [comment]
@eldy 
This PR is a FIX. Office365 doesn't support anymore TLS 1.0 or 1.1 
So Dolibarr won't be able to send email anymore for people using swift library for all version of Dolibarr 12.x to develop
https://docs.microsoft.com/fr-fr/microsoft-365/compliance/tls-1.0-and-1.1-deprecation-for-office-365?view=o365-worldwide

**Comment by eldy** [comment]
The "swiftmailer" is not yet a released feature. It is still an experimental feature (not available in stable version).

**Comment by philippe-opendsi** [comment]
And on the develop branch ? This update will be still refused ?

**Comment by frederic34** [comment]
and something like that ?
image

**Comment by BebZ** [comment]
Are you trying to make bank services easier in Dolibarr, do you dare ?

Le lun. 13 déc. 2021 à 11:23, Frédéric FRANCE ***@***.***> a
écrit :

**Comment by philippe-opendsi** [comment]
@BebZ nothing to do with banking service :-) . Swift mailer is the name of one library uses by Dolibarr to send email.

**Comment by eldy** [comment]
> And on the develop branch ? This update will be still refused ?

Yes, PR is qualified for develop. As it changes an experimental feature never released publically, it is even qualified during a beta period becaude it is related to code not reachable into stable version (see https://wiki.dolibarr.org/index.php?title=Category:RoadMap#Freeze_definition)

**Comment by eldy** [comment]
> @kkhelifa-opendsi this is breaking support for php 5...
> 
> https://github.com/Dolibarr/dolibarr/blob/20f4b5389b00dec1807f32ca050651cc38b860e1/.travis.yml#L47

There is a test into admin page to enabled this driver only for php7
if (version_compare(phpversion(), '7.0', '>=')) {

and because, there is already another driver working for all version, this should not be a trouble.

**Pull request merged**
