### PR TITLE
NEW Use preselect third-party from list on new card

### PR DESCRIPTION
**Pull request by ghost**
# New
When you go to a list with a preselect third-party (like: proposal) and you click on the new button the preselect third-party is now used as third-party on the new card.

I have make this change on all lists (`list.php`) that implement `$socid = GETPOST(...)` to avoid different behavior in the long run.

Hope you like it.

## Background
A employee ask me why the  third-party was not preselect, because he was on the  third-party and have click on new. I was wondering why not, because that was working perfect before. But the problem was, we do this on different ways.

Me 
1. Go to a third-party
2. Click on "Customer" or "Vendor"
3. Click on one of the "green" **bottom** buttons (new proposal, new order, new invoice, ...)

But the customer haven't seen this buttons, because the preview list was to long, so the buttons was outside of his current screen.

So the employee go this way:
1. Go to a third-party
2. Click on "Customer" or "Vendor"
3. Click on one of the top summary buttons 
4. See a list with only things from the third-party
5. Click on new
6. Wondering why the third-party is empty

## Additional changes
I have change the different visibility of the buttons when you have no rights.
A hand of the buttons was always visible but disabled and a hand of was not visible.
Now the new buttons on the lists are always visible

## Picture (take the new way)

2020-09-18 12_15_05-Price request

## Picture (always visible)
2020-09-18 11_49_18-Third-party

### CODE REVIEW

**Comment by eldy** [comment]
Can you help me to solve conflict ?
I am not sure of what happen to the list when it is open from the POS (with contextpage = postlist)

**Comment by ghost** [comment]
> 
> 
> Can you help me to solve conflict ?
> I am not sure of what happen to the list when it is open from the POS (with contextpage = postlist)

Hello,

I haven't not use POS before,
but i think i can test this behavior until this week(end)

**Comment by ghost** [comment]
@eldy I have correct the visibility, when a user came from the Extended POS (`contextpage = postlist`) and I have add a few comments to the usage of it to make it easier to understand why elements on the pages are not visible, when `contextpage` is set to `postlist`

**Comment by eldy** [comment]
I like such PR (it saves click and standardizes code).
:+1:

**Pull request merged**
