### PR TITLE
Removed @ operator from dol_include_once

### PR DESCRIPTION
**Pull request by marcosgdf**
Adding @ operator to include_once makes include errors untraceable, it shouldn't be there. Errors must be thrown so that we notice them. It is PHP configuration's choice to decide wether to log them or print them.

### CODE REVIEW

**Comment by marcosgdf** [comment]
Build fails because of:

```
include_once(/home/travis/build/Dolibarr/dolibarr/htdocs/concatpdf/class/actions_concatpdf.class.php): failed to open stream: No such file or directory
```

But who calls concatpdf? I don't see it around the code

**Comment by eldy** [comment]
This is an example why we should keep the @.
If a module has been installed (and database table conf contains reference to it), and if module is removed (but not correctly), some includes may refer to not existing external module files. In such cases, this make dolibarr broken and unstable. An external module (even if not correctly installed or uninstalled) should not make dolibarr unstable or broken.
This is why we added the @. I did not find better solution. Try catch seems to not be enough. May be now that dolibarr min is 5.2, this may works...

**Comment by marcosgdf** [comment]
What about a file_exists check before including it?

The problem is that PHP no longer reports errors and include with @ acts like a "die" since some PHP version. I've wasted around 1 day checking what was breaking my Dolibarr installation and was a problem because of dol_include_once doing silence including, which prevented me from finding the problem.

**Comment by rdoursenaud** [comment]
I agree that silencing errors should be avoided while at the same time keeping Dolibarr stable.
Silencing errors does not seem to be the right way to achieve this. It's just hiding everything under the carpet. Let's find a better way.
file_exists() looks like a good compromise.

**Comment by marcosgdf** [comment]
```
PHP Fatal error:  Class 'mod_codeclient_monkey' not found in /home/travis/build/Dolibarr/dolibarr/htdocs/societe/class/societe.class.php on line 2174
```

These errors are now not part of this change

**Comment by marcosgdf** [comment]
Oh I see.

Corrected.

**Pull request merged**
