### PR TITLE
QUAL Clean DOM -> Hide empty box on dashboard

### PR DESCRIPTION
**Pull request by kevin-reo**
QUAL
Hide empty div.box on dashboard for clean DOM
Empty boxes cause bugs when parent is display as a CSS flex container

### CODE REVIEW

**Comment by eldy** [comment]
We can't remove the empty box. This is what we get if we remove them when the number of box does not match the number of columns:
image

Not that extra box has their own css so you can disable them if necessary by your module.

**Comment by kevin-reo** [comment]
Ok sorry @eldy , I have not test the IHM for this :/
Can I adjust theme css directly in Eldy theme folder for Fix this ?

**Comment by eldy** [comment]
If your change does not break any feature, you can suggest it.
But what bug do you want to fix. I do not experience trouble with current code

**Comment by kevin-reo** [comment]
@eldy, thanks for your answer. 
To answer you I do not have big trouble also, my aim is to optimise and clean the DOM and the layout for modernize IHM, maybe I can suggest new layout system for boxes. 

here is an exemple (you can resize your window for play with boxes)
https://codepen.io/KRIKRAK/full/XWOMpPY

**Pull request closed without merging**
