### PR TITLE
NEW : cron arguments might come from php CLI (argv vs getpost)

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by eldy** [comment]
The url htdocs/public/cron/cron_run_jobs.php is a public HTML page.
To call the cron from CLI, the file is available into   scripts/cron/cron_run_jobs.php

**Comment by altairis-tof** [comment]
thanks @eldy for this tip; i did not know about it. 
by the way what is the use case for this "public" script ?

**Comment by eldy** [comment]
Launching batch from a remote computer with a wget (when you don't have cli access to server, like on a lot of  mutualized servers) for example.
I commit a test and message to inform user of this.

**Comment by altairis-tof** [comment]
wow ! thanks

**Pull request closed without merging**
