### PR TITLE
user assigned must access to the event on edit

### PR DESCRIPTION
**Pull request by defrance**
authorid and userownerid is not enough 
and display on calendar is managed by userassigned

### CODE REVIEW

**Comment by eldy** [comment]
This is not compliant with standard sharing calendar rules.
When you create an event on your calendar (you are the owner), you can invite other people. Part of your calendar is shared in read only for them. The user invited can decided to refuse or say "i won't be present" or "i ignore" but this is a status of the assignment (that should be store into field "answer_status" and "transparency" defined by calendar protocol and already available into table llx_actioncomm_resource but not yet used/implemented).
If a user has permission to manage its own calendar, why giving him permission to change calendar of its colleague. It looks interesting because it allow non owner to complete data by providing more comment to event but i am shared between accepting this behaviour and not.
What are thinking other people:
- 1) Only owner can edit its event ?
- 2) or all invited/assigned users ?
- 3) or a permission to allow this ?
- or just an option to switch between 1 and 2 ?

**Comment by defrance** [comment]
Thank yo very much for your feedback on my request.
I am actually coping with a customer who is currently using google calendar, and would be delignhted to be able to use Dolibarr for his business : here is how they work :
Some users are dedicated to make phone calls and to try and fix appointments for the commercial agents of the company.
So the appointment’s creator will not assist to the appointment. He assigns the appointment to another user : the commercial agent.
The idea is that, we would highly appreciate if the commercial agent could have the right to modify the appointment that has been assigned to him…. But in the same time, we do  not want him to have access to the other commercial agents’ appointments…..

Today, it is not possible to use the Dolibarr rights management as it exists….
Wether we should consider that the assigned user as the same rights on an appointment, than the appointment’s owner OR it would require a modification of the existing right description and the creation of a new specfic right :

• Replace «  Créer/modifier les actions (événements ou tâches) liées à son compte» BY « Créer/modifier les actions (événements ou tâches) dont il est propriétaire » (which is more precise and closer to reality)
• Create « modifier les actions (événements ou tâches) qui lui sont assignées »

I hope that was clear enough, and i’d be glad to discuss the subject with you whenever you wish.

**Comment by fappels** [comment]
If we allow assigned editing (preferred option 3) there should be a notification system, so the owner gets informed the event is changed. It's better practice only the appointment creator manages the agenda.

**Comment by philippe-opendsi** [comment]
Hello
I agree with defrance. A notification system would be a "nice to have" :-)

**Comment by defrance** [comment]
SO what we do about it?

**Comment by eldy** [comment]
There is already a permission called
"Create/modify actions (events or tasks) of others"
So we should have a condition to edit event on this permission instead of a test on the fact i am assigned or not.

**Comment by eldy** [comment]
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Pull request closed without merging**
