### PR TITLE
NEW : Add category feature on Fichinter

### PR DESCRIPTION
**Pull request by defrance**
NEW : implement category feature on Fichinter
- create fichinter category
- apply category on fichinter
- filter fichinter list with category

### CODE REVIEW

**Comment by defrance** [comment]
@eldy  : please integrate it now

**Comment by eldy** [comment]
The pr was introduced during the beta freeze period of v19, so it was postponed because no change on databases ( that is not a fix) is allowed on a branch during the beta period.
So to have it merged in develop, thanks to update PR to be compatible with future version (using migration files of dev version)
Also when making addition in the database structure, as defined in the contributing.md file, thanks to publish any database addition into a separated PR.

**Comment by eldy** [comment]
It seems this PR was set with "Discussion" or "PR to fix" tag, but no answer nor correction was provided since a long time. So request is automatically closed.
Please reopened and add a comment if you think this is an error.

**Comment by defrance** [comment]
This is becoming completely STUPID:
I make a PR, I am asked for corrections that I make then they let my PR rot and I am told that it is too much and finally they close the PR
I made this new PR a month ago to get back on track piece by piece and no response...
https://github.com/Dolibarr/dolibarr/pull/31234

Are we going to wait another year and close it?

How can we be surprised then that no one is investing in the developments of dolibarr anymore?

It is a lack of respect for people of good will who want to integrate features.

**Pull request closed without merging**
