### PR TITLE
NEW: compute customer stats with virtual products

### PR DESCRIPTION
**Pull request by altairis-tof**
if the product is a component of a virtual product, we look at the virtual product stats to have correct component stats and correct virtual stock

### CODE REVIEW

**Comment by BebZ** [comment]
:+1:

**Comment by eldy** [comment]
This should be an option. A link on page that say "Include count of products that are component of a virtual product" because we don't always want to have them included.
Also, calculation is wrong. For exemple to get unique customer, you sum nb of parent with number of child. If it is same customer, you count it twice.
It seems also that you don't take care of qty of a product into a virtual product.

This must be suggested into dev as it should be a second calculation rule offered to user.

**Comment by eldy** [comment]
Duplicate PR #3316 looks more complete, so i close this one.

**Comment by altairis-tof** [comment]
1) PR #3316 seems to be less complete than mine since it only work on orders since mine work on proposals, orders, sendings, invoices and contracts ! 

2) qty is ok (sample: $this->stats_facture['qty']+=($prod->stats_facture['qty'] \* $parent['qty']);)

3) why do you think it should be an option ? we are talking here about the component stats not on the father ones.

4) i dont understand your point about the customer; we stats on usage in proposals, orders, etc 

please reopen, i think that you were too far in looking at this PR

**Pull request closed without merging**
