### PR TITLE
NEW : table llx_element_time to store time spent on several elements (mo, ticket...) SQL integration

### PR DESCRIPTION
**Pull request by atm-gauthier**

### CODE REVIEW

**Comment by atm-gauthier** [comment]
Hi @eldy, this PR deals with issue https://github.com/Dolibarr/dolibarr/issues/21548
This is the table we want to create, I await your opinion before starting work on the code and migration part of the current data

**Comment by eldy** [comment]
Why creating a second table that represent the same information than into llx_projet_task_time
It is better to extend existing llx_projet_task_time by adding the 

fk_element integer NOT NULL,
elementtype varchar(32) NOT NULL

with a default value to 'task'.
The name of table will not match real need llx_projet_task_time instead of llx_element_time, but it is better to have a bad name on a table than having 2 duplicates tables for the same purpose.

**Comment by atm-gauthier** [comment]
@eldy What i want to do is move data from llx_projet_task_time to llx_element_time and not keeping 2 tables.
Then i could add the 2 fields and rename the table, What do you think about that ?
(If you are OK with that please just say it to me and don't merge it now, i Will work on that feature and add all necessary code next weeks)

**Comment by atm-gauthier** [comment]
@eldy i did complete sql update.
Can you check it and say me if you're ok with that ?
If it's ok don't merge now, just say it to me and i will work on php code

**Comment by atm-gauthier** [comment]
Hi @eldy, this is the code integration PR : https://github.com/Dolibarr/dolibarr/pull/24158

**Comment by atm-gauthier** [comment]
travis error doesn't seem to deal with what i did :
image

**Comment by atm-gauthier** [comment]
I moved everything into https://github.com/Dolibarr/dolibarr/pull/24158

**Pull request closed without merging**
