### PR TITLE
Fix #16794 V13 order by status instead of statut

### LINKED ISSUE #16794: /comm/propal/list.php?leftmenu=propals Dolibarr has detected a technical error
```
Dolibarr has detected a technical error.
This information can be useful for diagnostic purposes (you can set option $dolibarr_main_prod to '1' to remove such notices):
Date: 20210318182036
Dolibarr: 13.0.2 - https://www.dolibarr.org
Level of features: 0
PHP: 7.1.33
Server: nginx/1.16.1
OS: Linux VM_0_5_centos 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3861.400 QQBrowser/10.7.4313.400

Requested URL: /comm/propal/list.php?leftmenu=propals
Referer: http://d.xxxx.com/commande/list.php?leftmenu=orders
Menu manager: eldy_menu.php

Modules/Applications: user, ficheinter, stripe, paypal, notification, multicurrency, clicktodial, skype, externalrss, geoipmaxmind, comptabilite, gravatar, api, ldap, cashdesk, mailmanspip, adherent, supplier_proposal, incoterm, dolitrackmail, webservices, ftp, export, import, workflow, bookmark, mailing, fckeditor, bom, emailcollector, categorie, barcode, cron, commande, don, ecm, externalsite, expensereport, facture, fournisseur, holiday, opensurvey, paybox, printing, resource, salaries, societe, service, ticket, takepos, mrp, variants, website, agenda, projet, modulebuilder, productbatch, stock, product, expedition, socialnetworks, oauth, blockedlog, banque, margin, propal, prelevement, loan, tax, contrat
Database type manager: mysqli
Latest database access request error: SELECT u.rowid, u.lastname, u.firstname, u.statut as status, u.login, u.photo, u.gender, u.entity, u.admin FROM llx_user as u WHERE u.entity IN (0,1) AND u.rowid = 8 AND u.fk_soc = 2 UNION SELECT u2.rowid, u2.lastname, u2.firstname, u2.statut as status, u2.login, u2.photo, u2.gender, u2.entity, u2.admin FROM llx_user as u2, llx_societe_commerciaux as sc WHERE u2.entity IN (0,1) AND u2.rowid = sc.fk_user AND sc.fk_soc=2 ORDER BY statut DESC, lastname ASC
Return code for latest database access request error: DB_ERROR_NOSUCHFIELD
Information for latest database access request error: Unknown column 'statut' in 'order clause'
```

This is the commercial page from customer account.
 Error shows from both pages: Commercial proposals and Sales Orders, but didn't show on any page when I use the administration account.
Can it be fixed? How?

### PR DESCRIPTION
**Pull request by daraelmin**
#Fix #16794 V13 order by status instead of statut

### CODE REVIEW

**Comment by daraelmin** [comment]
@eldy When a PR solves a specific issue, is it better to porpose the fix in the bugged branch (here the 13.0) or in the develop branch ?

**Comment by atm-maxime** [comment]
> @eldy When a PR solves a specific issue, is it better to porpose the fix in the bugged branch (here the 13.0) or in the develop branch ?

Fix must be done in the proper branch, max n-2 (currently 11). Afterwards, 11 is merged in 12, 12 in 13 and 13 in develop to propagate the fix. New feature must be in develop.

**Comment by daraelmin** [comment]
@atm-maxime thanks for answering.

**Comment by eldy** [comment]
I have a doubt on using the alias name to make the order by: Is this working correclty with postgresql ?

**Comment by daraelmin** [comment]
I dont know for select with union but in in simple select it is possible in postrgreSQL 
https://www.postgresql.org/docs/7.3/queries-order.html

**Comment by eldy** [comment]
Seems ok from postgresql 8.2 https://www.postgresql.org/docs/8.2/queries-order.html

**Pull request merged**
