### PR TITLE
NEW Takepos - Add labels to icons in Numpad

### PR DESCRIPTION
**Pull request by teleassist**
Added possibility to show icons labels of payment buttons in Numpad of Takepos

image

### CODE REVIEW

**Comment by eldy** [comment]
I don't think adding an option to have that is required. Why not doing it always by default
@andreubisquerra are you ok ?

**Comment by andreubisquerra** [comment]
Yes, I think it is better by default @eldy 
Thank you @teleassist

**Comment by eldy** [comment]
@teleassist Can you simplify the PR to add the icon and label by default with no need of a setup for that.

**Comment by teleassist** [comment]
@andreubisquerra  you're welcome !
@eldy it's done !

**Pull request merged**
