### PR TITLE
fix:replace batch name by link to batch object 

### PR DESCRIPTION
**Pull request by bafbes**
In order to change any created batch extrafield, this latter needs to be accessed immediately

### CODE REVIEW

**Comment by eldy** [comment]
I don't understand the goal of this. Is it to provide more data on screen ? Can you provide a screenshot ?

**Comment by bafbes** [comment]
It's just to show a link to the batch element instead of it's name as string. This is more useful if we need to change the value of the batch extrafield or simply to show its other data

**Comment by eldy** [comment]
I see. So the code is not good.
Can you have a look at this change that i have commited to address this and that looks better: cbd99ea7a2e77403cfffcd40700b794814d3132f

**Comment by bafbes** [comment]
Okay. i did not know this shortcut.

**Pull request closed without merging**
