### PR TITLE
Fix [ bug #1786 ] Spanish localtax2 calculation errors with corrective invoices

### PR DESCRIPTION
**Pull request by marcosgdf**
_:warning:  Build failure has nothing to do with my PR._

Because this is an important change I'm going to explain why did I do it:

Given a normal invoice:

| U.P. | VAT Rate | Localtax1 Rate | Localtax2 Rate | Total HT | Total VAT | Total Localtax1 | Total Localtax2 | Total TTC |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 3 | 21 % | 0 | 0 | 3 | 3 \* 0,21 = 0,63 | 0 | 0 | 3+0,21 = 3,63 |

Given a corrective invoice:

| U.P. | VAT Rate | Localtax1 Rate | Localtax2 Rate | Total HT | Total VAT | Total Localtax1 | Total Localtax2 | Total TTC |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| -3 | 21 % | 0 | 0 | 3 | -3 \* 0,21 = -0,63 | 0 | 0 | -3+-0,21 = -3,63 |

We don't need to alter total_vat, total_localtax, total_localtax2 or total_ttc because the calculations are correct.

`-abs(-3,63) = -3,63` => There's no need to do abs as the calculations are actually negative because of the negative P.U.

This alterations were forcing localtax2 to be always negative and that is not correct, as it depends on negative or positive P.U.

For example, in Spain we have a Localtax2 with a -21 % rate.

Before the changes:

| U.P. | VAT Rate | Localtax1 Rate | Localtax2 Rate | Total HT | Total VAT | Total Localtax1 | Total Localtax2 | Total TTC |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| -3 | 21 % | 0 | -21 % | 3 | -3 \* 0,21 = -0,63 | 0 | -3 \* -0,21 = 0,63 But -0,63 is shown | -3+0,63-0,63 = -3 <-- See this is incorrect as Dolibarr is showing total_localtax2 as -0,63 |

After my changes:

| U.P. | VAT Rate | Localtax1 Rate | Localtax2 Rate | Total HT | Total VAT | Total Localtax1 | Total Localtax2 | Total TTC |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| -3 | 21 % | 0 | -21 % | 3 | -3 \* 0,21 = -0,63 | 0 | -3 \* -0,21 = 0,63 | -3+-0,63+0,63 = -3 |

### CODE REVIEW

**Comment by simnandez** [comment]
we have to check that the lines are correct in database

**Comment by eldy** [comment]
Some tests like
$this->line->total_ttc          = (($this->type==2||$qty<0)?-abs($total_ttc):$total_ttc);
with the test on type and qty were introduced because method is used for both customer and supplier input i think. For customer, an credit not is defined by type. For supplier, with use the qty < 0 for the moment because credit not is not implemented on supplier invoice.
With your code change, what about this ?

Also because, changes on vat claculation is very citical, i would prefer to have first a unit test case into FactureTest.php and FactureFournisseurTest.php calling addline and updateline with an assert after a new fetch to show what we should get (so test should be ko if something is wrong)

**Comment by marcosgdf** [comment]
It will stay the same because a negative UP will lead to a negative VAT, HT and so and a Positive UP will lead to a positive VAT, HT and so.

I did not modify the check for UP. See that I only modify the check in the total calculation so the result will remain the same.

I'll see if I can make a test.

**Comment by marcosgdf** [comment]
I'm affraid unit test cannot be made as this function interacts with DB.

**Comment by eldy** [comment]
This is not a problem. Most unit tests interact with the DB. I can manage this, at least can you put it by just adding a "text comment desbribing example of entries and what we expect into database for such examples". 
There is a lot of change into management of localtax, when never, I knew what was expected result for a particular data entry. We must first share what we expect as data into database for a given entry value, company customer and supplier properties.
I really need to have a defined example of what we should have as result to ensure everybody is ok with this specification. Then i would be able to validate commit changes on this because i would be able to check if it breaks or not expected result.

**Comment by marcosgdf** [comment]
Do you want me to insert the text comment here or in the code?

Here it is:

Given:
- Total_ht: -10 €
- Localtax2 rate: -21 %

Expected result is:
- Total_localtax2: 2,1
- Total_ttc: -7,9

## 

Given:
- Total_ht: -10 €
- Localtax2 rate: -21 %

Expected result is:
- Total_localtax2: -2,1
- Total_ttc: -12,1

**Comment by eldy** [comment]
Yes into comment of method testGetDefaultLocalTax of file
FunctionLibTest.php

2015-03-05 10:28 GMT+01:00 Marcos García notifications@github.com:

**Comment by marcosgdf** [comment]
Even if this has nothing to do with getdefaultlocaltax?

**Comment by marcosgdf** [comment]
Pushing into develop branch

**Pull request closed without merging**
