### PR TITLE
New: receipt beep alternative and current date/time

### PR DESCRIPTION
**Pull request by johnvan7**
**#New: Beep alternative ESC/POS command**
Added DOL_BEEP_ALTERNATIVE to activate the buzzer in using alternative command.

**#New: Print current date/time on the receipt**
Added DOL_PRINT_CURR_DATE (string template) to print the current date and/or time on the receipt.

### CODE REVIEW

**Comment by andreubisquerra** [comment]
First of all thank you for your PR @johnvan7 
I tried your code and:

In first tag DOL_BEEP_ALTERNATIVE are you tried with some printer? If yes what printer?

In second tag I tried and don't print the date. The code only print the text after the tag, no date. And the current tag dol_value_date works good

Thank you for answer me

**Comment by johnvan7** [comment]
Thanks for your reply!

In first tag _DOL_BEEP_ALTERNATIVE_, I've tested on my printers: Excelvan ESC/POS 80mm. I've found the command [here ](https://github.com/mike42/escpos-php/issues/142#issuecomment-231601204) (mike42/escpos-php's issue).

In second tag: I tried the dol_print_date_time tag and it always prints the time "00:00" (I'm testing dolibarr on Windows).
To test the second tag: _{dol_print_curr_date}d/m/Y H:i:s_ (works for me)

**Comment by andreubisquerra** [comment]
Good job @johnvan7 
Do you think it is a good idea to add a default format? Because it can create confusion and users may not know to add the date format. We could add this code:

case 'DOL_PRINT_CURR_DATE':
     **if (strlen($vals[$tplline]['value'])<2)** $this->printer->text(date('d/m/Y H:i:s')."\n");
     else $this->printer->text(date($vals[$tplline]['value'])."\n");
     break;

Thank you for your work

**Comment by johnvan7** [comment]
Yes of course, I've added it.

**Comment by eldy** [comment]
@andreubisquerra is this PR ok for you to be merged in its last version ?

**Comment by andreubisquerra** [comment]
Aproved!

**Pull request merged**
