### PR TITLE
NEW : add constant PROPAL_DONT_KEEP_INTERNAL_CONTACTS_ON_CLONING

### PR DESCRIPTION
**Pull request by altairis-tof**
add new constant to not copy internal contacts when cloning a proposal

### CODE REVIEW

**Comment by eldy** [comment]
When we make a cloning, a confirmation popup is shown. On some other features, you can check option of what you clone on not in this popup. I would prefer to have this feature managed this way (with a checkbox "Clone also contacts") instead of having a hidden constant for that.

**Comment by altairis-tof** [comment]
@eldy i am not sure that people that clone 50 proposals or more per day will appreciate to have to think about checking or unchecking the options at each time.
and furthermore i do not think their boss will appreciate that they can check or uncheck options that he decided for the company workflow.

**Comment by eldy** [comment]
They won't have. the checkbox can be automatically set or not according to an option. But users keep choice and must not go into the admin setup if he want to change the behaviour for one particular case.

**Comment by altairis-tof** [comment]
@altairis-benjamin thanks to look at this one and to check if it is not already coded in recent releases and develop branch. same here #18329 for orders and #18321 for shippings

**Comment by eldy** [comment]
For gui consistency with other object and options on cloning, this must be implemented by suggested a checkbox in the confirm popup. A hidden option can exist to have the checkbox pre-selected or not.

**Pull request closed without merging**
