### PR TITLE
feature : Add html label tag for product page in creation mode

### PR DESCRIPTION
**Pull request by dolibarr95**
# New *Add label tag for creation mode*
*If it generates bugs or conflicts (with Javascript or other functions) we should prefix the new 'id' and 'for' attributes.*

### CODE REVIEW

**Comment by eldy** [comment]
What is the goal of this change ? Bug fix of feature ?

**Comment by dolibarr95** [comment]
Hi
I've edit the title to feature. Having a label for each input could be nice (accessibility, user experience, etc), i think.
Tks

**Comment by eldy** [comment]
To address this in the past, we introduced a new way of coding like this

            // Supplier
            print '<tr>';
            print '<td>'.fieldLabel('Supplier','fournisseur',1).'</td><td>';

But we abandoned it because it is not enough for future. So now we try to write forms like this, for forms in read mode:

			// Label
			print '<tr><td class="tdtop">';
			print $form->editfieldkey("Label", 'label', $object->label, $object, $conf->global->MAIN_EDIT_ALSO_INLINE, 'alpha:32');
			print '</td><td colspan="2">';
			print $form->editfieldval("Label", 'label', $object->label, $object, $conf->global->MAIN_EDIT_ALSO_INLINE, 'alpha:32');
			print "</td></tr>";

But i planned to introduce same thing for edit mode, and a rewrite on how forms works in "edit" mode is planned and accesssibility would be a part of this new architecture. Bu for the moment, don't spend too much time on such change, because they will be deprecated with the new architecture to generated form in edit mode...

**Comment by dolibarr95** [comment]
Hi
tks for reading. 
It's perfect if you have planned something about this. So i will wait and use it when it will be ready.

Tks

**Pull request closed without merging**
