### PR TITLE
remove stock data from getsupplierprice

### PR DESCRIPTION
**Pull request by frederic34**
stock data can be retrieved with get

it complete this commit https://github.com/Dolibarr/dolibarr/commit/b895f8a78f4d03b5c6acbc0c785d79e260dc166b

### CODE REVIEW

**Comment by frederic34** [comment]
@fappels @ptibogxiv

**Comment by eldy** [comment]
There is one difference. The get return stock for 1 product, where the getsupplierprice can retreive stock of all products provided by a supplier. It may be usefull to develop external replenishment tool. It avoid to make 100 get if the supplier provided 100 products. Am i wrong ?

**Comment by frederic34** [comment]
@eldy it **Get purchase prices for a product** not many

**Comment by fappels** [comment]
Think load_stock is there by accident.

**Pull request merged**
