### PR TITLE
Fix : proposal validation was converting third as customer

### PR DESCRIPTION
**Pull request by atm-maxime**
I don't know if this is expected behaviour, but validating a proposal should not convert the thirs as customer. Only closing it as signed should do it. As long as the third has not signed the proposal it's not a customer, it's still a prospect. What do you think ?

### CODE REVIEW

**Comment by rdoursenaud** [comment]
I agree with you!

**Comment by bouna** [comment]
and me also !

_--------------------------------------------------------_

_SIDI YOUSSEF Mohamed Mahmoud_
_Consultant ERP/CRM_

_Ingénieur en Informatique_

_Ingénieur en Télécommunications_

_Mobile| +33 6 25 02 78 45 sidi.yousf@gmail.com sidi.yousf@gmail.com_

http://www.linkedin.com/profile/view?id=227599456&trk=nav_responsive_tab_profile_pic
http://www.linkedin.com/profile/view?id=227599456&trk=nav_responsive_tab_profile_pic
[image: http://www.viadeo.com/profile/0021nqcjsz8ecm7q#]http://www.viadeo.com/profile/0021nqcjsz8ecm7q#
         [image:
http://www.linkedin.com/profile/view?id=227599456&trk=nav_responsive_tab_profile]http://www.linkedin.com/profile/view?id=227599456&trk=nav_responsive_tab_profile

2014-04-23 18:26 GMT+02:00 Raphaël Doursenaud notifications@github.com:

**Comment by eldy** [comment]
I agree to.
I see the removal of code that set prospect as customer, but does the code to set it as customer when proposal is signed is present ?

**Comment by atm-maxime** [comment]
Yes, the same function is called in the cloture() function. Only if signed.

**Pull request merged**
