### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rdoursenaud**
Again, sorry for the messy commit history.
Relevant commits are 2808303 and 46c2985

These ensure that all served text files (such as PHP or JS code) are in UTF-8 without BOM.
This hopefully prevents from misbehavior in server/client interaction with some environments.

Thanks !

### CODE REVIEW

**Comment by hregis** [comment]
for commit 46c2985
this files are already in utf8 !

**Comment by rdoursenaud** [comment]
Strange, I just checked and they are ISO-8859-1 here...

**Comment by hregis** [comment]
All that is in the "includes" are external libraries that can be overwritten by the update of these libraries

**Comment by rdoursenaud** [comment]
Yeah, I know that. I planned to also report upstream.
But can you confirm that the files weren't UTF-8 in the first place ?

**Comment by rdoursenaud** [comment]
Ok I'll provide it soon. In the meantime I close this one.

**Pull request closed without merging**
