### PR TITLE
FIX - Add condition to delete product

### PR DESCRIPTION
**Pull request by atm-lucasmantegari**
# FIX - *Add condition to delete product*
We can currently delete a product even though it is in a BOM.
Adding this check helps avoid an SQL error when using this product on a OF.

### CODE REVIEW

**Comment by atm-lucasmantegari** [comment]
@eldy I think Travis has a bug. If not, please explain to me

**Comment by atm-lucasmantegari** [comment]
@eldy

**Comment by eldy** [comment]
> @eldy 

See my first comment..

**Comment by fappels** [comment]
See https://github.com/Dolibarr/dolibarr/pull/30140/commits/f401ad5e9bcd9658b2a4ada71557dff4a303e013
Is for MO, also BOM need to be added.

**Comment by atm-lucasmantegari** [comment]
@eldy its better like this ?

**Comment by eldy** [comment]
> @eldy its better like this ?

Seems better. But have cti errors

**Pull request closed without merging**
