### PR TITLE
NEW : Workstations management

### PR DESCRIPTION
**Pull request by atm-gauthier**
NEW :
- Workstations management
- Add multiselect on resources

### CODE REVIEW

**Comment by atm-gauthier** [comment]
@eldy Travis is wrong, it displays "Found string $db-> into a .class.php file in workstation/class/workstationresource.class.php" but i'm in a static method and i have to create an instance of object in the function, then it's not possible to use $this->db

**Comment by eldy** [comment]
Why using 2 static classes for getAllResourcesOfWorkstation and delete...
It seems this 2 methods can also be used as common methods (they themself make instanciation inside code). This allows to make code similar to other parts.

**Comment by atm-gauthier** [comment]
@eldy i moved my methods in common object, they are now generic functions for them to be usable later

**Comment by atm-gauthier** [comment]
@eldy is everything ok for you ?

**Pull request merged**
