### PR TITLE
NEW: #5830 Allow Generic E-mail Sender 

### PR DESCRIPTION
**Pull request by olsesacl**
select_email

### CODE REVIEW

**Comment by olsesacl** [comment]
Add config email to be used by default (User / Company)
default

**Comment by BebZ** [comment]
@guerrierk 
the end of dolimail ? 
NO...

**Comment by guerrierk** [comment]
@BebZ 
No, why ? I continue the module as DolImapMail because there are some lines in the Dolibarr core that are executed when the module 'dolimail' is installed (specially when user send a mail from a thirdparty card) and throw a fatal error. I mentionned it on the Forum (http://www.dolibarr.fr/forum/509-webmails/25441-comment-recevoir-des-e-mails-dans-dolibarr?start=375#75378).
Thanks to share your ideas, comments, bug ... about this module and its functionality. ;-)

**Comment by eldy** [comment]
Great. Can you resubmit your PR on the develop branch, because 4.0 is a stable version and does not accept new features.

**Comment by aljawaid** [comment]
@eldy which version will this be merged to?  I am on 4.0.1.  Or is it quicker to just copy the affected files and replace the current ones?

**Comment by olsesacl** [comment]
Change base develop

**Pull request closed without merging**
