### PR TITLE
New: Overload styles files from a current folder of module & theme

### PR DESCRIPTION
**Pull request by wdammak**
My goal is to overload css files only for the current module and without changing the source code of the module but just by adding a folder style in the module folder. Then just place the css files to overload in this folder they will be automatically added in the head.

The same method is applied to the current theme.

Ex. place a custom.css file in the societe/style/custom.css folder and check the head of a company module page.

### CODE REVIEW

**Comment by wdammak** [comment]
Up

**Comment by wdammak** [comment]
What are the reasons for not validating this request?

**Comment by eldy** [comment]
For integrity reason, adding files into core directories must be discouraged.
If a user want to change a behaviour by adding modules or new files, this must be done by adding files into directory "custom/..." (don't forget that on a correct installation of Dolibarr, all directories are set to readonly by the integrator, only "custom" and "documents" are writable.

With v10 (into develop branch), there is a new hook called "addHtmlHeader" that allow a module to interact with the hml header so you can add your own css depending on ny conditions of your choice.

**Comment by wdammak** [comment]
We can adapt this overloading mechanism so that the files are placed in the custom folder
/custom/module_name/style/custom.css

the goal is to simplify the relook of modules and customize them easily without touching a line of php code
As u like...

**Comment by hregis** [comment]
@wdammak @eldy 
you can already customize the css by adding your css file in your module in order to overload:
`/mymodule/css/mymodule.css.php`
and declare this in your "/mymodule/core/modules/modMymodule.class.php"
```
$this->module_parts = array(
	'css' => array(
		'data' => '/mymodule/css/mymodule.css.php',
		'entity' => '0'  // for all entities
	)
);
```

or you can add your own theme in "/mymodule/theme/mytheme"
and declare this in your "/mymodule/core/modules/modMymodule.class.php" : 
```
$this->module_parts = array(
	'theme' => array( '/mymodule/theme/mytheme')
);

```
or for your own module page, add specific css for your page with llxHeader():

```
$moreheadcss='hard coded css...';
$moreheadjs='hard coded js...';
and/or
$arrayofjs=array('/mymodule/js/mymodule.js.php'); 
$arrayofcss=array('/mymodule/css/mymodule.css.php'); 

llxHeader($moreheadcss.$moreheadjs,$langs->trans("MyModule"),'','','','',$arrayofjs, $arrayofcss);
```

**Comment by wdammak** [comment]
@hregis
Ok it's technical, we can also use the current header function.
But as you just mentioned, we must add the declaration of the theme or style in the module code.
My proposal, it dolibarr automatically overload the css or theme files in a corner by following a specific path. In this way, the user doesn't care about the evolution of the module and isn't obliged to make the changes each time.
A graphic designer/webmaster, can easily relook the interface just editing a css file.

This mechanism is used everywhere ...

**Comment by hregis** [comment]
@wdammak 
yes but, if there is another module that wants to overwrite the css we do how? :-)
who will be a priority?

**Comment by wdammak** [comment]
@hregis The priority is always what the user wants to see. :)
And in these cases, the user only has to edit his css files. And if he wants to see the default behavior, he renames the file with another extension or deletes it momentarily.

**Comment by wdammak** [comment]
new version : Group override css files in the custom folder

**Comment by eldy** [comment]
I understand the goal of the enhancement you suggest: Being able to use your own css without declaration.
But being able to do this need, as you did in your code, to make full scan of directories to find overwritting rules. And this is something we don't want because scanning at each php page call some directories to search for files require a lot of IO, even if there is no overlapping CSS, making useless bottleneck on server (IO is the weakest link compared to CPU).
Also, the title of your PR is "from a current folder of module & theme". This means you have a module.
In such a case, there is already a module, so it is easy just to declare that you have your own css using the solution provided by regis (thanks for mentionning this @hregis). it is just one line of code to add in your module and it save tons of IO that would be done for all users in the world even if they don't have the module that need the code. So the benefit does not worth the disadvantage

**Pull request closed without merging**
