### PR TITLE
FIX: bypass the load() function only if the file is loaded

### PR DESCRIPTION
**Pull request by kkhelifa-opendsi**
for the case of the cron the file 'my_module' is tested first and 'my_module@my_module' is tested after, or the file is already considered loaded for a file language from a custom module ...

### CODE REVIEW

**Comment by eldy** [comment]
Do you mean you use a lang file in your module called
aaa@mymodule where "aaa" is a key of an existing lang file into core ?

**Comment by kkhelifa-opendsi** [comment]
no it's if the module file is called
it is considered loaded even if the file has not been found considering it a core file
> 			// Load langs
> 			if (!$error)
> 			{
> 				$result = $langs->load($this->module_name);
> 				$result = $langs->load($this->module_name.'@'.$this->module_name); // If this->module_name was an existing language file, this will make nothing
> 				if ($result < 0)	// If technical error
> 				{
> 					dol_syslog(get_class($this)."::run_jobs Cannot load module lang file - ".$langs->error, LOG_ERR);
> 					$this->error = $langs->error;
> 					$this->lastoutput = $this->error;
> 					$this->lastresult = -1;
> 	                $retval = $this->lastresult;
> 	                $error++;
> 				}
> 			}
>

**Comment by philippe-opendsi** [comment]
Hello
ping @eldy Your question has been answered

**Comment by eldy** [comment]
Sorry i can't reproduce the trouble.

If value is 2 (so it means we already tried to load the file and we didn't not find it), we must no try again. There is no reason to try to load if value is 1 ONLY. 
1 and 2 (and also 3) are the value to say "already loaded", do not waste time to do it again
And value is (should be) set to 2 only if module was not find into core AND not find as external module. Making the suggested change create overload when it is not necessary. So i think trouble is somewhere else.

I think problem is in the portion of code you mention in your last comment, 
```
        // Load langs
  	if (!$error)
  	{
  		$result = $langs->load($this->module_name);
  		$result = $langs->load($this->module_name.'@'.$this->module_name); // If this->module_name was an existing language file, this will make nothing
  		if ($result < 0)	// If technical error
  		{
  			dol_syslog(get_class($this)."::run_jobs Cannot load module lang file - ".$langs->error, LOG_ERR);
  			$this->error = $langs->error;
  			$this->lastoutput = $this->error;
  			$this->lastresult = -1;
              $retval = $this->lastresult;
              $error++;
  		}
  	}
```

What do you have for $result (for the 2 call when $this->module_name is the name of your module) ?

**Pull request closed without merging**
