### PR TITLE
New Add a workflow to let @lvessiller-opendsi and @rycks merge 18.0 PR by accepting reviews

### PR DESCRIPTION
**Pull request by fcharlaix-opendsi**
The workflow only run on PR targeting the `18.0` branch, it adds @lvessiller-opendsi and @rycks as assignee and reviewer.

Combine with the ruleset below and allowing auto merge on this repo, the PR will auto merge once all requirements are met.

This ruleset make two approved review a requirement for all PR on 18.0 (excepted for repo admin) :
```yaml
{
  "id": 2630207,
  "name": "18",
  "target": "branch",
  "source_type": "Repository",
  "source": "fcharlaix-opendsi/dolibarr",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "exclude": [],
      "include": [
        "refs/heads/18.0"
      ]
    }
  },
  "rules": [
    {
      "type": "deletion"
    },
    {
      "type": "non_fast_forward"
    },
    {
      "type": "pull_request",
      "parameters": {
        "required_approving_review_count": 2,
        "dismiss_stale_reviews_on_push": true,
        "require_code_owner_review": false,
        "require_last_push_approval": false,
        "required_review_thread_resolution": true,
        "automatic_copilot_code_review_enabled": false
      }
    }
  ],
  "bypass_actors": [
    {
      "actor_id": 5,
      "actor_type": "RepositoryRole",
      "bypass_mode": "always"
    }
  ]
}
```

### CODE REVIEW

**Comment by frederic34** [comment]
this action tries to clean the phpstan baseline, but I can get github token
https://github.com/Dolibarr/dolibarr/actions/workflows/phpstan_baseline.yml
Is it desactivated in repo settings ?

**Comment by eldy** [comment]
> this action tries to clean the phpstan baseline, but I can get github token
@frederic34 
What do you mean with "this action tries to clean the phpstan baseline, but I can get github token" ?

**Comment by frederic34** [comment]
@eldy https://github.com/Dolibarr/dolibarr/pull/31931

**Comment by eldy** [comment]
> @eldy https://github.com/Dolibarr/dolibarr/pull/31931

31931 is related to phpstan_baseline.xml action. But this pr is related to another action to auto assign 2 users on any pr on branch v18.
The 31931 has a pb to get token (but i don't know why), but i don't see the relation whis this pr #31898 that is in branch 18.
Did i miss something ?

**Pull request merged**
