### PR TITLE
Need to make some alterations on inpayees

### PR DESCRIPTION
**Pull request by Shozuke**
Need to make some changes on "dolibarr\htdocs\compta".

I've created on custom field that i need to be visible on the list, how can i get it? My biggest problem here is that i don't know where was sent to the database and also how do I call it on php.

Thanks

### CODE REVIEW

**Comment by aspangaro** [comment]
Compared 3.1 to develop ?

**Comment by Shozuke** [comment]
yes, on 3.1 aspangaro

**Comment by marcosgdf** [comment]
This PR is so weird. Why are you comparing 3.1 to develop?

**Comment by rdoursenaud** [comment]
@Shozuke Please use the mailing list or the forum to discuss development issues, not pull requests.

**Comment by Shozuke** [comment]
@rdoursenaud I can't find the mailing list, and don't seem to be able to log in on the forum, that was why I've came here.

**Comment by rdoursenaud** [comment]
@Shozuke 
That's what I understood ;)
The international forum registration is indeed broken. A whole new version of the site is to be deployed but I don't have an ETA. Sorry.
Your best bet is the dolibarr-dev mailing list at https://savannah.nongnu.org/mail/?group=dolibarr

**Comment by rdoursenaud** [comment]
Oh and if I understand your original question correctly, the information you're looking for is there: http://wiki.dolibarr.org/index.php/Extrafields

**Comment by eldy** [comment]
PR Pushed on a very too old version. No more maintenance is provided for such old version.

**Pull request closed without merging**
