### PR TITLE
Updates and additions to VAT reports

### PR DESCRIPTION
**Pull request by ywarnier**
Added htdocs/compta/tva/quarter_report.php and finetunes clients.php and quadri_detail.php (+ required libraries)

### CODE REVIEW

**Comment by rdoursenaud** [comment]
@ywarnier IMHO It does not matter what market the commit is for.
English is standard so all developers can understand them if need be. (While chasing a bug, bissecting or rebasing for example.)

**Comment by rdoursenaud** [comment]
Also, changes to language files other than en_US should be submitted at transifex, not pull requests.
Even if merged, these will be lost at the next transifex sync.
Please see: http://wiki.dolibarr.org/index.php/Translator_documentation

**Comment by ywarnier** [comment]
Thanks for the translation link, I had overlooked this one (it's new to me and it's great).
I'll re-commit my change with a comment in English (this was originally a mistake but when thinking about it, I thought it didn't matter much because of the market).

**Comment by ywarnier** [comment]
Note that, talking about wiki on translations, I found the following down the bottom of the page you mentioned:
`If the translation was made on files directly (it should be the case for en_US), it is possible to integrate using the GIT system. To do this, create an account on http://www.github.com, fork the project, edit the relevant files and send a Pull Request.`
This leaves the translations to other stuff than en_US a bit unclear... (it doesn't say that non-en_US _MUST_ be sent through Transifex)

**Comment by rdoursenaud** [comment]
@ywarnier Yes, less than optimal wording.

Rule of thumb:
- en_US: Source code
- everything else: Transifex

Feel free to update the wiki accordingly ;)

**Comment by ywarnier** [comment]
Wiki updated

**Comment by rdoursenaud** [comment]
Great \o/
Thanks!

**Pull request closed without merging**
