### PR TITLE
Add payment mode in invoice list

### PR DESCRIPTION
**Pull request by atm-maxime**

### CODE REVIEW

**Comment by rdoursenaud** [comment]
This may be useful in the unpaid invoices list because we're waiting for a payment.
But I don't think it's wise in the general invoices list because they could be paid by another means. This will confuse users on whether it is the actual payment method or the one requested on the document.

**Comment by atm-maxime** [comment]
I agree, so we should have very good trainers to explain the difference :)
This was asked on the french forum and I think this can be useful if you want to display all your invoices waiting for an automated bank debit, or invoices that you have to transfer to a specific organism with whom you do factoring, or invoices that need a bill of exchange document...

**Comment by rdoursenaud** [comment]
Simply changing impayees.php and not touching list.php seem to fit your use case while keeping confusion away.

**Comment by atm-maxime** [comment]
;)

**Pull request merged**
