### PR TITLE
Warning on proposal home pages

### PR DESCRIPTION
**Pull request by atm-maxime**
On comm homepage, $now was defined twice.
On comm/propal homepage, $now was not defined and proposal date used to display warning instead of end validity date

### CODE REVIEW

**Comment by atm-maxime** [comment]
The warning on proposal is defined related to the proposal date and the delay was 31 days by default. The point of this warning is to alert on proposal still opened after 31 days, isn't it ? Is it better to have the alert like this or something like 5 days before the end validity date ? I made this 2 modifications to have the alert based on the end validity date and we should define a negative warning delay to have the 2nd type of warning. Which one do you think is better ?

**Comment by atm-maxime** [comment]
Can we imagine adding a new alert type base on the end validity date of the proposal, and which will be something like "# of proposal near end validity" ?

**Comment by eldy** [comment]
I confirm the "warning" meaning "late" must be done on date of end of validity.
A negative value if we want to be warn before the end of validity is for me the good solution. Does your patch was desgined to match this rule ?

**Comment by atm-maxime** [comment]
Yes this patch replace the proposal date by the end validity date for the warning calculation. Plus an error in the import process I noticed.

**Pull request merged**
