### PR TITLE
Contining task 172

### PR DESCRIPTION
**Pull request by FHenry**
Add column   fk_c_element_role  into llx_actioncomm_ressource to manage
role of linked element
As exemple we can have 
fk_element = 1
element_type= "user" or contact or place or whatever element
fk_c_element_role = 1 // 'Guest' or Host or whatever define in
dictionnary
fk_c_element_status = Present // or whatever define in dictionnary
according element type

### CODE REVIEW

**Comment by eldy** [comment]
I didn't understood meaning of fields
fk_c_element_role and fk_c_element_status 
can you provide an example with real values ?

Also, you can add field 
- "transparent" into table resrouce (this is a field into standard protocol of task assignement to tell if event make resource assigned busy or not). May be this is what you called "fk_c_element_role". However this should not be a field whose name start with "fk_c_" because it is not a field with value defined by user but defined by calendar management protocol (a good reference to know what we must manage and not is to see feature of google calendar that match vcal and calendar standard correctly. "transparent" is offical name into standard).
- "mandatory" into table resource (this is another field required by calendar protocol) to tell if an invitation is "mandatory" or "option". May be this is what you called fk_c_ekement_status ? However this should not be a field whose name start with "fk_c_" because it is not a field with value defined by user but defined by calendar management protocol (a good reference to know what we must manage and not is to see feature of google calendar that match vcal and calendard standard correctly)..

**Comment by FHenry** [comment]
What i'm thinking about is someting like 
fk_element = 
rowid of llx_contact or user or whatever

=>  Agree

element_type= 
table_element (or element) of dolibarr object

=> Agree

fk_c_element_role =
can be  Guest or Host (for a person contact/user) 
or indoor or outdoor or virtual conférence (for the future location/place module) 
or Full HD or Old Model (for the video projecteur)
or whatever define in new dictionnary llx_c_actioncomm_role (not created yet)

=> Examples your provide are not exclusive and using a field of type fk_c_element_role must be exclusive since you can have only once choice (what if you want to tell "invitation is full hd + indoor). It seems example you provide are property of a resource (room, hardware), so should be in the table that will manage the resource (and that should not be a dictionnary table but a full table in a new module). I still dont think this property is a prperty of the "link" (llx_actioncommresource is a table to link so only properties specific to the link and not to element linked must appears. 

fk_c_element_status = 
Present or Late or Missing whatever define in dictionnary according element type 

=> For invitation, this is goal of field "transparent" field, but you are right, we need it for answer. However, this must not be a foreign key field but just a status field so with a name "response_status". This field can't be opened by a dictionnary list of values, because it is also a field normalized by calendar protocol. So i suggest to name it answer_status because i don't know official name.

I use fk_c_ field because to my mind it will be populate with value define into dictionnay and it seems to be a rule to use fk_c_ prefix for dictionnay foreign key.

But none of those field will do the feature transparent. 
Mandatory can be fk_c_element_status but I wonder if it not better to add the two field. One is to prepare the event (mandatory) and  fk_c_element_status is to say if every ressource were effectivly present (usefull for commercial prospection)

=> Yes, you're right, we need two field, but i suggest "answer_status" instead of a link to dictionnary table. Having opened value here will make us not possible to interface with system that manage this fied according to calendard standard.

**Comment by eldy** [comment]
Oops, i tried to answer with => into your own answer. I paste it again because i am not sure it was saved:

What i'm thinking about is someting like 
fk_element = 
rowid of llx_contact or user or whatever

=> Agree

element_type= 
table_element (or element) of dolibarr object

=> Agree

fk_c_element_role =
can be Guest or Host (for a person contact/user) 
or indoor or outdoor or virtual conférence (for the future location/place module) 
or Full HD or Old Model (for the video projecteur)
or whatever define in new dictionnary llx_c_actioncomm_role (not created yet)

=> Examples your provide are not exclusive and using a field of type fk_c_element_role must be exclusive since you can have only once choice (what if you want to tell "invitation is full hd + indoor). It seems example you provide are property of a resource (room, hardware), so should be in the table that will manage the resource (and that should not be a dictionnary table but a full table in a new module). I still dont think this property is a prperty of the "link" (llx_actioncommresource is a table to link so only properties specific to the link and not to element linked must appears.

fk_c_element_status = 
Present or Late or Missing whatever define in dictionnary according element type

=> For invitation, this is goal of field "transparent" field, but you are right, we need it for answer. However, this must not be a foreign key field but just a status field so with a name "response_status". This field can't be opened by a dictionnary list of values, because it is also a field normalized by calendar protocol. So i suggest to name it answer_status because i don't know official name.

I use fk_c_ field because to my mind it will be populate with value define into dictionnay and it seems to be a rule to use fk_c_ prefix for dictionnay foreign key.

But none of those field will do the feature transparent. 
Mandatory can be fk_c_element_status but I wonder if it not better to add the two field. One is to prepare the event (mandatory) and fk_c_element_status is to say if every ressource were effectivly present (usefull for commercial prospection)

=> Yes, you're right, we need two field, but i suggest "answer_status" instead of a link to dictionnary table. Having opened value here will make us not possible to interface with system that manage this fied according to calendard standard

**Comment by FHenry** [comment]
I remove fk_c_element_role and rename fk_c_element_status into answer status, But in this strucure I still wonder how do you define if a contact or user assign to an event is guest or host ?

**Comment by eldy** [comment]
For what need to you need "guest or host" ?
In standard calendar, an event has an owner. The "owner" is i think what you call the "host".
This field is "fk_user_action". It is stored into table llx_actioncomm because in calendar protocol, you can have only one "owner" per event. If we can have several owner, i agree, we should put this into this link table but it seems you can have only one. The feature suggested by google is to transfer ownership but not to add a second owner. 
So we can keep field in table llx_actioncomm.
Is this "owner" what you think when you say "host" ?

**Comment by FHenry** [comment]
Yes this is exactly what i'm thinking about. Again a wording issue. And you answer very well, transfert ownership (I can't say "hostingship", it do not exists ) is the solution in this case. I have just finnish a Dolibarr Agenda to BlueMind agenda connector (open project on DoliForge), and I've face the stuff opacity and mandatory you notice for google.

**Pull request merged**
