### PR TITLE
NEW Can add a column with cumulative data in accounting report

### PR DESCRIPTION
**Pull request by papoteur-mga**
# New 
As activity can be versatile between months, it can be more useful to see the cumul of invoicing month by month during the fiscal year. Comparing with the previous year is thus easier.

- Replacing the column "with tax" with a cumul
- Replacing the percent with percent on cumul
- Suppressing the total because the total is already on the last month line
- suppress the last void column

### CODE REVIEW

**Comment by eldy** [comment]
Can you introduce an option (for example $conf->global->ACCOUNTING_TURNOVER_SHOW_CUMUL) so we can choose to enable the "cumul" without loosing existing feature of the column with tax (useful to compare with other calculation mode done on payment). Or if you really want to remove it, add also an option to hide it (for exemple option $conf->global->ACCOUNTING_TURNOVER_SHOW_WITH_TAX)

**Comment by papoteur-mga** [comment]
Thus, I choose another way. I added the choice in the report for displaying with an accumulation column or with the amount with tax.
I have also a correction for a translation catalogue to translate WarningReportNotReliable

**Comment by papoteur-mga** [comment]
Hello,
Is it something that retains the pull request?

**Comment by eldy** [comment]
We are in a beta. No new feature allowed during beta:
https://wiki.dolibarr.org/index.php/Category:RoadMap

**Comment by eldy** [comment]
A lot simplification were done into code of report for final 8.0.
Report were split into "turnover invoiced" and "turnover collected" that are 2 different menu entries.
But this make this PR not possible to merge. Can you check how you can keep your feature without loosing 8.0 new menu tree.

**Comment by papoteur-mga** [comment]
I have now added a line under calcul mode with a link to the table with (or without) the accumulation column. This line is present in each of page Engagement mode and Debt mode.

**Comment by papoteur-mga** [comment]
Hello,
How to reboot the tests, when one failed without apparent link with the submission?

**Pull request closed without merging**
