### PR TITLE
NEW Can show stock in alert even if alter is set to 0

### PR DESCRIPTION
**Pull request by hguibourgdev**
FIX ">=" instead of ">" for alert test in order to work when negative stock are allowed

### CODE REVIEW

**Comment by eldy** [comment]
Value 0 (default) is currently used to say we don't want limit alert.
With then change, how can be keep this behaviour ?

**Comment by hguibourgdev** [comment]
You can use "" (empty) limit to keep this behaviour (it is the default
value)
Thanks

2017-07-18 14:40 GMT+02:00 Laurent Destailleur <notifications@github.com>:

**Comment by BebZ** [comment]
"empty" is the default value of the field ?
In this case, can you add a tooltip on the field to notice users they can use negative stock, and that "empty means no alert"

**Comment by hguibourgdev** [comment]
Yes, I will do that, but on 5.0

2017-07-19 8:10 GMT+02:00 BebZ <notifications@github.com>:

**Comment by hguibourgdev** [comment]
Done, with:  #7187 #7188 #7199 #7200

**Pull request merged**
