### PR TITLE
[ task #892 ] Add option in thridparty customer/supplier admin to hide

### PR DESCRIPTION
**Pull request by FHenry**
non active in select_company method

### CODE REVIEW

**Comment by marcosgdf** [comment]
:musical_note: changelog :musical_note:

**Comment by FHenry** [comment]
True !!! Done...

**Comment by FHenry** [comment]
Ok, I've change the duration planned by a clean planned_workload (I've add translation also) and limit the index.php report on validatd project only.

**Comment by simnandez** [comment]
Conflicts....

**Comment by FHenry** [comment]
Should be ok now

**Pull request merged**
