### PR TITLE
JS error preventing hiding of dates at object line

### PR DESCRIPTION
**Pull request by IonAgorria**
The "if (CKEDITOR)" gives "ReferenceError: CKEDITOR is not defined" at JS console causing the next code to don't execute, is this code obsolete?

### CODE REVIEW

**Comment by eldy** [comment]
Yes, code is not obsolete.
CKEDITOR must be on or not, so we must test if on to use the code to set focus when CKEDITOR is on (we do not use same code when CKEDITOR is on or not).
To remove warning, may be a test like this can be done
if (typeof(CKEDITOR) !== 'undefined')

**Comment by rdoursenaud** [comment]
The code in `ajax.lib.php` is a little bit more defensive and uses

``` js
if (typeof CKEDITOR == "object" && typeof CKEDITOR.instances != "undefined" && CKEDITOR.instances[key] != "undefined")
```

Don't know if it's really needed but being consistent is better ;)

**Comment by eldy** [comment]
CKEDITOR.instances[key] != "undefined" is surely not a good idea. Vairable "key" in this context does not exists.

**Comment by IonAgorria** [comment]
Now is good?

**Pull request merged**
