### PR TITLE
New #19310 display links documents on card

### PR DESCRIPTION
**Pull request by atm-GregM**
# new #19310
add links documents on card view
add possibility to delete link on card view

image

### CODE REVIEW

**Comment by john-botella** [comment]
Can you add font awesome link icon before link label ?
```<i class="fa fa-link"></i>```

**Comment by atm-GregM** [comment]
add font awesome external-link icon

image

**Comment by atm-GregM** [comment]
Dissociated files and links
image

add None message
image

**Comment by eldy** [comment]
This means we add all the content of page "Files and linked files" to the main home page.
Trying to move all information of all tabs on the first main page is a dangerous direction. It save one click when we need to see the linked file, but we introduce also more scrolling (a larger page even when we don't need this information making more cons than pro). It is also a very bad user experience to have an information managed in read at one place and managed in write (upload) at another place.
I would prefer this steps:
A) - First rewrite the page documents, so the action "Upload a file" or "Add a link" is just a simple picto (+) at end of line title of arrays of joined files and at end of line title of line of array of attached file (using js that make the upload component appears).
B) - After that, we will have only 2 tables to manage, 1 for the joined files and 1 for the linked files. 
C) - Once this will be a truth, we will be able to completely remove the tab "Linked files" into the main card. So we keep the rule read and edit at same place. We lost space on the main tab due to a new section but we saved some due to one tab that disappear (so balance is neutral instead of being negative). But i am not sure this step will remain possible in future because a lot of feature may appears to manage files, upload, etc... But at least it will be easier to move into the main tab if it is still a good choice to do this. 
So we must first focus on A).

**Comment by atm-maxime** [comment]
@atm-GregM Following discussion with @eldy, can you go back on the non separated version and merge conflicts ?

**Comment by eldy** [comment]
Closed, another implementation has been suggested

**Pull request closed without merging**
