### PR TITLE
Fix: Local taxes. If buyer not subject to localtax no need make database

### PR DESCRIPTION
**Pull request by simnandez**
access

### CODE REVIEW

**Comment by eldy** [comment]
Are you sure of this fix ?
When you sell to someone, for example online, you don't know if buyer is subject to localtax or not. Are you sure the rule is not on seller subject to localtax, like it is for standard vat ?

**Comment by simnandez** [comment]
Yes i'm sure. In the third card we can put if third is subject or not to localtax (In Spain, although you, as the seller, you are subject to localtax1, if your customer is not subject should not be applied)

**Comment by eldy** [comment]
OK, so I suggest to add the code:

if ($mysoc->country_code == 'ES')   // For spain, localtaxes are qualified if both supplier and seller use local taxe
    {
        if ($local == 1 && (! $thirdparty_seller->localtax1_assuj || ! $thirdparty_buyer->localtax1_assuj)) return 0;
        if ($local == 2 && (! $thirdparty_seller->localtax2_assuj || ! $thirdparty_buyer->localtax2_assuj)) return 0;  
    }
under the lines
    if ($local == 1 && ! $thirdparty_seller->localtax1_assuj) return 0;
    if ($local == 2 && ! $thirdparty_seller->localtax2_assuj) return 0;

And we must also add same into function get_default_localtax

**Comment by simnandez** [comment]
Yes, I was going to propose to apply only to Spain.... I talked to the tax advisor, I will improve the rule

**Comment by simnandez** [comment]
I changed the get_localtax function, but  I will go over the other (get_default_localtax, get_product_localtax_for_country, etc)

**Comment by eldy** [comment]
Only get_default_localtax should be modified.

get_product_localtax_for_country is only to get tax according to product/country for standard case. if supplier/customer use local tax or not is tested into other functions.

**Pull request merged**
