### PR TITLE
 New:Algerian Chart of accounts

### PR DESCRIPTION
**Pull request by bafbes**
New:Algerian Chart of accounts - First version

### CODE REVIEW

**Comment by eldy** [comment]
I revert the merge because there is 2 errors into file.
- You must first remove column rowid
- The field account_parent must be a key on account_number not on rowid (so value into account_parent must be existing values found into account_number).

**Comment by hregis** [comment]
@bafbes @eldy 
ah mince j'étais en train de corriger ! ;-)

**Comment by bafbes** [comment]
I used the benin chart of accounts as a model in the file llx_accounting_account_bj.sql. The french chart of accounts  ( in the file llx_accounting_account_fr.sql) does not either show the parent account number in in the account_parent field. Look at the first non root record in it  : " INSERT INTO llx_accounting_account (rowid, fk_pcg_version, pcg_type, pcg_subtype, account_number, account_parent, label, active) VALUES (   1,'PCG99-ABREGE','CAPIT', 'CAPITAL',       '101', '1401', 'Capital', 1);" 
Count '1401' is not the parent account numer of '101' either but its parent rowid. Right ?
So which file must be taken as a model ?

**Comment by eldy** [comment]
Problem is more complex than that.
Finally the PR of abbes is correct and i will add a line of comment into it to be able to fix file on the fly on v9.

**Pull request merged**
