### PR TITLE
NEW Add doActions hooks to user card

### LINKED ISSUE #3394: Add doActions hooks to user card

### PR DESCRIPTION
**Pull request by marcosgdf**
Add doActions hooks to user card

Close #3394

### CODE REVIEW

**Comment by eldy** [comment]
Sorry, a commit to change user card was validated just before. Can you merge and resubmit your PR ?

**Comment by marcosgdf** [comment]
Done.

**Comment by rdoursenaud** [comment]
This just broke the user card:
`Parse error: syntax error, unexpected '}' in htdocs/user/card.php on line 573`

**Comment by marcosgdf** [comment]
I've submitted a PR fixing it. Thanks!

**Pull request merged**
