### PR TITLE
fix #28431

### LINKED ISSUE #28431: Access a third party from the contact list
### Bug

In the contact list: /contact/list.php

If we display the Third Party column.

If you choose a prospect/client company: no mistake.
If you choose a company, neither prospect nor customer: error.

I noticed that each time, we are redirected to a link:
/comm/card.php?socid=12345

There is no error when using the following link:
/societe/card.php?socid=12345

So, if the company is not a customer, the link must be /societe/card.php

### Environment Version

18/19

### Environment OS

_No response_

### Environment Web server

_No response_

### Environment PHP

8.2

### Environment Database

_No response_

### Environment URL(s)

/contact/list.php

### Expected and actual behavior

_No response_

### Steps to reproduce the behavior

_No response_

### Attached files

image

### PR DESCRIPTION
**Pull request by frederic34**

### CODE REVIEW

**Comment by sonikf** [comment]
Ηι @frederic34 
Issue reporter is using a thirdparty that is not customer, prospect or vendor.
Is there a valid use case for this?

**Comment by frederic34** [comment]
image

image
image

with the fix we have a better link

**Comment by sonikf** [comment]
Sorry, I'm not questioning your fix, my question is what is the purpose/use case of a thirdparty that is not customer, prospect or vendor and should this be allowed?

**Comment by frederic34** [comment]
it just correct the link, create a thirdparty with no type is already possible

**Comment by kuscoo** [comment]
> Sorry, I'm not questioning your fix, my question is what is the purpose/use case of a thirdparty that is not customer, prospect or vendor and should this be allowed?

You can use third parties as an address book, without commercial vocation (for example for institutions, etc.)

**Pull request merged**
