### PR TITLE
Update ticket.lang Finnish lang Add missed "Message"

### PR DESCRIPTION
**Pull request by mikko80**
# FIX|Fix #[Add missed "Message"]

### CODE REVIEW

**Comment by mdeweerd** [comment]
FYI, languages need to be updated on transifex.

**Comment by frederic34** [comment]
you can ask to register here https://explore.transifex.com/dolibarr-association/dolibarr/

**Comment by mikko80** [comment]
I already use transifex. But those keywords missing -> not possible set translations.

**Comment by mdeweerd** [comment]
The en_US files are the reference so you need to add the keys there.

I can see that it is used in ticket/card.  It's strange that it is not reported as a missing translation.

**Comment by mdeweerd** [comment]
It's not reported because Progression is listed in 
dev/translation/ignore_translation_keys.lst in the section of translations ignored for ci (because this check was added while translations were already missing).

So you can update the appropriate language file under langs/en_US and remove the keys that you are adding in dev/translation/ignore_translation_keys.lst .

**Comment by mdeweerd** [comment]
Also, a tip: you can remove the keys that you want to translate from `dev/translation/ignore_translation_keys.lst`, push that in your PR and you can check in the Action results or the Files Changes tab which files/locations are related to the translation so that you start to get an idea of the context.  (The ci flow annotates these issues).

**Comment by eldy** [comment]
@mikko80 - I added the entry into the main.lang so it should appear in 7 days on transifex

**Pull request closed without merging**
