### PR TITLE
Update llx_societe.sql

### PR DESCRIPTION
**Pull request by dolibit-ut**
add:    eori   varchar(20

### CODE REVIEW

**Comment by eldy** [comment]
Can you describe what is eori field ?

**Comment by frederic34** [comment]
https://github.com/Dolibarr/dolibarr/issues/15379

https://ec.europa.eu/taxation_customs/dds2/eos/eori_validation.jsp?Lang=fr

**Comment by eldy** [comment]
So it seems it is an ID to describe a tihrdparty. We alreaydy have 6 fields for that  profid1, ... profid6
And the meaning of each profid depends on the country. I suppose eori is for germany.
It apears tha for germany, only profid1, 2 and 3 are used with the meaning
ProfId1DE=Prof Id 1 (USt.-IdNr)
ProfId2DE=Prof Id 2 (USt.-Nr)
ProfId3DE=Prof Id 3 (Handelsregister-Nr.)

So i suggest to enable the prof id 4 for this need. So to have  ProfId4DE=Prof Id 4 (Eori)  into en_US/companies.lang

**Comment by dolibit-ut** [comment]
I have in my german installation the following Prof IDs:

ProfID1 - Steuernummer                     (tax number / tax identification number)
ProfID2 - Amtsgericht                         (local court)
ProfID3 - Handelsregister-Nummer     (commercial register no.)
ProfID4 - USt-IdNr.                            (VAT-ID)

The problem is that these ProfIDs are not uniformly and consistently defined across versions
(at least outside of France and some other countries).

**Comment by dolibit-ut** [comment]
And EORI is binding for all EU countries - not only for Germany.

**Comment by dolibit-ut** [comment]
In France it should be the SIRET No. with the prefix FR.

**Comment by frederic34** [comment]
why not adding profid7 ? like suggested in issue

**Comment by dolibit-ut** [comment]
For Spain it should be the VAT-ID (NIF-IVA) with prefix ES.

https://www.agenciatributaria.gob.es/AEAT.sede/en_gb/procedimientoini/DC13.shtml

**Comment by frederic34** [comment]
or a dictionary ?

**Comment by dolibit-ut** [comment]
A dictionary is also a nice idea.
But can this works with forms layout (php and pdf)?

**Comment by eldy** [comment]
We already have 6 fields for professional ID. And i don't know any country that has more than 6 different professional id. The EORI id is unknown in France. For France we have SIREN, SIRET, NAF and NCS, but not all organizations have them.

The VAT-ID or TaxID is not stored into profid but into field "vat_intra". For all countries.

Also for DE, this is the country IDs that are defined (into companies.lang) :

ProfId1DE=Prof Id 1 (USt.-IdNr)
ProfId2DE=Prof Id 2 (USt.-Nr)
ProfId3DE=Prof Id 3 (Handelsregister-Nr.)
ProfId4DE=-    so not used yet officialy
ProfId5DE=-    so not used yet officially 
ProfId6DE=-    so not used yet officially

It looks strange if you have something else, this is the 3 fields available since several versions now.

Except the Tax id (the VAT ID we need to manage intracommunautary VAT, for example FR12345679 or DE123456789) that is store into field "vat_intra" of llx_societe and that all countries in EEC have, other IDs are specific to each country, so the 6 ids available have a definition that depends on each country.

If you need a field similar to SIRET in France, we must modify companis.lang file with
ProfId4DE=Prof Id 4 (EORI)
And fields will be available for all companies with country DE.

Is EORI different than USt.-IdNr, USt.-Nr and Handelsregister-Nr.

**Comment by altairis-agnes** [comment]
In fact yes, the EORI number is known in France. EORI registration is compulsory for all customs activities and operations carried out within the European Union (https://www.economie.gouv.fr/entreprises/numero-eori)
I have a customer who has an EORI number. This number must appear in his company information.
And when he exports to the European Union, he must also mention his customer's EORI number on invoices.

**Comment by eldy** [comment]
Very few companies seems to used it (it's the first time i hear about it).
May be @aspangaro has stored it into intracommreport module (this is a new module dedicated to make declaration for custom sales out of france in europe) ? 

A good list of offical ID for France is here:
https://www.economie.gouv.fr/entreprises/numeros-identification-entreprise
So already we have SIRET, SIREN, APE, RCS (into profiD 1 to 4) and the "Numéro de TVA intracommunautaire" is inside "vat_intra".

So, if we need EORI, we can add it into ProfID5 for France. We can also add it at position 5 for DE and ES and all countries in europe (position 5 and 6 are not used by countries in europe), so it will be the same field (field 5) for all.

**Comment by altairis-agnes** [comment]
We hear about it now in France, it is the brexit effect ;)
But this number must appear on the pdf's (especially invoices).
All my customers who do business with Great Britain are currently calling me to add it on their pdf's.
It would be nice if this would be a standard dolibarr field (used or not depending on users' situations).

**Comment by dolibit-ut** [comment]
EORI is also relatively new - but is now required by more and more customs authorities. 
So this will become more important.

**Comment by dolibit-ut** [comment]
I have often problems with the different Prof-IDs at customers who are operating in many countries.
It is difficult to set this well for print templates with so many different types/characteristics.

**Comment by dolibit-ut** [comment]
> 
> 
> We already have 6 fields for professional ID. And i don't know any country that has more than 6 different professional id. The EORI id is unknown in France. For France we have SIREN, SIRET, NAF and NCS, but not all organizations have them.
> 
> The VAT-ID or TaxID is not stored into profid but into field "vat_intra". For all countries.
> 
> Also for DE, this is the country IDs that are defined (into companies.lang) :
> 
> ProfId1DE=Prof Id 1 (USt.-IdNr)
> ProfId2DE=Prof Id 2 (USt.-Nr)
> ProfId3DE=Prof Id 3 (Handelsregister-Nr.)
> ProfId4DE=- so not used yet officialy
> ProfId5DE=- so not used yet officially
> ProfId6DE=- so not used yet officially
> 
> It looks strange if you have something else, this is the 3 fields available since several versions now.
> 
> Except the Tax id (the VAT ID we need to manage intracommunautary VAT, for example FR12345679 or DE123456789) that is store into field "vat_intra" of llx_societe and that all countries in EEC have, other IDs are specific to each country, so the 6 ids available have a definition that depends on each country.
> 
> If you need a field similar to SIRET in France, we must modify companis.lang file with
> ProfId4DE=Prof Id 4 (EORI)
> And fields will be available for all companies with country DE.
> 
> Is EORI different than USt.-IdNr, USt.-Nr and Handelsregister-Nr.



**So this translation / setting is really wrong:
ProfId1DE=Prof Id 1 (USt.-IdNr)
ProfId2DE=Prof Id 2 (USt.-Nr)    this is both the same  and this is the VAT-ID** 


If ProfId2 is the VAT ID, it means it is duplicate of vat_intra. 
So i suggest to rename it into
Amtsgericht (local court)

**Comment by eldy** [comment]
eori added in profid5 for all european countries.

**Pull request closed without merging**
