### PR TITLE
NEW Add hidden option THIRDPARTY_PROPAGATE_EXTRAFIELDS_TO_ORDER to copy extrafields from third party to order

### PR DESCRIPTION
**Pull request by fbosman**
# Fix copy of extra fields from third party to order
Extra fields of third party were not transferred to the order from that third party

### CODE REVIEW

**Comment by eldy** [comment]
This is done on purpose. Extrafields of thrdparties are related to a thirdparty. And an order is an object that is completely different. We never transform a thirdparty into an order and we never transfer an order into a thirdparty. That's why we do not propagate extrafields.
This PR may have more side effet. I suggest you to add a condition

if (! empty($conf->global->THIRDPARTY_PROPAGATE_EXTRAFIELDS_TO_ORDER))

on a hidden feature so we don't have this done by default to keep the current behaviour.

**Comment by eldy** [comment]
This is done on purpose. Extrafields of thrdparties are related to a thirdparty. And an order is an object that is completely different. We never transform a thirdparty into an order and we never transfer an order into a thirdparty. That's why we do not propagate extrafields.
This side may have more side effet. I suggest you to add a condition

if (! empty($conf->global->THIRDPARTY_PROPAGATE_EXTRAFIELDS_TO_ORDER))

on a hidden feature so we don't have this done by default to keep the current behaviour.

**Comment by fbosman** [comment]
Hi Elly,
I partly agree, the business objects are indeed very different. But we need some extra fields in the order (for emballage) and want a default value on the customer object. So this field belongs to the customer as a standard wish.

**Comment by fbosman** [comment]
THIRDPARTY_PROPAGATE_EXTRAFIELDS_TO_ORDER has been added as hidden feature

**Comment by galexandre05** [comment]
Hi,

There is a bug with this hidden feature :
If you create an order from the main menu (ie without selecting a third party), Dolibarr tries to copy extra fields from nowhere (a non existent third party object). There is no code to check that a third party is selected and no code to copy the extra fields after a third party has been selected.

**Pull request merged**
