### PR TITLE
NEW: price request supplier

### PR DESCRIPTION
**Pull request by aconits**
This is a new feature. The purpose is to make price requests to various suppliers like the "propal" module does with clients.
We create our request by adding products with a quantity and no price to start.
Then we send the request to the supplier by mail with a pdf. The supplier writes his prices for each product.
If we have a positive response from supplier, we can modify the request by filling the supplier product reference and price.
Finally we close the request to "accepted" and create a new purchase order from there request.
Each price by quantity are added or modified automatically on the product.

### CODE REVIEW

**Comment by aconits** [comment]
Hi,
I fixed the travis CI builder in my last commit.
Kind regards.

**Comment by rdoursenaud** [comment]
Wow, quite a requested feature. Nice :+1: 
You may want to squash your commits for better history readability and "englishness" ;)
[FR] http://git-scm.com/book/fr/v1/Utilitaires-Git-R%C3%A9%C3%A9crire-l-historique#Rassembler-des-%3Cem%3Ecommits%3C%2Fem%3E

**Comment by eldy** [comment]
Great.
Module has been included and set to experimental status. There is still some work to do:
- move dir comm/asksupplierpice one rank higher into asksupplierprice.
- do not have price mandatory when adding a line (goal is to receive price I think)
- having export/imoprt profils into module descriptor.
- debug...

**Comment by eldy** [comment]
Also, notes that all foreigne keys and index were not included into merge.
You must send a PR with files of tables  xxx.key.sql containing orders to create index and foreign keys to have them included during migration or database creation process.

**Comment by nicoeis** [comment]
Hi there, 
I really need this fonction on my dollibarr ...

Can someone please telle me how to install it ? 

Thanks

**Comment by BebZ** [comment]
Hello @nicoeis , before posting here, you must really understand the goal of this platform : it is a developper environment, so rude language is used.
some infos are hiding here : 
https://wiki.dolibarr.org/index.php/User_documentation
complete begginer guide here : 
https://www.dolistore.com/fr/documentation/580-Dolibarr-The-Book-3-8--version-fran--aise-.html 

For your answer : please install a version of dolibarr dated after march 2015 (like 4.0.2), 
activate experimental mode for modules 
and check if ask price supplier appears in list of modules
image

And please don't double post on the forum, but you can translate/repost on the french forum if you find the solution.

**Comment by nicoeis** [comment]
Thank you

I found out how to upgrade the version to 4.0.2, the module is here but it’s bugy and everytime i try to make a new document i got a message error …
I posted a request on the french forum … but no answer for now.

I noticed a strange thing, the module’s name is in english in my version not in french like yours. 

Does it matter ? 

Thanks for your reply anyway

**Comment by nicoeis** [comment]
Hi,

I know it's probably not the right place to post but i'm helpless and really need this feature ...
And i figured you guys certainly got the answer .

Everytime im tryin' to do a new supplier proposal (demande de prix fournisseur) i have a message error and i cannot complete the file by adding items on it.

I really don't get it  --> **On the Online Demo version of Dolibarr it works perfectly !!**
https://demo.dolibarr.org/public/demo/index.php

and i'm on the same version ...

My instance of Dolibarr / Dolicloud is brand new and clean the only thing i did is the upgrade from 3.9.2 to 4.0.2 .


Please someone help me i need this for my company ...


capture d ecran 2016-12-06 a 21 49 21
capture d ecran 2016-12-08 a 13 37 12

**Comment by rdoursenaud** [comment]
@nicoeis It's definately not the right place. This pull request has been merged. No one will care about you.
Please at least open a new issue. See https://github.com/Dolibarr/dolibarr/blob/develop/.github/CONTRIBUTING.md for how to do that correctly.

**Pull request merged**
