### PR TITLE
NEW packaging on fournprice (enabled with hidden option PRODUIT_FOURN_PACKAGING)

### PR DESCRIPTION
**Pull request by atm-greg**
# New manage packaging on fourn product price
allow to set a packaging value on supplier price.
Use the packaging to recalculate qty of supplier_order lines according to it.

ex. : your supplier sales pen by 10. You need 3 pens to sale to your customers. You will order a pack of 10 pens to your supplier.

### CODE REVIEW

**Comment by aljawaid** [comment]
How is this different to supplier minimum quantity?

**Comment by atm-greg** [comment]
> How is this different to supplier minimum quantity?

The minimum quantity prevents the user to order too few product quantity.
The supplier packaging give possibility to calculate a quantity for the lines that respects a minimum packaging.
It prevents the user to order incoherent quantities.

**Comment by BebZ** [comment]
Nice ! Will you propose it also on the customer side ?
Example : we sell pens per pack of 10, customer wants 14, we propose to "regulate" qty to 20 ?

**Comment by eldy** [comment]
Can you help me to solve conflicts on this PR ?

**Comment by atm-maxime** [comment]
Ping @atm-greg

**Comment by eldy** [comment]
Ping @atm-greg

**Comment by eldy** [comment]
Is it same than #12503 ?

**Comment by BebZ** [comment]
Will it be included in version 11 ? 
Sorry for conflicts, i don't know how to solve, i will ask someone if he can check ;)

**Comment by BebZ** [comment]
I think this one is older than 12503 and on 12503 it says : 
@atm-greg 
"It's a rebuild of an old PR for this feature."

**Comment by eldy** [comment]
Thanks @BebZ to point me this note, so i close the PR.

**Pull request closed without merging**
