### PR TITLE
New add limit stock product by warehouse

### PR DESCRIPTION
**Pull request by atm-gauthier**

### CODE REVIEW

**Comment by BebZ** [comment]
Oh, please, did you check it's working with Batch/DLC products ?

**Comment by atm-gauthier** [comment]
@BebZ For me replenishement card doesn't allow to work with batch.
We can specify product batch on supplier order reception or on stock movement only.
My new feature doesn't interact with batch, it just allow to get stock limit and desired stock by product and by warehouse, and not only by product, then there are no problems with that.
Do you agree with that ?

**Comment by BebZ** [comment]
Sorry i didn't see it was for replenishment only.
I thought it was a "per warehouse" stock deletion ability  : 
NEW : Delete product stock warehouse

> If  you delete a product in a warehouse, not only delete "stock" but also "batch_stock" 
> it would delete the corresponding batch between the tables llx_product_stock and llx_product_batch

**Comment by fappels** [comment]
+1 Thanks for adding missing Min-Max model for stock replenishment.
Maybe table name may be confusing, better product_entrepot, no stock in stable only properties.
Also delete is missing in product.class and entrepot.class delete methods.

**Comment by atm-gauthier** [comment]
@fappels you're right, then I just added code to delete associated product_stock_entrepot lines when we drop a product or a warehouse

**Pull request merged**
