### PR TITLE
Fix: use get instead getJSON for avoid freezing

### PR DESCRIPTION
**Pull request by hregis**

### CODE REVIEW

**Comment by eldy** [comment]
I don't experience pb. 

Jquery v1.11.3 is higher than v1.2.3  (11 > 2) so what is the trouble. How to reproduce ?

**Comment by fappels** [comment]
My mistake, posted unrelated comment on blockUI issue, this fixes the refresh freezing of EDM area.

**Comment by hregis** [comment]
this fix concerns only the return is not in JSON and blocks removal BlockUI.
for the problem of jquery version ??? it's a blockui bug !! but the jquery test version is no longer present with the latest of blockui !! (the version currently present in dolibarr)

**Comment by hregis** [comment]
@eldy you can merge this fix

**Pull request merged**
