### PR TITLE
3.6b review

### PR DESCRIPTION
**Pull request by rdoursenaud**
A bunch of small fixes

### CODE REVIEW

**Comment by simnandez** [comment]
Great, but fr_FR must be translated via transifex

**Comment by rdoursenaud** [comment]
Of course but these are new fields! This makes no harm to include these now ;)

**Comment by rdoursenaud** [comment]
@simnandez What's your position on this ? Should I alter this PR so that there is no FR_fr file modified ?

**Comment by marcosgdf** [comment]
@rdoursenaud I altered mines so I think you gotta do it... :grimacing:

**Comment by rdoursenaud** [comment]
@simnandez @eldy 
I removed french translations modifications
The branch is now ready to be merged,

**Pull request merged**
