### PR TITLE
FIX CA report by product/service : subcategory filter

### PR DESCRIPTION
**Pull request by atm-lena**
# Fix # CA report by product/service : subcategory filter
Because of CATEGORIE_RECURSIV_ADD conf, product was counted twice with subcategory filter in CA report by product/service.
FIX sql request : replace "OR" to "IN".

### CODE REVIEW

**Comment by eldy** [comment]
Question about CATEGORIE_RECURSIV_ADD.
My understading is that it add parent categories too. Only main parent or all parents (if category is at level higher than 2) ?

**Comment by atm-lena** [comment]
> Question about CATEGORIE_RECURSIV_ADD.
> My understading is that it add parent categories too. Only main parent or all parents (if category is at level higher than 2) ?

Exactly !

**Comment by eldy** [comment]
But it adds only the first (main) parent or all parents ?

**Comment by atm-lena** [comment]
> But it adds only the first (main) parent or all parents ?

All parents

**Comment by eldy** [comment]
But it seems that the sql after modification add a test to find if categorie is parent of first level only ? Right ?
for this fix, the first part of fix, that remove the link with table categorie looks good to me. We must remove it to avoid duplicate.
However, the use of the subselect you add seems to work only to find if product is in category or in first child category.

This is how you can fix this:
- Remove the link to categorie table in the FROM like you did
- Call the method get_full_arbo('product', $selected_cat, 1) to get the list of all categories that are child of $selected_cat
Now you have all the categorie id in memory, just modify the where of the request you add

$sql.= " AND (p.rowid IN ";
        $sql.= " (SELECT fk_product FROM ".MAIN_DB_PREFIX."categorie_product cp WHERE cp.fk_categorie IN ";
        $sql.= " (SELECT rowid FROM ".MAIN_DB_PREFIX."categorie WHERE rowid = ".$selected_cat;
        if ($subcat) $sql.=" OR fk_parent = " . $selected_cat;
        $sql.= ")))";

Into something like this:

$sql.= " AND (p.rowid IN ";
        $sql .= " (SELECT fk_product FROM ".MAIN_DB_PREFIX."categorie_product cp WHERE ";
        if ($subcat) $sql .= "cp.fk_categorie IN (". $listofallcategorieidyougetpreviously.")"
        else $sql.="cp.fk_categorie = ".$selected_cat;
        $sql.= "))";

Code is really simpler, no subqueries that make requests difficult to understand and it will works with all subcategories whatever is the level.

**Comment by atm-lena** [comment]
> But it seems that the sql after modification add a test to find if categorie is parent of first level only ? Right ?
> for this fix, the first part of fix, that remove the link with table categorie looks good to me. We must remove it to avoid duplicate.
> However, the use of the subselect you add seems to work only to find if product is in category or in first child category.
> 
> This is how you can fix this:
> 
> * Remove the link to categorie table in the FROM like you did
> * Call the method get_full_arbo('product', $selected_cat, 1) to get the list of all categories that are child of $selected_cat
>   Now you have all the categorie id in memory, just modify the where of the request you add
> 
> $sql.= " AND (p.rowid IN ";
> $sql.= " (SELECT fk_product FROM ".MAIN_DB_PREFIX."categorie_product cp WHERE cp.fk_categorie IN ";
> $sql.= " (SELECT rowid FROM ".MAIN_DB_PREFIX."categorie WHERE rowid = ".$selected_cat;
> if ($subcat) $sql.=" OR fk_parent = " . $selected_cat;
> $sql.= ")))";
> 
> Into something like this:
> 
> $sql.= " AND (p.rowid IN ";
> $sql .= " (SELECT fk_product FROM ".MAIN_DB_PREFIX."categorie_product cp WHERE ";
> if ($subcat) $sql .= "cp.fk_categorie IN (". $listofallcategorieidyougetpreviously.")"
> else $sql.="cp.fk_categorie = ".$selected_cat;
> $sql.= "))";
> 
> Code is really simpler, no subqueries that make requests difficult to understand and it will works with all subcategories whatever is the level.

You're right ! I corrected my development.

**Pull request merged**
