### PR TITLE
adding leavelist module

### PR DESCRIPTION
**Pull request by slim-abid**
**Introduction**
Dolibarr is used also as software to facilitate the leave requests from the employees but does not give the hand to the employees not having certain permissions to view the leave of other colleagues.

**About this module** 

 - [ ] Facilitate visualizing the availability of certain employees in a finite period of time and also support transparency within the company.
 - [ ] Giving certain permissions to the employees for the visualization of all the leaves depending on the corporate hierarchy constituting the company.
 - [ ] Make the visualization easier with the applied filters and charts.
 - [ ] Implemented in two languages French and English.
 - [ ] Multiselect field for employees.
 
**Module UI examples**
 - Main page:
main1
main2
main3

 - Tables:
table

 - Charts:
 charts
 - calendars:
dolibarr

### CODE REVIEW

**Comment by atm-maxime** [comment]
Hi ! That's very cool of you to share these source. Although, you have to integrate your module as a part of the leave request module, not just like this in the custom directory which is reserved for external modules. And modifying the .gitignore and other global config files is not recommended as we all work with these setup.

**Comment by slim-abid** [comment]
> Hi ! That's very cool of you to share these source. Although, you have to integrate your module as a part of the leave request module, not just like this in the custom directory which is reserved for external modules. And modifying the .gitignore and other global config files is not recommended as we all work with these setup.

Thank you for your response! please tell me if I have to do other changes

**Comment by atm-maxime** [comment]
Hi.
What I meant was that there is already an internal module to deal with leave request (named holiday). Your module adds a lot of new features that should be integrated in the already existing module.
And there are many files you shouldn't have (.gitignore and other hidden files, build or doc directory, htdocs/leavelist/core/triggers/interface_99_modLeaveList_LeaveListTriggers.class.php.back file, ...)
Langs file should be centralized in the lang directory, the module descriptor in core/modules, ...
Finally I think you created a new module with module builder and you kept all the files but only some are useful.

There seems to be 3 new pages in your code (list, calendar and graph) why don't you just add these 3 in the holiday module and add menu entries in the core menu class ? I checked your index file where everything seems to be, and I think you have to review the way of coding of Dolibarr. For example the rights management. You shouldn't have to do a direct SQL request to retrieve check for user rights. 

Try to add small things on existing Dolibarr pages and small PRs to start with the community.

**Comment by slim-abid** [comment]
> Hi.
> What I meant was that there is already an internal module to deal with leave request (named holiday). Your module adds a lot of new features that should be integrated in the already existing module.
> And there are many files you shouldn't have (.gitignore and other hidden files, build or doc directory, htdocs/leavelist/core/triggers/interface_99_modLeaveList_LeaveListTriggers.class.php.back file, ...)
> Langs file should be centralized in the lang directory, the module descriptor in core/modules, ...
> Finally I think you created a new module with module builder and you kept all the files but only some are useful.
> 
> There seems to be 3 new pages in your code (list, calendar and graph) why don't you just add these 3 in the holiday module and add menu entries in the core menu class ? I checked your index file where everything seems to be, and I think you have to review the way of coding of Dolibarr. For example the rights management. You shouldn't have to do a direct SQL request to retrieve check for user rights.
> 
> Try to add small things on existing Dolibarr pages and small PRs to start with the community.

Thanks a lot! that explains it all, I will start with adding small things as you said

**Pull request closed without merging**
