### PR TITLE
Update fiche.php

### PR DESCRIPTION
**Pull request by syrus34**
Last invoices prices are with taxes and with no tax for last proposals and last orders. It's better to see all prices with taxes.

### CODE REVIEW

**Comment by atm-maxime** [comment]
Is it ? My guess is that this should be an option to tell if you want amount with or without taxes. For example, I have a service company and I don't care about amounts with taxes. All I want to see is amounts without taxes. @rdoursenaud, didn't you say that an accountancy setup "CREANCE-DETTE" should imply without taxes display and "RECETTE-DEPENSES" with ?

**Comment by rdoursenaud** [comment]
Yes, I believe that businesses that receive VAT refunds prefer amounts without VAT but for turnover and accounting data.
I see nothing wrong with this particular PR that simply tries to uniformise presentation.

**Comment by syrus34** [comment]
The display can be more precise with in fact 2 columns ht and ttc to find quickly a lastest invoice, propals
It's just to have coherent display between different lastest group.

**Comment by atm-maxime** [comment]
Of course, I think this should be uniformized but with taxes if RECETTES-DEPENSES and without if CREANCES-DETTES. The PR is ok for me too but is syrus wants to add an "if"...

**Comment by eldy** [comment]
I confirm that most business need price without VAT.
Ok to uniformize but by moving "last invoice" with price with not vat (like others) by default.
A hidden option to have "all prices with tax" into summary, list is also possible.

**Comment by eldy** [comment]
Discarded. PR should contains a if because need is only for few users.

**Pull request closed without merging**
