### PR TITLE
Add feature to change the check bordereau number with this given by the bank

### PR DESCRIPTION
**Pull request by defrance**

### CODE REVIEW

**Comment by atm-maxime** [comment]
Hi Charles. I added a new field on remisecheque some commits ago : refext. This will be useful to store the real check receipt number from the bank. See this commit : https://github.com/Dolibarr/dolibarr/commit/7abc53698a4915e44f6cfc0d992e208abf94623f

**Comment by defrance** [comment]
Arf, "Changed 2 days ago", i'm to slow, i prefer my method more simple but maybe somebody have a better advice about it

Propose to add your new fields on my new bordereau export and in the pdf

Bien cordialement,
Charles-françois BENKE

**Comment by atm-maxime** [comment]
I just added the ref_ext as it's on all other objects. Keeping an internal ref and having an external for this kind of application sounds to be the good solution to me.

You're right, this field should be in the export and I'll see to add it in the PDF.

**Comment by defrance** [comment]
Ok 
So let wait rhe merge and add the ext-ref field in export and pdf.
My little change will usefull for wait till the 3.5 version

Bien cordialement,
Charles-françois BENKE

**Comment by simnandez** [comment]
We have conflicts to merge, please solve it, thanks

**Pull request closed without merging**
