### PR TITLE
fix bug : external users should not see costprice and margin infos

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by simnandez** [comment]
Can you update the ChangeLog file?

**Comment by altairis-tof** [comment]
Done

**Comment by simnandez** [comment]
I think the modMargin.class.php at the /core/modules/ file has an error in the code, in the line 83 you have added && empty($user->societe_id)s , does not hurt to the "s"?

**Comment by altairis-tof** [comment]
thanks for the review; should be ok now.

**Pull request merged**
