### PR TITLE
FIX regression PR #20713

### PR DESCRIPTION
**Pull request by daraelmin**
Don't know why the first PR  #20906 was closed neither why I can't reopen it 
Please do not revert with PR #20900

### CODE REVIEW

**Comment by aspangaro** [comment]
Thanks @daraelmin 

PR revert #20900  is closed
For the PR #20906, surely a mistake when we integrate your fix in Easya, sorry.

I try your fix and it's work now !

**Comment by daraelmin** [comment]
> Thanks @daraelmin 
> 
> PR revert #20900  is closed
> For the PR #20906, surely a mistake when we integrate your fix in Easya, sorry.
> 
> I try your fix and it's work now !

Ok no problem.
Hope the dev camp in Valence is going well.

Cheers.

**Comment by eldy** [comment]
Do you have the trouble with last v16/develop  ?

**Comment by daraelmin** [comment]
Yes. The dix should be merged into develop /v16 top.
Cheers

Le vendredi 20 mai 2022, Laurent Destailleur ***@***.***> a
écrit :

**Pull request merged**
