### PR TITLE
Fix PGSQL Bug (better use JOIN rather than ,)

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by eldy** [comment]
I think a better solution is not in using inner join. We can keep , but problem is into the LEFT JOIN that is not at wrong place.
When you do 

select from a,b,c left join x on x.fieldx=a.fielda where ...

this is wrong with pgsql but also wrong for standard. You must modify into

select from a left join x on x.fieldx=a.fielda, b, c where ...

Reason is that a "left join" must be JUST after the table the "on" is for.
Doing this, you can fix pgsql without rewrite all request and changing into INNER JOIN. Moving "left join" at correct place should be enough. I prefer this writing because INNER JOIN bring other problems (i can't remember which one, but we spent so many time to remove all INNER JOIN in code in version 3.0 or 3.1 that i prefer to avoid if wa can and i think moving left join should be enough).

Can you check that my solution also work and try to for this patch instead of this one ?

**Comment by FHenry** [comment]
Ok, I understand, I will check. 
The other point on commonobject/ficheinterdet is more diffcult. For 3.3 and 3.4 (cause data base schema change is no more allowed) my fix can be ok but in dev branch we should add fk_parent_line into ficheinterdet and not merge the proposal fix. What do you think ?

**Comment by eldy** [comment]
I completed definition of freeze to be more clear about adding columns: http://wiki.dolibarr.org/index.php/Category:RoadMap#Freeze_definition
Adding for 3.3 (maintenancen branch is not possible), however, adding in beta version 3.4, since it is to fix a bug, is possible.

**Comment by FHenry** [comment]
Ok, I've done the pull request on 3.4 Branch. I close This pull request. I will check the left join in another pull request

**Pull request closed without merging**
