### PR TITLE
Update pr-18.yaml

### PR DESCRIPTION
**Pull request by frederic34**
https://docs.github.com/fr/rest/pulls/review-requests?apiVersion=2022-11-28#request-reviewers-for-a-pull-request

### CODE REVIEW

**Comment by frederic34** [comment]
```
gh: Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the frederic34/dolibarr repository. (HTTP 422)
{"message":"Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the frederic34/dolibarr repository.","documentation_url":"https://docs.github.com/rest/pulls/review-requests#request-reviewers-for-a-pull-request","status":"422"}
```
test on my fork

I think that token need to acces organization to check if reviewer are in it

**Comment by FHenry** [comment]
All PR on 18 branch failed cause of that ci t'est...

**Comment by frederic34** [comment]
@FHenry I try to fix it, it's apparently to enable an automerge feature on review
It has been added here https://github.com/Dolibarr/dolibarr/pull/31898

**Comment by rycks** [comment]
Yes we show that just now ...

> error fetching organization teams: GraphQL: Resource not accessible by integration (organization.teams)
> Error: Process completed with exit code 1.

**Comment by eldy** [comment]
> @FHenry I try to fix it, it's apparently to enable an automerge feature on review It has been added here #31898

@frederic34 We don't want merge here. All what we want in this github action is that any PR submitted to branchv18 has automaticaly in review for users
- lvessilier-opendsi
- rycks
- eldy

**Pull request merged**
