### PR TITLE
NEW display supplier in objectline if defined

### PR DESCRIPTION
**Pull request by ptibogxiv**

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide a screenshot of result after...

**Comment by ptibogxiv** [comment]
This is the result of the PR. Juste display supplier and supplier's ref of a line object if exist and add before.
image

**Comment by atm-maxime** [comment]
On a customer order, I don't know how fk_fournprice is filled. Can you tell me ? And what if there are several suppliers possible for the product?

**Comment by ptibogxiv** [comment]
@atm-maxime  the database used by this PR already exist for the order. I tought it was used by an ATM modules....

For the moment, i don't push PR for object creation which used it (chose supplier/price supplier if severals) when add a product to a propal, order or invoice and used it for creating the supplier order ie. ATM's module order2supplier with this defined price used by default in the form.

For some business, we can need to select a defined supplier/supplier-price for an order/invoice for the samed product ex: electronic sales, outsourced business

**Pull request merged**
