### PR TITLE
NEW Option to transfer only reconciliated lines from bank

### PR DESCRIPTION
**Pull request by rycks**
That PR add a checkbox on bank import to be able to not import non-reconciliated lines

image

### CODE REVIEW

**Comment by rycks** [comment]
Add default option and better choice with a drop down

image

**Comment by eldy** [comment]
For term consistency, can you rename Import ...
 Into 
Transfer ...

**Comment by rycks** [comment]
for sure !

**Comment by rycks** [comment]
@eldy done

**Pull request merged**
