### PR TITLE
NEW : addition of service management in production order production

### PR DESCRIPTION
**Pull request by atm-jpb**
MERGE AFTER :  https://github.com/Dolibarr/dolibarr/pull/21498

NEW  : addition of service management in production order production

Capture d’écran de 2022-08-22 16-31-44

Display of the production , product to consume , service to consume tables when the Inventory management also applies to services conf is deactivated
Capture d’écran de 2022-08-22 16-33-35

Handling add service input to  hour min 
Capture d’écran de 2022-08-22 16-37-04

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
conf activation 
Capture d’écran de 2022-08-22 16-44-45

grouping product ans service
Capture d’écran de 2022-08-22 16-45-31

### CODE REVIEW

**Comment by eldy** [comment]
https://github.com/Dolibarr/dolibarr/pull/21498 has been merged. Can you solve conflict on this one ?

**Comment by atm-jpb** [comment]
@eldy done

**Comment by atm-jpb** [comment]
@eldy 
1) SecurityTest::testGetURLContent
Should GET url 301 with following -> 200 but we get 503
Failed asserting that 503 matches expected 200.

this one does not concern development i presume

**Comment by atm-jpb** [comment]
@eldy 
this is the stickler log 
Latest Review Log
Started 2022-11-07 13:05:30 UTC

Completed 2022-11-07 13:09:54 UTC

Commit 61274371fbd9adbe04a46dbc48c306183940e096

INFO: Cloning repository 'https://github.com/ATM-Consulting/dolibarr.git' into '/tmp/Dolibarr-dolibarr-21837'
INFO: Fetching 'develop_NEW_OFStd_Times' from 'origin'
INFO: Running fixer phpcs on 2 files
INFO: Running container: phpcs-run phpcbf --standard=/src/dev/setup/codesniffer/ruleset.xml --extensions=php --tab-width=4 /src/htdocs/mrp/class/mo.class.php /src/htdocs/mrp/mo_production.php
INFO: phpcs version is: 3.6.2
INFO: Running phpcs on 2 files
INFO: Running container: phpcs-run phpcs -q --report=checkstyle --standard=/src/dev/setup/codesniffer/ruleset.xml --extensions=php --tab-width=4 /src/htdocs/mrp/class/mo.class.php /src/htdocs/mrp/mo_production.php
INFO: phpcs added 0 review notes
INFO: Publishing 0 new comments
but it's still on error  on github ...  what did i miss ?

**Comment by Humml87** [comment]
Hi @eldy and @atm-jpb,
this is a grate work! Can we merge this in develop?
The PR fix the new Bug #23108.

**Pull request closed without merging**
