### PR TITLE
Fix: #4880 Not disabled cause need to load personalized language

### PR DESCRIPTION
**Pull request by hregis**

### CODE REVIEW

**Comment by eldy** [comment]
Do you have an example why we need to load language to just output image file ?

**Comment by aljawaid** [comment]
This fix resolved my fatal error in the apache logs.

My barcode image and third party pics and product pics were brkoen and failed to load until I commented out the line in this fix as suggested by @hregis

**Comment by hregis** [comment]
@eldy 
I do not have that bug! I do not know why ... but if we allow the loading of "user", the fetch of the "user" included a use of $lang , so obviously !!

**Comment by hregis** [comment]
yes this is the BOM error, it's possible to resolved this... copy the content of the file, remove/delete the file, and recreate this file and paste the original content... save and enjoy ! ;-)

**Comment by eldy** [comment]
I pushed what i think to be a better fix by removing usage of $langs into the fetch of user.

**Pull request closed without merging**
