### PR TITLE
add new db tables to store emails and phones numbers

### PR DESCRIPTION
**Pull request by frederic34**
@eldy @aspangaro @atm-maxime @hregis @dolibit-ut @daraelmin @FHenry @altatof @ptibogxiv and any other interested
I propose to migrate all emails and phones numbers into separate table, so members, socpeoples, thirdparties and users can have multiple emails and phones (without loosing old old :fax: numbers, but still used)
Thank's in advance for comments

### CODE REVIEW

**Comment by frederic34** [comment]
a phone can be std, fax mobile etc, can be businness or private and can be default phone to use
an email can be business or private and can be default email to use

**Comment by hregis** [comment]
@frederic34 wouahou... It's very complicated! Why just one table with type of element?

**Comment by ptibogxiv** [comment]
@frederic34 can you include fax too (it's a good PR to disabled fax but keep it when needed)

**Comment by hregis** [comment]
And type of media?

**Comment by BB2A-Anthony** [comment]
It's very good proposal I follow you 100%

You need an email and a phone by default it's on for read on head

**Comment by frederic34** [comment]
> @frederic34 wouahou... It's very complicated! Why just one table with type of element?

That's why I'm asking everybody, but for foreign keys and speed I think it's better, but I may be wrong

> @frederic34 can you include fax too (it's a good PR to disabled fax but keep it when needed)

fax are still there, I set a dictionary of phones types

> And type of media?

can you develop ?

> You need an email and a phone by default it's on for read on head

yes it's in priority column(sort of rank), by example for user asking new password or for preferred phone number etc

**Comment by hregis** [comment]
One table with type of media (tel, fax, e-mail, etc...) and with elements (user, customer, adherent, etc...)

**Comment by daraelmin** [comment]
Great Idea... But what a hard work !

May I suggest to :
- add postal address, social network and website also 
- remove dupplicated column (adherent, third party, contact, user, etc.)

**Comment by frederic34** [comment]
> One table with type of media (tel, fax, e-mail, etc...) and with elements (user, customer, adherent, etc...)

so in commonobject a function for all

**Comment by ptibogxiv** [comment]
It will be si good to include country origin for phone/fax number too ie: fr -> +33

**Comment by hregis** [comment]
Hard work with all tables (llx_member_email, llx_member_phone, etc...) just one table with "type" (tel, fax, etc..) and "element" (user, customer, member, etc...) is very "souple" for me 😉

**Comment by frederic34** [comment]
hum hum one table to store

- emails
- phones
- address
- website url
- ...

define for each object a schema and store them in json format

**Comment by daraelmin** [comment]
Why in json and not in carddav?

**Comment by atm-maxime** [comment]
Seems a good idea. I agree one table is enough.
But isn't it hard work for few use case ? Usually people, members, users have one email and one mobile phone. But it would be more compliant with most address books.

**Comment by daraelmin** [comment]
> Seems a good idea. I agree one table is enough.
> But isn't it hard work for few use case ? Usually people, members, users have one email and one mobile phone. But it would be more compliant with most address books.

When an association has employee or elected member as employee, you can different profil for the same person dependong if you re looking for the member (adherent), the employee (user) or the client (thirdparty).

For Union (syndicat), the member has also a professional profil to store.

**Comment by fappels** [comment]
One phonenumber can be linked to more telecom service (Signal, whatsapp, telegram, ...).

**Comment by atm-maxime** [comment]
> When an association has employee or elected member as employee, you can different profil for the same person dependong if you re looking for the member (adherent), the employee (user) or the client (thirdparty).

Agreed, but you already can have different email and phone on the user card (employee), member card and customer card. And your example is about foundations, which doesn't represent all Dolibarr users. I'm ok with the functionality because it's more compliant with current standards, just pointing out that the need doesn't concern the user majority I think.

**Comment by altairis-tof** [comment]
hello, i also vote for one single table. 
@daraelmin also suggest carddav; it seems to be interesting; maybe @daraelmin can tell us more about it ?

**Comment by daraelmin** [comment]
@altatof 
In fact... I'm ignorant about this standart.
But I need to sync my adherent with an nextcloud instance.
Here is a feature request linked to carddav  #15831 and the module suggested is here https://github.com/Befox/cdav

**Comment by BB2A-Anthony** [comment]
I am ready to help in the dev if idea is validated by @eldy .
I think you have to be careful with API reset

**Comment by frederic34** [comment]
how to search in db if you store info in carddav format?

**Comment by daraelmin** [comment]
> how to search in db if you store info in carddav format?

Right.

**Comment by daraelmin** [comment]
From what I read, I imagine a really hard reenginering. Have you already tried to schematize?

It seems to me, that we can inspirate ourselves from the extrafields management. However I wonder if the query consultation performance will not be too impacted ... otherwise the big stake will be to "fix" some default value to guarantee functionality in the modules.

To me it appears we are talking of something like this

##sql side
An "entity" table with the base fields and an "entity property" table with relatively few columns each of which is indexed.

something like:
ENTITY (*id_entity*, company_name, gender, firstname, lastname, typeent, parent_entity_id, avatar_img)
ENTITY_PROPERTIES (*fk_id_entity, property*, value, default_in_module)
and a value diconnaire for "property".

The entity key is the only thing register in the member, company, user and contact tables and we delete the other values of type " profil". 

##php side

default fields mandatory for module fonctionnality, but selectable among the values already registered for the entity

Admin user should add mandatory fields or tell if default field are mandatory.

a possibility to add new property (within property_dictionnary) in the profile of the entity ( in a dedicated page or in each module with a core include or maybe both)

##js side
Ajax request for adding property and save them on update

##Impact
Performance ?
Vcard
Module retro compatibilities
Migration
Extrafield
Anything else ?

**Comment by BB2A-Anthony** [comment]
For migrate slowly whay

Add fonctionality and not touch the fonctionality is in inplace.  The number and mail this in place are not touching.  

For migration

Add number and mail in new table (set by default) dont touch in old emplacement if next time edit , modify on old emplacement and new table

You understant?

**Comment by daraelmin** [comment]
Ok. 
I assume you have a plan, so maybe I can help doing part of it. 
Just tell me wich steps you are thinking and on witch part you need volonteer. I'll give you a hand if I can.

EDIT : Sorry I've found the plan here : #16989

**Comment by eldy** [comment]
What is goal of adding a table compared to adding extrafields.
Moving horizontal data into a vertical storage leads to a lot of problem (how can be extract data in excel, how do we import, what about the search for a part of a field or end with or start with, what about merging thirdparties, finding duplicates, etc...)
Currently users does not see how data is stored. They just enter their data because fields for multiple phone, fax, etc, already exists.

What is the use case (a real life situation) that can justify that we must make architecture more complex that currently ? Does this happen frequently that we need to store more than 3 phone numbers for 1 thirdparties, knowing that, if we have more phone number, we must manage this by the "alternative contact record" (so contact/address).
For members, we also have 3 fields for phone but we can image to add a type "Pro, Perso, Mobile Pro, Mobile Person Fax, ..." to each of this 3 fields for a more accurate storage.
But using a vertical storage for just phone (when there is already a feature for that) seems a gaz engine for a very very small gain (if fact i don't really see the gain for end users compared to adding a simple "type of number" for each field). This was legitimate for social networks, because there is several hundred of social networks, and each user use a different family of social networks, but looks strange to me for just phone numbers.

**Comment by daraelmin** [comment]
> What is goal of adding a table compared to adding extrafields.
> Moving horizontal data into a vertical storage leads to a lot of problem (how can be extract data in excel, how do we import, what about the search for a part of a field or end with or start with, what about merging thirdparties, finding duplicates, etc...)
> Currently users does not see how data is stored. They just enter their data because fields for multiple phone, fax, etc, already exists.
> 
> What is the use case (a real life situation) that can justify that we must make architecture more complex that currently ? Does this happen frequently that we need to store more than 3 phone numbers for 1 thirdparties, knowing that, if we have more phone number, we must manage this by the "alternative contact record" (so contact/address).
> For members, we also have 3 fields for phone but we can image to add a type "Pro, Perso, Mobile Pro, Mobile Person Fax, ..." to each of this 3 fields for a more accurate storage.
> But using a vertical storage for just phone (when there is already a feature for that) seems a gaz engine for a very very small gain (if fact i don't really see the gain for end users compared to adding a simple "type of number" for each field). This was legitimate for social networks, because there is several hundred of social networks, and each user use a different family of social networks, but looks strange to me for just phone numbers.
> 

To me, the real benefit of having a separate table is to refer from all module and table to the same data. That may simplify the sync, export and import.

**Comment by daraelmin** [comment]
I have some use case : when user is employee, we should use his personnal adress when sending him his contract or salary but we must use our professionnal adress when he contact client or prospect or to impress visit card
With multy company... The same employee could have multiple adresses or phones...

**Comment by eldy** [comment]
For personal data, there is already fields to store data (like birthday, or personal phone, personal address of a user is already the field address, zip and country of the user card).
Currently we don't have more, because there is no module yet that need to manage more. 
This will be the goal of module HRM and it may introduce more fields dedicated for this module (the fields this modules need and that differs from other existing data) but because this data remains related to user/employee, it must be on the dedicated table of user. There is no need for a vertical table to store horizontal data.
My question was "a use case that show we must store data in a vertical table instead of an horizontal table)". The use case you give show we can perfectly work with current table (we are speaking about current phone numbers of a user), even if we currently miss some fields that will be managed by the module HRM in the future. 
if an employee has several address, for its employment coordinates, only the main address will be necessary for contracts (history may be required by HRM module but in such a case, it will be the role of the module HRM to introduce a table for history purpose). If a user absolutely needs to store 2 current adresses for the same employee, it is still possible to add extra fields. For most common need (and the core must cover the common need) current features (existing fields + extra fields) seems to provide the needs

**Comment by philippe-opendsi** [comment]
Hello, I will add one need when using in multicompany mode, a user can have different email adress depending on the entity he is working on.

**Comment by hregis** [comment]
@philippe-opendsi  i can add this feature in the module

**Comment by atm-maxime** [comment]
> Hello, I will add one need when using in multicompany mode, a user can have different email adress depending on the entity he is working on.

I asked myself the same and ended up to create a different user account. This is not the same user that works in 2 different entities.

**Comment by daraelmin** [comment]
Wouldn't it be more coherent to remove the redundant columns across the member / company / employee / user / contact / etc tables to group them into one (legal_entitey) which all the modules would refer to?
a single table with a single extrafield per legal entity
the management of name, email and telephone changes would thus be facilitated by centralization as well as searches.

When someone gets married, their name must be changed and checked in 3 to 6 tables ... same for a move, a change of operator or email address

um recent example:
One member changed her name after her marriage. we changed the name in adherent first ... But the thirdparty (client) hasn't be affected. we have therefore been modifying the name in the thirdparty... the operation causes a synchro and has modify ... the name of the company which employs our member ....

I'm not sure adding tables is relevant if we don't remove their modular assignment.

**Comment by frederic34** [comment]
add next comments on issue.

**Pull request closed without merging**
