### PR TITLE
Fix [ bug #990 ] Filter + sort does not work on order list

### PR DESCRIPTION
**Pull request by FHenry**

### CODE REVIEW

**Comment by simnandez** [comment]
You should update the ChangeLog.... ;)

**Comment by FHenry** [comment]
Into 3.4 that is not officialy released ?

**Comment by simnandez** [comment]
is a bug solved into 3.4 (still in RC)... I think that should be included in the 3.4 ChangeLog. 

Am I right, Laurent?

**Comment by eldy** [comment]
3.4 is no yet released.
What says release is done or not is "file are published onto sourceforge".

**Pull request merged**
