### PR TITLE
Contact page of task must use standard tpl too

### PR DESCRIPTION
**Pull request by defrance**

### CODE REVIEW

**Comment by eldy** [comment]
Mutualize code should be possible but currently there is a lot of difference that a re not managed by the standard tpl.

**Comment by eldy** [comment]
Mutualize code should be possible but currently there is a lot of difference that a re not managed by the standard tpl.

**Comment by defrance** [comment]
The main goal for me is to add the trigger present on bottom of contact template
I'll we show the difference beetween the old version and the template

**Comment by eldy** [comment]
An example of difference is that list of user is restricted to contact of project. Other users appears greyed with mention "Not assigned to project"

**Comment by defrance** [comment]
OK so i close this PR and create a new one who integrate the trigger

**Pull request closed without merging**
