### PR TITLE
various fixes on webservices

### PR DESCRIPTION
**Pull request by aaujon**
Add missing functionalities to webservice, such as update for invoices and various fixes (mainly adding missing fields to returned objects)

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Great! :+1: 
Would you mind writing unit tests for the methods you added?

**Comment by aaujon** [comment]
Yes sure, I will add some tests next week.

**Comment by eldy** [comment]
@aaujon Can you try to solve conflict so i can merge this into develop branch ?

**Comment by aaujon** [comment]
@eldy Yes I will solve this when I will push tests for the new methods.

**Comment by eldy** [comment]
Travis report this problem

PHP Parse error:  syntax error, unexpected '[', expecting ')' in /home/travis/build/Dolibarr/dolibarr/test/phpunit/WebservicesInvoicesTest.php on line 149
PHP Stack trace:
PHP   1. {main}() /home/travis/.phpenv/versions/5.3.29/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/.phpenv/versions/5.3.29/bin/phpunit:722
PHP   3. PHPUnit_TextUI_Command->run() phar:///home/travis/.phpenv/versions/5.3.29/bin/phpunit/phpunit/TextUI/Command.php:104
PHP   4. PHPUnit_Runner_BaseTestRunner->getTest() phar:///home/travis/.phpenv/versions/5.3.29/bin/phpunit/phpunit/TextUI/Command.php:126
PHP   5. ReflectionMethod->invoke() phar:///home/travis/.phpenv/versions/5.3.29/bin/phpunit/phpunit/Runner/BaseTestRunner.php:89
PHP   6. AllTests::suite() phar:///home/travis/.phpenv/versions/5.3.29/bin/phpunit/phpunit/Runner/BaseTestRunner.php:89

**Comment by aaujon** [comment]
@eldy The pull request is good now (failure is caused by another classe api_access.class.php)

**Pull request merged**
