### PR TITLE
NEW: It's time to remove Fax

### PR DESCRIPTION
**Pull request by aspangaro**
I think it's time to say good bye to the fax 👋

### CODE REVIEW

**Comment by atm-maxime** [comment]
Agreed, but maybe a bit hard to delete everywhere, some irreducible users might still use it...

**Comment by frederic34** [comment]
It's time to be able to add multiple phone numbers with type (fax, mobile, pers, pro etc...)

**Comment by aspangaro** [comment]
Yes @frederic34 like your social network system maybe ?

**Comment by frederic34** [comment]
Look at https://github.com/Dolibarr/dolibarr/pull/16987 and comments are welcome

**Comment by BB2A-Anthony** [comment]
Why not rename fax to phone_bis or other

And 100%  agre with @frederic34

**Comment by daraelmin** [comment]
In switzerland, faxes are still used, in particular by lawyers, trustees and administrations, because it is the only way (other than by post or personal delivery) to transmit a signed contract or mandate which has the value of proof in the event of dispute.

**Pull request closed without merging**
