### PR TITLE
NEW Can change customer on orders when hidden option COMMANDE_CHANGE_THIRDPARTY is on

### PR DESCRIPTION
**Pull request by bafbes**
add change customer function to customer orders

### CODE REVIEW

**Comment by bafbes** [comment]
I do not understand how to solve the "PR to fix or conflict to solve" label added by simnandez

**Comment by eldy** [comment]
On the fork you are working on this patch, you must make a merge of branch develop of dolibarr. This should make conlict appears. Then you must solve them, push and resubmit a new PR

**Comment by bafbes** [comment]
The branch develop is now merged and conflicts have been resolved.
Has it been done the right way ?

**Comment by eldy** [comment]
It seems to be done correctly.

**Pull request merged**
