### PR TITLE
NEW - Color line total and sub total

### PR DESCRIPTION
**Pull request by BB2A-Anthony**
# NEW|New [*Color line total and sub total*]
[*Long description*]

Color is egale to background color for the list/table title line

image

image

Default color
image

image

THEME_DARKMODEENABLED=2
image

### CODE REVIEW

**Comment by eldy** [comment]
Is it ok when using &THEME_DARKMODEENABLED=2 ?

**Comment by BB2A-Anthony** [comment]
> Is it ok when using &THEME_DARKMODEENABLED=2 ?
@eldy I'll test it, it's ok for me

**Comment by eldy** [comment]
Can you push a screenshot for result after ?

**Comment by BB2A-Anthony** [comment]
> Can you push a screenshot for result after ?

image

image

Default color
image

image

THEME_DARKMODEENABLED=2
image

**Comment by BB2A-Anthony** [comment]
@eldy up

**Pull request merged**
