### PR TITLE
try to fix the expensereport pdf

### PR DESCRIPTION
**Pull request by frederic34**
[00002.pdf](https://github.com/Dolibarr/dolibarr/files/2605947/00002.pdf)

### CODE REVIEW

**Comment by aljawaid** [comment]
@frederic34 When you say 'fix' could you kindly explain what the issues were?  The lack of the payment breakdown table and the (too early) page breaks were the only issues I could think of.

**Comment by frederic34** [comment]
@aljawaid https://www.dolibarr.fr/forum/527-bugs-sur-la-version-stable-courante/63006-note-de-frais-de-de-25-lignes-le-fichier-pdf-bug

**Comment by frederic34** [comment]
the same pdf before fix:
[00002(1).pdf](https://github.com/Dolibarr/dolibarr/files/2605982/00002.1.pdf)

**Comment by aljawaid** [comment]
@eldy @frederic34 I think this patch should be for a new pdf model.

Reason: the standard model, whilst not perfect shows the pdf using the typical 'invoice style' layout which some users may already be used to.

This revised model, shows a completely new layout with less columns.  Although this patch is better, some users may have issues with it if they have previously generated pdfs in the old style.

So I would suggest calling converting this patch into a new named pdf model for expense reports.

**Pull request merged**
