### PR TITLE
ADD civility label in fetch contact / API

### PR DESCRIPTION
**Pull request by ptibogxiv**

### CODE REVIEW

**Comment by fappels** [comment]
Why not add ->getCivilityLabel() in api class?

**Comment by eldy** [comment]
The label of civility is no more coming from table because it depends on user country.
It use a translation of langs->trans("Civility".$code)

**Comment by ptibogxiv** [comment]
@eldy the purpose of this PR is to pass the civility label in REST API as country for example.

**Comment by eldy** [comment]
Sure, but you take the value inside a field that is not used anymore.
The civility label must be generated with code

$civlitylabel = $langs->trans("Civility".$code)

**Comment by ptibogxiv** [comment]
@eldy update done ? it looks good for you ?

**Pull request merged**
