### PR TITLE
FIX : select sales representative doesn't handle tranverse mode case

### PR DESCRIPTION
**Pull request by atm-josselin**

### CODE REVIEW

**Comment by eldy** [comment]
@hregis Are you ok with this ?

**Comment by hregis** [comment]
@eldy @atm-josselin 
NO !! transverse need to use "llx_usergroup_user" table
see my PR  https://github.com/Dolibarr/dolibarr/pull/11020/files

**Comment by atm-josselin** [comment]
@hregis i agree with you, but could you do this PR in 7.0 ?

**Comment by hregis** [comment]
@eldy @atm-josselin 
i send a PR : https://github.com/Dolibarr/dolibarr/pull/11298

**Comment by atm-gauthier** [comment]
@hregis thank you, we're waiting for @eldy opinion

**Comment by eldy** [comment]
Closed replace by #11298

**Pull request closed without merging**
