### PR TITLE
Set State on mysoc global

### PR DESCRIPTION
**Pull request by tony13tv**
FIX: State not loaded when used in doctemplates

### CODE REVIEW

**Comment by eldy** [comment]
For performance reason, we don't want to have any SQL request into this method setMysoc().
So we will have to move it somewhere else.
In which use of doctemplates do you need it ?

**Comment by tony13tv** [comment]
But you already have SQL requests some lines below when getCountry() is called. I need it to replace the data in odt template.

**Comment by eldy** [comment]
> But you already have SQL requests some lines below when getCountry() is called. I need it to replace the data in odt template.

No, this is code that is not use. It is here to address very old compatibility issue, but in a recent version of Dolibarr this code is not called.

**Comment by eldy** [comment]
> But you already have SQL requests some lines below when getCountry() is called. I need it to replace the data in odt template.

No. the code that make a SQL request is dead code that is never called. It is here to adresse compatibility issues on very old version of Dolibarr (this part of code will be removed probably in a next version). On a common version, there is no SQL call in this method as it is a method to juste move data in memory (conf->global->...) into another place ($soc->...) for an easier use in rest of code.

**Pull request closed without merging**
