### PR TITLE
NEW : dev feature : replace conf filename with "conf" parameter on url b...

### PR DESCRIPTION
**Pull request by bafbes**
NEW : dev feature : replace conf filename with "conf" parameter on url by GET

### CODE REVIEW

**Comment by rdoursenaud** [comment]
Wow, this is a very dangerous feature! The input is not sanitized so it's possible to inject arbitrary code and do pretty much anything.

**Comment by braito4** [comment]
I think they had problems:
https://github.com/Dolibarr/dolibarr/commit/1598a5d3a6a27ce44d7d8d73583d07c96776fe5d
https://github.com/Dolibarr/dolibarr/commit/a8f60a5c183788d3921b309d707be59b4742e840

**Comment by rdoursenaud** [comment]
Thanks for the heads up @braito4.

It think it's better to revert this commit altogether then.

Switching the whole configuration from GET parameters sounds wrong to me anyway.

[Shameless self plug]
If it's for development purposes, you can use my git hook https://github.com/rdoursenaud/dolibarr-git-hooks to achieve this behavior when switching branches.

**Comment by bafbes** [comment]
I saw the sanitized versions. Do this still pose a security issue ?
This option is very useful as it permits to change the conf file on the fly. I use it at least ten times a day.

**Comment by rdoursenaud** [comment]
I perfectly understand your use case but it's a debug feature that should not be used in production.
Hiding it under a hidden constant like `CONF_DEBUG` would be reasonable.

**Comment by bafbes** [comment]
I do not see where to store the CONF_DEBUG constant as this functionality is called early - before loading database constants. In addition its utility is only proven in production.

I looked around in many directions and could not find any potential security risks in this situation.
Can you give an example of any potential security risks ?

**Comment by rdoursenaud** [comment]
Yes: use whatever security flaw in the uploading mechanism (these flaws are very widespread) to put a forged file on the server and then call it at runtime in the critical filefunc using your trick.
Boom, full access to running arbitrary code.
This gets even worse if Dolibarr is hosted alongside other tools (like CMS, website…) because the uploading flaw can be in any of these.
Trusting user input to dynamically call sensitive code is always a bad idea.

**Comment by bafbes** [comment]
I understand this security issue as the included file may be set intentionally to the wrong one. The case is that I can see no way to set a value for the "conf" parameter in the url line to redirect the included file to a file outside of the "conf" directory ( This directory is assumed to be secure) . Can you give an example of such a value ?

**Comment by bafbes** [comment]
I find the hook very useful. I use it to switch the databases between the development branch and the last stable tagged Dolibarr version.

**Pull request merged**
