### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by marcosgdf**
- Improved readability of function `picto_from_langcode`
- Converted indentation from spaces to tabs

### CODE REVIEW

**Comment by marcosgdf** [comment]
@hregis What about now?

I preffered to do `if (!$codelang)` as we don't need to asign a content to the variable, which means using "less" memory..

**Comment by marcosgdf** [comment]
@hregis Removed the `$codelang` test

**Comment by hregis** [comment]
shit! :-)
This pull request cannot be automatically merged.

**Comment by marcosgdf** [comment]
@hregis >,<''''

Try now, there was a conflict in functions.lib.php which I am afraid my changes got lost as the diff show 0 changes...

**Comment by marcosgdf** [comment]
@hregis Yep, my changes got lost. Wait a minute until I fix it and I'll notify you when I'm done

**Comment by marcosgdf** [comment]
@hregis Finally, try it now

**Pull request merged**
