### PR TITLE
Delete right align on multichoice . Unreadable complete menu choice

### PR DESCRIPTION
**Pull request by inoveaconseil**
Delete right align on multichoice . Unreadable complete menu choice

### CODE REVIEW

**Comment by eldy** [comment]
Can you provide a screen shot of problem before ?

**Comment by inoveaconseil** [comment]
I'ts done
capture du 2017-03-25 11-54-44

**Comment by eldy** [comment]
If you change align on right, what happen if you click on a widget completely on right ?
I think solution should be into javascript to make alignment depending on position

**Comment by fappels** [comment]
Also on 5.0, see bug report #6736.

**Comment by inoveaconseil** [comment]
Where we are a multichoicedoc on the right in Dolibarr ?
This menu appears just when we have a pdf file is linked. So I have found
this menu in the widgets and in the list of documents.
I make a mistake ?

2017-05-01 10:57 GMT+02:00 Francis Appels <notifications@github.com>:

**Pull request closed without merging**
