### PR TITLE
FIX display project tasks list columns

### PR DESCRIPTION
**Pull request by atm-steve**
Fix columns in project tasks list. Add extrafields in columns list add empty space on total line.

### CODE REVIEW

**Comment by atm-steve** [comment]
@eldy Can't fix stickler, please check the fix

**Comment by eldy** [comment]
You IDE is probably not configured with the dolibarr syntax rules.
Indentation must use tabulation instead of spaces.
Just set your IDE to use tab instead of space, at least for the dolibarr project, then open and resave the same page. The IDE should save the file correctly.

**Comment by atm-jpb** [comment]
@eldy

**Comment by atm-greg** [comment]
@eldy IDE problem solved

**Comment by john-botella** [comment]
@eldy IDE problem solved

**Pull request merged**
