### PR TITLE
Fix: #20161 Can't import thirds. Column Skype doesn't exist

### PR DESCRIPTION
**Pull request by fmarcet**
In version 15 the 'skype' column has been removed but is trying to import it

### CODE REVIEW

**Comment by hregis** [comment]
@fmarcet "skype" field or other social networks fields is deprecated, the new field is : 

` socialnetworks           text DEFAULT NULL,                           -- json with socialnetworks`

use with "llx_c_socialnetworks" dictionnary

**Comment by fmarcet** [comment]
Hi @hregis, yes I know. But it was still in the list of fields to import in the third parties, so it was impossible to import third parties because the skype column does not exist.

**Comment by hregis** [comment]
@fmarcet this field is no longer created on new installations

**Comment by aspangaro** [comment]
#20161

**Pull request merged**
