### PR TITLE
FIX: use the currency for propal signature page

### PR DESCRIPTION
**Pull request by Slordef**
# FIX Signature of propal now use the propal currency

From a client point of view, it is more pleasant to have the currency of the proposal which automatically comes from the client's currency during creation.

Of course, even if we do not activate "multicurrency" in the modules, the `multicurrency_code` and `multicurrency_total_ttc` fields are correctly used

### CODE REVIEW

**Comment by eldy** [comment]
I think we should show both when object is multicurrency object.
The main currency (because this is the value that will be requested at the bank and used into accountancy). And if the proposal is mutlicurrency, we show the amount in parenthesis. For example
Amount:   30 €    ($28)
Can you enhance in this direction ?

**Comment by Slordef** [comment]
@eldy sounds good

**Comment by Slordef** [comment]
@eldy After discuss with @Amael-PE 
We came to the conclusion that it is still preferable to only show the customer's currency since it is only him who will have this document.
As for the accounting data, that's another part.

Should we ?

**Comment by Amael-PE** [comment]
Hey here,
Indeed, our use case is the following: Albert is working in a large French company and can accept/sign up to 5000€.

- I sell Albert a service S, whose price is 3000 CHF. As Albert is in France, I offer 3100 €
- Once th offer is done I want to send the link to sign to Albert... But I need him to see the 3100 €, cause he is French and doesn't care about our Swiss prices.

If we show a CHF price (main currency), I will only confuse Albert. He will go to the management etc and it will only make thnigs longer... Better send an email then

I hope our use case is clear !
An thanks for the amazing work on Dolibarr !

**Pull request merged**
