### PR TITLE
T937 I've removed the fields/lines which are empty in the company detail

### PR DESCRIPTION
**Pull request by PaulPoulain**
https://doliforge.org/plugins/tracker/?aid=937

### CODE REVIEW

**Comment by marcosgdf** [comment]
I don't think this is OK :confused:

**Comment by PaulPoulain** [comment]
Hi Marcos,

could you please explain what is not OK : the patch does not apply ? it does not work as expected ? you don't like the feature ?

**Comment by marcosgdf** [comment]
I don't think the feature would be appropiate for Dolibarr. I mean, some fields are very important and, from my point of view, should not be hidden even if they are not set. Also, you are bypassing if a module is enabled or not, you are just evaluating if it is empty or not. And I didn't know that societe.class variables are now config variables ¿?

**Comment by PaulPoulain** [comment]
OK, the commit message is unclear : the removal is made only when DISPLAYING the company, if they are empty.
It mean:
- if you enter something in "country", it will be displayed. If there's nothing the line will be hidden in display
- in the form itself, you always get all fields

The idea behind this is to have more space on the screen and see contacts,... (that are below the "client" informations)

**Comment by marcosgdf** [comment]
I already understood what you meant, but some fields are so important because of Thirds nature that, from my point of view, should not be hidden.

But the last word belongs to @eldy

**Comment by eldy** [comment]
There is a lot of need that differs. Some want fields, some want other. I think discussion on wich field is required and not is a lost of time, there is too many point of views.
The only good solution I see is adding a new architecture to allow user to choose wich field to have into list. I am working on this for 3.5.
Before that, i suffest to keep everything as it is for the moment.

**Pull request closed without merging**
