### PR TITLE
fix:Handle constant MAIN_SHOW_SOCIETE2EXTERN in invoice payment card

### PR DESCRIPTION
**Pull request by bafbes**
fix:Handle constant MAIN_SHOW_SOCIETE2EXTERN in invoice payment card

### CODE REVIEW

**Comment by eldy** [comment]
Const must now use the final name MAIN_EXTERNAL_USERS_CAN_ALSO_SEE_SUBSIDIARIES_COMPANIES

**Comment by bafbes** [comment]
MAIN_EXTERNAL_USERS_CAN_SEE_SUBSIDIARY_COMPANIES

**Comment by eldy** [comment]
It seems the function MAIN_EXTERNAL_USERS_CAN_SEE_SUBSIDIARY_COMPANIES does not allow to see subsidiary companies, but ALL companies by disabling the test
if ($user->socid) $socid = $user->socid;
If goal is to see all companies, it means the user must be an internal user instead of external user.

**Comment by bafbes** [comment]
The primary goal was not to see subsidiary companies only but all companies. 
I think it's better to have this option giving access to all companies than not having any possibility for external users to access other companies than theirs.

**Comment by eldy** [comment]
There is already an option to allow a user to see all companies. This option is called "Type of user" :
internal user = see all companies
external user = see only its own company
This is the only difference between internal / external.

**Comment by bafbes** [comment]
No. The primary difference between an internal and an external user is that an internal user belongs to the company associated to our Dolibarr installation, while external users are contacts of our third-parties to whom we decided to give access to our Dolibarr and for wihch we have forbidden any access to any data of other third-parties.

The question is to provide an option to allow external users to access this data,or at least to the data of the third-parties subordinates of their company.

**Comment by eldy** [comment]
> No. The primary difference between an internal and an external user is that an internal user belongs to the company associated to our Dolibarr installation, while external users are contacts of our third-parties to whom we decided to give access to our Dolibarr and for wihch we have forbidden any access to any data of other third-parties.
> 
> The question is to provide an option to allow external users to access this data,or at least to the data of the third-parties subordinates of their company.

This is your definition. But this is not the definition of dolibarr specification. For Dolibarr, an internal user is not necessarily a user that is inside the company. It is a user that has a view that is not restricted to himself. That's all.
So i confirm the option to allow an external user to see other companies already exists. Don't take into consideration the "label of the field". Imagine this label is "User no restricted to himself". If a partner need a large view of companies, it is an "internal partner", even if it is another company. This is why it was called "internal user" but "Internal users" are also designed for external companies.

**Comment by bafbes** [comment]
In the table llx_user in wich users are stored, the field fk_soc contains the id of thirdparty to wich the external user belongs and is empty for internal users. Is that wrong ?

**Comment by eldy** [comment]
Yes.
Because, for user with an "internal view", we want to provide a large view on the data for the user, we don't need to store the company the view is limited to. So this id is empty.

**Comment by bafbes** [comment]
So, instead of seeing a user having the fk_soc field linked to a third party as a user belonging to this third party, we should rather see him as a user who has a vision limited to this third party only.
I admit that I could not undersrtand this concept just by reading the code. 
Thanks.

**Comment by eldy** [comment]
Even if this PR goal is to fix a bug, it seems it introduces more problems than it solves, so request is closed.

**Pull request closed without merging**
