### PR TITLE
NEW Add entity field in llx_societe_remise_except and llx_societe_remise

### PR DESCRIPTION
**Pull request by hregis**
useful when third-sharing is used with multicompany module

### CODE REVIEW

**Comment by hregis** [comment]
@simnandez @eldy 
i'ts possible to merge for 4.0 and not 4.1 ?

**Comment by eldy** [comment]
Did you share discount and not thirdparties ? I don't think so. Sharing is still on thirdparties, isn't it ?
So why introducing a field into table of discounts. All discounts are linked to a thirdparty and entity field is already present into thirdparty, so why don't you use this field (with inner join on thirdparty table), that already contains the correct data instead of creating duplicated information ?

**Comment by hregis** [comment]
@eldy When sharing client file between multiple entities we do not share the discounts. Each entity has its own discounts to a third party. You see ?

**Comment by hregis** [comment]
@eldy ping ? pong ?

**Comment by eldy** [comment]
Ok, i understand. Can you fix conflict ?

**Comment by hregis** [comment]
@eldy  ready thanks

**Pull request merged**
