### PR TITLE
FIX: It doesn't check if there is enough stock to update the lines of orders/invoices

### PR DESCRIPTION
**Pull request by fmarcet**

### CODE REVIEW

**Comment by eldy** [comment]
It seems there is a lot of other bugs with this feature. Let's work on sanitizing this.
First what is goal of option STOCK_MUST_BE_ENOUGH_FOR_xxx ?

1) Currently code works on addline or updateline (when not forgot) and sometimes only if object is draft, sometime only when object is not draft. Not clear. Also addline and updateline are low level function and not business events. Having such control here is a bad thing. It will break a lot of feature (for exemple build a specimen pdf.

2) What is goal:
- Disallow to build a draft object by an error when adding line from gui.
  or
- Disallow to validate an object ?

To  resolve all problems, i think we must:

1) Consider this feature as not working at all.
2) Move all checks STOCK_MUST_BE_ENOUGH_FOR_xxx into a trigger file dedicated to the module Stock and triggered on "validate" only (validate order, validate invoice, validate shipment, ...). This is a "business test" so being moved into a trigger is a good place.
Showing warning when building draft is already done into combo list of product (where remain stock is already visible).

Are you ok to move code like explained into develop branch ?

**Comment by BebZ** [comment]
I think it is ok for us, working on manual shipping and manual ventilation of suppliers reception, the step "on validation of shipment" is more adapted to our workflow.
First the salesman inputs the order, no matter of the stock, the purchaser resplenish the stock, the warehouse guy receives and ships the products ;)

**Comment by fmarcet** [comment]
Yes, I also think it's better to make checks at the time of validation. I start with it for inclusion in the develop branch.

**Comment by eldy** [comment]
I manually added fix on check of good warehouse.
For other change, i will keep the option as described into setup page "check when ADDING line". This is a stupi option, but for consistency of behaviour, i will keep this as it is until new options, 
STOCK_MUST_BE_ENOUGH_FOR_XXX_TO_VALIDATE
is available to replace old one that will be the hidden.

**Pull request closed without merging**
