### PR TITLE
Add Extrafields for Supplier invoice lines

### PR DESCRIPTION
**Pull request by aschio**
I added extrafields features for supplier invoice lines. I created 2 new files in install directory with sql code. I didn't create file sql to migrate from 3.6.0 because i think that file will be updated by developer  that will merge this code. 
Third commit add extrafields on supplier invoice head.
It's my first Dolibarr pull request, so let me know what I wrong

### CODE REVIEW

**Comment by aschio** [comment]
After some mails with Florian, I closed this pull request.

**Comment by BebZ** [comment]
does it mean it won't be integrated ?
Or because you didn't respect enough coding style of Dolibarr ?

**Comment by aschio** [comment]
I did some mistakes with dolibarr branch. So, I will do a new pull request on correct develop branch. Please, do not consider this pull request.

**Comment by BebZ** [comment]
cool ;) did you notice there was already a merged content here for spplier orders extrafields ? 
https://github.com/Dolibarr/dolibarr/pull/1353

**Pull request closed without merging**
