### PR TITLE
NEW Add subtotal for all types of linked objects and sort them by rowid (…

### PR DESCRIPTION
**Pull request by samifilali**
# Fix
Add subtotal for all types of linked objects and sort them by rowid (creation date)

### CODE REVIEW

**Comment by eldy** [comment]
What is goal of adding a total when there is only 1 line ?

**Comment by samifilali** [comment]
> What is goal of adding a total when there is only 1 line ?

I think it's cleaner to separate the different types of related objects when many are alone, logically and especially visually.

**Comment by eldy** [comment]
The most common case is when there is only 1 line so with no need of subtotal. So it means we duplicate all lines with a subtotal just for tha rare case there is 2 lines of same type.
This create a visual load.
If separation between types an subtotal when there is is not clear, we should solve this with css for this rare case ( for example by adding a bolder separator line), instead of overloading screen for most common case.

**Comment by samifilali** [comment]
I understand but in this case, should we apply the css on the <tr> tags and add a collapse attribute to the table, apply the css on each td tag or something else ?

**Comment by atm-thibaultf** [comment]
@eldy

**Comment by eldy** [comment]
> I understand but in this case, should we apply the css on the <tr> tags and add a collapse attribute to the table, apply the css on each td tag or something else ?
> 
> 

Using js to allow collapse can also be an interesting feature.
But my understanding here is that you want to show a total line, even when there is only 1 line. Am i right ? If yes, as this looks strange, i suggest first to add a hidden const to implement this behaviour so we won't loos time in pro or cons of this new behaviour, both are better and worse..

**Comment by eldy** [comment]
Can you push this PR on develop branch.

**Comment by samifilali** [comment]
cf. https://github.com/Dolibarr/dolibarr/pull/26566

**Pull request closed without merging**
