### PR TITLE
NEW Date shipment from order accepts hours

### PR DESCRIPTION
**Pull request by ptibogxiv**
better for local pickup collection with date and hour from order

### CODE REVIEW

**Comment by eldy** [comment]
If you modify migration script, you must also modify the file into mysql/tables
Also in develop now, the migration script is 12 to 13

**Comment by ptibogxiv** [comment]
> If you modify migration script, you must also modify the file into mysql/tables
> Also in develop now, the migration script is 12 to 13

@eldy with covid-19  merge it in v13 it's very late  end of 2020 (planned shipment or local pick up become to really need for next 18 months).

shipment card already support shipmentdate with hour so it's more a fix that enhancement
it's not good to push planned shipment date from order without hour to a planned shipment date with hour. field must be the same !

**Comment by eldy** [comment]
Sorry, the beta is already too much advanced and too many developers have already validated the non regression modules to introduce a change into how data are stored into database

**Comment by ptibogxiv** [comment]
@eldy  so i updated this PR for v13

**Pull request merged**
