### PR TITLE
FIX no empty value in required extrafield

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
FIX no empty value in required extrafield
- avoid to have empty value in required extra field

### CODE REVIEW

**Comment by eldy** [comment]
This introduced some troubles in the past before using 0. 
Can you describe how to reproduce the bug ?
Did you follow the tooltip when entering the select that say "La liste doit être de la forme clef,valeur (où la clé ne peut être '0')"

**Comment by lvessiller-opendsi** [comment]
@eldy 
If in the dictionnary it begins with 1 or not uses "0" as id (like in "c_typent" dictionnary), the select for "sellist" extra field show an empty value for key "0". So, even if it's a required extra field when you post this field you have no error message. Effectively, "0" is not considered as empty value for "sellist".

For example, you had this "sellist" extra field :

image

This extra field is required but if you create a new company with an empty value, it's not forbidden with no error message.

image

And in the card the extra field is empty (even if it was required).

image

**Comment by lvessiller-opendsi** [comment]
Result in company card :

image

**Comment by lvessiller-opendsi** [comment]
@eldy 
Is there something wrong with this fix  ?
Do you understand my example ?

**Comment by eldy** [comment]
I think the fix should not be done in the function that test if field is empty or not.
If type is "selectlist", value '0' must be considered as an empty key (according to rule visible into setup).

I don't remember what's wrong when using not defined key into select list for the empty field. I think it was related to javascript and when using beautifier like select2. So what do you think of fixing by changing the method that check field instead of changing the formatting of the choice ?

**Comment by lvessiller-opendsi** [comment]
@eldy
There  is a problem if I try to check required values after submiting form (in "setOptionalsFromPost" method). If "0" is considered as empty, when we add an "sellist" extrafield that uses "0" with a label (not empty), we have "field required" error.

For example, if we add "CompanyType" sellist like below : 

image

In this case in select list output we have a "-" label for "0" value.
But it's considered as empty.

image

image


Do you think it can be appropriate ?

**Comment by lvessiller-opendsi** [comment]
@eldy 
I don't know how to resolve this problem after submiting form.
Have you any suggestion ?

**Comment by eldy** [comment]
I did not succeed in finding why we got troubles with forbidding '0' for sellist. So I validated the PR and we will see if problem goes back...

**Pull request merged**
