### PR TITLE
FIX: restore good retrieve of bank id

### PR DESCRIPTION
**Pull request by altairis-tof**

### CODE REVIEW

**Comment by frederic34** [comment]
in develop

``` php
if (! empty($object->fk_account) || ! empty($object->fk_bank) || ! empty($conf->global->FACTURE_RIB_NUMBER))
{
$bankid=empty($object->fk_account)?$conf->global->FACTURE_RIB_NUMBER:$object->fk_account);
if (! empty($object->fk_bank)) $bankid=$object->fk_bank;   // For backward compatibility when object->fk_account is forced with object->fk_bank
```

**Comment by altairis-tof** [comment]
maybe but in 3.7 it should be fk_bank as it is set in facture.php (even in develop branch...)
<code>
        if (GETPOST('fk_bank')) { // this field may come from an external module
            $object->fk_bank = GETPOST('fk_bank');
        } else {
            $object->fk_bank = $object->fk_account;
        }
</code>

**Comment by eldy** [comment]
I tested with 3.7 and bank account is correctly provided to ->fk_acount and correctly output by crabe template.
Can you describe more precisely how to reproduce the bug ?

**Comment by altairis-tof** [comment]
as stated above, the facture.php script set fk_bank with GETPOST('fk_bank') if set either fk_account, so fk_bank should the variable used in crabe model. The goal of this is to allow external module to set fk_bank; i think you did it to be used with your select_bank module. I've just migrate a customer to 3.7 with your select_bank module and it's then that i realized the problem.

**Comment by eldy** [comment]
Sorry, i still can't reproduce any bug.
Can you describe step to reproduce the bug ?

**Comment by eldy** [comment]
Closed too old PR with no answer

**Pull request closed without merging**
