### PR TITLE
Task # 1016 : deposits numbering

### PR DESCRIPTION
**Pull request by atm-maxime**

### CODE REVIEW

**Comment by simnandez** [comment]
The Task # 1005 define specific numbering for remplacement invoices (spanish invoicing law). I make a new numbering module called mars for it and I think it's better expand mars with numbering for deposit and leave from terre....
I must also make a new numbering module with user selection numbering (standard, remplacement, etc).....

**Comment by atm-maxime** [comment]
Thanks Juanjo for this informations. I'll test your mars numbering module, but it's not active yet in my installation. Do I have to set my company country to ES to see it ?
I'll revert what I have done on standard terre numbering module but keep it on mercure where it can be defined by the user. What do you think ?

**Comment by simnandez** [comment]
I'm working with this (task 1005), I expected to finish it next week, is not finished and it has bugs... 
Is not necessary set company to ES. 

Yes keep it on mercure, I will add into mercure also the remplacement invoices.

**Comment by simnandez** [comment]
Someone has renamed mars to mars-es_ES.  I will reverse it

**Comment by eldy** [comment]
For numbering for replacement invoice, it will be better to include it into already existing template. If not defined, mask used is mask of standard invoice.
However, we should not have mask for proformat invoice becasue a proforma invoice is NOT an invoice but an order with a label "proforma invoice" on it. Saving proforma invoice as invoice, make accountancy not legal for most european users, that why we should not see this option for most users.

**Comment by simnandez** [comment]
Ok, we could create a order document model for the proforma invoice (with the label, etc)?

**Comment by eldy** [comment]
I think we can.

**Pull request merged**
