### PR TITLE
Fix : missing user object when dol_check_secure_access_document() function called

### PR DESCRIPTION
**Pull request by jfefe**

### CODE REVIEW

**Comment by eldy** [comment]
The patch should not overwrite user. 

The correct way to fix is not to do user=fuser but fuser=user (so replace $user into all tests with $fuser) and do 

if (! is_object($fuser)) $fuser=$user

**Comment by jfefe** [comment]
It would not be better to put $user parameter in each function call?

**Comment by eldy** [comment]
Each function, no (we will overload code with params). Only function that need to track user (so that may need to receive a specific different user) need it as parameter (so all crud function is yes + some other but not all).

PS: Can you resubmit your PR with correct fix:
"The correct way to fix is not to do user=fuser but fuser=user (so replace $user into all tests with $fuser) and do
if (! is_object($fuser)) $fuser=$user"

We will release 3.4 in few days and it will be good to have all bugs fixed.

**Comment by eldy** [comment]
I think fix was done into 3.4 so included into dev during merge. So i close request.

**Pull request closed without merging**
