### PR TITLE
Accountancy + Templates Month/Year relative + Api Supplier

### PR DESCRIPTION
**Pull request by PMickael**

### CODE REVIEW

**Comment by eldy** [comment]
Can you describe the goal of PR in PR title (or description if too short)

**Comment by PMickael** [comment]
All informations are in commit 

350a15a2c2 [Api][Supplier] Implement Payments
ab79eed6ea [ListOfTemplates] Add relative to month/year total
8adc2a5a0d [Accountancy] Directly show supplier invoice files popup in listing + Autoswitch to the next account when one is select with enter or tab

Use rebase and merge to merge this, it will be cleaner than a lot of merge commit

**Comment by eldy** [comment]
To ba validated, we must have 1 PR per feature or fix.
Can you split this PR in 3 (one for each topic) ?

**Comment by PMickael** [comment]
Does not make any sense to ask to split this, If your not ok with a part of it, say why, or just merge what it's needed

**Comment by eldy** [comment]
As explained, you PR contains 3 PR (3 new features).
To allow a PR to be discussed by other, corrected, tested, it must includes 1 and only 1 feature.

**Comment by PMickael** [comment]
I lose too much time to try to make you understand or be open-minded about how to treat an open source projet, never get any response : #10054, I keep all the upgrade I made for me then, a lot of core function was actually not working properly (check, tva, accountancy, loan, salaries, etc...) and was not update since more than 1year (my first attempt to to discuss) I fix most of them...

**Pull request closed without merging**
