### PR TITLE
FIX keep hidden optionals values in form not to reset extra field

### PR DESCRIPTION
**Pull request by lvessiller-opendsi**
FIX keep hidden optionals values in form not to reset extra field

**To reproduce**
- create an extrafield on proposal line and set visibility as 0
- create a new proposal
- add a line and set the hidden extrafield to a non empty value (such as 5)
- edit the line and save it
So the extrafield is updated and is set now to NULL

**Fix**
This fix add a hidden input field in the form on edit mode and so the optional value is kept and not reset to NULL in the database.

### CODE REVIEW

**Comment by eldy** [comment]
Don't understand your process to reproduce you say:
To reproduce

- create an extrafield on proposal line and set visibility as 0
- create a new proposal
- add a line and set the hidden extrafield to a non empty value (such as 5)
=> But if visibility is 0, you can't set value. Did i miss something ?

**Comment by lvessiller-opendsi** [comment]
> Don't understand your process to reproduce you say: To reproduce
> 
> * create an extrafield on proposal line and set visibility as 0
> * create a new proposal
> * add a line and set the hidden extrafield to a non empty value (such as 5)
>   => But if visibility is 0, you can't set value. Did i miss something ?

Sorry, I didn't explain all.
The extra field is set by an external module using a trigger on create.
But when the user wants to modify one line, the value of the extra field is reset to NULL, but I want to keep the value set in database.

**Comment by priojk** [comment]
This seems to be the same issue, raised by @glu000, with a detailed description of how to reproduce the problem: #29353

**Comment by eldy** [comment]
#29353 seems different in a sense it is on "boolean" option that is managed differently than other fields.
@lvessiller-opendsi i did a test into v20 with an extrafields of type varchar, and i do not experience the trouble. The extrafields with visilibility 0 is not lost when editing a proposal line in v20.
Is your problem only on boolean fields ? or only in v18 ?

**Comment by lvessiller-opendsi** [comment]
@eldy
You're right, it wasn't the origin of this trouble.
It was due to an external module.

**Pull request closed without merging**
