### PR TITLE
Update accountancy.lang

### PR DESCRIPTION
**Pull request by philazerty**
Correction de quelques fautes sur la traduction française

### CODE REVIEW

**Comment by aspangaro** [comment]
Update in transifex. Thanks Philippe

**Comment by eldy** [comment]
PR for translation other than en_US are useless, they will be overwritten with transifex translations

**Comment by philazerty** [comment]
If someone has two minutes to explain how transifex works I will do them there. A number of them are missing.

**Comment by braito4** [comment]
https://wiki.dolibarr.org/index.php/Translator_documentation

**Pull request closed without merging**
