### PR TITLE
New: Improved forced install process

### PR DESCRIPTION
**Pull request by rdoursenaud**
Tamper proofed the process by not relying on POST values for forced fields.
Disabled all fields set when $force_install_noedit is set.
Added a full-featured forced install config file template.

On the side:
Improved Dolibarr root and url detection.
Prevent install locking if install was not successful.
Added missing translation on failed administrator creation.
Better escaping of posted values.

### CODE REVIEW

**Comment by rdoursenaud** [comment]
This is a first step to try and make Dolibarr installable from the CLI with just one configuration file.
Upon completion, this should also allow us to automate testing the install process with Travis ;)

**Comment by eldy** [comment]
For part 
Disabled all fields set when $force_install_noedit is set.
What about if force_install_noedit is set but the value is not provided into the forced file. Goal of option is to lock if defined but not if not defined.

Also "Improved Dolibarr root and url detection." is a very sensitive part. Each change create a lot of regression, depending on web server, setup of server, os, etc... So can you push such change into isolated and separated PR ?

**Comment by rdoursenaud** [comment]
Sorry for the very late reply, I've been quite busy ;)

Upon looking at the code, I also check if the corresponding value is set in the forced file alongside `$force_install_noedit` before setting the field `disabled`, so I believe I already do what you're asking for.

On the root and url detection, the main improvement is that I factored it in a library so we're certain they are maintained in a central place and the same code is used in all install processes.
One minor code change is that I relied on PHP native path parsing functions rather than fragile regular expressions but the code is totally equivalent. Just more robust.
This is very easily auditable since everything is now in a single file (`htdocs/install/inc.php`).

I'm very confident there is zero regression and just rebased upon current develop, so please reconsider merging as a whole.

Thanks.

**Comment by eldy** [comment]
Hi @rdoursenaud 
Branch develop is now opened for merging majors changes. I would like to introduce this PR. Can you solve conflict on develop ?

**Comment by rdoursenaud** [comment]
Thanks @eldy.
Rebased against current develop.
Should be mergeable now.

**Pull request merged**
