### PR TITLE
New Module MultiSMTP Allows users to configure an email account

### PR DESCRIPTION
**Pull request by aspangaro**
A great thanks to @marcosgdf for our work

### CODE REVIEW

**Comment by marcosgdf** [comment]
As the author of the module, I am really surprised to see that my code is going to be incorporated in the core of the project. I have not been contacted by the author of the PR to request for authorisation or to declare the intentions to do it. As I already told the author of the PR, I am not comfortable with my code being incorporated in Dolibarr.

**Comment by aspangaro** [comment]
Hello @marcosgdf 

Nicolas Zabouri from @inoveaconseil has been trying to reach you for two months regarding the multismtp and importorderlines modules on different networks (email, skype, LinkedIn,...). Without any answer from you, we had agreed within the association to proceed to the integration of your modules which are very much used.

If you don't want to integrate them, I withdraw my pull request.

Sorry for the inconvenience but it would be a pity.

Have a nice day.

**Comment by eldy** [comment]
This is a good case to remind on how opensource works : When you publish code for Dolibarr, like for a module, it is GPL (because a module is a derivative work of Dolibarr that is GPL), and as the license say, it means, when you publish it, that you already agree that your code may be reused, modified in any project (like Dolibarr but any other project). This is for the license. However, I agree that a good practice is still to ask and wait a little time before doing it (even if this should be useless since using GPL license is already an answer to say "yes you can"). That's why we never included a module in core without agreement of initial authors of module.

This is why, when you publish a module on Dolistore, there is a remind of this saying 
"...According to Dolibarr license and terms of use of Dolistore, your module is licensed on an OpenSource license. This means your work may be modified, reuse and redistribute by anybody, including by Dolibarr core team to include it into official version..."

My question for the feature is however : What is the interest of this module? The use of n smtp account is generally a lack of knowledge of how a SMTP server should works or how a SMTP server should be setup for multiple users, and is a bad practice, especially in terms of security (but also from a functional point of view). Normally the SMTP server is supposed to be accessed with a service account or via api key or via ip authorization rules between the erp and the server. 
For example, if you use n different smtp account for SMTP with Gmail, it is because you are not using the recommended method to use SMTP and use instead the old deprecated method (called the "less secured method" by Google). If you use the recommended method (using the smtp-relay.gmail.com instead of using smtp.gmail.com with a user account), you should not need to have 1 SMTP account per user. This is just an example, but you should find more with most email providers.
So usage of this module may be helpful but for very rare situation only, and i don't think it can be qualified to be in core since in 90% of cases, it is a bad practice. Keeping it as an external module for the case it is not possible to do another way seems a better choice (my opinion)

**Comment by FHenry** [comment]
@eldy for users with Google suite or office365 (payed option for organisation) they need this. As Dolibarr users aren't expert in postfix configuration.

**Comment by eldy** [comment]
@FHenry This looks strange. You should not, above all if you pay the version for organisation. The account is found from the From of email and not from the account to connect to SMTP, like do Gmail, SendGrid, and most SMTP provider, but i don't know Office365 much.

**Comment by aspangaro** [comment]
@eldy We also have the case where users use multiple domain names to reply to emails.

**Comment by philippe-opendsi** [comment]
@eldy 
I agree with you but... it's not working like that in real life. Many users doesn't have the skills to do this work properly and don't want to pay to have it properly configured because "it works"
There's probably too a lack of information and good practices tutorial about this topic wich becomes more and more complex.
Today every of our customer using gmail or office365 need the use of multismtp. We never had one who have apply good practices.

@marcosgdf I can't find your module on the dolistore. Do you still maintain it ?

**Comment by eldy** [comment]
For a good setup of SMTP with gmail, there is this chapter in wiki: https://wiki.dolibarr.org/index.php/Setup_EMails#Gmail_.28with_mode_relay_of_Gmail_with_GSuite.29
I point to this page for my customers who want to use Gmail as email provider. In most cases, it is enough to have them making the correct setup.

**Comment by FHenry** [comment]
> @FHenry This looks strange. You should not, above all if you pay the version for organisation. The account is found from the From of email and not from the account to connect to SMTP, like do Gmail, SendGrid, and most SMTP provider, but i don't know Office365 much.

Your link in wiki Dolibarr is a vers good solution, I didn't know it.

**Pull request closed without merging**
