### PR TITLE
Swiftmailer

### PR DESCRIPTION
**Pull request by frederic34**
ready

### CODE REVIEW

**Comment by frederic34** [comment]
@homer8173

**Comment by homer8173** [comment]
Nice job @frederic34 
isn't it the same to use : 
_isset($this->params['sourceIp']) ? $this->params['sourceIp'] : null;_
and 
_$this->params['sourceIp']_
?
I was wondering why they choosed to write : _$this->params['sourceIp'] ?? null_

**Comment by frederic34** [comment]
@homer8173 I have modified the excludes for php-parallel-lint, it seems there are some code not recognised by php 5.4 in includes/sabre (yield, finally...)
where did you put your random_byte replacement?

**Comment by homer8173** [comment]
i made a monster, i put it in the file that was using it
It would be better to put it a lib dedicated to 5.4 support or to import a library like this one : 
https://github.com/paragonie/random_compat

**Comment by frederic34** [comment]
I walked into swiftmailer github history...

**Comment by frederic34** [comment]
@homer8173 you can test now, also do you know this webtool : https://www.mail-tester.com/

**Comment by eldy** [comment]
Is it an upgrade of Swiftmailer official lib or internal fix ?
What if we upgrade later with official lib ? Do we lose the fixes ?

**Comment by frederic34** [comment]
it' internal fix because of presence of php7 code
also i let php-parallel-lint make inspect of some includes to avoid including later libs incompatibles with php5.4

**Pull request merged**
