### PR TITLE
Fix resource delete with attached file

### LINKED ISSUE #10987: PHP Fatal error:  Uncaught Error: Call to undefined function dol_delete_dir_recursive() in resource/class/dolresource.class.php:465\nStack trace:\n#0
# Bug
We cannot delete resource when the resource has any attached file or linked file. The error we are getting is given below..........

`PHP Fatal error:  Uncaught Error: Call to undefined function dol_delete_dir_recursive() in /resource/class/dolresource.class.php:465\nStack trace:\n#0 resource/card.php(193): Dolresource->delete('59')\n#1 {main}\n   thrown in resource/class/dolresource.class.php on line 465,z`

## Environment
- **Version**: 9.0.2

## Expected and actual behavior
When we click on delete resource link. Resource should be deleted whether it has linked files or not.

## Steps to reproduce the behavior
Create a resource. Now upload a file in the resource. Now try to delete that resource will get the said error.

## Suggested implementation
Resource should be deleted whether is has any number of files attached.

### PR DESCRIPTION
**Pull request by atm-maxime**
Fix #10987

### CODE REVIEW

**Comment by alsoft10** [comment]
Hi,
    I tested it on  Dolibarr:9.0.3 and still it is not fixed. When going to delete the resource while there is an attachment. Simply Dolibarr does not let it delete. A 500 internal error is generated.

**Comment by hregis** [comment]
@alsoft10 
500 internal error is an Apache/php error
check your apache logs

**Comment by alsoft10** [comment]
`[Wed May 29 16:54:39.783913 2019] [-:error] [pid 17471:tid PHP Fatal error:  Uncaught Error: Call to undefined function dol_delete_dir_recursive() in /public_html/resource/class/dolresource.class.php:465\nStack trace:\n#0 /public_html/resource/card.php(193): Dolresource->delete('148')\n#1 {main}\n  thrown in /public_html/resource/class/dolresource.class.php on line 465, referer http://website.com/resource/card.php?id=148&action=delete`

The above error shown in apache error log file. I seems it still has error with dolibarr **dol_delete_dir_recursive()** function.

**Comment by atm-maxime** [comment]
Do your code contains the fix I made ?

**Pull request merged**
