### PR TITLE
Add new core module : REST API

### PR DESCRIPTION
**Pull request by jfefe**
Here is the new REST API for Dolibarr ERP/CRM!

### CODE REVIEW

**Comment by jfefe** [comment]
Hey @rdoursenaud do you know how pass Travis test?

**Comment by simnandez** [comment]
@jfefe : file api_access.class.php, lines 53 and 108 you have a double underscore for respective methods, if you put a single underscore, Travis will be benevolent with you ;-)

**Comment by jfefe** [comment]
Yes @simnadez but methods are provided by Restler framework. I wrote a end mail to its developer to see how we can fix it. So wait and see...

**Comment by rdoursenaud** [comment]
@jfefe if this is from the Restler framework, we don't have to push _our_ coding standards to _them_. This is rude!
What you must do is silence the errors for these specific lines with an explicit comment.
See: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file

**Comment by frederic34** [comment]
You can put the problematic file in /dev/codesniffer/ruleset.xml to exclude it.

**Comment by jfefe** [comment]
After using explicit comment as suggested by @rdoursenaud, Travis build is ok.

**Pull request merged**
